# Add/remove labels if issue matches the regex specified
OS-Linux:
    - 'OS.*Linux'
OS-Mac:
    - 'OS.*Mac'
Requestor-Player:
    - 'Gameplay as a Player'
Requestor-Modders:
    - 'Mod capability as a Modder'
Requestor-TML Maintainers:
    - 'tModLoader code as a Contributor/Maintainer'