# Add/remove labels if issue matches the regex specified

"os: linux":
    - 'OS.*Linux'
"os: macos":
    - 'OS.*macOS'
"os: windows":
    - 'OS.*Windows'

"social: steam":
    - 'Platform.*Steam'
"social: gog":
    - 'Platform.*GOG'
"social: wegame":
    - 'Platform.*WeGame'