<!-- This is a special targets file that is only to be used by TML's own project files, such as ExampleMod. -->
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <!-- Set game paths from WorkspaceInfo.targets and avoid having them overwritten by tMLMod.targets. -->
  <Import Project="src/WorkspaceInfo.targets" />
  <PropertyGroup>
		<tMLSteamPath>$(tModLoaderSteamPath)/</tMLSteamPath>
		<tMLLibraryPath>$(tMLSteamPath)Libraries</tMLLibraryPath>
  </PropertyGroup>  
  <!-- Import targets from src, do not use the destination folder in order to not create an eval-build dependency cycle. -->
  <Import Project="src/tModLoader/Terraria/release_extras/tMLMod.targets" />  

  <ItemGroup>
    <!-- unfortunately VS Goto Defintion doesn't work on pdb source paths, only direct project references -->
    <Reference Remove="$(tMLSteamPath)**/FNA.dll"/>
    <Reference Remove="$(tMLSteamPath)**/ReLogic.dll"/>
    <Reference Remove="$(tMLSteamPath)**/tModLoader.dll"/>
    <ProjectReference Include="$(MSBuildThisFileDirectory)FNA/FNA.Core.csproj" />
    <ProjectReference Include="$(MSBuildThisFileDirectory)src/tModLoader/ReLogic/ReLogic.csproj" />
    <ProjectReference Include="$(MSBuildThisFileDirectory)src/tModLoader/Terraria/Terraria.csproj" />
  </ItemGroup>
</Project>