using GeneratorTest = tModLoader.SourceGenerators.Tests.tModLoaderSourceGeneratorVerifier<tModLoader.SourceGenerators.Tests.Adapter<tModLoader.SourceGenerators.ModHandleGenerator>>.Test;

namespace tModLoader.SourceGenerators.Tests;

public class ModHandleGeneratorTests
{
	[Fact]
	public async Task EmptyModHandle()
	{
		const string CodeFile = @"
using Terraria.ModLoader;

namespace GeneratedDemo;

public sealed partial class GeneratedMod : Mod {
}
";

		const string GeneratedFile = @"// <auto-generated/>
using System.IO;
using System.Runtime.CompilerServices;

namespace GeneratedDemo;

partial class GeneratedMod {
	[CompilerGenerated]
	public override void HandlePacket(BinaryReader reader, int whoAmI) {
		byte type = reader.ReadByte();

		switch (type) {
			default:
				Logger.WarnFormat(""GeneratedMod: Unknown Packet Type: {0}"", type.ToString());
				break;
		}
	}
}
";

		await new GeneratorTest {
			TestState = {
				Sources = { CodeFile },
				GeneratedSources = {
					(typeof(Adapter<ModHandleGenerator>), "GeneratedDemo.GeneratedMod.g.cs", GeneratedFile),
				},
			},
		}.RunAsync();
	}

	[Fact]
	public async Task GeneratedModHandle()
	{
		const string CodeFile = @"
using Terraria.ModLoader;
using Terraria.ModLoader.Packets;

namespace GeneratedDemo;

public sealed partial class GeneratedMod : Mod {
}

[NetPacket(typeof(GeneratedMod))]
public partial struct GeneratedPacket {
	public readonly void HandlePacket() { }

	public void Receive(System.IO.BinaryReader reader, int sender) => throw new System.NotImplementedException();
}
";

		const string GeneratedFile_Mod = @"// <auto-generated/>
using System.IO;
using System.Runtime.CompilerServices;

namespace GeneratedDemo;

partial class GeneratedMod {
	[CompilerGenerated]
	public override void HandlePacket(BinaryReader reader, int whoAmI) {
		byte type = reader.ReadByte();

		switch (type) {
			case global::GeneratedDemo.GeneratedPacket.Id: {
				var packet = default(global::GeneratedDemo.GeneratedPacket);
				packet.Receive(reader, whoAmI);
				break;
			}
			default:
				Logger.WarnFormat(""GeneratedMod: Unknown Packet Type: {0}"", type.ToString());
				break;
		}
	}
}
";
		const string GeneratedFile_Packet = @"// <auto-generated/>
using System.Runtime.CompilerServices;

namespace GeneratedDemo;

partial struct GeneratedPacket {
	[CompilerGenerated]
	public const byte Id = 0;
}
";

		await new GeneratorTest {
			TestState = {
				Sources = { CodeFile },
				GeneratedSources = {
					(typeof(Adapter<ModHandleGenerator>), "GeneratedDemo.GeneratedMod.g.cs", GeneratedFile_Mod),
					(typeof(Adapter<ModHandleGenerator>), "GeneratedDemo.GeneratedPacket.g.cs", GeneratedFile_Packet),
				},
			},
		}.RunAsync();
	}
}
