using GeneratorTest = tModLoader.SourceGenerators.Tests.tModLoaderSourceGeneratorVerifier<tModLoader.SourceGenerators.Tests.Adapter<tModLoader.SourceGenerators.NetPacketGeneratorv2>>.Test;

namespace tModLoader.SourceGenerators.Tests;

partial class NetPacketGeneratorv2Tests
{
	[Fact]
	public async Task StructPacketWithDefaultSerializedIgnoredInt32()
	{
		const string CodeFile = @"
using Terraria.ModLoader;
using Terraria.ModLoader.Packets;

namespace GeneratedDemo;

public sealed class GeneratedMod : Mod {
}

[NetPacket(typeof(GeneratedMod))]
public partial struct GeneratedPacket {
	public int Default;

	[Serialize]
	public int Serialized;

	[Ignore]
	public int Ignored;

	public readonly void HandlePacket() {
	}
}
";

		const string GeneratedFile = @"// <auto-generated/>
using System.IO;
using System.Runtime.CompilerServices;

namespace GeneratedDemo;

partial struct GeneratedPacket {
	[CompilerGenerated]
	private void Serialize(global::Terraria.ModLoader.ModPacket writer, int toClient, int ignoreClient) {

		var encoder_Default = default(global::Terraria.ModLoader.Packets.IntEncoder);
		encoder_Default.Write(writer, Default);
		var encoder_Serialized = default(global::Terraria.ModLoader.Packets.IntEncoder);
		encoder_Serialized.Write(writer, Serialized);

	}

	[CompilerGenerated]
	private void Deserialize(BinaryReader reader, int sender) {

		var encoder_Default = default(global::Terraria.ModLoader.Packets.IntEncoder);
		Default = encoder_Default.Read(reader);
		var encoder_Serialized = default(global::Terraria.ModLoader.Packets.IntEncoder);
		Serialized = encoder_Serialized.Read(reader);

	}
}
";

		await new GeneratorTest {
			TestState = {
				Sources = { CodeFile },
				GeneratedSources = {
					(typeof(Adapter<NetPacketGeneratorv2>), "GeneratedDemo.GeneratedPacket.g.cs", GeneratedFile),
				},
			},
		}.RunAsync();
	}

	[Fact]
	public async Task StructPacketWithDefaultSerializedIgnoredInt32EncodedAsIntBit7()
	{
		const string CodeFile = @"
using Terraria.ModLoader;
using Terraria.ModLoader.Packets;

namespace GeneratedDemo;

public sealed class GeneratedMod : Mod {
}

[NetPacket(typeof(GeneratedMod))]
public partial struct GeneratedPacket {
	[EncodedAs(typeof(Int32Bit7Encoder))]
	public int Default;

	[Serialize]
	[EncodedAs(typeof(Int32Bit7Encoder))]
	public int Serialized;

	[Ignore]
	[EncodedAs(typeof(Int32Bit7Encoder))]
	public int Ignored;

	public readonly void HandlePacket() {
	}
}
";

		const string GeneratedFile = @"// <auto-generated/>
using System.IO;
using System.Runtime.CompilerServices;

namespace GeneratedDemo;

partial struct GeneratedPacket {
	[CompilerGenerated]
	private void Serialize(global::Terraria.ModLoader.ModPacket writer, int toClient, int ignoreClient) {

		var encoder_Default = default(global::Terraria.ModLoader.Packets.Int32Bit7Encoder);
		encoder_Default.Write(writer, Default);
		var encoder_Serialized = default(global::Terraria.ModLoader.Packets.Int32Bit7Encoder);
		encoder_Serialized.Write(writer, Serialized);

	}

	[CompilerGenerated]
	private void Deserialize(BinaryReader reader, int sender) {

		var encoder_Default = default(global::Terraria.ModLoader.Packets.Int32Bit7Encoder);
		Default = encoder_Default.Read(reader);
		var encoder_Serialized = default(global::Terraria.ModLoader.Packets.Int32Bit7Encoder);
		Serialized = encoder_Serialized.Read(reader);

	}
}
";

		await new GeneratorTest {
			TestState = {
				Sources = { CodeFile },
				GeneratedSources = {
					(typeof(Adapter<NetPacketGeneratorv2>), "GeneratedDemo.GeneratedPacket.g.cs", GeneratedFile),
				},
			},
		}.RunAsync();
	}

	[Fact]
	public async Task StructPacketWithDefaultSerializedIgnoredInt32EncodedAsByte()
	{
		const string CodeFile = @"
using Terraria.ModLoader;
using Terraria.ModLoader.Packets;

namespace GeneratedDemo;

public sealed class GeneratedMod : Mod {
}

[NetPacket(typeof(GeneratedMod))]
public partial struct GeneratedPacket {
	[EncodedAs(typeof(ByteEncoder))]
	public int Default;

	[Serialize]
	[EncodedAs(typeof(ByteEncoder))]
	public int Serialized;

	[Ignore]
	[EncodedAs(typeof(ByteEncoder))]
	public int Ignored;

	public readonly void HandlePacket() {
	}
}
";

		const string GeneratedFile = @"// <auto-generated/>
using System.IO;
using System.Runtime.CompilerServices;

namespace GeneratedDemo;

partial struct GeneratedPacket {
	[CompilerGenerated]
	private void Serialize(global::Terraria.ModLoader.ModPacket writer, int toClient, int ignoreClient) {

		var encoder_Default = default(global::Terraria.ModLoader.Packets.ByteEncoder);
		encoder_Default.Write(writer, (byte)Default);
		var encoder_Serialized = default(global::Terraria.ModLoader.Packets.ByteEncoder);
		encoder_Serialized.Write(writer, (byte)Serialized);

	}

	[CompilerGenerated]
	private void Deserialize(BinaryReader reader, int sender) {

		var encoder_Default = default(global::Terraria.ModLoader.Packets.ByteEncoder);
		Default = (int)encoder_Default.Read(reader);
		var encoder_Serialized = default(global::Terraria.ModLoader.Packets.ByteEncoder);
		Serialized = (int)encoder_Serialized.Read(reader);

	}
}
";

		await new GeneratorTest {
			TestState = {
				Sources = { CodeFile },
				GeneratedSources = {
					(typeof(Adapter<NetPacketGeneratorv2>), "GeneratedDemo.GeneratedPacket.g.cs", GeneratedFile),
				},
			},
		}.RunAsync();
	}

	[Fact]
	public async Task StructPacketWithDefaultSerializedIgnoredInt32EncodedAsLong()
	{
		const string CodeFile = @"
using Terraria.ModLoader;
using Terraria.ModLoader.Packets;

namespace GeneratedDemo;

public sealed class GeneratedMod : Mod {
}

[NetPacket(typeof(GeneratedMod))]
public partial struct GeneratedPacket {
	[EncodedAs(typeof(LongEncoder))]
	public int Default;

	[Serialize]
	[EncodedAs(typeof(LongEncoder))]
	public int Serialized;

	[Ignore]
	[EncodedAs(typeof(LongEncoder))]
	public int Ignored;

	public readonly void HandlePacket() {
	}
}
";

		const string GeneratedFile = @"// <auto-generated/>
using System.IO;
using System.Runtime.CompilerServices;

namespace GeneratedDemo;

partial struct GeneratedPacket {
	[CompilerGenerated]
	private void Serialize(global::Terraria.ModLoader.ModPacket writer, int toClient, int ignoreClient) {

		var encoder_Default = default(global::Terraria.ModLoader.Packets.LongEncoder);
		encoder_Default.Write(writer, (long)Default);
		var encoder_Serialized = default(global::Terraria.ModLoader.Packets.LongEncoder);
		encoder_Serialized.Write(writer, (long)Serialized);

	}

	[CompilerGenerated]
	private void Deserialize(BinaryReader reader, int sender) {

		var encoder_Default = default(global::Terraria.ModLoader.Packets.LongEncoder);
		Default = (int)encoder_Default.Read(reader);
		var encoder_Serialized = default(global::Terraria.ModLoader.Packets.LongEncoder);
		Serialized = (int)encoder_Serialized.Read(reader);

	}
}
";

		await new GeneratorTest {
			TestState = {
				Sources = { CodeFile },
				GeneratedSources = {
					(typeof(Adapter<NetPacketGeneratorv2>), "GeneratedDemo.GeneratedPacket.g.cs", GeneratedFile),
				},
			},
		}.RunAsync();
	}

	[Fact]
	public async Task StructPacketWithDefaultSerializedIgnoredInt32AutoSerializeOn()
	{
		const string CodeFile = @"
using Terraria.ModLoader;
using Terraria.ModLoader.Packets;

namespace GeneratedDemo;

public sealed class GeneratedMod : Mod {
}

[NetPacket(typeof(GeneratedMod), AutoSerialize = true)]
public partial struct GeneratedPacket {
	public int Default;

	[Serialize]
	public int Serialized;

	[Ignore]
	public int Ignored;

	public readonly void HandlePacket() {
	}
}
";

		const string GeneratedFile = @"// <auto-generated/>
using System.IO;
using System.Runtime.CompilerServices;

namespace GeneratedDemo;

partial struct GeneratedPacket {
	[CompilerGenerated]
	private void Serialize(global::Terraria.ModLoader.ModPacket writer, int toClient, int ignoreClient) {

		var encoder_Default = default(global::Terraria.ModLoader.Packets.IntEncoder);
		encoder_Default.Write(writer, Default);
		var encoder_Serialized = default(global::Terraria.ModLoader.Packets.IntEncoder);
		encoder_Serialized.Write(writer, Serialized);

	}

	[CompilerGenerated]
	private void Deserialize(BinaryReader reader, int sender) {

		var encoder_Default = default(global::Terraria.ModLoader.Packets.IntEncoder);
		Default = encoder_Default.Read(reader);
		var encoder_Serialized = default(global::Terraria.ModLoader.Packets.IntEncoder);
		Serialized = encoder_Serialized.Read(reader);

	}
}
";

		await new GeneratorTest {
			TestState = {
				Sources = { CodeFile },
				GeneratedSources = {
					(typeof(Adapter<NetPacketGeneratorv2>), "GeneratedDemo.GeneratedPacket.g.cs", GeneratedFile),
				},
			},
		}.RunAsync();
	}

	[Fact]
	public async Task StructPacketWithDefaultSerializedIgnoredInt32EncodedAsIntBit7AutoSerializeOn()
	{
		const string CodeFile = @"
using Terraria.ModLoader;
using Terraria.ModLoader.Packets;

namespace GeneratedDemo;

public sealed class GeneratedMod : Mod {
}

[NetPacket(typeof(GeneratedMod), AutoSerialize = true)]
public partial struct GeneratedPacket {
	[EncodedAs(typeof(Int32Bit7Encoder))]
	public int Default;

	[Serialize]
	[EncodedAs(typeof(Int32Bit7Encoder))]
	public int Serialized;

	[Ignore]
	[EncodedAs(typeof(Int32Bit7Encoder))]
	public int Ignored;

	public readonly void HandlePacket() {
	}
}
";

		const string GeneratedFile = @"// <auto-generated/>
using System.IO;
using System.Runtime.CompilerServices;

namespace GeneratedDemo;

partial struct GeneratedPacket {
	[CompilerGenerated]
	private void Serialize(global::Terraria.ModLoader.ModPacket writer, int toClient, int ignoreClient) {

		var encoder_Default = default(global::Terraria.ModLoader.Packets.Int32Bit7Encoder);
		encoder_Default.Write(writer, Default);
		var encoder_Serialized = default(global::Terraria.ModLoader.Packets.Int32Bit7Encoder);
		encoder_Serialized.Write(writer, Serialized);

	}

	[CompilerGenerated]
	private void Deserialize(BinaryReader reader, int sender) {

		var encoder_Default = default(global::Terraria.ModLoader.Packets.Int32Bit7Encoder);
		Default = encoder_Default.Read(reader);
		var encoder_Serialized = default(global::Terraria.ModLoader.Packets.Int32Bit7Encoder);
		Serialized = encoder_Serialized.Read(reader);

	}
}
";

		await new GeneratorTest {
			TestState = {
				Sources = { CodeFile },
				GeneratedSources = {
					(typeof(Adapter<NetPacketGeneratorv2>), "GeneratedDemo.GeneratedPacket.g.cs", GeneratedFile),
				},
			},
		}.RunAsync();
	}

	[Fact]
	public async Task StructPacketWithDefaultSerializedIgnoredInt32EncodedAsByteAutoSerializeOn()
	{
		const string CodeFile = @"
using Terraria.ModLoader;
using Terraria.ModLoader.Packets;

namespace GeneratedDemo;

public sealed class GeneratedMod : Mod {
}

[NetPacket(typeof(GeneratedMod), AutoSerialize = true)]
public partial struct GeneratedPacket {
	[EncodedAs(typeof(ByteEncoder))]
	public int Default;

	[Serialize]
	[EncodedAs(typeof(ByteEncoder))]
	public int Serialized;

	[Ignore]
	[EncodedAs(typeof(ByteEncoder))]
	public int Ignored;

	public readonly void HandlePacket() {
	}
}
";

		const string GeneratedFile = @"// <auto-generated/>
using System.IO;
using System.Runtime.CompilerServices;

namespace GeneratedDemo;

partial struct GeneratedPacket {
	[CompilerGenerated]
	private void Serialize(global::Terraria.ModLoader.ModPacket writer, int toClient, int ignoreClient) {

		var encoder_Default = default(global::Terraria.ModLoader.Packets.ByteEncoder);
		encoder_Default.Write(writer, (byte)Default);
		var encoder_Serialized = default(global::Terraria.ModLoader.Packets.ByteEncoder);
		encoder_Serialized.Write(writer, (byte)Serialized);

	}

	[CompilerGenerated]
	private void Deserialize(BinaryReader reader, int sender) {

		var encoder_Default = default(global::Terraria.ModLoader.Packets.ByteEncoder);
		Default = (int)encoder_Default.Read(reader);
		var encoder_Serialized = default(global::Terraria.ModLoader.Packets.ByteEncoder);
		Serialized = (int)encoder_Serialized.Read(reader);

	}
}
";

		await new GeneratorTest {
			TestState = {
				Sources = { CodeFile },
				GeneratedSources = {
					(typeof(Adapter<NetPacketGeneratorv2>), "GeneratedDemo.GeneratedPacket.g.cs", GeneratedFile),
				},
			},
		}.RunAsync();
	}

	[Fact]
	public async Task StructPacketWithDefaultSerializedIgnoredInt32EncodedAsLongAutoSerializeOn()
	{
		const string CodeFile = @"
using Terraria.ModLoader;
using Terraria.ModLoader.Packets;

namespace GeneratedDemo;

public sealed class GeneratedMod : Mod {
}

[NetPacket(typeof(GeneratedMod), AutoSerialize = true)]
public partial struct GeneratedPacket {
	[EncodedAs(typeof(LongEncoder))]
	public int Default;

	[Serialize]
	[EncodedAs(typeof(LongEncoder))]
	public int Serialized;

	[Ignore]
	[EncodedAs(typeof(LongEncoder))]
	public int Ignored;

	public readonly void HandlePacket() {
	}
}
";

		const string GeneratedFile = @"// <auto-generated/>
using System.IO;
using System.Runtime.CompilerServices;

namespace GeneratedDemo;

partial struct GeneratedPacket {
	[CompilerGenerated]
	private void Serialize(global::Terraria.ModLoader.ModPacket writer, int toClient, int ignoreClient) {

		var encoder_Default = default(global::Terraria.ModLoader.Packets.LongEncoder);
		encoder_Default.Write(writer, (long)Default);
		var encoder_Serialized = default(global::Terraria.ModLoader.Packets.LongEncoder);
		encoder_Serialized.Write(writer, (long)Serialized);

	}

	[CompilerGenerated]
	private void Deserialize(BinaryReader reader, int sender) {

		var encoder_Default = default(global::Terraria.ModLoader.Packets.LongEncoder);
		Default = (int)encoder_Default.Read(reader);
		var encoder_Serialized = default(global::Terraria.ModLoader.Packets.LongEncoder);
		Serialized = (int)encoder_Serialized.Read(reader);

	}
}
";

		await new GeneratorTest {
			TestState = {
				Sources = { CodeFile },
				GeneratedSources = {
					(typeof(Adapter<NetPacketGeneratorv2>), "GeneratedDemo.GeneratedPacket.g.cs", GeneratedFile),
				},
			},
		}.RunAsync();
	}

	[Fact]
	public async Task StructPacketWithDefaultSerializedIgnoredInt32AutoSerializeOff()
	{
		const string CodeFile = @"
using Terraria.ModLoader;
using Terraria.ModLoader.Packets;

namespace GeneratedDemo;

public sealed class GeneratedMod : Mod {
}

[NetPacket(typeof(GeneratedMod), AutoSerialize = false)]
public partial struct GeneratedPacket {
	public int Default;

	[Serialize]
	public int Serialized;

	[Ignore]
	public int Ignored;

	public readonly void HandlePacket() {
	}
}
";

		const string GeneratedFile = @"// <auto-generated/>
using System.IO;
using System.Runtime.CompilerServices;

namespace GeneratedDemo;

partial struct GeneratedPacket {
	[CompilerGenerated]
	private void Serialize(global::Terraria.ModLoader.ModPacket writer, int toClient, int ignoreClient) {

		var encoder_Serialized = default(global::Terraria.ModLoader.Packets.IntEncoder);
		encoder_Serialized.Write(writer, Serialized);

	}

	[CompilerGenerated]
	private void Deserialize(BinaryReader reader, int sender) {

		var encoder_Serialized = default(global::Terraria.ModLoader.Packets.IntEncoder);
		Serialized = encoder_Serialized.Read(reader);

	}
}
";

		await new GeneratorTest {
			TestState = {
				Sources = { CodeFile },
				GeneratedSources = {
					(typeof(Adapter<NetPacketGeneratorv2>), "GeneratedDemo.GeneratedPacket.g.cs", GeneratedFile),
				},
			},
		}.RunAsync();
	}

	[Fact]
	public async Task StructPacketWithDefaultSerializedIgnoredInt32EncodedAsIntBit7AutoSerializeOff()
	{
		const string CodeFile = @"
using Terraria.ModLoader;
using Terraria.ModLoader.Packets;

namespace GeneratedDemo;

public sealed class GeneratedMod : Mod {
}

[NetPacket(typeof(GeneratedMod), AutoSerialize = false)]
public partial struct GeneratedPacket {
	[EncodedAs(typeof(Int32Bit7Encoder))]
	public int Default;

	[Serialize]
	[EncodedAs(typeof(Int32Bit7Encoder))]
	public int Serialized;

	[Ignore]
	[EncodedAs(typeof(Int32Bit7Encoder))]
	public int Ignored;

	public readonly void HandlePacket() {
	}
}
";

		const string GeneratedFile = @"// <auto-generated/>
using System.IO;
using System.Runtime.CompilerServices;

namespace GeneratedDemo;

partial struct GeneratedPacket {
	[CompilerGenerated]
	private void Serialize(global::Terraria.ModLoader.ModPacket writer, int toClient, int ignoreClient) {

		var encoder_Serialized = default(global::Terraria.ModLoader.Packets.Int32Bit7Encoder);
		encoder_Serialized.Write(writer, Serialized);

	}

	[CompilerGenerated]
	private void Deserialize(BinaryReader reader, int sender) {

		var encoder_Serialized = default(global::Terraria.ModLoader.Packets.Int32Bit7Encoder);
		Serialized = encoder_Serialized.Read(reader);

	}
}
";

		await new GeneratorTest {
			TestState = {
				Sources = { CodeFile },
				GeneratedSources = {
					(typeof(Adapter<NetPacketGeneratorv2>), "GeneratedDemo.GeneratedPacket.g.cs", GeneratedFile),
				},
			},
		}.RunAsync();
	}

	[Fact]
	public async Task StructPacketWithDefaultSerializedIgnoredInt32EncodedAsByteAutoSerializeOff()
	{
		const string CodeFile = @"
using Terraria.ModLoader;
using Terraria.ModLoader.Packets;

namespace GeneratedDemo;

public sealed class GeneratedMod : Mod {
}

[NetPacket(typeof(GeneratedMod), AutoSerialize = false)]
public partial struct GeneratedPacket {
	[EncodedAs(typeof(ByteEncoder))]
	public int Default;

	[Serialize]
	[EncodedAs(typeof(ByteEncoder))]
	public int Serialized;

	[Ignore]
	[EncodedAs(typeof(ByteEncoder))]
	public int Ignored;

	public readonly void HandlePacket() {
	}
}
";

		const string GeneratedFile = @"// <auto-generated/>
using System.IO;
using System.Runtime.CompilerServices;

namespace GeneratedDemo;

partial struct GeneratedPacket {
	[CompilerGenerated]
	private void Serialize(global::Terraria.ModLoader.ModPacket writer, int toClient, int ignoreClient) {

		var encoder_Serialized = default(global::Terraria.ModLoader.Packets.ByteEncoder);
		encoder_Serialized.Write(writer, (byte)Serialized);

	}

	[CompilerGenerated]
	private void Deserialize(BinaryReader reader, int sender) {

		var encoder_Serialized = default(global::Terraria.ModLoader.Packets.ByteEncoder);
		Serialized = (int)encoder_Serialized.Read(reader);

	}
}
";

		await new GeneratorTest {
			TestState = {
				Sources = { CodeFile },
				GeneratedSources = {
					(typeof(Adapter<NetPacketGeneratorv2>), "GeneratedDemo.GeneratedPacket.g.cs", GeneratedFile),
				},
			},
		}.RunAsync();
	}

	[Fact]
	public async Task StructPacketWithDefaultSerializedIgnoredInt32EncodedAsLongAutoSerializeOff()
	{
		const string CodeFile = @"
using Terraria.ModLoader;
using Terraria.ModLoader.Packets;

namespace GeneratedDemo;

public sealed class GeneratedMod : Mod {
}

[NetPacket(typeof(GeneratedMod), AutoSerialize = false)]
public partial struct GeneratedPacket {
	[EncodedAs(typeof(LongEncoder))]
	public int Default;

	[Serialize]
	[EncodedAs(typeof(LongEncoder))]
	public int Serialized;

	[Ignore]
	[EncodedAs(typeof(LongEncoder))]
	public int Ignored;

	public readonly void HandlePacket() {
	}
}
";

		const string GeneratedFile = @"// <auto-generated/>
using System.IO;
using System.Runtime.CompilerServices;

namespace GeneratedDemo;

partial struct GeneratedPacket {
	[CompilerGenerated]
	private void Serialize(global::Terraria.ModLoader.ModPacket writer, int toClient, int ignoreClient) {

		var encoder_Serialized = default(global::Terraria.ModLoader.Packets.LongEncoder);
		encoder_Serialized.Write(writer, (long)Serialized);

	}

	[CompilerGenerated]
	private void Deserialize(BinaryReader reader, int sender) {

		var encoder_Serialized = default(global::Terraria.ModLoader.Packets.LongEncoder);
		Serialized = (int)encoder_Serialized.Read(reader);

	}
}
";

		await new GeneratorTest {
			TestState = {
				Sources = { CodeFile },
				GeneratedSources = {
					(typeof(Adapter<NetPacketGeneratorv2>), "GeneratedDemo.GeneratedPacket.g.cs", GeneratedFile),
				},
			},
		}.RunAsync();
	}
}
