using GeneratorTest = tModLoader.SourceGenerators.Tests.tModLoaderSourceGeneratorVerifier<tModLoader.SourceGenerators.Tests.Adapter<tModLoader.SourceGenerators.NetPacketGeneratorv2>>.Test;

namespace tModLoader.SourceGenerators.Tests;

partial class NetPacketGeneratorv2Tests
{
	[Fact]
	public async Task StructPacketWithDefaultSerializedIgnoredInt32EncodedAsLongGlobal()
	{
		const string CodeFile = @"
using Terraria.ModLoader;
using Terraria.ModLoader.Packets;

namespace GeneratedDemo;

public sealed class GeneratedMod : Mod {
}

[NetPacket(typeof(GeneratedMod))]
[GloballyEncodedAs(typeof(int), typeof(LongEncoder))]
public partial struct GeneratedPacket {
	public int Default { get; set; }

	[Serialize]
	public int Serialized { get; set; }

	[Ignore]
	public int Ignored { get; set; }

	public readonly void HandlePacket() {
	}
}
";

		const string GeneratedFile = @"// <auto-generated/>
using System.IO;
using System.Runtime.CompilerServices;

namespace GeneratedDemo;

partial struct GeneratedPacket {
	[CompilerGenerated]
	private void Serialize(global::Terraria.ModLoader.ModPacket writer, int toClient, int ignoreClient) {

		var encoder_Default = default(global::Terraria.ModLoader.Packets.LongEncoder);
		encoder_Default.Write(writer, (long)Default);
		var encoder_Serialized = default(global::Terraria.ModLoader.Packets.LongEncoder);
		encoder_Serialized.Write(writer, (long)Serialized);

	}

	[CompilerGenerated]
	private void Deserialize(BinaryReader reader, int sender) {

		var encoder_Default = default(global::Terraria.ModLoader.Packets.LongEncoder);
		Default = (int)encoder_Default.Read(reader);
		var encoder_Serialized = default(global::Terraria.ModLoader.Packets.LongEncoder);
		Serialized = (int)encoder_Serialized.Read(reader);

	}
}
";

		await new GeneratorTest {
			TestState = {
				Sources = { CodeFile },
				GeneratedSources = {
					(typeof(Adapter<NetPacketGeneratorv2>), "GeneratedDemo.GeneratedPacket.g.cs", GeneratedFile),
				},
			},
		}.RunAsync();
	}

	[Fact]
	public async Task StructPacketWithDefaultSerializedIgnoredInt32EncodedAsByteGlobal()
	{
		const string CodeFile = @"
using Terraria.ModLoader;
using Terraria.ModLoader.Packets;

namespace GeneratedDemo;

public sealed class GeneratedMod : Mod {
}

[NetPacket(typeof(GeneratedMod))]
[GloballyEncodedAs(typeof(int), typeof(LongEncoder))]
public partial struct GeneratedPacket {
	[EncodedAs(typeof(ByteEncoder))]
	public int Default { get; set; }

	[Serialize]
	[EncodedAs(typeof(ByteEncoder))]
	public int Serialized { get; set; }

	[Ignore]
	[EncodedAs(typeof(ByteEncoder))]
	public int Ignored { get; set; }

	public readonly void HandlePacket() {
	}
}
";

		const string GeneratedFile = @"// <auto-generated/>
using System.IO;
using System.Runtime.CompilerServices;

namespace GeneratedDemo;

partial struct GeneratedPacket {
	[CompilerGenerated]
	private void Serialize(global::Terraria.ModLoader.ModPacket writer, int toClient, int ignoreClient) {

		var encoder_Default = default(global::Terraria.ModLoader.Packets.ByteEncoder);
		encoder_Default.Write(writer, (byte)Default);
		var encoder_Serialized = default(global::Terraria.ModLoader.Packets.ByteEncoder);
		encoder_Serialized.Write(writer, (byte)Serialized);

	}

	[CompilerGenerated]
	private void Deserialize(BinaryReader reader, int sender) {

		var encoder_Default = default(global::Terraria.ModLoader.Packets.ByteEncoder);
		Default = (int)encoder_Default.Read(reader);
		var encoder_Serialized = default(global::Terraria.ModLoader.Packets.ByteEncoder);
		Serialized = (int)encoder_Serialized.Read(reader);

	}
}
";

		await new GeneratorTest {
			TestState = {
				Sources = { CodeFile },
				GeneratedSources = {
					(typeof(Adapter<NetPacketGeneratorv2>), "GeneratedDemo.GeneratedPacket.g.cs", GeneratedFile),
				},
			},
		}.RunAsync();
	}

	[Fact]
	public async Task StructPacketWithDefaultSerializedIgnoredInt32EncodedAsLongGlobalAutoSerializeOn()
	{
		const string CodeFile = @"
using Terraria.ModLoader;
using Terraria.ModLoader.Packets;

namespace GeneratedDemo;

public sealed class GeneratedMod : Mod {
}

[NetPacket(typeof(GeneratedMod), AutoSerialize = true)]
[GloballyEncodedAs(typeof(int), typeof(LongEncoder))]
public partial struct GeneratedPacket {
	public int Default { get; set; }

	[Serialize]
	public int Serialized { get; set; }

	[Ignore]
	public int Ignored { get; set; }

	public readonly void HandlePacket() {
	}
}
";

		const string GeneratedFile = @"// <auto-generated/>
using System.IO;
using System.Runtime.CompilerServices;

namespace GeneratedDemo;

partial struct GeneratedPacket {
	[CompilerGenerated]
	private void Serialize(global::Terraria.ModLoader.ModPacket writer, int toClient, int ignoreClient) {

		var encoder_Default = default(global::Terraria.ModLoader.Packets.LongEncoder);
		encoder_Default.Write(writer, (long)Default);
		var encoder_Serialized = default(global::Terraria.ModLoader.Packets.LongEncoder);
		encoder_Serialized.Write(writer, (long)Serialized);

	}

	[CompilerGenerated]
	private void Deserialize(BinaryReader reader, int sender) {

		var encoder_Default = default(global::Terraria.ModLoader.Packets.LongEncoder);
		Default = (int)encoder_Default.Read(reader);
		var encoder_Serialized = default(global::Terraria.ModLoader.Packets.LongEncoder);
		Serialized = (int)encoder_Serialized.Read(reader);

	}
}
";

		await new GeneratorTest {
			TestState = {
				Sources = { CodeFile },
				GeneratedSources = {
					(typeof(Adapter<NetPacketGeneratorv2>), "GeneratedDemo.GeneratedPacket.g.cs", GeneratedFile),
				},
			},
		}.RunAsync();
	}

	[Fact]
	public async Task StructPacketWithDefaultSerializedIgnoredInt32EncodedAsByteGlobalAutoSerializeOn()
	{
		const string CodeFile = @"
using Terraria.ModLoader;
using Terraria.ModLoader.Packets;

namespace GeneratedDemo;

public sealed class GeneratedMod : Mod {
}

[NetPacket(typeof(GeneratedMod), AutoSerialize = true)]
[GloballyEncodedAs(typeof(int), typeof(LongEncoder))]
public partial struct GeneratedPacket {
	[EncodedAs(typeof(ByteEncoder))]
	public int Default { get; set; }

	[Serialize]
	[EncodedAs(typeof(ByteEncoder))]
	public int Serialized { get; set; }

	[Ignore]
	[EncodedAs(typeof(ByteEncoder))]
	public int Ignored { get; set; }

	public readonly void HandlePacket() {
	}
}
";

		const string GeneratedFile = @"// <auto-generated/>
using System.IO;
using System.Runtime.CompilerServices;

namespace GeneratedDemo;

partial struct GeneratedPacket {
	[CompilerGenerated]
	private void Serialize(global::Terraria.ModLoader.ModPacket writer, int toClient, int ignoreClient) {

		var encoder_Default = default(global::Terraria.ModLoader.Packets.ByteEncoder);
		encoder_Default.Write(writer, (byte)Default);
		var encoder_Serialized = default(global::Terraria.ModLoader.Packets.ByteEncoder);
		encoder_Serialized.Write(writer, (byte)Serialized);

	}

	[CompilerGenerated]
	private void Deserialize(BinaryReader reader, int sender) {

		var encoder_Default = default(global::Terraria.ModLoader.Packets.ByteEncoder);
		Default = (int)encoder_Default.Read(reader);
		var encoder_Serialized = default(global::Terraria.ModLoader.Packets.ByteEncoder);
		Serialized = (int)encoder_Serialized.Read(reader);

	}
}
";

		await new GeneratorTest {
			TestState = {
				Sources = { CodeFile },
				GeneratedSources = {
					(typeof(Adapter<NetPacketGeneratorv2>), "GeneratedDemo.GeneratedPacket.g.cs", GeneratedFile),
				},
			},
		}.RunAsync();
	}

	[Fact]
	public async Task StructPacketWithDefaultSerializedIgnoredInt32EncodedAsLongGlobalAutoSerializeOff()
	{
		const string CodeFile = @"
using Terraria.ModLoader;
using Terraria.ModLoader.Packets;

namespace GeneratedDemo;

public sealed class GeneratedMod : Mod {
}

[NetPacket(typeof(GeneratedMod), AutoSerialize = false)]
[GloballyEncodedAs(typeof(int), typeof(LongEncoder))]
public partial struct GeneratedPacket {
	public int Default { get; set; }

	[Serialize]
	public int Serialized { get; set; }

	[Ignore]
	public int Ignored { get; set; }

	public readonly void HandlePacket() {
	}
}
";

		const string GeneratedFile = @"// <auto-generated/>
using System.IO;
using System.Runtime.CompilerServices;

namespace GeneratedDemo;

partial struct GeneratedPacket {
	[CompilerGenerated]
	private void Serialize(global::Terraria.ModLoader.ModPacket writer, int toClient, int ignoreClient) {

		var encoder_Serialized = default(global::Terraria.ModLoader.Packets.LongEncoder);
		encoder_Serialized.Write(writer, (long)Serialized);

	}

	[CompilerGenerated]
	private void Deserialize(BinaryReader reader, int sender) {

		var encoder_Serialized = default(global::Terraria.ModLoader.Packets.LongEncoder);
		Serialized = (int)encoder_Serialized.Read(reader);

	}
}
";

		await new GeneratorTest {
			TestState = {
				Sources = { CodeFile },
				GeneratedSources = {
					(typeof(Adapter<NetPacketGeneratorv2>), "GeneratedDemo.GeneratedPacket.g.cs", GeneratedFile),
				},
			},
		}.RunAsync();
	}

	[Fact]
	public async Task StructPacketWithDefaultSerializedIgnoredInt32EncodedAsByteGlobalAutoSerializeOff()
	{
		const string CodeFile = @"
using Terraria.ModLoader;
using Terraria.ModLoader.Packets;

namespace GeneratedDemo;

public sealed class GeneratedMod : Mod {
}

[NetPacket(typeof(GeneratedMod), AutoSerialize = false)]
[GloballyEncodedAs(typeof(int), typeof(LongEncoder))]
public partial struct GeneratedPacket {
	[EncodedAs(typeof(ByteEncoder))]
	public int Default { get; set; }

	[Serialize]
	[EncodedAs(typeof(ByteEncoder))]
	public int Serialized { get; set; }

	[Ignore]
	[EncodedAs(typeof(ByteEncoder))]
	public int Ignored { get; set; }

	public readonly void HandlePacket() {
	}
}
";

		const string GeneratedFile = @"// <auto-generated/>
using System.IO;
using System.Runtime.CompilerServices;

namespace GeneratedDemo;

partial struct GeneratedPacket {
	[CompilerGenerated]
	private void Serialize(global::Terraria.ModLoader.ModPacket writer, int toClient, int ignoreClient) {

		var encoder_Serialized = default(global::Terraria.ModLoader.Packets.ByteEncoder);
		encoder_Serialized.Write(writer, (byte)Serialized);

	}

	[CompilerGenerated]
	private void Deserialize(BinaryReader reader, int sender) {

		var encoder_Serialized = default(global::Terraria.ModLoader.Packets.ByteEncoder);
		Serialized = (int)encoder_Serialized.Read(reader);

	}
}
";

		await new GeneratorTest {
			TestState = {
				Sources = { CodeFile },
				GeneratedSources = {
					(typeof(Adapter<NetPacketGeneratorv2>), "GeneratedDemo.GeneratedPacket.g.cs", GeneratedFile),
				},
			},
		}.RunAsync();
	}
}
