using GeneratorTest = tModLoader.SourceGenerators.Tests.tModLoaderSourceGeneratorVerifier<tModLoader.SourceGenerators.Tests.Adapter<tModLoader.SourceGenerators.NetPacketGeneratorv2>>.Test;

namespace tModLoader.SourceGenerators.Tests;

partial class NetPacketGeneratorv2Tests
{
	[Fact]
	public async Task PreOnPostSerializeMethodsVoid()
	{
		const string CodeFile = @"
using Terraria.ModLoader;
using Terraria.ModLoader.Packets;
using System.IO;

namespace GeneratedDemo;

public sealed class GeneratedMod : Mod {
}

[NetPacket(typeof(GeneratedMod))]
public partial struct GeneratedPacket {
	public int Field;

	public readonly void HandlePacket() {
	}

	private readonly void PreSerialize(BinaryWriter writer, int toClient, int ignoreClient) { }
	private readonly void OnSerialize(BinaryWriter writer, int toClient, int ignoreClient) { }
	private readonly void PostSerialize(BinaryWriter writer, int toClient, int ignoreClient) { }
	private readonly void PreDeserialize(BinaryReader reader, int sender) { }
	private readonly void OnDeserialize(BinaryReader reader, int sender) { }
	private readonly void PostDeserialize(BinaryReader reader, int sender) { }

	private readonly void PreSerialize_Field(BinaryWriter writer, int toClient, int ignoreClient) { }
	private readonly void OnSerialize_Field(BinaryWriter writer, int toClient, int ignoreClient) { }
	private readonly void PostSerialize_Field(BinaryWriter writer, int toClient, int ignoreClient) { }
	private readonly void PreDeserialize_Field(BinaryReader reader, int sender) { }
	private readonly void OnDeserialize_Field(BinaryReader reader, int sender) { }
	private readonly void PostDeserialize_Field(BinaryReader reader, int sender) { }

	public void HandleForAll() => throw new System.NotImplementedException();
}
";

		const string GeneratedFile = @"// <auto-generated/>
using System.IO;
using System.Runtime.CompilerServices;

namespace GeneratedDemo;

partial struct GeneratedPacket {
	[CompilerGenerated]
	private void Serialize(global::Terraria.ModLoader.ModPacket writer, int toClient, int ignoreClient) {

		PreSerialize(writer, toClient, ignoreClient);
		OnSerialize(writer, toClient, ignoreClient);
		PreSerialize_Field(writer, toClient, ignoreClient);
		OnSerialize_Field(writer, toClient, ignoreClient);
		var encoder_Field = default(global::Terraria.ModLoader.Packets.IntEncoder);
		encoder_Field.Write(writer, Field);
		PostSerialize_Field(writer, toClient, ignoreClient);
		PostSerialize(writer, toClient, ignoreClient);

	}

	[CompilerGenerated]
	private void Deserialize(BinaryReader reader, int sender) {

		PreDeserialize(reader, sender);
		OnDeserialize(reader, sender);
		PreDeserialize_Field(reader, sender);
		OnDeserialize_Field(reader, sender);
		var encoder_Field = default(global::Terraria.ModLoader.Packets.IntEncoder);
		Field = encoder_Field.Read(reader);
		PostDeserialize_Field(reader, sender);
		PostDeserialize(reader, sender);

	}
}
";

		await new GeneratorTest {
			TestState = {
				Sources = { CodeFile },
				GeneratedSources = {
					(typeof(Adapter<NetPacketGeneratorv2>), "GeneratedDemo.GeneratedPacket.g.cs", GeneratedFile),
				},
			},
		}.RunAsync();
	}

	[Fact]
	public async Task PreOnPostSerializeMethodsBool()
	{
		const string CodeFile = @"
using Terraria.ModLoader;
using Terraria.ModLoader.Packets;
using System.IO;

namespace GeneratedDemo;

public sealed class GeneratedMod : Mod {
}

[NetPacket(typeof(GeneratedMod))]
public partial struct GeneratedPacket {
	public int Field;

	public readonly void HandlePacket() {
	}

	private readonly bool PreSerialize(BinaryWriter writer, int toClient, int ignoreClient) { return true; }
	private readonly void OnSerialize(BinaryWriter writer, int toClient, int ignoreClient) { }
	private readonly void PostSerialize(BinaryWriter writer, int toClient, int ignoreClient) { }
	private readonly bool PreDeserialize(BinaryReader reader, int sender) { return true; }
	private readonly void OnDeserialize(BinaryReader reader, int sender) { }
	private readonly void PostDeserialize(BinaryReader reader, int sender) { }

	private readonly bool PreSerialize_Field(BinaryWriter writer, int toClient, int ignoreClient) { return true; }
	private readonly void OnSerialize_Field(BinaryWriter writer, int toClient, int ignoreClient) { }
	private readonly void PostSerialize_Field(BinaryWriter writer, int toClient, int ignoreClient) { }
	private readonly bool PreDeserialize_Field(BinaryReader reader, int sender) { return true; }
	private readonly void OnDeserialize_Field(BinaryReader reader, int sender) { }
	private readonly void PostDeserialize_Field(BinaryReader reader, int sender) { }
}
";

		const string GeneratedFile = @"// <auto-generated/>
using System.IO;
using System.Runtime.CompilerServices;

namespace GeneratedDemo;

partial struct GeneratedPacket {
	[CompilerGenerated]
	private void Serialize(global::Terraria.ModLoader.ModPacket writer, int toClient, int ignoreClient) {

		if (PreSerialize(writer, toClient, ignoreClient)) {
			OnSerialize(writer, toClient, ignoreClient);
			if (PreSerialize_Field(writer, toClient, ignoreClient)) {
				OnSerialize_Field(writer, toClient, ignoreClient);
				var encoder_Field = default(global::Terraria.ModLoader.Packets.IntEncoder);
				encoder_Field.Write(writer, Field);
			}
			PostSerialize_Field(writer, toClient, ignoreClient);
		}
		PostSerialize(writer, toClient, ignoreClient);

	}

	[CompilerGenerated]
	private void Deserialize(BinaryReader reader, int sender) {

		if (PreDeserialize(reader, sender)) {
			OnDeserialize(reader, sender);
			if (PreDeserialize_Field(reader, sender)) {
				OnDeserialize_Field(reader, sender);
				var encoder_Field = default(global::Terraria.ModLoader.Packets.IntEncoder);
				Field = encoder_Field.Read(reader);
			}
			PostDeserialize_Field(reader, sender);
		}
		PostDeserialize(reader, sender);

	}
}
";

		await new GeneratorTest {
			TestState = {
				Sources = { CodeFile },
				GeneratedSources = {
					(typeof(Adapter<NetPacketGeneratorv2>), "GeneratedDemo.GeneratedPacket.g.cs", GeneratedFile),
				},
			},
		}.RunAsync();
	}
}
