var class_terraria_1_1_game_content_1_1_object_interactions_1_1_block_because_you_are_over_an_important_tile =
[
    [ "ShouldBlockSmartInteract", "class_terraria_1_1_game_content_1_1_object_interactions_1_1_block_because_you_are_over_an_important_tile.html#acf842a672cebc654c04c30dcbbbf4405", null ]
];