var class_terraria_1_1_i_d_1_1_armor_i_ds_1_1_body_1_1_sets =
[
    [ "IncludeCapeFrontAndBackInfo", "struct_terraria_1_1_i_d_1_1_armor_i_ds_1_1_body_1_1_sets_1_1_include_cape_front_and_back_info.html", "struct_terraria_1_1_i_d_1_1_armor_i_ds_1_1_body_1_1_sets_1_1_include_cape_front_and_back_info" ]
];