var class_terraria_1_1_mod_loader_1_1_config_1_1_reference_defaults_preserving_resolver =
[
    [ "ValueProviderDecorator", "class_terraria_1_1_mod_loader_1_1_config_1_1_reference_defaults_preserving_resolver_1_1_value_provider_decorator.html", "class_terraria_1_1_mod_loader_1_1_config_1_1_reference_defaults_preserving_resolver_1_1_value_provider_decorator" ],
    [ "CreateProperties", "class_terraria_1_1_mod_loader_1_1_config_1_1_reference_defaults_preserving_resolver.html#a1de9a257270cc9cd66d82632893ebfa9", null ]
];