var namespace_terraria_1_1_game_content_1_1_bestiary =
[
    [ "BestiaryDatabase", "class_terraria_1_1_game_content_1_1_bestiary_1_1_bestiary_database.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_bestiary_database" ],
    [ "BestiaryDatabaseNPCsPopulator", "class_terraria_1_1_game_content_1_1_bestiary_1_1_bestiary_database_n_p_cs_populator.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_bestiary_database_n_p_cs_populator" ],
    [ "BestiaryEntry", "class_terraria_1_1_game_content_1_1_bestiary_1_1_bestiary_entry.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_bestiary_entry" ],
    [ "BestiaryPortraitBackgroundBasedOnWorldEvilProviderPreferenceInfoElement", "class_terraria_1_1_game_content_1_1_bestiary_1_1_bestiary_portrait_background_based_on_world_evi6b5a316600e324989aec2d639e673d9d.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_bestiary_portrait_background_based_on_world_evi6b5a316600e324989aec2d639e673d9d" ],
    [ "BestiaryPortraitBackgroundProviderPreferenceInfoElement", "class_terraria_1_1_game_content_1_1_bestiary_1_1_bestiary_portrait_background_provider_preference_info_element.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_bestiary_portrait_background_provider_preference_info_element" ],
    [ "BestiaryUICollectionInfo", "struct_terraria_1_1_game_content_1_1_bestiary_1_1_bestiary_u_i_collection_info.html", "struct_terraria_1_1_game_content_1_1_bestiary_1_1_bestiary_u_i_collection_info" ],
    [ "BestiaryUnlockProgressReport", "struct_terraria_1_1_game_content_1_1_bestiary_1_1_bestiary_unlock_progress_report.html", "struct_terraria_1_1_game_content_1_1_bestiary_1_1_bestiary_unlock_progress_report" ],
    [ "BestiaryUnlocksTracker", "class_terraria_1_1_game_content_1_1_bestiary_1_1_bestiary_unlocks_tracker.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_bestiary_unlocks_tracker" ],
    [ "BossBestiaryInfoElement", "class_terraria_1_1_game_content_1_1_bestiary_1_1_boss_bestiary_info_element.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_boss_bestiary_info_element" ],
    [ "CommonEnemyUICollectionInfoProvider", "class_terraria_1_1_game_content_1_1_bestiary_1_1_common_enemy_u_i_collection_info_provider.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_common_enemy_u_i_collection_info_provider" ],
    [ "CritterUICollectionInfoProvider", "class_terraria_1_1_game_content_1_1_bestiary_1_1_critter_u_i_collection_info_provider.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_critter_u_i_collection_info_provider" ],
    [ "CustomEntryIcon", "class_terraria_1_1_game_content_1_1_bestiary_1_1_custom_entry_icon.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_custom_entry_icon" ],
    [ "EntryIconDrawSettings", "struct_terraria_1_1_game_content_1_1_bestiary_1_1_entry_icon_draw_settings.html", "struct_terraria_1_1_game_content_1_1_bestiary_1_1_entry_icon_draw_settings" ],
    [ "FilterProviderInfoElement", "class_terraria_1_1_game_content_1_1_bestiary_1_1_filter_provider_info_element.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_filter_provider_info_element" ],
    [ "Filters", "class_terraria_1_1_game_content_1_1_bestiary_1_1_filters.html", [
      [ "ByBoss", "class_terraria_1_1_game_content_1_1_bestiary_1_1_filters_1_1_by_boss.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_filters_1_1_by_boss" ],
      [ "ByInfoElement", "class_terraria_1_1_game_content_1_1_bestiary_1_1_filters_1_1_by_info_element.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_filters_1_1_by_info_element" ],
      [ "ByRareCreature", "class_terraria_1_1_game_content_1_1_bestiary_1_1_filters_1_1_by_rare_creature.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_filters_1_1_by_rare_creature" ],
      [ "BySearch", "class_terraria_1_1_game_content_1_1_bestiary_1_1_filters_1_1_by_search.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_filters_1_1_by_search" ],
      [ "ByUnlockState", "class_terraria_1_1_game_content_1_1_bestiary_1_1_filters_1_1_by_unlock_state.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_filters_1_1_by_unlock_state" ]
    ] ],
    [ "FlavorTextBestiaryInfoElement", "class_terraria_1_1_game_content_1_1_bestiary_1_1_flavor_text_bestiary_info_element.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_flavor_text_bestiary_info_element" ],
    [ "GoldCritterUICollectionInfoProvider", "class_terraria_1_1_game_content_1_1_bestiary_1_1_gold_critter_u_i_collection_info_provider.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_gold_critter_u_i_collection_info_provider" ],
    [ "HighestOfMultipleUICollectionInfoProvider", "class_terraria_1_1_game_content_1_1_bestiary_1_1_highest_of_multiple_u_i_collection_info_provider.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_highest_of_multiple_u_i_collection_info_provider" ],
    [ "IBestiaryBackgroundImagePathAndColorProvider", "interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_bestiary_background_image_path_and_color_provider.html", "interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_bestiary_background_image_path_and_color_provider" ],
    [ "IBestiaryBackgroundOverlayAndColorProvider", "interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_bestiary_background_overlay_and_color_provider.html", "interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_bestiary_background_overlay_and_color_provider" ],
    [ "IBestiaryEntryDisplayIndex", "interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_bestiary_entry_display_index.html", "interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_bestiary_entry_display_index" ],
    [ "IBestiaryEntryFilter", "interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_bestiary_entry_filter.html", "interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_bestiary_entry_filter" ],
    [ "IBestiaryInfoElement", "interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_bestiary_info_element.html", "interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_bestiary_info_element" ],
    [ "IBestiarySortStep", "interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_bestiary_sort_step.html", "interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_bestiary_sort_step" ],
    [ "IBestiaryUICollectionInfoProvider", "interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_bestiary_u_i_collection_info_provider.html", "interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_bestiary_u_i_collection_info_provider" ],
    [ "IEntryIcon", "interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_entry_icon.html", "interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_entry_icon" ],
    [ "IFilterInfoProvider", "interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_filter_info_provider.html", "interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_filter_info_provider" ],
    [ "IItemBestiaryInfoElement", "interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_item_bestiary_info_element.html", null ],
    [ "IPreferenceProviderElement", "interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_preference_provider_element.html", "interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_preference_provider_element" ],
    [ "IProvideSearchFilterString", "interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_provide_search_filter_string.html", "interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_provide_search_filter_string" ],
    [ "ItemDropBestiaryInfoElement", "class_terraria_1_1_game_content_1_1_bestiary_1_1_item_drop_bestiary_info_element.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_item_drop_bestiary_info_element" ],
    [ "ItemFromCatchingNPCBestiaryInfoElement", "class_terraria_1_1_game_content_1_1_bestiary_1_1_item_from_catching_n_p_c_bestiary_info_element.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_item_from_catching_n_p_c_bestiary_info_element" ],
    [ "ModBestiaryInfoElement", "class_terraria_1_1_game_content_1_1_bestiary_1_1_mod_bestiary_info_element.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_mod_bestiary_info_element" ],
    [ "ModBiomeBestiaryInfoElement", "class_terraria_1_1_game_content_1_1_bestiary_1_1_mod_biome_bestiary_info_element.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_mod_biome_bestiary_info_element" ],
    [ "ModSourceBestiaryInfoElement", "class_terraria_1_1_game_content_1_1_bestiary_1_1_mod_source_bestiary_info_element.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_mod_source_bestiary_info_element" ],
    [ "MoonLordPortraitBackgroundProviderBestiaryInfoElement", "class_terraria_1_1_game_content_1_1_bestiary_1_1_moon_lord_portrait_background_provider_bestiary_info_element.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_moon_lord_portrait_background_provider_bestiary_info_element" ],
    [ "NamePlateInfoElement", "class_terraria_1_1_game_content_1_1_bestiary_1_1_name_plate_info_element.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_name_plate_info_element" ],
    [ "NPCKillsTracker", "class_terraria_1_1_game_content_1_1_bestiary_1_1_n_p_c_kills_tracker.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_n_p_c_kills_tracker" ],
    [ "NPCNetIdBestiaryInfoElement", "class_terraria_1_1_game_content_1_1_bestiary_1_1_n_p_c_net_id_bestiary_info_element.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_n_p_c_net_id_bestiary_info_element" ],
    [ "NPCPortraitInfoElement", "class_terraria_1_1_game_content_1_1_bestiary_1_1_n_p_c_portrait_info_element.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_n_p_c_portrait_info_element" ],
    [ "NPCStatsReportInfoElement", "class_terraria_1_1_game_content_1_1_bestiary_1_1_n_p_c_stats_report_info_element.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_n_p_c_stats_report_info_element" ],
    [ "NPCWasChatWithTracker", "class_terraria_1_1_game_content_1_1_bestiary_1_1_n_p_c_was_chat_with_tracker.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_n_p_c_was_chat_with_tracker" ],
    [ "NPCWasNearPlayerTracker", "class_terraria_1_1_game_content_1_1_bestiary_1_1_n_p_c_was_near_player_tracker.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_n_p_c_was_near_player_tracker" ],
    [ "RareSpawnBestiaryInfoElement", "class_terraria_1_1_game_content_1_1_bestiary_1_1_rare_spawn_bestiary_info_element.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_rare_spawn_bestiary_info_element" ],
    [ "SalamanderShellyDadUICollectionInfoProvider", "class_terraria_1_1_game_content_1_1_bestiary_1_1_salamander_shelly_dad_u_i_collection_info_provider.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_salamander_shelly_dad_u_i_collection_info_provider" ],
    [ "SearchAliasInfoElement", "class_terraria_1_1_game_content_1_1_bestiary_1_1_search_alias_info_element.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_search_alias_info_element" ],
    [ "SortingSteps", "class_terraria_1_1_game_content_1_1_bestiary_1_1_sorting_steps.html", [
      [ "Alphabetical", "class_terraria_1_1_game_content_1_1_bestiary_1_1_sorting_steps_1_1_alphabetical.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_sorting_steps_1_1_alphabetical" ],
      [ "ByAttack", "class_terraria_1_1_game_content_1_1_bestiary_1_1_sorting_steps_1_1_by_attack.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_sorting_steps_1_1_by_attack" ],
      [ "ByBestiaryRarity", "class_terraria_1_1_game_content_1_1_bestiary_1_1_sorting_steps_1_1_by_bestiary_rarity.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_sorting_steps_1_1_by_bestiary_rarity" ],
      [ "ByBestiarySortingId", "class_terraria_1_1_game_content_1_1_bestiary_1_1_sorting_steps_1_1_by_bestiary_sorting_id.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_sorting_steps_1_1_by_bestiary_sorting_id" ],
      [ "ByCoins", "class_terraria_1_1_game_content_1_1_bestiary_1_1_sorting_steps_1_1_by_coins.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_sorting_steps_1_1_by_coins" ],
      [ "ByDefense", "class_terraria_1_1_game_content_1_1_bestiary_1_1_sorting_steps_1_1_by_defense.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_sorting_steps_1_1_by_defense" ],
      [ "ByHP", "class_terraria_1_1_game_content_1_1_bestiary_1_1_sorting_steps_1_1_by_h_p.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_sorting_steps_1_1_by_h_p" ],
      [ "ByNetId", "class_terraria_1_1_game_content_1_1_bestiary_1_1_sorting_steps_1_1_by_net_id.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_sorting_steps_1_1_by_net_id" ],
      [ "ByStat", "class_terraria_1_1_game_content_1_1_bestiary_1_1_sorting_steps_1_1_by_stat.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_sorting_steps_1_1_by_stat" ],
      [ "ByUnlockState", "class_terraria_1_1_game_content_1_1_bestiary_1_1_sorting_steps_1_1_by_unlock_state.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_sorting_steps_1_1_by_unlock_state" ]
    ] ],
    [ "SpawnConditionBestiaryInfoElement", "class_terraria_1_1_game_content_1_1_bestiary_1_1_spawn_condition_bestiary_info_element.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_spawn_condition_bestiary_info_element" ],
    [ "SpawnConditionBestiaryOverlayInfoElement", "class_terraria_1_1_game_content_1_1_bestiary_1_1_spawn_condition_bestiary_overlay_info_element.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_spawn_condition_bestiary_overlay_info_element" ],
    [ "SpawnConditionDecorativeOverlayInfoElement", "class_terraria_1_1_game_content_1_1_bestiary_1_1_spawn_condition_decorative_overlay_info_element.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_spawn_condition_decorative_overlay_info_element" ],
    [ "TownNPCUICollectionInfoProvider", "class_terraria_1_1_game_content_1_1_bestiary_1_1_town_n_p_c_u_i_collection_info_provider.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_town_n_p_c_u_i_collection_info_provider" ],
    [ "UnlockableNPCEntryIcon", "class_terraria_1_1_game_content_1_1_bestiary_1_1_unlockable_n_p_c_entry_icon.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_unlockable_n_p_c_entry_icon" ],
    [ "UnlockProgressDisplayBestiaryInfoElement", "class_terraria_1_1_game_content_1_1_bestiary_1_1_unlock_progress_display_bestiary_info_element.html", "class_terraria_1_1_game_content_1_1_bestiary_1_1_unlock_progress_display_bestiary_info_element" ],
    [ "BestiaryEntryUnlockState", "namespace_terraria_1_1_game_content_1_1_bestiary.html#ae2e3402c328192330104a16282a158da", [
      [ "NotKnownAtAll_0", "namespace_terraria_1_1_game_content_1_1_bestiary.html#ae2e3402c328192330104a16282a158daaf94f4251fec3cb45544a3adf567dd836", null ],
      [ "CanShowPortraitOnly_1", "namespace_terraria_1_1_game_content_1_1_bestiary.html#ae2e3402c328192330104a16282a158daa324f66239282e932f360ff4baa14c0dc", null ],
      [ "CanShowStats_2", "namespace_terraria_1_1_game_content_1_1_bestiary.html#ae2e3402c328192330104a16282a158daaac2b5e516fb284e17ef6c5fa92462a13", null ],
      [ "CanShowDropsWithoutDropRates_3", "namespace_terraria_1_1_game_content_1_1_bestiary.html#ae2e3402c328192330104a16282a158daaa05aafaf954f4e1a9d38acb43e2ced41", null ],
      [ "CanShowDropsWithDropRates_4", "namespace_terraria_1_1_game_content_1_1_bestiary.html#ae2e3402c328192330104a16282a158daaeab6ed40d8b8f5471e60c713ec421843", null ]
    ] ]
];