<Project Sdk="Microsoft.NET.Sdk">

	<!-- Import tModLoader mod properties -->
	<Import Project="C:\Program Files (x86)\Steam\steamapps\common\tModLoaderDev\tMLMod.targets" />

	<!-- General -->
	<PropertyGroup>
		
	</PropertyGroup>
	<ItemGroup>
	  <Reference Include="ItemSourceHelper">
	    <HintPath>..\ModAssemblies\ItemSourceHelper_v1.0.3.dll</HintPath>
	  </Reference>
	</ItemGroup>

	<!-- References -->

</Project>