name: Bug Report
description: Report a bug in the TML software
labels: ["Type: Bug", "NEW ISSUE"]
body:
- type: markdown
  attributes:
    value: |
      > The tModLoader software is provided "as is", without warranty of any kind, express or implied, including but not limited to the warranties of merchantability, fitness for a particular purpose and noninfringement. In no event shall the software developers be liable for any claim, damages or other liability, whether in an action of contract, tort or otherwise, arising from, out of or in connection with the software or the use or other dealings in the software.

      Please **look at the FAQ before** submitting an issue. Your issue might be well known with an easy fix. [Basic tModLoader Usage FAQ](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ) 
      Please fill out all the necessary details. 
      Please only report an issue if you are certain there's a problem with the tModLoader software.

      If you are having trouble with **a specific mod**, please report that to the mod's author, not here.

      If you are having trouble installing tModLoader, that is not suitable for the bug tracker. That is a support question, not a bug. For support questions, you should go to [Discord](http://discord.gg/tmodloader)
      Please read the pinned messages in the `#support-forum` channel beforehand.
- type: markdown
  attributes:
    value: |
      ## Is there an existing issue for this?
      Please search using the search bar on the issues page to see if an issue already exists for the bug you encountered. If there is, please add to that issue instead of making a new issue. You can also react with 👍 to prioritize and issue.
- type: dropdown
  attributes:
    label: Version
    description: What version are you running?
    multiple: false
    options:
      - Latest 1.4.4-stable
      - Latest 1.4.4-preview
      - Latest 1.4.3-legacy
      - Latest 1.3-legacy
      - Self-Compiled (please specify branch)
      - Other (please specify elsewhere)
  validations:
    required: true
- type: dropdown
  attributes:
    label: OS
    description: What OS are you on?
    multiple: false
    options:
      - Windows
      - Mac
      - Linux
  validations:
    required: true
- type: dropdown
  attributes:
    label: Platform
    description: What store did you purchase Terraria from?
    multiple: false
    options:
      - Steam
      - GOG
  validations:
    required: true
- type: dropdown
  attributes:
    label: This bug affects...
    description: In order to help understand the issue, we would like to know if this is a player-facing bug, or a modder-facing bug.
    multiple: false
    options:
      - 'Mod capability as a Modder'
      - 'Gameplay as a Player'
  validations:
    required: true        
- type: textarea
  attributes:
    label: Description
    id: description
    description: |
      Describe your issue(s) here. What is the issue?
      Please keep this as concise as possible, preferably a single line describing the issue. 
      For example: "When I press X button in menu Y, the component Z becomes unclickable"
- type: textarea
  attributes:
    label: Log File
    description: |
      Please attach the log files here. You'll find the log files in the logs folder. Look for the `client.log`, `Launch.log`, `Natives.log`, and `environment-client.log` files. If the issue relates to multiplayer post the `server.log` and `environment-sever.log` files as well.
      
      On 1.4+ versions they can be found in the "tModLoader-Logs" folder in your tModLoader [install directory](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-Guide#install) (to find your install directory on Steam right click on tModloader, then Manage and "Browse local files"). 
      
      On 1.3 it can be found in the Logs folder within the [saves folder](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-Guide#saves).
      
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
- type: textarea
  attributes:
    label: Steps to reproduce
    description: Please describe the steps to reproduce this issue.
    placeholder: |
      1. [First Step]
      2. [Second Step]
      3. [And so on...]
- type: textarea
  attributes:
    label: Expected Behavior
    description: |
      What should be happening? If you don't know, leave what you think should happen.
- type: textarea
  attributes:
    label: Actual Behavior
    description: |
      What is actually happening?
- type: textarea
  attributes:
    label: Reproduction frequency
    description: |
      How often are you reliably able to reproduce this issue?
- type: textarea
  attributes:
    label: Additional Information
    description: |
       Any additional information, configuration, or data that might be necessary to reproduce the issue.
