blank_issues_enabled: false
contact_links:
 - name: Discord Community Support
   url: https://discord.gg/tmodloader
   about: Please direct any and all help requests to here. If a help request is on GitHub, it WILL go unanswered
