Terraria ModLoader: Terraria.ModLoader.AssemblyManager.LoadedMod Class Reference
Terraria.ModLoader.AssemblyManager.LoadedMod Class Reference
Public Member Functions
void AddDependency (LoadedMod dep)
void EnableEaC ()
void LoadAssemblies ()
void SetMod (ModLoader.LoadingMod mod)
void UpdateWeakRefs ()
Public Attributes
Assembly assembly
bool CanEaC
readonly List< LoadedMod > dependencies = new List<LoadedMod>()
readonly List< LoadedMod > dependents = new List<LoadedMod>()
TmodFile modFile
string Name => modFile.name
BuildProperties properties
readonly ISet< string > weakDependencies = new HashSet<string>()
Properties
bool NeedsReload [get, set]
Private Member Functions
string DllName (string dll)
string EncapsulateName (string name)
byte [] EncapsulateReferences (byte[] code)
void SetNeedsReload ()
void SetNeedsReloadUnlessEaC ()
string WeakDepName (string depName)
Private Attributes
bool _needsReload = true
string AssemblyName => eacEnabled ? Name : Name + '_' + loadIndex
bool eacEnabled
int loadIndex
Detailed Description
Definition at line 14 of file AssemblyManager.cs.
Member Function Documentation
AddDependency()
void Terraria.ModLoader.AssemblyManager.LoadedMod.AddDependency (LoadedMod dep)
Definition at line 62 of file AssemblyManager.cs.
References Terraria.ModLoader.AssemblyManager.LoadedMod.dependents.
{
                 dependencies.Add(dep);
                 dep.dependents.Add(this);
             }
DllName()
string Terraria.ModLoader.AssemblyManager.LoadedMod.DllName (string dll) private
EnableEaC()
void Terraria.ModLoader.AssemblyManager.LoadedMod.EnableEaC ()
Definition at line 70 of file AssemblyManager.cs.
{
                 if (eacEnabled)
                     return;
                 SetNeedsReloadUnlessEaC();
                 eacEnabled = true;
                 //all dependencies need to have unmodified names
                 foreach (var dep in dependencies)
                     dep.EnableEaC();
             }
EncapsulateName()
string Terraria.ModLoader.AssemblyManager.LoadedMod.EncapsulateName (string name) private
Definition at line 129 of file AssemblyManager.cs.
References Terraria.ModLoader.AssemblyManager.LoadedMod.SetMod().
{
                 if (name == Name)
                     return AssemblyName;
                 if (properties.dllReferences.Contains(name))
                     return DllName(name);
                 if (weakDependencies.Contains(name))
                     return WeakDepName(name);
                 foreach (var dep in dependencies) {
                     var _name = dep.EncapsulateName(name);
                     if (_name != name)
                         return _name;
                 }
                 return name;
             }
EncapsulateReferences()
byte [] Terraria.ModLoader.AssemblyManager.LoadedMod.EncapsulateReferences (byte [] code) private
Definition at line 110 of file AssemblyManager.cs.
{
                 if (eacEnabled)
                     return code;
                 var asm = AssemblyDefinition.ReadAssembly(new MemoryStream(code));
                 asm.Name.Name = EncapsulateName(asm.Name.Name);
                 //randomise the module version id so that the debugger can detect it as a different module (even if it has the same content)
                 asm.MainModule.Mvid = Guid.NewGuid();
                 foreach (var mod in asm.Modules)
                     foreach (var asmRef in mod.AssemblyReferences)
                         asmRef.Name = EncapsulateName(asmRef.Name);
                 var ret = new MemoryStream();
                 asm.Write(ret);
                 return ret.ToArray();
             }
LoadAssemblies()
void Terraria.ModLoader.AssemblyManager.LoadedMod.LoadAssemblies ()
Definition at line 99 of file AssemblyManager.cs.
References Terraria.ModLoader.IO.TmodFile.GetFile(), Terraria.ModLoader.IO.TmodFile.GetMainAssembly(), and Terraria.ModLoader.IO.TmodFile.GetMainPDB().
{
                 if (!NeedsReload)
                     return;
                 foreach (var dll in properties.dllReferences)
                     LoadAssembly(EncapsulateReferences(modFile.GetFile("lib/" + dll + ".dll")));
                 assembly = LoadAssembly(EncapsulateReferences(modFile.GetMainAssembly()), modFile.GetMainPDB());
                 NeedsReload = false;
             }
SetMod()
void Terraria.ModLoader.AssemblyManager.LoadedMod.SetMod (ModLoader.LoadingMod mod)
Definition at line 44 of file AssemblyManager.cs.
References Terraria.ModLoader.IO.TmodFile.hash, and Terraria.ModLoader.IO.TmodFile.version.
Referenced by Terraria.ModLoader.AssemblyManager.LoadedMod.EncapsulateName().
{
                 if (modFile == null ||
                     modFile.version != mod.modFile.version ||
                     !modFile.hash.SequenceEqual(mod.modFile.hash))
                     SetNeedsReload();
                 modFile = mod.modFile;
                 properties = mod.properties;
             }
SetNeedsReload()
void Terraria.ModLoader.AssemblyManager.LoadedMod.SetNeedsReload () private
Definition at line 54 of file AssemblyManager.cs.
{
                 NeedsReload = true;
                 eacEnabled = false;
                 foreach (var dep in dependents)
                     dep.SetNeedsReload();
             }
SetNeedsReloadUnlessEaC()
void Terraria.ModLoader.AssemblyManager.LoadedMod.SetNeedsReloadUnlessEaC () private
Definition at line 82 of file AssemblyManager.cs.
{
                 if (!eacEnabled)
                     NeedsReload = true;
                 foreach (var dep in dependents)
                     dep.SetNeedsReloadUnlessEaC();
             }
UpdateWeakRefs()
void Terraria.ModLoader.AssemblyManager.LoadedMod.UpdateWeakRefs ()
Definition at line 90 of file AssemblyManager.cs.
{
                 foreach (var loaded in dependencies.Where(dep => weakDependencies.Remove(dep.Name))) {
                     if (eacEnabled && !loaded.eacEnabled)
                         loaded.EnableEaC();
                     else if (loaded.AssemblyName != WeakDepName(loaded.Name))
                         SetNeedsReload();
                 }
             }
WeakDepName()
string Terraria.ModLoader.AssemblyManager.LoadedMod.WeakDepName (string depName) private
Member Data Documentation
_needsReload
bool Terraria.ModLoader.AssemblyManager.LoadedMod._needsReload = true private
Definition at line 31 of file AssemblyManager.cs.
assembly
Assembly Terraria.ModLoader.AssemblyManager.LoadedMod.assembly
Definition at line 26 of file AssemblyManager.cs.
AssemblyName
string Terraria.ModLoader.AssemblyManager.LoadedMod.AssemblyName => eacEnabled ? Name : Name + '_' + loadIndex private
Definition at line 40 of file AssemblyManager.cs.
CanEaC
bool Terraria.ModLoader.AssemblyManager.LoadedMod.CanEaC
Initial value:
=> eacEnabled ||
                !loadedAssemblies.ContainsKey(modFile.name) && dependencies.All(dep => dep.CanEaC)
Definition at line 67 of file AssemblyManager.cs.
dependencies
readonly List<LoadedMod> Terraria.ModLoader.AssemblyManager.LoadedMod.dependencies = new List<LoadedMod>()
Definition at line 20 of file AssemblyManager.cs.
dependents
readonly List<LoadedMod> Terraria.ModLoader.AssemblyManager.LoadedMod.dependents = new List<LoadedMod>()
Definition at line 21 of file AssemblyManager.cs.
Referenced by Terraria.ModLoader.AssemblyManager.LoadedMod.AddDependency().
eacEnabled
bool Terraria.ModLoader.AssemblyManager.LoadedMod.eacEnabled private
Definition at line 29 of file AssemblyManager.cs.
loadIndex
int Terraria.ModLoader.AssemblyManager.LoadedMod.loadIndex private
Definition at line 28 of file AssemblyManager.cs.
modFile
TmodFile Terraria.ModLoader.AssemblyManager.LoadedMod.modFile
Definition at line 16 of file AssemblyManager.cs.
Name
string Terraria.ModLoader.AssemblyManager.LoadedMod.Name => modFile.name
Definition at line 18 of file AssemblyManager.cs.
properties
BuildProperties Terraria.ModLoader.AssemblyManager.LoadedMod.properties
Definition at line 17 of file AssemblyManager.cs.
weakDependencies
readonly ISet<string> Terraria.ModLoader.AssemblyManager.LoadedMod.weakDependencies = new HashSet<string>()
Definition at line 24 of file AssemblyManager.cs.
Property Documentation
NeedsReload
bool Terraria.ModLoader.AssemblyManager.LoadedMod.NeedsReload get set private
Definition at line 32 of file AssemblyManager.cs.
The documentation for this class was generated from the following file:
D:/Documents/My Games/Terraria/Modding/tModLoader/patches/tModLoader/Terraria.ModLoader/AssemblyManager.cs