Terraria ModLoader: Terraria.ModLoader.Default.MysteryTileEntity Class Reference
Terraria.ModLoader.Default.MysteryTileEntity Class Reference
Public Member Functions
override void Load (TagCompound tag)
override TagCompound Save ()
override bool ValidTile (int i, int j)
Public Member Functions inherited from Terraria.ModLoader.ModTileEntity
virtual bool Autoload (ref string name)
int Find (int i, int j)
virtual int Hook_AfterPlacement (int i, int j, int type, int style, int direction)
void Kill (int i, int j)
virtual void NetReceive (BinaryReader reader)
virtual void NetSend (BinaryWriter writer)
virtual void OnKill ()
virtual void OnNetPlace ()
int Place (int i, int j)
virtual void PostGlobalUpdate ()
virtual void PreGlobalUpdate ()
override sealed void ReadExtraData (BinaryReader reader, bool networkSend)
override sealed void WriteExtraData (BinaryWriter writer, bool networkSend)
Private Attributes
TagCompound data
string modName
string tileEntityName
Additional Inherited Members
Static Public Member Functions inherited from Terraria.ModLoader.ModTileEntity
static ModTileEntity ConstructFromBase (ModTileEntity tileEntity)
static ModTileEntity ConstructFromType (int type)
static int CountInWorld ()
static ModTileEntity GetTileEntity (int type)
static void Initialize ()
static void NetPlaceEntity (int i, int j, int type)
Public Attributes inherited from Terraria.ModLoader.ModTileEntity
const int numVanilla = 3
Properties inherited from Terraria.ModLoader.ModTileEntity
Mod mod [get, set]
string Name [get, set]
int Type [get, set]
Detailed Description
Definition at line 7 of file MysteryTileEntity.cs.
Member Function Documentation
Load()
override void Terraria.ModLoader.Default.MysteryTileEntity.Load (TagCompound tag) inline virtual
Reimplemented from Terraria.ModLoader.ModTileEntity.
Definition at line 35 of file MysteryTileEntity.cs.
References Terraria.ModLoader.ModTileEntity.ConstructFromBase(), Terraria.ModLoader.ModLoader.GetMod(), Terraria.ModLoader.Mod.GetTileEntity(), and Terraria.ModLoader.ModTileEntity.Type.
         {
             SetData(tag);
         }
Save()
override TagCompound Terraria.ModLoader.Default.MysteryTileEntity.Save () inline virtual
Reimplemented from Terraria.ModLoader.ModTileEntity.
Definition at line 25 of file MysteryTileEntity.cs.
         {
             return new TagCompound
             {
                 ["mod"] = modName,
                 ["name"] = tileEntityName,
                 ["data"] = data
             };
         }
ValidTile()
override bool Terraria.ModLoader.Default.MysteryTileEntity.ValidTile (int i, int j) inline virtual
Implements Terraria.ModLoader.ModTileEntity.
Definition at line 20 of file MysteryTileEntity.cs.
         {
             return Main.tile[i, j].active() && Main.tile[i, j].type == mod.TileType("MysteryTile");
         }
Member Data Documentation
data
TagCompound Terraria.ModLoader.Default.MysteryTileEntity.data private
Definition at line 11 of file MysteryTileEntity.cs.
modName
string Terraria.ModLoader.Default.MysteryTileEntity.modName private
Definition at line 9 of file MysteryTileEntity.cs.
tileEntityName
string Terraria.ModLoader.Default.MysteryTileEntity.tileEntityName private
Definition at line 10 of file MysteryTileEntity.cs.