Terraria ModLoader: Terraria.ModLoader.WorldHooks Class Reference
Terraria.ModLoader.WorldHooks Class Reference
Static Public Member Functions
static void ChooseWaterStyle (ref int style)
static void ModifyWorldGenTasks (List< GenPass > passes, ref float totalWeight)
static void PostDrawTiles ()
static void PostUpdate ()
static void PostWorldGen ()
static void PreUpdate ()
static void PreWorldGen ()
static void ResetNearbyTileEffects ()
static void TileCountsAvailable (int[] tileCounts)
Detailed Description
Definition at line 8 of file WorldHooks.cs.
Member Function Documentation
ChooseWaterStyle()
static void Terraria.ModLoader.WorldHooks.ChooseWaterStyle (ref int style) static
Definition at line 110 of file WorldHooks.cs.
References Terraria.ModLoader.ModWorld.ChooseWaterStyle().
Referenced by Terraria.ModLoader.WaterStyleLoader.ChooseWaterStyle().
         {
             foreach (ModWorld modWorld in worlds)
             {
                 modWorld.ChooseWaterStyle(ref style);
             }
         }
ModifyWorldGenTasks()
static void Terraria.ModLoader.WorldHooks.ModifyWorldGenTasks (List< GenPass > passes, ref float totalWeight) static
Definition at line 62 of file WorldHooks.cs.
References Terraria.ModLoader.ModWorld.ModifyWorldGenTasks().
         {
             foreach (ModWorld modWorld in worlds)
             {
                 modWorld.ModifyWorldGenTasks(passes, ref totalWeight);
             }
         }
PostDrawTiles()
static void Terraria.ModLoader.WorldHooks.PostDrawTiles () static
Definition at line 118 of file WorldHooks.cs.
References Terraria.ModLoader.ModWorld.PostDrawTiles().
         {
             foreach (ModWorld modWorld in worlds)
             {
                 modWorld.PostDrawTiles();
             }
         }
PostUpdate()
static void Terraria.ModLoader.WorldHooks.PostUpdate () static
Definition at line 94 of file WorldHooks.cs.
References Terraria.ModLoader.ModWorld.PostUpdate().
         {
             foreach (ModWorld modWorld in worlds)
             {
                 modWorld.PostUpdate();
             }
         }
PostWorldGen()
static void Terraria.ModLoader.WorldHooks.PostWorldGen () static
Definition at line 70 of file WorldHooks.cs.
References Terraria.ModLoader.ModWorld.PostWorldGen().
         {
             foreach (ModWorld modWorld in worlds)
             {
                 modWorld.PostWorldGen();
             }
         }
PreUpdate()
static void Terraria.ModLoader.WorldHooks.PreUpdate () static
Definition at line 86 of file WorldHooks.cs.
References Terraria.ModLoader.ModWorld.PreUpdate().
         {
             foreach (ModWorld modWorld in worlds)
             {
                 modWorld.PreUpdate();
             }
         }
PreWorldGen()
static void Terraria.ModLoader.WorldHooks.PreWorldGen () static
Definition at line 54 of file WorldHooks.cs.
References Terraria.ModLoader.ModWorld.PreWorldGen().
         {
             foreach (ModWorld modWorld in worlds)
             {
                 modWorld.PreWorldGen();
             }
         }
ResetNearbyTileEffects()
static void Terraria.ModLoader.WorldHooks.ResetNearbyTileEffects () static
Definition at line 78 of file WorldHooks.cs.
References Terraria.ModLoader.ModWorld.ResetNearbyTileEffects().
         {
             foreach (ModWorld modWorld in worlds)
             {
                 modWorld.ResetNearbyTileEffects();
             }
         }
TileCountsAvailable()
static void Terraria.ModLoader.WorldHooks.TileCountsAvailable (int [] tileCounts) static
Definition at line 102 of file WorldHooks.cs.
References Terraria.ModLoader.ModWorld.TileCountsAvailable().
         {
             foreach (ModWorld modWorld in worlds)
             {
                 modWorld.TileCountsAvailable(tileCounts);
             }
         }
The documentation for this class was generated from the following file:
D:/Documents/My Games/Terraria/Modding/tModLoader/src/tModLoader/Terraria.ModLoader/WorldHooks.cs