Terraria ModLoader: Terraria.ModLoader.ModTile Class Reference
Terraria.ModLoader.ModTile Class Reference
Public Member Functions
void AddMapEntry (Color color, string name="")
void AddMapEntry (Color color, string name, Func< string, int, int, string > nameFunc)
void AddToArray (ref int[] array)
virtual void AnimateTile (ref int frame, ref int frameCounter)
virtual bool Autoload (ref string name, ref string texture)
virtual bool AutoSelect (int i, int j, Item item)
virtual bool CanExplode (int i, int j)
virtual bool CanKillTile (int i, int j, ref bool blockDamaged)
virtual bool CanPlace (int i, int j)
virtual void ChangeWaterfallStyle (ref int style)
virtual bool CreateDust (int i, int j, ref int type)
virtual bool Dangersense (int i, int j, Player player)
virtual void DrawEffects (int i, int j, SpriteBatch spriteBatch, ref Color drawColor)
virtual bool Drop (int i, int j)
virtual void DropCritterChance (int i, int j, ref int wormChance, ref int grassHopperChance, ref int jungleGrubChance)
virtual ushort GetMapOption (int i, int j)
virtual bool HasWalkDust ()
virtual void HitWire (int i, int j)
virtual void KillMultiTile (int i, int j, int frameX, int frameY)
virtual bool KillSound (int i, int j)
virtual void KillTile (int i, int j, ref bool fail, ref bool effectOnly, ref bool noItem)
virtual void ModifyLight (int i, int j, ref float r, ref float g, ref float b)
virtual void MouseOver (int i, int j)
virtual void MouseOverFar (int i, int j)
virtual void NearbyEffects (int i, int j, bool closer)
virtual void NumDust (int i, int j, bool fail, ref int num)
virtual void PlaceInWorld (int i, int j, Item item)
virtual void PostDraw (int i, int j, SpriteBatch spriteBatch)
virtual void PostSetDefaults ()
virtual bool PreDraw (int i, int j, SpriteBatch spriteBatch)
virtual void RandomUpdate (int i, int j)
virtual void RightClick (int i, int j)
virtual int SaplingGrowthType (ref int style)
virtual void SetDefaults ()
virtual void SetDrawPositions (int i, int j, ref int width, ref int offsetY, ref int height)
void SetModCactus (ModCactus cactus)
void SetModPalmTree (ModPalmTree palmTree)
void SetModTree (ModTree tree)
virtual void SetSpriteEffects (int i, int j, ref SpriteEffects spriteEffects)
virtual bool Slope (int i, int j)
virtual bool TileFrame (int i, int j, ref bool resetFrame, ref bool noBreak)
virtual void WalkDust (ref int dustType, ref bool makeDust, ref Color color)
Public Attributes
int [] adjTiles = new int[0]
int animationFrameHeight = 0
bool bed = false
string chest = ""
int chestDrop = 0
int closeDoorID = -1
bool disableSmartCursor = false
string dresser = ""
int dresserDrop = 0
int drop = 0
int dustType = 0
float mineResist = 1f
int minPick = 0
int openDoorID = -1
bool sapling = false
int soundStyle = 1
int soundType = 0
bool torch = false
Properties
Mod mod [get, set]
string Name [get, set]
ushort Type [get, set]
Detailed Description
Definition at line 10 of file ModTile.cs.
Member Function Documentation
AddMapEntry() [1/2]
void Terraria.ModLoader.ModTile.AddMapEntry (Color color, string name = "") inline
Definition at line 56 of file ModTile.cs.
         {
             if (!MapLoader.initialized)
             {
                 MapEntry entry = new MapEntry(color, name);
                 if (!MapLoader.tileEntries.Keys.Contains(Type))
                 {
                     MapLoader.tileEntries[Type] = new List<MapEntry>();
                 }
                 MapLoader.tileEntries[Type].Add(entry);
             }
         }
AddMapEntry() [2/2]
void Terraria.ModLoader.ModTile.AddMapEntry (Color color, string name, Func< string, int, int, string > nameFunc) inline
Definition at line 69 of file ModTile.cs.
         {
             if (!MapLoader.initialized)
             {
                 MapEntry entry = new MapEntry(color, name, nameFunc);
                 if (!MapLoader.tileEntries.Keys.Contains(Type))
                 {
                     MapLoader.tileEntries[Type] = new List<MapEntry>();
                 }
                 MapLoader.tileEntries[Type].Add(entry);
             }
         }
AddToArray()
void Terraria.ModLoader.ModTile.AddToArray (ref int [] array) inline
Definition at line 50 of file ModTile.cs.
         {
             Array.Resize(ref array, array.Length + 1);
             array[array.Length - 1] = Type;
         }
AnimateTile()
virtual void Terraria.ModLoader.ModTile.AnimateTile (ref int frame, ref int frameCounter) inline virtual
Definition at line 173 of file ModTile.cs.
Referenced by Terraria.ModLoader.TileLoader.AnimateTiles().
         {
         }
Autoload()
virtual bool Terraria.ModLoader.ModTile.Autoload (ref string name, ref string texture) inline virtual
Definition at line 97 of file ModTile.cs.
Referenced by Terraria.ModLoader.Mod.AutoloadTile().
         {
             return mod.Properties.Autoload;
         }
AutoSelect()
virtual bool Terraria.ModLoader.ModTile.AutoSelect (int i, int j, Item item) inline virtual
Definition at line 221 of file ModTile.cs.
Referenced by Terraria.ModLoader.TileLoader.AutoSelect().
         {
             return false;
         }
CanExplode()
virtual bool Terraria.ModLoader.ModTile.CanExplode (int i, int j) inline virtual
Definition at line 147 of file ModTile.cs.
Referenced by Terraria.ModLoader.TileLoader.CanExplode().
         {
             return true;
         }
CanKillTile()
virtual bool Terraria.ModLoader.ModTile.CanKillTile (int i, int j, ref bool blockDamaged) inline virtual
Definition at line 134 of file ModTile.cs.
         {
             return true;
         }
CanPlace()
virtual bool Terraria.ModLoader.ModTile.CanPlace (int i, int j) inline virtual
Definition at line 204 of file ModTile.cs.
         {
             return true;
         }
ChangeWaterfallStyle()
virtual void Terraria.ModLoader.ModTile.ChangeWaterfallStyle (ref int style) inline virtual
Definition at line 244 of file ModTile.cs.
         {
         }
CreateDust()
virtual bool Terraria.ModLoader.ModTile.CreateDust (int i, int j, ref int type) inline virtual
Definition at line 119 of file ModTile.cs.
         {
             type = dustType;
             return true;
         }
Dangersense()
virtual bool Terraria.ModLoader.ModTile.Dangersense (int i, int j, Player player) inline virtual
Definition at line 160 of file ModTile.cs.
Referenced by Terraria.ModLoader.TileLoader.Dangersense().
         {
             return false;
         }
DrawEffects()
virtual void Terraria.ModLoader.ModTile.DrawEffects (int i, int j, SpriteBatch spriteBatch, ref Color drawColor) inline virtual
Definition at line 182 of file ModTile.cs.
         {
         }
Drop()
virtual bool Terraria.ModLoader.ModTile.Drop (int i, int j) inline virtual
Definition at line 129 of file ModTile.cs.
Referenced by Terraria.ModLoader.TileLoader.Drop().
         {
             return true;
         }
DropCritterChance()
virtual void Terraria.ModLoader.ModTile.DropCritterChance (int i, int j, ref int wormChance, ref int grassHopperChance, ref int jungleGrubChance) inline virtual
Definition at line 125 of file ModTile.cs.
         {
         }
GetMapOption()
virtual ushort Terraria.ModLoader.ModTile.GetMapOption (int i, int j) inline virtual
Definition at line 190 of file ModTile.cs.
         {
             return 0;
         }
HasWalkDust()
virtual bool Terraria.ModLoader.ModTile.HasWalkDust () inline virtual
Definition at line 235 of file ModTile.cs.
         {
             return false;
         }
HitWire()
virtual void Terraria.ModLoader.ModTile.HitWire (int i, int j) inline virtual
Definition at line 226 of file ModTile.cs.
         {
         }
KillMultiTile()
virtual void Terraria.ModLoader.ModTile.KillMultiTile (int i, int j, int frameX, int frameY) inline virtual
Definition at line 143 of file ModTile.cs.
         {
         }
KillSound()
virtual bool Terraria.ModLoader.ModTile.KillSound (int i, int j) inline virtual
Definition at line 110 of file ModTile.cs.
Referenced by Terraria.ModLoader.TileLoader.KillSound().
         {
             return true;
         }
KillTile()
virtual void Terraria.ModLoader.ModTile.KillTile (int i, int j, ref bool fail, ref bool effectOnly, ref bool noItem) inline virtual
Definition at line 139 of file ModTile.cs.
         {
         }
ModifyLight()
virtual void Terraria.ModLoader.ModTile.ModifyLight (int i, int j, ref float r, ref float g, ref float b) inline virtual
Definition at line 156 of file ModTile.cs.
         {
         }
MouseOver()
virtual void Terraria.ModLoader.ModTile.MouseOver (int i, int j) inline virtual
Definition at line 213 of file ModTile.cs.
         {
         }
MouseOverFar()
virtual void Terraria.ModLoader.ModTile.MouseOverFar (int i, int j) inline virtual
Definition at line 217 of file ModTile.cs.
         {
         }
NearbyEffects()
virtual void Terraria.ModLoader.ModTile.NearbyEffects (int i, int j, bool closer) inline virtual
Definition at line 152 of file ModTile.cs.
         {
         }
NumDust()
virtual void Terraria.ModLoader.ModTile.NumDust (int i, int j, bool fail, ref int num) inline virtual
Definition at line 115 of file ModTile.cs.
         {
         }
PlaceInWorld()
virtual void Terraria.ModLoader.ModTile.PlaceInWorld (int i, int j, Item item) inline virtual
Definition at line 253 of file ModTile.cs.
         {
         }
PostDraw()
virtual void Terraria.ModLoader.ModTile.PostDraw (int i, int j, SpriteBatch spriteBatch) inline virtual
Definition at line 186 of file ModTile.cs.
         {
         }
PostSetDefaults()
virtual void Terraria.ModLoader.ModTile.PostSetDefaults () inline virtual
Definition at line 106 of file ModTile.cs.
Referenced by Terraria.ModLoader.TileLoader.IsModMusicBox().
         {
         }
PreDraw()
virtual bool Terraria.ModLoader.ModTile.PreDraw (int i, int j, SpriteBatch spriteBatch) inline virtual
Definition at line 177 of file ModTile.cs.
         {
             return true;
         }
RandomUpdate()
virtual void Terraria.ModLoader.ModTile.RandomUpdate (int i, int j) inline virtual
Definition at line 195 of file ModTile.cs.
         {
         }
RightClick()
virtual void Terraria.ModLoader.ModTile.RightClick (int i, int j) inline virtual
Definition at line 209 of file ModTile.cs.
         {
         }
SaplingGrowthType()
virtual int Terraria.ModLoader.ModTile.SaplingGrowthType (ref int style) inline virtual
Definition at line 248 of file ModTile.cs.
Referenced by Terraria.ModLoader.TileLoader.SaplingGrowthType().
         {
             return -1;
         }
SetDefaults()
virtual void Terraria.ModLoader.ModTile.SetDefaults () inline virtual
Reimplemented in Terraria.ModLoader.Default.MysteryTile.
Definition at line 102 of file ModTile.cs.
Referenced by Terraria.ModLoader.TileLoader.IsModMusicBox().
         {
         }
SetDrawPositions()
virtual void Terraria.ModLoader.ModTile.SetDrawPositions (int i, int j, ref int width, ref int offsetY, ref int height) inline virtual
Definition at line 169 of file ModTile.cs.
Referenced by Terraria.ModLoader.TileLoader.SetDrawPositions().
         {
         }
SetModCactus()
void Terraria.ModLoader.ModTile.SetModCactus (ModCactus cactus) inline
Definition at line 92 of file ModTile.cs.
         {
             TileLoader.cacti[Type] = cactus;
         }
SetModPalmTree()
void Terraria.ModLoader.ModTile.SetModPalmTree (ModPalmTree palmTree) inline
Definition at line 87 of file ModTile.cs.
         {
             TileLoader.palmTrees[Type] = palmTree;
         }
SetModTree()
void Terraria.ModLoader.ModTile.SetModTree (ModTree tree) inline
Definition at line 82 of file ModTile.cs.
         {
             TileLoader.trees[Type] = tree;
         }
SetSpriteEffects()
virtual void Terraria.ModLoader.ModTile.SetSpriteEffects (int i, int j, ref SpriteEffects spriteEffects) inline virtual
Definition at line 165 of file ModTile.cs.
         {
         }
Slope()
virtual bool Terraria.ModLoader.ModTile.Slope (int i, int j) inline virtual
Definition at line 230 of file ModTile.cs.
         {
             return true;
         }
TileFrame()
virtual bool Terraria.ModLoader.ModTile.TileFrame (int i, int j, ref bool resetFrame, ref bool noBreak) inline virtual
Definition at line 199 of file ModTile.cs.
Referenced by Terraria.ModLoader.TileLoader.TileFrame().
         {
             return true;
         }
WalkDust()
virtual void Terraria.ModLoader.ModTile.WalkDust (ref int dustType, ref bool makeDust, ref Color color) inline virtual
Definition at line 240 of file ModTile.cs.
         {
         }
Member Data Documentation
adjTiles
int [] Terraria.ModLoader.ModTile.adjTiles = new int[0]
Definition at line 39 of file ModTile.cs.
Referenced by Terraria.ModLoader.TileLoader.AdjTiles().
animationFrameHeight
int Terraria.ModLoader.ModTile.animationFrameHeight = 0
Definition at line 35 of file ModTile.cs.
Referenced by Terraria.ModLoader.TileLoader.SetAnimationFrame().
bed
bool Terraria.ModLoader.ModTile.bed = false
Definition at line 46 of file ModTile.cs.
Referenced by Terraria.ModLoader.TileLoader.IsModBed().
chest
string Terraria.ModLoader.ModTile.chest = ""
Definition at line 42 of file ModTile.cs.
Referenced by Terraria.ModLoader.TileLoader.ModChestName().
chestDrop
int Terraria.ModLoader.ModTile.chestDrop = 0
Definition at line 43 of file ModTile.cs.
closeDoorID
int Terraria.ModLoader.ModTile.closeDoorID = -1
Definition at line 40 of file ModTile.cs.
Referenced by Terraria.ModLoader.TileLoader.CloseDoorID().
disableSmartCursor
bool Terraria.ModLoader.ModTile.disableSmartCursor = false
Definition at line 38 of file ModTile.cs.
Referenced by Terraria.ModLoader.TileLoader.DisableSmartCursor().
dresser
string Terraria.ModLoader.ModTile.dresser = ""
Definition at line 44 of file ModTile.cs.
Referenced by Terraria.ModLoader.TileLoader.ModDresserName().
dresserDrop
int Terraria.ModLoader.ModTile.dresserDrop = 0
Definition at line 45 of file ModTile.cs.
drop
int Terraria.ModLoader.ModTile.drop = 0
Definition at line 34 of file ModTile.cs.
Referenced by Terraria.ModLoader.TileLoader.Drop().
dustType
int Terraria.ModLoader.ModTile.dustType = 0
Definition at line 33 of file ModTile.cs.
mineResist
float Terraria.ModLoader.ModTile.mineResist = 1f
Definition at line 36 of file ModTile.cs.
Referenced by Terraria.ModLoader.TileLoader.MineDamage().
minPick
int Terraria.ModLoader.ModTile.minPick = 0
Definition at line 37 of file ModTile.cs.
Referenced by Terraria.ModLoader.TileLoader.PickPowerCheck().
openDoorID
int Terraria.ModLoader.ModTile.openDoorID = -1
Definition at line 41 of file ModTile.cs.
Referenced by Terraria.ModLoader.TileLoader.OpenDoorID().
sapling
bool Terraria.ModLoader.ModTile.sapling = false
Definition at line 48 of file ModTile.cs.
Referenced by Terraria.ModLoader.TileLoader.IsSapling().
soundStyle
int Terraria.ModLoader.ModTile.soundStyle = 1
Definition at line 32 of file ModTile.cs.
Referenced by Terraria.ModLoader.TileLoader.KillSound().
soundType
int Terraria.ModLoader.ModTile.soundType = 0
Definition at line 31 of file ModTile.cs.
Referenced by Terraria.ModLoader.TileLoader.KillSound().
torch
bool Terraria.ModLoader.ModTile.torch = false
Definition at line 47 of file ModTile.cs.
Referenced by Terraria.ModLoader.TileLoader.IsTorch().
Property Documentation
mod
Mod Terraria.ModLoader.ModTile.mod get set
Definition at line 13 of file ModTile.cs.
Referenced by Terraria.ModLoader.Mod.AddTile(), and Terraria.ModLoader.Mod.AutoloadTile().
Name
string Terraria.ModLoader.ModTile.Name get set
Definition at line 19 of file ModTile.cs.
Referenced by Terraria.ModLoader.Mod.AddTile().
Type
ushort Terraria.ModLoader.ModTile.Type get set
Definition at line 25 of file ModTile.cs.
Referenced by Terraria.ModLoader.ModRecipe.AddTile(), Terraria.ModLoader.Mod.AddTile(), Terraria.ModLoader.TileLoader.AnimateTiles(), Terraria.ModLoader.TileLoader.IsModMusicBox(), Terraria.ModLoader.Mod.RegisterHotKey(), and Terraria.ModLoader.Mod.TileType().