@echo off
echo Cleaning up output folders...
dotnet clean "../src/tModLoader/Terraria/Terraria.csproj" -c Release --nologo -v q
echo Building Release...
dotnet build "../src/tModLoader/Terraria/Terraria.csproj" -c Release --nologo -v q /clp:ErrorsOnly
echo Building ExampleMod...
dotnet build "../ExampleMod/ExampleMod.csproj" -c Release --nologo -v q /clp:ErrorsOnly
pause