var searchData=
[
  ['iachievementtracker_794',['IAchievementTracker',['../interface_terraria_1_1_achievements_1_1_i_achievement_tracker.html',1,'Terraria::Achievements']]],
  ['iassetreader_795',['IAssetReader',['../class_i_asset_reader.html',1,'']]],
  ['iaudiosystem_796',['IAudioSystem',['../interface_terraria_1_1_audio_1_1_i_audio_system.html',1,'Terraria::Audio']]],
  ['iaudiotrack_797',['IAudioTrack',['../interface_terraria_1_1_audio_1_1_i_audio_track.html',1,'Terraria::Audio']]],
  ['iballcontactlistener_798',['IBallContactListener',['../interface_terraria_1_1_physics_1_1_i_ball_contact_listener.html',1,'Terraria::Physics']]],
  ['ibestiarybackgroundimagepathandcolorprovider_799',['IBestiaryBackgroundImagePathAndColorProvider',['../interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_bestiary_background_image_path_and_color_provider.html',1,'Terraria::GameContent::Bestiary']]],
  ['ibestiarybackgroundoverlayandcolorprovider_800',['IBestiaryBackgroundOverlayAndColorProvider',['../interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_bestiary_background_overlay_and_color_provider.html',1,'Terraria::GameContent::Bestiary']]],
  ['ibestiaryentrydisplayindex_801',['IBestiaryEntryDisplayIndex',['../interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_bestiary_entry_display_index.html',1,'Terraria::GameContent::Bestiary']]],
  ['ibestiaryentryfilter_802',['IBestiaryEntryFilter',['../interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_bestiary_entry_filter.html',1,'Terraria::GameContent::Bestiary']]],
  ['ibestiaryinfoelement_803',['IBestiaryInfoElement',['../interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_bestiary_info_element.html',1,'Terraria::GameContent::Bestiary']]],
  ['ibestiarysortstep_804',['IBestiarySortStep',['../interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_bestiary_sort_step.html',1,'Terraria::GameContent::Bestiary']]],
  ['ibestiaryuicollectioninfoprovider_805',['IBestiaryUICollectionInfoProvider',['../interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_bestiary_u_i_collection_info_provider.html',1,'Terraria::GameContent::Bestiary']]],
  ['ibigprogressbar_806',['IBigProgressBar',['../interface_terraria_1_1_game_content_1_1_u_i_1_1_big_progress_bar_1_1_i_big_progress_bar.html',1,'Terraria::GameContent::UI::BigProgressBar']]],
  ['ibuilderacctoggle_807',['IBuilderAccToggle',['../interface_terraria_1_1_game_content_1_1_u_i_1_1_builder_acc_toggles_u_i_1_1_i_builder_acc_toggle.html',1,'Terraria::GameContent::UI::BuilderAccTogglesUI']]],
  ['icehousebuilder_808',['IceHouseBuilder',['../class_terraria_1_1_game_content_1_1_biomes_1_1_cave_house_1_1_ice_house_builder.html',1,'Terraria::GameContent::Biomes::CaveHouse']]],
  ['iceshader_809',['IceShader',['../class_terraria_1_1_game_content_1_1_r_g_b_1_1_ice_shader.html',1,'Terraria::GameContent::RGB']]],
  ['ichatcommand_810',['IChatCommand',['../interface_terraria_1_1_chat_1_1_commands_1_1_i_chat_command.html',1,'Terraria::Chat::Commands']]],
  ['ichatmonitor_811',['IChatMonitor',['../interface_terraria_1_1_game_content_1_1_u_i_1_1_chat_1_1_i_chat_monitor.html',1,'Terraria::GameContent::UI::Chat']]],
  ['ichatprocessor_812',['IChatProcessor',['../interface_terraria_1_1_chat_1_1_i_chat_processor.html',1,'Terraria::Chat']]],
  ['icloneable_813',['ICloneable',['../class_i_cloneable.html',1,'']]],
  ['icolorable_814',['IColorable',['../interface_terraria_1_1_game_content_1_1_u_i_1_1_elements_1_1_i_colorable.html',1,'Terraria::GameContent::UI::Elements']]],
  ['icomparable_815',['IComparable',['../class_i_comparable.html',1,'']]],
  ['icomparer_816',['IComparer',['../class_i_comparer.html',1,'']]],
  ['icomparer_3c_20tuple_3c_20int_2c_20float_20_3e_3e_817',['IComparer&lt; Tuple&lt; int, float &gt;&gt;',['../class_i_comparer_3_01_tuple_3_01int_00_01float_01_4_4.html',1,'']]],
  ['iconcolor_818',['iconColor',['../struct_terraria_1_1_data_structures_1_1_boss_bar_draw_params.html#a43ceb9ba4eb31e94471fb7be98d0376c',1,'Terraria::DataStructures::BossBarDrawParams']]],
  ['icondition_819',['ICondition',['../interface_terraria_1_1_recipe_1_1_i_condition.html',1,'Terraria::Recipe']]],
  ['iconframe_820',['iconFrame',['../struct_terraria_1_1_data_structures_1_1_boss_bar_draw_params.html#aa7457e6112854a8ce2e3fc090ef88988',1,'Terraria::DataStructures::BossBarDrawParams']]],
  ['iconscale_821',['iconScale',['../struct_terraria_1_1_data_structures_1_1_boss_bar_draw_params.html#ac315e379926e9c49d5378325d1318a59',1,'Terraria::DataStructures::BossBarDrawParams']]],
  ['icontentvalidator_822',['IContentValidator',['../class_i_content_validator.html',1,'']]],
  ['icontexture_823',['iconTexture',['../struct_terraria_1_1_data_structures_1_1_boss_bar_draw_params.html#a6da99506d15cefc246b173e4562d6996',1,'Terraria::DataStructures::BossBarDrawParams']]],
  ['icreativeitemsortstep_824',['ICreativeItemSortStep',['../interface_terraria_1_1_game_content_1_1_creative_1_1_i_creative_item_sort_step.html',1,'Terraria::GameContent::Creative']]],
  ['icreativepower_825',['ICreativePower',['../interface_terraria_1_1_game_content_1_1_creative_1_1_i_creative_power.html',1,'Terraria::GameContent::Creative']]],
  ['icreditsrollsegment_826',['ICreditsRollSegment',['../interface_terraria_1_1_game_content_1_1_skies_1_1_credits_roll_1_1_i_credits_roll_segment.html',1,'Terraria::GameContent::Skies::CreditsRoll']]],
  ['icreditsrollsegmentaction_827',['ICreditsRollSegmentAction',['../interface_terraria_1_1_game_content_1_1_skies_1_1_credits_roll_1_1_i_credits_roll_segment_action.html',1,'Terraria::GameContent::Skies::CreditsRoll']]],
  ['icreditsrollsegmentaction_3c_20npc_20_3e_828',['ICreditsRollSegmentAction&lt; NPC &gt;',['../interface_terraria_1_1_game_content_1_1_skies_1_1_credits_roll_1_1_i_credits_roll_segment_action.html',1,'Terraria::GameContent::Skies::CreditsRoll']]],
  ['icreditsrollsegmentaction_3c_20player_20_3e_829',['ICreditsRollSegmentAction&lt; Player &gt;',['../interface_terraria_1_1_game_content_1_1_skies_1_1_credits_roll_1_1_i_credits_roll_segment_action.html',1,'Terraria::GameContent::Skies::CreditsRoll']]],
  ['icreditsrollsegmentaction_3c_20segments_2eloosesprite_20_3e_830',['ICreditsRollSegmentAction&lt; Segments.LooseSprite &gt;',['../interface_terraria_1_1_game_content_1_1_skies_1_1_credits_roll_1_1_i_credits_roll_segment_action.html',1,'Terraria::GameContent::Skies::CreditsRoll']]],
  ['ientitywithglobals_831',['IEntityWithGlobals',['../interface_terraria_1_1_mod_loader_1_1_i_entity_with_globals.html',1,'Terraria::ModLoader']]],
  ['ientitywithglobals_3c_20globalitem_20_3e_832',['IEntityWithGlobals&lt; GlobalItem &gt;',['../interface_terraria_1_1_mod_loader_1_1_i_entity_with_globals.html',1,'Terraria::ModLoader']]],
  ['ientitywithglobals_3c_20globalnpc_20_3e_833',['IEntityWithGlobals&lt; GlobalNPC &gt;',['../interface_terraria_1_1_mod_loader_1_1_i_entity_with_globals.html',1,'Terraria::ModLoader']]],
  ['ientitywithglobals_3c_20globalprojectile_20_3e_834',['IEntityWithGlobals&lt; GlobalProjectile &gt;',['../interface_terraria_1_1_mod_loader_1_1_i_entity_with_globals.html',1,'Terraria::ModLoader']]],
  ['ientryfilter_835',['IEntryFilter',['../interface_terraria_1_1_data_structures_1_1_i_entry_filter.html',1,'Terraria::DataStructures']]],
  ['ientryfilter_3c_20bestiaryentry_20_3e_836',['IEntryFilter&lt; BestiaryEntry &gt;',['../interface_terraria_1_1_data_structures_1_1_i_entry_filter.html',1,'Terraria::DataStructures']]],
  ['ientryfilter_3c_20item_20_3e_837',['IEntryFilter&lt; Item &gt;',['../interface_terraria_1_1_data_structures_1_1_i_entry_filter.html',1,'Terraria::DataStructures']]],
  ['ientryicon_838',['IEntryIcon',['../interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_entry_icon.html',1,'Terraria::GameContent::Bestiary']]],
  ['ientrysortstep_839',['IEntrySortStep',['../interface_terraria_1_1_data_structures_1_1_i_entry_sort_step.html',1,'Terraria::DataStructures']]],
  ['ientrysortstep_3c_20bestiaryentry_20_3e_840',['IEntrySortStep&lt; BestiaryEntry &gt;',['../interface_terraria_1_1_data_structures_1_1_i_entry_sort_step.html',1,'Terraria::DataStructures']]],
  ['ientrysortstep_3c_20int_20_3e_841',['IEntrySortStep&lt; int &gt;',['../interface_terraria_1_1_data_structures_1_1_i_entry_sort_step.html',1,'Terraria::DataStructures']]],
  ['ienumerable_842',['IEnumerable',['../class_i_enumerable.html',1,'']]],
  ['ienumerable_3c_20keyvaluepair_3c_20string_2c_20object_20_3e_3e_843',['IEnumerable&lt; KeyValuePair&lt; string, object &gt;&gt;',['../class_i_enumerable_3_01_key_value_pair_3_01string_00_01object_01_4_4.html',1,'']]],
  ['iequatable_844',['IEquatable',['../class_i_equatable.html',1,'']]],
  ['ifilebrowser_845',['IFileBrowser',['../interface_terraria_1_1_utilities_1_1_file_browser_1_1_i_file_browser.html',1,'Terraria::Utilities::FileBrowser']]],
  ['ifilterinfoprovider_846',['IFilterInfoProvider',['../interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_filter_info_provider.html',1,'Terraria::GameContent::Bestiary']]],
  ['igroupoptionbutton_847',['IGroupOptionButton',['../interface_terraria_1_1_game_content_1_1_u_i_1_1_elements_1_1_i_group_option_button.html',1,'Terraria::GameContent::UI::Elements']]],
  ['ihavebackbuttoncommand_848',['IHaveBackButtonCommand',['../interface_terraria_1_1_u_i_1_1_i_have_back_button_command.html',1,'Terraria::UI']]],
  ['iingamenotification_849',['IInGameNotification',['../interface_terraria_1_1_u_i_1_1_i_in_game_notification.html',1,'Terraria::UI']]],
  ['iitembestiaryinfoelement_850',['IItemBestiaryInfoElement',['../interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_item_bestiary_info_element.html',1,'Terraria::GameContent::Bestiary']]],
  ['iitemdroprule_851',['IItemDropRule',['../interface_terraria_1_1_game_content_1_1_item_drop_rules_1_1_i_item_drop_rule.html',1,'Terraria::GameContent::ItemDropRules']]],
  ['iitemdroprulechainattempt_852',['IItemDropRuleChainAttempt',['../interface_terraria_1_1_game_content_1_1_item_drop_rules_1_1_i_item_drop_rule_chain_attempt.html',1,'Terraria::GameContent::ItemDropRules']]],
  ['iitemdroprulecondition_853',['IItemDropRuleCondition',['../interface_terraria_1_1_game_content_1_1_item_drop_rules_1_1_i_item_drop_rule_condition.html',1,'Terraria::GameContent::ItemDropRules']]],
  ['iitementryfilter_854',['IItemEntryFilter',['../interface_terraria_1_1_game_content_1_1_creative_1_1_i_item_entry_filter.html',1,'Terraria::GameContent::Creative']]],
  ['ilightingengine_855',['ILightingEngine',['../interface_terraria_1_1_graphics_1_1_light_1_1_i_lighting_engine.html',1,'Terraria::Graphics::Light']]],
  ['iloadable_856',['ILoadable',['../interface_terraria_1_1_mod_loader_1_1_i_loadable.html',1,'Terraria::ModLoader']]],
  ['iloader_857',['ILoader',['../interface_terraria_1_1_mod_loader_1_1_i_loader.html',1,'Terraria::ModLoader']]],
  ['imageio_858',['ImageIO',['../class_terraria_1_1_mod_loader_1_1_i_o_1_1_image_i_o.html',1,'Terraria::ModLoader::IO']]],
  ['imanuallyordereduielement_859',['IManuallyOrderedUIElement',['../interface_terraria_1_1_game_content_1_1_u_i_1_1_elements_1_1_i_manually_ordered_u_i_element.html',1,'Terraria::GameContent::UI::Elements']]],
  ['imaplayer_860',['IMapLayer',['../interface_terraria_1_1_map_1_1_i_map_layer.html',1,'Terraria::Map']]],
  ['immediatespritebatchforplayerdyeseffect_861',['ImmediateSpritebatchForPlayerDyesEffect',['../class_terraria_1_1_game_content_1_1_skies_1_1_credits_roll_1_1_segments_1_1_player_segment_1_1_i80cf05f0478e3894be72e0a77d29c1ad.html',1,'Terraria::GameContent::Skies::CreditsRoll::Segments::PlayerSegment']]],
  ['imodtype_862',['IModType',['../interface_terraria_1_1_mod_loader_1_1_i_mod_type.html',1,'Terraria::ModLoader']]],
  ['imultiplayercloseplayersoverlay_863',['IMultiplayerClosePlayersOverlay',['../interface_terraria_1_1_game_content_1_1_u_i_1_1_i_multiplayer_close_players_overlay.html',1,'Terraria::GameContent::UI']]],
  ['includecapefrontandbackinfo_864',['IncludeCapeFrontAndBackInfo',['../struct_terraria_1_1_i_d_1_1_armor_i_ds_1_1_body_1_1_sets_1_1_include_cape_front_and_back_info.html',1,'Terraria::ID::ArmorIDs::Body::Sets']]],
  ['incrementattribute_865',['IncrementAttribute',['../class_terraria_1_1_mod_loader_1_1_config_1_1_increment_attribute.html',1,'Terraria::ModLoader::Config']]],
  ['index_866',['index',['../class_terraria_1_1_mod_loader_1_1_drawable_tooltip_line.html#a91f4dbe5ede1242c5cf5b7a9764ed832',1,'Terraria::ModLoader::DrawableTooltipLine']]],
  ['ineedrendertargetcontent_867',['INeedRenderTargetContent',['../interface_terraria_1_1_game_content_1_1_i_need_render_target_content.html',1,'Terraria::GameContent']]],
  ['inesteditemdroprule_868',['INestedItemDropRule',['../interface_terraria_1_1_game_content_1_1_item_drop_rules_1_1_i_nested_item_drop_rule.html',1,'Terraria::GameContent::ItemDropRules']]],
  ['inetdiagnosticsui_869',['INetDiagnosticsUI',['../interface_terraria_1_1_u_i_1_1_i_net_diagnostics_u_i.html',1,'Terraria::UI']]],
  ['infodisplay_870',['InfoDisplay',['../class_terraria_1_1_mod_loader_1_1_info_display.html',1,'Terraria::ModLoader']]],
  ['infoname_871',['InfoName',['../class_terraria_1_1_mod_loader_1_1_info_display.html#a92fb42a5b373faf7c26581734b7c0eb3',1,'Terraria::ModLoader::InfoDisplay']]],
  ['infotosetbackcolor_872',['InfoToSetBackColor',['../struct_terraria_1_1_main_1_1_info_to_set_back_color.html',1,'Terraria::Main']]],
  ['ingamefancyui_873',['IngameFancyUI',['../class_terraria_1_1_u_i_1_1_ingame_fancy_u_i.html',1,'Terraria::UI']]],
  ['ingamenotificationstracker_874',['InGameNotificationsTracker',['../class_terraria_1_1_u_i_1_1_in_game_notifications_tracker.html',1,'Terraria::UI']]],
  ['ingamepopups_875',['InGamePopups',['../class_terraria_1_1_u_i_1_1_in_game_popups.html',1,'Terraria::UI']]],
  ['initializationcontext_876',['InitializationContext',['../class_terraria_1_1_mod_loader_1_1_initialization_context.html',1,'Terraria::ModLoader']]],
  ['initialize_877',['Initialize',['../class_terraria_1_1_mod_loader_1_1_mod_player.html#a7b06737bb45ee8fae87eb4c989b40da6',1,'Terraria.ModLoader.ModPlayer.Initialize()'],['../class_terraria_1_1_mod_loader_1_1_default_1_1_unloaded_player.html#a1510ec7c92d8e270652b914bda121137',1,'Terraria.ModLoader.Default.UnloadedPlayer.Initialize()']]],
  ['inmodbiome_878',['InModBiome',['../class_terraria_1_1_player.html#aee1d82f69be88d14a9be2fa765cee8d9',1,'Terraria::Player']]],
  ['inneroutline_879',['InnerOutline',['../class_terraria_1_1_world_building_1_1_mod_shapes_1_1_inner_outline.html',1,'Terraria::WorldBuilding::ModShapes']]],
  ['inpcaction_880',['INPCAction',['../interface_terraria_1_1_game_content_1_1_skies_1_1_credits_roll_1_1_actions_1_1_n_p_cs_1_1_i_n_p_c_action.html',1,'Terraria::GameContent::Skies::CreditsRoll::Actions::NPCs']]],
  ['inshape_881',['InShape',['../class_terraria_1_1_world_building_1_1_modifiers_1_1_in_shape.html',1,'Terraria::WorldBuilding::Modifiers']]],
  ['instanced_882',['Instanced',['../struct_terraria_1_1_mod_loader_1_1_instanced.html',1,'Terraria::ModLoader']]],
  ['instanced_3c_20globalitem_20_3e_883',['Instanced&lt; GlobalItem &gt;',['../struct_terraria_1_1_mod_loader_1_1_instanced.html',1,'Terraria::ModLoader']]],
  ['instanced_3c_20globalnpc_20_3e_884',['Instanced&lt; GlobalNPC &gt;',['../struct_terraria_1_1_mod_loader_1_1_instanced.html',1,'Terraria::ModLoader']]],
  ['instanced_3c_20globalprojectile_20_3e_885',['Instanced&lt; GlobalProjectile &gt;',['../struct_terraria_1_1_mod_loader_1_1_instanced.html',1,'Terraria::ModLoader']]],
  ['instanceenumerator_886',['InstanceEnumerator',['../struct_terraria_1_1_mod_loader_1_1_core_1_1_hook_list_1_1_instance_enumerator.html',1,'Terraria::ModLoader::Core::HookList']]],
  ['instanceperentity_887',['InstancePerEntity',['../class_terraria_1_1_mod_loader_1_1_global_type.html#aefee6bbda59e6c2119accbd942226516',1,'Terraria::ModLoader::GlobalType']]],
  ['intrange_888',['IntRange',['../struct_terraria_1_1_utilities_1_1_int_range.html',1,'Terraria::Utilities']]],
  ['invasion_889',['invasion',['../struct_terraria_1_1_mod_loader_1_1_n_p_c_spawn_info.html#a8eb193778914243d9a2a00f08b1bcf67',1,'Terraria::ModLoader::NPCSpawnInfo']]],
  ['inzonepurity_890',['InZonePurity',['../class_terraria_1_1_player.html#afca10a763a513895301070f8e6a66c60',1,'Terraria::Player']]],
  ['ioexception_891',['IOException',['../class_i_o_exception.html',1,'']]],
  ['ioimpl_892',['IOImpl',['../class_terraria_1_1_mod_loader_1_1_i_o_1_1_tile_i_o_1_1_i_o_impl.html',1,'Terraria::ModLoader::IO::TileIO']]],
  ['ioimpl_3c_20modtile_2c_20tileentry_20_3e_893',['IOImpl&lt; ModTile, TileEntry &gt;',['../class_terraria_1_1_mod_loader_1_1_i_o_1_1_tile_i_o_1_1_i_o_impl.html',1,'Terraria::ModLoader::IO::TileIO']]],
  ['ioimpl_3c_20modwall_2c_20wallentry_20_3e_894',['IOImpl&lt; ModWall, WallEntry &gt;',['../class_terraria_1_1_mod_loader_1_1_i_o_1_1_tile_i_o_1_1_i_o_impl.html',1,'Terraria::ModLoader::IO::TileIO']]],
  ['ionplayerjoining_895',['IOnPlayerJoining',['../interface_terraria_1_1_game_content_1_1_i_on_player_joining.html',1,'Terraria::GameContent']]],
  ['iparticle_896',['IParticle',['../interface_terraria_1_1_graphics_1_1_renderers_1_1_i_particle.html',1,'Terraria::Graphics::Renderers']]],
  ['ipcbase_897',['IPCBase',['../class_terraria_1_1_social_1_1_we_game_1_1_i_p_c_base.html',1,'Terraria::Social::WeGame']]],
  ['ipcclient_898',['IPCClient',['../class_terraria_1_1_social_1_1_we_game_1_1_i_p_c_client.html',1,'Terraria::Social::WeGame']]],
  ['ipccontent_899',['IPCContent',['../class_terraria_1_1_social_1_1_we_game_1_1_i_p_c_content.html',1,'Terraria::Social::WeGame']]],
  ['ipcmessage_900',['IPCMessage',['../class_terraria_1_1_social_1_1_we_game_1_1_i_p_c_message.html',1,'Terraria::Social::WeGame']]],
  ['ipcserver_901',['IPCServer',['../class_terraria_1_1_social_1_1_we_game_1_1_i_p_c_server.html',1,'Terraria::Social::WeGame']]],
  ['ipersistentperplayercontent_902',['IPersistentPerPlayerContent',['../interface_terraria_1_1_game_content_1_1_i_persistent_per_player_content.html',1,'Terraria::GameContent']]],
  ['ipersistentperworldcontent_903',['IPersistentPerWorldContent',['../interface_terraria_1_1_game_content_1_1_i_persistent_per_world_content.html',1,'Terraria::GameContent']]],
  ['iplayeraction_904',['IPlayerAction',['../interface_terraria_1_1_game_content_1_1_skies_1_1_credits_roll_1_1_actions_1_1_players_1_1_i_player_action.html',1,'Terraria::GameContent::Skies::CreditsRoll::Actions::Players']]],
  ['iplayerrenderer_905',['IPlayerRenderer',['../interface_terraria_1_1_graphics_1_1_renderers_1_1_i_player_renderer.html',1,'Terraria::Graphics::Renderers']]],
  ['iplayerresourcesdisplayset_906',['IPlayerResourcesDisplaySet',['../interface_terraria_1_1_game_content_1_1_u_i_1_1_i_player_resources_display_set.html',1,'Terraria::GameContent::UI']]],
  ['ipooledparticle_907',['IPooledParticle',['../interface_terraria_1_1_graphics_1_1_renderers_1_1_i_pooled_particle.html',1,'Terraria::Graphics::Renderers']]],
  ['ipowersubcategoryelement_908',['IPowerSubcategoryElement',['../interface_terraria_1_1_game_content_1_1_creative_1_1_i_power_subcategory_element.html',1,'Terraria::GameContent::Creative']]],
  ['ipreferenceproviderelement_909',['IPreferenceProviderElement',['../interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_preference_provider_element.html',1,'Terraria::GameContent::Bestiary']]],
  ['iprojectilesource_910',['IProjectileSource',['../interface_terraria_1_1_data_structures_1_1_i_projectile_source.html',1,'Terraria::DataStructures']]],
  ['iprovideitemconditiondescription_911',['IProvideItemConditionDescription',['../interface_terraria_1_1_game_content_1_1_item_drop_rules_1_1_i_provide_item_condition_description.html',1,'Terraria::GameContent::ItemDropRules']]],
  ['iprovidereports_912',['IProvideReports',['../interface_terraria_1_1_data_structures_1_1_i_provide_reports.html',1,'Terraria::DataStructures']]],
  ['iprovidesearchfilterstring_913',['IProvideSearchFilterString',['../interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_provide_search_filter_string.html',1,'Terraria::GameContent::Bestiary']]],
  ['iprovidesliderelement_914',['IProvideSliderElement',['../interface_terraria_1_1_game_content_1_1_creative_1_1_i_provide_slider_element.html',1,'Terraria::GameContent::Creative']]],
  ['irejectionreason_915',['IRejectionReason',['../class_i_rejection_reason.html',1,'']]],
  ['isanglerquestavailable_916',['IsAnglerQuestAvailable',['../class_terraria_1_1_mod_loader_1_1_mod_item.html#a96dd26858841172db14aa3798635c2ba',1,'Terraria.ModLoader.ModItem.IsAnglerQuestAvailable()'],['../class_terraria_1_1_mod_loader_1_1_global_item.html#a5a61ec22b6991616cad881bfc21c0696',1,'Terraria.ModLoader.GlobalItem.IsAnglerQuestAvailable()']]],
  ['isarmorset_917',['IsArmorSet',['../class_terraria_1_1_mod_loader_1_1_mod_item.html#a324513758f139965b9c5d13c588c5517',1,'Terraria.ModLoader.ModItem.IsArmorSet()'],['../class_terraria_1_1_mod_loader_1_1_global_item.html#a9ea562f4cb6d576abae4b59452e7bccd',1,'Terraria.ModLoader.GlobalItem.IsArmorSet()']]],
  ['isavailable_918',['IsAvailable',['../class_terraria_1_1_mod_loader_1_1_mod_menu.html#a85b24b0deceea643b4a93b25ea80b10c',1,'Terraria::ModLoader::ModMenu']]],
  ['isbiomeactive_919',['IsBiomeActive',['../class_terraria_1_1_mod_loader_1_1_mod_biome.html#a23bf4682286024ffbc1c1c072b2196bb',1,'Terraria::ModLoader::ModBiome']]],
  ['isbloodmoonandnotfromstatue_920',['IsBloodMoonAndNotFromStatue',['../class_terraria_1_1_game_content_1_1_item_drop_rules_1_1_conditions_1_1_is_blood_moon_and_not_from_statue.html',1,'Terraria::GameContent::ItemDropRules::Conditions']]],
  ['ischristmas_921',['IsChristmas',['../class_terraria_1_1_game_content_1_1_item_drop_rules_1_1_conditions_1_1_is_christmas.html',1,'Terraria::GameContent::ItemDropRules::Conditions']]],
  ['iscorruption_922',['IsCorruption',['../class_terraria_1_1_game_content_1_1_item_drop_rules_1_1_conditions_1_1_is_corruption.html',1,'Terraria::GameContent::ItemDropRules::Conditions']]],
  ['iscorruptionandnotexpert_923',['IsCorruptionAndNotExpert',['../class_terraria_1_1_game_content_1_1_item_drop_rules_1_1_conditions_1_1_is_corruption_and_not_expert.html',1,'Terraria::GameContent::ItemDropRules::Conditions']]],
  ['iscrimson_924',['IsCrimson',['../class_terraria_1_1_game_content_1_1_item_drop_rules_1_1_conditions_1_1_is_crimson.html',1,'Terraria::GameContent::ItemDropRules::Conditions']]],
  ['iscrimsonandnotexpert_925',['IsCrimsonAndNotExpert',['../class_terraria_1_1_game_content_1_1_item_drop_rules_1_1_conditions_1_1_is_crimson_and_not_expert.html',1,'Terraria::GameContent::ItemDropRules::Conditions']]],
  ['isearchfilter_926',['ISearchFilter',['../interface_terraria_1_1_data_structures_1_1_i_search_filter.html',1,'Terraria::DataStructures']]],
  ['isearchfilter_3c_20bestiaryentry_20_3e_927',['ISearchFilter&lt; BestiaryEntry &gt;',['../interface_terraria_1_1_data_structures_1_1_i_search_filter.html',1,'Terraria::DataStructures']]],
  ['isearchfilter_3c_20item_20_3e_928',['ISearchFilter&lt; Item &gt;',['../interface_terraria_1_1_data_structures_1_1_i_search_filter.html',1,'Terraria::DataStructures']]],
  ['isempty_929',['IsEmpty',['../class_terraria_1_1_world_building_1_1_modifiers_1_1_is_empty.html',1,'Terraria::WorldBuilding::Modifiers']]],
  ['isexpert_930',['IsExpert',['../class_terraria_1_1_game_content_1_1_item_drop_rules_1_1_conditions_1_1_is_expert.html',1,'Terraria::GameContent::ItemDropRules::Conditions']]],
  ['ishadereffect_931',['IShaderEffect',['../interface_terraria_1_1_game_content_1_1_skies_1_1_credits_roll_1_1_segments_1_1_player_segment_1_1_i_shader_effect.html',1,'Terraria.GameContent.Skies.CreditsRoll.Segments.PlayerSegment.IShaderEffect'],['../interface_terraria_1_1_game_content_1_1_skies_1_1_credits_roll_1_1_segments_1_1_sprite_segment_1_1_i_shader_effect.html',1,'Terraria.GameContent.Skies.CreditsRoll.Segments.SpriteSegment.IShaderEffect']]],
  ['ishardmode_932',['IsHardmode',['../class_terraria_1_1_game_content_1_1_item_drop_rules_1_1_conditions_1_1_is_hardmode.html',1,'Terraria::GameContent::ItemDropRules::Conditions']]],
  ['isheadlayer_933',['IsHeadLayer',['../class_terraria_1_1_mod_loader_1_1_player_draw_layer.html#a75c79c6584246557a3099938e4dc81de',1,'Terraria::ModLoader::PlayerDrawLayer']]],
  ['ishoppersonalitytrait_934',['IShopPersonalityTrait',['../interface_terraria_1_1_game_content_1_1_personalities_1_1_i_shop_personality_trait.html',1,'Terraria::GameContent::Personalities']]],
  ['isimulationconditionsetter_935',['ISimulationConditionSetter',['../interface_terraria_1_1_game_content_1_1_loot_simulation_1_1_i_simulation_condition_setter.html',1,'Terraria::GameContent::LootSimulation']]],
  ['isloadingenabled_936',['IsLoadingEnabled',['../interface_terraria_1_1_mod_loader_1_1_i_loadable.html#a99cb7624fdbd3514ea3af077a6d0e63e',1,'Terraria.ModLoader.ILoadable.IsLoadingEnabled()'],['../class_terraria_1_1_mod_loader_1_1_mod_tile_entity.html#ad802a41427e54c3bcadc616d3bf23aa5',1,'Terraria.ModLoader.ModTileEntity.IsLoadingEnabled()'],['../class_terraria_1_1_mod_loader_1_1_mod_type.html#a041087074eaff42734190d565f13ce1a',1,'Terraria.ModLoader.ModType.IsLoadingEnabled()']]],
  ['islockedchest_937',['IsLockedChest',['../class_terraria_1_1_mod_loader_1_1_mod_tile.html#a73168146e18265de2739d619377b8adf',1,'Terraria::ModLoader::ModTile']]],
  ['ismartinteractblockreasonprovider_938',['ISmartInteractBlockReasonProvider',['../interface_terraria_1_1_game_content_1_1_object_interactions_1_1_i_smart_interact_block_reason_provider.html',1,'Terraria::GameContent::ObjectInteractions']]],
  ['ismartinteractcandidate_939',['ISmartInteractCandidate',['../interface_terraria_1_1_game_content_1_1_object_interactions_1_1_i_smart_interact_candidate.html',1,'Terraria::GameContent::ObjectInteractions']]],
  ['ismartinteractcandidateprovider_940',['ISmartInteractCandidateProvider',['../interface_terraria_1_1_game_content_1_1_object_interactions_1_1_i_smart_interact_candidate_provider.html',1,'Terraria::GameContent::ObjectInteractions']]],
  ['ismastermode_941',['IsMasterMode',['../class_terraria_1_1_game_content_1_1_item_drop_rules_1_1_conditions_1_1_is_master_mode.html',1,'Terraria::GameContent::ItemDropRules::Conditions']]],
  ['ismodifier_942',['isModifier',['../class_terraria_1_1_mod_loader_1_1_drawable_tooltip_line.html#a744e18254de99adea41f1c75e6ae3bf6',1,'Terraria.ModLoader.DrawableTooltipLine.isModifier()'],['../class_terraria_1_1_mod_loader_1_1_tooltip_line.html#a5a998c87573cd4944c0966e7b3409588',1,'Terraria.ModLoader.TooltipLine.isModifier()']]],
  ['ismodifierbad_943',['isModifierBad',['../class_terraria_1_1_mod_loader_1_1_drawable_tooltip_line.html#a7b144755d23bcddbfc52210385710f37',1,'Terraria.ModLoader.DrawableTooltipLine.isModifierBad()'],['../class_terraria_1_1_mod_loader_1_1_tooltip_line.html#a7efdb3feea743c6755643e82c5e5ff3b',1,'Terraria.ModLoader.TooltipLine.isModifierBad()']]],
  ['isnotsolid_944',['IsNotSolid',['../class_terraria_1_1_world_building_1_1_modifiers_1_1_is_not_solid.html',1,'Terraria::WorldBuilding::Modifiers']]],
  ['isocialmodule_945',['ISocialModule',['../interface_terraria_1_1_social_1_1_i_social_module.html',1,'Terraria::Social']]],
  ['isocket_946',['ISocket',['../interface_terraria_1_1_net_1_1_sockets_1_1_i_socket.html',1,'Terraria::Net::Sockets']]],
  ['isprimarybiome_947',['IsPrimaryBiome',['../class_terraria_1_1_mod_loader_1_1_mod_biome.html#af75a5a9efa286109c702edbd3c49c748',1,'Terraria::ModLoader::ModBiome']]],
  ['ispriteaction_948',['ISpriteAction',['../interface_terraria_1_1_game_content_1_1_skies_1_1_credits_roll_1_1_actions_1_1_sprites_1_1_i_sprite_action.html',1,'Terraria::GameContent::Skies::CreditsRoll::Actions::Sprites']]],
  ['ispumpkinmoon_949',['IsPumpkinMoon',['../class_terraria_1_1_game_content_1_1_item_drop_rules_1_1_conditions_1_1_is_pumpkin_moon.html',1,'Terraria::GameContent::ItemDropRules::Conditions']]],
  ['isquestfish_950',['IsQuestFish',['../class_terraria_1_1_mod_loader_1_1_mod_item.html#a146b63f35e144131997ef0e081a9f500',1,'Terraria::ModLoader::ModItem']]],
  ['issceneeffectactive_951',['IsSceneEffectActive',['../class_terraria_1_1_mod_loader_1_1_mod_biome.html#a3453119cc8f1f3fa6b31672c215cd6b6',1,'Terraria::ModLoader::ModBiome']]],
  ['isselected_952',['IsSelected',['../class_terraria_1_1_mod_loader_1_1_mod_boss_bar_style.html#a199d5f537488cb564a584a7e3663fe85',1,'Terraria::ModLoader::ModBossBarStyle']]],
  ['issolid_953',['IsSolid',['../class_terraria_1_1_world_building_1_1_conditions_1_1_is_solid.html',1,'Terraria.WorldBuilding.Conditions.IsSolid'],['../class_terraria_1_1_world_building_1_1_modifiers_1_1_is_solid.html',1,'Terraria.WorldBuilding.Modifiers.IsSolid']]],
  ['issuereport_954',['IssueReport',['../class_terraria_1_1_data_structures_1_1_issue_report.html',1,'Terraria::DataStructures']]],
  ['issuereportsindicator_955',['IssueReportsIndicator',['../class_terraria_1_1_game_content_1_1_u_i_1_1_issue_reports_indicator.html',1,'Terraria::GameContent::UI']]],
  ['istaticportmapping_956',['IStaticPortMapping',['../interface_n_a_t_u_p_n_p_lib_1_1_i_static_port_mapping.html',1,'NATUPNPLib']]],
  ['istaticportmappingcollection_957',['IStaticPortMappingCollection',['../interface_n_a_t_u_p_n_p_lib_1_1_i_static_port_mapping_collection.html',1,'NATUPNPLib']]],
  ['istile_958',['IsTile',['../class_terraria_1_1_world_building_1_1_conditions_1_1_is_tile.html',1,'Terraria::WorldBuilding::Conditions']]],
  ['istouching_959',['IsTouching',['../class_terraria_1_1_world_building_1_1_modifiers_1_1_is_touching.html',1,'Terraria::WorldBuilding::Modifiers']]],
  ['istouchingair_960',['IsTouchingAir',['../class_terraria_1_1_world_building_1_1_modifiers_1_1_is_touching_air.html',1,'Terraria::WorldBuilding::Modifiers']]],
  ['isusingspecificaivalues_961',['IsUsingSpecificAIValues',['../class_terraria_1_1_game_content_1_1_item_drop_rules_1_1_conditions_1_1_is_using_specific_a_i_values.html',1,'Terraria::GameContent::ItemDropRules::Conditions']]],
  ['isvanityset_962',['IsVanitySet',['../class_terraria_1_1_mod_loader_1_1_equip_texture.html#acd4647b2d645c915743daa3b734919f7',1,'Terraria.ModLoader.EquipTexture.IsVanitySet()'],['../class_terraria_1_1_mod_loader_1_1_mod_item.html#a7411ef16c0702304775364b6c177b690',1,'Terraria.ModLoader.ModItem.IsVanitySet()'],['../class_terraria_1_1_mod_loader_1_1_global_item.html#afc66c0f98cbc3d51a577b847d011d711',1,'Terraria.ModLoader.GlobalItem.IsVanitySet()']]],
  ['itaghandler_963',['ITagHandler',['../interface_terraria_1_1_u_i_1_1_chat_1_1_i_tag_handler.html',1,'Terraria::UI::Chat']]],
  ['item_964',['Item',['../class_terraria_1_1_mod_loader_1_1_mod_item.html#abc96a407c86a78570037ef4318d9c112',1,'Terraria.ModLoader.ModItem.Item()'],['../class_terraria_1_1_mod_loader_1_1_equip_texture.html#a1ef4348349e6b437eac4d37c7093b148',1,'Terraria.ModLoader.EquipTexture.Item()'],['../class_terraria_1_1_item.html',1,'Terraria.Item']]],
  ['itemcraftcondition_965',['ItemCraftCondition',['../class_terraria_1_1_game_content_1_1_achievements_1_1_item_craft_condition.html',1,'Terraria::GameContent::Achievements']]],
  ['itemcreationcontext_966',['ItemCreationContext',['../class_terraria_1_1_mod_loader_1_1_item_creation_context.html',1,'Terraria::ModLoader']]],
  ['itemdefinition_967',['ItemDefinition',['../class_terraria_1_1_mod_loader_1_1_config_1_1_item_definition.html',1,'Terraria::ModLoader::Config']]],
  ['itemdefinitionelement_968',['ItemDefinitionElement',['../class_terraria_1_1_mod_loader_1_1_config_1_1_u_i_1_1_item_definition_element.html',1,'Terraria::ModLoader::Config::UI']]],
  ['itemdrop_969',['ItemDrop',['../class_terraria_1_1_mod_loader_1_1_mod_block_type.html#ab38346a81262f8dce57d4cd067bab64e',1,'Terraria::ModLoader::ModBlockType']]],
  ['itemdropattemptresult_970',['ItemDropAttemptResult',['../struct_terraria_1_1_game_content_1_1_item_drop_rules_1_1_item_drop_attempt_result.html',1,'Terraria::GameContent::ItemDropRules']]],
  ['itemdropbestiaryinfoelement_971',['ItemDropBestiaryInfoElement',['../class_terraria_1_1_game_content_1_1_bestiary_1_1_item_drop_bestiary_info_element.html',1,'Terraria::GameContent::Bestiary']]],
  ['itemdropdatabase_972',['ItemDropDatabase',['../class_terraria_1_1_game_content_1_1_item_drop_rules_1_1_item_drop_database.html',1,'Terraria::GameContent::ItemDropRules']]],
  ['itemdropresolver_973',['ItemDropResolver',['../class_terraria_1_1_game_content_1_1_item_drop_rules_1_1_item_drop_resolver.html',1,'Terraria::GameContent::ItemDropRules']]],
  ['itemdroprule_974',['ItemDropRule',['../class_terraria_1_1_game_content_1_1_item_drop_rules_1_1_item_drop_rule.html',1,'Terraria::GameContent::ItemDropRules']]],
  ['itemdropwithconditionrule_975',['ItemDropWithConditionRule',['../class_terraria_1_1_game_content_1_1_item_drop_rules_1_1_item_drop_with_condition_rule.html',1,'Terraria::GameContent::ItemDropRules']]],
  ['itemfromcatchingnpcbestiaryinfoelement_976',['ItemFromCatchingNPCBestiaryInfoElement',['../class_terraria_1_1_game_content_1_1_bestiary_1_1_item_from_catching_n_p_c_bestiary_info_element.html',1,'Terraria::GameContent::Bestiary']]],
  ['itemgroupandorderingroup_977',['ItemGroupAndOrderInGroup',['../struct_terraria_1_1_i_d_1_1_content_samples_1_1_creative_helper_1_1_item_group_and_order_in_group.html',1,'Terraria::ID::ContentSamples::CreativeHelper']]],
  ['itemholdstyleid_978',['ItemHoldStyleID',['../class_terraria_1_1_i_d_1_1_item_hold_style_i_d.html',1,'Terraria::ID']]],
  ['itemid_979',['ItemID',['../class_terraria_1_1_i_d_1_1_item_i_d.html',1,'Terraria::ID']]],
  ['iteminstallinfo_980',['ItemInstallInfo',['../struct_terraria_1_1_social_1_1_steam_1_1_workshop_helper_1_1_item_install_info.html',1,'Terraria::Social::Steam::WorkshopHelper']]],
  ['itempickupcondition_981',['ItemPickupCondition',['../class_terraria_1_1_game_content_1_1_achievements_1_1_item_pickup_condition.html',1,'Terraria::GameContent::Achievements']]],
  ['itemrarity_982',['ItemRarity',['../class_terraria_1_1_game_content_1_1_u_i_1_1_item_rarity.html',1,'Terraria::GameContent::UI']]],
  ['itemshopsellbackhelper_983',['ItemShopSellbackHelper',['../class_terraria_1_1_game_content_1_1_item_shop_sellback_helper.html',1,'Terraria::GameContent']]],
  ['itemslot_984',['ItemSlot',['../class_terraria_1_1_u_i_1_1_item_slot.html',1,'Terraria::UI']]],
  ['itemsorting_985',['ItemSorting',['../class_terraria_1_1_u_i_1_1_item_sorting.html',1,'Terraria::UI']]],
  ['itemspace_986',['ItemSpace',['../class_terraria_1_1_mod_loader_1_1_global_item.html#af6ed20f0b7f9e7b84a84bb31ca269d3f',1,'Terraria.ModLoader.GlobalItem.ItemSpace()'],['../class_terraria_1_1_mod_loader_1_1_mod_item.html#ae360f7809f0151bf1bdbc78dc5dae8c1',1,'Terraria.ModLoader.ModItem.ItemSpace()']]],
  ['itemspacestatus_987',['ItemSpaceStatus',['../struct_terraria_1_1_player_1_1_item_space_status.html',1,'Terraria::Player']]],
  ['itemssacrificedunlockstracker_988',['ItemsSacrificedUnlocksTracker',['../class_terraria_1_1_game_content_1_1_creative_1_1_items_sacrificed_unlocks_tracker.html',1,'Terraria::GameContent::Creative']]],
  ['itemsyncpersistentstats_989',['ItemSyncPersistentStats',['../struct_terraria_1_1_data_structures_1_1_item_sync_persistent_stats.html',1,'Terraria::DataStructures']]],
  ['itemtaghandler_990',['ItemTagHandler',['../class_terraria_1_1_game_content_1_1_u_i_1_1_chat_1_1_item_tag_handler.html',1,'Terraria::GameContent::UI::Chat']]],
  ['itemtooltip_991',['ItemTooltip',['../class_terraria_1_1_u_i_1_1_item_tooltip.html',1,'Terraria::UI']]],
  ['itemusestyleid_992',['ItemUseStyleID',['../class_terraria_1_1_i_d_1_1_item_use_style_i_d.html',1,'Terraria::ID']]],
  ['itownnpcprofile_993',['ITownNPCProfile',['../interface_terraria_1_1_game_content_1_1_i_town_n_p_c_profile.html',1,'Terraria::GameContent']]],
  ['iupnpnat_994',['IUPnPNAT',['../interface_n_a_t_u_p_n_p_lib_1_1_i_u_pn_p_n_a_t.html',1,'NATUPNPLib']]],
  ['ivalueprovider_995',['IValueProvider',['../class_i_value_provider.html',1,'']]],
  ['ivertextype_996',['IVertexType',['../class_i_vertex_type.html',1,'']]]
];
