var searchData=
[
  ['iachievementtracker_796',['IAchievementTracker',['../interface_terraria_1_1_achievements_1_1_i_achievement_tracker.html',1,'Terraria::Achievements']]],
  ['iassetreader_797',['IAssetReader',['../class_i_asset_reader.html',1,'']]],
  ['iaudiosystem_798',['IAudioSystem',['../interface_terraria_1_1_audio_1_1_i_audio_system.html',1,'Terraria::Audio']]],
  ['iaudiotrack_799',['IAudioTrack',['../interface_terraria_1_1_audio_1_1_i_audio_track.html',1,'Terraria::Audio']]],
  ['iballcontactlistener_800',['IBallContactListener',['../interface_terraria_1_1_physics_1_1_i_ball_contact_listener.html',1,'Terraria::Physics']]],
  ['ibestiarybackgroundimagepathandcolorprovider_801',['IBestiaryBackgroundImagePathAndColorProvider',['../interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_bestiary_background_image_path_and_color_provider.html',1,'Terraria::GameContent::Bestiary']]],
  ['ibestiarybackgroundoverlayandcolorprovider_802',['IBestiaryBackgroundOverlayAndColorProvider',['../interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_bestiary_background_overlay_and_color_provider.html',1,'Terraria::GameContent::Bestiary']]],
  ['ibestiaryentrydisplayindex_803',['IBestiaryEntryDisplayIndex',['../interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_bestiary_entry_display_index.html',1,'Terraria::GameContent::Bestiary']]],
  ['ibestiaryentryfilter_804',['IBestiaryEntryFilter',['../interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_bestiary_entry_filter.html',1,'Terraria::GameContent::Bestiary']]],
  ['ibestiaryinfoelement_805',['IBestiaryInfoElement',['../interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_bestiary_info_element.html',1,'Terraria::GameContent::Bestiary']]],
  ['ibestiarysortstep_806',['IBestiarySortStep',['../interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_bestiary_sort_step.html',1,'Terraria::GameContent::Bestiary']]],
  ['ibestiaryuicollectioninfoprovider_807',['IBestiaryUICollectionInfoProvider',['../interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_bestiary_u_i_collection_info_provider.html',1,'Terraria::GameContent::Bestiary']]],
  ['ibigprogressbar_808',['IBigProgressBar',['../interface_terraria_1_1_game_content_1_1_u_i_1_1_big_progress_bar_1_1_i_big_progress_bar.html',1,'Terraria::GameContent::UI::BigProgressBar']]],
  ['ibuilderacctoggle_809',['IBuilderAccToggle',['../interface_terraria_1_1_game_content_1_1_u_i_1_1_builder_acc_toggles_u_i_1_1_i_builder_acc_toggle.html',1,'Terraria::GameContent::UI::BuilderAccTogglesUI']]],
  ['icehousebuilder_810',['IceHouseBuilder',['../class_terraria_1_1_game_content_1_1_biomes_1_1_cave_house_1_1_ice_house_builder.html',1,'Terraria::GameContent::Biomes::CaveHouse']]],
  ['iceshader_811',['IceShader',['../class_terraria_1_1_game_content_1_1_r_g_b_1_1_ice_shader.html',1,'Terraria::GameContent::RGB']]],
  ['ichatcommand_812',['IChatCommand',['../interface_terraria_1_1_chat_1_1_commands_1_1_i_chat_command.html',1,'Terraria::Chat::Commands']]],
  ['ichatmonitor_813',['IChatMonitor',['../interface_terraria_1_1_game_content_1_1_u_i_1_1_chat_1_1_i_chat_monitor.html',1,'Terraria::GameContent::UI::Chat']]],
  ['ichatprocessor_814',['IChatProcessor',['../interface_terraria_1_1_chat_1_1_i_chat_processor.html',1,'Terraria::Chat']]],
  ['icloneable_815',['ICloneable',['../class_i_cloneable.html',1,'']]],
  ['icolorable_816',['IColorable',['../interface_terraria_1_1_game_content_1_1_u_i_1_1_elements_1_1_i_colorable.html',1,'Terraria::GameContent::UI::Elements']]],
  ['icomparable_817',['IComparable',['../class_i_comparable.html',1,'']]],
  ['icomparer_818',['IComparer',['../class_i_comparer.html',1,'']]],
  ['icomparer_3c_20tuple_3c_20int_2c_20float_20_3e_3e_819',['IComparer&lt; Tuple&lt; int, float &gt;&gt;',['../class_i_comparer_3_01_tuple_3_01int_00_01float_01_4_4.html',1,'']]],
  ['iconcolor_820',['iconColor',['../struct_terraria_1_1_data_structures_1_1_boss_bar_draw_params.html#a43ceb9ba4eb31e94471fb7be98d0376c',1,'Terraria::DataStructures::BossBarDrawParams']]],
  ['icondition_821',['ICondition',['../interface_terraria_1_1_recipe_1_1_i_condition.html',1,'Terraria::Recipe']]],
  ['iconframe_822',['iconFrame',['../struct_terraria_1_1_data_structures_1_1_boss_bar_draw_params.html#aa7457e6112854a8ce2e3fc090ef88988',1,'Terraria::DataStructures::BossBarDrawParams']]],
  ['iconscale_823',['iconScale',['../struct_terraria_1_1_data_structures_1_1_boss_bar_draw_params.html#ac315e379926e9c49d5378325d1318a59',1,'Terraria::DataStructures::BossBarDrawParams']]],
  ['icontentvalidator_824',['IContentValidator',['../class_i_content_validator.html',1,'']]],
  ['icontexture_825',['iconTexture',['../struct_terraria_1_1_data_structures_1_1_boss_bar_draw_params.html#a6da99506d15cefc246b173e4562d6996',1,'Terraria::DataStructures::BossBarDrawParams']]],
  ['icreativeitemsortstep_826',['ICreativeItemSortStep',['../interface_terraria_1_1_game_content_1_1_creative_1_1_i_creative_item_sort_step.html',1,'Terraria::GameContent::Creative']]],
  ['icreativepower_827',['ICreativePower',['../interface_terraria_1_1_game_content_1_1_creative_1_1_i_creative_power.html',1,'Terraria::GameContent::Creative']]],
  ['icreditsrollsegment_828',['ICreditsRollSegment',['../interface_terraria_1_1_game_content_1_1_skies_1_1_credits_roll_1_1_i_credits_roll_segment.html',1,'Terraria::GameContent::Skies::CreditsRoll']]],
  ['icreditsrollsegmentaction_829',['ICreditsRollSegmentAction',['../interface_terraria_1_1_game_content_1_1_skies_1_1_credits_roll_1_1_i_credits_roll_segment_action.html',1,'Terraria::GameContent::Skies::CreditsRoll']]],
  ['icreditsrollsegmentaction_3c_20npc_20_3e_830',['ICreditsRollSegmentAction&lt; NPC &gt;',['../interface_terraria_1_1_game_content_1_1_skies_1_1_credits_roll_1_1_i_credits_roll_segment_action.html',1,'Terraria::GameContent::Skies::CreditsRoll']]],
  ['icreditsrollsegmentaction_3c_20player_20_3e_831',['ICreditsRollSegmentAction&lt; Player &gt;',['../interface_terraria_1_1_game_content_1_1_skies_1_1_credits_roll_1_1_i_credits_roll_segment_action.html',1,'Terraria::GameContent::Skies::CreditsRoll']]],
  ['icreditsrollsegmentaction_3c_20segments_2eloosesprite_20_3e_832',['ICreditsRollSegmentAction&lt; Segments.LooseSprite &gt;',['../interface_terraria_1_1_game_content_1_1_skies_1_1_credits_roll_1_1_i_credits_roll_segment_action.html',1,'Terraria::GameContent::Skies::CreditsRoll']]],
  ['ientitywithglobals_833',['IEntityWithGlobals',['../interface_terraria_1_1_mod_loader_1_1_i_entity_with_globals.html',1,'Terraria::ModLoader']]],
  ['ientitywithglobals_3c_20globalitem_20_3e_834',['IEntityWithGlobals&lt; GlobalItem &gt;',['../interface_terraria_1_1_mod_loader_1_1_i_entity_with_globals.html',1,'Terraria::ModLoader']]],
  ['ientitywithglobals_3c_20globalnpc_20_3e_835',['IEntityWithGlobals&lt; GlobalNPC &gt;',['../interface_terraria_1_1_mod_loader_1_1_i_entity_with_globals.html',1,'Terraria::ModLoader']]],
  ['ientitywithglobals_3c_20globalprojectile_20_3e_836',['IEntityWithGlobals&lt; GlobalProjectile &gt;',['../interface_terraria_1_1_mod_loader_1_1_i_entity_with_globals.html',1,'Terraria::ModLoader']]],
  ['ientryfilter_837',['IEntryFilter',['../interface_terraria_1_1_data_structures_1_1_i_entry_filter.html',1,'Terraria::DataStructures']]],
  ['ientryfilter_3c_20bestiaryentry_20_3e_838',['IEntryFilter&lt; BestiaryEntry &gt;',['../interface_terraria_1_1_data_structures_1_1_i_entry_filter.html',1,'Terraria::DataStructures']]],
  ['ientryfilter_3c_20item_20_3e_839',['IEntryFilter&lt; Item &gt;',['../interface_terraria_1_1_data_structures_1_1_i_entry_filter.html',1,'Terraria::DataStructures']]],
  ['ientryicon_840',['IEntryIcon',['../interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_entry_icon.html',1,'Terraria::GameContent::Bestiary']]],
  ['ientrysortstep_841',['IEntrySortStep',['../interface_terraria_1_1_data_structures_1_1_i_entry_sort_step.html',1,'Terraria::DataStructures']]],
  ['ientrysortstep_3c_20bestiaryentry_20_3e_842',['IEntrySortStep&lt; BestiaryEntry &gt;',['../interface_terraria_1_1_data_structures_1_1_i_entry_sort_step.html',1,'Terraria::DataStructures']]],
  ['ientrysortstep_3c_20int_20_3e_843',['IEntrySortStep&lt; int &gt;',['../interface_terraria_1_1_data_structures_1_1_i_entry_sort_step.html',1,'Terraria::DataStructures']]],
  ['ienumerable_844',['IEnumerable',['../class_i_enumerable.html',1,'']]],
  ['ienumerable_3c_20keyvaluepair_3c_20string_2c_20object_20_3e_3e_845',['IEnumerable&lt; KeyValuePair&lt; string, object &gt;&gt;',['../class_i_enumerable_3_01_key_value_pair_3_01string_00_01object_01_4_4.html',1,'']]],
  ['iequatable_846',['IEquatable',['../class_i_equatable.html',1,'']]],
  ['ifilebrowser_847',['IFileBrowser',['../interface_terraria_1_1_utilities_1_1_file_browser_1_1_i_file_browser.html',1,'Terraria::Utilities::FileBrowser']]],
  ['ifilterinfoprovider_848',['IFilterInfoProvider',['../interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_filter_info_provider.html',1,'Terraria::GameContent::Bestiary']]],
  ['igroupoptionbutton_849',['IGroupOptionButton',['../interface_terraria_1_1_game_content_1_1_u_i_1_1_elements_1_1_i_group_option_button.html',1,'Terraria::GameContent::UI::Elements']]],
  ['ihavebackbuttoncommand_850',['IHaveBackButtonCommand',['../interface_terraria_1_1_u_i_1_1_i_have_back_button_command.html',1,'Terraria::UI']]],
  ['iingamenotification_851',['IInGameNotification',['../interface_terraria_1_1_u_i_1_1_i_in_game_notification.html',1,'Terraria::UI']]],
  ['iitembestiaryinfoelement_852',['IItemBestiaryInfoElement',['../interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_item_bestiary_info_element.html',1,'Terraria::GameContent::Bestiary']]],
  ['iitemdroprule_853',['IItemDropRule',['../interface_terraria_1_1_game_content_1_1_item_drop_rules_1_1_i_item_drop_rule.html',1,'Terraria::GameContent::ItemDropRules']]],
  ['iitemdroprulechainattempt_854',['IItemDropRuleChainAttempt',['../interface_terraria_1_1_game_content_1_1_item_drop_rules_1_1_i_item_drop_rule_chain_attempt.html',1,'Terraria::GameContent::ItemDropRules']]],
  ['iitemdroprulecondition_855',['IItemDropRuleCondition',['../interface_terraria_1_1_game_content_1_1_item_drop_rules_1_1_i_item_drop_rule_condition.html',1,'Terraria::GameContent::ItemDropRules']]],
  ['iitementryfilter_856',['IItemEntryFilter',['../interface_terraria_1_1_game_content_1_1_creative_1_1_i_item_entry_filter.html',1,'Terraria::GameContent::Creative']]],
  ['ilightingengine_857',['ILightingEngine',['../interface_terraria_1_1_graphics_1_1_light_1_1_i_lighting_engine.html',1,'Terraria::Graphics::Light']]],
  ['iloadable_858',['ILoadable',['../interface_terraria_1_1_mod_loader_1_1_i_loadable.html',1,'Terraria::ModLoader']]],
  ['iloader_859',['ILoader',['../interface_terraria_1_1_mod_loader_1_1_i_loader.html',1,'Terraria::ModLoader']]],
  ['imageio_860',['ImageIO',['../class_terraria_1_1_mod_loader_1_1_i_o_1_1_image_i_o.html',1,'Terraria::ModLoader::IO']]],
  ['imanuallyordereduielement_861',['IManuallyOrderedUIElement',['../interface_terraria_1_1_game_content_1_1_u_i_1_1_elements_1_1_i_manually_ordered_u_i_element.html',1,'Terraria::GameContent::UI::Elements']]],
  ['imaplayer_862',['IMapLayer',['../interface_terraria_1_1_map_1_1_i_map_layer.html',1,'Terraria::Map']]],
  ['immediatespritebatchforplayerdyeseffect_863',['ImmediateSpritebatchForPlayerDyesEffect',['../class_terraria_1_1_game_content_1_1_skies_1_1_credits_roll_1_1_segments_1_1_player_segment_1_1_i80cf05f0478e3894be72e0a77d29c1ad.html',1,'Terraria::GameContent::Skies::CreditsRoll::Segments::PlayerSegment']]],
  ['imodtype_864',['IModType',['../interface_terraria_1_1_mod_loader_1_1_i_mod_type.html',1,'Terraria::ModLoader']]],
  ['imultiplayercloseplayersoverlay_865',['IMultiplayerClosePlayersOverlay',['../interface_terraria_1_1_game_content_1_1_u_i_1_1_i_multiplayer_close_players_overlay.html',1,'Terraria::GameContent::UI']]],
  ['includecapefrontandbackinfo_866',['IncludeCapeFrontAndBackInfo',['../struct_terraria_1_1_i_d_1_1_armor_i_ds_1_1_body_1_1_sets_1_1_include_cape_front_and_back_info.html',1,'Terraria::ID::ArmorIDs::Body::Sets']]],
  ['incrementattribute_867',['IncrementAttribute',['../class_terraria_1_1_mod_loader_1_1_config_1_1_increment_attribute.html',1,'Terraria::ModLoader::Config']]],
  ['index_868',['index',['../class_terraria_1_1_mod_loader_1_1_drawable_tooltip_line.html#a91f4dbe5ede1242c5cf5b7a9764ed832',1,'Terraria::ModLoader::DrawableTooltipLine']]],
  ['ineedrendertargetcontent_869',['INeedRenderTargetContent',['../interface_terraria_1_1_game_content_1_1_i_need_render_target_content.html',1,'Terraria::GameContent']]],
  ['inesteditemdroprule_870',['INestedItemDropRule',['../interface_terraria_1_1_game_content_1_1_item_drop_rules_1_1_i_nested_item_drop_rule.html',1,'Terraria::GameContent::ItemDropRules']]],
  ['inetdiagnosticsui_871',['INetDiagnosticsUI',['../interface_terraria_1_1_u_i_1_1_i_net_diagnostics_u_i.html',1,'Terraria::UI']]],
  ['infodisplay_872',['InfoDisplay',['../class_terraria_1_1_mod_loader_1_1_info_display.html',1,'Terraria::ModLoader']]],
  ['infoname_873',['InfoName',['../class_terraria_1_1_mod_loader_1_1_info_display.html#a92fb42a5b373faf7c26581734b7c0eb3',1,'Terraria::ModLoader::InfoDisplay']]],
  ['infotosetbackcolor_874',['InfoToSetBackColor',['../struct_terraria_1_1_main_1_1_info_to_set_back_color.html',1,'Terraria::Main']]],
  ['ingamefancyui_875',['IngameFancyUI',['../class_terraria_1_1_u_i_1_1_ingame_fancy_u_i.html',1,'Terraria::UI']]],
  ['ingamenotificationstracker_876',['InGameNotificationsTracker',['../class_terraria_1_1_u_i_1_1_in_game_notifications_tracker.html',1,'Terraria::UI']]],
  ['ingamepopups_877',['InGamePopups',['../class_terraria_1_1_u_i_1_1_in_game_popups.html',1,'Terraria::UI']]],
  ['initializationcontext_878',['InitializationContext',['../class_terraria_1_1_mod_loader_1_1_initialization_context.html',1,'Terraria::ModLoader']]],
  ['initialize_879',['Initialize',['../class_terraria_1_1_mod_loader_1_1_mod_player.html#a7b06737bb45ee8fae87eb4c989b40da6',1,'Terraria.ModLoader.ModPlayer.Initialize()'],['../class_terraria_1_1_mod_loader_1_1_default_1_1_unloaded_player.html#a1510ec7c92d8e270652b914bda121137',1,'Terraria.ModLoader.Default.UnloadedPlayer.Initialize()']]],
  ['inmodbiome_880',['InModBiome',['../class_terraria_1_1_player.html#aee1d82f69be88d14a9be2fa765cee8d9',1,'Terraria::Player']]],
  ['inneroutline_881',['InnerOutline',['../class_terraria_1_1_world_building_1_1_mod_shapes_1_1_inner_outline.html',1,'Terraria::WorldBuilding::ModShapes']]],
  ['inpcaction_882',['INPCAction',['../interface_terraria_1_1_game_content_1_1_skies_1_1_credits_roll_1_1_actions_1_1_n_p_cs_1_1_i_n_p_c_action.html',1,'Terraria::GameContent::Skies::CreditsRoll::Actions::NPCs']]],
  ['inshape_883',['InShape',['../class_terraria_1_1_world_building_1_1_modifiers_1_1_in_shape.html',1,'Terraria::WorldBuilding::Modifiers']]],
  ['instanced_884',['Instanced',['../struct_terraria_1_1_mod_loader_1_1_instanced.html',1,'Terraria::ModLoader']]],
  ['instanced_3c_20globalitem_20_3e_885',['Instanced&lt; GlobalItem &gt;',['../struct_terraria_1_1_mod_loader_1_1_instanced.html',1,'Terraria::ModLoader']]],
  ['instanced_3c_20globalnpc_20_3e_886',['Instanced&lt; GlobalNPC &gt;',['../struct_terraria_1_1_mod_loader_1_1_instanced.html',1,'Terraria::ModLoader']]],
  ['instanced_3c_20globalprojectile_20_3e_887',['Instanced&lt; GlobalProjectile &gt;',['../struct_terraria_1_1_mod_loader_1_1_instanced.html',1,'Terraria::ModLoader']]],
  ['instanceenumerator_888',['InstanceEnumerator',['../struct_terraria_1_1_mod_loader_1_1_core_1_1_hook_list_1_1_instance_enumerator.html',1,'Terraria::ModLoader::Core::HookList']]],
  ['instanceperentity_889',['InstancePerEntity',['../class_terraria_1_1_mod_loader_1_1_global_type.html#aefee6bbda59e6c2119accbd942226516',1,'Terraria::ModLoader::GlobalType']]],
  ['intrange_890',['IntRange',['../struct_terraria_1_1_utilities_1_1_int_range.html',1,'Terraria::Utilities']]],
  ['invasion_891',['invasion',['../struct_terraria_1_1_mod_loader_1_1_n_p_c_spawn_info.html#a8eb193778914243d9a2a00f08b1bcf67',1,'Terraria::ModLoader::NPCSpawnInfo']]],
  ['inzonepurity_892',['InZonePurity',['../class_terraria_1_1_player.html#afca10a763a513895301070f8e6a66c60',1,'Terraria::Player']]],
  ['ioexception_893',['IOException',['../class_i_o_exception.html',1,'']]],
  ['ioimpl_894',['IOImpl',['../class_terraria_1_1_mod_loader_1_1_i_o_1_1_tile_i_o_1_1_i_o_impl.html',1,'Terraria::ModLoader::IO::TileIO']]],
  ['ioimpl_3c_20modtile_2c_20tileentry_20_3e_895',['IOImpl&lt; ModTile, TileEntry &gt;',['../class_terraria_1_1_mod_loader_1_1_i_o_1_1_tile_i_o_1_1_i_o_impl.html',1,'Terraria::ModLoader::IO::TileIO']]],
  ['ioimpl_3c_20modwall_2c_20wallentry_20_3e_896',['IOImpl&lt; ModWall, WallEntry &gt;',['../class_terraria_1_1_mod_loader_1_1_i_o_1_1_tile_i_o_1_1_i_o_impl.html',1,'Terraria::ModLoader::IO::TileIO']]],
  ['ionplayerjoining_897',['IOnPlayerJoining',['../interface_terraria_1_1_game_content_1_1_i_on_player_joining.html',1,'Terraria::GameContent']]],
  ['iparticle_898',['IParticle',['../interface_terraria_1_1_graphics_1_1_renderers_1_1_i_particle.html',1,'Terraria::Graphics::Renderers']]],
  ['ipcbase_899',['IPCBase',['../class_terraria_1_1_social_1_1_we_game_1_1_i_p_c_base.html',1,'Terraria::Social::WeGame']]],
  ['ipcclient_900',['IPCClient',['../class_terraria_1_1_social_1_1_we_game_1_1_i_p_c_client.html',1,'Terraria::Social::WeGame']]],
  ['ipccontent_901',['IPCContent',['../class_terraria_1_1_social_1_1_we_game_1_1_i_p_c_content.html',1,'Terraria::Social::WeGame']]],
  ['ipcmessage_902',['IPCMessage',['../class_terraria_1_1_social_1_1_we_game_1_1_i_p_c_message.html',1,'Terraria::Social::WeGame']]],
  ['ipcserver_903',['IPCServer',['../class_terraria_1_1_social_1_1_we_game_1_1_i_p_c_server.html',1,'Terraria::Social::WeGame']]],
  ['ipersistentperplayercontent_904',['IPersistentPerPlayerContent',['../interface_terraria_1_1_game_content_1_1_i_persistent_per_player_content.html',1,'Terraria::GameContent']]],
  ['ipersistentperworldcontent_905',['IPersistentPerWorldContent',['../interface_terraria_1_1_game_content_1_1_i_persistent_per_world_content.html',1,'Terraria::GameContent']]],
  ['iplayeraction_906',['IPlayerAction',['../interface_terraria_1_1_game_content_1_1_skies_1_1_credits_roll_1_1_actions_1_1_players_1_1_i_player_action.html',1,'Terraria::GameContent::Skies::CreditsRoll::Actions::Players']]],
  ['iplayerrenderer_907',['IPlayerRenderer',['../interface_terraria_1_1_graphics_1_1_renderers_1_1_i_player_renderer.html',1,'Terraria::Graphics::Renderers']]],
  ['iplayerresourcesdisplayset_908',['IPlayerResourcesDisplaySet',['../interface_terraria_1_1_game_content_1_1_u_i_1_1_i_player_resources_display_set.html',1,'Terraria::GameContent::UI']]],
  ['ipooledparticle_909',['IPooledParticle',['../interface_terraria_1_1_graphics_1_1_renderers_1_1_i_pooled_particle.html',1,'Terraria::Graphics::Renderers']]],
  ['ipowersubcategoryelement_910',['IPowerSubcategoryElement',['../interface_terraria_1_1_game_content_1_1_creative_1_1_i_power_subcategory_element.html',1,'Terraria::GameContent::Creative']]],
  ['ipreferenceproviderelement_911',['IPreferenceProviderElement',['../interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_preference_provider_element.html',1,'Terraria::GameContent::Bestiary']]],
  ['iprojectilesource_912',['IProjectileSource',['../interface_terraria_1_1_data_structures_1_1_i_projectile_source.html',1,'Terraria::DataStructures']]],
  ['iprovideitemconditiondescription_913',['IProvideItemConditionDescription',['../interface_terraria_1_1_game_content_1_1_item_drop_rules_1_1_i_provide_item_condition_description.html',1,'Terraria::GameContent::ItemDropRules']]],
  ['iprovidereports_914',['IProvideReports',['../interface_terraria_1_1_data_structures_1_1_i_provide_reports.html',1,'Terraria::DataStructures']]],
  ['iprovidesearchfilterstring_915',['IProvideSearchFilterString',['../interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_provide_search_filter_string.html',1,'Terraria::GameContent::Bestiary']]],
  ['iprovidesliderelement_916',['IProvideSliderElement',['../interface_terraria_1_1_game_content_1_1_creative_1_1_i_provide_slider_element.html',1,'Terraria::GameContent::Creative']]],
  ['irejectionreason_917',['IRejectionReason',['../class_i_rejection_reason.html',1,'']]],
  ['isanglerquestavailable_918',['IsAnglerQuestAvailable',['../class_terraria_1_1_mod_loader_1_1_mod_item.html#a96dd26858841172db14aa3798635c2ba',1,'Terraria.ModLoader.ModItem.IsAnglerQuestAvailable()'],['../class_terraria_1_1_mod_loader_1_1_global_item.html#a5a61ec22b6991616cad881bfc21c0696',1,'Terraria.ModLoader.GlobalItem.IsAnglerQuestAvailable()']]],
  ['isarmorset_919',['IsArmorSet',['../class_terraria_1_1_mod_loader_1_1_mod_item.html#a324513758f139965b9c5d13c588c5517',1,'Terraria.ModLoader.ModItem.IsArmorSet()'],['../class_terraria_1_1_mod_loader_1_1_global_item.html#a9ea562f4cb6d576abae4b59452e7bccd',1,'Terraria.ModLoader.GlobalItem.IsArmorSet()']]],
  ['isavailable_920',['IsAvailable',['../class_terraria_1_1_mod_loader_1_1_mod_menu.html#a85b24b0deceea643b4a93b25ea80b10c',1,'Terraria::ModLoader::ModMenu']]],
  ['isbiomeactive_921',['IsBiomeActive',['../class_terraria_1_1_mod_loader_1_1_mod_biome.html#a23bf4682286024ffbc1c1c072b2196bb',1,'Terraria::ModLoader::ModBiome']]],
  ['isbloodmoonandnotfromstatue_922',['IsBloodMoonAndNotFromStatue',['../class_terraria_1_1_game_content_1_1_item_drop_rules_1_1_conditions_1_1_is_blood_moon_and_not_from_statue.html',1,'Terraria::GameContent::ItemDropRules::Conditions']]],
  ['ischristmas_923',['IsChristmas',['../class_terraria_1_1_game_content_1_1_item_drop_rules_1_1_conditions_1_1_is_christmas.html',1,'Terraria::GameContent::ItemDropRules::Conditions']]],
  ['iscorruption_924',['IsCorruption',['../class_terraria_1_1_game_content_1_1_item_drop_rules_1_1_conditions_1_1_is_corruption.html',1,'Terraria::GameContent::ItemDropRules::Conditions']]],
  ['iscorruptionandnotexpert_925',['IsCorruptionAndNotExpert',['../class_terraria_1_1_game_content_1_1_item_drop_rules_1_1_conditions_1_1_is_corruption_and_not_expert.html',1,'Terraria::GameContent::ItemDropRules::Conditions']]],
  ['iscrimson_926',['IsCrimson',['../class_terraria_1_1_game_content_1_1_item_drop_rules_1_1_conditions_1_1_is_crimson.html',1,'Terraria::GameContent::ItemDropRules::Conditions']]],
  ['iscrimsonandnotexpert_927',['IsCrimsonAndNotExpert',['../class_terraria_1_1_game_content_1_1_item_drop_rules_1_1_conditions_1_1_is_crimson_and_not_expert.html',1,'Terraria::GameContent::ItemDropRules::Conditions']]],
  ['isearchfilter_928',['ISearchFilter',['../interface_terraria_1_1_data_structures_1_1_i_search_filter.html',1,'Terraria::DataStructures']]],
  ['isearchfilter_3c_20bestiaryentry_20_3e_929',['ISearchFilter&lt; BestiaryEntry &gt;',['../interface_terraria_1_1_data_structures_1_1_i_search_filter.html',1,'Terraria::DataStructures']]],
  ['isearchfilter_3c_20item_20_3e_930',['ISearchFilter&lt; Item &gt;',['../interface_terraria_1_1_data_structures_1_1_i_search_filter.html',1,'Terraria::DataStructures']]],
  ['isempty_931',['IsEmpty',['../class_terraria_1_1_world_building_1_1_modifiers_1_1_is_empty.html',1,'Terraria::WorldBuilding::Modifiers']]],
  ['isexpert_932',['IsExpert',['../class_terraria_1_1_game_content_1_1_item_drop_rules_1_1_conditions_1_1_is_expert.html',1,'Terraria::GameContent::ItemDropRules::Conditions']]],
  ['ishadereffect_933',['IShaderEffect',['../interface_terraria_1_1_game_content_1_1_skies_1_1_credits_roll_1_1_segments_1_1_player_segment_1_1_i_shader_effect.html',1,'Terraria.GameContent.Skies.CreditsRoll.Segments.PlayerSegment.IShaderEffect'],['../interface_terraria_1_1_game_content_1_1_skies_1_1_credits_roll_1_1_segments_1_1_sprite_segment_1_1_i_shader_effect.html',1,'Terraria.GameContent.Skies.CreditsRoll.Segments.SpriteSegment.IShaderEffect']]],
  ['ishardmode_934',['IsHardmode',['../class_terraria_1_1_game_content_1_1_item_drop_rules_1_1_conditions_1_1_is_hardmode.html',1,'Terraria::GameContent::ItemDropRules::Conditions']]],
  ['isheadlayer_935',['IsHeadLayer',['../class_terraria_1_1_mod_loader_1_1_player_draw_layer.html#a75c79c6584246557a3099938e4dc81de',1,'Terraria::ModLoader::PlayerDrawLayer']]],
  ['ishoppersonalitytrait_936',['IShopPersonalityTrait',['../interface_terraria_1_1_game_content_1_1_personalities_1_1_i_shop_personality_trait.html',1,'Terraria::GameContent::Personalities']]],
  ['isimulationconditionsetter_937',['ISimulationConditionSetter',['../interface_terraria_1_1_game_content_1_1_loot_simulation_1_1_i_simulation_condition_setter.html',1,'Terraria::GameContent::LootSimulation']]],
  ['isloadingenabled_938',['IsLoadingEnabled',['../interface_terraria_1_1_mod_loader_1_1_i_loadable.html#a99cb7624fdbd3514ea3af077a6d0e63e',1,'Terraria.ModLoader.ILoadable.IsLoadingEnabled()'],['../class_terraria_1_1_mod_loader_1_1_mod_tile_entity.html#ad802a41427e54c3bcadc616d3bf23aa5',1,'Terraria.ModLoader.ModTileEntity.IsLoadingEnabled()'],['../class_terraria_1_1_mod_loader_1_1_mod_type.html#a041087074eaff42734190d565f13ce1a',1,'Terraria.ModLoader.ModType.IsLoadingEnabled()']]],
  ['islockedchest_939',['IsLockedChest',['../class_terraria_1_1_mod_loader_1_1_mod_tile.html#a73168146e18265de2739d619377b8adf',1,'Terraria::ModLoader::ModTile']]],
  ['ismartinteractblockreasonprovider_940',['ISmartInteractBlockReasonProvider',['../interface_terraria_1_1_game_content_1_1_object_interactions_1_1_i_smart_interact_block_reason_provider.html',1,'Terraria::GameContent::ObjectInteractions']]],
  ['ismartinteractcandidate_941',['ISmartInteractCandidate',['../interface_terraria_1_1_game_content_1_1_object_interactions_1_1_i_smart_interact_candidate.html',1,'Terraria::GameContent::ObjectInteractions']]],
  ['ismartinteractcandidateprovider_942',['ISmartInteractCandidateProvider',['../interface_terraria_1_1_game_content_1_1_object_interactions_1_1_i_smart_interact_candidate_provider.html',1,'Terraria::GameContent::ObjectInteractions']]],
  ['ismastermode_943',['IsMasterMode',['../class_terraria_1_1_game_content_1_1_item_drop_rules_1_1_conditions_1_1_is_master_mode.html',1,'Terraria::GameContent::ItemDropRules::Conditions']]],
  ['ismodifier_944',['isModifier',['../class_terraria_1_1_mod_loader_1_1_drawable_tooltip_line.html#a744e18254de99adea41f1c75e6ae3bf6',1,'Terraria.ModLoader.DrawableTooltipLine.isModifier()'],['../class_terraria_1_1_mod_loader_1_1_tooltip_line.html#a5a998c87573cd4944c0966e7b3409588',1,'Terraria.ModLoader.TooltipLine.isModifier()']]],
  ['ismodifierbad_945',['isModifierBad',['../class_terraria_1_1_mod_loader_1_1_drawable_tooltip_line.html#a7b144755d23bcddbfc52210385710f37',1,'Terraria.ModLoader.DrawableTooltipLine.isModifierBad()'],['../class_terraria_1_1_mod_loader_1_1_tooltip_line.html#a7efdb3feea743c6755643e82c5e5ff3b',1,'Terraria.ModLoader.TooltipLine.isModifierBad()']]],
  ['isnotsolid_946',['IsNotSolid',['../class_terraria_1_1_world_building_1_1_modifiers_1_1_is_not_solid.html',1,'Terraria::WorldBuilding::Modifiers']]],
  ['isocialmodule_947',['ISocialModule',['../interface_terraria_1_1_social_1_1_i_social_module.html',1,'Terraria::Social']]],
  ['isocket_948',['ISocket',['../interface_terraria_1_1_net_1_1_sockets_1_1_i_socket.html',1,'Terraria::Net::Sockets']]],
  ['isprimarybiome_949',['IsPrimaryBiome',['../class_terraria_1_1_mod_loader_1_1_mod_biome.html#af75a5a9efa286109c702edbd3c49c748',1,'Terraria::ModLoader::ModBiome']]],
  ['ispriteaction_950',['ISpriteAction',['../interface_terraria_1_1_game_content_1_1_skies_1_1_credits_roll_1_1_actions_1_1_sprites_1_1_i_sprite_action.html',1,'Terraria::GameContent::Skies::CreditsRoll::Actions::Sprites']]],
  ['ispumpkinmoon_951',['IsPumpkinMoon',['../class_terraria_1_1_game_content_1_1_item_drop_rules_1_1_conditions_1_1_is_pumpkin_moon.html',1,'Terraria::GameContent::ItemDropRules::Conditions']]],
  ['isquestfish_952',['IsQuestFish',['../class_terraria_1_1_mod_loader_1_1_mod_item.html#a146b63f35e144131997ef0e081a9f500',1,'Terraria::ModLoader::ModItem']]],
  ['issceneeffectactive_953',['IsSceneEffectActive',['../class_terraria_1_1_mod_loader_1_1_mod_biome.html#a3453119cc8f1f3fa6b31672c215cd6b6',1,'Terraria::ModLoader::ModBiome']]],
  ['isselected_954',['IsSelected',['../class_terraria_1_1_mod_loader_1_1_mod_boss_bar_style.html#a199d5f537488cb564a584a7e3663fe85',1,'Terraria::ModLoader::ModBossBarStyle']]],
  ['issolid_955',['IsSolid',['../class_terraria_1_1_world_building_1_1_conditions_1_1_is_solid.html',1,'Terraria.WorldBuilding.Conditions.IsSolid'],['../class_terraria_1_1_world_building_1_1_modifiers_1_1_is_solid.html',1,'Terraria.WorldBuilding.Modifiers.IsSolid']]],
  ['issuereport_956',['IssueReport',['../class_terraria_1_1_data_structures_1_1_issue_report.html',1,'Terraria::DataStructures']]],
  ['issuereportsindicator_957',['IssueReportsIndicator',['../class_terraria_1_1_game_content_1_1_u_i_1_1_issue_reports_indicator.html',1,'Terraria::GameContent::UI']]],
  ['istaticportmapping_958',['IStaticPortMapping',['../interface_n_a_t_u_p_n_p_lib_1_1_i_static_port_mapping.html',1,'NATUPNPLib']]],
  ['istaticportmappingcollection_959',['IStaticPortMappingCollection',['../interface_n_a_t_u_p_n_p_lib_1_1_i_static_port_mapping_collection.html',1,'NATUPNPLib']]],
  ['istile_960',['IsTile',['../class_terraria_1_1_world_building_1_1_conditions_1_1_is_tile.html',1,'Terraria::WorldBuilding::Conditions']]],
  ['istouching_961',['IsTouching',['../class_terraria_1_1_world_building_1_1_modifiers_1_1_is_touching.html',1,'Terraria::WorldBuilding::Modifiers']]],
  ['istouchingair_962',['IsTouchingAir',['../class_terraria_1_1_world_building_1_1_modifiers_1_1_is_touching_air.html',1,'Terraria::WorldBuilding::Modifiers']]],
  ['isusingspecificaivalues_963',['IsUsingSpecificAIValues',['../class_terraria_1_1_game_content_1_1_item_drop_rules_1_1_conditions_1_1_is_using_specific_a_i_values.html',1,'Terraria::GameContent::ItemDropRules::Conditions']]],
  ['isvanityset_964',['IsVanitySet',['../class_terraria_1_1_mod_loader_1_1_equip_texture.html#acd4647b2d645c915743daa3b734919f7',1,'Terraria.ModLoader.EquipTexture.IsVanitySet()'],['../class_terraria_1_1_mod_loader_1_1_mod_item.html#a7411ef16c0702304775364b6c177b690',1,'Terraria.ModLoader.ModItem.IsVanitySet()'],['../class_terraria_1_1_mod_loader_1_1_global_item.html#afc66c0f98cbc3d51a577b847d011d711',1,'Terraria.ModLoader.GlobalItem.IsVanitySet()']]],
  ['itaghandler_965',['ITagHandler',['../interface_terraria_1_1_u_i_1_1_chat_1_1_i_tag_handler.html',1,'Terraria::UI::Chat']]],
  ['item_966',['Item',['../class_terraria_1_1_mod_loader_1_1_mod_item.html#abc96a407c86a78570037ef4318d9c112',1,'Terraria.ModLoader.ModItem.Item()'],['../class_terraria_1_1_mod_loader_1_1_equip_texture.html#a1ef4348349e6b437eac4d37c7093b148',1,'Terraria.ModLoader.EquipTexture.Item()'],['../class_terraria_1_1_item.html',1,'Terraria.Item']]],
  ['itemcraftcondition_967',['ItemCraftCondition',['../class_terraria_1_1_game_content_1_1_achievements_1_1_item_craft_condition.html',1,'Terraria::GameContent::Achievements']]],
  ['itemcreationcontext_968',['ItemCreationContext',['../class_terraria_1_1_mod_loader_1_1_item_creation_context.html',1,'Terraria::ModLoader']]],
  ['itemdefinition_969',['ItemDefinition',['../class_terraria_1_1_mod_loader_1_1_config_1_1_item_definition.html',1,'Terraria::ModLoader::Config']]],
  ['itemdefinitionelement_970',['ItemDefinitionElement',['../class_terraria_1_1_mod_loader_1_1_config_1_1_u_i_1_1_item_definition_element.html',1,'Terraria::ModLoader::Config::UI']]],
  ['itemdrop_971',['ItemDrop',['../class_terraria_1_1_mod_loader_1_1_mod_block_type.html#ab38346a81262f8dce57d4cd067bab64e',1,'Terraria::ModLoader::ModBlockType']]],
  ['itemdropattemptresult_972',['ItemDropAttemptResult',['../struct_terraria_1_1_game_content_1_1_item_drop_rules_1_1_item_drop_attempt_result.html',1,'Terraria::GameContent::ItemDropRules']]],
  ['itemdropbestiaryinfoelement_973',['ItemDropBestiaryInfoElement',['../class_terraria_1_1_game_content_1_1_bestiary_1_1_item_drop_bestiary_info_element.html',1,'Terraria::GameContent::Bestiary']]],
  ['itemdropdatabase_974',['ItemDropDatabase',['../class_terraria_1_1_game_content_1_1_item_drop_rules_1_1_item_drop_database.html',1,'Terraria::GameContent::ItemDropRules']]],
  ['itemdropresolver_975',['ItemDropResolver',['../class_terraria_1_1_game_content_1_1_item_drop_rules_1_1_item_drop_resolver.html',1,'Terraria::GameContent::ItemDropRules']]],
  ['itemdroprule_976',['ItemDropRule',['../class_terraria_1_1_game_content_1_1_item_drop_rules_1_1_item_drop_rule.html',1,'Terraria::GameContent::ItemDropRules']]],
  ['itemdropwithconditionrule_977',['ItemDropWithConditionRule',['../class_terraria_1_1_game_content_1_1_item_drop_rules_1_1_item_drop_with_condition_rule.html',1,'Terraria::GameContent::ItemDropRules']]],
  ['itemfromcatchingnpcbestiaryinfoelement_978',['ItemFromCatchingNPCBestiaryInfoElement',['../class_terraria_1_1_game_content_1_1_bestiary_1_1_item_from_catching_n_p_c_bestiary_info_element.html',1,'Terraria::GameContent::Bestiary']]],
  ['itemgroupandorderingroup_979',['ItemGroupAndOrderInGroup',['../struct_terraria_1_1_i_d_1_1_content_samples_1_1_creative_helper_1_1_item_group_and_order_in_group.html',1,'Terraria::ID::ContentSamples::CreativeHelper']]],
  ['itemholdstyleid_980',['ItemHoldStyleID',['../class_terraria_1_1_i_d_1_1_item_hold_style_i_d.html',1,'Terraria::ID']]],
  ['itemid_981',['ItemID',['../class_terraria_1_1_i_d_1_1_item_i_d.html',1,'Terraria::ID']]],
  ['iteminstallinfo_982',['ItemInstallInfo',['../struct_terraria_1_1_social_1_1_steam_1_1_workshop_helper_1_1_item_install_info.html',1,'Terraria::Social::Steam::WorkshopHelper']]],
  ['itempickupcondition_983',['ItemPickupCondition',['../class_terraria_1_1_game_content_1_1_achievements_1_1_item_pickup_condition.html',1,'Terraria::GameContent::Achievements']]],
  ['itemrarity_984',['ItemRarity',['../class_terraria_1_1_game_content_1_1_u_i_1_1_item_rarity.html',1,'Terraria::GameContent::UI']]],
  ['itemshopsellbackhelper_985',['ItemShopSellbackHelper',['../class_terraria_1_1_game_content_1_1_item_shop_sellback_helper.html',1,'Terraria::GameContent']]],
  ['itemslot_986',['ItemSlot',['../class_terraria_1_1_u_i_1_1_item_slot.html',1,'Terraria::UI']]],
  ['itemsorting_987',['ItemSorting',['../class_terraria_1_1_u_i_1_1_item_sorting.html',1,'Terraria::UI']]],
  ['itemspace_988',['ItemSpace',['../class_terraria_1_1_mod_loader_1_1_global_item.html#af6ed20f0b7f9e7b84a84bb31ca269d3f',1,'Terraria.ModLoader.GlobalItem.ItemSpace()'],['../class_terraria_1_1_mod_loader_1_1_mod_item.html#ae360f7809f0151bf1bdbc78dc5dae8c1',1,'Terraria.ModLoader.ModItem.ItemSpace()']]],
  ['itemspacestatus_989',['ItemSpaceStatus',['../struct_terraria_1_1_player_1_1_item_space_status.html',1,'Terraria::Player']]],
  ['itemssacrificedunlockstracker_990',['ItemsSacrificedUnlocksTracker',['../class_terraria_1_1_game_content_1_1_creative_1_1_items_sacrificed_unlocks_tracker.html',1,'Terraria::GameContent::Creative']]],
  ['itemsyncpersistentstats_991',['ItemSyncPersistentStats',['../struct_terraria_1_1_data_structures_1_1_item_sync_persistent_stats.html',1,'Terraria::DataStructures']]],
  ['itemtaghandler_992',['ItemTagHandler',['../class_terraria_1_1_game_content_1_1_u_i_1_1_chat_1_1_item_tag_handler.html',1,'Terraria::GameContent::UI::Chat']]],
  ['itemtooltip_993',['ItemTooltip',['../class_terraria_1_1_u_i_1_1_item_tooltip.html',1,'Terraria::UI']]],
  ['itemusestyleid_994',['ItemUseStyleID',['../class_terraria_1_1_i_d_1_1_item_use_style_i_d.html',1,'Terraria::ID']]],
  ['itownnpcprofile_995',['ITownNPCProfile',['../interface_terraria_1_1_game_content_1_1_i_town_n_p_c_profile.html',1,'Terraria::GameContent']]],
  ['iupnpnat_996',['IUPnPNAT',['../interface_n_a_t_u_p_n_p_lib_1_1_i_u_pn_p_n_a_t.html',1,'NATUPNPLib']]],
  ['ivalueprovider_997',['IValueProvider',['../class_i_value_provider.html',1,'']]],
  ['ivertextype_998',['IVertexType',['../class_i_vertex_type.html',1,'']]]
];
