var searchData=
[
  ['iachievementtracker_3608',['IAchievementTracker',['../interface_terraria_1_1_achievements_1_1_i_achievement_tracker.html',1,'Terraria::Achievements']]],
  ['iassetreader_3609',['IAssetReader',['../class_i_asset_reader.html',1,'']]],
  ['iaudiosystem_3610',['IAudioSystem',['../interface_terraria_1_1_audio_1_1_i_audio_system.html',1,'Terraria::Audio']]],
  ['iaudiotrack_3611',['IAudioTrack',['../interface_terraria_1_1_audio_1_1_i_audio_track.html',1,'Terraria::Audio']]],
  ['iballcontactlistener_3612',['IBallContactListener',['../interface_terraria_1_1_physics_1_1_i_ball_contact_listener.html',1,'Terraria::Physics']]],
  ['ibestiarybackgroundimagepathandcolorprovider_3613',['IBestiaryBackgroundImagePathAndColorProvider',['../interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_bestiary_background_image_path_and_color_provider.html',1,'Terraria::GameContent::Bestiary']]],
  ['ibestiarybackgroundoverlayandcolorprovider_3614',['IBestiaryBackgroundOverlayAndColorProvider',['../interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_bestiary_background_overlay_and_color_provider.html',1,'Terraria::GameContent::Bestiary']]],
  ['ibestiaryentrydisplayindex_3615',['IBestiaryEntryDisplayIndex',['../interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_bestiary_entry_display_index.html',1,'Terraria::GameContent::Bestiary']]],
  ['ibestiaryentryfilter_3616',['IBestiaryEntryFilter',['../interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_bestiary_entry_filter.html',1,'Terraria::GameContent::Bestiary']]],
  ['ibestiaryinfoelement_3617',['IBestiaryInfoElement',['../interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_bestiary_info_element.html',1,'Terraria::GameContent::Bestiary']]],
  ['ibestiaryprioritizedelement_3618',['IBestiaryPrioritizedElement',['../interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_bestiary_prioritized_element.html',1,'Terraria::GameContent::Bestiary']]],
  ['ibestiarysortstep_3619',['IBestiarySortStep',['../interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_bestiary_sort_step.html',1,'Terraria::GameContent::Bestiary']]],
  ['ibestiaryuicollectioninfoprovider_3620',['IBestiaryUICollectionInfoProvider',['../interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_bestiary_u_i_collection_info_provider.html',1,'Terraria::GameContent::Bestiary']]],
  ['ibigprogressbar_3621',['IBigProgressBar',['../interface_terraria_1_1_game_content_1_1_u_i_1_1_big_progress_bar_1_1_i_big_progress_bar.html',1,'Terraria::GameContent::UI::BigProgressBar']]],
  ['ibuilderacctoggle_3622',['IBuilderAccToggle',['../interface_terraria_1_1_game_content_1_1_u_i_1_1_builder_acc_toggles_u_i_1_1_i_builder_acc_toggle.html',1,'Terraria::GameContent::UI::BuilderAccTogglesUI']]],
  ['icameramodifier_3623',['ICameraModifier',['../interface_terraria_1_1_graphics_1_1_camera_modifiers_1_1_i_camera_modifier.html',1,'Terraria::Graphics::CameraModifiers']]],
  ['icehousebuilder_3624',['IceHouseBuilder',['../class_terraria_1_1_game_content_1_1_biomes_1_1_cave_house_1_1_ice_house_builder.html',1,'Terraria::GameContent::Biomes::CaveHouse']]],
  ['iceshader_3625',['IceShader',['../class_terraria_1_1_game_content_1_1_r_g_b_1_1_ice_shader.html',1,'Terraria::GameContent::RGB']]],
  ['ichatcommand_3626',['IChatCommand',['../interface_terraria_1_1_chat_1_1_commands_1_1_i_chat_command.html',1,'Terraria::Chat::Commands']]],
  ['ichatmonitor_3627',['IChatMonitor',['../interface_terraria_1_1_game_content_1_1_u_i_1_1_chat_1_1_i_chat_monitor.html',1,'Terraria::GameContent::UI::Chat']]],
  ['ichatprocessor_3628',['IChatProcessor',['../interface_terraria_1_1_chat_1_1_i_chat_processor.html',1,'Terraria::Chat']]],
  ['icloneable_3629',['ICloneable',['../class_i_cloneable.html',1,'']]],
  ['icolorable_3630',['IColorable',['../interface_terraria_1_1_game_content_1_1_u_i_1_1_elements_1_1_i_colorable.html',1,'Terraria::GameContent::UI::Elements']]],
  ['icomparable_3631',['IComparable',['../class_i_comparable.html',1,'']]],
  ['icomparer_3632',['IComparer',['../class_i_comparer.html',1,'']]],
  ['icomparer_3c_20tuple_3c_20int_2c_20float_20_3e_3e_3633',['IComparer&lt; Tuple&lt; int, float &gt;&gt;',['../class_i_comparer_3_01_tuple_3_01int_00_01float_01_4_4.html',1,'']]],
  ['icondition_3634',['ICondition',['../interface_terraria_1_1_recipe_1_1_i_condition.html',1,'Terraria::Recipe']]],
  ['iconfigkeyholder_3635',['IConfigKeyHolder',['../interface_terraria_1_1_data_structures_1_1_i_config_key_holder.html',1,'Terraria::DataStructures']]],
  ['icontentvalidator_3636',['IContentValidator',['../class_i_content_validator.html',1,'']]],
  ['icreativeitemsortstep_3637',['ICreativeItemSortStep',['../interface_terraria_1_1_game_content_1_1_creative_1_1_i_creative_item_sort_step.html',1,'Terraria::GameContent::Creative']]],
  ['icreativepower_3638',['ICreativePower',['../interface_terraria_1_1_game_content_1_1_creative_1_1_i_creative_power.html',1,'Terraria::GameContent::Creative']]],
  ['icreditsrollsegment_3639',['ICreditsRollSegment',['../interface_terraria_1_1_game_content_1_1_skies_1_1_credits_roll_1_1_i_credits_roll_segment.html',1,'Terraria::GameContent::Skies::CreditsRoll']]],
  ['icreditsrollsegmentaction_3640',['ICreditsRollSegmentAction',['../interface_terraria_1_1_game_content_1_1_skies_1_1_credits_roll_1_1_i_credits_roll_segment_action.html',1,'Terraria::GameContent::Skies::CreditsRoll']]],
  ['icreditsrollsegmentaction_3c_20npc_20_3e_3641',['ICreditsRollSegmentAction&lt; NPC &gt;',['../interface_terraria_1_1_game_content_1_1_skies_1_1_credits_roll_1_1_i_credits_roll_segment_action.html',1,'Terraria::GameContent::Skies::CreditsRoll']]],
  ['icreditsrollsegmentaction_3c_20player_20_3e_3642',['ICreditsRollSegmentAction&lt; Player &gt;',['../interface_terraria_1_1_game_content_1_1_skies_1_1_credits_roll_1_1_i_credits_roll_segment_action.html',1,'Terraria::GameContent::Skies::CreditsRoll']]],
  ['icreditsrollsegmentaction_3c_20segments_2eloosesprite_20_3e_3643',['ICreditsRollSegmentAction&lt; Segments.LooseSprite &gt;',['../interface_terraria_1_1_game_content_1_1_skies_1_1_credits_roll_1_1_i_credits_roll_segment_action.html',1,'Terraria::GameContent::Skies::CreditsRoll']]],
  ['ientitywithglobals_3644',['IEntityWithGlobals',['../interface_terraria_1_1_mod_loader_1_1_i_entity_with_globals.html',1,'Terraria::ModLoader']]],
  ['ientitywithglobals_3c_20globalitem_20_3e_3645',['IEntityWithGlobals&lt; GlobalItem &gt;',['../interface_terraria_1_1_mod_loader_1_1_i_entity_with_globals.html',1,'Terraria::ModLoader']]],
  ['ientitywithglobals_3c_20globalnpc_20_3e_3646',['IEntityWithGlobals&lt; GlobalNPC &gt;',['../interface_terraria_1_1_mod_loader_1_1_i_entity_with_globals.html',1,'Terraria::ModLoader']]],
  ['ientitywithglobals_3c_20globalprojectile_20_3e_3647',['IEntityWithGlobals&lt; GlobalProjectile &gt;',['../interface_terraria_1_1_mod_loader_1_1_i_entity_with_globals.html',1,'Terraria::ModLoader']]],
  ['ientryfilter_3648',['IEntryFilter',['../interface_terraria_1_1_data_structures_1_1_i_entry_filter.html',1,'Terraria::DataStructures']]],
  ['ientryfilter_3c_20bestiaryentry_20_3e_3649',['IEntryFilter&lt; BestiaryEntry &gt;',['../interface_terraria_1_1_data_structures_1_1_i_entry_filter.html',1,'Terraria::DataStructures']]],
  ['ientryfilter_3c_20item_20_3e_3650',['IEntryFilter&lt; Item &gt;',['../interface_terraria_1_1_data_structures_1_1_i_entry_filter.html',1,'Terraria::DataStructures']]],
  ['ientryicon_3651',['IEntryIcon',['../interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_entry_icon.html',1,'Terraria::GameContent::Bestiary']]],
  ['ientrysortstep_3652',['IEntrySortStep',['../interface_terraria_1_1_data_structures_1_1_i_entry_sort_step.html',1,'Terraria::DataStructures']]],
  ['ientrysortstep_3c_20bestiaryentry_20_3e_3653',['IEntrySortStep&lt; BestiaryEntry &gt;',['../interface_terraria_1_1_data_structures_1_1_i_entry_sort_step.html',1,'Terraria::DataStructures']]],
  ['ientrysortstep_3c_20int_20_3e_3654',['IEntrySortStep&lt; int &gt;',['../interface_terraria_1_1_data_structures_1_1_i_entry_sort_step.html',1,'Terraria::DataStructures']]],
  ['ienumerable_3655',['IEnumerable',['../class_i_enumerable.html',1,'']]],
  ['ienumerable_3c_20keyvaluepair_3c_20string_2c_20object_20_3e_3e_3656',['IEnumerable&lt; KeyValuePair&lt; string, object &gt;&gt;',['../class_i_enumerable_3_01_key_value_pair_3_01string_00_01object_01_4_4.html',1,'']]],
  ['iequatable_3657',['IEquatable',['../class_i_equatable.html',1,'']]],
  ['ifilebrowser_3658',['IFileBrowser',['../interface_terraria_1_1_utilities_1_1_file_browser_1_1_i_file_browser.html',1,'Terraria::Utilities::FileBrowser']]],
  ['ifilterinfoprovider_3659',['IFilterInfoProvider',['../interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_filter_info_provider.html',1,'Terraria::GameContent::Bestiary']]],
  ['igroupoptionbutton_3660',['IGroupOptionButton',['../interface_terraria_1_1_game_content_1_1_u_i_1_1_elements_1_1_i_group_option_button.html',1,'Terraria::GameContent::UI::Elements']]],
  ['ihavebackbuttoncommand_3661',['IHaveBackButtonCommand',['../interface_terraria_1_1_u_i_1_1_i_have_back_button_command.html',1,'Terraria::UI']]],
  ['iingamenotification_3662',['IInGameNotification',['../interface_terraria_1_1_u_i_1_1_i_in_game_notification.html',1,'Terraria::UI']]],
  ['iitembestiaryinfoelement_3663',['IItemBestiaryInfoElement',['../interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_item_bestiary_info_element.html',1,'Terraria::GameContent::Bestiary']]],
  ['iitemdroprule_3664',['IItemDropRule',['../interface_terraria_1_1_game_content_1_1_item_drop_rules_1_1_i_item_drop_rule.html',1,'Terraria::GameContent::ItemDropRules']]],
  ['iitemdroprulechainattempt_3665',['IItemDropRuleChainAttempt',['../interface_terraria_1_1_game_content_1_1_item_drop_rules_1_1_i_item_drop_rule_chain_attempt.html',1,'Terraria::GameContent::ItemDropRules']]],
  ['iitemdroprulecondition_3666',['IItemDropRuleCondition',['../interface_terraria_1_1_game_content_1_1_item_drop_rules_1_1_i_item_drop_rule_condition.html',1,'Terraria::GameContent::ItemDropRules']]],
  ['iitementryfilter_3667',['IItemEntryFilter',['../interface_terraria_1_1_game_content_1_1_creative_1_1_i_item_entry_filter.html',1,'Terraria::GameContent::Creative']]],
  ['ilightingengine_3668',['ILightingEngine',['../interface_terraria_1_1_graphics_1_1_light_1_1_i_lighting_engine.html',1,'Terraria::Graphics::Light']]],
  ['iloadable_3669',['ILoadable',['../interface_terraria_1_1_mod_loader_1_1_i_loadable.html',1,'Terraria::ModLoader']]],
  ['iloader_3670',['ILoader',['../interface_terraria_1_1_mod_loader_1_1_i_loader.html',1,'Terraria::ModLoader']]],
  ['imageio_3671',['ImageIO',['../class_terraria_1_1_mod_loader_1_1_i_o_1_1_image_i_o.html',1,'Terraria::ModLoader::IO']]],
  ['imanuallyordereduielement_3672',['IManuallyOrderedUIElement',['../interface_terraria_1_1_game_content_1_1_u_i_1_1_elements_1_1_i_manually_ordered_u_i_element.html',1,'Terraria::GameContent::UI::Elements']]],
  ['imaplayer_3673',['IMapLayer',['../interface_terraria_1_1_map_1_1_i_map_layer.html',1,'Terraria::Map']]],
  ['immediatespritebatchforplayerdyeseffect_3674',['ImmediateSpritebatchForPlayerDyesEffect',['../class_terraria_1_1_game_content_1_1_skies_1_1_credits_roll_1_1_segments_1_1_player_segment_1_1_i80cf05f0478e3894be72e0a77d29c1ad.html',1,'Terraria::GameContent::Skies::CreditsRoll::Segments::PlayerSegment']]],
  ['imodtype_3675',['IModType',['../interface_terraria_1_1_mod_loader_1_1_i_mod_type.html',1,'Terraria::ModLoader']]],
  ['imultiplayercloseplayersoverlay_3676',['IMultiplayerClosePlayersOverlay',['../interface_terraria_1_1_game_content_1_1_u_i_1_1_i_multiplayer_close_players_overlay.html',1,'Terraria::GameContent::UI']]],
  ['includecapefrontandbackinfo_3677',['IncludeCapeFrontAndBackInfo',['../struct_terraria_1_1_i_d_1_1_armor_i_ds_1_1_body_1_1_sets_1_1_include_cape_front_and_back_info.html',1,'Terraria::ID::ArmorIDs::Body::Sets']]],
  ['incrementattribute_3678',['IncrementAttribute',['../class_terraria_1_1_mod_loader_1_1_config_1_1_increment_attribute.html',1,'Terraria::ModLoader::Config']]],
  ['ineedrendertargetcontent_3679',['INeedRenderTargetContent',['../interface_terraria_1_1_game_content_1_1_i_need_render_target_content.html',1,'Terraria::GameContent']]],
  ['inesteditemdroprule_3680',['INestedItemDropRule',['../interface_terraria_1_1_game_content_1_1_item_drop_rules_1_1_i_nested_item_drop_rule.html',1,'Terraria::GameContent::ItemDropRules']]],
  ['inetdiagnosticsui_3681',['INetDiagnosticsUI',['../interface_terraria_1_1_u_i_1_1_i_net_diagnostics_u_i.html',1,'Terraria::UI']]],
  ['infodisplay_3682',['InfoDisplay',['../class_terraria_1_1_mod_loader_1_1_info_display.html',1,'Terraria::ModLoader']]],
  ['infodisplayloader_3683',['InfoDisplayLoader',['../class_terraria_1_1_mod_loader_1_1_info_display_loader.html',1,'Terraria::ModLoader']]],
  ['infotosetbackcolor_3684',['InfoToSetBackColor',['../struct_terraria_1_1_main_1_1_info_to_set_back_color.html',1,'Terraria::Main']]],
  ['ingamefancyui_3685',['IngameFancyUI',['../class_terraria_1_1_u_i_1_1_ingame_fancy_u_i.html',1,'Terraria::UI']]],
  ['ingamenotificationstracker_3686',['InGameNotificationsTracker',['../class_terraria_1_1_u_i_1_1_in_game_notifications_tracker.html',1,'Terraria::UI']]],
  ['ingameoptions_3687',['IngameOptions',['../class_terraria_1_1_ingame_options.html',1,'Terraria']]],
  ['ingamepopups_3688',['InGamePopups',['../class_terraria_1_1_u_i_1_1_in_game_popups.html',1,'Terraria::UI']]],
  ['initializationcontext_3689',['InitializationContext',['../class_terraria_1_1_mod_loader_1_1_initialization_context.html',1,'Terraria::ModLoader']]],
  ['inneroutline_3690',['InnerOutline',['../class_terraria_1_1_world_building_1_1_mod_shapes_1_1_inner_outline.html',1,'Terraria::WorldBuilding::ModShapes']]],
  ['inpcaction_3691',['INPCAction',['../interface_terraria_1_1_game_content_1_1_skies_1_1_credits_roll_1_1_actions_1_1_n_p_cs_1_1_i_n_p_c_action.html',1,'Terraria::GameContent::Skies::CreditsRoll::Actions::NPCs']]],
  ['inshape_3692',['InShape',['../class_terraria_1_1_world_building_1_1_modifiers_1_1_in_shape.html',1,'Terraria::WorldBuilding::Modifiers']]],
  ['instanced_3693',['Instanced',['../struct_terraria_1_1_mod_loader_1_1_instanced.html',1,'Terraria::ModLoader']]],
  ['instanced_3c_20globalitem_20_3e_3694',['Instanced&lt; GlobalItem &gt;',['../struct_terraria_1_1_mod_loader_1_1_instanced.html',1,'Terraria::ModLoader']]],
  ['instanced_3c_20globalnpc_20_3e_3695',['Instanced&lt; GlobalNPC &gt;',['../struct_terraria_1_1_mod_loader_1_1_instanced.html',1,'Terraria::ModLoader']]],
  ['instanced_3c_20globalprojectile_20_3e_3696',['Instanced&lt; GlobalProjectile &gt;',['../struct_terraria_1_1_mod_loader_1_1_instanced.html',1,'Terraria::ModLoader']]],
  ['instanceenumerator_3697',['InstanceEnumerator',['../struct_terraria_1_1_mod_loader_1_1_core_1_1_hook_list_1_1_instance_enumerator.html',1,'Terraria::ModLoader::Core::HookList']]],
  ['intrange_3698',['IntRange',['../struct_terraria_1_1_utilities_1_1_int_range.html',1,'Terraria::Utilities']]],
  ['invasionid_3699',['InvasionID',['../class_terraria_1_1_i_d_1_1_invasion_i_d.html',1,'Terraria::ID']]],
  ['invasions_3700',['Invasions',['../class_terraria_1_1_game_content_1_1_bestiary_1_1_bestiary_database_n_p_cs_populator_1_1_common_te88d9ec051cbe968cdce0d7ccd2a60c1.html',1,'Terraria::GameContent::Bestiary::BestiaryDatabaseNPCsPopulator::CommonTags::SpawnConditions']]],
  ['ioexception_3701',['IOException',['../class_i_o_exception.html',1,'']]],
  ['ioimpl_3702',['IOImpl',['../class_terraria_1_1_mod_loader_1_1_i_o_1_1_tile_i_o_1_1_i_o_impl.html',1,'Terraria::ModLoader::IO::TileIO']]],
  ['ioimpl_3c_20modtile_2c_20tileentry_20_3e_3703',['IOImpl&lt; ModTile, TileEntry &gt;',['../class_terraria_1_1_mod_loader_1_1_i_o_1_1_tile_i_o_1_1_i_o_impl.html',1,'Terraria::ModLoader::IO::TileIO']]],
  ['ioimpl_3c_20modwall_2c_20wallentry_20_3e_3704',['IOImpl&lt; ModWall, WallEntry &gt;',['../class_terraria_1_1_mod_loader_1_1_i_o_1_1_tile_i_o_1_1_i_o_impl.html',1,'Terraria::ModLoader::IO::TileIO']]],
  ['ionplayerjoining_3705',['IOnPlayerJoining',['../interface_terraria_1_1_game_content_1_1_i_on_player_joining.html',1,'Terraria::GameContent']]],
  ['iparticle_3706',['IParticle',['../interface_terraria_1_1_graphics_1_1_renderers_1_1_i_particle.html',1,'Terraria::Graphics::Renderers']]],
  ['ipcbase_3707',['IPCBase',['../class_terraria_1_1_social_1_1_we_game_1_1_i_p_c_base.html',1,'Terraria::Social::WeGame']]],
  ['ipcclient_3708',['IPCClient',['../class_terraria_1_1_social_1_1_we_game_1_1_i_p_c_client.html',1,'Terraria::Social::WeGame']]],
  ['ipccontent_3709',['IPCContent',['../class_terraria_1_1_social_1_1_we_game_1_1_i_p_c_content.html',1,'Terraria::Social::WeGame']]],
  ['ipcmessage_3710',['IPCMessage',['../class_terraria_1_1_social_1_1_we_game_1_1_i_p_c_message.html',1,'Terraria::Social::WeGame']]],
  ['ipcserver_3711',['IPCServer',['../class_terraria_1_1_social_1_1_we_game_1_1_i_p_c_server.html',1,'Terraria::Social::WeGame']]],
  ['ipersistentperplayercontent_3712',['IPersistentPerPlayerContent',['../interface_terraria_1_1_game_content_1_1_i_persistent_per_player_content.html',1,'Terraria::GameContent']]],
  ['ipersistentperworldcontent_3713',['IPersistentPerWorldContent',['../interface_terraria_1_1_game_content_1_1_i_persistent_per_world_content.html',1,'Terraria::GameContent']]],
  ['iplayeraction_3714',['IPlayerAction',['../interface_terraria_1_1_game_content_1_1_skies_1_1_credits_roll_1_1_actions_1_1_players_1_1_i_player_action.html',1,'Terraria::GameContent::Skies::CreditsRoll::Actions::Players']]],
  ['iplayerrenderer_3715',['IPlayerRenderer',['../interface_terraria_1_1_graphics_1_1_renderers_1_1_i_player_renderer.html',1,'Terraria::Graphics::Renderers']]],
  ['iplayerresourcesdisplayset_3716',['IPlayerResourcesDisplaySet',['../interface_terraria_1_1_game_content_1_1_u_i_1_1_resource_sets_1_1_i_player_resources_display_set.html',1,'Terraria::GameContent::UI::ResourceSets']]],
  ['ipooledparticle_3717',['IPooledParticle',['../interface_terraria_1_1_graphics_1_1_renderers_1_1_i_pooled_particle.html',1,'Terraria::Graphics::Renderers']]],
  ['ipowersubcategoryelement_3718',['IPowerSubcategoryElement',['../interface_terraria_1_1_game_content_1_1_creative_1_1_i_power_subcategory_element.html',1,'Terraria::GameContent::Creative']]],
  ['ipreferenceproviderelement_3719',['IPreferenceProviderElement',['../interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_preference_provider_element.html',1,'Terraria::GameContent::Bestiary']]],
  ['iprojectilesource_3720',['IProjectileSource',['../interface_terraria_1_1_data_structures_1_1_i_projectile_source.html',1,'Terraria::DataStructures']]],
  ['iprovideitemconditiondescription_3721',['IProvideItemConditionDescription',['../interface_terraria_1_1_game_content_1_1_item_drop_rules_1_1_i_provide_item_condition_description.html',1,'Terraria::GameContent::ItemDropRules']]],
  ['iprovidereports_3722',['IProvideReports',['../interface_terraria_1_1_data_structures_1_1_i_provide_reports.html',1,'Terraria::DataStructures']]],
  ['iprovidesearchfilterstring_3723',['IProvideSearchFilterString',['../interface_terraria_1_1_game_content_1_1_bestiary_1_1_i_provide_search_filter_string.html',1,'Terraria::GameContent::Bestiary']]],
  ['iprovidesliderelement_3724',['IProvideSliderElement',['../interface_terraria_1_1_game_content_1_1_creative_1_1_i_provide_slider_element.html',1,'Terraria::GameContent::Creative']]],
  ['irejectionreason_3725',['IRejectionReason',['../class_i_rejection_reason.html',1,'']]],
  ['isbloodmoonandnotfromstatue_3726',['IsBloodMoonAndNotFromStatue',['../class_terraria_1_1_game_content_1_1_item_drop_rules_1_1_conditions_1_1_is_blood_moon_and_not_from_statue.html',1,'Terraria::GameContent::ItemDropRules::Conditions']]],
  ['ischristmas_3727',['IsChristmas',['../class_terraria_1_1_game_content_1_1_item_drop_rules_1_1_conditions_1_1_is_christmas.html',1,'Terraria::GameContent::ItemDropRules::Conditions']]],
  ['iscorruption_3728',['IsCorruption',['../class_terraria_1_1_game_content_1_1_item_drop_rules_1_1_conditions_1_1_is_corruption.html',1,'Terraria::GameContent::ItemDropRules::Conditions']]],
  ['iscorruptionandnotexpert_3729',['IsCorruptionAndNotExpert',['../class_terraria_1_1_game_content_1_1_item_drop_rules_1_1_conditions_1_1_is_corruption_and_not_expert.html',1,'Terraria::GameContent::ItemDropRules::Conditions']]],
  ['iscrimson_3730',['IsCrimson',['../class_terraria_1_1_game_content_1_1_item_drop_rules_1_1_conditions_1_1_is_crimson.html',1,'Terraria::GameContent::ItemDropRules::Conditions']]],
  ['iscrimsonandnotexpert_3731',['IsCrimsonAndNotExpert',['../class_terraria_1_1_game_content_1_1_item_drop_rules_1_1_conditions_1_1_is_crimson_and_not_expert.html',1,'Terraria::GameContent::ItemDropRules::Conditions']]],
  ['isearchfilter_3732',['ISearchFilter',['../interface_terraria_1_1_data_structures_1_1_i_search_filter.html',1,'Terraria::DataStructures']]],
  ['isearchfilter_3c_20bestiaryentry_20_3e_3733',['ISearchFilter&lt; BestiaryEntry &gt;',['../interface_terraria_1_1_data_structures_1_1_i_search_filter.html',1,'Terraria::DataStructures']]],
  ['isearchfilter_3c_20item_20_3e_3734',['ISearchFilter&lt; Item &gt;',['../interface_terraria_1_1_data_structures_1_1_i_search_filter.html',1,'Terraria::DataStructures']]],
  ['isempty_3735',['IsEmpty',['../class_terraria_1_1_world_building_1_1_modifiers_1_1_is_empty.html',1,'Terraria::WorldBuilding::Modifiers']]],
  ['isexpert_3736',['IsExpert',['../class_terraria_1_1_game_content_1_1_item_drop_rules_1_1_conditions_1_1_is_expert.html',1,'Terraria::GameContent::ItemDropRules::Conditions']]],
  ['ishadereffect_3737',['IShaderEffect',['../interface_terraria_1_1_game_content_1_1_skies_1_1_credits_roll_1_1_segments_1_1_player_segment_1_1_i_shader_effect.html',1,'Terraria.GameContent.Skies.CreditsRoll.Segments.PlayerSegment.IShaderEffect'],['../interface_terraria_1_1_game_content_1_1_skies_1_1_credits_roll_1_1_segments_1_1_sprite_segment_1_1_i_shader_effect.html',1,'Terraria.GameContent.Skies.CreditsRoll.Segments.SpriteSegment.IShaderEffect']]],
  ['ishardmode_3738',['IsHardmode',['../class_terraria_1_1_game_content_1_1_item_drop_rules_1_1_conditions_1_1_is_hardmode.html',1,'Terraria::GameContent::ItemDropRules::Conditions']]],
  ['ishoppersonalitytrait_3739',['IShopPersonalityTrait',['../interface_terraria_1_1_game_content_1_1_personalities_1_1_i_shop_personality_trait.html',1,'Terraria::GameContent::Personalities']]],
  ['isimulationconditionsetter_3740',['ISimulationConditionSetter',['../interface_terraria_1_1_game_content_1_1_loot_simulation_1_1_i_simulation_condition_setter.html',1,'Terraria::GameContent::LootSimulation']]],
  ['ismartinteractblockreasonprovider_3741',['ISmartInteractBlockReasonProvider',['../interface_terraria_1_1_game_content_1_1_object_interactions_1_1_i_smart_interact_block_reason_provider.html',1,'Terraria::GameContent::ObjectInteractions']]],
  ['ismartinteractcandidate_3742',['ISmartInteractCandidate',['../interface_terraria_1_1_game_content_1_1_object_interactions_1_1_i_smart_interact_candidate.html',1,'Terraria::GameContent::ObjectInteractions']]],
  ['ismartinteractcandidateprovider_3743',['ISmartInteractCandidateProvider',['../interface_terraria_1_1_game_content_1_1_object_interactions_1_1_i_smart_interact_candidate_provider.html',1,'Terraria::GameContent::ObjectInteractions']]],
  ['ismastermode_3744',['IsMasterMode',['../class_terraria_1_1_game_content_1_1_item_drop_rules_1_1_conditions_1_1_is_master_mode.html',1,'Terraria::GameContent::ItemDropRules::Conditions']]],
  ['isnotsolid_3745',['IsNotSolid',['../class_terraria_1_1_world_building_1_1_modifiers_1_1_is_not_solid.html',1,'Terraria::WorldBuilding::Modifiers']]],
  ['isocialmodule_3746',['ISocialModule',['../interface_terraria_1_1_social_1_1_i_social_module.html',1,'Terraria::Social']]],
  ['isocket_3747',['ISocket',['../interface_terraria_1_1_net_1_1_sockets_1_1_i_socket.html',1,'Terraria::Net::Sockets']]],
  ['ispriteaction_3748',['ISpriteAction',['../interface_terraria_1_1_game_content_1_1_skies_1_1_credits_roll_1_1_actions_1_1_sprites_1_1_i_sprite_action.html',1,'Terraria::GameContent::Skies::CreditsRoll::Actions::Sprites']]],
  ['ispumpkinmoon_3749',['IsPumpkinMoon',['../class_terraria_1_1_game_content_1_1_item_drop_rules_1_1_conditions_1_1_is_pumpkin_moon.html',1,'Terraria::GameContent::ItemDropRules::Conditions']]],
  ['issolid_3750',['IsSolid',['../class_terraria_1_1_world_building_1_1_conditions_1_1_is_solid.html',1,'Terraria.WorldBuilding.Conditions.IsSolid'],['../class_terraria_1_1_world_building_1_1_modifiers_1_1_is_solid.html',1,'Terraria.WorldBuilding.Modifiers.IsSolid']]],
  ['issuereport_3751',['IssueReport',['../class_terraria_1_1_data_structures_1_1_issue_report.html',1,'Terraria::DataStructures']]],
  ['issuereportsindicator_3752',['IssueReportsIndicator',['../class_terraria_1_1_game_content_1_1_u_i_1_1_issue_reports_indicator.html',1,'Terraria::GameContent::UI']]],
  ['istaticportmapping_3753',['IStaticPortMapping',['../interface_n_a_t_u_p_n_p_lib_1_1_i_static_port_mapping.html',1,'NATUPNPLib']]],
  ['istaticportmappingcollection_3754',['IStaticPortMappingCollection',['../interface_n_a_t_u_p_n_p_lib_1_1_i_static_port_mapping_collection.html',1,'NATUPNPLib']]],
  ['istile_3755',['IsTile',['../class_terraria_1_1_world_building_1_1_conditions_1_1_is_tile.html',1,'Terraria::WorldBuilding::Conditions']]],
  ['istouching_3756',['IsTouching',['../class_terraria_1_1_world_building_1_1_modifiers_1_1_is_touching.html',1,'Terraria::WorldBuilding::Modifiers']]],
  ['istouchingair_3757',['IsTouchingAir',['../class_terraria_1_1_world_building_1_1_modifiers_1_1_is_touching_air.html',1,'Terraria::WorldBuilding::Modifiers']]],
  ['isusingspecificaivalues_3758',['IsUsingSpecificAIValues',['../class_terraria_1_1_game_content_1_1_item_drop_rules_1_1_conditions_1_1_is_using_specific_a_i_values.html',1,'Terraria::GameContent::ItemDropRules::Conditions']]],
  ['itaghandler_3759',['ITagHandler',['../interface_terraria_1_1_u_i_1_1_chat_1_1_i_tag_handler.html',1,'Terraria::UI::Chat']]],
  ['item_3760',['Item',['../class_terraria_1_1_item.html',1,'Terraria']]],
  ['itemalternativefunctionid_3761',['ItemAlternativeFunctionID',['../class_terraria_1_1_i_d_1_1_item_alternative_function_i_d.html',1,'Terraria::ID']]],
  ['itemcraftcondition_3762',['ItemCraftCondition',['../class_terraria_1_1_game_content_1_1_achievements_1_1_item_craft_condition.html',1,'Terraria::GameContent::Achievements']]],
  ['itemcreationcontext_3763',['ItemCreationContext',['../class_terraria_1_1_mod_loader_1_1_item_creation_context.html',1,'Terraria::ModLoader']]],
  ['itemdefinition_3764',['ItemDefinition',['../class_terraria_1_1_mod_loader_1_1_config_1_1_item_definition.html',1,'Terraria::ModLoader::Config']]],
  ['itemdefinitionelement_3765',['ItemDefinitionElement',['../class_terraria_1_1_mod_loader_1_1_config_1_1_u_i_1_1_item_definition_element.html',1,'Terraria::ModLoader::Config::UI']]],
  ['itemdropattemptresult_3766',['ItemDropAttemptResult',['../struct_terraria_1_1_game_content_1_1_item_drop_rules_1_1_item_drop_attempt_result.html',1,'Terraria::GameContent::ItemDropRules']]],
  ['itemdropbestiaryinfoelement_3767',['ItemDropBestiaryInfoElement',['../class_terraria_1_1_game_content_1_1_bestiary_1_1_item_drop_bestiary_info_element.html',1,'Terraria::GameContent::Bestiary']]],
  ['itemdropdatabase_3768',['ItemDropDatabase',['../class_terraria_1_1_game_content_1_1_item_drop_rules_1_1_item_drop_database.html',1,'Terraria::GameContent::ItemDropRules']]],
  ['itemdropresolver_3769',['ItemDropResolver',['../class_terraria_1_1_game_content_1_1_item_drop_rules_1_1_item_drop_resolver.html',1,'Terraria::GameContent::ItemDropRules']]],
  ['itemdroprule_3770',['ItemDropRule',['../class_terraria_1_1_game_content_1_1_item_drop_rules_1_1_item_drop_rule.html',1,'Terraria::GameContent::ItemDropRules']]],
  ['itemdropwithconditionrule_3771',['ItemDropWithConditionRule',['../class_terraria_1_1_game_content_1_1_item_drop_rules_1_1_item_drop_with_condition_rule.html',1,'Terraria::GameContent::ItemDropRules']]],
  ['itemfilters_3772',['ItemFilters',['../class_terraria_1_1_game_content_1_1_creative_1_1_item_filters.html',1,'Terraria::GameContent::Creative']]],
  ['itemfromcatchingnpcbestiaryinfoelement_3773',['ItemFromCatchingNPCBestiaryInfoElement',['../class_terraria_1_1_game_content_1_1_bestiary_1_1_item_from_catching_n_p_c_bestiary_info_element.html',1,'Terraria::GameContent::Bestiary']]],
  ['itemgroupandorderingroup_3774',['ItemGroupAndOrderInGroup',['../struct_terraria_1_1_i_d_1_1_content_samples_1_1_creative_helper_1_1_item_group_and_order_in_group.html',1,'Terraria::ID::ContentSamples::CreativeHelper']]],
  ['itemholdstyleid_3775',['ItemHoldStyleID',['../class_terraria_1_1_i_d_1_1_item_hold_style_i_d.html',1,'Terraria::ID']]],
  ['itemid_3776',['ItemID',['../class_terraria_1_1_i_d_1_1_item_i_d.html',1,'Terraria::ID']]],
  ['iteminstallinfo_3777',['ItemInstallInfo',['../struct_terraria_1_1_social_1_1_steam_1_1_workshop_helper_1_1_item_install_info.html',1,'Terraria::Social::Steam::WorkshopHelper']]],
  ['itemio_3778',['ItemIO',['../class_terraria_1_1_mod_loader_1_1_i_o_1_1_item_i_o.html',1,'Terraria::ModLoader::IO']]],
  ['itemloader_3779',['ItemLoader',['../class_terraria_1_1_mod_loader_1_1_item_loader.html',1,'Terraria::ModLoader']]],
  ['itempickupcondition_3780',['ItemPickupCondition',['../class_terraria_1_1_game_content_1_1_achievements_1_1_item_pickup_condition.html',1,'Terraria::GameContent::Achievements']]],
  ['itemrarity_3781',['ItemRarity',['../class_terraria_1_1_game_content_1_1_u_i_1_1_item_rarity.html',1,'Terraria::GameContent::UI']]],
  ['itemrarityid_3782',['ItemRarityID',['../class_terraria_1_1_i_d_1_1_item_rarity_i_d.html',1,'Terraria::ID']]],
  ['itemshopsellbackhelper_3783',['ItemShopSellbackHelper',['../class_terraria_1_1_game_content_1_1_item_shop_sellback_helper.html',1,'Terraria::GameContent']]],
  ['itemslot_3784',['ItemSlot',['../class_terraria_1_1_u_i_1_1_item_slot.html',1,'Terraria::UI']]],
  ['itemsorting_3785',['ItemSorting',['../class_terraria_1_1_u_i_1_1_item_sorting.html',1,'Terraria::UI']]],
  ['itemspacestatus_3786',['ItemSpaceStatus',['../struct_terraria_1_1_player_1_1_item_space_status.html',1,'Terraria::Player']]],
  ['itemssacrificedunlockstracker_3787',['ItemsSacrificedUnlocksTracker',['../class_terraria_1_1_game_content_1_1_creative_1_1_items_sacrificed_unlocks_tracker.html',1,'Terraria::GameContent::Creative']]],
  ['itemsyncpersistentstats_3788',['ItemSyncPersistentStats',['../struct_terraria_1_1_data_structures_1_1_item_sync_persistent_stats.html',1,'Terraria::DataStructures']]],
  ['itemtaghandler_3789',['ItemTagHandler',['../class_terraria_1_1_game_content_1_1_u_i_1_1_chat_1_1_item_tag_handler.html',1,'Terraria::GameContent::UI::Chat']]],
  ['itemtooltip_3790',['ItemTooltip',['../class_terraria_1_1_u_i_1_1_item_tooltip.html',1,'Terraria::UI']]],
  ['itemtransferinfo_3791',['ItemTransferInfo',['../struct_terraria_1_1_u_i_1_1_item_slot_1_1_item_transfer_info.html',1,'Terraria::UI::ItemSlot']]],
  ['itemusestyleid_3792',['ItemUseStyleID',['../class_terraria_1_1_i_d_1_1_item_use_style_i_d.html',1,'Terraria::ID']]],
  ['itiledata_3793',['ITileData',['../interface_terraria_1_1_i_tile_data.html',1,'Terraria']]],
  ['itownnpcprofile_3794',['ITownNPCProfile',['../interface_terraria_1_1_game_content_1_1_i_town_n_p_c_profile.html',1,'Terraria::GameContent']]],
  ['iupnpnat_3795',['IUPnPNAT',['../interface_n_a_t_u_p_n_p_lib_1_1_i_u_pn_p_n_a_t.html',1,'NATUPNPLib']]],
  ['ivalueprovider_3796',['IValueProvider',['../class_i_value_provider.html',1,'']]],
  ['ivertextype_3797',['IVertexType',['../class_i_vertex_type.html',1,'']]]
];
