<Project
	ToolsVersion="14.0"
	xmlns="http://schemas.microsoft.com/developer/msbuild/2003"
	InitialTargets="TmlCheckForWarnings"
>

	<!-- Set default values for our build config properties -->
	<PropertyGroup>
		<BuildMod Condition="'$(BuildMod)' == ''">true</BuildMod>
		<OutputTmlReferences Condition="'$(OutputTmlReferences)' == ''">false</OutputTmlReferences>
	</PropertyGroup>

	<!-- Build Defaults -->
	<PropertyGroup Condition="'$(BuildMod)' == 'true'">
		<PlatformTarget>AnyCPU</PlatformTarget>
		<TargetFramework>net10.0</TargetFramework>
		<LangVersion>14.0</LangVersion>

		<!-- Include annotations in compiled binary for mods to see. -->
		<DefineConstants>$(DefineConstants);JETBRAINS_ANNOTATIONS</DefineConstants>
	</PropertyGroup>

	<PropertyGroup>
		<!-- GetDirectoryName is used to get a path without a trailing slash. -->
		<TerrariaSteamPath Condition="'$(TerrariaSteamPath)' == ''">$([System.IO.Path]::GetDirectoryName('$(MSBuildThisFileDirectory)'))</TerrariaSteamPath>
		<tModLoaderSteamPath Condition="'$(tModLoaderSteamPath)' == ''">$([System.IO.Path]::GetDirectoryName('$(MSBuildThisFileDirectory)'))</tModLoaderSteamPath>
		<tMLLibraryPath>$(tModLoaderSteamPath)/Libraries</tMLLibraryPath>
		<!-- tMLSteamPath property is obsolete, switch to tModLoaderSteamPath. Note the lack of trailing slash. -->
		<tMLSteamPath>$(tModLoaderSteamPath)/</tMLSteamPath>
		<tMLName>tModLoader</tMLName>
		<tMLPath>$(tMLName).dll</tMLPath>
		<tMLServerPath>$(tMLPath) -server</tMLServerPath>
		<!-- The below comment gets replaced in the build script with <DefineConstant> -->
		<!-- TML stable version define placeholder -->

		<DotNetName Condition=" '$(OS)' == 'Windows_NT' ">dotnet.exe</DotNetName>
		<DotNetName Condition=" '$(OS)' == 'Unix' ">dotnet</DotNetName>
		<DotNetName Condition=" '$(DotNetName)' == '' ">dotnet</DotNetName>
	</PropertyGroup>

	<!-- Debug/run properties -->
	<PropertyGroup Condition="!Exists('/etc/NIXOS')">
		<ExecutablePath>$(DotNetName)</ExecutablePath>
		<TmlClientArgs>$(tMLPath)</TmlClientArgs>
		<TmlServerArgs>$(tMLServerPath)</TmlServerArgs>
	</PropertyGroup>
	<PropertyGroup Condition=" Exists('/etc/NIXOS')">
		<!-- NixOS: When starting TML via system .NET, the 'steam-run' wrapper must be used to create a FHS environment. -->
		<ExecutablePath>steam-run</ExecutablePath>
		<TmlClientArgs>$(DotNetName) $(tMLPath)</TmlClientArgs>
		<TmlServerArgs>$(DotNetName) $(tMLServerPath)</TmlServerArgs>
	</PropertyGroup>

	<!-- Build/packaging properties -->
	<PropertyGroup Condition="'$(BuildMod)' == 'true'">
		<!--
			NixOS: The 'steam-run' FHS wrapper is purposefully not used for mod builds,
			as it is not available on non-Steam supported architectures, such as ARM.
			This is okay, as builds use fewer system libraries than clients and servers.
		-->
		<BuildLaunch>$(DotNetName)</BuildLaunch>
		<BuildArch>$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)</BuildArch>
		<BuildEnvVars Condition="'$(OS)' == 'Windows_NT'"></BuildEnvVars>
		<BuildEnvVars Condition="'$(OS)' == 'Unix' AND '$(BuildArch)' != 'Arm64'">LD_LIBRARY_PATH=$(tModLoaderSteamPath)/Libraries/Native/Linux</BuildEnvVars>
		<BuildEnvVars Condition="'$(OS)' == 'Unix' AND '$(BuildArch)' == 'Arm64'">LD_LIBRARY_PATH=$(tModLoaderSteamPath)/Libraries/Native/Linux-arm64</BuildEnvVars>
		<BuildEnvVars Condition="'$(OS)' == 'OSX'">DYLD_LIBRARY_PATH=$(tModLoaderSteamPath)/Libraries/Native/OSX</BuildEnvVars>
	</PropertyGroup>

	<ItemGroup Condition="'$(BuildMod)' == 'true'">
		<AdditionalFiles Include="**/*.hjson" />
		<AdditionalFiles Include="**/*.txt" />
		<AdditionalFiles Include="**/*.png" />
		<AdditionalFiles Include="**/*.fx" />
		<!-- Remove the txt files that can be found in build folders, causing them to appear in the editor -->
		<AdditionalFiles Remove="bin/**" />
		<AdditionalFiles Remove="obj/**" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="$(tModLoaderSteamPath)/$(tMLPath)" Private="$(OutputTmlReferences)" />
		<Reference Include="$(tMLLibraryPath)/**/*.dll" Private="$(OutputTmlReferences)" />
		<Reference Remove="$(tMLLibraryPath)/Native/**" />
		<Reference Remove="$(tMLLibraryPath)/**/runtime*/**" />
		<Reference Remove="$(tMLLibraryPath)/**/*.resources.dll" />
		<Reference Remove="$(tMLLibraryPath)/tModCodeAssist/**" />
		<Analyzer Include="$(tMLLibraryPath)/tModCodeAssist/1.0.0/tModCodeAssist.dll" />
		<Analyzer Include="$(tMLLibraryPath)/tModCodeAssist/1.0.0/tModCodeAssist.CodeFixes.dll" />
	</ItemGroup>

	<Target Name="TmlCheckForWarnings">
		<!-- NixOS only: Check if steam-run is available. -->
		<Exec Condition="Exists('/etc/NIXOS')" Command="which steam-run &gt;/dev/null" IgnoreExitCode="True">
			<Output TaskParameter="ExitCode" PropertyName="SteamRunCheck" />
		</Exec>
		<!-- NixOS only: Notify the user if steam-run is unavailable. -->
		<Warning Condition="Exists('/etc/NIXOS') And '$(SteamRunCheck)' != '0'" Text="To debug mods on NixOS, add the 'steam-run' package to your system environment." />
	</Target>

	<!-- Package the mod after building its code -->
	<Target Name="BuildMod" AfterTargets="Build" Condition="'$(BuildMod)' == 'true'">
		<Exec
			Command="$(BuildLaunch) $(tMLServerPath) -build $(ProjectDir) -eac $(TargetPath) -define &quot;$(DefineConstants)&quot; -unsafe $(AllowUnsafeBlocks) $(ExtraBuildModFlags)"
			WorkingDirectory="$(tModLoaderSteamPath)"
			EnvironmentVariables="$(BuildEnvVars)"
		/>
	</Target>

</Project>