Terraria ModLoader: Terraria.ModLoader.SoundLoader Class Reference
Terraria.ModLoader.SoundLoader Class Reference
This class is used to keep track of and support the existence of custom sounds that have been added to the game.
Static Public Member Functions
static int GetSoundSlot (SoundType type, string sound)
Returns the style (last parameter passed to Main.PlaySound) of the sound corresponding to the given SoundType and the given sound file path. Returns 0 if there is no corresponding style.
static int SoundCount (SoundType type)
Public Attributes
const int customSoundType = 50
This value should be passed as the first parameter to Main.PlaySound whenever you want to play a custom sound that is not an item, npcHit, or npcKilled sound.
Static Private Member Functions
static SoundLoader ()
Static Private Attributes
static readonly IDictionary< SoundType, int > nextSound = new Dictionary<SoundType, int>()
Detailed Description
This class is used to keep track of and support the existence of custom sounds that have been added to the game.
Definition at line 11 of file SoundLoader.cs.
Constructor & Destructor Documentation
static Terraria.ModLoader.SoundLoader.SoundLoader () static private
Definition at line 26 of file SoundLoader.cs.
{
             foreach (SoundType type in Enum.GetValues(typeof(SoundType))) {
                 nextSound[type] = GetNumVanilla(type);
                 sounds[type] = new Dictionary<string, int>();
                 modSounds[type] = new Dictionary<int, ModSound>();
             }
         }
Member Function Documentation
static int Terraria.ModLoader.SoundLoader.GetSoundSlot (SoundType type, string sound) static
Returns the style (last parameter passed to Main.PlaySound) of the sound corresponding to the given SoundType and the given sound file path. Returns 0 if there is no corresponding style.
Definition at line 47 of file SoundLoader.cs.
References Terraria.ModLoader.ModContent.GetMusic(), and Terraria.ModLoader.ModContent.GetSound().
Referenced by Terraria.ModLoader.Mod.AddSound().
{
             if (sounds[type].ContainsKey(sound)) {
                 return sounds[type][sound];
             }
             else {
                 return 0;
             }
         }
static int Terraria.ModLoader.SoundLoader.SoundCount (SoundType type) static
Definition at line 40 of file SoundLoader.cs.
Referenced by Terraria.ModLoader.Mod.AddMusicBox().
{
             return nextSound[type];
         }
Member Data Documentation
const int Terraria.ModLoader.SoundLoader.customSoundType = 50
This value should be passed as the first parameter to Main.PlaySound whenever you want to play a custom sound that is not an item, npcHit, or npcKilled sound.
Definition at line 21 of file SoundLoader.cs.
readonly IDictionary<SoundType, int> Terraria.ModLoader.SoundLoader.nextSound = new Dictionary<SoundType, int>() static private
Definition at line 13 of file SoundLoader.cs.