Terraria ModLoader: Terraria.ModLoader.ModLoader Class Reference
Terraria.ModLoader.ModLoader Class Reference
This serves as the central class which loads mods. It contains many static fields and methods related to mods and their contents.
Classes
class LoadingMod
Static Public Member Functions
static bool FileExists (string name)
Returns whether or not a file with the specified name exists.
static byte[] GetFileBytes (string name)
Gets the byte representation of the file with the specified name. The name is in the format of "ModFolder/OtherFolders/FileNameWithExtension". Throws an ArgumentException if the file does not exist.
static string[] GetLoadedMods ()
Returns an array containing the names of all loaded mods. The array entries will be in the reverse order in which the mods were loaded.
static Mod GetMod (string name)
Gets the instance of the Mod with the specified name.
static Mod GetMod (int index)
static Music GetMusic (string name)
Gets the music with the specified name. The name is in the same format as for texture names. Throws an ArgumentException if the music does not exist. Note: SoundMP3 is in the Terraria.ModLoader namespace.
static SoundEffect GetSound (string name)
Gets the sound with the specified name. The name is in the same format as for texture names. Throws an ArgumentException if the sound does not exist. Note: SoundEffect is in the Microsoft.Xna.Framework.Audio namespace.
static Texture2D GetTexture (string name)
Gets the texture with the specified name. The name is in the format of "ModFolder/OtherFolders/FileNameWithoutExtension". Throws an ArgumentException if the texture does not exist. If a vanilla texture is desired, the format "Terraria/FileNameWithoutExtension" will reference an image from the "terraria/Content/Images" folder. Note: Texture2D is in the Microsoft.Xna.Framework.Graphics namespace.
static bool IsSignedBy (TmodFile mod, string xmlPublicKey)
static bool MusicExists (string name)
Returns whether or not a sound with the specified name exists.
static void RefreshModLanguage (GameCulture culture)
static ModHotKey RegisterHotKey (Mod mod, string name, string defaultKey)
static bool SoundExists (string name)
Returns whether or not a sound with the specified name exists.
static bool TextureExists (string name)
Returns whether or not a texture with the specified name exists.
Static Public Attributes
static readonly string compressedPlatformRepresentation = (windows ? "w" : (linux ? "l" : "m")) + (gog ? "g" : "s")
static readonly bool gog = false
static readonly bool linux = false
static Mod[] LoadedMods => (Mod[])loadedMods.Clone()
static readonly bool mac = false
static int ModCount => loadedMods.Length
static string ModPath => modPath
The file path in which mods are stored.
static readonly string ModSourcePath = Main.SavePath + Path.DirectorySeparatorChar + "Mod Sources"
The file path in which mod sources are stored. Mod sources are the code and images that developers work with.
static readonly Version version = new Version(0, 10, 0, 3)
The name and version number of tModLoader.
static readonly string versionedName = "tModLoader v" + version
static readonly bool windows = false
Static Private Member Functions
static TopoSort< LoadingMod > BuildSort (ICollection< LoadingMod > mods)
static bool CommandLineModPackOverride ()
static void DisposeMusic ()
static void LoadEnabledModCache ()
static bool LoadMods ()
static void PostBuildMenu (bool success)
static void ResizeArrays (bool unloading=false)
static LocalizedText SetLocalizedText (Dictionary< string, LocalizedText > dict, LocalizedText value)
static void SplitName (string name, out string domain, out string subName)
static bool VerifyNames (List< LoadingMod > mods)
Static Private Attributes
static HashSet< string > enabledMods
A cached list of enabled mods (not necessarily currently loaded or even installed), mirroring the enabled.json file.
static readonly string ImagePath = "Content" + Path.DirectorySeparatorChar + "Images"
static Mod[] loadedMods = new Mod[0]
static WeakReference[] loadedModsWeakReferences = new WeakReference[0]
static readonly Stack< string > loadOrder = new Stack<string>()
static string steamID64 = ""
Detailed Description
This serves as the central class which loads mods. It contains many static fields and methods related to mods and their contents.
Definition at line 26 of file ModLoader.cs.
Member Function Documentation
static TopoSort<LoadingMod> Terraria.ModLoader.ModLoader.BuildSort (ICollection< LoadingMod > mods) static private
Definition at line 617 of file ModLoader.cs.
References Terraria.ModLoader.ModNet.AllowVanillaClients, Terraria.ModLoader.ModItem.item, Terraria.ModLoader.ErrorLogger.Log(), and Terraria.ModLoader.ModNPC.npc.
         {
             var nameMap = mods.ToDictionary(mod => mod.Name);
             return new TopoSort<LoadingMod>(mods,
                 mod => mod.properties.sortAfter.Where(nameMap.ContainsKey).Select(name => nameMap[name]),
                 mod => mod.properties.sortBefore.Where(nameMap.ContainsKey).Select(name => nameMap[name]));
         }
static bool Terraria.ModLoader.ModLoader.CommandLineModPackOverride () static private
Definition at line 418 of file ModLoader.cs.
References Terraria.ModLoader.Console.
         {
             if (commandLineModPack != "")
             {
                 try
                 {
                     string fileName = UI.UIModPacks.ModListSaveDirectory + Path.DirectorySeparatorChar + commandLineModPack + ".json";
                     Directory.CreateDirectory(UI.UIModPacks.ModListSaveDirectory);
                     if (File.Exists(fileName))
                     {
                         using (StreamReader r = new StreamReader(fileName))
{
                             Console.WriteLine($"Loading specified modpack: {commandLineModPack}\n");
                             string json = r.ReadToEnd();
                             string[] modsToEnable = JsonConvert.DeserializeObject<string[]>(json);
                             var mods = ModLoader.FindMods();
                             foreach (var item in mods)
{
                                 DisableMod(item);
                             }
                             foreach (string modname in modsToEnable)
{
                                 foreach (var item in mods)
{
                                     if (item.name == modname)
{
                                         EnableMod(item);
                                     }
                                 }
                             }
                         }
                     }
                     else
                     {
                         if (Main.dedServ)
{
                             Console.ForegroundColor = ConsoleColor.Red;
                             Console.WriteLine($"No modpack named {commandLineModPack} was found in {UI.UIModPacks.ModListSaveDirectory}. Make sure not to include the .json extension.\n");
                             Console.ResetColor();
                         }
                         else
{
                             Interface.errorMessage.SetMessage($"No modpack named {commandLineModPack} was found in {UI.UIModPacks.ModListSaveDirectory}. Make sure not to include the .json extension.");
                         }
                         commandLineModPack = "";
                         return false;
                     }
                 }
                 catch
                 {
                     if (Main.dedServ)
                     {
                         Console.ForegroundColor = ConsoleColor.Red;
                         Console.WriteLine($"The {commandLineModPack} modpack failed to be read properly, it might be malformed.\n");
                         Console.ResetColor();
                     }
                     else
                     {
                         Interface.errorMessage.SetMessage($"No modpack named {commandLineModPack} was found in {UI.UIModPacks.ModListSaveDirectory}. Make sure not to include the .json extension.");
                     }
                     commandLineModPack = "";
                     return false;
                 }
             }
             commandLineModPack = "";
             return true;
         }
static void Terraria.ModLoader.ModLoader.DisposeMusic () static private
Definition at line 744 of file ModLoader.cs.
         {
             for (int i = 0; i < Main.music.Length; i++)
             {
                 MusicStreaming music = Main.music[i] as MusicStreaming;
                 if (music != null)
                 {
                     if (i < Main.maxMusic)
                     {
                         Main.music[i] = Main.soundBank.GetCue("Music_" + i);
                     }
                     else
                     {
                         Main.music[i] = null;
                     }
                     music.Stop(AudioStopOptions.Immediate);
                     music.Dispose();
                 }
             }
         }
static bool Terraria.ModLoader.ModLoader.FileExists (string name) static
Returns whether or not a file with the specified name exists.
Definition at line 899 of file ModLoader.cs.
References Terraria.ModLoader.Mod.FileExists().
Referenced by Terraria.ModLoader.Mod.AddNPCHeadTexture().
         {
             if (!name.Contains('/'))
                 return false;
             string modName, subName;
             SplitName(name, out modName, out subName);
             Mod mod = GetMod(modName);
             return mod != null && mod.FileExists(subName);
         }
static byte [] Terraria.ModLoader.ModLoader.GetFileBytes (string name) static
Gets the byte representation of the file with the specified name. The name is in the format of "ModFolder/OtherFolders/FileNameWithExtension". Throws an ArgumentException if the file does not exist.
Exceptions
MissingResourceException Missing mod: " + name
Definition at line 884 of file ModLoader.cs.
References Terraria.ModLoader.Mod.GetFileBytes().
         {
             string modName, subName;
             SplitName(name, out modName, out subName);
             Mod mod = GetMod(modName);
             if (mod == null)
                 throw new MissingResourceException("Missing mod: " + name);
             return mod.GetFileBytes(subName);
         }
static string [] Terraria.ModLoader.ModLoader.GetLoadedMods () static
Returns an array containing the names of all loaded mods. The array entries will be in the reverse order in which the mods were loaded.
Definition at line 122 of file ModLoader.cs.
References Terraria.ModLoader.Console, Terraria.ModLoader.Mod.File, Terraria.ModLoader.Mod.Load(), Terraria.ModLoader.Exceptions.AddRecipesException.modName, Terraria.ModLoader.Mod.Name, Terraria.ModLoader.Mod.PostSetupContent(), and Terraria.ModLoader.Mod.tModLoaderVersion.
         {
             return loadOrder.ToArray();
         }
static Mod Terraria.ModLoader.ModLoader.GetMod (string name) static
Gets the instance of the Mod with the specified name.
Definition at line 105 of file ModLoader.cs.
Referenced by Terraria.ModLoader.IO.ItemIO.Load(), Terraria.ModLoader.IO.ItemIO.LoadLegacy(), Terraria.ModLoader.CommandManager.Matches(), Terraria.ModLoader.PlayerHooks.ReceiveCustomBiomes(), and Terraria.ModLoader.PlayerHooks.SetStartInventory().
         {
             Mod m;
             mods.TryGetValue(name, out m);
             return m;
         }
static Mod Terraria.ModLoader.ModLoader.GetMod (int index) static
Definition at line 112 of file ModLoader.cs.
         {
             return index >= 0 && index < loadedMods.Length ? loadedMods[index] : null;
         }
static Music Terraria.ModLoader.ModLoader.GetMusic (string name) static
Gets the music with the specified name. The name is in the same format as for texture names. Throws an ArgumentException if the music does not exist. Note: SoundMP3 is in the Terraria.ModLoader namespace.
Exceptions
MissingResourceException Missing mod: " + name
Definition at line 988 of file ModLoader.cs.
References Terraria.ModLoader.Mod.GetMusic(), and Terraria.ModLoader.Music.
Referenced by Terraria.ModLoader.SoundLoader.GetSoundSlot().
         {
             if (Main.dedServ) { return null; }
             string modName, subName;
             SplitName(name, out modName, out subName);
             Mod mod = GetMod(modName);
             if (mod == null) { throw new MissingResourceException("Missing mod: " + name); }
             return mod.GetMusic(subName);
         }
static SoundEffect Terraria.ModLoader.ModLoader.GetSound (string name) static
Gets the sound with the specified name. The name is in the same format as for texture names. Throws an ArgumentException if the sound does not exist. Note: SoundEffect is in the Microsoft.Xna.Framework.Audio namespace.
Exceptions
MissingResourceException Missing mod: " + name
Definition at line 954 of file ModLoader.cs.
References Terraria.ModLoader.Mod.GetSound().
Referenced by Terraria.ModLoader.Mod.AddSound(), and Terraria.ModLoader.SoundLoader.GetSoundSlot().
         {
             if (Main.dedServ)
                 return null;
             string modName, subName;
             SplitName(name, out modName, out subName);
             Mod mod = GetMod(modName);
             if (mod == null)
                 throw new MissingResourceException("Missing mod: " + name);
             return mod.GetSound(subName);
         }
static Texture2D Terraria.ModLoader.ModLoader.GetTexture (string name) static
Gets the texture with the specified name. The name is in the format of "ModFolder/OtherFolders/FileNameWithoutExtension". Throws an ArgumentException if the texture does not exist. If a vanilla texture is desired, the format "Terraria/FileNameWithoutExtension" will reference an image from the "terraria/Content/Images" folder. Note: Texture2D is in the Microsoft.Xna.Framework.Graphics namespace.
Exceptions
MissingResourceException Missing mod: " + name
Definition at line 915 of file ModLoader.cs.
Referenced by Terraria.ModLoader.Mod.AddBackgroundTexture(), Terraria.ModLoader.Mod.AddBossHeadTexture(), Terraria.ModLoader.Mod.AddDust(), Terraria.ModLoader.Mod.AddEquipTexture(), Terraria.ModLoader.Mod.AddMount(), Terraria.ModLoader.Mod.AddNPCHeadTexture(), Terraria.ModLoader.Mod.AddTranslation(), Terraria.ModLoader.ModProjectile.AutoStaticDefaults(), Terraria.ModLoader.ModItem.AutoStaticDefaults(), Terraria.ModLoader.ModNPC.AutoStaticDefaults(), Terraria.ModLoader.BackgroundTextureLoader.GetBackgroundSlot(), Terraria.ModLoader.NPCHeadLoader.GetBossHeadSlot(), Terraria.ModLoader.EquipLoader.GetEquipTexture(), and Terraria.ModLoader.ModGore.GetGoreSlot().
         {
             if (Main.dedServ)
                 return null;
             string modName, subName;
             SplitName(name, out modName, out subName);
             if (modName == "Terraria")
                 return Main.instance.Content.Load<Texture2D>("Images" + Path.DirectorySeparatorChar + subName);
             Mod mod = GetMod(modName);
             if (mod == null)
                 throw new MissingResourceException("Missing mod: " + name);
             return mod.GetTexture(subName);
         }
static bool Terraria.ModLoader.ModLoader.IsSignedBy (TmodFile mod, string xmlPublicKey) static
Definition at line 487 of file ModLoader.cs.
References Terraria.ModLoader.IO.TmodFile.hash.
         {
             var f = new RSAPKCS1SignatureDeformatter();
             var v = AsymmetricAlgorithm.Create("RSA");
             f.SetHashAlgorithm("SHA1");
             v.FromXmlString(xmlPublicKey);
             f.SetKey(v);
             return f.VerifySignature(mod.hash, mod.signature);
         }
static void Terraria.ModLoader.ModLoader.LoadEnabledModCache () static private
Definition at line 784 of file ModLoader.cs.
References Terraria.ModLoader.IO.TmodFile.name.
         {
             enabledMods = new HashSet<string>();
             string path = ModPath + Path.DirectorySeparatorChar + "enabled.json";
             if (File.Exists(path))
             {
                 using (StreamReader r = new StreamReader(path))
                 {
                     string json = r.ReadToEnd();
                     try
                     {
                         enabledMods = JsonConvert.DeserializeObject<HashSet<string>>(json);
                     }
                     catch { }
                 }
             }
         }
static bool Terraria.ModLoader.ModLoader.LoadMods () static private
Definition at line 365 of file ModLoader.cs.
         {
             //load all referenced assemblies before mods for compiling
             ModCompile.LoadReferences();
             if (!CommandLineModPackOverride())
                 return false;
             Interface.loadMods.SetProgressFinding();
             var modsToLoad = FindMods()
                 .Where(IsEnabled)
                 .Select(mod => new LoadingMod(mod, BuildProperties.ReadModFile(mod)))
                 .Where(mod => LoadSide(mod.properties.side))
                 .ToList();
             // Press shift while starting up tModLoader or while trapped in a reload cycle to skip loading all mods.
             if (Main.oldKeyState.PressingShift())
                 modsToLoad.Clear();
             if (!VerifyNames(modsToLoad))
                 return false;
             try
             {
                 EnsureDependenciesExist(modsToLoad, false);
                 EnsureTargetVersionsMet(modsToLoad);
                 modsToLoad = Sort(modsToLoad);
             }
             catch (ModSortingException e)
             {
                 foreach (var mod in e.errored)
                     DisableMod(mod.modFile);
                 ErrorLogger.LogDependencyError(e.Message);
                 return false;
             }
             var modInstances = AssemblyManager.InstantiateMods(modsToLoad);
             if (modInstances == null)
                 return false;
             modInstances.Insert(0, new ModLoaderMod());
             loadedMods = modInstances.ToArray();
             loadedModsWeakReferences = loadedMods.Skip(1).Select(x => new WeakReference(x)).ToArray();
             foreach (var mod in modInstances)
             {
                 loadOrder.Push(mod.Name);
                 mods[mod.Name] = mod;
             }
             return true;
         }
static bool Terraria.ModLoader.ModLoader.MusicExists (string name) static
Returns whether or not a sound with the specified name exists.
Definition at line 1001 of file ModLoader.cs.
References Terraria.ModLoader.Mod.MusicExists().
         {
             if (!name.Contains('/')) { return false; }
             string modName, subName;
             SplitName(name, out modName, out subName);
             Mod mod = GetMod(modName);
             return mod != null && mod.MusicExists(subName);
         }
static void Terraria.ModLoader.ModLoader.PostBuildMenu (bool success) static private
Definition at line 865 of file ModLoader.cs.
         {
             Main.menuMode = success ? (reloadAfterBuild ? Interface.reloadModsID : 0) : Interface.errorMessageID;
         }
static void Terraria.ModLoader.ModLoader.RefreshModLanguage (GameCulture culture) static
Definition at line 256 of file ModLoader.cs.
References Terraria.ModLoader.ModBuff.Description, Terraria.ModLoader.ModBuff.DisplayName, Terraria.ModLoader.ModNPC.DisplayName, Terraria.ModLoader.ModItem.DisplayName, Terraria.ModLoader.ModProjectile.DisplayName, Terraria.ModLoader.ModTranslation.GetTranslation(), Terraria.ModLoader.ModItem.item, Terraria.ModLoader.ModTranslation.Key, Terraria.ModLoader.ModNPC.npc, Terraria.ModLoader.ModProjectile.projectile, Terraria.ModLoader.ModItem.Tooltip, and Terraria.ModLoader.ModBuff.Type.
         {
             Dictionary<string, LocalizedText> dict = LanguageManager.Instance._localizedTexts;
             foreach (ModItem item in ItemLoader.items)
             {
                 LocalizedText text = new LocalizedText(item.DisplayName.Key, item.DisplayName.GetTranslation(culture));
                 Lang._itemNameCache[item.item.type] = SetLocalizedText(dict, text);
                 text = new LocalizedText(item.Tooltip.Key, item.Tooltip.GetTranslation(culture));
                 if (text.Value != null)
                 {
                     text = SetLocalizedText(dict, text);
                     Lang._itemTooltipCache[item.item.type] = ItemTooltip.FromLanguageKey(text.Key);
                 }
             }
             foreach (var keyValuePair in MapLoader.tileEntries)
             {
                 foreach (MapEntry entry in keyValuePair.Value)
                 {
                     if (entry.translation != null)
                     {
                         LocalizedText text = new LocalizedText(entry.translation.Key, entry.translation.GetTranslation(culture));
                         SetLocalizedText(dict, text);
                     }
                 }
             }
             foreach (var keyValuePair in MapLoader.wallEntries)
             {
                 foreach (MapEntry entry in keyValuePair.Value)
                 {
                     if (entry.translation != null)
                     {
                         LocalizedText text = new LocalizedText(entry.translation.Key, entry.translation.GetTranslation(culture));
                         SetLocalizedText(dict, text);
                     }
                 }
             }
             foreach (ModProjectile proj in ProjectileLoader.projectiles)
             {
                 LocalizedText text = new LocalizedText(proj.DisplayName.Key, proj.DisplayName.GetTranslation(culture));
                 Lang._projectileNameCache[proj.projectile.type] = SetLocalizedText(dict, text);
             }
             foreach (ModNPC npc in NPCLoader.npcs)
             {
                 LocalizedText text = new LocalizedText(npc.DisplayName.Key, npc.DisplayName.GetTranslation(culture));
                 Lang._npcNameCache[npc.npc.type] = SetLocalizedText(dict, text);
             }
             foreach (ModBuff buff in BuffLoader.buffs)
             {
                 LocalizedText text = new LocalizedText(buff.DisplayName.Key, buff.DisplayName.GetTranslation(culture));
                 Lang._buffNameCache[buff.Type] = SetLocalizedText(dict, text);
                 text = new LocalizedText(buff.Description.Key, buff.Description.GetTranslation(culture));
                 Lang._buffDescriptionCache[buff.Type] = SetLocalizedText(dict, text);
             }
             foreach (Mod mod in loadedMods)
             {
                 foreach (ModTranslation translation in mod.translations.Values)
                 {
                     LocalizedText text = new LocalizedText(translation.Key, translation.GetTranslation(culture));
                     SetLocalizedText(dict, text);
                 }
             }
             LanguageManager.Instance.ProcessCopyCommandsInTexts();
         }
static ModHotKey Terraria.ModLoader.ModLoader.RegisterHotKey (Mod mod, string name, string defaultKey) static
Definition at line 1010 of file ModLoader.cs.
References Terraria.ModLoader.IO.TmodFile.name, Terraria.ModLoader.Mod.Name, and Terraria.ModLoader.ModLoader.steamID64.
Referenced by Terraria.ModLoader.Mod.RegisterHotKey().
         {
             string key = mod.Name + ": " + name;
             modHotKeys[key] = new ModHotKey(mod, name, defaultKey);
             return modHotKeys[key];
         }
static void Terraria.ModLoader.ModLoader.ResizeArrays (bool unloading = false) static private
Definition at line 227 of file ModLoader.cs.
         {
             ItemLoader.ResizeArrays(unloading);
             EquipLoader.ResizeAndFillArrays();
             Main.InitializeItemAnimations();
             ModDust.ResizeArrays();
             TileLoader.ResizeArrays(unloading);
             WallLoader.ResizeArrays(unloading);
             ProjectileLoader.ResizeArrays();
             NPCLoader.ResizeArrays(unloading);
             NPCHeadLoader.ResizeAndFillArrays();
             ModGore.ResizeAndFillArrays();
             SoundLoader.ResizeAndFillArrays();
             MountLoader.ResizeArrays();
             BuffLoader.ResizeArrays();
             PlayerHooks.RebuildHooks();
             BackgroundTextureLoader.ResizeAndFillArrays();
             UgBgStyleLoader.ResizeAndFillArrays();
             SurfaceBgStyleLoader.ResizeAndFillArrays();
             GlobalBgStyleLoader.ResizeAndFillArrays(unloading);
             WaterStyleLoader.ResizeArrays();
             WaterfallStyleLoader.ResizeArrays();
             WorldHooks.ResizeArrays();
             foreach (LocalizedText text in LanguageManager.Instance._localizedTexts.Values)
             {
                 text.Override = null;
             }
         }
static LocalizedText Terraria.ModLoader.ModLoader.SetLocalizedText (Dictionary< string, LocalizedText > dict, LocalizedText value) static private
Definition at line 320 of file ModLoader.cs.
         {
             if (dict.ContainsKey(value.Key))
             {
                 dict[value.Key].SetValue(value.Value);
             }
             else
             {
                 dict[value.Key] = value;
             }
             return dict[value.Key];
         }
static bool Terraria.ModLoader.ModLoader.SoundExists (string name) static
Returns whether or not a sound with the specified name exists.
Definition at line 972 of file ModLoader.cs.
References Terraria.ModLoader.Mod.SoundExists().
         {
             if (!name.Contains('/'))
                 return false;
             string modName, subName;
             SplitName(name, out modName, out subName);
             Mod mod = GetMod(modName);
             return mod != null && mod.SoundExists(subName);
         }
static void Terraria.ModLoader.ModLoader.SplitName (string name, out string domain, out string subName) static private
Definition at line 870 of file ModLoader.cs.
         {
             int slash = name.IndexOf('/');
             if (slash < 0)
                 throw new MissingResourceException("Missing mod qualifier: " + name);
             domain = name.Substring(0, slash);
             subName = name.Substring(slash + 1);
         }
static bool Terraria.ModLoader.ModLoader.TextureExists (string name) static
Returns whether or not a texture with the specified name exists.
Definition at line 935 of file ModLoader.cs.
References Terraria.ModLoader.Mod.TextureExists().
Referenced by Terraria.ModLoader.Mod.AddEquipTexture(), Terraria.ModLoader.Mod.AddMount(), and Terraria.ModLoader.ModItem.AutoStaticDefaults().
         {
             if (!name.Contains('/'))
                 return false;
             string modName, subName;
             SplitName(name, out modName, out subName);
             if (modName == "Terraria")
                 return File.Exists(ImagePath + Path.DirectorySeparatorChar + name + ".xnb");
             Mod mod = GetMod(modName);
             return mod != null && mod.TextureExists(subName);
         }
static bool Terraria.ModLoader.ModLoader.VerifyNames (List< LoadingMod > mods) static private
Definition at line 497 of file ModLoader.cs.
References Terraria.ModLoader.TopoSort< T >.AllDependencies(), Terraria.ModLoader.TopoSort< T >.Dependencies(), and Terraria.ModLoader.TopoSort< T >.list.
         {
             var names = new HashSet<string>();
             foreach (var mod in mods)
             {
                 try
                 {
                     if (mod.Name.Length == 0)
                         throw new ModNameException("Mods must actually have stuff in their names");
                     if (mod.Name.Equals("Terraria", StringComparison.InvariantCultureIgnoreCase))
                         throw new ModNameException("Mods names cannot be named Terraria");
                     if (names.Contains(mod.Name))
                         throw new ModNameException("Two mods share the internal name " + mod.Name);
                     if (mod.Name.IndexOf('.') >= 0)
                         throw new ModNameException("A mod's internal name cannot contain a period");
                     names.Add(mod.Name);
                 }
                 catch (Exception e)
                 {
                     DisableMod(mod.modFile);
                     ErrorLogger.LogLoadingError(mod.Name, mod.modFile.tModLoaderVersion, e);
                     return false;
                 }
             }
             return true;
         }
Member Data Documentation
readonly string Terraria.ModLoader.ModLoader.compressedPlatformRepresentation = (windows ? "w" : (linux ? "l" : "m")) + (gog ? "g" : "s") static
Definition at line 52 of file ModLoader.cs.
HashSet<string> Terraria.ModLoader.ModLoader.enabledMods static private
A cached list of enabled mods (not necessarily currently loaded or even installed), mirroring the enabled.json file.
Definition at line 774 of file ModLoader.cs.
readonly bool Terraria.ModLoader.ModLoader.gog = false static
Definition at line 50 of file ModLoader.cs.
readonly string Terraria.ModLoader.ModLoader.ImagePath = "Content" + Path.DirectorySeparatorChar + "Images" static private
Definition at line 59 of file ModLoader.cs.
readonly bool Terraria.ModLoader.ModLoader.linux = false static
Definition at line 40 of file ModLoader.cs.
Mod [] Terraria.ModLoader.ModLoader.loadedMods = new Mod[0] static private
Definition at line 66 of file ModLoader.cs.
Mod [] Terraria.ModLoader.ModLoader.LoadedMods => (Mod[])loadedMods.Clone() static
Definition at line 117 of file ModLoader.cs.
Referenced by Terraria.ModLoader.IO.TagSerializer< T, S >.GetType(), Terraria.ModLoader.ModNet.OnModsDownloaded(), and Terraria.ModLoader.ModNet.ReadNetIDs().
WeakReference [] Terraria.ModLoader.ModLoader.loadedModsWeakReferences = new WeakReference[0] static private
Definition at line 65 of file ModLoader.cs.
readonly Stack<string> Terraria.ModLoader.ModLoader.loadOrder = new Stack<string>() static private
Definition at line 64 of file ModLoader.cs.
readonly bool Terraria.ModLoader.ModLoader.mac = false static
Definition at line 45 of file ModLoader.cs.
int Terraria.ModLoader.ModLoader.ModCount => loadedMods.Length static
Definition at line 100 of file ModLoader.cs.
string Terraria.ModLoader.ModLoader.ModPath => modPath static
The file path in which mods are stored.
Definition at line 55 of file ModLoader.cs.
Referenced by Terraria.ModLoader.ModNet.ModHeader.ModHeader().
readonly string Terraria.ModLoader.ModLoader.ModSourcePath = Main.SavePath + Path.DirectorySeparatorChar + "Mod Sources" static
The file path in which mod sources are stored. Mod sources are the code and images that developers work with.
Definition at line 58 of file ModLoader.cs.
string Terraria.ModLoader.ModLoader.steamID64 = "" static private
Definition at line 76 of file ModLoader.cs.
Referenced by Terraria.ModLoader.ModLoader.RegisterHotKey().
readonly Version Terraria.ModLoader.ModLoader.version = new Version(0, 10, 0, 3) static
The name and version number of tModLoader.
Definition at line 30 of file ModLoader.cs.
readonly string Terraria.ModLoader.ModLoader.versionedName = "tModLoader v" + version static
Definition at line 31 of file ModLoader.cs.
readonly bool Terraria.ModLoader.ModLoader.windows = false static
Definition at line 35 of file ModLoader.cs.
Referenced by Terraria.ModLoader.IO.TmodFile.GetMainAssembly(), and Terraria.ModLoader.IO.TmodFile.GetMainPDB().