Terraria ModLoader: Terraria.ModLoader.ModNet Class Reference
Terraria.ModLoader.ModNet Class Reference
Classes
class ModHeader
class NetConfig
Static Public Member Functions
static Mod GetMod (int netID)
static bool IsModdedClient (int i)
Static Public Attributes
static int NetModCount => netMods.Length
static int[] rxDataType
static int[] rxMsgType
static int[] txDataType
static int[] txMsgType
Properties
static bool AllowVanillaClients [get, set]
Static Private Member Functions
static void AddNoSyncDeps (List< Mod > syncMods)
static void CancelDownload ()
static void DownloadNextMod ()
static void OnModsDownloaded (bool needsReload)
static void ReadNetIDs (BinaryReader reader)
static void SendServerConfigs (ModPacket p, Mod mod)
static void SetupDiagnostics ()
Static Private Attributes
static FileStream downloadingFile
static long downloadingLength
static ModHeader downloadingMod
static Queue< ModHeader > downloadQueue = new Queue<ModHeader>()
static Mod[] netMods
Detailed Description
Definition at line 18 of file ModNet.cs.
Member Function Documentation
static void Terraria.ModLoader.ModNet.AddNoSyncDeps (List< Mod > syncMods) static private
Definition at line 105 of file ModNet.cs.
{
             var queue = new Queue<Mod>(syncMods.Where(m => m.Side == ModSide.Both));
             while (queue.Count > 0) {
                 foreach (var dep in AssemblyManager.GetDependencies(queue.Dequeue())) {
                     if (dep.Side == ModSide.NoSync && !syncMods.Contains(dep)) {
                         syncMods.Add(dep);
                         queue.Enqueue(dep);
                     }
                 }
             }
         }
static void Terraria.ModLoader.ModNet.CancelDownload () static private
Definition at line 315 of file ModNet.cs.
{
             try {
                 downloadingFile?.Close();
                 File.Delete(downloadingMod.path);
             }
             catch { }
             downloadingMod = null;
             Netplay.disconnect = true;
         }
static void Terraria.ModLoader.ModNet.DownloadNextMod () static private
Definition at line 227 of file ModNet.cs.
References Terraria.ModLoader.Mod.Close(), and Terraria.ModLoader.ModLoader.GetMod().
{
             downloadingMod = downloadQueue.Dequeue();
             downloadingFile = null;
             var p = new ModPacket(MessageID.ModFile);
             p.Write(downloadingMod.name);
             p.Send();
         }
static Mod Terraria.ModLoader.ModNet.GetMod (int netID) static
Referenced by Terraria.ModLoader.ItemLoader.NeedsModSaving().
static bool Terraria.ModLoader.ModNet.IsModdedClient (int i) static
static void Terraria.ModLoader.ModNet.OnModsDownloaded (bool needsReload) static private
Definition at line 325 of file ModNet.cs.
References Terraria.ModLoader.ModLoader.Mods, and Terraria.ModLoader.ModPacket.Send().
{
             if (needsReload) {
                 Main.netMode = 0;
                 ModLoader.OnSuccessfulLoad = NetReload();
                 ModLoader.Reload();
                 return;
             }
             Main.netMode = 1;
             downloadingMod = null;
             netMods = null;
             foreach (var mod in ModLoader.Mods)
                 mod.netID = -1;
             new ModPacket(MessageID.SyncMods).Send();
         }
static void Terraria.ModLoader.ModNet.ReadNetIDs (BinaryReader reader) static private
Definition at line 374 of file ModNet.cs.
References Terraria.ModLoader.Mod.HijackSendData(), and Terraria.ModLoader.ModLoader.Mods.
{
             var mods = ModLoader.Mods;
             var list = new List<Mod>();
             var n = reader.ReadInt32();
             for (short i = 0; i < n; i++) {
                 var name = reader.ReadString();
                 var mod = mods.SingleOrDefault(m => m.Name == name);
                 list.Add(mod);
                 if (mod != null) //nosync mod that doesn't exist on the client
                     mod.netID = i;
             }
             netMods = list.ToArray();
             SetupDiagnostics();
             ItemLoader.ReadNetGlobalOrder(reader);
             WorldHooks.ReadNetWorldOrder(reader);
             int serverMaxBuffs = reader.ReadInt32();
             if (serverMaxBuffs != Player.MaxBuffs) {
                 Netplay.disconnect = true;
                 Main.statusText = $"The server expects Player.MaxBuffs of {serverMaxBuffs}\nbut this client reports {Player.MaxBuffs}.\nSome mod is behaving poorly.";
             }
         }
static void Terraria.ModLoader.ModNet.SendServerConfigs (ModPacket p, Mod mod) static private
Definition at line 117 of file ModNet.cs.
References Terraria.ModLoader.ModLoader.Mods, and Terraria.ModLoader.Config.ModConfig.OnChanged().
{
             if (!ConfigManager.Configs.TryGetValue(mod, out var configs)) {
                 p.Write(0);
                 return;
             }
             var serverConfigs = configs.Where(x => x.Mode == ConfigScope.ServerSide).ToArray();
             p.Write(serverConfigs.Length);
             foreach (var config in serverConfigs) {
                 string json = JsonConvert.SerializeObject(config, ConfigManager.serializerSettingsCompact);
                 Logging.Terraria.Info($"Sending Server Config {config.mod.Name} {config.Name}: {json}");
                 p.Write(config.Name);
                 p.Write(json);
             }
         }
static void Terraria.ModLoader.ModNet.SetupDiagnostics () static private
Definition at line 460 of file ModNet.cs.
References Terraria.ModLoader.Mod.Name.
{
             rxMsgType = new int[netMods.Length];
             rxDataType = new int[netMods.Length];
             txMsgType = new int[netMods.Length];
             txDataType = new int[netMods.Length];
         }
Member Data Documentation
FileStream Terraria.ModLoader.ModNet.downloadingFile static private
Definition at line 71 of file ModNet.cs.
long Terraria.ModLoader.ModNet.downloadingLength static private
Definition at line 72 of file ModNet.cs.
ModHeader Terraria.ModLoader.ModNet.downloadingMod static private
Definition at line 70 of file ModNet.cs.
Queue<ModHeader> Terraria.ModLoader.ModNet.downloadQueue = new Queue<ModHeader>() static private
Definition at line 68 of file ModNet.cs.
int Terraria.ModLoader.ModNet.NetModCount => netMods.Length static
Definition at line 66 of file ModNet.cs.
Referenced by Terraria.ModLoader.Mod.GetPacket().
Mod [] Terraria.ModLoader.ModNet.netMods static private
Definition at line 59 of file ModNet.cs.
int [] Terraria.ModLoader.ModNet.rxDataType static
Definition at line 456 of file ModNet.cs.
int [] Terraria.ModLoader.ModNet.rxMsgType static
Definition at line 455 of file ModNet.cs.
int [] Terraria.ModLoader.ModNet.txDataType static
Definition at line 458 of file ModNet.cs.
Referenced by Terraria.ModLoader.ModPacket.Send().
int [] Terraria.ModLoader.ModNet.txMsgType static
Definition at line 457 of file ModNet.cs.
Referenced by Terraria.ModLoader.ModPacket.Send().
Property Documentation
bool Terraria.ModLoader.ModNet.AllowVanillaClients static get set
Definition at line 53 of file ModNet.cs.
Referenced by Terraria.ModLoader.ProjectileLoader.AddHook< F >(), Terraria.ModLoader.BuffLoader.BuffLoader(), Terraria.ModLoader.ItemLoader.FindVanillaWings(), Terraria.ModLoader.MountLoader.GetMount(), Terraria.ModLoader.ModPrefix.ModPrefix(), and Terraria.ModLoader.NPCLoader.NPCLoader().