Terraria ModLoader: Terraria.ModLoader.ModCompile.BuildingMod Class Reference
Terraria.ModLoader.ModCompile.BuildingMod Class Reference
Public Member Functions
BuildingMod (TmodFile modFile, BuildProperties properties, string path)
Public Attributes
string path
Detailed Description
Definition at line 37 of file ModCompile.cs.
Constructor & Destructor Documentation
Terraria.ModLoader.ModCompile.BuildingMod.BuildingMod (TmodFile modFile, BuildProperties properties, string path)
Definition at line 41 of file ModCompile.cs.
References Terraria.ModLoader.Console, Terraria.ModLoader.Environment, Terraria.ModLoader.ErrorLogger.Log(), Terraria.ModLoader.ModCompile.BuildingMod.path, Terraria.ModLoader.ModCompile.IBuildStatus.SetProgress(), Terraria.ModLoader.ModCompile.IBuildStatus.SetStatus(), Terraria.ModLoader.IO.ImageIO.ToRawBytes(), and Terraria.ModLoader.IO.TmodFile.version.
                                                                                           : base(modFile, properties)
             {
                 this.path = path;
             }
Member Data Documentation
string Terraria.ModLoader.ModCompile.BuildingMod.path
Definition at line 39 of file ModCompile.cs.
Referenced by Terraria.ModLoader.ModCompile.BuildingMod.BuildingMod().