Terraria ModLoader: Terraria.ModLoader.ItemLoader Class Reference
Terraria.ModLoader.ItemLoader Class Reference
This serves as the central class from which item-related functions are carried out. It also stores a list of mod items by ID.
Classes
class HookList
Static Public Member Functions
static bool AllowPrefix (Item item, int pre)
static bool AltFunctionUse (Item item, Player player)
Calls ModItem.AltFunctionUse, then all GlobalItem.AltFunctionUse hooks, until one of them returns true. Returns whether any of the hooks returned true.
static string AnglerChat (int type)
static void ArmorArmGlowMask (int slot, Player drawPlayer, float shadow, ref int glowMask, ref Color color)
Calls the item's body equipment texture's ArmorArmGlowMask hook, then all GlobalItem.ArmorArmGlowMask hooks.
static void ArmorSetShadows (Player player)
If the player's head texture's IsVanitySet returns true, calls the equipment texture's ArmorSetShadows. This is then repeated for the player's body, then the legs. Then for each GlobalItem, if GlobalItem.IsVanitySet returns a non-empty string, calls GlobalItem.ArmorSetShadows, using player.head, player.body, and player.legs.
static void AutoLightSelect (Item item, ref bool dryTorch, ref bool wetTorch, ref bool glowstick)
static bool CanBurnInLava (Item item)
Calls ModItem.CanBurnInLava.
static bool CanEquipAccessory (Item item, int slot)
static bool CanHitNPC (Item item, Player player, NPC target)
Gathers the results of ModItem.CanHitNPC and all GlobalItem.CanHitNPC hooks. If any of them returns false, this returns false. Otherwise, if any of them returns true then this returns true. If all of them return null, this returns null.
static bool CanHitPvp (Item item, Player player, Player target)
Calls all GlobalItem.CanHitPvp hooks, then ModItem.CanHitPvp, until one of them returns false. If all of them return true, this returns true.
static bool CanPickup (Item item, Player player)
static bool CanRightClick (Item item)
Calls ModItem.CanRightClick, then all GlobalItem.CanRightClick hooks, until one of the returns true. If one of the returns true, returns Main.mouseRight. Otherwise, returns false.
static bool CanUseItem (Item item, Player player)
Returns the "and" operation on the results of ModItem.CanUseItem and all GlobalItem.CanUseItem hooks. Does not fail fast (every hook is called).
static void CaughtFishStack (Item item)
static bool CheckProjOnSwing (Player player, Item item)
If the item is a modded item, ModItem.checkProjOnSwing is true, and the player is not at the beginning of the item's use animation, sets canShoot to false.
static int ChoosePrefix (Item item, UnifiedRandom rand)
static bool ConsumeAmmo (Item item, Item ammo, Player player)
Calls ModItem.ConsumeAmmo for the weapon, ModItem.ConsumeAmmo for the ammo, then each GlobalItem.ConsumeAmmo hook for the weapon and ammo, until one of them returns false. If all of them return true, returns true.
static bool ConsumeItem (Item item, Player player)
If ModItem.ConsumeItem or any of the GlobalItem.ConsumeItem hooks returns false, sets consume to false.
static void DrawArmorColor (EquipType type, int slot, Player drawPlayer, float shadow, ref Color color, ref int glowMask, ref Color glowMaskColor)
Calls the item's equipment texture's DrawArmorColor hook, then all GlobalItem.DrawArmorColor hooks.
static bool DrawBody (Player player)
Calls the item's body equipment texture's DrawBody hook, then all GlobalItem.DrawBody hooks, until one of them returns false. Returns true if none of them return false.
static void DrawHair (Player player, ref bool drawHair, ref bool drawAltHair)
Calls the item's head equipment texture's DrawHair hook, then all GlobalItem.DrawHair hooks.
static void DrawHands (Player player, ref bool drawHands, ref bool drawArms)
Calls the item's body equipment texture's DrawHands hook, then all GlobalItem.DrawHands hooks.
static bool DrawHead (Player player)
Calls the item's head equipment texture's DrawHead hook, then all GlobalItem.DrawHead hooks, until one of them returns false. Returns true if none of them return false.
static bool DrawLegs (Player player)
Calls the item's leg equipment texture's DrawLegs hook, then the item's shoe equipment texture's DrawLegs hook, then all GlobalItem.DrawLegs hooks, until one of them returns false. Returns true if none of them return false.
static void ExtractinatorUse (ref int resultType, ref int resultStack, int extractType)
static Color GetAlpha (Item item, Color lightColor)
Calls all GlobalItem.GetAlpha hooks then ModItem.GetAlpha, until one of them returns a color, and returns that color. Returns null if all of the hooks return null.
static void GetHealLife (Item item, Player player, bool quickHeal, ref int healValue)
Calls ModItem.GetHealLife, then all GlobalItem.GetHealLife hooks.
static void GetHealMana (Item item, Player player, bool quickHeal, ref int healValue)
Calls ModItem.GetHealMana, then all GlobalItem.GetHealMana hooks.
static ModItem GetItem (int type)
Gets the ModItem instance corresponding to the specified type. Returns null if no modded item has the given type.
static void GetWeaponCrit (Item item, Player player, ref int crit)
Calls ModItem.GetWeaponCrit, then all GlobalItem.GetWeaponCrit hooks.
static void GetWeaponDamage (Item item, Player player, ref int damage)
Calls ModItem.GetWeaponDamage, then all GlobalItem.GetWeaponDamage hooks.
static void GetWeaponKnockback (Item item, Player player, ref float knockback)
Calls ModItem.GetWeaponKnockback, then all GlobalItem.GetWeaponKnockback hooks.
static Item GetWing (Player player)
s Returns the wing item that the player is functionally using. If player.wingsLogic has been modified, so no equipped wing can be found to match what the player is using, this creates a new Item object to return.
static void GrabRange (Item item, Player player, ref int grabRange)
Calls ModItem.GrabRange, then all GlobalItem.GrabRange hooks.
static bool GrabStyle (Item item, Player player)
Calls all GlobalItem.GrabStyle hooks then ModItem.GrabStyle, until one of them returns true. Returns whether any of the hooks returned true.
static void HoldItem (Item item, Player player)
Calls ModItem.HoldItem and all GlobalItem.HoldItem hooks.
static bool HoldItemFrame (Item item, Player player)
Calls ModItem.HoldItemFrame, then all GlobalItem.HoldItemFrame hooks, until one of them returns true. Returns whether any of the hooks returned true.
static void HoldoutOffset (float gravDir, int type, ref Vector2 offset)
static void HoldoutOrigin (Player player, ref Vector2 origin)
static void HoldStyle (Item item, Player player)
If the player is not holding onto a rope and is not in the middle of using an item, calls ModItem.HoldStyle and all GlobalItem.HoldStyle hooks.
static void HorizontalWingSpeeds (Player player)
If the player is using wings, this uses the result of GetWing, and calls ModItem.HorizontalWingSpeeds then all GlobalItem.HorizontalWingSpeeds hooks.
static void IsAnglerQuestAvailable (int itemID, ref bool notAvailable)
static bool IsModBossBag (Item item)
Returns whether ModItem.bossBagNPC is greater than 0. Returns false if item is not a modded item.
static bool ItemSpace (Item item, Player player)
static void MeleeEffects (Item item, Player player, Rectangle hitbox)
Calls ModItem.MeleeEffects and all GlobalItem.MeleeEffects hooks.
static float MeleeSpeedMultiplier (Item item, Player player)
static void ModifyHitNPC (Item item, Player player, NPC target, ref int damage, ref float knockBack, ref bool crit)
Calls ModItem.ModifyHitNPC, then all GlobalItem.ModifyHitNPC hooks.
static void ModifyHitPvp (Item item, Player player, Player target, ref int damage, ref bool crit)
Calls ModItem.ModifyHitPvp, then all GlobalItem.ModifyHitPvp hooks.
static void ModifyManaCost (Item item, Player player, ref float reduce, ref float mult)
Calls ModItem.ModifyManaCost, then all GlobalItem.ModifyManaCost hooks.
static List< TooltipLine > ModifyTooltips (Item item, ref int numTooltips, string[] names, ref string[] text, ref bool[] modifier, ref bool[] badModifier, ref int oneDropLogo, out Color?[] overrideColor)
static void ModifyWeaponDamage (Item item, Player player, ref float add, ref float mult, ref float flat)
Calls ModItem.HookModifyWeaponDamage, then all GlobalItem.HookModifyWeaponDamage hooks.
static bool NeedsModSaving (Item item)
static void OnConsumeAmmo (Item item, Item ammo, Player player)
Calls ModItem.OnConsumeAmmo for the weapon, ModItem.OnConsumeAmmo for the ammo, then each GlobalItem.OnConsumeAmmo hook for the weapon and ammo.
static void OnConsumeItem (Item item, Player player)
Calls ModItem.OnConsumeItem and all GlobalItem.OnConsumeItem hooks.
static void OnConsumeMana (Item item, Player player, int manaConsumed)
Calls ModItem.OnConsumeMana, then all GlobalItem.OnConsumeMana hooks.
static void OnCraft (Item item, Recipe recipe)
static void OnHitNPC (Item item, Player player, NPC target, int damage, float knockBack, bool crit)
Calls ModItem.OnHitNPC and all GlobalItem.OnHitNPC hooks.
static void OnHitPvp (Item item, Player player, Player target, int damage, bool crit)
Calls ModItem.OnHitPvp and all GlobalItem.OnHitPvp hooks.
static void OnMissingMana (Item item, Player player, int neededMana)
Calls ModItem.OnMissingMana, then all GlobalItem.OnMissingMana hooks.
static bool OnPickup (Item item, Player player)
Calls all GlobalItem.OnPickup hooks then ModItem.OnPickup, until one of the returns false. Returns true if all of the hooks return true.
static void OpenBossBag (int type, Player player, ref int npc)
If the item is a modded item and ModItem.bossBagNPC is greater than 0, calls ModItem.OpenBossBag and sets npc to ModItem.bossBagNPC.
static void OpenVanillaBag (string context, Player player, int arg)
Calls all GlobalItem.OpenVanillaBag hooks.
static void PickAmmo (Item weapon, Item ammo, Player player, ref int type, ref float speed, ref int damage, ref float knockback)
Calls ModItem.PickAmmo, then all GlobalItem.PickAmmo hooks.
static void PostDrawInInventory (Item item, SpriteBatch spriteBatch, Vector2 position, Rectangle frame, Color drawColor, Color itemColor, Vector2 origin, float scale)
Calls ModItem.PostDrawInInventory, then all GlobalItem.PostDrawInInventory hooks.
static void PostDrawInWorld (Item item, SpriteBatch spriteBatch, Color lightColor, Color alphaColor, float rotation, float scale, int whoAmI)
Calls ModItem.PostDrawInWorld, then all GlobalItem.PostDrawInWorld hooks.
static void PostDrawTooltip (Item item, ReadOnlyCollection< DrawableTooltipLine > lines)
static void PostDrawTooltipLine (Item item, DrawableTooltipLine line)
static void PostReforge (Item item)
Calls ModItem.PostReforge, then all GlobalItem.PostReforge hooks.
static void PostUpdate (Item item)
Calls ModItem.PostUpdate and all GlobalItem.PostUpdate hooks.
static bool PreDrawInInventory (Item item, SpriteBatch spriteBatch, Vector2 position, Rectangle frame, Color drawColor, Color itemColor, Vector2 origin, float scale)
Returns the "and" operator on the results of all GlobalItem.PreDrawInInventory hooks and ModItem.PreDrawInInventory.
static bool PreDrawInWorld (Item item, SpriteBatch spriteBatch, Color lightColor, Color alphaColor, ref float rotation, ref float scale, int whoAmI)
Returns the "and" operator on the results of ModItem.PreDrawInWorld and all GlobalItem.PreDrawInWorld hooks.
static bool PreDrawTooltip (Item item, ReadOnlyCollection< TooltipLine > lines, ref int x, ref int y)
static bool PreDrawTooltipLine (Item item, DrawableTooltipLine line, ref int yOffset)
static bool PrefixChance (Item item, int pre, UnifiedRandom rand)
Allows for blocking, forcing and altering chance of prefix rolling. False (block) takes precedence over True (force). Null gives vanilla behaviour
static bool PreOpenVanillaBag (string context, Player player, int arg)
Calls each GlobalItem.PreOpenVanillaBag hook until one of them returns false. Returns true if all of them returned true.
static bool PreReforge (Item item)
Calls ModItem.PreReforge, then all GlobalItem.PreReforge hooks.
static void PreUpdateVanitySet (Player player)
If the player's head texture's IsVanitySet returns true, calls the equipment texture's PreUpdateVanitySet. This is then repeated for the player's body, then the legs. Then for each GlobalItem, if GlobalItem.IsVanitySet returns a non-empty string, calls GlobalItem.PreUpdateVanitySet, using player.head, player.body, and player.legs.
static bool ReforgePrice (Item item, ref int reforgePrice, ref bool canApplyDiscount)
Call all ModItem.ReforgePrice, then GlobalItem.ReforgePrice hooks.
static void RightClick (Item item, Player player)
If Main.mouseRightRelease is true, the following steps are taken:
static void SetMatch (int armorSlot, int type, bool male, ref int equipSlot, ref bool robes)
Calls EquipTexture.SetMatch, then all GlobalItem.SetMatch hooks.
static bool Shoot (Item item, Player player, ref Vector2 position, ref float speedX, ref float speedY, ref int type, ref int damage, ref float knockBack)
Calls each GlobalItem.Shoot hook, then ModItem.Shoot, until one of them returns false. If all of them return true, returns true.
static void Update (Item item, ref float gravity, ref float maxFallSpeed)
Calls ModItem.Update, then all GlobalItem.Update hooks.
static void UpdateAccessory (Item item, Player player, bool hideVisual)
Calls ModItem.UpdateAccessory and all GlobalItem.UpdateAccessory hooks.
static void UpdateArmorSet (Player player, Item head, Item body, Item legs)
If the head's ModItem.IsArmorSet returns true, calls the head's ModItem.UpdateArmorSet. This is then repeated for the body, then the legs. Then for each GlobalItem, if GlobalItem.IsArmorSet returns a non-empty string, calls GlobalItem.UpdateArmorSet with that string.
static void UpdateEquip (Item item, Player player)
Calls ModItem.UpdateEquip and all GlobalItem.UpdateEquip hooks.
static void UpdateInventory (Item item, Player player)
Calls ModItem.UpdateInventory and all GlobalItem.UpdateInventory hooks.
static void UpdateVanity (Player player)
Calls each of the item's equipment texture's UpdateVanity hook.
static void UpdateVanitySet (Player player)
If the player's head texture's IsVanitySet returns true, calls the equipment texture's UpdateVanitySet. This is then repeated for the player's body, then the legs. Then for each GlobalItem, if GlobalItem.IsVanitySet returns a non-empty string, calls GlobalItem.UpdateVanitySet, using player.head, player.body, and player.legs.
static bool UseItem (Item item, Player player)
Returns true if any of ModItem.UseItem or GlobalItem.UseItem return true Does not fail fast (calls every hook)
static bool UseItemFrame (Item item, Player player)
Calls ModItem.UseItemFrame, then all GlobalItem.UseItemFrame hooks, until one of them returns true. Returns whether any of the hooks returned true.
static void UseItemHitbox (Item item, Player player, ref Rectangle hitbox, ref bool noHitbox)
Calls ModItem.UseItemHitbox, then all GlobalItem.UseItemHitbox hooks.
static void UseStyle (Item item, Player player)
Calls ModItem.UseStyle and all GlobalItem.UseStyle hooks.
static float UseTimeMultiplier (Item item, Player player)
static void VerticalWingSpeeds (Player player, ref float ascentWhenFalling, ref float ascentWhenRising, ref float maxCanAscendMultiplier, ref float maxAscentMultiplier, ref float constantAscend)
If the player is using wings, this uses the result of GetWing, and calls ModItem.VerticalWingSpeeds then all GlobalItem.VerticalWingSpeeds hooks.
static bool WingUpdate (Player player, bool inUse)
If wings can be seen on the player, calls the player's wing's equipment texture's WingUpdate and all GlobalItem.WingUpdate hooks.
Static Public Attributes
static int ItemCount => nextItem
Private Member Functions
delegate void DelegateAnglerChat (int type, ref string chat, ref string catchLocation)
delegate void DelegateArmorArmGlowMask (int slot, Player drawPlayer, float shadow, ref int glowMask, ref Color color)
delegate void DelegateCaughtFishStack (int type, ref int stack)
delegate void DelegateDrawArmorColor (EquipType type, int slot, Player drawPlayer, float shadow, ref Color color, ref int glowMask, ref Color glowMaskColor)
delegate void DelegateDrawHair (int body, ref bool drawHair, ref bool drawAltHair)
delegate void DelegateDrawHands (int body, ref bool drawHands, ref bool drawArms)
delegate void DelegateExtractinatorUse (int extractType, ref int resultType, ref int resultStack)
delegate void DelegateGetHealLife (Item item, Player player, bool quickHeal, ref int healValue)
delegate void DelegateGetHealMana (Item item, Player player, bool quickHeal, ref int healValue)
delegate void DelegateGetWeaponCrit (Item item, Player player, ref int crit)
delegate void DelegateGetWeaponDamage (Item item, Player player, ref int damage)
delegate void DelegateGetWeaponKnockback (Item item, Player player, ref float knockback)
delegate void DelegateGrabRange (Item item, Player player, ref int grabRange)
delegate void DelegateHorizontalWingSpeeds (Item item, Player player, ref float speed, ref float acceleration)
delegate void DelegateModifyHitNPC (Item item, Player player, NPC target, ref int damage, ref float knockBack, ref bool crit)
delegate void DelegateModifyHitPvp (Item item, Player player, Player target, ref int damage, ref bool crit)
delegate void DelegateModifyManaCost (Item item, Player player, ref float reduce, ref float mult)
delegate void DelegateModifyWeaponDamage (Item item, Player player, ref float add, ref float mult, ref float flat)
delegate void DelegateModifyWeaponDamageOld (Item item, Player player, ref float add, ref float mult)
delegate void DelegateOldPickAmmo (Item item, Player player, ref int type, ref float speed, ref int damage, ref float knockback)
delegate void DelegatePickAmmo (Item weapon, Item ammo, Player player, ref int type, ref float speed, ref int damage, ref float knockback)
delegate void DelegatePostDrawTooltip (Item item, ReadOnlyCollection< DrawableTooltipLine > lines)
delegate void DelegatePostDrawTooltipLine (Item item, DrawableTooltipLine line)
delegate bool DelegatePreDrawInWorld (Item item, SpriteBatch spriteBatch, Color lightColor, Color alphaColor, ref float rotation, ref float scale, int whoAmI)
delegate bool DelegatePreDrawTooltip (Item item, ReadOnlyCollection< TooltipLine > lines, ref int x, ref int y)
delegate bool DelegatePreDrawTooltipLine (Item item, DrawableTooltipLine line, ref int yOffset)
delegate bool DelegateReforgePrice (Item item, ref int reforgePrice, ref bool canApplyDiscount)
delegate void DelegateSetMatch (int armorSlot, int type, bool male, ref int equipSlot, ref bool robes)
delegate bool DelegateShoot (Item item, Player player, ref Vector2 position, ref float speedX, ref float speedY, ref int type, ref int damage, ref float knockBack)
delegate void DelegateUpdate (Item item, ref float gravity, ref float maxFallSpeed)
delegate void DelegateUseItemHitbox (Item item, Player player, ref Rectangle hitbox, ref bool noHitbox)
delegate void DelegateVerticalWingSpeeds (Item item, Player player, ref float ascentWhenFalling, ref float ascentWhenRising, ref float maxCanAscendMultiplier, ref float maxAscentMultiplier, ref float constantAscend)
Static Private Member Functions
static HookList AddHook< F > (Expression< Func< GlobalItem, F >> func)
static Rectangle AnimatedItemFrame (Item item)
static void FindVanillaWings ()
static bool GeneralPrefix (Item item)
static bool HasMethod (Type t, string method, params Type[] args)
Static Private Attributes
static HookList HookAllowPrefix = AddHook<Func<Item, int, bool>>(g => g.AllowPrefix)
static HookList HookAltFunctionUse = AddHook<Func<Item, Player, bool>>(g => g.AltFunctionUse)
static HookList HookAnglerChat = AddHook<DelegateAnglerChat>(g => g.AnglerChat)
static HookList HookArmorArmGlowMask = AddHook<DelegateArmorArmGlowMask>(g => g.ArmorArmGlowMask)
static HookList HookArmorSetShadows = AddHook<Action<Player, string>>(g => g.ArmorSetShadows)
static HookList HookCanBurnInLava = AddHook<Func<Item, bool>>(g => g.CanBurnInLava)
static HookList HookCanEquipAccessory = AddHook<Func<Item, Player, int, bool>>(g => g.CanEquipAccessory)
static HookList HookCanHitNPC = AddHook<Func<Item, Player, NPC, bool?>>(g => g.CanHitNPC)
static HookList HookCanHitPvp = AddHook<Func<Item, Player, Player, bool>>(g => g.CanHitPvp)
static HookList HookCanPickup = AddHook<Func<Item, Player, bool>>(g => g.CanPickup)
static HookList HookCanRightClick = AddHook<Func<Item, bool>>(g => g.CanRightClick)
static HookList HookCanUseItem = AddHook<Func<Item, Player, bool>>(g => g.CanUseItem)
static HookList HookCaughtFishStack = AddHook<DelegateCaughtFishStack>(g => g.CaughtFishStack)
static HookList HookChoosePrefix = AddHook<Func<Item, UnifiedRandom, int>>(g => g.ChoosePrefix)
static HookList HookConsumeAmmo = AddHook<Func<Item, Player, bool>>(g => g.ConsumeAmmo)
static HookList HookConsumeItem = AddHook<Func<Item, Player, bool>>(g => g.ConsumeItem)
static HookList HookDrawArmorColor = AddHook<DelegateDrawArmorColor>(g => g.DrawArmorColor)
static HookList HookDrawBody = AddHook<Func<int, bool>>(g => g.DrawBody)
static HookList HookDrawHair = AddHook<DelegateDrawHair>(g => g.DrawHair)
static HookList HookDrawHands = AddHook<DelegateDrawHands>(g => g.DrawHands)
static HookList HookDrawHead = AddHook<Func<int, bool>>(g => g.DrawHead)
static HookList HookDrawLegs = AddHook<Func<int, int, bool>>(g => g.DrawLegs)
static HookList HookExtractinatorUse = AddHook<DelegateExtractinatorUse>(g => g.ExtractinatorUse)
static HookList HookGetAlpha = AddHook<Func<Item, Color, Color?>>(g => g.GetAlpha)
static HookList HookGetHealLife = AddHook<DelegateGetHealLife>(g => g.GetHealLife)
static HookList HookGetHealMana = AddHook<DelegateGetHealMana>(g => g.GetHealMana)
static HookList HookGetWeaponCrit = AddHook<DelegateGetWeaponCrit>(g => g.GetWeaponCrit)
static HookList HookGetWeaponDamage = AddHook<DelegateGetWeaponDamage>(g => g.GetWeaponDamage)
static HookList HookGetWeaponKnockback = AddHook<DelegateGetWeaponKnockback>(g => g.GetWeaponKnockback)
static HookList HookGrabRange = AddHook<DelegateGrabRange>(g => g.GrabRange)
static HookList HookGrabStyle = AddHook<Func<Item, Player, bool>>(g => g.GrabStyle)
static HookList HookHoldItem = AddHook<Action<Item, Player>>(g => g.HoldItem)
static HookList HookHoldItemFrame = AddHook<Func<Item, Player, bool>>(g => g.HoldItemFrame)
static HookList HookHoldoutOffset = AddHook<Func<int, Vector2?>>(g => g.HoldoutOffset)
static HookList HookHoldoutOrigin = AddHook<Func<int, Vector2?>>(g => g.HoldoutOrigin)
static HookList HookHoldStyle = AddHook<Action<Item, Player>>(g => g.HoldStyle)
static HookList HookHorizontalWingSpeeds = AddHook<DelegateHorizontalWingSpeeds>(g => g.HorizontalWingSpeeds)
static HookList HookIsAnglerQuestAvailable = AddHook<Func<int, bool>>(g => g.IsAnglerQuestAvailable)
static HookList HookItemSpace = AddHook<Func<Item, Player, bool>>(g => g.ItemSpace)
static HookList HookMeleeEffects = AddHook<Action<Item, Player, Rectangle>>(g => g.MeleeEffects)
static HookList HookMeleeSpeedMultiplier = AddHook<Func<Item, Player, float>>(g => g.MeleeSpeedMultiplier)
static HookList HookModifyHitNPC = AddHook<DelegateModifyHitNPC>(g => g.ModifyHitNPC)
static HookList HookModifyHitPvp = AddHook<DelegateModifyHitPvp>(g => g.ModifyHitPvp)
static HookList HookModifyManaCost = AddHook<DelegateModifyManaCost>(g => g.ModifyManaCost)
static HookList HookModifyTooltips = AddHook<Action<Item, List<TooltipLine>>>(g => g.ModifyTooltips)
static HookList HookModifyWeaponDamage = AddHook<DelegateModifyWeaponDamage>(g => g.ModifyWeaponDamage)
static HookList HookModifyWeaponDamageOld = AddHook<DelegateModifyWeaponDamage>(g => g.ModifyWeaponDamage)
static HookList HookNeedsSaving = AddHook<Func<Item, bool>>(g => g.NeedsSaving)
static HookList HookOldPickAmmo = AddHook<DelegateOldPickAmmo>(g => g.PickAmmo)
static HookList HookOnConsumeAmmo = AddHook<Action<Item, Player>>(g => g.OnConsumeAmmo)
static HookList HookOnConsumeItem = AddHook<Action<Item, Player>>(g => g.OnConsumeItem)
static HookList HookOnConsumeMana = AddHook<Action<Item, Player, int>>(g => g.OnConsumeMana)
static HookList HookOnCraft = AddHook<Action<Item, Recipe>>(g => g.OnCraft)
static HookList HookOnHitNPC = AddHook<Action<Item, Player, NPC, int, float, bool>>(g => g.OnHitNPC)
static HookList HookOnHitPvp = AddHook<Action<Item, Player, Player, int, bool>>(g => g.OnHitPvp)
static HookList HookOnMissingMana = AddHook<Action<Item, Player, int>>(g => g.OnMissingMana)
static HookList HookOnPickup = AddHook<Func<Item, Player, bool>>(g => g.OnPickup)
static HookList HookOpenVanillaBag = AddHook<Action<string, Player, int>>(g => g.OpenVanillaBag)
static HookList HookPickAmmo = AddHook<DelegatePickAmmo>(g => g.PickAmmo)
static HookList HookPostDrawInInventory = AddHook<Action<Item, SpriteBatch, Vector2, Rectangle, Color, Color, Vector2, float>>(g => g.PostDrawInInventory)
static HookList HookPostDrawInWorld = AddHook<Action<Item, SpriteBatch, Color, Color, float, float, int>>(g => g.PostDrawInWorld)
static HookList HookPostDrawTooltip = AddHook<DelegatePostDrawTooltip>(g => g.PostDrawTooltip)
static HookList HookPostDrawTooltipLine = AddHook<DelegatePostDrawTooltipLine>(g => g.PostDrawTooltipLine)
static HookList HookPostReforge = AddHook<Action<Item>>(g => g.PostReforge)
static HookList HookPostUpdate = AddHook<Action<Item>>(g => g.PostUpdate)
static HookList HookPreDrawInInventory = AddHook<Func<Item, SpriteBatch, Vector2, Rectangle, Color, Color, Vector2, float, bool>>(g => g.PreDrawInInventory)
static HookList HookPreDrawInWorld = AddHook<DelegatePreDrawInWorld>(g => g.PreDrawInWorld)
static HookList HookPreDrawTooltip = AddHook<DelegatePreDrawTooltip>(g => g.PreDrawTooltip)
static HookList HookPreDrawTooltipLine = AddHook<DelegatePreDrawTooltipLine>(g => g.PreDrawTooltipLine)
static HookList HookPrefixChance = AddHook<Func<Item, int, UnifiedRandom, bool?>>(g => g.PrefixChance)
static HookList HookPreOpenVanillaBag = AddHook<Func<string, Player, int, bool>>(g => g.PreOpenVanillaBag)
static HookList HookPreReforge = AddHook<Func<Item, bool>>(g => g.NewPreReforge)
static HookList HookPreUpdateVanitySet = AddHook<Action<Player, string>>(g => g.PreUpdateVanitySet)
static HookList HookReforgePrice = AddHook<DelegateReforgePrice>(g => g.ReforgePrice)
static HookList HookRightClick = AddHook<Action<Item, Player>>(g => g.RightClick)
static List< HookList > hooks = new List<HookList>()
static HookList HookSetDefaults = AddHook<Action<Item>>(g => g.SetDefaults)
static HookList HookSetMatch = AddHook<DelegateSetMatch>(g => g.SetMatch)
static HookList HookShoot = AddHook<DelegateShoot>(g => g.Shoot)
static HookList HookUpdate = AddHook<DelegateUpdate>(g => g.Update)
static HookList HookUpdateAccessory = AddHook<Action<Item, Player, bool>>(g => g.UpdateAccessory)
static HookList HookUpdateArmorSet = AddHook<Action<Player, string>>(g => g.UpdateArmorSet)
static HookList HookUpdateEquip = AddHook<Action<Item, Player>>(g => g.UpdateEquip)
static HookList HookUpdateInventory = AddHook<Action<Item, Player>>(g => g.UpdateInventory)
static HookList HookUpdateVanitySet = AddHook<Action<Player, string>>(g => g.UpdateVanitySet)
static HookList HookUseItem = AddHook<Func<Item, Player, bool>>(g => g.UseItem)
static HookList HookUseItemFrame = AddHook<Func<Item, Player, bool>>(g => g.UseItemFrame)
static HookList HookUseItemHitbox = AddHook<DelegateUseItemHitbox>(g => g.UseItemHitbox)
static HookList HookUseStyle = AddHook<Action<Item, Player>>(g => g.UseStyle)
static HookList HookUseTimeMultiplier = AddHook<Func<Item, Player, float>>(g => g.UseTimeMultiplier)
static HookList HookVerticalWingSpeeds = AddHook<DelegateVerticalWingSpeeds>(g => g.VerticalWingSpeeds)
static HookList HookWingUpdate = AddHook<Func<int, Player, bool, bool>>(g => g.WingUpdate)
static int nextItem = ItemID.Count
Detailed Description
This serves as the central class from which item-related functions are carried out. It also stores a list of mod items by ID.
Definition at line 21 of file ItemLoader.cs.
Member Function Documentation
static HookList Terraria.ModLoader.ItemLoader.AddHook< F > (Expression< Func< GlobalItem, F >> func) static private
Definition at line 46 of file ItemLoader.cs.
{
             var hook = new HookList(ModLoader.Method(func));
             hooks.Add(hook);
             return hook;
         }
static bool Terraria.ModLoader.ItemLoader.AllowPrefix (Item item, int pre) static
Definition at line 289 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr.
{
             bool result = true;
             foreach (var g in HookAllowPrefix.arr) {
                 result &= g.Instance(item).AllowPrefix(item, pre);
             }
             if (item.modItem != null) {
                 result &= item.modItem.AllowPrefix(pre);
             }
             return result;
         }
static bool Terraria.ModLoader.ItemLoader.AltFunctionUse (Item item, Player player) static
Calls ModItem.AltFunctionUse, then all GlobalItem.AltFunctionUse hooks, until one of them returns true. Returns whether any of the hooks returned true.
Definition at line 848 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr.
{
             if (item.IsAir)
                 return false;
             if (item.modItem != null && item.modItem.AltFunctionUse(player))
                 return true;
             foreach (var g in HookAltFunctionUse.arr)
                 if (g.Instance(item).AltFunctionUse(item, player))
                     return true;
             return false;
         }
static string Terraria.ModLoader.ItemLoader.AnglerChat (int type) static
Definition at line 1660 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr.
{
             string chat = "";
             string catchLocation = "";
             GetItem(type)?.AnglerQuestChat(ref chat, ref catchLocation);
             foreach (var g in HookAnglerChat.arr)
                 g.AnglerChat(type, ref chat, ref catchLocation);
             if (string.IsNullOrEmpty(chat) || string.IsNullOrEmpty(catchLocation))
                 return null;
             return chat + "\n\n(" + catchLocation + ")";
         }
static Rectangle Terraria.ModLoader.ItemLoader.AnimatedItemFrame (Item item) static private
Definition at line 242 of file ItemLoader.cs.
{
             int frameCount = Main.itemAnimations[item.type].FrameCount;
             int frameDuration = Main.itemAnimations[item.type].TicksPerFrame;
             return Main.itemAnimations[item.type].GetFrame(Main.itemTexture[item.type]);
         }
static void Terraria.ModLoader.ItemLoader.ArmorArmGlowMask (int slot, Player drawPlayer, float shadow, ref int glowMask, ref Color color) static
Calls the item's body equipment texture's ArmorArmGlowMask hook, then all GlobalItem.ArmorArmGlowMask hooks.
Definition at line 1276 of file ItemLoader.cs.
References Terraria.ModLoader.EquipTexture.ArmorArmGlowMask(), Terraria.ModLoader.ItemLoader.HookList.arr, and Terraria.ModLoader.EquipLoader.GetEquipTexture().
{
             EquipTexture texture = EquipLoader.GetEquipTexture(EquipType.Body, slot);
             texture?.ArmorArmGlowMask(drawPlayer, shadow, ref glowMask, ref color);
             foreach (var g in HookArmorArmGlowMask.arr)
                 g.ArmorArmGlowMask(slot, drawPlayer, shadow, ref glowMask, ref color);
         }
static void Terraria.ModLoader.ItemLoader.ArmorSetShadows (Player player) static
If the player's head texture's IsVanitySet returns true, calls the equipment texture's ArmorSetShadows. This is then repeated for the player's body, then the legs. Then for each GlobalItem, if GlobalItem.IsVanitySet returns a non-empty string, calls GlobalItem.ArmorSetShadows, using player.head, player.body, and player.legs.
Definition at line 999 of file ItemLoader.cs.
References Terraria.ModLoader.EquipTexture.ArmorSetShadows(), Terraria.ModLoader.GlobalItem.ArmorSetShadows(), Terraria.ModLoader.ItemLoader.HookList.arr, Terraria.ModLoader.EquipLoader.GetEquipTexture(), Terraria.ModLoader.EquipTexture.IsVanitySet(), and Terraria.ModLoader.GlobalItem.IsVanitySet().
{
             EquipTexture headTexture = EquipLoader.GetEquipTexture(EquipType.Head, player.head);
             EquipTexture bodyTexture = EquipLoader.GetEquipTexture(EquipType.Body, player.body);
             EquipTexture legTexture = EquipLoader.GetEquipTexture(EquipType.Legs, player.legs);
             if (headTexture != null && headTexture.IsVanitySet(player.head, player.body, player.legs))
                 headTexture.ArmorSetShadows(player);
             if (bodyTexture != null && bodyTexture.IsVanitySet(player.head, player.body, player.legs))
                 bodyTexture.ArmorSetShadows(player);
             if (legTexture != null && legTexture.IsVanitySet(player.head, player.body, player.legs))
                 legTexture.ArmorSetShadows(player);
             foreach (GlobalItem globalItem in HookArmorSetShadows.arr) {
                 string set = globalItem.IsVanitySet(player.head, player.body, player.legs);
                 if (!string.IsNullOrEmpty(set))
                     globalItem.ArmorSetShadows(player, set);
             }
         }
static void Terraria.ModLoader.ItemLoader.AutoLightSelect (Item item, ref bool dryTorch, ref bool wetTorch, ref bool glowstick) static
Definition at line 1626 of file ItemLoader.cs.
{
             if (item.modItem != null) {
                 item.modItem.AutoLightSelect(ref dryTorch, ref wetTorch, ref glowstick);
                 if (wetTorch) {
                     dryTorch = false;
                     glowstick = false;
                 }
                 if (dryTorch) {
                     glowstick = false;
                 }
             }
         }
static bool Terraria.ModLoader.ItemLoader.CanBurnInLava (Item item) static
Calls ModItem.CanBurnInLava.
Definition at line 1392 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr.
         {
             foreach (var g in HookCanBurnInLava.arr)
                 if (g.Instance(item).CanBurnInLava(item))
                     return true;
             return item.modItem?.CanBurnInLava() ?? false;
         }
static bool Terraria.ModLoader.ItemLoader.CanEquipAccessory (Item item, int slot) static
Definition at line 1605 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr.
{
             Player player = Main.player[Main.myPlayer];
             if (item.modItem != null && !item.modItem.CanEquipAccessory(player, slot))
                 return false;
             foreach (var g in HookCanEquipAccessory.arr)
                 if (!g.Instance(item).CanEquipAccessory(item, player, slot))
                     return false;
             return true;
         }
static bool Terraria.ModLoader.ItemLoader.CanHitNPC (Item item, Player player, NPC target) static
Gathers the results of ModItem.CanHitNPC and all GlobalItem.CanHitNPC hooks. If any of them returns false, this returns false. Otherwise, if any of them returns true then this returns true. If all of them return null, this returns null.
Definition at line 668 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr, and Terraria.ModLoader.Item.
{
             bool? canHit = item.modItem?.CanHitNPC(player, target);
             if (canHit.HasValue && !canHit.Value) {
                 return false;
             }
             foreach (var g in HookCanHitNPC.arr) {
                 bool? globalCanHit = g.Instance(item).CanHitNPC(item, player, target);
                 if (globalCanHit.HasValue) {
                     if (globalCanHit.Value) {
                         canHit = true;
                     }
                     else {
                         return false;
                     }
                 }
             }
             return canHit;
         }
static bool Terraria.ModLoader.ItemLoader.CanHitPvp (Item item, Player player, Player target) static
Calls all GlobalItem.CanHitPvp hooks, then ModItem.CanHitPvp, until one of them returns false. If all of them return true, this returns true.
Definition at line 720 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr, and Terraria.ModLoader.Item.
{
             foreach (var g in HookCanHitPvp.arr)
                 if (!g.Instance(item).CanHitPvp(item, player, target))
                     return false;
             return item.modItem == null || item.modItem.CanHitPvp(player, target);
         }
static bool Terraria.ModLoader.ItemLoader.CanPickup (Item item, Player player) static
Definition at line 1443 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr.
{
             foreach (var g in HookCanPickup.arr)
                 if (!g.Instance(item).CanPickup(item, player))
                     return false;
             return item.modItem?.CanPickup(player) ?? true;
         }
static bool Terraria.ModLoader.ItemLoader.CanRightClick (Item item) static
Calls ModItem.CanRightClick, then all GlobalItem.CanRightClick hooks, until one of the returns true. If one of the returns true, returns Main.mouseRight. Otherwise, returns false.
Definition at line 1038 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr.
{
             if (item.IsAir || !Main.mouseRight)
                 return false;
             if (item.modItem != null && item.modItem.CanRightClick())
                 return true;
             foreach (var g in HookCanRightClick.arr)
                 if (g.Instance(item).CanRightClick(item))
                     return true;
             return false;
         }
static bool Terraria.ModLoader.ItemLoader.CanUseItem (Item item, Player player) static
Returns the "and" operation on the results of ModItem.CanUseItem and all GlobalItem.CanUseItem hooks. Does not fail fast (every hook is called).
Parameters
item The item.
player The player holding the item.
Definition at line 310 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr.
{
             bool flag = true;
             if (item.modItem != null)
                 flag &= item.modItem.CanUseItem(player);
             foreach (var g in HookCanUseItem.arr)
                 flag &= g.Instance(item).CanUseItem(item, player);
             return flag;
         }
static void Terraria.ModLoader.ItemLoader.CaughtFishStack (Item item) static
Definition at line 1641 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr.
{
             item.modItem?.CaughtFishStack(ref item.stack);
             foreach (var g in HookCaughtFishStack.arr)
                 g.Instance(item).CaughtFishStack(item.type, ref item.stack);
         }
static bool Terraria.ModLoader.ItemLoader.CheckProjOnSwing (Player player, Item item) static
If the item is a modded item, ModItem.checkProjOnSwing is true, and the player is not at the beginning of the item's use animation, sets canShoot to false.
Definition at line 539 of file ItemLoader.cs.
References Terraria.ModLoader.Item.
{
             return item.modItem == null || !item.modItem.OnlyShootOnSwing || player.itemAnimation == player.itemAnimationMax - 1;
         }
static int Terraria.ModLoader.ItemLoader.ChoosePrefix (Item item, UnifiedRandom rand) static
Definition at line 250 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr.
{
             foreach (var g in HookChoosePrefix.arr) {
                 int pre = g.Instance(item).ChoosePrefix(item, rand);
                 if (pre > 0) {
                     return pre;
                 }
             }
             if (item.modItem != null) {
                 int pre = item.modItem.ChoosePrefix(rand);
                 if (pre > 0) {
                     return pre;
                 }
             }
             return -1;
         }
static bool Terraria.ModLoader.ItemLoader.ConsumeAmmo (Item item, Item ammo, Player player) static
Calls ModItem.ConsumeAmmo for the weapon, ModItem.ConsumeAmmo for the ammo, then each GlobalItem.ConsumeAmmo hook for the weapon and ammo, until one of them returns false. If all of them return true, returns true.
Definition at line 569 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr.
{
             if (item.modItem != null && !item.modItem.ConsumeAmmo(player) ||
                     ammo.modItem != null && !ammo.modItem.ConsumeAmmo(player))
                 return false;
             foreach (var g in HookConsumeAmmo.arr) {
                 if (!g.Instance(item).ConsumeAmmo(item, player) ||
                     !g.Instance(ammo).ConsumeAmmo(ammo, player))
                     return false;
             }
             return true;
         }
static bool Terraria.ModLoader.ItemLoader.ConsumeItem (Item item, Player player) static
If ModItem.ConsumeItem or any of the GlobalItem.ConsumeItem hooks returns false, sets consume to false.
Definition at line 780 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr.
{
             if (item.IsAir) return true;
             if (item.modItem != null && !item.modItem.ConsumeItem(player))
                 return false;
             foreach (var g in HookConsumeItem.arr)
                 if (!g.Instance(item).ConsumeItem(item, player))
                     return false;
             OnConsumeItem(item, player);
             return true;
         }
delegate void Terraria.ModLoader.ItemLoader.DelegateAnglerChat (int type, ref string chat, ref string catchLocation) private
delegate void Terraria.ModLoader.ItemLoader.DelegateArmorArmGlowMask (int slot, Player drawPlayer, float shadow, ref int glowMask, ref Color color) private
delegate void Terraria.ModLoader.ItemLoader.DelegateCaughtFishStack (int type, ref int stack) private
delegate void Terraria.ModLoader.ItemLoader.DelegateDrawArmorColor (EquipType type, int slot, Player drawPlayer, float shadow, ref Color color, ref int glowMask, ref Color glowMaskColor) private
delegate void Terraria.ModLoader.ItemLoader.DelegateDrawHair (int body, ref bool drawHair, ref bool drawAltHair) private
delegate void Terraria.ModLoader.ItemLoader.DelegateDrawHands (int body, ref bool drawHands, ref bool drawArms) private
delegate void Terraria.ModLoader.ItemLoader.DelegateExtractinatorUse (int extractType, ref int resultType, ref int resultStack) private
delegate void Terraria.ModLoader.ItemLoader.DelegateGetHealLife (Item item, Player player, bool quickHeal, ref int healValue) private
delegate void Terraria.ModLoader.ItemLoader.DelegateGetHealMana (Item item, Player player, bool quickHeal, ref int healValue) private
delegate void Terraria.ModLoader.ItemLoader.DelegateGetWeaponCrit (Item item, Player player, ref int crit) private
delegate void Terraria.ModLoader.ItemLoader.DelegateGetWeaponDamage (Item item, Player player, ref int damage) private
delegate void Terraria.ModLoader.ItemLoader.DelegateGetWeaponKnockback (Item item, Player player, ref float knockback) private
delegate void Terraria.ModLoader.ItemLoader.DelegateGrabRange (Item item, Player player, ref int grabRange) private
delegate void Terraria.ModLoader.ItemLoader.DelegateHorizontalWingSpeeds (Item item, Player player, ref float speed, ref float acceleration) private
delegate void Terraria.ModLoader.ItemLoader.DelegateModifyHitNPC (Item item, Player player, NPC target, ref int damage, ref float knockBack, ref bool crit) private
delegate void Terraria.ModLoader.ItemLoader.DelegateModifyHitPvp (Item item, Player player, Player target, ref int damage, ref bool crit) private
delegate void Terraria.ModLoader.ItemLoader.DelegateModifyManaCost (Item item, Player player, ref float reduce, ref float mult) private
delegate void Terraria.ModLoader.ItemLoader.DelegateModifyWeaponDamage (Item item, Player player, ref float add, ref float mult, ref float flat) private
delegate void Terraria.ModLoader.ItemLoader.DelegateModifyWeaponDamageOld (Item item, Player player, ref float add, ref float mult) private
delegate void Terraria.ModLoader.ItemLoader.DelegateOldPickAmmo (Item item, Player player, ref int type, ref float speed, ref int damage, ref float knockback) private
delegate void Terraria.ModLoader.ItemLoader.DelegatePickAmmo (Item weapon, Item ammo, Player player, ref int type, ref float speed, ref int damage, ref float knockback) private
delegate void Terraria.ModLoader.ItemLoader.DelegatePostDrawTooltip (Item item, ReadOnlyCollection< DrawableTooltipLine > lines) private
delegate void Terraria.ModLoader.ItemLoader.DelegatePostDrawTooltipLine (Item item, DrawableTooltipLine line) private
delegate bool Terraria.ModLoader.ItemLoader.DelegatePreDrawInWorld (Item item, SpriteBatch spriteBatch, Color lightColor, Color alphaColor, ref float rotation, ref float scale, int whoAmI) private
delegate bool Terraria.ModLoader.ItemLoader.DelegatePreDrawTooltip (Item item, ReadOnlyCollection< TooltipLine > lines, ref int x, ref int y) private
delegate bool Terraria.ModLoader.ItemLoader.DelegatePreDrawTooltipLine (Item item, DrawableTooltipLine line, ref int yOffset) private
delegate bool Terraria.ModLoader.ItemLoader.DelegateReforgePrice (Item item, ref int reforgePrice, ref bool canApplyDiscount) private
delegate void Terraria.ModLoader.ItemLoader.DelegateSetMatch (int armorSlot, int type, bool male, ref int equipSlot, ref bool robes) private
delegate bool Terraria.ModLoader.ItemLoader.DelegateShoot (Item item, Player player, ref Vector2 position, ref float speedX, ref float speedY, ref int type, ref int damage, ref float knockBack) private
delegate void Terraria.ModLoader.ItemLoader.DelegateUpdate (Item item, ref float gravity, ref float maxFallSpeed) private
delegate void Terraria.ModLoader.ItemLoader.DelegateUseItemHitbox (Item item, Player player, ref Rectangle hitbox, ref bool noHitbox) private
delegate void Terraria.ModLoader.ItemLoader.DelegateVerticalWingSpeeds (Item item, Player player, ref float ascentWhenFalling, ref float ascentWhenRising, ref float maxCanAscendMultiplier, ref float maxAscentMultiplier, ref float constantAscend) private
static void Terraria.ModLoader.ItemLoader.DrawArmorColor (EquipType type, int slot, Player drawPlayer, float shadow, ref Color color, ref int glowMask, ref Color glowMaskColor) static
Calls the item's equipment texture's DrawArmorColor hook, then all GlobalItem.DrawArmorColor hooks.
Definition at line 1262 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr, Terraria.ModLoader.EquipTexture.DrawArmorColor(), and Terraria.ModLoader.EquipLoader.GetEquipTexture().
{
             EquipTexture texture = EquipLoader.GetEquipTexture(type, slot);
             texture?.DrawArmorColor(drawPlayer, shadow, ref color, ref glowMask, ref glowMaskColor);
             foreach (var g in HookDrawArmorColor.arr)
                 g.DrawArmorColor(type, slot, drawPlayer, shadow, ref color, ref glowMask, ref glowMaskColor);
         }
static bool Terraria.ModLoader.ItemLoader.DrawBody (Player player) static
Calls the item's body equipment texture's DrawBody hook, then all GlobalItem.DrawBody hooks, until one of them returns false. Returns true if none of them return false.
Definition at line 1225 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr, Terraria.ModLoader.EquipTexture.DrawBody(), and Terraria.ModLoader.EquipLoader.GetEquipTexture().
{
             EquipTexture texture = EquipLoader.GetEquipTexture(EquipType.Body, player.body);
             if (texture != null && !texture.DrawBody())
                 return false;
             foreach (var g in HookDrawBody.arr)
                 if (!g.DrawBody(player.body))
                     return false;
             return true;
         }
static void Terraria.ModLoader.ItemLoader.DrawHair (Player player, ref bool drawHair, ref bool drawAltHair) static
Calls the item's head equipment texture's DrawHair hook, then all GlobalItem.DrawHair hooks.
Definition at line 1194 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr, Terraria.ModLoader.EquipTexture.DrawHair(), and Terraria.ModLoader.EquipLoader.GetEquipTexture().
{
             EquipTexture texture = EquipLoader.GetEquipTexture(EquipType.Head, player.head);
             texture?.DrawHair(ref drawHair, ref drawAltHair);
             foreach (var g in HookDrawHair.arr)
                 g.DrawHair(player.head, ref drawHair, ref drawAltHair);
         }
static void Terraria.ModLoader.ItemLoader.DrawHands (Player player, ref bool drawHands, ref bool drawArms) static
Calls the item's body equipment texture's DrawHands hook, then all GlobalItem.DrawHands hooks.
Definition at line 1177 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr, Terraria.ModLoader.EquipTexture.DrawHands(), and Terraria.ModLoader.EquipLoader.GetEquipTexture().
{
             EquipTexture texture = EquipLoader.GetEquipTexture(EquipType.Body, player.body);
             texture?.DrawHands(ref drawHands, ref drawArms);
             foreach (var g in HookDrawHands.arr)
                 g.DrawHands(player.body, ref drawHands, ref drawArms);
         }
static bool Terraria.ModLoader.ItemLoader.DrawHead (Player player) static
Calls the item's head equipment texture's DrawHead hook, then all GlobalItem.DrawHead hooks, until one of them returns false. Returns true if none of them return false.
Definition at line 1209 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr, Terraria.ModLoader.EquipTexture.DrawHead(), and Terraria.ModLoader.EquipLoader.GetEquipTexture().
{
             EquipTexture texture = EquipLoader.GetEquipTexture(EquipType.Head, player.head);
             if (texture != null && !texture.DrawHead())
                 return false;
             foreach (var g in HookDrawHead.arr)
                 if (!g.DrawHead(player.head))
                     return false;
             return true;
         }
static bool Terraria.ModLoader.ItemLoader.DrawLegs (Player player) static
Calls the item's leg equipment texture's DrawLegs hook, then the item's shoe equipment texture's DrawLegs hook, then all GlobalItem.DrawLegs hooks, until one of them returns false. Returns true if none of them return false.
Definition at line 1241 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr, Terraria.ModLoader.EquipTexture.DrawLegs(), and Terraria.ModLoader.EquipLoader.GetEquipTexture().
{
             EquipTexture texture = EquipLoader.GetEquipTexture(EquipType.Legs, player.legs);
             if (texture != null && !texture.DrawLegs())
                 return false;
             texture = EquipLoader.GetEquipTexture(EquipType.Shoes, player.shoe);
             if (texture != null && !texture.DrawLegs())
                 return false;
             foreach (var g in HookDrawLegs.arr)
                 if (!g.DrawLegs(player.legs, player.shoe))
                     return false;
             return true;
         }
static void Terraria.ModLoader.ItemLoader.ExtractinatorUse (ref int resultType, ref int resultStack, int extractType) static
Definition at line 1619 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr.
{
             GetItem(extractType)?.ExtractinatorUse(ref resultType, ref resultStack);
             foreach (var g in HookExtractinatorUse.arr)
                 g.ExtractinatorUse(extractType, ref resultType, ref resultStack);
         }
static void Terraria.ModLoader.ItemLoader.FindVanillaWings () static private
Definition at line 52 of file ItemLoader.cs.
References Terraria.ModLoader.ModNet.AllowVanillaClients, and Terraria.ModLoader.Item.
{
             if (vanillaWings[1] != 0)
                 return;
             Item item = new Item();
             for (int k = 0; k < ItemID.Count; k++) {
                 item.SetDefaults(k);
                 if (item.wingSlot > 0) {
                     vanillaWings[item.wingSlot] = k;
                 }
             }
         }
static bool Terraria.ModLoader.ItemLoader.GeneralPrefix (Item item) static private
Definition at line 174 of file ItemLoader.cs.
References Terraria.ModLoader.Item.
{
             return item.maxStack == 1 && item.damage > 0 && item.ammo == 0 && !item.accessory;
         }
static Color Terraria.ModLoader.ItemLoader.GetAlpha (Item item, Color lightColor) static
Calls all GlobalItem.GetAlpha hooks then ModItem.GetAlpha, until one of them returns a color, and returns that color. Returns null if all of the hooks return null.
Definition at line 1484 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr, and Terraria.ModLoader.Item.
{
             if (item.IsAir)
                 return null;
             foreach (var g in HookGetAlpha.arr) {
                 Color? color = g.Instance(item).GetAlpha(item, lightColor);
                 if (color.HasValue)
                     return color;
             }
             return item.modItem?.GetAlpha(lightColor);
         }
static void Terraria.ModLoader.ItemLoader.GetHealLife (Item item, Player player, bool quickHeal, ref int healValue) static
Calls ModItem.GetHealLife, then all GlobalItem.GetHealLife hooks.
Definition at line 397 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr, and Terraria.ModLoader.Item.
{
             if (item.IsAir)
                 return;
             item.modItem?.GetHealLife(player, quickHeal, ref healValue);
             foreach (var g in HookGetHealLife.arr)
                 g.Instance(item).GetHealLife(item, player, quickHeal, ref healValue);
         }
static void Terraria.ModLoader.ItemLoader.GetHealMana (Item item, Player player, bool quickHeal, ref int healValue) static
Calls ModItem.GetHealMana, then all GlobalItem.GetHealMana hooks.
Definition at line 412 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr, and Terraria.ModLoader.Item.
{
             if (item.IsAir)
                 return;
             item.modItem?.GetHealMana(player, quickHeal, ref healValue);
             foreach (var g in HookGetHealMana.arr)
                 g.Instance(item).GetHealMana(item, player, quickHeal, ref healValue);
         }
static ModItem Terraria.ModLoader.ItemLoader.GetItem (int type) static
Gets the ModItem instance corresponding to the specified type. Returns null if no modded item has the given type.
Definition at line 76 of file ItemLoader.cs.
Referenced by Terraria.ModLoader.Mod.AddMusicBox(), and Terraria.ModLoader.ModContent.MusicExists().
{
             return type >= ItemID.Count && type < ItemCount ? items[type - ItemID.Count] : null;
         }
static void Terraria.ModLoader.ItemLoader.GetWeaponCrit (Item item, Player player, ref int crit) static
Calls ModItem.GetWeaponCrit, then all GlobalItem.GetWeaponCrit hooks.
Definition at line 526 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr.
{
             if (item.IsAir)
                 return;
             item.modItem?.GetWeaponCrit(player, ref crit);
             foreach (var g in HookGetWeaponCrit.arr)
                 g.Instance(item).GetWeaponCrit(item, player, ref crit);
         }
static void Terraria.ModLoader.ItemLoader.GetWeaponDamage (Item item, Player player, ref int damage) static
Calls ModItem.GetWeaponDamage, then all GlobalItem.GetWeaponDamage hooks.
Definition at line 475 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr, and Terraria.ModLoader.Item.
Referenced by Terraria.ModLoader.CombinedHooks.GetWeaponDamage().
{
             if (item.IsAir)
                 return;
             item.modItem?.GetWeaponDamage(player, ref damage);
             foreach (var g in HookGetWeaponDamage.arr)
                 g.Instance(item).GetWeaponDamage(item, player, ref damage);
         }
static void Terraria.ModLoader.ItemLoader.GetWeaponKnockback (Item item, Player player, ref float knockback) static
Calls ModItem.GetWeaponKnockback, then all GlobalItem.GetWeaponKnockback hooks.
Definition at line 510 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr, and Terraria.ModLoader.Item.
{
             if (item.IsAir)
                 return;
             item.modItem?.GetWeaponKnockback(player, ref knockback);
             foreach (var g in HookGetWeaponKnockback.arr)
                 g.Instance(item).GetWeaponKnockback(item, player, ref knockback);
         }
static Item Terraria.ModLoader.ItemLoader.GetWing (Player player) static
s Returns the wing item that the player is functionally using. If player.wingsLogic has been modified, so no equipped wing can be found to match what the player is using, this creates a new Item object to return.
Definition at line 1287 of file ItemLoader.cs.
References Terraria.ModLoader.EquipLoader.GetEquipTexture(), Terraria.ModLoader.Item, Terraria.ModLoader.ModItem.item, and Terraria.ModLoader.EquipTexture.item.
{
             Item item = null;
             for (int k = 3; k < 8 + player.extraAccessorySlots; k++) {
                 if (player.armor[k].wingSlot == player.wingsLogic) {
                     item = player.armor[k];
                 }
             }
             if (item != null) {
                 return item;
             }
             if (player.wingsLogic > 0 && player.wingsLogic < Main.maxWings) {
                 item = new Item();
                 item.SetDefaults(vanillaWings[player.wingsLogic]);
                 return item;
             }
             if (player.wingsLogic >= Main.maxWings) {
                 EquipTexture texture = EquipLoader.GetEquipTexture(EquipType.Wings, player.wingsLogic);
                 if (texture?.item != null)
                     return texture.item.item;
             }
             return null;
         }
static void Terraria.ModLoader.ItemLoader.GrabRange (Item item, Player player, ref int grabRange) static
Calls ModItem.GrabRange, then all GlobalItem.GrabRange hooks.
Definition at line 1419 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr.
{
             item.modItem?.GrabRange(player, ref grabRange);
             foreach (var g in HookGrabRange.arr)
                 g.Instance(item).GrabRange(item, player, ref grabRange);
         }
static bool Terraria.ModLoader.ItemLoader.GrabStyle (Item item, Player player) static
Calls all GlobalItem.GrabStyle hooks then ModItem.GrabStyle, until one of them returns true. Returns whether any of the hooks returned true.
Definition at line 1432 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr.
{
             foreach (var g in HookGrabStyle.arr)
                 if (g.Instance(item).GrabStyle(item, player))
                     return true;
             return item.modItem != null && item.modItem.GrabStyle(player);
         }
static bool Terraria.ModLoader.ItemLoader.HasMethod (Type t, string method, params Type[] args) static private
Definition at line 1773 of file ItemLoader.cs.
References Terraria.ModLoader.GlobalItem.CloneNewInstances, Terraria.ModLoader.GlobalItem.InstancePerEntity, and Terraria.ModLoader.Item.
{
             return t.GetMethod(method, args).DeclaringType != typeof(GlobalItem);
         }
static void Terraria.ModLoader.ItemLoader.HoldItem (Item item, Player player) static
Calls ModItem.HoldItem and all GlobalItem.HoldItem hooks.
Definition at line 356 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr.
{
             if (item.IsAir)
                 return;
             item.modItem?.HoldItem(player);
             foreach (var g in HookHoldItem.arr)
                 g.Instance(item).HoldItem(item, player);
         }
static bool Terraria.ModLoader.ItemLoader.HoldItemFrame (Item item, Player player) static
Calls ModItem.HoldItemFrame, then all GlobalItem.HoldItemFrame hooks, until one of them returns true. Returns whether any of the hooks returned true.
Definition at line 830 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr.
{
             if (item.IsAir)
                 return false;
             if (item.modItem != null && item.modItem.HoldItemFrame(player))
                 return true;
             foreach (var g in HookHoldItemFrame.arr)
                 if (g.Instance(item).HoldItemFrame(item, player))
                     return true;
             return false;
         }
static void Terraria.ModLoader.ItemLoader.HoldoutOffset (float gravDir, int type, ref Vector2 offset) static
Definition at line 1563 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr, and Terraria.ModLoader.ModItem.HoldoutOffset().
{
             ModItem modItem = GetItem(type);
             if (modItem != null) {
                 Vector2? modOffset = modItem.HoldoutOffset();
                 if (modOffset.HasValue) {
                     offset.X = modOffset.Value.X;
                     offset.Y += gravDir * modOffset.Value.Y;
                 }
             }
             foreach (var g in HookHoldoutOffset.arr) {
                 Vector2? modOffset = g.HoldoutOffset(type);
                 if (modOffset.HasValue) {
                     offset.X = modOffset.Value.X;
                     offset.Y = Main.itemTexture[type].Height / 2f + gravDir * modOffset.Value.Y;
                 }
             }
         }
static void Terraria.ModLoader.ItemLoader.HoldoutOrigin (Player player, ref Vector2 origin) static
Definition at line 1582 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr, and Terraria.ModLoader.Item.
{
             Item item = player.inventory[player.selectedItem];
             Vector2 modOrigin = Vector2.Zero;
             if (item.modItem != null) {
                 Vector2? modOrigin2 = item.modItem.HoldoutOrigin();
                 if (modOrigin2.HasValue) {
                     modOrigin = modOrigin2.Value;
                 }
             }
             foreach (var g in HookHoldoutOrigin.arr) {
                 Vector2? modOrigin2 = g.Instance(item).HoldoutOrigin(item.type);
                 if (modOrigin2.HasValue) {
                     modOrigin = modOrigin2.Value;
                 }
             }
             modOrigin.X *= player.direction;
             modOrigin.Y *= -player.gravDir;
             origin += modOrigin;
         }
static void Terraria.ModLoader.ItemLoader.HoldStyle (Item item, Player player) static
If the player is not holding onto a rope and is not in the middle of using an item, calls ModItem.HoldStyle and all GlobalItem.HoldStyle hooks.
Definition at line 341 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr.
{
             if (item.IsAir || player.pulley || player.itemAnimation > 0)
                 return;
             item.modItem?.HoldStyle(player);
             foreach (var g in HookHoldStyle.arr)
                 g.Instance(item).HoldStyle(item, player);
         }
static void Terraria.ModLoader.ItemLoader.HorizontalWingSpeeds (Player player) static
If the player is using wings, this uses the result of GetWing, and calls ModItem.HorizontalWingSpeeds then all GlobalItem.HorizontalWingSpeeds hooks.
Definition at line 1343 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr, Terraria.ModLoader.EquipLoader.GetEquipTexture(), Terraria.ModLoader.EquipTexture.HorizontalWingSpeeds(), and Terraria.ModLoader.Item.
{
             Item item = GetWing(player);
             if (item == null) {
                 EquipTexture texture = EquipLoader.GetEquipTexture(EquipType.Wings, player.wingsLogic);
                 texture?.HorizontalWingSpeeds(player, ref player.accRunSpeed, ref player.runAcceleration);
                 return;
             }
             item.modItem?.HorizontalWingSpeeds(player, ref player.accRunSpeed, ref player.runAcceleration);
             foreach (var g in HookHorizontalWingSpeeds.arr)
                 g.Instance(item).HorizontalWingSpeeds(item, player, ref player.accRunSpeed, ref player.runAcceleration);
         }
static void Terraria.ModLoader.ItemLoader.IsAnglerQuestAvailable (int itemID, ref bool notAvailable) static
Definition at line 1649 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr, and Terraria.ModLoader.ModItem.IsAnglerQuestAvailable().
{
             ModItem modItem = GetItem(itemID);
             if (modItem != null)
                 notAvailable |= !modItem.IsAnglerQuestAvailable();
             foreach (var g in HookIsAnglerQuestAvailable.arr)
                 notAvailable |= !g.IsAnglerQuestAvailable(itemID);
         }
static bool Terraria.ModLoader.ItemLoader.IsModBossBag (Item item) static
Returns whether ModItem.bossBagNPC is greater than 0. Returns false if item is not a modded item.
Definition at line 1087 of file ItemLoader.cs.
{
             return item.modItem != null && item.modItem.BossBagNPC > 0;
         }
static bool Terraria.ModLoader.ItemLoader.ItemSpace (Item item, Player player) static
Definition at line 1468 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr.
{
             foreach (var g in HookItemSpace.arr)
                 if (g.Instance(item).ItemSpace(item, player))
                     return true;
             return item.modItem?.ItemSpace(player) ?? false;
         }
static void Terraria.ModLoader.ItemLoader.MeleeEffects (Item item, Player player, Rectangle hitbox) static
Calls ModItem.MeleeEffects and all GlobalItem.MeleeEffects hooks.
Definition at line 650 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr.
{
             item.modItem?.MeleeEffects(player, hitbox);
             foreach (var g in HookMeleeEffects.arr)
                 g.Instance(item).MeleeEffects(item, player, hitbox);
         }
static float Terraria.ModLoader.ItemLoader.MeleeSpeedMultiplier (Item item, Player player) static
Definition at line 380 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr, and Terraria.ModLoader.Item.
Referenced by Terraria.ModLoader.PlayerHooks.TotalMeleeSpeedMultiplier().
{
             if (item.IsAir)
                 return 1f;
             float multiplier = item.modItem?.MeleeSpeedMultiplier(player) ?? 1f;
             foreach (var g in HookMeleeSpeedMultiplier.arr)
                 multiplier *= g.Instance(item).MeleeSpeedMultiplier(item, player);
             return multiplier;
         }
static void Terraria.ModLoader.ItemLoader.ModifyHitNPC (Item item, Player player, NPC target, ref int damage, ref float knockBack, ref bool crit) static
Calls ModItem.ModifyHitNPC, then all GlobalItem.ModifyHitNPC hooks.
Definition at line 694 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr.
{
             item.modItem?.ModifyHitNPC(player, target, ref damage, ref knockBack, ref crit);
             foreach (var g in HookModifyHitNPC.arr)
                 g.Instance(item).ModifyHitNPC(item, player, target, ref damage, ref knockBack, ref crit);
         }
static void Terraria.ModLoader.ItemLoader.ModifyHitPvp (Item item, Player player, Player target, ref int damage, ref bool crit) static
Calls ModItem.ModifyHitPvp, then all GlobalItem.ModifyHitPvp hooks.
Definition at line 735 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr.
{
             item.modItem?.ModifyHitPvp(player, target, ref damage, ref crit);
             foreach (var g in HookModifyHitPvp.arr)
                 g.Instance(item).ModifyHitPvp(item, player, target, ref damage, ref crit);
         }
static void Terraria.ModLoader.ItemLoader.ModifyManaCost (Item item, Player player, ref float reduce, ref float mult) static
Calls ModItem.ModifyManaCost, then all GlobalItem.ModifyManaCost hooks.
Definition at line 427 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr.
Referenced by Terraria.ModLoader.CombinedHooks.ModifyManaCost().
{
             if (item.IsAir)
                 return;
             item.modItem?.ModifyManaCost(player, ref reduce, ref mult);
             foreach (var g in HookModifyManaCost.arr) {
                 g.Instance(item).ModifyManaCost(item, player, ref reduce, ref mult);
             }
         }
static List<TooltipLine> Terraria.ModLoader.ItemLoader.ModifyTooltips (Item item, ref int numTooltips, string[] names, ref string[] text, ref bool[] modifier, ref bool[] badModifier, ref int oneDropLogo, out Color?[] overrideColor) static
Definition at line 1718 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr, Terraria.ModLoader.TooltipLine.isModifier, and Terraria.ModLoader.TooltipLine.isModifierBad.
{
             List<TooltipLine> tooltips = new List<TooltipLine>();
             for (int k = 0; k < numTooltips; k++) {
                 TooltipLine tooltip = new TooltipLine(names[k], text[k]);
                 tooltip.isModifier = modifier[k];
                 tooltip.isModifierBad = badModifier[k];
                 if (k == oneDropLogo) {
                     tooltip.oneDropLogo = true;
                 }
                 tooltips.Add(tooltip);
             }
             item.modItem?.ModifyTooltips(tooltips);
             foreach (var g in HookModifyTooltips.arr)
                 g.Instance(item).ModifyTooltips(item, tooltips);
             numTooltips = tooltips.Count;
             text = new string[numTooltips];
             modifier = new bool[numTooltips];
             badModifier = new bool[numTooltips];
             oneDropLogo = -1;
             overrideColor = new Color?[numTooltips];
             for (int k = 0; k < numTooltips; k++) {
                 text[k] = tooltips[k].text;
                 modifier[k] = tooltips[k].isModifier;
                 badModifier[k] = tooltips[k].isModifierBad;
                 if (tooltips[k].oneDropLogo) {
                     oneDropLogo = k;
                 }
                 overrideColor[k] = tooltips[k].overrideColor;
             }
             return tooltips;
         }
static void Terraria.ModLoader.ItemLoader.ModifyWeaponDamage (Item item, Player player, ref float add, ref float mult, ref float flat) static
Calls ModItem.HookModifyWeaponDamage, then all GlobalItem.HookModifyWeaponDamage hooks.
Definition at line 492 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr, and Terraria.ModLoader.Item.
Referenced by Terraria.ModLoader.CombinedHooks.ModifyWeaponDamage().
{
             if (item.IsAir)
                 return;
             item.modItem?.ModifyWeaponDamage(player, ref add, ref mult);
             item.modItem?.ModifyWeaponDamage(player, ref add, ref mult, ref flat);
             foreach (var g in HookModifyWeaponDamageOld.arr)
                 g.Instance(item).ModifyWeaponDamage(item, player, ref add, ref mult);
             foreach (var g in HookModifyWeaponDamage.arr)
                 g.Instance(item).ModifyWeaponDamage(item, player, ref add, ref mult, ref flat);
         }
static bool Terraria.ModLoader.ItemLoader.NeedsModSaving (Item item) static
Definition at line 1754 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr, and Terraria.ModLoader.ModNet.GetMod().
{
             return item.type != 0 && (item.modItem != null || item.prefix >= PrefixID.Count || HookNeedsSaving.arr.Count(g => g.Instance(item).NeedsSaving(item)) > 0);
         }
static void Terraria.ModLoader.ItemLoader.OnConsumeAmmo (Item item, Item ammo, Player player) static
Calls ModItem.OnConsumeAmmo for the weapon, ModItem.OnConsumeAmmo for the ammo, then each GlobalItem.OnConsumeAmmo hook for the weapon and ammo.
Definition at line 587 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr, and Terraria.ModLoader.Item.
{
             if (item.IsAir)
                 return;
             item.modItem?.OnConsumeAmmo(player);
             ammo.modItem?.OnConsumeAmmo(player);
             foreach (var g in HookOnConsumeAmmo.arr) {
                 g.Instance(item).OnConsumeAmmo(item, player);
                 g.Instance(ammo).OnConsumeAmmo(ammo, player);
             }
         }
static void Terraria.ModLoader.ItemLoader.OnConsumeItem (Item item, Player player) static
Calls ModItem.OnConsumeItem and all GlobalItem.OnConsumeItem hooks.
Definition at line 797 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr.
{
             if (item.IsAir)
                 return;
             item.modItem?.OnConsumeItem(player);
             foreach (var g in HookOnConsumeItem.arr)
                 g.Instance(item).OnConsumeItem(item, player);
         }
static void Terraria.ModLoader.ItemLoader.OnConsumeMana (Item item, Player player, int manaConsumed) static
Calls ModItem.OnConsumeMana, then all GlobalItem.OnConsumeMana hooks.
Definition at line 457 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr, and Terraria.ModLoader.Item.
Referenced by Terraria.ModLoader.CombinedHooks.OnConsumeMana().
{
             if (item.IsAir)
                 return;
             item.modItem?.OnConsumeMana(player, manaConsumed);
             foreach (var g in HookOnConsumeMana.arr) {
                 g.Instance(item).OnConsumeMana(item, player, manaConsumed);
             }
         }
static void Terraria.ModLoader.ItemLoader.OnCraft (Item item, Recipe recipe) static
Definition at line 1675 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr, and Terraria.ModLoader.Item.
{
             item.modItem?.OnCraft(recipe);
             foreach (var g in HookOnCraft.arr)
                 g.Instance(item).OnCraft(item, recipe);
         }
static void Terraria.ModLoader.ItemLoader.OnHitNPC (Item item, Player player, NPC target, int damage, float knockBack, bool crit) static
Calls ModItem.OnHitNPC and all GlobalItem.OnHitNPC hooks.
Definition at line 707 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr.
{
             item.modItem?.OnHitNPC(player, target, damage, knockBack, crit);
             foreach (var g in HookOnHitNPC.arr)
                 g.Instance(item).OnHitNPC(item, player, target, damage, knockBack, crit);
         }
static void Terraria.ModLoader.ItemLoader.OnHitPvp (Item item, Player player, Player target, int damage, bool crit) static
Calls ModItem.OnHitPvp and all GlobalItem.OnHitPvp hooks.
Definition at line 748 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr.
{
             item.modItem?.OnHitPvp(player, target, damage, crit);
             foreach (var g in HookOnHitPvp.arr)
                 g.Instance(item).OnHitPvp(item, player, target, damage, crit);
         }
static void Terraria.ModLoader.ItemLoader.OnMissingMana (Item item, Player player, int neededMana) static
Calls ModItem.OnMissingMana, then all GlobalItem.OnMissingMana hooks.
Definition at line 442 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr.
Referenced by Terraria.ModLoader.CombinedHooks.OnMissingMana().
{
             if (item.IsAir)
                 return;
             item.modItem?.OnMissingMana(player, neededMana);
             foreach (var g in HookOnMissingMana.arr) {
                 g.Instance(item).OnMissingMana(item, player, neededMana);
             }
         }
static bool Terraria.ModLoader.ItemLoader.OnPickup (Item item, Player player) static
Calls all GlobalItem.OnPickup hooks then ModItem.OnPickup, until one of the returns false. Returns true if all of the hooks return true.
Definition at line 1457 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr.
{
             foreach (var g in HookOnPickup.arr)
                 if (!g.Instance(item).OnPickup(item, player))
                     return false;
             return item.modItem?.OnPickup(player) ?? true;
         }
static void Terraria.ModLoader.ItemLoader.OpenBossBag (int type, Player player, ref int npc) static
If the item is a modded item and ModItem.bossBagNPC is greater than 0, calls ModItem.OpenBossBag and sets npc to ModItem.bossBagNPC.
Definition at line 1096 of file ItemLoader.cs.
References Terraria.ModLoader.ModItem.BossBagNPC, and Terraria.ModLoader.ModItem.OpenBossBag().
{
             ModItem modItem = GetItem(type);
             if (modItem != null && modItem.BossBagNPC > 0) {
                 modItem.OpenBossBag(player);
                 npc = modItem.BossBagNPC;
             }
         }
static void Terraria.ModLoader.ItemLoader.OpenVanillaBag (string context, Player player, int arg) static
Calls all GlobalItem.OpenVanillaBag hooks.
Definition at line 1131 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr, and Terraria.ModLoader.Item.
{
             foreach (var g in HookOpenVanillaBag.arr)
                 g.OpenVanillaBag(context, player, arg);
         }
static void Terraria.ModLoader.ItemLoader.PickAmmo (Item weapon, Item ammo, Player player, ref int type, ref float speed, ref int damage, ref float knockback) static
Calls ModItem.PickAmmo, then all GlobalItem.PickAmmo hooks.
Definition at line 551 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr.
{
             ammo.modItem?.PickAmmo(weapon, player, ref type, ref speed, ref damage, ref knockback);
             ammo.modItem?.PickAmmo(player, ref type, ref speed, ref damage, ref knockback); // deprecated
             foreach (var g in HookPickAmmo.arr) {
                 g.Instance(ammo).PickAmmo(weapon, ammo, player, ref type, ref speed, ref damage, ref knockback);
             }
             foreach (var g in HookOldPickAmmo.arr) {
                 g.Instance(ammo).PickAmmo(ammo, player, ref type, ref speed, ref damage, ref knockback); // deprecated
             }
         }
static void Terraria.ModLoader.ItemLoader.PostDrawInInventory (Item item, SpriteBatch spriteBatch, Vector2 position, Rectangle frame, Color drawColor, Color itemColor, Vector2 origin, float scale) static
Calls ModItem.PostDrawInInventory, then all GlobalItem.PostDrawInInventory hooks.
Definition at line 1554 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr.
{
             item.modItem?.PostDrawInInventory(spriteBatch, position, frame, drawColor, itemColor, origin, scale);
             foreach (var g in HookPostDrawInInventory.arr)
                 g.Instance(item).PostDrawInInventory(item, spriteBatch, position, frame, drawColor, itemColor, origin, scale);
         }
static void Terraria.ModLoader.ItemLoader.PostDrawInWorld (Item item, SpriteBatch spriteBatch, Color lightColor, Color alphaColor, float rotation, float scale, int whoAmI) static
Calls ModItem.PostDrawInWorld, then all GlobalItem.PostDrawInWorld hooks.
Definition at line 1521 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr.
{
             item.modItem?.PostDrawInWorld(spriteBatch, lightColor, alphaColor, rotation, scale, whoAmI);
             foreach (var g in HookPostDrawInWorld.arr)
                 g.Instance(item).PostDrawInWorld(item, spriteBatch, lightColor, alphaColor, rotation, scale, whoAmI);
         }
static void Terraria.ModLoader.ItemLoader.PostDrawTooltip (Item item, ReadOnlyCollection< DrawableTooltipLine > lines) static
Definition at line 1693 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr, and Terraria.ModLoader.Item.
{
             item.modItem?.PostDrawTooltip(lines);
             foreach (var g in HookPostDrawTooltip.arr)
                 g.Instance(item).PostDrawTooltip(item, lines);
         }
static void Terraria.ModLoader.ItemLoader.PostDrawTooltipLine (Item item, DrawableTooltipLine line) static
Definition at line 1711 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr.
{
             item.modItem?.PostDrawTooltipLine(line);
             foreach (var g in HookPostDrawTooltipLine.arr)
                 g.Instance(item).PostDrawTooltipLine(item, line);
         }
static void Terraria.ModLoader.ItemLoader.PostReforge (Item item) static
Calls ModItem.PostReforge, then all GlobalItem.PostReforge hooks.
Definition at line 1166 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr.
{
             item.modItem?.PostReforge();
             foreach (var g in HookPostReforge.arr)
                 g.Instance(item).PostReforge(item);
         }
static void Terraria.ModLoader.ItemLoader.PostUpdate (Item item) static
Calls ModItem.PostUpdate and all GlobalItem.PostUpdate hooks.
Definition at line 1405 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr, and Terraria.ModLoader.Item.
{
             item.modItem?.PostUpdate();
             foreach (var g in HookPostUpdate.arr)
                 g.Instance(item).PostUpdate(item);
         }
static bool Terraria.ModLoader.ItemLoader.PreDrawInInventory (Item item, SpriteBatch spriteBatch, Vector2 position, Rectangle frame, Color drawColor, Color itemColor, Vector2 origin, float scale) static
Returns the "and" operator on the results of all GlobalItem.PreDrawInInventory hooks and ModItem.PreDrawInInventory.
Definition at line 1535 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr.
{
             bool flag = true;
             foreach (var g in HookPreDrawInInventory.arr)
                 flag &= g.Instance(item).PreDrawInInventory(item, spriteBatch, position, frame, drawColor, itemColor, origin, scale);
             if (item.modItem != null)
                 flag &= item.modItem.PreDrawInInventory(spriteBatch, position, frame, drawColor, itemColor, origin, scale);
             return flag;
         }
static bool Terraria.ModLoader.ItemLoader.PreDrawInWorld (Item item, SpriteBatch spriteBatch, Color lightColor, Color alphaColor, ref float rotation, ref float scale, int whoAmI) static
Returns the "and" operator on the results of ModItem.PreDrawInWorld and all GlobalItem.PreDrawInWorld hooks.
Definition at line 1504 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr.
{
             bool flag = true;
             if (item.modItem != null)
                 flag &= item.modItem.PreDrawInWorld(spriteBatch, lightColor, alphaColor, ref rotation, ref scale, whoAmI);
             foreach (var g in HookPreDrawInWorld.arr)
                 flag &= g.Instance(item).PreDrawInWorld(item, spriteBatch, lightColor, alphaColor, ref rotation, ref scale, whoAmI);
             return flag;
         }
static bool Terraria.ModLoader.ItemLoader.PreDrawTooltip (Item item, ReadOnlyCollection< TooltipLine > lines, ref int x, ref int y) static
Definition at line 1683 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr, and Terraria.ModLoader.Item.
{
             bool modItemPreDraw = item.modItem?.PreDrawTooltip(lines, ref x, ref y) ?? true;
             List<bool> globalItemPreDraw = new List<bool>();
             foreach (var g in HookPreDrawTooltip.arr)
                 globalItemPreDraw.Add(g.PreDrawTooltip(item, lines, ref x, ref y));
             return modItemPreDraw && globalItemPreDraw.All(z => z);
         }
static bool Terraria.ModLoader.ItemLoader.PreDrawTooltipLine (Item item, DrawableTooltipLine line, ref int yOffset) static
Definition at line 1701 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr, and Terraria.ModLoader.Item.
{
             bool modItemPreDrawLine = item.modItem?.PreDrawTooltipLine(line, ref yOffset) ?? true;
             List<bool> globalItemPreDrawLine = new List<bool>();
             foreach (var g in HookPreDrawTooltipLine.arr)
                 globalItemPreDrawLine.Add(g.PreDrawTooltipLine(item, line, ref yOffset));
             return modItemPreDrawLine && globalItemPreDrawLine.All(x => x);
         }
static bool Terraria.ModLoader.ItemLoader.PrefixChance (Item item, int pre, UnifiedRandom rand) static
Allows for blocking, forcing and altering chance of prefix rolling. False (block) takes precedence over True (force). Null gives vanilla behaviour
Definition at line 273 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr.
{
             bool? result = null;
             foreach (var g in HookPrefixChance.arr) {
                 bool? r = g.Instance(item).PrefixChance(item, pre, rand);
                 if (r.HasValue)
                     result = r.Value && (result ?? true);
             }
             if (item.modItem != null) {
                 bool? r = item.modItem.PrefixChance(pre, rand);
                 if (r.HasValue)
                     result = r.Value && (result ?? true);
             }
             return result;
         }
static bool Terraria.ModLoader.ItemLoader.PreOpenVanillaBag (string context, Player player, int arg) static
Calls each GlobalItem.PreOpenVanillaBag hook until one of them returns false. Returns true if all of them returned true.
Definition at line 1112 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr, and Terraria.ModLoader.NPCLoader.blockLoot.
{
             bool result = true;
             foreach (var g in HookPreOpenVanillaBag.arr)
                 result &= g.PreOpenVanillaBag(context, player, arg);
             if (!result) {
                 NPCLoader.blockLoot.Clear(); // clear blockloot
                 return false;
             }
             return true;
         }
static bool Terraria.ModLoader.ItemLoader.PreReforge (Item item) static
Calls ModItem.PreReforge, then all GlobalItem.PreReforge hooks.
Definition at line 1155 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr.
{
             bool b = item.modItem?.NewPreReforge() ?? true;
             foreach (var g in HookPreReforge.arr)
                 b &= g.Instance(item).NewPreReforge(item);
             return b;
         }
static void Terraria.ModLoader.ItemLoader.PreUpdateVanitySet (Player player) static
If the player's head texture's IsVanitySet returns true, calls the equipment texture's PreUpdateVanitySet. This is then repeated for the player's body, then the legs. Then for each GlobalItem, if GlobalItem.IsVanitySet returns a non-empty string, calls GlobalItem.PreUpdateVanitySet, using player.head, player.body, and player.legs.
Definition at line 948 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr, Terraria.ModLoader.EquipLoader.GetEquipTexture(), Terraria.ModLoader.EquipTexture.IsVanitySet(), Terraria.ModLoader.GlobalItem.IsVanitySet(), Terraria.ModLoader.EquipTexture.PreUpdateVanitySet(), and Terraria.ModLoader.GlobalItem.PreUpdateVanitySet().
{
             EquipTexture headTexture = EquipLoader.GetEquipTexture(EquipType.Head, player.head);
             EquipTexture bodyTexture = EquipLoader.GetEquipTexture(EquipType.Body, player.body);
             EquipTexture legTexture = EquipLoader.GetEquipTexture(EquipType.Legs, player.legs);
             if (headTexture != null && headTexture.IsVanitySet(player.head, player.body, player.legs))
                 headTexture.PreUpdateVanitySet(player);
             if (bodyTexture != null && bodyTexture.IsVanitySet(player.head, player.body, player.legs))
                 bodyTexture.PreUpdateVanitySet(player);
             if (legTexture != null && legTexture.IsVanitySet(player.head, player.body, player.legs))
                 legTexture.PreUpdateVanitySet(player);
             foreach (GlobalItem globalItem in HookPreUpdateVanitySet.arr) {
                 string set = globalItem.IsVanitySet(player.head, player.body, player.legs);
                 if (!string.IsNullOrEmpty(set))
                     globalItem.PreUpdateVanitySet(player, set);
             }
         }
static bool Terraria.ModLoader.ItemLoader.ReforgePrice (Item item, ref int reforgePrice, ref bool canApplyDiscount) static
Call all ModItem.ReforgePrice, then GlobalItem.ReforgePrice hooks.
Parameters
canApplyDiscount
Returns
Definition at line 1143 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr.
{
             bool b = item.modItem?.ReforgePrice(ref reforgePrice, ref canApplyDiscount) ?? true;
             foreach (var g in HookReforgePrice.arr)
                 b &= g.Instance(item).ReforgePrice(item, ref reforgePrice, ref canApplyDiscount);
             return b;
         }
static void Terraria.ModLoader.ItemLoader.RightClick (Item item, Player player) static
If Main.mouseRightRelease is true, the following steps are taken:
Call ModItem.RightClick
Calls all GlobalItem.RightClick hooks
Call ItemLoader.ConsumeItem, and if it returns true, decrements the item's stack
Sets the item's type to 0 if the item's stack is 0
Plays the item-grabbing sound
Sets Main.stackSplit to 30
Sets Main.mouseRightRelease to false
Calls Recipe.FindRecipes.
Definition at line 1065 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr.
{
             if (!Main.mouseRightRelease)
                 return;
             item.modItem?.RightClick(player);
             foreach (var g in HookRightClick.arr)
                 g.Instance(item).RightClick(item, player);
             if (ConsumeItem(item, player) && --item.stack == 0)
                 item.SetDefaults();
             Main.PlaySound(7);
             Main.stackSplit = 30;
             Main.mouseRightRelease = false;
             Recipe.FindRecipes();
         }
static void Terraria.ModLoader.ItemLoader.SetMatch (int armorSlot, int type, bool male, ref int equipSlot, ref bool robes) static
Calls EquipTexture.SetMatch, then all GlobalItem.SetMatch hooks.
Definition at line 1024 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr, Terraria.ModLoader.EquipLoader.GetEquipTexture(), and Terraria.ModLoader.EquipTexture.SetMatch().
{
             EquipTexture texture = EquipLoader.GetEquipTexture((EquipType)armorSlot, type);
             texture?.SetMatch(male, ref equipSlot, ref robes);
             foreach (var g in HookSetMatch.arr)
                 g.SetMatch(armorSlot, type, male, ref equipSlot, ref robes);
         }
static bool Terraria.ModLoader.ItemLoader.Shoot (Item item, Player player, ref Vector2 position, ref float speedX, ref float speedY, ref int type, ref int damage, ref float knockBack) static
Calls each GlobalItem.Shoot hook, then ModItem.Shoot, until one of them returns false. If all of them return true, returns true.
Parameters
item The weapon item.
player The player.
position The shoot spawn position.
speedX The speed x calculated from shootSpeed and mouse position.
speedY The speed y calculated from shootSpeed and mouse position.
type The projectile type choosen by ammo and weapon.
damage The projectile damage.
knockBack The projectile knock back.
Returns
Definition at line 616 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr, and Terraria.ModLoader.Item.
{
             bool result = true;
             foreach (var g in HookShoot.arr) {
                 result &= g.Instance(item).Shoot(item, player, ref position, ref speedX, ref speedY, ref type, ref damage, ref knockBack);
             }
             if (result && item.modItem != null) {
                 return item.modItem.Shoot(player, ref position, ref speedX, ref speedY, ref type, ref damage, ref knockBack);
             }
             return result;
         }
static void Terraria.ModLoader.ItemLoader.Update (Item item, ref float gravity, ref float maxFallSpeed) static
Calls ModItem.Update, then all GlobalItem.Update hooks.
Definition at line 1381 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr.
{
             item.modItem?.Update(ref gravity, ref maxFallSpeed);
             foreach (var g in HookUpdate.arr)
                 g.Instance(item).Update(item, ref gravity, ref maxFallSpeed);
         }
static void Terraria.ModLoader.ItemLoader.UpdateAccessory (Item item, Player player, bool hideVisual) static
Calls ModItem.UpdateAccessory and all GlobalItem.UpdateAccessory hooks.
Definition at line 900 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr.
{
             if (item.IsAir)
                 return;
             item.modItem?.UpdateAccessory(player, hideVisual);
             foreach (var g in HookUpdateAccessory.arr)
                 g.Instance(item).UpdateAccessory(item, player, hideVisual);
         }
static void Terraria.ModLoader.ItemLoader.UpdateArmorSet (Player player, Item head, Item body, Item legs) static
If the head's ModItem.IsArmorSet returns true, calls the head's ModItem.UpdateArmorSet. This is then repeated for the body, then the legs. Then for each GlobalItem, if GlobalItem.IsArmorSet returns a non-empty string, calls GlobalItem.UpdateArmorSet with that string.
Definition at line 926 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr, Terraria.ModLoader.GlobalItem.IsArmorSet(), and Terraria.ModLoader.GlobalItem.UpdateArmorSet().
{
             if (head.modItem != null && head.modItem.IsArmorSet(head, body, legs))
                 head.modItem.UpdateArmorSet(player);
             if (body.modItem != null && body.modItem.IsArmorSet(head, body, legs))
                 body.modItem.UpdateArmorSet(player);
             if (legs.modItem != null && legs.modItem.IsArmorSet(head, body, legs))
                 legs.modItem.UpdateArmorSet(player);
             foreach (GlobalItem globalItem in HookUpdateArmorSet.arr) {
                 string set = globalItem.IsArmorSet(head, body, legs);
                 if (!string.IsNullOrEmpty(set))
                     globalItem.UpdateArmorSet(player, set);
             }
         }
static void Terraria.ModLoader.ItemLoader.UpdateEquip (Item item, Player player) static
Calls ModItem.UpdateEquip and all GlobalItem.UpdateEquip hooks.
Definition at line 884 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr.
{
             if (item.IsAir)
                 return;
             item.modItem?.UpdateEquip(player);
             foreach (var g in HookUpdateEquip.arr)
                 g.Instance(item).UpdateEquip(item, player);
         }
static void Terraria.ModLoader.ItemLoader.UpdateInventory (Item item, Player player) static
Calls ModItem.UpdateInventory and all GlobalItem.UpdateInventory hooks.
Definition at line 868 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr.
{
             if (item.IsAir)
                 return;
             item.modItem?.UpdateInventory(player);
             foreach (var g in HookUpdateInventory.arr)
                 g.Instance(item).UpdateInventory(item, player);
         }
static void Terraria.ModLoader.ItemLoader.UpdateVanity (Player player) static
Calls each of the item's equipment texture's UpdateVanity hook.
Definition at line 913 of file ItemLoader.cs.
References Terraria.ModLoader.EquipLoader.EquipTypes, Terraria.ModLoader.EquipLoader.GetEquipTexture(), and Terraria.ModLoader.EquipTexture.UpdateVanity().
{
             foreach (EquipType type in EquipLoader.EquipTypes) {
                 int slot = EquipLoader.GetPlayerEquip(player, type);
                 EquipTexture texture = EquipLoader.GetEquipTexture(type, slot);
                 texture?.UpdateVanity(player, type);
             }
         }
static void Terraria.ModLoader.ItemLoader.UpdateVanitySet (Player player) static
If the player's head texture's IsVanitySet returns true, calls the equipment texture's UpdateVanitySet. This is then repeated for the player's body, then the legs. Then for each GlobalItem, if GlobalItem.IsVanitySet returns a non-empty string, calls GlobalItem.UpdateVanitySet, using player.head, player.body, and player.legs.
Definition at line 973 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr, Terraria.ModLoader.EquipLoader.GetEquipTexture(), Terraria.ModLoader.EquipTexture.IsVanitySet(), Terraria.ModLoader.GlobalItem.IsVanitySet(), Terraria.ModLoader.EquipTexture.UpdateVanitySet(), and Terraria.ModLoader.GlobalItem.UpdateVanitySet().
{
             EquipTexture headTexture = EquipLoader.GetEquipTexture(EquipType.Head, player.head);
             EquipTexture bodyTexture = EquipLoader.GetEquipTexture(EquipType.Body, player.body);
             EquipTexture legTexture = EquipLoader.GetEquipTexture(EquipType.Legs, player.legs);
             if (headTexture != null && headTexture.IsVanitySet(player.head, player.body, player.legs))
                 headTexture.UpdateVanitySet(player);
             if (bodyTexture != null && bodyTexture.IsVanitySet(player.head, player.body, player.legs))
                 bodyTexture.UpdateVanitySet(player);
             if (legTexture != null && legTexture.IsVanitySet(player.head, player.body, player.legs))
                 legTexture.UpdateVanitySet(player);
             foreach (GlobalItem globalItem in HookUpdateVanitySet.arr) {
                 string set = globalItem.IsVanitySet(player.head, player.body, player.legs);
                 if (!string.IsNullOrEmpty(set))
                     globalItem.UpdateVanitySet(player, set);
             }
         }
static bool Terraria.ModLoader.ItemLoader.UseItem (Item item, Player player) static
Returns true if any of ModItem.UseItem or GlobalItem.UseItem return true Does not fail fast (calls every hook)
Definition at line 760 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr.
{
             if (item.IsAir)
                 return false;
             bool flag = false;
             if (item.modItem != null)
                 flag |= item.modItem.UseItem(player);
             foreach (var g in HookUseItem.arr)
                 flag |= g.Instance(item).UseItem(item, player);
             return flag;
         }
static bool Terraria.ModLoader.ItemLoader.UseItemFrame (Item item, Player player) static
Calls ModItem.UseItemFrame, then all GlobalItem.UseItemFrame hooks, until one of them returns true. Returns whether any of the hooks returned true.
Definition at line 813 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr.
{
             if (item.modItem != null && item.modItem.UseItemFrame(player))
                 return true;
             foreach (var g in HookUseItemFrame.arr)
                 if (g.Instance(item).UseItemFrame(item, player))
                     return true;
             return false;
         }
static void Terraria.ModLoader.ItemLoader.UseItemHitbox (Item item, Player player, ref Rectangle hitbox, ref bool noHitbox) static
Calls ModItem.UseItemHitbox, then all GlobalItem.UseItemHitbox hooks.
Definition at line 637 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr.
{
             item.modItem?.UseItemHitbox(player, ref hitbox, ref noHitbox);
             foreach (var g in HookUseItemHitbox.arr)
                 g.Instance(item).UseItemHitbox(item, player, ref hitbox, ref noHitbox);
         }
static void Terraria.ModLoader.ItemLoader.UseStyle (Item item, Player player) static
Calls ModItem.UseStyle and all GlobalItem.UseStyle hooks.
Definition at line 326 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr.
{
             if (item.IsAir)
                 return;
             item.modItem?.UseStyle(player);
             foreach (var g in HookUseStyle.arr)
                 g.Instance(item).UseStyle(item, player);
         }
static float Terraria.ModLoader.ItemLoader.UseTimeMultiplier (Item item, Player player) static
Definition at line 367 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr.
Referenced by Terraria.ModLoader.PlayerHooks.TotalUseTimeMultiplier().
{
             if (item.IsAir)
                 return 1f;
             float multiplier = item.modItem?.UseTimeMultiplier(player) ?? 1f;
             foreach (var g in HookUseTimeMultiplier.arr)
                 multiplier *= g.Instance(item).UseTimeMultiplier(item, player);
             return multiplier;
         }
static void Terraria.ModLoader.ItemLoader.VerticalWingSpeeds (Player player, ref float ascentWhenFalling, ref float ascentWhenRising, ref float maxCanAscendMultiplier, ref float maxAscentMultiplier, ref float constantAscend) static
If the player is using wings, this uses the result of GetWing, and calls ModItem.VerticalWingSpeeds then all GlobalItem.VerticalWingSpeeds hooks.
Definition at line 1317 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr, Terraria.ModLoader.EquipLoader.GetEquipTexture(), Terraria.ModLoader.Item, and Terraria.ModLoader.EquipTexture.VerticalWingSpeeds().
{
             Item item = GetWing(player);
             if (item == null) {
                 EquipTexture texture = EquipLoader.GetEquipTexture(EquipType.Wings, player.wingsLogic);
                 texture?.VerticalWingSpeeds(
                     player, ref ascentWhenFalling, ref ascentWhenRising, ref maxCanAscendMultiplier,
                     ref maxAscentMultiplier, ref constantAscend);
                 return;
             }
             item.modItem?.VerticalWingSpeeds(player, ref ascentWhenFalling, ref ascentWhenRising, ref maxCanAscendMultiplier,
                 ref maxAscentMultiplier, ref constantAscend);
             foreach (var g in HookVerticalWingSpeeds.arr)
                 g.Instance(item).VerticalWingSpeeds(item, player, ref ascentWhenFalling, ref ascentWhenRising,
                     ref maxCanAscendMultiplier, ref maxAscentMultiplier, ref constantAscend);
         }
static bool Terraria.ModLoader.ItemLoader.WingUpdate (Player player, bool inUse) static
If wings can be seen on the player, calls the player's wing's equipment texture's WingUpdate and all GlobalItem.WingUpdate hooks.
Definition at line 1361 of file ItemLoader.cs.
References Terraria.ModLoader.ItemLoader.HookList.arr, Terraria.ModLoader.EquipLoader.GetEquipTexture(), Terraria.ModLoader.Item, and Terraria.ModLoader.EquipTexture.WingUpdate().
{
             if (player.wings <= 0)
                 return false;
             EquipTexture texture = EquipLoader.GetEquipTexture(EquipType.Wings, player.wings);
             bool? retVal = texture?.WingUpdate(player, inUse);
             foreach (var g in HookWingUpdate.arr)
                 retVal |= g.WingUpdate(player.wings, player, inUse);
             return retVal ?? false;
         }
Member Data Documentation
HookList Terraria.ModLoader.ItemLoader.HookAllowPrefix = AddHook<Func<Item, int, bool>>(g => g.AllowPrefix) static private
Definition at line 288 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookAltFunctionUse = AddHook<Func<Item, Player, bool>>(g => g.AltFunctionUse) static private
Definition at line 844 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookAnglerChat = AddHook<DelegateAnglerChat>(g => g.AnglerChat) static private
Definition at line 1659 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookArmorArmGlowMask = AddHook<DelegateArmorArmGlowMask>(g => g.ArmorArmGlowMask) static private
Definition at line 1272 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookArmorSetShadows = AddHook<Action<Player, string>>(g => g.ArmorSetShadows) static private
Definition at line 993 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookCanBurnInLava = AddHook<Func<Item, bool>>(g => g.CanBurnInLava) static private
Definition at line 1388 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookCanEquipAccessory = AddHook<Func<Item, Player, int, bool>>(g => g.CanEquipAccessory) static private
Definition at line 1602 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookCanHitNPC = AddHook<Func<Item, Player, NPC, bool?>>(g => g.CanHitNPC) static private
Definition at line 657 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookCanHitPvp = AddHook<Func<Item, Player, Player, bool>>(g => g.CanHitPvp) static private
Definition at line 714 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookCanPickup = AddHook<Func<Item, Player, bool>>(g => g.CanPickup) static private
Definition at line 1440 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookCanRightClick = AddHook<Func<Item, bool>>(g => g.CanRightClick) static private
Definition at line 1032 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookCanUseItem = AddHook<Func<Item, Player, bool>>(g => g.CanUseItem) static private
Definition at line 300 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookCaughtFishStack = AddHook<DelegateCaughtFishStack>(g => g.CaughtFishStack) static private
Definition at line 1640 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookChoosePrefix = AddHook<Func<Item, UnifiedRandom, int>>(g => g.ChoosePrefix) static private
Definition at line 248 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookConsumeAmmo = AddHook<Func<Item, Player, bool>>(g => g.ConsumeAmmo) static private
Definition at line 563 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookConsumeItem = AddHook<Func<Item, Player, bool>>(g => g.ConsumeItem) static private
Definition at line 774 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookDrawArmorColor = AddHook<DelegateDrawArmorColor>(g => g.DrawArmorColor) static private
Definition at line 1258 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookDrawBody = AddHook<Func<int, bool>>(g => g.DrawBody) static private
Definition at line 1221 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookDrawHair = AddHook<DelegateDrawHair>(g => g.DrawHair) static private
Definition at line 1186 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookDrawHands = AddHook<DelegateDrawHands>(g => g.DrawHands) static private
Definition at line 1173 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookDrawHead = AddHook<Func<int, bool>>(g => g.DrawHead) static private
Definition at line 1202 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookDrawLegs = AddHook<Func<int, int, bool>>(g => g.DrawLegs) static private
Definition at line 1237 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookExtractinatorUse = AddHook<DelegateExtractinatorUse>(g => g.ExtractinatorUse) static private
Definition at line 1618 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookGetAlpha = AddHook<Func<Item, Color, Color?>>(g => g.GetAlpha) static private
Definition at line 1476 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookGetHealLife = AddHook<DelegateGetHealLife>(g => g.GetHealLife) static private
Definition at line 393 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookGetHealMana = AddHook<DelegateGetHealMana>(g => g.GetHealMana) static private
Definition at line 408 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookGetWeaponCrit = AddHook<DelegateGetWeaponCrit>(g => g.GetWeaponCrit) static private
Definition at line 522 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookGetWeaponDamage = AddHook<DelegateGetWeaponDamage>(g => g.GetWeaponDamage) static private
Definition at line 470 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookGetWeaponKnockback = AddHook<DelegateGetWeaponKnockback>(g => g.GetWeaponKnockback) static private
Definition at line 506 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookGrabRange = AddHook<DelegateGrabRange>(g => g.GrabRange) static private
Definition at line 1413 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookGrabStyle = AddHook<Func<Item, Player, bool>>(g => g.GrabStyle) static private
Definition at line 1426 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookHoldItem = AddHook<Action<Item, Player>>(g => g.HoldItem) static private
Definition at line 351 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookHoldItemFrame = AddHook<Func<Item, Player, bool>>(g => g.HoldItemFrame) static private
Definition at line 824 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookHoldoutOffset = AddHook<Func<int, Vector2?>>(g => g.HoldoutOffset) static private
Definition at line 1562 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookHoldoutOrigin = AddHook<Func<int, Vector2?>>(g => g.HoldoutOrigin) static private
Definition at line 1581 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookHoldStyle = AddHook<Action<Item, Player>>(g => g.HoldStyle) static private
Definition at line 336 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookHorizontalWingSpeeds = AddHook<DelegateHorizontalWingSpeeds>(g => g.HorizontalWingSpeeds) static private
Definition at line 1337 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookIsAnglerQuestAvailable = AddHook<Func<int, bool>>(g => g.IsAnglerQuestAvailable) static private
Definition at line 1648 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookItemSpace = AddHook<Func<Item, Player, bool>>(g => g.ItemSpace) static private
Definition at line 1465 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookMeleeEffects = AddHook<Action<Item, Player, Rectangle>>(g => g.MeleeEffects) static private
Definition at line 644 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookMeleeSpeedMultiplier = AddHook<Func<Item, Player, float>>(g => g.MeleeSpeedMultiplier) static private
Definition at line 379 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookModifyHitNPC = AddHook<DelegateModifyHitNPC>(g => g.ModifyHitNPC) static private
Definition at line 688 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookModifyHitPvp = AddHook<DelegateModifyHitPvp>(g => g.ModifyHitPvp) static private
Definition at line 729 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookModifyManaCost = AddHook<DelegateModifyManaCost>(g => g.ModifyManaCost) static private
Definition at line 423 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookModifyTooltips = AddHook<Action<Item, List<TooltipLine>>>(g => g.ModifyTooltips) static private
Definition at line 1717 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookModifyWeaponDamage = AddHook<DelegateModifyWeaponDamage>(g => g.ModifyWeaponDamage) static private
Definition at line 488 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookModifyWeaponDamageOld = AddHook<DelegateModifyWeaponDamage>(g => g.ModifyWeaponDamage) static private
Definition at line 486 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookNeedsSaving = AddHook<Func<Item, bool>>(g => g.NeedsSaving) static private
Definition at line 1753 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookOldPickAmmo = AddHook<DelegateOldPickAmmo>(g => g.PickAmmo) static private
Definition at line 544 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookOnConsumeAmmo = AddHook<Action<Item, Player>>(g => g.OnConsumeAmmo) static private
Definition at line 583 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookOnConsumeItem = AddHook<Action<Item, Player>>(g => g.OnConsumeItem) static private
Definition at line 793 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookOnConsumeMana = AddHook<Action<Item, Player, int>>(g => g.OnConsumeMana) static private
Definition at line 453 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookOnCraft = AddHook<Action<Item, Recipe>>(g => g.OnCraft) static private
Definition at line 1674 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookOnHitNPC = AddHook<Action<Item, Player, NPC, int, float, bool>>(g => g.OnHitNPC) static private
Definition at line 701 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookOnHitPvp = AddHook<Action<Item, Player, Player, int, bool>>(g => g.OnHitPvp) static private
Definition at line 742 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookOnMissingMana = AddHook<Action<Item, Player, int>>(g => g.OnMissingMana) static private
Definition at line 438 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookOnPickup = AddHook<Func<Item, Player, bool>>(g => g.OnPickup) static private
Definition at line 1451 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookOpenVanillaBag = AddHook<Action<string, Player, int>>(g => g.OpenVanillaBag) static private
Definition at line 1125 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookPickAmmo = AddHook<DelegatePickAmmo>(g => g.PickAmmo) static private
Definition at line 547 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookPostDrawInInventory = AddHook<Action<Item, SpriteBatch, Vector2, Rectangle, Color, Color, Vector2, float>>(g => g.PostDrawInInventory) static private
Definition at line 1547 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookPostDrawInWorld = AddHook<Action<Item, SpriteBatch, Color, Color, float, float, int>>(g => g.PostDrawInWorld) static private
Definition at line 1515 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookPostDrawTooltip = AddHook<DelegatePostDrawTooltip>(g => g.PostDrawTooltip) static private
Definition at line 1692 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookPostDrawTooltipLine = AddHook<DelegatePostDrawTooltipLine>(g => g.PostDrawTooltipLine) static private
Definition at line 1710 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookPostReforge = AddHook<Action<Item>>(g => g.PostReforge) static private
Definition at line 1162 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookPostUpdate = AddHook<Action<Item>>(g => g.PostUpdate) static private
Definition at line 1401 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookPreDrawInInventory = AddHook<Func<Item, SpriteBatch, Vector2, Rectangle, Color, Color, Vector2, float, bool>>(g => g.PreDrawInInventory) static private
Definition at line 1528 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookPreDrawInWorld = AddHook<DelegatePreDrawInWorld>(g => g.PreDrawInWorld) static private
Definition at line 1498 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookPreDrawTooltip = AddHook<DelegatePreDrawTooltip>(g => g.PreDrawTooltip) static private
Definition at line 1682 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookPreDrawTooltipLine = AddHook<DelegatePreDrawTooltipLine>(g => g.PreDrawTooltipLine) static private
Definition at line 1700 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookPrefixChance = AddHook<Func<Item, int, UnifiedRandom, bool?>>(g => g.PrefixChance) static private
Definition at line 266 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookPreOpenVanillaBag = AddHook<Func<string, Player, int, bool>>(g => g.PreOpenVanillaBag) static private
Definition at line 1104 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookPreReforge = AddHook<Func<Item, bool>>(g => g.NewPreReforge) static private
Definition at line 1151 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookPreUpdateVanitySet = AddHook<Action<Player, string>>(g => g.PreUpdateVanitySet) static private
Definition at line 943 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookReforgePrice = AddHook<DelegateReforgePrice>(g => g.ReforgePrice) static private
Definition at line 1137 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookRightClick = AddHook<Action<Item, Player>>(g => g.RightClick) static private
Definition at line 1052 of file ItemLoader.cs.
List<HookList> Terraria.ModLoader.ItemLoader.hooks = new List<HookList>() static private
Definition at line 44 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookSetDefaults = AddHook<Action<Item>>(g => g.SetDefaults) static private
Definition at line 194 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookSetMatch = AddHook<DelegateSetMatch>(g => g.SetMatch) static private
Definition at line 1020 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookShoot = AddHook<DelegateShoot>(g => g.Shoot) static private
Definition at line 601 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookUpdate = AddHook<DelegateUpdate>(g => g.Update) static private
Definition at line 1375 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookUpdateAccessory = AddHook<Action<Item, Player, bool>>(g => g.UpdateAccessory) static private
Definition at line 894 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookUpdateArmorSet = AddHook<Action<Player, string>>(g => g.UpdateArmorSet) static private
Definition at line 921 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookUpdateEquip = AddHook<Action<Item, Player>>(g => g.UpdateEquip) static private
Definition at line 878 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookUpdateInventory = AddHook<Action<Item, Player>>(g => g.UpdateInventory) static private
Definition at line 862 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookUpdateVanitySet = AddHook<Action<Player, string>>(g => g.UpdateVanitySet) static private
Definition at line 968 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookUseItem = AddHook<Func<Item, Player, bool>>(g => g.UseItem) static private
Definition at line 755 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookUseItemFrame = AddHook<Func<Item, Player, bool>>(g => g.UseItemFrame) static private
Definition at line 807 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookUseItemHitbox = AddHook<DelegateUseItemHitbox>(g => g.UseItemHitbox) static private
Definition at line 631 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookUseStyle = AddHook<Action<Item, Player>>(g => g.UseStyle) static private
Definition at line 321 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookUseTimeMultiplier = AddHook<Func<Item, Player, float>>(g => g.UseTimeMultiplier) static private
Definition at line 366 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookVerticalWingSpeeds = AddHook<DelegateVerticalWingSpeeds>(g => g.VerticalWingSpeeds) static private
Definition at line 1311 of file ItemLoader.cs.
HookList Terraria.ModLoader.ItemLoader.HookWingUpdate = AddHook<Func<int, Player, bool, bool>>(g => g.WingUpdate) static private
Definition at line 1357 of file ItemLoader.cs.
int Terraria.ModLoader.ItemLoader.ItemCount => nextItem static
Definition at line 80 of file ItemLoader.cs.
Referenced by Terraria.ModLoader.RecipeEditor.AddIngredient(), Terraria.ModLoader.RecipeFinder.AddIngredient(), Terraria.ModLoader.RecipeEditor.DeleteIngredient(), Terraria.ModLoader.RecipeEditor.SetIngredientStack(), Terraria.ModLoader.RecipeFinder.SetResult(), and Terraria.ModLoader.RecipeEditor.SetResult().
int Terraria.ModLoader.ItemLoader.nextItem = ItemID.Count static private
Definition at line 23 of file ItemLoader.cs.