Terraria ModLoader: Terraria.ModLoader.Mod Class Reference
Terraria.ModLoader.Mod Class Reference
Mod is an abstract class that you will override. It serves as a central place from which the mod's contents are stored. It provides methods for you to use or override.
Public Member Functions
void AddBackgroundTexture (string texture)
Adds a texture to the list of background textures and assigns it a background texture slot.
void AddBossHeadTexture (string texture, int npcType=-1)
Assigns a head texture that can be used by NPCs on the map.
void AddBuff (string name, ModBuff buff, string texture)
Adds a type of buff to the game with the specified internal name and texture.
void AddCommand (string name, ModCommand mc)
Manually add a Command during Load
void AddConfig (string name, ModConfig mc)
void AddDust (string name, ModDust dust, string texture="")
Adds a type of dust to your mod with the specified name. Create an instance of ModDust normally, preferably through the constructor of an overriding class. Leave the texture as an empty string to use the vanilla dust sprite sheet.
int AddEquipTexture (ModItem item, EquipType type, string name, string texture, string armTexture="", string femaleTexture="")
Adds an equipment texture of the specified type, internal name, and associated item to your mod. (The item parameter may be null if you don't want to associate an item with the texture.) You can then get the ID for your texture by calling EquipLoader.GetEquipTexture, and using the EquipTexture's Slot property. If the EquipType is EquipType.Body, make sure that you also provide an armTexture and a femaleTexture. Returns the ID / slot that is assigned to the equipment texture.
int AddEquipTexture (EquipTexture equipTexture, ModItem item, EquipType type, string name, string texture, string armTexture="", string femaleTexture="")
Adds an equipment texture of the specified type, internal name, and associated item to your mod. This method is different from the other AddEquipTexture in that you can specify the class of the equipment texture, thus allowing you to override EquipmentTexture's hooks. All other parameters are the same as the other AddEquipTexture.
void AddGlobalBgStyle (string name, GlobalBgStyle globalBgStyle)
Adds the given global background style with the given name to this mod.
void AddGlobalBuff (string name, GlobalBuff globalBuff)
Adds the given GlobalBuff instance to this mod using the provided name.
void AddGlobalItem (string name, GlobalItem globalItem)
Adds the given GlobalItem instance to this mod with the provided name.
void AddGlobalNPC (string name, GlobalNPC globalNPC)
Adds the given GlobalNPC instance to this mod with the provided name.
void AddGlobalProjectile (string name, GlobalProjectile globalProjectile)
Adds the given GlobalProjectile instance to this mod with the provided name.
void AddGlobalRecipe (string name, GlobalRecipe globalRecipe)
Manually add a Global Recipe during Load
void AddGlobalTile (string name, GlobalTile globalTile)
Adds the given GlobalTile instance to this mod with the provided name.
void AddGlobalWall (string name, GlobalWall globalWall)
Adds the given GlobalWall instance to this mod with the provided name.
void AddGore (string texture, ModGore modGore=null)
Adds the given texture to the game as a custom gore, with the given custom gore behavior. If no custom gore behavior is provided, the custom gore will have the default vanilla behavior.
void AddItem (string name, ModItem item)
Adds a type of item to your mod with the specified internal name. This method should be called in Load. You can obtain an instance of ModItem by overriding it then creating an instance of the subclass.
void AddModWorld (string name, ModWorld modWorld)
Adds a ModWorld to this mod with the given name.
void AddMount (string name, ModMountData mount, string texture, IDictionary< MountTextureType, string > extraTextures=null)
Adds the given mount to the game with the given name and texture. The extraTextures dictionary should optionally map types of mount textures to the texture paths you want to include.
void AddMusicBox (int musicSlot, int itemType, int tileType, int tileFrameY=0)
Allows you to tie a music ID, and item ID, and a tile ID together to form a music box. When music with the given ID is playing, equipped music boxes have a chance to change their ID to the given item type. When an item with the given item type is equipped, it will play the music that has musicSlot as its ID. When a tile with the given type and Y-frame is nearby, if its X-frame is >= 36, it will play the music that has musicSlot as its ID.
void AddNPC (string name, ModNPC npc)
Adds a type of NPC to the game with the specified name and texture. Also allows you to give the NPC alternate textures.
void AddNPCHeadTexture (int npcType, string texture)
Assigns a head texture to the given town NPC type.
void AddPlayer (string name, ModPlayer player)
Adds a type of ModPlayer to this mod. All ModPlayer types will be newly created and attached to each player that is loaded.
void AddPrefix (string name, ModPrefix prefix)
Adds a prefix to your mod with the specified internal name. This method should be called in Load. You can obtain an instance of ModPrefix by overriding it then creating an instance of the subclass.
void AddProjectile (string name, ModProjectile projectile)
Adds a type of projectile to the game with the specified name.
virtual void AddRecipeGroups ()
Override this method to add recipe groups to this mod. You must add recipe groups by calling the RecipeGroup.RegisterGroup method here. A recipe group is a set of items that can be used interchangeably in the same recipe.
virtual void AddRecipes ()
Override this method to add recipes to the game. It is recommended that you do so through instances of ModRecipe, since it provides methods that simplify recipe creation.
void AddSound (SoundType type, string soundPath, ModSound modSound=null)
Adds the given sound file to the game as the given type of sound and with the given custom sound playing. If no ModSound instance is provided, the custom sound will play in a similar manner as the default vanilla ones.
void AddSurfaceBgStyle (string name, ModSurfaceBgStyle surfaceBgStyle)
Adds the given surface background style with the given name to this mod.
void AddTexture (string name, Texture2D texture)
Shorthand for calling ModLoader.AddTexture(this.FileName(name), texture).
void AddTile (string name, ModTile tile, string texture)
Adds a type of tile to the game with the specified name and texture.
void AddTileEntity (string name, ModTileEntity entity)
Manually add a tile entity during Load.
void AddTranslation (ModTranslation translation)
Adds a ModTranslation to the game so that you can use Language.GetText to get a LocalizedText.
void AddUgBgStyle (string name, ModUgBgStyle ugBgStyle)
Adds the given underground background style with the given name to this mod.
void AddWall (string name, ModWall wall, string texture)
Adds a type of wall to the game with the specified name and texture.
void AddWaterfallStyle (string name, ModWaterfallStyle waterfallStyle, string texture)
Adds the given waterfall style to the game with the given name and texture path.
void AddWaterStyle (string name, ModWaterStyle waterStyle, string texture, string blockTexture)
Adds the given water style to the game with the given name, texture path, and block texture path.
int BuffType (string name)
Gets the type of the ModBuff of this mod corresponding to the given name. Returns 0 if no ModBuff with the given name is found.
int BuffType< T > ()
Same as the other BuffType, but assumes that the class name and internal name are the same.
virtual object Call (params object[] args)
Used for weak inter-mod communication. This allows you to interact with other mods without having to reference their types or namespaces, provided that they have implemented this method.
virtual void Close ()
Close is called before Unload, and may be called at any time when mod unloading is imminent (such as when downloading an update, or recompiling) Use this to release any additional file handles, or stop streaming music. Make sure to call base.Close() at the end May be called multiple times before Unload
ModTranslation CreateTranslation (string key)
Creates a ModTranslation object that you can use in AddTranslation.
int DustType (string name)
Gets the type of the ModDust of this mod with the given name. Returns 0 if no ModDust with the given name is found.
int DustType< T > ()
Same as the other DustType, but assumes that the class name and internal name are the same.
bool EffectExists (string name)
Used to check if a custom Effect exists
bool FileExists (string name)
Shorthand for calling ModLoader.FileExists(this.FileName(name)). Note that file extensions are used here.
bool FontExists (string name)
Used to check if a custom SpriteFont exists
sbyte GetAccessorySlot (string name, EquipType type)
Same as GetEquipSlot, except returns the number as an sbyte (signed byte) for your convenience.
int GetBackgroundSlot (string name)
Gets the texture slot corresponding to the specified texture name. Shorthand for calling BackgroundTextureLoader.GetBackgroundSlot(this.Name + '/' + name).
ModBuff GetBuff (string name)
Gets the ModBuff of this mod corresponding to the given name. Returns null if no ModBuff with the given name is found.
T GetBuff< T > ()
ModConfig GetConfig (string name)
T GetConfig< T > ()
ModDust GetDust (string name)
Gets the ModDust of this mod corresponding to the given name. Returns null if no ModDust with the given name is found.
T GetDust< T > ()
Same as the other GetDust, but assumes that the class name and internal name are the same.
Effect GetEffect (string name)
Gets an Effect loaded from the specified path.
int GetEquipSlot (string name, EquipType type)
Gets the slot/ID of the equipment texture corresponding to the given name. Returns -1 if no EquipTexture with the given name is found.
EquipTexture GetEquipTexture (string name, EquipType type)
Gets the EquipTexture instance corresponding to the name and EquipType. Returns null if no EquipTexture with the given name and EquipType is found.
byte[] GetFileBytes (string name)
Retrieve contents of files within the tmod file
Stream GetFileStream (string name, bool newFileStream=false)
Retrieve contents of files within the tmod file
DynamicSpriteFont GetFont (string name)
Gets a SpriteFont loaded from the specified path.
GlobalBgStyle GetGlobalBgStyle (string name)
Returns the global background style corresponding to the given name.
T GetGlobalBgStyle< T > ()
GlobalBuff GetGlobalBuff (string name)
Gets the GlobalBuff with the given name from this mod.
T GetGlobalBuff< T > ()
GlobalItem GetGlobalItem (string name)
Gets the GlobalItem instance with the given name from this mod.
T GetGlobalItem< T > ()
Same as the other GetGlobalItem, but assumes that the class name and internal name are the same.
GlobalNPC GetGlobalNPC (string name)
Gets the GlobalNPC instance with the given name from this mod.
T GetGlobalNPC< T > ()
GlobalProjectile GetGlobalProjectile (string name)
Gets the GlobalProjectile instance with the given name from this mod.
T GetGlobalProjectile< T > ()
GlobalRecipe GetGlobalRecipe (string name)
Gets the global recipe corresponding to the specified name.
T GetGlobalRecipe< T > ()
GlobalTile GetGlobalTile (string name)
Gets the GlobalTile instance with the given name from this mod.
T GetGlobalTile< T > ()
Same as the other GetGlobalTile, but assumes that the class name and internal name are the same.
GlobalWall GetGlobalWall (string name)
Gets the GlobalWall instance with the given name from this mod.
T GetGlobalWall< T > ()
int GetGoreSlot (string name)
Shorthand for calling ModGore.GetGoreSlot(this.Name + '/' + name).
int GetGoreSlot< T > ()
Same as the other GetGoreSlot, but assumes that the class name and internal name are the same.
ModItem GetItem (string name)
Gets the ModItem instance corresponding to the name. Because this method is in the Mod class, conflicts between mods are avoided. Returns null if no ModItem with the given name is found.
T GetItem< T > ()
Same as the other GetItem, but assumes that the class name and internal name are the same.
LegacySoundStyle GetLegacySoundSlot (SoundType type, string name)
Shorthand for calling SoundLoader.GetLegacySoundSlot(type, this.Name + '/' + name).
ModWorld GetModWorld (string name)
Gets the ModWorld instance with the given name from this mod.
T GetModWorld< T > ()
Same as the other GetModWorld, but assumes that the class name and internal name are the same.
ModMountData GetMount (string name)
Gets the ModMountData instance of this mod corresponding to the given name. Returns null if no ModMountData has the given name.
T GetMount< T > ()
Music GetMusic (string name)
Shorthand for calling ModContent.GetMusic(this.FileName(name)).
ModNPC GetNPC (string name)
Gets the ModNPC of this mod corresponding to the given name. Returns null if no ModNPC with the given name is found.
T GetNPC< T > ()
ModPacket GetPacket (int capacity=256)
Creates a ModPacket object that you can write to and then send between servers and clients.
ModPlayer GetPlayer (string name)
Gets the ModPlayer of this mod corresponding to the given name. Returns null if no ModPlayer with the given name is found.
T GetPlayer< T > ()
ModPrefix GetPrefix (string name)
Gets the ModPrefix instance corresponding to the name. Because this method is in the Mod class, conflicts between mods are avoided. Returns null if no ModPrefix with the given name is found.
T GetPrefix< T > ()
Same as the other GetPrefix, but assumes that the class name and internal name are the same.
ModProjectile GetProjectile (string name)
Gets the ModProjectile of this mod corresponding to the given name. Returns null if no ModProjectile with the given name is found.
T GetProjectile< T > ()
SoundEffect GetSound (string name)
Shorthand for calling ModContent.GetSound(this.FileName(name)).
int GetSoundSlot (SoundType type, string name)
Shorthand for calling SoundLoader.GetSoundSlot(type, this.Name + '/' + name).
ModSurfaceBgStyle GetSurfaceBgStyle (string name)
Returns the surface background style corresponding to the given name.
T GetSurfaceBgStyle< T > ()
int GetSurfaceBgStyleSlot (string name)
Returns the Slot of the surface background style corresponding to the given name.
int GetSurfaceBgStyleSlot< T > ()
Texture2D GetTexture (string name)
Shorthand for calling ModContent.GetTexture(this.FileName(name)).
ModTile GetTile (string name)
Gets the ModTile of this mod corresponding to the given name. Returns null if no ModTile with the given name is found.
T GetTile< T > ()
Same as the other GetTile, but assumes that the class name and internal name are the same.
ModTileEntity GetTileEntity (string name)
Gets the ModTileEntity of this mod corresponding to the given name. Returns null if no ModTileEntity with the given name is found.
T GetTileEntity< T > ()
Same as the other GetTileEntity, but assumes that the class name and internal name are the same.
ModUgBgStyle GetUgBgStyle (string name)
Returns the underground background style corresponding to the given name.
T GetUgBgStyle< T > ()
ModWall GetWall (string name)
Gets the ModWall of this mod corresponding to the given name. Returns null if no ModWall with the given name is found.
T GetWall< T > ()
ModWaterfallStyle GetWaterfallStyle (string name)
Returns the waterfall style with the given name from this mod.
T GetWaterfallStyle< T > ()
int GetWaterfallStyleSlot (string name)
Returns the waterfall style corresponding to the given name.
int GetWaterfallStyleSlot< T > ()
ModWaterStyle GetWaterStyle (string name)
Returns the water style with the given name from this mod.
T GetWaterStyle< T > ()
virtual void HandlePacket (BinaryReader reader, int whoAmI)
Called whenever a net message / packet is received from a client (if this is a server) or the server (if this is a client). whoAmI is the ID of whomever sent the packet (equivalent to the Main.myPlayer of the sender), and reader is used to read the binary data of the packet.
virtual bool HijackGetData (ref byte messageType, ref BinaryReader reader, int playerNumber)
Allows you to modify net message / packet information that is received before the game can act on it.
virtual bool HijackSendData (int whoAmI, int msgType, int remoteClient, int ignoreClient, NetworkText text, int number, float number2, float number3, float number4, int number5, int number6, int number7)
Hijacks the send data method. Only use if you absolutely know what you are doing. If any hooks return true, the message is not sent.
virtual void HotKeyPressed (string name)
Called when a hotkey is pressed. Check against the name to verify particular hotkey that was pressed. (Using the ModHotKey is more recommended.)
int ItemType (string name)
Gets the internal ID / type of the ModItem corresponding to the name. Returns 0 if no ModItem with the given name is found.
int ItemType< T > ()
Same as the other ItemType, but assumes that the class name and internal name are the same.
virtual void Load ()
Override this method to add most of your content to your mod. Here you will call other methods such as AddItem. This is guaranteed to be called after all content has been autoloaded.
virtual bool LoadResource (string path, int length, Func< Stream > getStream)
Hook for pre-loading resources
virtual void LoadResourceFromStream (string path, int len, BinaryReader reader)
virtual void LoadResources ()
virtual void MidUpdateDustTime ()
Called after Dust got updated, but before Time (day/night, events, etc.) gets updated.
virtual void MidUpdateGoreProjectile ()
Called after Gores got updated, but before any Projectiles get updated.
virtual void MidUpdateInvasionNet ()
Called after Invasions got updated. The only thing that is updated after this is the Network.
virtual void MidUpdateItemDust ()
Called after Items got updated, but before any Dust gets updated.
virtual void MidUpdateNPCGore ()
Called after NPCs got updated, but before any Gores get updated.
virtual void MidUpdatePlayerNPC ()
Called after Players got updated, but before any NPCs get updated.
virtual void MidUpdateProjectileItem ()
Gets called immediately after all Projectiles are updated, but before any Items get updated.
virtual void MidUpdateTimeWorld ()
Called after Time got updated, but before the World gets updated.
virtual void ModifyInterfaceLayers (List< GameInterfaceLayer > layers)
Allows you to modify the elements of the in-game interface that get drawn. GameInterfaceLayer can be found in the Terraria.UI namespace. Check https://github.com/tModLoader/tModLoader/wiki/Vanilla-Interface-layers-values for vanilla interface layer names
virtual void ModifyLightingBrightness (ref float scale)
Allows you to modify overall brightness of lights. Can be used to create effects similiar to what night vision and darkness (de)buffs give you. Values too high or too low might result in glitches. For night vision effect use scale 1.03
virtual void ModifySunLightColor (ref Color tileColor, ref Color backgroundColor)
Allows you to modify color of light the sun emits.
virtual void ModifyTransformMatrix (ref SpriteViewMatrix Transform)
Allows you to set the transformation of the screen that is drawn. (Translations, rotations, scales, etc.)
int MountType (string name)
Gets the ID of the ModMountData instance corresponding to the given name. Returns 0 if no ModMountData has the given name.
int MountType< T > ()
Same as the other MountType, but assumes that the class name and internal name are the same.
bool MusicExists (string name)
Shorthand for calling ModLoader.MusicExists(this.FileName(name)).
int NPCType (string name)
Gets the type of the ModNPC of this mod with the given name. Returns 0 if no ModNPC with the given name is found.
int NPCType< T > ()
Same as the other NPCType, but assumes that the class name and internal name are the same.
virtual void PostAddRecipes ()
This provides a hook into the mod-loading process immediately after recipes have been added. You can use this to edit recipes added by other mods.
virtual void PostDrawFullscreenMap (ref string mouseText)
Called while the fullscreen map is active. Allows custom drawing to the map.
virtual void PostDrawInterface (SpriteBatch spriteBatch)
Called after interface is drawn but right before mouse and mouse hover text is drawn. Allows for drawing interface.
virtual void PostSetupContent ()
Allows you to load things in your mod after its content has been setup (arrays have been resized to fit the content, etc).
virtual void PostUpdateEverything ()
Called after the Network got updated, this is the last hook that happens in an update.
virtual void PostUpdateInput ()
Called after the input keys are polled. Allows for modifying things like scroll wheel if your custom drawing should capture that.
byte PrefixType (string name)
Gets the internal ID / type of the ModPrefix corresponding to the name. Returns 0 if no ModPrefix with the given name is found.
byte PrefixType< T > ()
Same as the other PrefixType, but assumes that the class name and internal name are the same.
virtual void PreSaveAndQuit ()
Called in SP or Client when the Save and Quit button is pressed. One use for this hook is clearing out custom UI slots to return items to the player.
virtual void PreUpdateEntities ()
Use this if you want to do something before anything in the World gets updated. Called after UI updates, but before anything in the World (Players, NPCs, Projectiles, Tiles) gets updated.
int ProjectileType (string name)
Gets the type of the ModProjectile of this mod with the given name. Returns 0 if no ModProjectile with the given name is found.
int ProjectileType< T > ()
Same as the other ProjectileType, but assumes that the class name and internal name are the same.
ModHotKey RegisterHotKey (string name, string defaultKey)
Registers a hotkey with a name and defaultKey. Use the returned ModHotKey to detect when buttons are pressed. Do this in a ModPlayer.ProcessTriggers.
bool SoundExists (string name)
Shorthand for calling ModLoader.SoundExists(this.FileName(name)).
bool TextureExists (string name)
Shorthand for calling ModLoader.TextureExists(this.FileName(name)).
int TileEntityType (string name)
Gets the type of the ModTileEntity of this mod with the given name. Returns -1 if no ModTileEntity with the given name is found.
int TileEntityType< T > ()
Same as the other TileEntityType, but assumes that the class name and internal name are the same.
int TileType (string name)
Gets the type of the ModTile of this mod with the given name. Returns 0 if no ModTile with the given name is found.
int TileType< T > ()
Same as the other TileType, but assumes that the class name and internal name are the same.
virtual void Unload ()
This is called whenever this mod is unloaded from the game. Use it to undo changes that you've made in Load that aren't automatically handled (for example, modifying the texture of a vanilla item). Mods are guaranteed to be unloaded in the reverse order they were loaded in.
virtual void UpdateMusic (ref int music, ref MusicPriority priority)
Allows you to determine what music should currently play.
virtual void UpdateMusic (ref int music)
A legacy hook that you should no longer use. Use the version with two parameters instead.
virtual void UpdateUI (GameTime gameTime)
Ran every update and suitable for calling Update for UserInterface classes
int WallType (string name)
Gets the type of the ModWall of this mod with the given name. Returns 0 if no ModWall with the given name is found.
int WallType< T > ()
Same as the other WallType, but assumes that the class name and internal name are the same.
Public Attributes
bool IsNetSynced => netID >= 0
virtual string Name => File.name
Stores the name of the mod. This name serves as the mod's identification, and also helps with saving everything your mod adds. By default this returns the name of the folder that contains all your code and stuff.
virtual Version Version => File.version
This version number of this mod.
Properties
Assembly Code [get, set]
The assembly code this is loaded when tModLoader loads this mod.
string DisplayName [get, set]
The display name of this mod in the Mods menu.
virtual uint ExtraPlayerBuffSlots [get]
The amount of extra buff slots this mod desires for Players. This value is checked after Mod.Load but before Mod.PostSetupContent. The actual number of buffs the player can use will be 22 plus the max value of all enabled mods. In-game use Player.MaxBuffs to check the maximum number of buffs.
ILog Logger [get, set]
A logger with this mod's name for easy logging.
ModProperties Properties [get, protected set]
ModSide Side = ModProperties.AutoLoadAll [get, set]
The ModSide that controls how this mod is synced between client and server.
Version tModLoaderVersion [get, set]
The version of tModLoader that was being used when this mod was built.
Private Member Functions
void AutoloadBackgrounds ()
void AutoloadBuff (Type type)
void AutoloadCommand (Type type)
void AutoloadDust (Type type)
void AutoloadGlobalBgStyle (Type type)
void AutoloadGlobalBuff (Type type)
void AutoloadGlobalItem (Type type)
void AutoloadGlobalNPC (Type type)
void AutoloadGlobalProjectile (Type type)
void AutoloadGlobalRecipe (Type type)
void AutoloadGlobalTile (Type type)
void AutoloadGlobalWall (Type type)
void AutoloadGores (IList< Type > modGores)
void AutoloadItem (Type type)
void AutoloadLocalization ()
Loads .lang files
void AutoloadModWorld (Type type)
void AutoloadMountData (Type type)
void AutoloadNPC (Type type)
void AutoloadPlayer (Type type)
void AutoloadPrefix (Type type)
void AutoloadProjectile (Type type)
void AutoloadSounds (IList< Type > modSounds)
void AutoloadSurfaceBgStyle (Type type)
void AutoloadTile (Type type)
void AutoloadTileEntity (Type type)
void AutoloadUgBgStyle (Type type)
void AutoloadWall (Type type)
void AutoloadWaterfallStyle (Type type)
void AutoloadWaterStyle (Type type)
Music LoadMusic (string path, string extension)
bool LoadResourceLegacy (string path, int length, Func< Stream > getStream)
SoundEffect LoadSound (Stream stream, int length, string extension)
void LoadTexture (string path, Stream stream, bool rawimg)
Private Attributes
readonly Queue< Task > AsyncLoadQueue = new Queue<Task>()
IDisposable fileHandle
Detailed Description
Mod is an abstract class that you will override. It serves as a central place from which the mod's contents are stored. It provides methods for you to use or override.
Definition at line 24 of file Mod.cs.
Member Function Documentation
void Terraria.ModLoader.Mod.AddBackgroundTexture (string texture)
Adds a texture to the list of background textures and assigns it a background texture slot.
Parameters
texture The texture.
Definition at line 1393 of file Mod.cs.
References Terraria.ModLoader.BackgroundTextureLoader.GetBackgroundSlot(), and Terraria.ModLoader.ModContent.GetTexture().
{
             if (!loading)
                 throw new Exception("AddBackgroundTexture can only be called from Mod.Load or Mod.Autoload");
             BackgroundTextureLoader.backgrounds[texture] = BackgroundTextureLoader.ReserveBackgroundSlot();
             ModContent.GetTexture(texture);
         }
void Terraria.ModLoader.Mod.AddBossHeadTexture (string texture, int npcType = -1)
Assigns a head texture that can be used by NPCs on the map.
Parameters
texture The texture.
npcType An optional npc id for NPCID.Sets.BossHeadTextures
Definition at line 931 of file Mod.cs.
References Terraria.ModLoader.ModContent.GetTexture().
{
             if (!loading)
                 throw new Exception("AddBossHeadTexture can only be called from Mod.Load or Mod.Autoload");
             int slot = NPCHeadLoader.ReserveBossHeadSlot(texture);
             NPCHeadLoader.bossHeads[texture] = slot;
             ModContent.GetTexture(texture);
             if (npcType >= 0) {
                 NPCHeadLoader.npcToBossHead[npcType] = slot;
             }
         }
void Terraria.ModLoader.Mod.AddBuff (string name, ModBuff buff, string texture)
Adds a type of buff to the game with the specified internal name and texture.
Parameters
name The name.
buff The buff.
texture The texture.
Definition at line 976 of file Mod.cs.
References Terraria.ModLoader.ModBuff.Description, Terraria.ModLoader.ModBuff.DisplayName, Terraria.ModLoader.ModBuff.mod, Terraria.ModLoader.ModBuff.Name, and Terraria.ModLoader.ModBuff.Type.
{
             if (!loading)
                 throw new Exception("AddBuff can only be called from Mod.Load or Mod.Autoload");
             if (buffs.ContainsKey(name))
                 throw new Exception("You tried to add 2 ModBuff with the same name: " + name + ". Maybe 2 classes share a classname but in different namespaces while autoloading or you manually called AddBuff with 2 buffs of the same name.");
             buff.mod = this;
             buff.Name = name;
             buff.Type = BuffLoader.ReserveBuffID();
             buff.texture = texture;
             buff.DisplayName = GetOrCreateTranslation(string.Format("Mods.{0}.BuffName.{1}", Name, name));
             buff.Description = GetOrCreateTranslation(string.Format("Mods.{0}.BuffDescription.{1}", Name, name));
             buffs[name] = buff;
             BuffLoader.buffs.Add(buff);
             ContentInstance.Register(buff);
         }
void Terraria.ModLoader.Mod.AddCommand (string name, ModCommand mc)
Manually add a Command during Load
Definition at line 1438 of file Mod.cs.
References Terraria.ModLoader.ModCommand.mod, and Terraria.ModLoader.ModCommand.Name.
{
             if (!loading)
                 throw new Exception("AddCommand can only be called from Mod.Load or Mod.Autoload");
             mc.mod = this;
             mc.Name = name;
             CommandManager.Add(mc);
         }
void Terraria.ModLoader.Mod.AddConfig (string name, ModConfig mc)
Definition at line 225 of file Mod.cs.
References Terraria.ModLoader.Config.ModConfig.mod, and Terraria.ModLoader.Config.ModConfig.Name.
         {
             mc.Name = name;
             mc.mod = this;
             ConfigManager.Add(mc);
             ContentInstance.Register(mc);
         }
void Terraria.ModLoader.Mod.AddDust (string name, ModDust dust, string texture = "")
Adds a type of dust to your mod with the specified name. Create an instance of ModDust normally, preferably through the constructor of an overriding class. Leave the texture as an empty string to use the vanilla dust sprite sheet.
Parameters
name The name.
dust The dust.
texture The texture.
Definition at line 485 of file Mod.cs.
References Terraria.ModLoader.ModContent.GetTexture(), Terraria.ModLoader.ModDust.mod, Terraria.ModLoader.ModDust.Name, Terraria.ModLoader.ModDust.Texture, and Terraria.ModLoader.ModDust.Type.
{
             if (!loading)
                 throw new Exception("AddDust can only be called from Mod.Load or Mod.Autoload");
             dust.mod = this;
             dust.Name = name;
             dust.Type = ModDust.ReserveDustID();
             dust.Texture = !string.IsNullOrEmpty(texture) ? ModContent.GetTexture(texture) : Main.dustTexture;
             dusts[name] = dust;
             ModDust.dusts.Add(dust);
             ContentInstance.Register(dust);
         }
int Terraria.ModLoader.Mod.AddEquipTexture (ModItem item, EquipType type, string name, string texture, string armTexture = "", string femaleTexture = "")
Adds an equipment texture of the specified type, internal name, and associated item to your mod. (The item parameter may be null if you don't want to associate an item with the texture.) You can then get the ID for your texture by calling EquipLoader.GetEquipTexture, and using the EquipTexture's Slot property. If the EquipType is EquipType.Body, make sure that you also provide an armTexture and a femaleTexture. Returns the ID / slot that is assigned to the equipment texture.
Parameters
item The item.
type The type.
name The name.
texture The texture.
armTexture The arm texture (for body slots).
femaleTexture The female texture (for body slots), if missing the regular body texture is used.
Returns
Definition at line 345 of file Mod.cs.
{
             return AddEquipTexture(new EquipTexture(), item, type, name, texture, armTexture, femaleTexture);
         }
int Terraria.ModLoader.Mod.AddEquipTexture (EquipTexture equipTexture, ModItem item, EquipType type, string name, string texture, string armTexture = "", string femaleTexture = "")
Adds an equipment texture of the specified type, internal name, and associated item to your mod. This method is different from the other AddEquipTexture in that you can specify the class of the equipment texture, thus allowing you to override EquipmentTexture's hooks. All other parameters are the same as the other AddEquipTexture.
Parameters
equipTexture The equip texture.
item The item.
type The type.
name The name.
texture The texture.
armTexture The arm texture (for body slots).
femaleTexture The female texture (for body slots), if missing the regular body texture is used.
Returns
Definition at line 363 of file Mod.cs.
References Terraria.ModLoader.ModContent.GetTexture(), Terraria.ModLoader.ModItem.item, Terraria.ModLoader.EquipTexture.item, Terraria.ModLoader.EquipTexture.mod, Terraria.ModLoader.EquipTexture.Name, Terraria.ModLoader.EquipTexture.Slot, Terraria.ModLoader.EquipTexture.Texture, Terraria.ModLoader.ModContent.TextureExists(), and Terraria.ModLoader.EquipTexture.Type.
{
             if (!loading)
                 throw new Exception("AddEquipTexture can only be called from Mod.Load or Mod.Autoload");
             ModContent.GetTexture(texture); //ensure texture exists
             equipTexture.Texture = texture;
             equipTexture.mod = this;
             equipTexture.Name = name;
             equipTexture.Type = type;
             equipTexture.item = item;
             int slot = equipTexture.Slot = EquipLoader.ReserveEquipID(type);
             EquipLoader.equipTextures[type][slot] = equipTexture;
             equipTextures[Tuple.Create(name, type)] = equipTexture;
             if (type == EquipType.Body) {
                 if (femaleTexture == null || !ModContent.TextureExists(femaleTexture))
                     femaleTexture = texture;
                 EquipLoader.femaleTextures[slot] = femaleTexture;
                 ModContent.GetTexture(armTexture); //ensure texture exists
                 EquipLoader.armTextures[slot] = armTexture;
             }
             if (item != null) {
                 IDictionary<EquipType, int> slots;
                 if (!EquipLoader.idToSlot.TryGetValue(item.item.type, out slots))
                     EquipLoader.idToSlot[item.item.type] = slots = new Dictionary<EquipType, int>();
                 slots[type] = slot;
                 if (type == EquipType.Head || type == EquipType.Body || type == EquipType.Legs)
                     EquipLoader.slotToId[type][slot] = item.item.type;
             }
             return slot;
         }
void Terraria.ModLoader.Mod.AddGlobalBgStyle (string name, GlobalBgStyle globalBgStyle)
Adds the given global background style with the given name to this mod.
Parameters
name The name.
globalBgStyle The global bg style.
Definition at line 1232 of file Mod.cs.
References Terraria.ModLoader.GlobalBgStyle.mod, and Terraria.ModLoader.GlobalBgStyle.Name.
{
             if (!loading)
                 throw new Exception("AddGlobalBgStyle can only be called from Mod.Load or Mod.Autoload");
             globalBgStyle.mod = this;
             globalBgStyle.Name = name;
             globalBgStyles[name] = globalBgStyle;
             GlobalBgStyleLoader.globalBgStyles.Add(globalBgStyle);
             ContentInstance.Register(globalBgStyle);
         }
void Terraria.ModLoader.Mod.AddGlobalBuff (string name, GlobalBuff globalBuff)
Adds the given GlobalBuff instance to this mod using the provided name.
Parameters
name The name.
globalBuff The global buff.
Definition at line 1025 of file Mod.cs.
References Terraria.ModLoader.GlobalBuff.mod, and Terraria.ModLoader.GlobalBuff.Name.
{
             globalBuff.mod = this;
             globalBuff.Name = name;
             globalBuffs[name] = globalBuff;
             BuffLoader.globalBuffs.Add(globalBuff);
             ContentInstance.Register(globalBuff);
         }
void Terraria.ModLoader.Mod.AddGlobalItem (string name, GlobalItem globalItem)
Adds the given GlobalItem instance to this mod with the provided name.
Parameters
name The name.
globalItem The global item.
Definition at line 295 of file Mod.cs.
References Terraria.ModLoader.GlobalItem.mod, and Terraria.ModLoader.GlobalItem.Name.
{
             if (!loading)
                 throw new Exception("AddGlobalItem can only be called from Mod.Load or Mod.Autoload");
             ItemLoader.VerifyGlobalItem(globalItem);
             globalItem.mod = this;
             globalItem.Name = name;
             globalItems[name] = globalItem;
             globalItem.index = ItemLoader.globalItems.Count;
             ItemLoader.globalIndexes[Name + ':' + name] = ItemLoader.globalItems.Count;
             if (ItemLoader.globalIndexesByType.ContainsKey(globalItem.GetType())) {
                 ItemLoader.globalIndexesByType[globalItem.GetType()] = -1;
             }
             else {
                 ItemLoader.globalIndexesByType[globalItem.GetType()] = ItemLoader.globalItems.Count;
             }
             ItemLoader.globalItems.Add(globalItem);
             ContentInstance.Register(globalItem);
         }
void Terraria.ModLoader.Mod.AddGlobalNPC (string name, GlobalNPC globalNPC)
Adds the given GlobalNPC instance to this mod with the provided name.
Parameters
name The name.
globalNPC The global NPC.
Definition at line 871 of file Mod.cs.
References Terraria.ModLoader.GlobalNPC.mod, and Terraria.ModLoader.GlobalNPC.Name.
{
             if (!loading)
                 throw new Exception("AddGlobalNPC can only be called from Mod.Load or Mod.Autoload");
             NPCLoader.VerifyGlobalNPC(globalNPC);
             globalNPC.mod = this;
             globalNPC.Name = name;
             globalNPCs[name] = globalNPC;
             globalNPC.index = NPCLoader.globalNPCs.Count;
             NPCLoader.globalIndexes[Name + ':' + name] = NPCLoader.globalNPCs.Count;
             if (NPCLoader.globalIndexesByType.ContainsKey(globalNPC.GetType())) {
                 NPCLoader.globalIndexesByType[globalNPC.GetType()] = -1;
             }
             else {
                 NPCLoader.globalIndexesByType[globalNPC.GetType()] = NPCLoader.globalNPCs.Count;
             }
             NPCLoader.globalNPCs.Add(globalNPC);
             ContentInstance.Register(globalNPC);
         }
void Terraria.ModLoader.Mod.AddGlobalProjectile (string name, GlobalProjectile globalProjectile)
Adds the given GlobalProjectile instance to this mod with the provided name.
Parameters
name The name.
globalProjectile The global projectile.
Definition at line 787 of file Mod.cs.
References Terraria.ModLoader.GlobalProjectile.mod, and Terraria.ModLoader.GlobalProjectile.Name.
{
             if (!loading)
                 throw new Exception("AddGlobalProjectile can only be called from Mod.Load or Mod.Autoload");
             ProjectileLoader.VerifyGlobalProjectile(globalProjectile);
             globalProjectile.mod = this;
             globalProjectile.Name = name;
             globalProjectiles[name] = globalProjectile;
             globalProjectile.index = ProjectileLoader.globalProjectiles.Count;
             ProjectileLoader.globalIndexes[Name + ':' + name] = ProjectileLoader.globalProjectiles.Count;
             if (ProjectileLoader.globalIndexesByType.ContainsKey(globalProjectile.GetType())) {
                 ProjectileLoader.globalIndexesByType[globalProjectile.GetType()] = -1;
             }
             else {
                 ProjectileLoader.globalIndexesByType[globalProjectile.GetType()] = ProjectileLoader.globalProjectiles.Count;
             }
             ProjectileLoader.globalProjectiles.Add(globalProjectile);
             ContentInstance.Register(globalProjectile);
         }
void Terraria.ModLoader.Mod.AddGlobalRecipe (string name, GlobalRecipe globalRecipe)
Manually add a Global Recipe during Load
Parameters
name The name.
globalRecipe The global recipe.
Definition at line 1413 of file Mod.cs.
References Terraria.ModLoader.GlobalRecipe.mod, and Terraria.ModLoader.GlobalRecipe.Name.
{
             if (!loading)
                 throw new Exception("AddGlobalRecipe can only be called from Mod.Load or Mod.Autoload");
             globalRecipe.mod = this;
             globalRecipe.Name = name;
             globalRecipes[name] = globalRecipe;
             RecipeHooks.Add(globalRecipe);
             ContentInstance.Register(globalRecipe);
         }
void Terraria.ModLoader.Mod.AddGlobalTile (string name, GlobalTile globalTile)
Adds the given GlobalTile instance to this mod with the provided name.
Parameters
name The name.
globalTile The global tile.
Definition at line 587 of file Mod.cs.
References Terraria.ModLoader.GlobalTile.mod, and Terraria.ModLoader.GlobalTile.Name.
{
             if (!loading)
                 throw new Exception("AddGlobalTile can only be called from Mod.Load or Mod.Autoload");
             globalTile.mod = this;
             globalTile.Name = name;
             globalTiles[name] = globalTile;
             TileLoader.globalTiles.Add(globalTile);
             ContentInstance.Register(globalTile);
         }
void Terraria.ModLoader.Mod.AddGlobalWall (string name, GlobalWall globalWall)
Adds the given GlobalWall instance to this mod with the provided name.
Parameters
name The name.
globalWall The global wall.
Definition at line 713 of file Mod.cs.
References Terraria.ModLoader.GlobalWall.mod, and Terraria.ModLoader.GlobalWall.Name.
{
             if (!loading)
                 throw new Exception("AddGlobalWall can only be called from Mod.Load or Mod.Autoload");
             globalWall.mod = this;
             globalWall.Name = name;
             globalWalls[name] = globalWall;
             WallLoader.globalWalls.Add(globalWall);
             ContentInstance.Register(globalWall);
         }
void Terraria.ModLoader.Mod.AddGore (string texture, ModGore modGore = null)
Adds the given texture to the game as a custom gore, with the given custom gore behavior. If no custom gore behavior is provided, the custom gore will have the default vanilla behavior.
Parameters
texture The texture.
modGore The mod gore.
Definition at line 1330 of file Mod.cs.
References Terraria.ModLoader.ModGore.GetGoreSlot().
{
             if (!loading)
                 throw new Exception("AddGore can only be called from Mod.Load or Mod.Autoload");
             int id = ModGore.ReserveGoreID();
             ModGore.gores[texture] = id;
             if (modGore != null) {
                 ModGore.modGores[id] = modGore;
                 ContentInstance.Register(modGore);
             }
         }
void Terraria.ModLoader.Mod.AddItem (string name, ModItem item)
Adds a type of item to your mod with the specified internal name. This method should be called in Load. You can obtain an instance of ModItem by overriding it then creating an instance of the subclass.
Parameters
name The name.
item The item.
Exceptions
System.Exception You tried to add 2 ModItems with the same name: " + name + ". Maybe 2 classes share a classname but in different namespaces while autoloading or you manually called AddItem with 2 items of the same name.
Definition at line 240 of file Mod.cs.
References Terraria.ModLoader.ModItem.DisplayName, Terraria.ModLoader.ModItem.item, Terraria.ModLoader.ModItem.mod, Terraria.ModLoader.ModItem.Name, and Terraria.ModLoader.ModItem.Tooltip.
{
             if (!loading)
                 throw new Exception(Language.GetTextValue("tModLoader.LoadErrorAddItemOnlyInLoad"));
             if (items.ContainsKey(name))
                 throw new Exception(Language.GetTextValue("tModLoader.LoadError2ModItemSameName", name));
             item.mod = this;
             item.Name = name;
             item.DisplayName = GetOrCreateTranslation(string.Format("Mods.{0}.ItemName.{1}", Name, name));
             item.Tooltip = GetOrCreateTranslation(string.Format("Mods.{0}.ItemTooltip.{1}", Name, name), true);
             item.item.ResetStats(ItemLoader.ReserveItemID());
             item.item.modItem = item;
             items[name] = item;
             ItemLoader.items.Add(item);
             ContentInstance.Register(item);
         }
void Terraria.ModLoader.Mod.AddModWorld (string name, ModWorld modWorld)
Adds a ModWorld to this mod with the given name.
Parameters
name The name.
modWorld The mod world.
Definition at line 1135 of file Mod.cs.
References Terraria.ModLoader.ModWorld.mod, and Terraria.ModLoader.ModWorld.Name.
{
             if (!loading)
                 throw new Exception("AddModWorld can only be called from Mod.Load or Mod.Autoload");
             modWorld.mod = this;
             modWorld.Name = name;
             worlds[name] = modWorld;
             WorldHooks.Add(modWorld);
             ContentInstance.Register(modWorld);
         }
void Terraria.ModLoader.Mod.AddMount (string name, ModMountData mount, string texture, IDictionary< MountTextureType, string > extraTextures = null)
Adds the given mount to the game with the given name and texture. The extraTextures dictionary should optionally map types of mount textures to the texture paths you want to include.
Parameters
name The name.
mount The mount.
texture The texture.
extraTextures The extra textures.
Definition at line 1051 of file Mod.cs.
References Terraria.ModLoader.ModContent.GetTexture(), Terraria.ModLoader.ModMountData.mod, Terraria.ModLoader.ModMountData.Name, Terraria.ModLoader.ModContent.TextureExists(), and Terraria.ModLoader.ModMountData.Type.
{
             if (!loading)
                 throw new Exception("AddMount can only be called from Mod.Load or Mod.Autoload");
             if (Mount.mounts == null || Mount.mounts.Length == MountID.Count)
                 Mount.Initialize();
             mount.mod = this;
             mount.Name = name;
             mount.Type = MountLoader.ReserveMountID();
             mount.texture = texture;
             mountDatas[name] = mount;
             MountLoader.mountDatas[mount.Type] = mount;
             ContentInstance.Register(mount);
             if (extraTextures == null)
                 return;
             foreach (var entry in extraTextures) {
                 if (!ModContent.TextureExists(entry.Value))
                     continue;
                 Texture2D extraTexture = ModContent.GetTexture(entry.Value);
                 switch (entry.Key) {
                     case MountTextureType.Back:
                         mount.mountData.backTexture = extraTexture;
                         break;
                     case MountTextureType.BackGlow:
                         mount.mountData.backTextureGlow = extraTexture;
                         break;
                     case MountTextureType.BackExtra:
                         mount.mountData.backTextureExtra = extraTexture;
                         break;
                     case MountTextureType.BackExtraGlow:
                         mount.mountData.backTextureExtraGlow = extraTexture;
                         break;
                     case MountTextureType.Front:
                         mount.mountData.frontTexture = extraTexture;
                         break;
                     case MountTextureType.FrontGlow:
                         mount.mountData.frontTextureGlow = extraTexture;
                         break;
                     case MountTextureType.FrontExtra:
                         mount.mountData.frontTextureExtra = extraTexture;
                         break;
                     case MountTextureType.FrontExtraGlow:
                         mount.mountData.frontTextureExtraGlow = extraTexture;
                         break;
                 }
             }
         }
void Terraria.ModLoader.Mod.AddMusicBox (int musicSlot, int itemType, int tileType, int tileFrameY = 0)
Allows you to tie a music ID, and item ID, and a tile ID together to form a music box. When music with the given ID is playing, equipped music boxes have a chance to change their ID to the given item type. When an item with the given item type is equipped, it will play the music that has musicSlot as its ID. When a tile with the given type and Y-frame is nearby, if its X-frame is >= 36, it will play the music that has musicSlot as its ID.
Parameters
musicSlot The music slot.
itemType Type of the item.
tileType Type of the tile.
tileFrameY The tile frame y.
Exceptions
System.ArgumentOutOfRangeException Cannot assign music box to vanilla music ID " + musicSlot or Music ID " + musicSlot + " does not exist or Cannot assign music box to vanilla item ID " + itemType or Item ID " + itemType + " does not exist or Cannot assign music box to vanilla tile ID " + tileType or Tile ID " + tileType + " does not exist
System.ArgumentException Music ID " + musicSlot + " has already been assigned a music box or Item ID " + itemType + " has already been assigned a music or or Y-frame must be divisible by 36
Definition at line 1475 of file Mod.cs.
References Terraria.ModLoader.ItemLoader.GetItem(), Terraria.ModLoader.TileLoader.GetTile(), and Terraria.ModLoader.SoundLoader.SoundCount().
{
             if (!loading)
                 throw new Exception("AddMusicBox can only be called from Mod.Load or Mod.Autoload");
             if (Main.waveBank == null)
                 return;
             if (musicSlot < Main.maxMusic) {
                 throw new ArgumentOutOfRangeException("Cannot assign music box to vanilla music ID " + musicSlot);
             }
             if (musicSlot >= SoundLoader.SoundCount(SoundType.Music)) {
                 throw new ArgumentOutOfRangeException("Music ID " + musicSlot + " does not exist");
             }
             if (itemType < ItemID.Count) {
                 throw new ArgumentOutOfRangeException("Cannot assign music box to vanilla item ID " + itemType);
             }
             if (ItemLoader.GetItem(itemType) == null) {
                 throw new ArgumentOutOfRangeException("Item ID " + itemType + " does not exist");
             }
             if (tileType < TileID.Count) {
                 throw new ArgumentOutOfRangeException("Cannot assign music box to vanilla tile ID " + tileType);
             }
             if (TileLoader.GetTile(tileType) == null) {
                 throw new ArgumentOutOfRangeException("Tile ID " + tileType + " does not exist");
             }
             if (SoundLoader.musicToItem.ContainsKey(musicSlot)) {
                 throw new ArgumentException("Music ID " + musicSlot + " has already been assigned a music box");
             }
             if (SoundLoader.itemToMusic.ContainsKey(itemType)) {
                 throw new ArgumentException("Item ID " + itemType + " has already been assigned a music");
             }
             if (!SoundLoader.tileToMusic.ContainsKey(tileType)) {
                 SoundLoader.tileToMusic[tileType] = new Dictionary<int, int>();
             }
             if (SoundLoader.tileToMusic[tileType].ContainsKey(tileFrameY)) {
                 string message = "Y-frame " + tileFrameY + " of tile type " + tileType + " has already been assigned a music";
                 throw new ArgumentException(message);
             }
             if (tileFrameY % 36 != 0) {
                 throw new ArgumentException("Y-frame must be divisible by 36");
             }
             SoundLoader.musicToItem[musicSlot] = itemType;
             SoundLoader.itemToMusic[itemType] = musicSlot;
             SoundLoader.tileToMusic[tileType][tileFrameY] = musicSlot;
         }
void Terraria.ModLoader.Mod.AddNPC (string name, ModNPC npc)
Adds a type of NPC to the game with the specified name and texture. Also allows you to give the NPC alternate textures.
Parameters
name The name.
npc The NPC.
Definition at line 824 of file Mod.cs.
References Terraria.ModLoader.ModNPC.DisplayName, Terraria.ModLoader.ModNPC.mod, Terraria.ModLoader.ModNPC.Name, and Terraria.ModLoader.ModNPC.npc.
{
             if (!loading)
                 throw new Exception("AddNPC can only be called from Mod.Load or Mod.Autoload");
             if (npcs.ContainsKey(name))
                 throw new Exception("You tried to add 2 ModNPC with the same name: " + name + ". Maybe 2 classes share a classname but in different namespaces while autoloading or you manually called AddNPC with 2 npcs of the same name.");
             npc.mod = this;
             npc.Name = name;
             npc.npc.type = NPCLoader.ReserveNPCID();
             npc.DisplayName = GetOrCreateTranslation(string.Format("Mods.{0}.NPCName.{1}", Name, name));
             npcs[name] = npc;
             NPCLoader.npcs.Add(npc);
             ContentInstance.Register(npc);
         }
void Terraria.ModLoader.Mod.AddNPCHeadTexture (int npcType, string texture)
Assigns a head texture to the given town NPC type.
Parameters
npcType Type of the NPC.
texture The texture.
Exceptions
MissingResourceException
Definition at line 909 of file Mod.cs.
References Terraria.ModLoader.ModContent.GetTexture().
{
             if (!loading)
                 throw new Exception("AddNPCHeadTexture can only be called from Mod.Load or Mod.Autoload");
             int slot = NPCHeadLoader.ReserveHeadSlot();
             NPCHeadLoader.heads[texture] = slot;
             if (!Main.dedServ) {
                 ModContent.GetTexture(texture);
             }
             /*else if (Main.dedServ && !(ModLoader.FileExists(texture + ".png") || ModLoader.FileExists(texture + ".rawimg")))
             {
                 throw new MissingResourceException(texture);
             }*/
             NPCHeadLoader.npcToHead[npcType] = slot;
             NPCHeadLoader.headToNPC[slot] = npcType;
         }
void Terraria.ModLoader.Mod.AddPlayer (string name, ModPlayer player)
Adds a type of ModPlayer to this mod. All ModPlayer types will be newly created and attached to each player that is loaded.
Parameters
name The name.
player The player.
Definition at line 948 of file Mod.cs.
References Terraria.ModLoader.ModPlayer.mod, and Terraria.ModLoader.ModPlayer.Name.
{
             if (!loading)
                 throw new Exception("AddPlayer can only be called from Mod.Load or Mod.Autoload");
             player.mod = this;
             player.Name = name;
             players[name] = player;
             PlayerHooks.Add(player);
             ContentInstance.Register(player);
         }
void Terraria.ModLoader.Mod.AddPrefix (string name, ModPrefix prefix)
Adds a prefix to your mod with the specified internal name. This method should be called in Load. You can obtain an instance of ModPrefix by overriding it then creating an instance of the subclass.
Parameters
name The name.
prefix The prefix.
Exceptions
System.Exception You tried to add 2 ModItems with the same name: " + name + ". Maybe 2 classes share a classname but in different namespaces while autoloading or you manually called AddItem with 2 items of the same name.
Definition at line 431 of file Mod.cs.
References Terraria.ModLoader.ModPrefix.Category, Terraria.ModLoader.ModPrefix.DisplayName, Terraria.ModLoader.ModPrefix.mod, Terraria.ModLoader.ModPrefix.Name, and Terraria.ModLoader.ModPrefix.Type.
{
             if (!loading)
                 throw new Exception("AddPrefix can only be called from Mod.Load or Mod.Autoload");
             if (prefixes.ContainsKey(name))
                 throw new Exception("You tried to add 2 ModPrefixes with the same name: " + name + ". Maybe 2 classes share a classname but in different namespaces while autoloading or you manually called AddPrefix with 2 prefixes of the same name.");
             prefix.mod = this;
             prefix.Name = name;
             prefix.DisplayName = GetOrCreateTranslation(string.Format("Mods.{0}.Prefix.{1}", Name, name));
             prefix.Type = ModPrefix.ReservePrefixID();
             prefixes[name] = prefix;
             ModPrefix.prefixes.Add(prefix);
             ModPrefix.categoryPrefixes[prefix.Category].Add(prefix);
             ContentInstance.Register(prefix);
         }
void Terraria.ModLoader.Mod.AddProjectile (string name, ModProjectile projectile)
Adds a type of projectile to the game with the specified name.
Parameters
name The name.
projectile The projectile.
Definition at line 740 of file Mod.cs.
References Terraria.ModLoader.ModProjectile.DisplayName, Terraria.ModLoader.ModProjectile.mod, Terraria.ModLoader.ModProjectile.Name, and Terraria.ModLoader.ModProjectile.projectile.
{
             if (!loading)
                 throw new Exception("AddProjectile can only be called from Mod.Load or Mod.Autoload");
             if (projectiles.ContainsKey(name))
                 throw new Exception("You tried to add 2 ModProjectile with the same name: " + name + ". Maybe 2 classes share a classname but in different namespaces while autoloading or you manually called AddProjectile with 2 projectiles of the same name.");
             projectile.mod = this;
             projectile.Name = name;
             projectile.projectile.type = ProjectileLoader.ReserveProjectileID();
             projectile.DisplayName = GetOrCreateTranslation(string.Format("Mods.{0}.ProjectileName.{1}", Name, name));
             projectiles[name] = projectile;
             ProjectileLoader.projectiles.Add(projectile);
             ContentInstance.Register(projectile);
         }
virtual void Terraria.ModLoader.Mod.AddRecipeGroups () virtual
Override this method to add recipe groups to this mod. You must add recipe groups by calling the RecipeGroup.RegisterGroup method here. A recipe group is a set of items that can be used interchangeably in the same recipe.
Definition at line 94 of file Mod.cs.
{
         }
virtual void Terraria.ModLoader.Mod.AddRecipes () virtual
Override this method to add recipes to the game. It is recommended that you do so through instances of ModRecipe, since it provides methods that simplify recipe creation.
Definition at line 100 of file Mod.cs.
{
         }
void Terraria.ModLoader.Mod.AddSound (SoundType type, string soundPath, ModSound modSound = null)
Adds the given sound file to the game as the given type of sound and with the given custom sound playing. If no ModSound instance is provided, the custom sound will play in a similar manner as the default vanilla ones.
Parameters
type The type.
soundPath The sound path.
modSound The mod sound.
Definition at line 1362 of file Mod.cs.
References Terraria.ModLoader.ModContent.GetSound(), and Terraria.ModLoader.SoundLoader.GetSoundSlot().
{
             if (!loading)
                 throw new Exception("AddSound can only be called from Mod.Load or Mod.Autoload");
             int id = SoundLoader.ReserveSoundID(type);
             SoundLoader.sounds[type][soundPath] = id;
             if (modSound != null) {
                 SoundLoader.modSounds[type][id] = modSound;
                 modSound.sound = ModContent.GetSound(soundPath);
             }
         }
void Terraria.ModLoader.Mod.AddSurfaceBgStyle (string name, ModSurfaceBgStyle surfaceBgStyle)
Adds the given surface background style with the given name to this mod.
Parameters
name The name.
surfaceBgStyle The surface bg style.
Definition at line 1195 of file Mod.cs.
References Terraria.ModLoader.ModSurfaceBgStyle.mod, Terraria.ModLoader.ModSurfaceBgStyle.Name, and Terraria.ModLoader.ModSurfaceBgStyle.Slot.
{
             if (!loading)
                 throw new Exception("AddSurfaceBgStyle can only be called from Mod.Load or Mod.Autoload");
             surfaceBgStyle.mod = this;
             surfaceBgStyle.Name = name;
             surfaceBgStyle.Slot = SurfaceBgStyleLoader.ReserveBackgroundSlot();
             surfaceBgStyles[name] = surfaceBgStyle;
             SurfaceBgStyleLoader.surfaceBgStyles.Add(surfaceBgStyle);
             ContentInstance.Register(surfaceBgStyle);
         }
void Terraria.ModLoader.Mod.AddTexture (string name, Texture2D texture)
Shorthand for calling ModLoader.AddTexture(this.FileName(name), texture).
Parameters
name The name.
texture The texture.
Exceptions
Terraria.ModLoader.Exceptions.ModNameException Texture already exist: " + name
Definition at line 1598 of file Mod.cs.
{
             if (Main.dedServ)
                 return;
             if (TextureExists(name))
                 throw new Exception("Texture already exist: " + name);
             textures[name] = texture;
         }
void Terraria.ModLoader.Mod.AddTile (string name, ModTile tile, string texture)
Adds a type of tile to the game with the specified name and texture.
Parameters
name The name.
tile The tile.
texture The texture.
Definition at line 535 of file Mod.cs.
References Terraria.ModLoader.ModTile.mod, Terraria.ModLoader.ModTile.Name, and Terraria.ModLoader.ModTile.Type.
{
             if (!loading)
                 throw new Exception("AddItem can only be called from Mod.Load or Mod.Autoload");
             if (tiles.ContainsKey(name))
                 throw new Exception("You tried to add 2 ModTile with the same name: " + name + ". Maybe 2 classes share a classname but in different namespaces while autoloading or you manually called AddTile with 2 tiles of the same name.");
             tile.mod = this;
             tile.Name = name;
             tile.Type = (ushort)TileLoader.ReserveTileID();
             tile.texture = texture;
             tiles[name] = tile;
             TileLoader.tiles.Add(tile);
             ContentInstance.Register(tile);
         }
void Terraria.ModLoader.Mod.AddTileEntity (string name, ModTileEntity entity)
Manually add a tile entity during Load.
Definition at line 617 of file Mod.cs.
References Terraria.ModLoader.ModTileEntity.mod, Terraria.ModLoader.ModTileEntity.Name, and Terraria.ModLoader.ModTileEntity.Type.
{
             if (!loading)
                 throw new Exception("AddTileEntity can only be called from Mod.Load or Mod.Autoload");
             int id = ModTileEntity.ReserveTileEntityID();
             entity.mod = this;
             entity.Name = name;
             entity.Type = id;
             entity.type = (byte)id;
             tileEntities[name] = entity;
             ModTileEntity.tileEntities.Add(entity);
             ContentInstance.Register(entity);
         }
void Terraria.ModLoader.Mod.AddTranslation (ModTranslation translation)
Adds a ModTranslation to the game so that you can use Language.GetText to get a LocalizedText.
Definition at line 1544 of file Mod.cs.
References Terraria.ModLoader.ModTranslation.Key.
{
             translations[translation.Key] = translation;
         }
void Terraria.ModLoader.Mod.AddUgBgStyle (string name, ModUgBgStyle ugBgStyle)
Adds the given underground background style with the given name to this mod.
Parameters
name The name.
ugBgStyle The ug bg style.
Definition at line 1167 of file Mod.cs.
References Terraria.ModLoader.ModUgBgStyle.mod, Terraria.ModLoader.ModUgBgStyle.Name, and Terraria.ModLoader.ModUgBgStyle.Slot.
{
             if (!loading)
                 throw new Exception("AddUgBgStyle can only be called from Mod.Load or Mod.Autoload");
             ugBgStyle.mod = this;
             ugBgStyle.Name = name;
             ugBgStyle.Slot = UgBgStyleLoader.ReserveBackgroundSlot();
             ugBgStyles[name] = ugBgStyle;
             UgBgStyleLoader.ugBgStyles.Add(ugBgStyle);
             ContentInstance.Register(ugBgStyle);
         }
void Terraria.ModLoader.Mod.AddWall (string name, ModWall wall, string texture)
Adds a type of wall to the game with the specified name and texture.
Parameters
name The name.
wall The wall.
texture The texture.
Definition at line 669 of file Mod.cs.
References Terraria.ModLoader.ModWall.mod, Terraria.ModLoader.ModWall.Name, and Terraria.ModLoader.ModWall.Type.
{
             if (!loading)
                 throw new Exception("AddWall can only be called from Mod.Load or Mod.Autoload");
             wall.mod = this;
             wall.Name = name;
             wall.Type = (ushort)WallLoader.ReserveWallID();
             wall.texture = texture;
             walls[name] = wall;
             WallLoader.walls.Add(wall);
             ContentInstance.Register(wall);
         }
void Terraria.ModLoader.Mod.AddWaterfallStyle (string name, ModWaterfallStyle waterfallStyle, string texture)
Adds the given waterfall style to the game with the given name and texture path.
Parameters
name The name.
waterfallStyle The waterfall style.
texture The texture.
Definition at line 1292 of file Mod.cs.
References Terraria.ModLoader.ModWaterfallStyle.mod, Terraria.ModLoader.ModWaterfallStyle.Name, and Terraria.ModLoader.ModWaterfallStyle.Type.
{
             if (!loading)
                 throw new Exception("AddWaterfallStyle can only be called from Mod.Load or Mod.Autoload");
             waterfallStyle.mod = this;
             waterfallStyle.Name = name;
             waterfallStyle.Type = WaterfallStyleLoader.ReserveStyle();
             waterfallStyle.texture = texture;
             waterfallStyles[name] = waterfallStyle;
             WaterfallStyleLoader.waterfallStyles.Add(waterfallStyle);
             ContentInstance.Register(waterfallStyle);
         }
void Terraria.ModLoader.Mod.AddWaterStyle (string name, ModWaterStyle waterStyle, string texture, string blockTexture)
Adds the given water style to the game with the given name, texture path, and block texture path.
Parameters
name The name.
waterStyle The water style.
texture The texture.
blockTexture The block texture.
Definition at line 1261 of file Mod.cs.
References Terraria.ModLoader.ModWaterStyle.mod, Terraria.ModLoader.ModWaterStyle.Name, and Terraria.ModLoader.ModWaterStyle.Type.
{
             if (!loading)
                 throw new Exception("AddWaterStyle can only be called from Mod.Load or Mod.Autoload");
             waterStyle.mod = this;
             waterStyle.Name = name;
             waterStyle.Type = WaterStyleLoader.ReserveStyle();
             waterStyle.texture = texture;
             waterStyle.blockTexture = blockTexture;
             waterStyles[name] = waterStyle;
             WaterStyleLoader.waterStyles.Add(waterStyle);
             ContentInstance.Register(waterStyle);
         }
void Terraria.ModLoader.Mod.AutoloadBackgrounds () private
Definition at line 532 of file ModInternals.cs.
{
             foreach (string texture in textures.Keys.Where(t => t.StartsWith("Backgrounds/"))) {
                 AddBackgroundTexture(Name + '/' + texture);
             }
         }
void Terraria.ModLoader.Mod.AutoloadBuff (Type type) private
Definition at line 490 of file ModInternals.cs.
References Terraria.ModLoader.ModBuff.Autoload(), Terraria.ModLoader.ModBuff.mod, and Terraria.ModLoader.Mod.Name.
{
             ModBuff buff = (ModBuff)Activator.CreateInstance(type);
             buff.mod = this;
             string name = type.Name;
             string texture = (type.Namespace + "." + type.Name).Replace('.', '/');
             if (buff.Autoload(ref name, ref texture)) {
                 AddBuff(name, buff, texture);
             }
         }
void Terraria.ModLoader.Mod.AutoloadCommand (Type type) private
Definition at line 636 of file ModInternals.cs.
{
             var mc = (ModCommand)Activator.CreateInstance(type);
             mc.mod = this;
             var name = type.Name;
             if (mc.Autoload(ref name))
                 AddCommand(name, mc);
         }
void Terraria.ModLoader.Mod.AutoloadDust (Type type) private
Definition at line 378 of file ModInternals.cs.
References Terraria.ModLoader.ModDust.Autoload(), Terraria.ModLoader.ModDust.mod, and Terraria.ModLoader.Mod.Name.
{
             ModDust dust = (ModDust)Activator.CreateInstance(type);
             dust.mod = this;
             string name = type.Name;
             string texture = (type.Namespace + "." + type.Name).Replace('.', '/');
             if (dust.Autoload(ref name, ref texture)) {
                 AddDust(name, dust, texture);
             }
         }
void Terraria.ModLoader.Mod.AutoloadGlobalBgStyle (Type type) private
Definition at line 556 of file ModInternals.cs.
References Terraria.ModLoader.GlobalBgStyle.Autoload(), Terraria.ModLoader.GlobalBgStyle.mod, and Terraria.ModLoader.Mod.Name.
{
             GlobalBgStyle globalBgStyle = (GlobalBgStyle)Activator.CreateInstance(type);
             globalBgStyle.mod = this;
             string name = type.Name;
             if (globalBgStyle.Autoload(ref name)) {
                 AddGlobalBgStyle(name, globalBgStyle);
             }
         }
void Terraria.ModLoader.Mod.AutoloadGlobalBuff (Type type) private
Definition at line 500 of file ModInternals.cs.
References Terraria.ModLoader.GlobalBuff.Autoload(), Terraria.ModLoader.GlobalBuff.mod, and Terraria.ModLoader.Mod.Name.
{
             GlobalBuff globalBuff = (GlobalBuff)Activator.CreateInstance(type);
             globalBuff.mod = this;
             string name = type.Name;
             if (globalBuff.Autoload(ref name)) {
                 AddGlobalBuff(name, globalBuff);
             }
         }
void Terraria.ModLoader.Mod.AutoloadGlobalItem (Type type) private
Definition at line 360 of file ModInternals.cs.
References Terraria.ModLoader.GlobalItem.Autoload(), Terraria.ModLoader.GlobalItem.mod, and Terraria.ModLoader.Mod.Name.
{
             GlobalItem globalItem = (GlobalItem)Activator.CreateInstance(type);
             globalItem.mod = this;
             string name = type.Name;
             if (globalItem.Autoload(ref name)) {
                 AddGlobalItem(name, globalItem);
             }
         }
void Terraria.ModLoader.Mod.AutoloadGlobalNPC (Type type) private
Definition at line 472 of file ModInternals.cs.
References Terraria.ModLoader.GlobalNPC.Autoload(), Terraria.ModLoader.GlobalNPC.mod, and Terraria.ModLoader.Mod.Name.
{
             GlobalNPC globalNPC = (GlobalNPC)Activator.CreateInstance(type);
             globalNPC.mod = this;
             string name = type.Name;
             if (globalNPC.Autoload(ref name)) {
                 AddGlobalNPC(name, globalNPC);
             }
         }
void Terraria.ModLoader.Mod.AutoloadGlobalProjectile (Type type) private
Definition at line 444 of file ModInternals.cs.
References Terraria.ModLoader.GlobalProjectile.Autoload(), Terraria.ModLoader.GlobalProjectile.mod, and Terraria.ModLoader.Mod.Name.
{
             GlobalProjectile globalProjectile = (GlobalProjectile)Activator.CreateInstance(type);
             globalProjectile.mod = this;
             string name = type.Name;
             if (globalProjectile.Autoload(ref name)) {
                 AddGlobalProjectile(name, globalProjectile);
             }
         }
void Terraria.ModLoader.Mod.AutoloadGlobalRecipe (Type type) private
Definition at line 627 of file ModInternals.cs.
References Terraria.ModLoader.GlobalRecipe.Autoload(), Terraria.ModLoader.GlobalRecipe.mod, and Terraria.ModLoader.Mod.Name.
{
             GlobalRecipe globalRecipe = (GlobalRecipe)Activator.CreateInstance(type);
             globalRecipe.mod = this;
             string name = type.Name;
             if (globalRecipe.Autoload(ref name)) {
                 AddGlobalRecipe(name, globalRecipe);
             }
         }
void Terraria.ModLoader.Mod.AutoloadGlobalTile (Type type) private
Definition at line 398 of file ModInternals.cs.
References Terraria.ModLoader.GlobalTile.Autoload(), Terraria.ModLoader.GlobalTile.mod, and Terraria.ModLoader.Mod.Name.
{
             GlobalTile globalTile = (GlobalTile)Activator.CreateInstance(type);
             globalTile.mod = this;
             string name = type.Name;
             if (globalTile.Autoload(ref name)) {
                 AddGlobalTile(name, globalTile);
             }
         }
void Terraria.ModLoader.Mod.AutoloadGlobalWall (Type type) private
Definition at line 426 of file ModInternals.cs.
References Terraria.ModLoader.GlobalWall.Autoload(), Terraria.ModLoader.GlobalWall.mod, and Terraria.ModLoader.Mod.Name.
{
             GlobalWall globalWall = (GlobalWall)Activator.CreateInstance(type);
             globalWall.mod = this;
             string name = type.Name;
             if (globalWall.Autoload(ref name)) {
                 AddGlobalWall(name, globalWall);
             }
         }
void Terraria.ModLoader.Mod.AutoloadGores (IList< Type > modGores) private
Definition at line 586 of file ModInternals.cs.
{
             var modGoreNames = modGores.ToDictionary(t => t.Namespace + "." + t.Name);
             foreach (var texture in textures.Keys.Where(t => t.StartsWith("Gores/"))) {
                 ModGore modGore = null;
                 Type t;
                 if (modGoreNames.TryGetValue(Name + "." + texture.Replace('/', '.'), out t))
                     modGore = (ModGore)Activator.CreateInstance(t);
                 AddGore(Name + '/' + texture, modGore);
             }
         }
void Terraria.ModLoader.Mod.AutoloadItem (Type type) private
Definition at line 346 of file ModInternals.cs.
References Terraria.ModLoader.ModItem.Autoload(), Terraria.ModLoader.ModItem.mod, Terraria.ModLoader.Mod.Name, Terraria.ModLoader.ModItem.Name, and Terraria.ModLoader.ModItem.Texture.
{
             ModItem item = (ModItem)Activator.CreateInstance(type);
             item.mod = this;
             string name = type.Name;
             if (item.Autoload(ref name)) {
                 AddItem(name, item);
                 var autoloadEquip = type.GetAttribute<AutoloadEquip>();
                 if (autoloadEquip != null)
                     foreach (var equip in autoloadEquip.equipTypes)
                         AddEquipTexture(item, equip, item.Name, item.Texture + '_' + equip,
                             item.Texture + "_Arms", item.Texture + "_FemaleBody");
             }
         }
void Terraria.ModLoader.Mod.AutoloadLocalization () private
Loads .lang files
Definition at line 647 of file ModInternals.cs.
{
             var modTranslationDictionary = new Dictionary<string, ModTranslation>();
             foreach (var translationFile in File.Where(entry => Path.GetExtension(entry.Name) == ".lang")) {
                 // .lang files need to be UTF8 encoded.
                 string translationFileContents = System.Text.Encoding.UTF8.GetString(File.GetBytes(translationFile));
                 GameCulture culture = GameCulture.FromName(Path.GetFileNameWithoutExtension(translationFile.Name));
                 using (StringReader reader = new StringReader(translationFileContents)) {
                     string line;
                     while ((line = reader.ReadLine()) != null) {
                         int split = line.IndexOf('=');
                         if (split < 0)
                             continue; // lines witout a = are ignored
                         string key = line.Substring(0, split).Trim().Replace(" ", "_");
                         string value = line.Substring(split + 1); // removed .Trim() since sometimes it is desired.
                         if (value.Length == 0) {
                             continue;
                         }
                         value = value.Replace("\\n", "\n");
                         // TODO: Maybe prepend key with filename: en.US.ItemName.lang would automatically assume "ItemName." for all entries.
                         //string key = key;
                         if (!modTranslationDictionary.TryGetValue(key, out ModTranslation mt))
                             modTranslationDictionary[key] = mt = CreateTranslation(key);
                         mt.AddTranslation(culture, value);
                     }
                 }
             }
             foreach (var value in modTranslationDictionary.Values) {
                 AddTranslation(value);
             }
         }
void Terraria.ModLoader.Mod.AutoloadModWorld (Type type) private
Definition at line 523 of file ModInternals.cs.
References Terraria.ModLoader.ModWorld.Autoload(), Terraria.ModLoader.ModWorld.mod, and Terraria.ModLoader.Mod.Name.
{
             ModWorld modWorld = (ModWorld)Activator.CreateInstance(type);
             modWorld.mod = this;
             string name = type.Name;
             if (modWorld.Autoload(ref name)) {
                 AddModWorld(name, modWorld);
             }
         }
void Terraria.ModLoader.Mod.AutoloadMountData (Type type) private
Definition at line 509 of file ModInternals.cs.
References Terraria.ModLoader.ModMountData.mod, and Terraria.ModLoader.Mod.Name.
{
             ModMountData mount = (ModMountData)Activator.CreateInstance(type);
             mount.mod = this;
             string name = type.Name;
             string texture = (type.Namespace + "." + type.Name).Replace('.', '/');
             var extraTextures = new Dictionary<MountTextureType, string>();
             foreach (MountTextureType textureType in Enum.GetValues(typeof(MountTextureType))) {
                 extraTextures[textureType] = texture + "_" + textureType.ToString();
             }
             if (mount.Autoload(ref name, ref texture, extraTextures)) {
                 AddMount(name, mount, texture, extraTextures);
             }
         }
void Terraria.ModLoader.Mod.AutoloadNPC (Type type) private
Definition at line 453 of file ModInternals.cs.
References Terraria.ModLoader.ModNPC.Autoload(), Terraria.ModLoader.ModNPC.BossHeadTexture, Terraria.ModLoader.ModNPC.HeadTexture, Terraria.ModLoader.ModNPC.mod, Terraria.ModLoader.Mod.Name, and Terraria.ModLoader.ModNPC.npc.
{
             ModNPC npc = (ModNPC)Activator.CreateInstance(type);
             npc.mod = this;
             string name = type.Name;
             if (npc.Autoload(ref name)) {
                 AddNPC(name, npc);
                 var autoloadHead = type.GetAttribute<AutoloadHead>();
                 if (autoloadHead != null) {
                     string headTexture = npc.HeadTexture;
                     AddNPCHeadTexture(npc.npc.type, headTexture);
                 }
                 var autoloadBossHead = type.GetAttribute<AutoloadBossHead>();
                 if (autoloadBossHead != null) {
                     string headTexture = npc.BossHeadTexture;
                     AddBossHeadTexture(headTexture, npc.npc.type);
                 }
             }
         }
void Terraria.ModLoader.Mod.AutoloadPlayer (Type type) private
Definition at line 481 of file ModInternals.cs.
References Terraria.ModLoader.ModPlayer.Autoload(), Terraria.ModLoader.ModPlayer.mod, and Terraria.ModLoader.Mod.Name.
{
             ModPlayer player = (ModPlayer)Activator.CreateInstance(type);
             player.mod = this;
             string name = type.Name;
             if (player.Autoload(ref name)) {
                 AddPlayer(name, player);
             }
         }
void Terraria.ModLoader.Mod.AutoloadPrefix (Type type) private
Definition at line 369 of file ModInternals.cs.
References Terraria.ModLoader.ModPrefix.Autoload(), Terraria.ModLoader.ModPrefix.mod, and Terraria.ModLoader.Mod.Name.
{
             ModPrefix prefix = (ModPrefix)Activator.CreateInstance(type);
             prefix.mod = this;
             string name = type.Name;
             if (prefix.Autoload(ref name)) {
                 AddPrefix(name, prefix);
             }
         }
void Terraria.ModLoader.Mod.AutoloadProjectile (Type type) private
Definition at line 435 of file ModInternals.cs.
References Terraria.ModLoader.ModProjectile.Autoload(), Terraria.ModLoader.ModProjectile.mod, and Terraria.ModLoader.Mod.Name.
{
             ModProjectile projectile = (ModProjectile)Activator.CreateInstance(type);
             projectile.mod = this;
             string name = type.Name;
             if (projectile.Autoload(ref name)) {
                 AddProjectile(name, projectile);
             }
         }
void Terraria.ModLoader.Mod.AutoloadSounds (IList< Type > modSounds) private
Definition at line 598 of file ModInternals.cs.
{
             var modSoundNames = modSounds.ToDictionary(t => t.Namespace + "." + t.Name);
             foreach (var sound in sounds.Keys.Where(t => t.StartsWith("Sounds/"))) {
                 string substring = sound.Substring("Sounds/".Length);
                 SoundType soundType = SoundType.Custom;
                 if (substring.StartsWith("Item/")) {
                     soundType = SoundType.Item;
                 }
                 else if (substring.StartsWith("NPCHit/")) {
                     soundType = SoundType.NPCHit;
                 }
                 else if (substring.StartsWith("NPCKilled/")) {
                     soundType = SoundType.NPCKilled;
                 }
                 ModSound modSound = null;
                 Type t;
                 if (modSoundNames.TryGetValue((Name + '/' + sound).Replace('/', '.'), out t))
                     modSound = (ModSound)Activator.CreateInstance(t);
                 AddSound(soundType, Name + '/' + sound, modSound);
             }
             foreach (var music in musics.Keys.Where(t => t.StartsWith("Sounds/"))) {
                 string substring = music.Substring("Sounds/".Length);
                 if (substring.StartsWith("Music/")) {
                     AddSound(SoundType.Music, Name + '/' + music);
                 }
             }
         }
void Terraria.ModLoader.Mod.AutoloadSurfaceBgStyle (Type type) private
Definition at line 547 of file ModInternals.cs.
References Terraria.ModLoader.ModSurfaceBgStyle.Autoload(), Terraria.ModLoader.ModSurfaceBgStyle.mod, and Terraria.ModLoader.Mod.Name.
{
             ModSurfaceBgStyle surfaceBgStyle = (ModSurfaceBgStyle)Activator.CreateInstance(type);
             surfaceBgStyle.mod = this;
             string name = type.Name;
             if (surfaceBgStyle.Autoload(ref name)) {
                 AddSurfaceBgStyle(name, surfaceBgStyle);
             }
         }
void Terraria.ModLoader.Mod.AutoloadTile (Type type) private
Definition at line 388 of file ModInternals.cs.
References Terraria.ModLoader.ModTile.Autoload(), Terraria.ModLoader.ModTile.mod, and Terraria.ModLoader.Mod.Name.
{
             ModTile tile = (ModTile)Activator.CreateInstance(type);
             tile.mod = this;
             string name = type.Name;
             string texture = (type.Namespace + "." + type.Name).Replace('.', '/');
             if (tile.Autoload(ref name, ref texture)) {
                 AddTile(name, tile, texture);
             }
         }
void Terraria.ModLoader.Mod.AutoloadTileEntity (Type type) private
Definition at line 407 of file ModInternals.cs.
References Terraria.ModLoader.ModTileEntity.Autoload(), Terraria.ModLoader.ModTileEntity.mod, and Terraria.ModLoader.Mod.Name.
{
             ModTileEntity tileEntity = (ModTileEntity)Activator.CreateInstance(type);
             tileEntity.mod = this;
             string name = type.Name;
             if (tileEntity.Autoload(ref name)) {
                 AddTileEntity(name, tileEntity);
             }
         }
void Terraria.ModLoader.Mod.AutoloadUgBgStyle (Type type) private
Definition at line 538 of file ModInternals.cs.
References Terraria.ModLoader.ModUgBgStyle.Autoload(), Terraria.ModLoader.ModUgBgStyle.mod, and Terraria.ModLoader.Mod.Name.
{
             ModUgBgStyle ugBgStyle = (ModUgBgStyle)Activator.CreateInstance(type);
             ugBgStyle.mod = this;
             string name = type.Name;
             if (ugBgStyle.Autoload(ref name)) {
                 AddUgBgStyle(name, ugBgStyle);
             }
         }
void Terraria.ModLoader.Mod.AutoloadWall (Type type) private
Definition at line 416 of file ModInternals.cs.
References Terraria.ModLoader.ModWall.Autoload(), Terraria.ModLoader.ModWall.mod, and Terraria.ModLoader.Mod.Name.
{
             ModWall wall = (ModWall)Activator.CreateInstance(type);
             wall.mod = this;
             string name = type.Name;
             string texture = (type.Namespace + "." + type.Name).Replace('.', '/');
             if (wall.Autoload(ref name, ref texture)) {
                 AddWall(name, wall, texture);
             }
         }
void Terraria.ModLoader.Mod.AutoloadWaterfallStyle (Type type) private
Definition at line 576 of file ModInternals.cs.
References Terraria.ModLoader.ModWaterfallStyle.Autoload(), Terraria.ModLoader.ModWaterfallStyle.mod, and Terraria.ModLoader.Mod.Name.
{
             ModWaterfallStyle waterfallStyle = (ModWaterfallStyle)Activator.CreateInstance(type);
             waterfallStyle.mod = this;
             string name = type.Name;
             string texture = (type.Namespace + "." + type.Name).Replace('.', '/');
             if (waterfallStyle.Autoload(ref name, ref texture)) {
                 AddWaterfallStyle(name, waterfallStyle, texture);
             }
         }
void Terraria.ModLoader.Mod.AutoloadWaterStyle (Type type) private
Definition at line 565 of file ModInternals.cs.
References Terraria.ModLoader.ModWaterStyle.Autoload(), Terraria.ModLoader.ModWaterStyle.mod, and Terraria.ModLoader.Mod.Name.
{
             ModWaterStyle waterStyle = (ModWaterStyle)Activator.CreateInstance(type);
             waterStyle.mod = this;
             string name = type.Name;
             string texture = (type.Namespace + "." + type.Name).Replace('.', '/');
             string blockTexture = texture + "_Block";
             if (waterStyle.Autoload(ref name, ref texture, ref blockTexture)) {
                 AddWaterStyle(name, waterStyle, texture, blockTexture);
             }
         }
int Terraria.ModLoader.Mod.BuffType (string name)
Gets the type of the ModBuff of this mod corresponding to the given name. Returns 0 if no ModBuff with the given name is found.
Parameters
name The name.
Returns
int Terraria.ModLoader.Mod.BuffType< T > ()
Same as the other BuffType, but assumes that the class name and internal name are the same.
Template Parameters
T
Returns
Type Constraints
T : ModBuff
T : ModContent.BuffType<T>()
virtual object Terraria.ModLoader.Mod.Call (params object[] args) virtual
Used for weak inter-mod communication. This allows you to interact with other mods without having to reference their types or namespaces, provided that they have implemented this method.
Definition at line 1683 of file Mod.cs.
{
             return null;
         }
virtual void Terraria.ModLoader.Mod.Close () virtual
Close is called before Unload, and may be called at any time when mod unloading is imminent (such as when downloading an update, or recompiling) Use this to release any additional file handles, or stop streaming music. Make sure to call base.Close() at the end May be called multiple times before Unload
Definition at line 136 of file Mod.cs.
Referenced by Terraria.ModLoader.ModNet.DownloadNextMod().
{
             fileHandle?.Dispose();
             if (File != null && File.IsOpen)
                 throw new IOException($"TModFile has open handles: {File.path}");
         }
ModTranslation Terraria.ModLoader.Mod.CreateTranslation (string key)
Creates a ModTranslation object that you can use in AddTranslation.
Parameters
key The key for the ModTranslation. The full key will be Mods.ModName.key
int Terraria.ModLoader.Mod.DustType (string name)
Gets the type of the ModDust of this mod with the given name. Returns 0 if no ModDust with the given name is found.
Parameters
name The name.
Returns
int Terraria.ModLoader.Mod.DustType< T > ()
Same as the other DustType, but assumes that the class name and internal name are the same.
Template Parameters
T
Returns
Type Constraints
T : ModDust
T : ModContent.DustType<T>()
bool Terraria.ModLoader.Mod.EffectExists (string name)
Used to check if a custom Effect exists
bool Terraria.ModLoader.Mod.FileExists (string name)
Shorthand for calling ModLoader.FileExists(this.FileName(name)). Note that file extensions are used here.
Parameters
name The name.
Returns
Referenced by Terraria.ModLoader.ModContent.FileExists().
bool Terraria.ModLoader.Mod.FontExists (string name)
Used to check if a custom SpriteFont exists
sbyte Terraria.ModLoader.Mod.GetAccessorySlot (string name, EquipType type)
Same as GetEquipSlot, except returns the number as an sbyte (signed byte) for your convenience.
Parameters
name The name.
type
Returns
int Terraria.ModLoader.Mod.GetBackgroundSlot (string name)
Gets the texture slot corresponding to the specified texture name. Shorthand for calling BackgroundTextureLoader.GetBackgroundSlot(this.Name + '/' + name).
Parameters
name The name.
Returns
ModBuff Terraria.ModLoader.Mod.GetBuff (string name)
Gets the ModBuff of this mod corresponding to the given name. Returns null if no ModBuff with the given name is found.
Parameters
name The name.
Returns
T Terraria.ModLoader.Mod.GetBuff< T > ()
Type Constraints
T : ModBuff
T : ModContent.GetInstance<T>()
ModConfig Terraria.ModLoader.Mod.GetConfig (string name)
Definition at line 1707 of file Mod.cs.
         {
             List<ModConfig> configs;
             if (ConfigManager.Configs.TryGetValue(this, out configs))
             {
                 return configs.Single(x => x.Name == name);
             }
             return null;
         }
T Terraria.ModLoader.Mod.GetConfig< T > ()
Type Constraints
T : ModConfig
T : T
T : GetConfig
T : typeof
T : T
T : Name
ModDust Terraria.ModLoader.Mod.GetDust (string name)
Gets the ModDust of this mod corresponding to the given name. Returns null if no ModDust with the given name is found.
Parameters
name The name.
Returns
T Terraria.ModLoader.Mod.GetDust< T > ()
Same as the other GetDust, but assumes that the class name and internal name are the same.
Template Parameters
T
Returns
Type Constraints
T : ModDust
T : ModContent.GetInstance<T>()
Effect Terraria.ModLoader.Mod.GetEffect (string name)
Gets an Effect loaded from the specified path.
Exceptions
MissingResourceException
Definition at line 1668 of file Mod.cs.
{
             if (!effects.TryGetValue(name, out var effect))
                 throw new MissingResourceException(name);
             return effect;
         }
int Terraria.ModLoader.Mod.GetEquipSlot (string name, EquipType type)
Gets the slot/ID of the equipment texture corresponding to the given name. Returns -1 if no EquipTexture with the given name is found.
Parameters
name The name.
type
Returns
EquipTexture Terraria.ModLoader.Mod.GetEquipTexture (string name, EquipType type)
Gets the EquipTexture instance corresponding to the name and EquipType. Returns null if no EquipTexture with the given name and EquipType is found.
Parameters
name The name.
type The type.
Returns
byte [] Terraria.ModLoader.Mod.GetFileBytes (string name)
Retrieve contents of files within the tmod file
Parameters
name The name.
Returns
Referenced by Terraria.ModLoader.ModContent.GetFileBytes().
Stream Terraria.ModLoader.Mod.GetFileStream (string name, bool newFileStream = false)
Retrieve contents of files within the tmod file
Parameters
name The name.
Returns
Referenced by Terraria.ModLoader.ModContent.OpenRead().
DynamicSpriteFont Terraria.ModLoader.Mod.GetFont (string name)
Gets a SpriteFont loaded from the specified path.
Exceptions
MissingResourceException
Definition at line 1652 of file Mod.cs.
{
             if (!fonts.TryGetValue(name, out var font))
                 throw new MissingResourceException(name);
             return font;
         }
GlobalBgStyle Terraria.ModLoader.Mod.GetGlobalBgStyle (string name)
Returns the global background style corresponding to the given name.
Parameters
name The name.
Returns
T Terraria.ModLoader.Mod.GetGlobalBgStyle< T > ()
Type Constraints
T : GlobalBgStyle
T : ModContent.GetInstance<T>()
GlobalBuff Terraria.ModLoader.Mod.GetGlobalBuff (string name)
Gets the GlobalBuff with the given name from this mod.
Parameters
name The name.
Returns
T Terraria.ModLoader.Mod.GetGlobalBuff< T > ()
Type Constraints
T : GlobalBuff
T : ModContent.GetInstance<T>()
GlobalItem Terraria.ModLoader.Mod.GetGlobalItem (string name)
Gets the GlobalItem instance with the given name from this mod.
Parameters
name The name.
Returns
Referenced by Terraria.ModLoader.IO.ItemIO.Load(), and Terraria.ModLoader.IO.ItemIO.LoadLegacy().
T Terraria.ModLoader.Mod.GetGlobalItem< T > ()
Same as the other GetGlobalItem, but assumes that the class name and internal name are the same.
Template Parameters
T
Returns
Type Constraints
T : GlobalItem
T : T
T : GetGlobalItem
T : typeof
T : T
T : Name
GlobalNPC Terraria.ModLoader.Mod.GetGlobalNPC (string name)
Gets the GlobalNPC instance with the given name from this mod.
Parameters
name The name.
Returns
T Terraria.ModLoader.Mod.GetGlobalNPC< T > ()
Type Constraints
T : GlobalNPC
T : ModContent.GetInstance<T>()
GlobalProjectile Terraria.ModLoader.Mod.GetGlobalProjectile (string name)
Gets the GlobalProjectile instance with the given name from this mod.
Parameters
name The name.
Returns
T Terraria.ModLoader.Mod.GetGlobalProjectile< T > ()
Type Constraints
T : GlobalProjectile
T : ModContent.GetInstance<T>()
GlobalRecipe Terraria.ModLoader.Mod.GetGlobalRecipe (string name)
Gets the global recipe corresponding to the specified name.
Parameters
name The name.
Returns
T Terraria.ModLoader.Mod.GetGlobalRecipe< T > ()
Type Constraints
T : GlobalRecipe
T : ModContent.GetInstance<T>()
GlobalTile Terraria.ModLoader.Mod.GetGlobalTile (string name)
Gets the GlobalTile instance with the given name from this mod.
Parameters
name The name.
Returns
T Terraria.ModLoader.Mod.GetGlobalTile< T > ()
Same as the other GetGlobalTile, but assumes that the class name and internal name are the same.
Template Parameters
T
Returns
Type Constraints
T : GlobalTile
T : ModContent.GetInstance<T>()
GlobalWall Terraria.ModLoader.Mod.GetGlobalWall (string name)
Gets the GlobalWall instance with the given name from this mod.
Parameters
name The name.
Returns
T Terraria.ModLoader.Mod.GetGlobalWall< T > ()
Type Constraints
T : GlobalWall
T : ModContent.GetInstance<T>()
int Terraria.ModLoader.Mod.GetGoreSlot (string name)
Shorthand for calling ModGore.GetGoreSlot(this.Name + '/' + name).
Parameters
name The name.
Returns
int Terraria.ModLoader.Mod.GetGoreSlot< T > ()
Same as the other GetGoreSlot, but assumes that the class name and internal name are the same.
Template Parameters
T
Returns
Type Constraints
T : ModGore
T : GetGoreSlot
T : typeof
T : T
T : Name
ModItem Terraria.ModLoader.Mod.GetItem (string name)
Gets the ModItem instance corresponding to the name. Because this method is in the Mod class, conflicts between mods are avoided. Returns null if no ModItem with the given name is found.
Parameters
name The name.
Returns
T Terraria.ModLoader.Mod.GetItem< T > ()
Same as the other GetItem, but assumes that the class name and internal name are the same.
Template Parameters
T
Returns
Type Constraints
T : ModItem
T : ModContent.GetInstance<T>()
LegacySoundStyle Terraria.ModLoader.Mod.GetLegacySoundSlot (SoundType type, string name)
Shorthand for calling SoundLoader.GetLegacySoundSlot(type, this.Name + '/' + name).
Parameters
type The type.
name The name.
Returns
ModWorld Terraria.ModLoader.Mod.GetModWorld (string name)
Gets the ModWorld instance with the given name from this mod.
Parameters
name The name.
Returns
T Terraria.ModLoader.Mod.GetModWorld< T > ()
Same as the other GetModWorld, but assumes that the class name and internal name are the same.
Template Parameters
T
Returns
Type Constraints
T : ModWorld
T : ModContent.GetInstance<T>()
ModMountData Terraria.ModLoader.Mod.GetMount (string name)
Gets the ModMountData instance of this mod corresponding to the given name. Returns null if no ModMountData has the given name.
Parameters
name The name.
Returns
T Terraria.ModLoader.Mod.GetMount< T > ()
Type Constraints
T : ModMountData
T : ModContent.GetInstance<T>()
Music Terraria.ModLoader.Mod.GetMusic (string name)
Shorthand for calling ModContent.GetMusic(this.FileName(name)).
Parameters
name The name.
Returns
Exceptions
MissingResourceException
Definition at line 1634 of file Mod.cs.
Referenced by Terraria.ModLoader.ModContent.GetMusic().
{
             if (!musics.TryGetValue(name, out var music))
                 throw new MissingResourceException(name);
             return music;
         }
ModNPC Terraria.ModLoader.Mod.GetNPC (string name)
Gets the ModNPC of this mod corresponding to the given name. Returns null if no ModNPC with the given name is found.
Parameters
name The name.
Returns
T Terraria.ModLoader.Mod.GetNPC< T > ()
Type Constraints
T : ModNPC
T : ModContent.GetInstance<T>()
ModPacket Terraria.ModLoader.Mod.GetPacket (int capacity = 256)
Creates a ModPacket object that you can write to and then send between servers and clients.
Parameters
capacity The capacity.
Returns
Exceptions
System.Exception Cannot get packet for " + Name + " because it does not exist on the other side
Definition at line 1693 of file Mod.cs.
References Terraria.ModLoader.ModNet.NetModCount.
{
             if (netID < 0)
                 throw new Exception("Cannot get packet for " + Name + " because it does not exist on the other side");
             var p = new ModPacket(MessageID.ModPacket, capacity + 5);
             if (ModNet.NetModCount < 256)
                 p.Write((byte)netID);
             else
                 p.Write(netID);
             p.netID = netID;
             return p;
         }
ModPlayer Terraria.ModLoader.Mod.GetPlayer (string name)
Gets the ModPlayer of this mod corresponding to the given name. Returns null if no ModPlayer with the given name is found.
Parameters
name The name.
Returns
T Terraria.ModLoader.Mod.GetPlayer< T > ()
Type Constraints
T : ModPlayer
T : ModContent.GetInstance<T>()
ModPrefix Terraria.ModLoader.Mod.GetPrefix (string name)
Gets the ModPrefix instance corresponding to the name. Because this method is in the Mod class, conflicts between mods are avoided. Returns null if no ModPrefix with the given name is found.
Parameters
name The name.
Returns
T Terraria.ModLoader.Mod.GetPrefix< T > ()
Same as the other GetPrefix, but assumes that the class name and internal name are the same.
Template Parameters
T
Returns
Type Constraints
T : ModPrefix
T : ModContent.GetInstance<T>()
ModProjectile Terraria.ModLoader.Mod.GetProjectile (string name)
Gets the ModProjectile of this mod corresponding to the given name. Returns null if no ModProjectile with the given name is found.
Parameters
name The name.
Returns
T Terraria.ModLoader.Mod.GetProjectile< T > ()
Type Constraints
T : ModProjectile
T : ModContent.GetInstance<T>()
SoundEffect Terraria.ModLoader.Mod.GetSound (string name)
Shorthand for calling ModContent.GetSound(this.FileName(name)).
Parameters
name The name.
Returns
Exceptions
MissingResourceException
Definition at line 1614 of file Mod.cs.
Referenced by Terraria.ModLoader.ModContent.GetSound().
{
             if (!sounds.TryGetValue(name, out var sound))
                 throw new MissingResourceException(name);
             return sound;
         }
int Terraria.ModLoader.Mod.GetSoundSlot (SoundType type, string name)
Shorthand for calling SoundLoader.GetSoundSlot(type, this.Name + '/' + name).
Parameters
type The type.
name The name.
Returns
ModSurfaceBgStyle Terraria.ModLoader.Mod.GetSurfaceBgStyle (string name)
Returns the surface background style corresponding to the given name.
Parameters
name The name.
Returns
T Terraria.ModLoader.Mod.GetSurfaceBgStyle< T > ()
Type Constraints
T : ModSurfaceBgStyle
T : ModContent.GetInstance<T>()
int Terraria.ModLoader.Mod.GetSurfaceBgStyleSlot (string name)
Returns the Slot of the surface background style corresponding to the given name.
Parameters
name The name.
Returns
int Terraria.ModLoader.Mod.GetSurfaceBgStyleSlot< T > ()
Type Constraints
T : ModSurfaceBgStyle
T : GetSurfaceBgStyleSlot
T : typeof
T : T
T : Name
Texture2D Terraria.ModLoader.Mod.GetTexture (string name)
Shorthand for calling ModContent.GetTexture(this.FileName(name)).
Exceptions
MissingResourceException
Definition at line 1578 of file Mod.cs.
{
             if (!textures.TryGetValue(name, out var t))
                 throw new MissingResourceException(name, textures.Keys);
             return t;
         }
ModTile Terraria.ModLoader.Mod.GetTile (string name)
Gets the ModTile of this mod corresponding to the given name. Returns null if no ModTile with the given name is found.
Parameters
name The name.
Returns
T Terraria.ModLoader.Mod.GetTile< T > ()
Same as the other GetTile, but assumes that the class name and internal name are the same.
Template Parameters
T
Returns
Type Constraints
T : ModTile
T : ModContent.GetInstance<T>()
ModTileEntity Terraria.ModLoader.Mod.GetTileEntity (string name)
Gets the ModTileEntity of this mod corresponding to the given name. Returns null if no ModTileEntity with the given name is found.
Parameters
name The name.
Returns
T Terraria.ModLoader.Mod.GetTileEntity< T > ()
Same as the other GetTileEntity, but assumes that the class name and internal name are the same.
Template Parameters
T
Returns
Type Constraints
T : ModTileEntity
T : ModContent.GetInstance<T>()
ModUgBgStyle Terraria.ModLoader.Mod.GetUgBgStyle (string name)
Returns the underground background style corresponding to the given name.
Parameters
name The name.
Returns
T Terraria.ModLoader.Mod.GetUgBgStyle< T > ()
Type Constraints
T : ModUgBgStyle
T : ModContent.GetInstance<T>()
ModWall Terraria.ModLoader.Mod.GetWall (string name)
Gets the ModWall of this mod corresponding to the given name. Returns null if no ModWall with the given name is found.
Parameters
name The name.
Returns
T Terraria.ModLoader.Mod.GetWall< T > ()
Type Constraints
T : ModWall
T : ModContent.GetInstance<T>()
ModWaterfallStyle Terraria.ModLoader.Mod.GetWaterfallStyle (string name)
Returns the waterfall style with the given name from this mod.
Parameters
name The name.
Returns
T Terraria.ModLoader.Mod.GetWaterfallStyle< T > ()
Type Constraints
T : ModWaterfallStyle
T : ModContent.GetInstance<T>()
int Terraria.ModLoader.Mod.GetWaterfallStyleSlot (string name)
Returns the waterfall style corresponding to the given name.
Parameters
name The name.
Returns
int Terraria.ModLoader.Mod.GetWaterfallStyleSlot< T > ()
Type Constraints
T : ModWaterfallStyle
T : GetWaterfallStyleSlot
T : typeof
T : T
T : Name
ModWaterStyle Terraria.ModLoader.Mod.GetWaterStyle (string name)
Returns the water style with the given name from this mod.
Parameters
name The name.
Returns
T Terraria.ModLoader.Mod.GetWaterStyle< T > ()
Type Constraints
T : ModWaterStyle
T : ModContent.GetInstance<T>()
virtual void Terraria.ModLoader.Mod.HandlePacket (BinaryReader reader, int whoAmI) virtual
Called whenever a net message / packet is received from a client (if this is a server) or the server (if this is a client). whoAmI is the ID of whomever sent the packet (equivalent to the Main.myPlayer of the sender), and reader is used to read the binary data of the packet.
Parameters
reader The reader.
whoAmI The player the message is from.
Definition at line 44 of file ModHooks.cs.
{
         }
virtual bool Terraria.ModLoader.Mod.HijackGetData (ref byte messageType, ref BinaryReader reader, int playerNumber) virtual
Allows you to modify net message / packet information that is received before the game can act on it.
Parameters
messageType Type of the message.
reader The reader.
playerNumber The player number the message is from.
Returns
Definition at line 54 of file ModHooks.cs.
{
             return false;
         }
virtual bool Terraria.ModLoader.Mod.HijackSendData (int whoAmI, int msgType, int remoteClient, int ignoreClient, NetworkText text, int number, float number2, float number3, float number4, int number5, int number6, int number7) virtual
Hijacks the send data method. Only use if you absolutely know what you are doing. If any hooks return true, the message is not sent.
Definition at line 61 of file ModHooks.cs.
Referenced by Terraria.ModLoader.ModNet.ReadNetIDs().
{
             return false;
         }
virtual void Terraria.ModLoader.Mod.HotKeyPressed (string name) virtual
Called when a hotkey is pressed. Check against the name to verify particular hotkey that was pressed. (Using the ModHotKey is more recommended.)
Parameters
name The display name of the hotkey.
Definition at line 36 of file ModHooks.cs.
{
         }
int Terraria.ModLoader.Mod.ItemType (string name)
Gets the internal ID / type of the ModItem corresponding to the name. Returns 0 if no ModItem with the given name is found.
Parameters
name The name.
Returns
Referenced by Terraria.ModLoader.ModRecipe.AddIngredient(), Terraria.ModLoader.IO.ItemIO.Load(), Terraria.ModLoader.IO.ItemIO.LoadLegacy(), and Terraria.ModLoader.ModRecipe.SetResult().
int Terraria.ModLoader.Mod.ItemType< T > ()
Same as the other ItemType, but assumes that the class name and internal name are the same.
Template Parameters
T
Returns
Type Constraints
T : ModItem
T : ModContent.ItemType<T>()
virtual void Terraria.ModLoader.Mod.Load () virtual
Override this method to add most of your content to your mod. Here you will call other methods such as AddItem. This is guaranteed to be called after all content has been autoloaded.
Definition at line 71 of file Mod.cs.
{
         }
Music Terraria.ModLoader.Mod.LoadMusic (string path, string extension) private
Definition at line 109 of file ModInternals.cs.
References Terraria.ModLoader.ModPrefix.AutoDefaults(), Terraria.ModLoader.ModProjectile.AutoStaticDefaults(), Terraria.ModLoader.ModItem.AutoStaticDefaults(), Terraria.ModLoader.ModNPC.AutoStaticDefaults(), Terraria.ModLoader.ModTile.chest, Terraria.ModLoader.ModContent.GetTexture(), Terraria.ModLoader.ModTile.HighlightTexture, Terraria.ModLoader.ModItem.item, Terraria.ModLoader.ModMountData.mountData, Terraria.ModLoader.ModNPC.npc, Terraria.ModLoader.ModProjectile.projectile, Terraria.ModLoader.GlobalWall.SetDefaults(), Terraria.ModLoader.ModBuff.SetDefaults(), Terraria.ModLoader.GlobalTile.SetDefaults(), Terraria.ModLoader.ModDust.SetDefaults(), Terraria.ModLoader.ModWall.SetDefaults(), Terraria.ModLoader.ModPrefix.SetDefaults(), Terraria.ModLoader.ModProjectile.SetStaticDefaults(), Terraria.ModLoader.ModItem.SetStaticDefaults(), Terraria.ModLoader.ModNPC.SetStaticDefaults(), Terraria.ModLoader.ModBuff.Type, Terraria.ModLoader.ModWaterStyle.Type, Terraria.ModLoader.ModWall.Type, Terraria.ModLoader.ModTile.Type, Terraria.ModLoader.ModMountData.Type, and Terraria.ModLoader.ModWaterfallStyle.Type.
{
             path = "tmod:"+Name+'/'+path+extension;
             switch (extension) {
                 case ".wav": return new MusicStreamingWAV(path);
                 case ".mp3": return new MusicStreamingMP3(path);
                 case ".ogg": return new MusicStreamingOGG(path);
             }
             throw new ResourceLoadException("Unknown music extension "+extension);
         }
virtual bool Terraria.ModLoader.Mod.LoadResource (string path, int length, Func< Stream > getStream) virtual
Hook for pre-loading resources
Parameters
path The path of the resource within the tmod
length The length of the uncompressed resource
getStream A function which returns a stream containing the file content
Returns
true if the file will no-longer be needed and should not be cached
Definition at line 149 of file Mod.cs.
{
             if (tModLoaderVersion < new Version(0, 11) && LoadResourceLegacy(path, length, getStream)) // TODO LoadResourceLegacy is marked obsolete
                 return false;
             string extension = Path.GetExtension(path).ToLower();
             path = Path.ChangeExtension(path, null);
             switch (extension) {
                 case ".png":
                 case ".rawimg":
                     if (!Main.dedServ)
                         LoadTexture(path, getStream(), extension == ".rawimg");
                     return true;
                 case ".wav":
                 case ".mp3":
                 case ".ogg":
                     //Main.engine == null would be more sensible, but only the waveBank fails on Linux when there is no audio hardware
                     if (Main.dedServ || Main.waveBank == null) { }
                     else if (path.Contains("Music/"))
                         musics[path] = LoadMusic(path, extension);
                     else
                         sounds[path] = LoadSound(getStream(), length, extension);
                     return true;
                 case ".xnb":
                     if (Main.dedServ) { }
                     else if (path.StartsWith("Fonts/"))
                         fonts[path] = Main.instance.OurLoad<DynamicSpriteFont>("tmod:"+Name+"/"+path);
                     else if (path.StartsWith("Effects/"))
                         effects[path] = Main.ShaderContentManager.Load<Effect>("tmod:"+Name+"/"+path);
                     else
                         throw new ResourceLoadException(Language.GetTextValue("tModLoader.LoadErrorUnknownXNBFileHint", path));
                     return true;
             }
             return false;
         }
virtual void Terraria.ModLoader.Mod.LoadResourceFromStream (string path, int len, BinaryReader reader) virtual
Definition at line 194 of file Mod.cs.
{
         }
bool Terraria.ModLoader.Mod.LoadResourceLegacy (string path, int length, Func< Stream > getStream) private
Definition at line 186 of file Mod.cs.
{
             using (var stream = getStream()) {
                 LoadResourceFromStream(path, length, new BinaryReader(stream));
                 return stream.Position > 0;
             }
         }
virtual void Terraria.ModLoader.Mod.LoadResources () virtual
Definition at line 109 of file Mod.cs.
{
             if (File == null)
                 return;
             fileHandle = File.Open();
             var skipCache = new HashSet<string>();
             foreach (var entry in File) {
                 Interface.loadMods.SubProgressText = entry.Name;
                 Stream _stream = null;
                 Stream GetStream() => _stream = File.GetStream(entry);
                 if (LoadResource(entry.Name, entry.Length, GetStream))
                     skipCache.Add(entry.Name);
                 _stream?.Dispose();
             }
             File.CacheFiles(skipCache);
         }
SoundEffect Terraria.ModLoader.Mod.LoadSound (Stream stream, int length, string extension) private
Definition at line 85 of file ModInternals.cs.
References Terraria.ModLoader.Audio.MusicStreamingOGG.Convert().
{
             switch (extension) {
                 case ".wav":
                     if (!stream.CanSeek)
                         stream = new MemoryStream(stream.ReadBytes(length));
                     return SoundEffect.FromStream(stream);
                 case ".mp3":
                     using (var mp3Stream = new MP3Stream(stream))
                     using (var ms = new MemoryStream()) {
                         mp3Stream.CopyTo(ms);
                         return new SoundEffect(ms.ToArray(), mp3Stream.Frequency, (AudioChannels)mp3Stream.ChannelCount);
                     }
                 case ".ogg":
                     using (var reader = new VorbisReader(stream, true)) {
                         var buffer = new byte[reader.TotalSamples * 2 * reader.Channels];
                         var floatBuf = new float[buffer.Length / 2];
                         reader.ReadSamples(floatBuf, 0, floatBuf.Length);
                         MusicStreamingOGG.Convert(floatBuf, buffer);
                         return new SoundEffect(buffer, reader.SampleRate, (AudioChannels)reader.Channels);
                     }
             }
             throw new ResourceLoadException("Unknown sound extension "+extension);
         }
void Terraria.ModLoader.Mod.LoadTexture (string path, Stream stream, bool rawimg) private
Definition at line 60 of file ModInternals.cs.
References Terraria.ModLoader.IO.ImageIO.PngToTexture2DAsync(), and Terraria.ModLoader.IO.ImageIO.RawToTexture2DAsync().
{
             try {
                 var texTask = rawimg
                     ? ImageIO.RawToTexture2DAsync(Main.instance.GraphicsDevice, new BinaryReader(stream))
                     : ImageIO.PngToTexture2DAsync(Main.instance.GraphicsDevice, stream);
                 AsyncLoadQueue.Enqueue(texTask.ContinueWith(t => {
                     if (t.Exception != null)
                         throw new ResourceLoadException(
                             Language.GetTextValue("tModLoader.LoadErrorTextureFailedToLoad", path), t.Exception);
                     var tex = t.Result;
                     tex.Name = Name + "/" + path;
                     lock (textures)
                         textures[path] = tex;
                 }));
             }
             catch (Exception e) {
                 throw new ResourceLoadException(Language.GetTextValue("tModLoader.LoadErrorTextureFailedToLoad", path), e);
             }
             finally {
                 stream.Close();
             }
         }
virtual void Terraria.ModLoader.Mod.MidUpdateDustTime () virtual
Called after Dust got updated, but before Time (day/night, events, etc.) gets updated.
If you are looking to hook an earlier part of the update process, see MidUpdateItemDust. If you are looking to hook a later part of the update process, see MidUpdateTimeWorld.
Definition at line 139 of file ModHooks.cs.
{
         }
virtual void Terraria.ModLoader.Mod.MidUpdateGoreProjectile () virtual
Called after Gores got updated, but before any Projectiles get updated.
If you are looking to hook an earlier part of the update process, see MidUpdateNPCGore. If you are looking to hook a later part of the update process, see MidUpdateProjectileItem.
Definition at line 112 of file ModHooks.cs.
{
         }
virtual void Terraria.ModLoader.Mod.MidUpdateInvasionNet () virtual
Called after Invasions got updated. The only thing that is updated after this is the Network.
If you are looking to hook an earlier part of the update process, see MidUpdateTimeWorld. If you are looking to hook even after the Network is updated, see PostUpdateEverything.
Definition at line 157 of file ModHooks.cs.
{
         }
virtual void Terraria.ModLoader.Mod.MidUpdateItemDust () virtual
Called after Items got updated, but before any Dust gets updated.
If you are looking to hook an earlier part of the update process, see MidUpdateProjectileItem. If you are looking to hook a later part of the update process, see MidUpdateDustTime.
Definition at line 130 of file ModHooks.cs.
{
         }
virtual void Terraria.ModLoader.Mod.MidUpdateNPCGore () virtual
Called after NPCs got updated, but before any Gores get updated.
If you are looking to hook an earlier part of the update process, see MidUpdatePlayerNPC. If you are looking to hook a later part of the update process, see MidUpdateGoreProjectile.
Definition at line 103 of file ModHooks.cs.
{
         }
virtual void Terraria.ModLoader.Mod.MidUpdatePlayerNPC () virtual
Called after Players got updated, but before any NPCs get updated.
If you are looking to hook an earlier part of the update process, see PreUpdateEntities. If you are looking to hook a later part of the update process, see MidUpdateNPCGore.
Definition at line 94 of file ModHooks.cs.
{
         }
virtual void Terraria.ModLoader.Mod.MidUpdateProjectileItem () virtual
Gets called immediately after all Projectiles are updated, but before any Items get updated.
If you are looking to hook an earlier part of the update process, see MidUpdateGoreProjectile. If you are looking to hook a later part of the update process, see MidUpdateItemDust.
Definition at line 121 of file ModHooks.cs.
{
         }
virtual void Terraria.ModLoader.Mod.MidUpdateTimeWorld () virtual
Called after Time got updated, but before the World gets updated.
If you are looking to hook an earlier part of the update process, see MidUpdateDustTime. If you are looking to hook a later part of the update process, see MidUpdateInvasionNet.
Definition at line 148 of file ModHooks.cs.
{
         }
virtual void Terraria.ModLoader.Mod.ModifyInterfaceLayers (List< GameInterfaceLayer > layers) virtual
Allows you to modify the elements of the in-game interface that get drawn. GameInterfaceLayer can be found in the Terraria.UI namespace. Check https://github.com/tModLoader/tModLoader/wiki/Vanilla-Interface-layers-values for vanilla interface layer names
Parameters
layers The layers.
Definition at line 172 of file ModHooks.cs.
{
         }
virtual void Terraria.ModLoader.Mod.ModifyLightingBrightness (ref float scale) virtual
Allows you to modify overall brightness of lights. Can be used to create effects similiar to what night vision and darkness (de)buffs give you. Values too high or too low might result in glitches. For night vision effect use scale 1.03
Parameters
scale Brightness scale
Definition at line 187 of file ModHooks.cs.
{
         }
virtual void Terraria.ModLoader.Mod.ModifySunLightColor (ref Color tileColor, ref Color backgroundColor) virtual
Allows you to modify color of light the sun emits.
Parameters
tileColor Tile lighting color
backgroundColor Background lighting color
Definition at line 180 of file ModHooks.cs.
{
         }
virtual void Terraria.ModLoader.Mod.ModifyTransformMatrix (ref SpriteViewMatrix Transform) virtual
Allows you to set the transformation of the screen that is drawn. (Translations, rotations, scales, etc.)
Definition at line 68 of file ModHooks.cs.
{
         }
int Terraria.ModLoader.Mod.MountType (string name)
Gets the ID of the ModMountData instance corresponding to the given name. Returns 0 if no ModMountData has the given name.
Parameters
name The name.
Returns
int Terraria.ModLoader.Mod.MountType< T > ()
Same as the other MountType, but assumes that the class name and internal name are the same.
Template Parameters
T
Returns
Type Constraints
T : ModMountData
T : ModContent.MountType<T>()
bool Terraria.ModLoader.Mod.MusicExists (string name)
Shorthand for calling ModLoader.MusicExists(this.FileName(name)).
Parameters
name The name.
Returns
Referenced by Terraria.ModLoader.ModContent.MusicExists().
int Terraria.ModLoader.Mod.NPCType (string name)
Gets the type of the ModNPC of this mod with the given name. Returns 0 if no ModNPC with the given name is found.
Parameters
name The name.
Returns
int Terraria.ModLoader.Mod.NPCType< T > ()
Same as the other NPCType, but assumes that the class name and internal name are the same.
Template Parameters
T
Returns
Type Constraints
T : ModNPC
T : ModContent.NPCType<T>()
virtual void Terraria.ModLoader.Mod.PostAddRecipes () virtual
This provides a hook into the mod-loading process immediately after recipes have been added. You can use this to edit recipes added by other mods.
Definition at line 106 of file Mod.cs.
{
         }
virtual void Terraria.ModLoader.Mod.PostDrawFullscreenMap (ref string mouseText) virtual
Called while the fullscreen map is active. Allows custom drawing to the map.
Parameters
mouseText The mouse text.
Definition at line 203 of file ModHooks.cs.
{
         }
virtual void Terraria.ModLoader.Mod.PostDrawInterface (SpriteBatch spriteBatch) virtual
Called after interface is drawn but right before mouse and mouse hover text is drawn. Allows for drawing interface.
Note: This hook should no longer be used. It is better to use the ModifyInterfaceLayers hook.
Parameters
spriteBatch The sprite batch.
Definition at line 196 of file ModHooks.cs.
{
         }
virtual void Terraria.ModLoader.Mod.PostSetupContent () virtual
Allows you to load things in your mod after its content has been setup (arrays have been resized to fit the content, etc).
Definition at line 77 of file Mod.cs.
{
         }
virtual void Terraria.ModLoader.Mod.PostUpdateEverything () virtual
Called after the Network got updated, this is the last hook that happens in an update.
If you are looking to hook an earlier part of the update process, see MidUpdateInvasionNet.
Definition at line 165 of file ModHooks.cs.
{
         }
virtual void Terraria.ModLoader.Mod.PostUpdateInput () virtual
Called after the input keys are polled. Allows for modifying things like scroll wheel if your custom drawing should capture that.
Definition at line 209 of file ModHooks.cs.
{
         }
byte Terraria.ModLoader.Mod.PrefixType (string name)
Gets the internal ID / type of the ModPrefix corresponding to the name. Returns 0 if no ModPrefix with the given name is found.
Parameters
name The name.
Returns
Referenced by Terraria.ModLoader.IO.ItemIO.Load().
byte Terraria.ModLoader.Mod.PrefixType< T > ()
Same as the other PrefixType, but assumes that the class name and internal name are the same.
Template Parameters
T
Returns
Type Constraints
T : ModPrefix
T : ModContent.PrefixType<T>()
virtual void Terraria.ModLoader.Mod.PreSaveAndQuit () virtual
Called in SP or Client when the Save and Quit button is pressed. One use for this hook is clearing out custom UI slots to return items to the player.
Definition at line 215 of file ModHooks.cs.
References Terraria.ModLoader.ModLoader.Mods.
{
         }
virtual void Terraria.ModLoader.Mod.PreUpdateEntities () virtual
Use this if you want to do something before anything in the World gets updated. Called after UI updates, but before anything in the World (Players, NPCs, Projectiles, Tiles) gets updated.
When Main.autoPause is true or Main.FrameSkipMode is 0 or 2, the game may do a partial update. This means that it only updates menus and some animations, but not the World or Entities. This hook - and every hook after it - only gets called on frames with a full update.
If you are looking to hook a later part of the update process, see MidUpdatePlayerNPC.
Definition at line 85 of file ModHooks.cs.
{
         }
int Terraria.ModLoader.Mod.ProjectileType (string name)
Gets the type of the ModProjectile of this mod with the given name. Returns 0 if no ModProjectile with the given name is found.
Parameters
name The name.
Returns
int Terraria.ModLoader.Mod.ProjectileType< T > ()
Same as the other ProjectileType, but assumes that the class name and internal name are the same.
Template Parameters
T
Returns
Type Constraints
T : ModProjectile
T : ModContent.ProjectileType<T>()
ModHotKey Terraria.ModLoader.Mod.RegisterHotKey (string name, string defaultKey)
Registers a hotkey with a name and defaultKey. Use the returned ModHotKey to detect when buttons are pressed. Do this in a ModPlayer.ProcessTriggers.
Parameters
name The name.
defaultKey The default key.
Returns
Definition at line 1527 of file Mod.cs.
{
             if (!loading)
                 throw new Exception("RegisterHotKey can only be called from Mod.Load or Mod.Autoload");
             return HotKeyLoader.RegisterHotKey(new ModHotKey(this, name, defaultKey));
         }
bool Terraria.ModLoader.Mod.SoundExists (string name)
Shorthand for calling ModLoader.SoundExists(this.FileName(name)).
Parameters
name The name.
Returns
Referenced by Terraria.ModLoader.ModContent.SoundExists().
bool Terraria.ModLoader.Mod.TextureExists (string name)
Shorthand for calling ModLoader.TextureExists(this.FileName(name)).
Parameters
name The name.
Returns
Referenced by Terraria.ModLoader.ModContent.TextureExists().
int Terraria.ModLoader.Mod.TileEntityType (string name)
Gets the type of the ModTileEntity of this mod with the given name. Returns -1 if no ModTileEntity with the given name is found.
Parameters
name The name.
Returns
int Terraria.ModLoader.Mod.TileEntityType< T > ()
Same as the other TileEntityType, but assumes that the class name and internal name are the same.
Template Parameters
T
Returns
Type Constraints
T : ModTileEntity
T : ModContent.TileEntityType<T>()
int Terraria.ModLoader.Mod.TileType (string name)
Gets the type of the ModTile of this mod with the given name. Returns 0 if no ModTile with the given name is found.
Parameters
name The name.
Returns
Referenced by Terraria.ModLoader.ModRecipe.AddTile().
int Terraria.ModLoader.Mod.TileType< T > ()
Same as the other TileType, but assumes that the class name and internal name are the same.
Template Parameters
T
Returns
Type Constraints
T : ModTile
T : ModContent.TileType<T>()
virtual void Terraria.ModLoader.Mod.Unload () virtual
This is called whenever this mod is unloaded from the game. Use it to undo changes that you've made in Load that aren't automatically handled (for example, modifying the texture of a vanilla item). Mods are guaranteed to be unloaded in the reverse order they were loaded in.
Definition at line 83 of file Mod.cs.
{
         }
virtual void Terraria.ModLoader.Mod.UpdateMusic (ref int music, ref MusicPriority priority) virtual
Allows you to determine what music should currently play.
Parameters
music The music.
priority The music priority.
Definition at line 20 of file ModHooks.cs.
{
             UpdateMusic(ref music);
         }
virtual void Terraria.ModLoader.Mod.UpdateMusic (ref int music) virtual
A legacy hook that you should no longer use. Use the version with two parameters instead.
Parameters
music
Definition at line 29 of file ModHooks.cs.
{
         }
virtual void Terraria.ModLoader.Mod.UpdateUI (GameTime gameTime) virtual
Ran every update and suitable for calling Update for UserInterface classes
Definition at line 74 of file ModHooks.cs.
{
         }
int Terraria.ModLoader.Mod.WallType (string name)
Gets the type of the ModWall of this mod with the given name. Returns 0 if no ModWall with the given name is found.
Parameters
name The name.
Returns
int Terraria.ModLoader.Mod.WallType< T > ()
Same as the other WallType, but assumes that the class name and internal name are the same.
Template Parameters
T
Returns
Type Constraints
T : ModWall
T : ModContent.WallType<T>()
Member Data Documentation
readonly Queue<Task> Terraria.ModLoader.Mod.AsyncLoadQueue = new Queue<Task>() private
Definition at line 26 of file ModInternals.cs.
IDisposable Terraria.ModLoader.Mod.fileHandle private
Definition at line 65 of file Mod.cs.
bool Terraria.ModLoader.Mod.IsNetSynced => netID >= 0
Definition at line 63 of file Mod.cs.
virtual string Terraria.ModLoader.Mod.Name => File.name
Stores the name of the mod. This name serves as the mod's identification, and also helps with saving everything your mod adds. By default this returns the name of the folder that contains all your code and stuff.
Definition at line 42 of file Mod.cs.
Referenced by Terraria.ModLoader.ModRecipe.AddIngredient(), Terraria.ModLoader.ModRecipe.AddTile(), Terraria.ModLoader.Mod.AutoloadBuff(), Terraria.ModLoader.Mod.AutoloadDust(), Terraria.ModLoader.Mod.AutoloadGlobalBgStyle(), Terraria.ModLoader.Mod.AutoloadGlobalBuff(), Terraria.ModLoader.Mod.AutoloadGlobalItem(), Terraria.ModLoader.Mod.AutoloadGlobalNPC(), Terraria.ModLoader.Mod.AutoloadGlobalProjectile(), Terraria.ModLoader.Mod.AutoloadGlobalRecipe(), Terraria.ModLoader.Mod.AutoloadGlobalTile(), Terraria.ModLoader.Mod.AutoloadGlobalWall(), Terraria.ModLoader.Mod.AutoloadItem(), Terraria.ModLoader.Mod.AutoloadModWorld(), Terraria.ModLoader.Mod.AutoloadMountData(), Terraria.ModLoader.Mod.AutoloadNPC(), Terraria.ModLoader.Mod.AutoloadPlayer(), Terraria.ModLoader.Mod.AutoloadPrefix(), Terraria.ModLoader.Mod.AutoloadProjectile(), Terraria.ModLoader.Mod.AutoloadSurfaceBgStyle(), Terraria.ModLoader.Mod.AutoloadTile(), Terraria.ModLoader.Mod.AutoloadTileEntity(), Terraria.ModLoader.Mod.AutoloadUgBgStyle(), Terraria.ModLoader.Mod.AutoloadWall(), Terraria.ModLoader.Mod.AutoloadWaterfallStyle(), Terraria.ModLoader.Mod.AutoloadWaterStyle(), Terraria.ModLoader.Exceptions.CustomModDataException.CustomModDataException(), Terraria.ModLoader.IO.ItemIO.LoadLegacy(), Terraria.ModLoader.IO.ItemIO.Save(), Terraria.ModLoader.PlayerHooks.SendCustomBiomes(), Terraria.ModLoader.ModRecipe.SetResult(), Terraria.ModLoader.ModNet.SetupDiagnostics(), Terraria.ModLoader.MonoModHooks.StringRep(), and Terraria.ModLoader.TooltipLine.TooltipLine().
virtual Version Terraria.ModLoader.Mod.Version => File.version
This version number of this mod.
Definition at line 50 of file Mod.cs.
Property Documentation
Assembly Terraria.ModLoader.Mod.Code get set
The assembly code this is loaded when tModLoader loads this mod.
Definition at line 33 of file Mod.cs.
string Terraria.ModLoader.Mod.DisplayName get set
The display name of this mod in the Mods menu.
Definition at line 60 of file Mod.cs.
virtual uint Terraria.ModLoader.Mod.ExtraPlayerBuffSlots get
The amount of extra buff slots this mod desires for Players. This value is checked after Mod.Load but before Mod.PostSetupContent. The actual number of buffs the player can use will be 22 plus the max value of all enabled mods. In-game use Player.MaxBuffs to check the maximum number of buffs.
Definition at line 89 of file Mod.cs.
ILog Terraria.ModLoader.Mod.Logger get set
A logger with this mod's name for easy logging.
Definition at line 37 of file Mod.cs.
ModProperties Terraria.ModLoader.Mod.Properties get protected set
Definition at line 52 of file Mod.cs.
ModSide Terraria.ModLoader.Mod.Side = ModProperties.AutoLoadAll get set
The ModSide that controls how this mod is synced between client and server.
Definition at line 56 of file Mod.cs.
Version Terraria.ModLoader.Mod.tModLoaderVersion get set
The version of tModLoader that was being used when this mod was built.
Definition at line 46 of file Mod.cs.