Terraria ModLoader: Terraria.ModLoader.Default.MysteryTilesWorld Class Reference
Terraria.ModLoader.Default.MysteryTilesWorld Class Reference
Inherits Terraria.ModLoader.ModWorld.
Public Member Functions
override void Initialize ()
Called whenever the world is loaded. This can be used to initialize data structures, etc.
override void Load (TagCompound tag)
Allows you to load custom data you have saved for this world.
override void LoadLegacy (BinaryReader reader)
Allows you to load pre-v0.9 custom data you have saved for this world.
override TagCompound Save ()
Allows you to save custom data for this world. Useful for things like saving world specific flags. For example, if your mod adds a boss and you want certain NPC to only spawn once it has been defeated, this is where you would store the information that that boss has been defeated in this world. Returns null by default.
Public Member Functions inherited from Terraria.ModLoader.ModWorld
virtual bool Autoload (ref string name)
Allows you to automatically add a ModWorld instead of using Mod.AddModWorld. Return true to allow autoloading; by default returns the mod's autoload property. Name is initialized to the overriding class name. Use this to either force or stop an autoload, or change the name that identifies this type of ModWorld.
virtual void ChooseWaterStyle (ref int style)
Allows you to change the water style (determines water color) that is currently being used.
virtual void ModifyWorldGenTasks (List< GenPass > tasks, ref float totalWeight)
A more advanced option to PostWorldGen, this method allows you modify the list of Generation Passes before a new world begins to be generated. For example, removing the "Planting Trees" pass will cause a world to generate without trees. Placing a new Generation Pass before the "Dungeon" pass will prevent the the mod's pass from cutting into the dungeon.
virtual void NetReceive (BinaryReader reader)
Allows you to do things with custom data that is received between clients and server.
virtual void NetSend (BinaryWriter writer)
Allows you to send custom data between clients and server. This is useful for syncing information such as bosses that have been defeated.
virtual void PostDrawTiles ()
Called after drawing Tiles. Can be used for drawing a tile overlay akin to wires. Note that spritebatch should be begun and ended within this method.
virtual void PostUpdate ()
Use this method to have things happen in the world. In vanilla Terraria, a good example of code suitable for this hook is how Falling Stars fall to the ground during the night. This hook is called every frame.
virtual void PostWorldGen ()
Use this method to place tiles in the world after world generation is complete.
virtual void PreUpdate ()
Use this method to have things happen in the world. In vanilla Terraria, a good example of code suitable for this hook is how Falling Stars fall to the ground during the night. This hook is called every frame.
virtual void PreWorldGen ()
Allows a mod to run code before a world is generated.
virtual void ResetNearbyTileEffects ()
Use this to reset any fields you set in any of your ModTile.NearbyEffects hooks back to their default values.
virtual void TileCountsAvailable (int[] tileCounts)
Allows you to store information about how many of each tile is nearby the player. This is useful for counting how many tiles of a certain custom biome there are. The tileCounts parameter stores the tile count indexed by tile type.
Private Member Functions
void ConfirmPendingInfo ()
void RestoreTiles (List< ushort > canRestore)
Private Attributes
List< MysteryTileInfo > infos = new List<MysteryTileInfo>()
Additional Inherited Members
Properties inherited from Terraria.ModLoader.ModWorld
Mod mod [get, set]
The mod that added this type of ModWorld.
string Name [get, set]
The name of this ModWorld. Used for distinguishing between multiple ModWorlds added by a single Mod.
Detailed Description
Definition at line 8 of file MysteryTilesWorld.cs.
Member Function Documentation
ConfirmPendingInfo()
void Terraria.ModLoader.Default.MysteryTilesWorld.ConfirmPendingInfo () private
Definition at line 121 of file MysteryTilesWorld.cs.
References Terraria.ModLoader.Default.MysteryTileFrame.FrameID, Terraria.ModLoader.Default.MysteryTileFrame.FrameX, Terraria.ModLoader.Default.MysteryTileFrame.FrameY, Terraria.ModLoader.ModLoader.GetMod(), and Terraria.ModLoader.Mod.TileType().
         {
             List<int> truePendingID = new List<int>();
             int nextID = 0;
             for (int k = 0; k < pendingInfos.Count; k++)
             {
                 while (nextID < infos.Count && infos[nextID] != null)
                 {
                     nextID++;
                 }
                 if (nextID == infos.Count)
                 {
                     infos.Add(pendingInfos[k]);
                 }
                 else
                 {
                     infos[nextID] = pendingInfos[k];
                 }
                 truePendingID.Add(nextID);
             }
             ushort pendingType = (ushort)ModLoader.GetMod("ModLoader").TileType("PendingMysteryTile");
             ushort mysteryType = (ushort)ModLoader.GetMod("ModLoader").TileType("MysteryTile");
             for (int x = 0; x < Main.maxTilesX; x++)
             {
                 for (int y = 0; y < Main.maxTilesY; y++)
                 {
                     if (Main.tile[x, y].type == pendingType)
                     {
                         Tile tile = Main.tile[x, y];
                         MysteryTileFrame frame = new MysteryTileFrame(tile.frameX, tile.frameY);
                         frame = new MysteryTileFrame(truePendingID[frame.FrameID]);
                         tile.type = mysteryType;
                         tile.frameX = frame.FrameX;
                         tile.frameY = frame.FrameY;
                     }
                 }
             }
         }
Initialize()
override void Terraria.ModLoader.Default.MysteryTilesWorld.Initialize () virtual
Called whenever the world is loaded. This can be used to initialize data structures, etc.
Reimplemented from Terraria.ModLoader.ModWorld.
Definition at line 13 of file MysteryTilesWorld.cs.
         {
             infos.Clear();
             pendingInfos.Clear();
         }
Load()
override void Terraria.ModLoader.Default.MysteryTilesWorld.Load (TagCompound tag) virtual
Allows you to load custom data you have saved for this world.
Reimplemented from Terraria.ModLoader.ModWorld.
Definition at line 26 of file MysteryTilesWorld.cs.
References Terraria.ModLoader.ModLoader.GetMod(), and Terraria.ModLoader.Mod.TileType().
         {
             List<ushort> canRestore = new List<ushort>();
             bool canRestoreFlag = false;
             foreach (var infoTag in tag.GetList<TagCompound>("list"))
             {
                 if (!infoTag.ContainsKey("mod"))
                 {
                     infos.Add(null);
                     canRestore.Add(0);
                     continue;
                 }
                 string modName = infoTag.GetString("mod");
                 string name = infoTag.GetString("name");
                 bool frameImportant = infoTag.ContainsKey("frameX");
                 var info = frameImportant ?
                     new MysteryTileInfo(modName, name, infoTag.GetShort("frameX"), infoTag.GetShort("frameY")) :
                     new MysteryTileInfo(modName, name);
                 infos.Add(info);
                 int type = ModLoader.GetMod(modName)?.TileType(name) ?? 0;
                 canRestore.Add((ushort) type);
                 if (type != 0)
                     canRestoreFlag = true;
             }
             if (canRestoreFlag)
             {
                 RestoreTiles(canRestore);
                 for (int k = 0; k < canRestore.Count; k++)
                 {
                     if (canRestore[k] > 0)
                     {
                         infos[k] = null;
                     }
                 }
             }
             if (pendingInfos.Count > 0)
             {
                 ConfirmPendingInfo();
             }
         }
LoadLegacy()
override void Terraria.ModLoader.Default.MysteryTilesWorld.LoadLegacy (BinaryReader reader) virtual
Allows you to load pre-v0.9 custom data you have saved for this world.
Reimplemented from Terraria.ModLoader.ModWorld.
Definition at line 69 of file MysteryTilesWorld.cs.
         {
             var list = new List<TagCompound>();
             int count = reader.ReadInt32();
             for (int k = 0; k < count; k++)
             {
                 string modName = reader.ReadString();
                 if (modName.Length == 0)
                 {
                     list.Add(new TagCompound());
                 }
                 else
                 {
                     var tag = new TagCompound {
                         ["mod"] = modName,
                         ["name"] = reader.ReadString(),
                     };
                     if (reader.ReadBoolean())
                     {
                         tag.Set("frameX", reader.ReadInt16());
                         tag.Set("frameY", reader.ReadInt16());
                     }
                     list.Add(tag);
                 }
             }
             Load(new TagCompound {["list"] = list});
         }
RestoreTiles()
void Terraria.ModLoader.Default.MysteryTilesWorld.RestoreTiles (List< ushort > canRestore) private
Definition at line 97 of file MysteryTilesWorld.cs.
References Terraria.ModLoader.Default.MysteryTileFrame.FrameID, Terraria.ModLoader.Default.MysteryTileInfo.frameX, Terraria.ModLoader.Default.MysteryTileInfo.frameY, Terraria.ModLoader.ModLoader.GetMod(), and Terraria.ModLoader.Mod.TileType().
         {
             ushort mysteryType = (ushort)ModLoader.GetMod("ModLoader").TileType("MysteryTile");
             for (int x = 0; x < Main.maxTilesX; x++)
             {
                 for (int y = 0; y < Main.maxTilesY; y++)
                 {
                     if (Main.tile[x, y].type == mysteryType)
                     {
                         Tile tile = Main.tile[x, y];
                         MysteryTileFrame frame = new MysteryTileFrame(tile.frameX, tile.frameY);
                         int frameID = frame.FrameID;
                         if (canRestore[frameID] > 0)
{
                             MysteryTileInfo info = infos[frameID];
                             tile.type = canRestore[frameID];
                             tile.frameX = info.frameX;
                             tile.frameY = info.frameY;
                         }
                     }
                 }
             }
         }
Save()
override TagCompound Terraria.ModLoader.Default.MysteryTilesWorld.Save () virtual
Allows you to save custom data for this world. Useful for things like saving world specific flags. For example, if your mod adds a boss and you want certain NPC to only spawn once it has been defeated, this is where you would store the information that that boss has been defeated in this world. Returns null by default.
Reimplemented from Terraria.ModLoader.ModWorld.
Definition at line 19 of file MysteryTilesWorld.cs.
         {
             return new TagCompound {
                 ["list"] = infos.Select(info => info?.Save() ?? new TagCompound()).ToList()
             };
         }
Member Data Documentation
infos
List<MysteryTileInfo> Terraria.ModLoader.Default.MysteryTilesWorld.infos = new List<MysteryTileInfo>() private
Definition at line 10 of file MysteryTilesWorld.cs.