Terraria ModLoader: Terraria.ModLoader.ModNPC Class Reference
Terraria.ModLoader.ModNPC Class Reference
This class serves as a place for you to place all your properties and hooks for each NPC. Create instances of ModNPC (preferably overriding this class) to pass as parameters to Mod.AddNPC.
Public Member Functions
ModNPC ()
ModNPC constructor.
virtual void AI ()
Allows you to determine how this NPC behaves. This will only be called if PreAI returns true.
virtual bool Autoload (ref string name, ref string texture, ref string[] altTextures)
Allows you to automatically load an NPC instead of using Mod.AddNPC. Return true to allow autoloading; by default returns the mod's autoload property. Name is initialized to the overriding class name, texture is initialized to the namespace and overriding class name with periods replaced with slashes, and altTextures is initialized to null. Use this method to either force or stop an autoload, to change the default display name and texture path, or to give the NPC alternate textures.
virtual void AutoloadHead (ref string headTexture, ref string bossHeadTexture)
Allows you to control the path to this NPC's head texture when it is autoloaded. The headTexture defaults to the default NPC texture plus "_Head", and the bossHeadTexture defaults to the default headTexture plus "_Head_Boss". If the textures don't exist, the NPC will not be given a head texture. The headTexture should be used for town NPCs, and the bossHeadTexture should be used for any non-town NPC that you want to display on the map.
virtual void BossHeadRotation (ref float rotation)
Allows you to customize the rotation of this NPC's boss head icon on the map.
virtual void BossHeadSlot (ref int index)
Allows you to customize the boss head texture used by this NPC based on its state.
virtual void BossHeadSpriteEffects (ref SpriteEffects spriteEffects)
Allows you to flip this NPC's boss head icon on the map.
virtual void BossLoot (ref string name, ref int potionType)
Allows you to customize what happens when this boss dies, such as which name is displayed in the defeat message and what type of potion it drops.
virtual bool CanBeHitByItem (Player player, Item item)
Allows you to determine whether this NPC can be hit by the given melee weapon when swung. Return true to allow hitting the NPC, return false to block hitting the NPC, and return null to use the vanilla code for whether the NPC can be hit. Returns null by default.
virtual bool CanBeHitByProjectile (Projectile projectile)
Allows you to determine whether this NPC can be hit by the given projectile. Return true to allow hitting the NPC, return false to block hitting the NPC, and return null to use the vanilla code for whether the NPC can be hit. Returns null by default.
virtual bool CanHitNPC (NPC target)
Allows you to determine whether this NPC can hit the given friendly NPC. Return true to allow hitting the target, return false to block this NPC from hitting the target, and return null to use the vanilla code for whether the target can be hit. Returns null by default.
virtual bool CanHitPlayer (Player target, ref int cooldownSlot)
Allows you to determine whether this NPC can hit the given player. Return false to block this NPC from hitting the target. Returns true by default. CooldownSlot determines which of the player's cooldown counters to use (-1, 0, or 1), and defaults to -1.
virtual float CanSpawn (NPCSpawnInfo spawnInfo)
Whether or not this NPC can spawn with the given spawning conditions. Return the weight for the chance of this NPC to spawn compared to vanilla mobs. All vanilla mobs combined have a total weight of 1. Returns 0 by default, which disables natural spawning.
virtual bool CanTownNPCSpawn (int numTownNPCs, int money)
Whether or not the conditions have been met for this town NPC to be able to move into town. For example, the Demolitionist requires that any player has an explosive.
virtual bool CheckActive ()
Whether or not to run the code for checking whether this NPC will remain active. Return false to stop this NPC from being despawned and to stop this NPC from counting towards the limit for how many NPCs can exist near a player. Returns true by default.
virtual bool CheckConditions (int left, int right, int top, int bottom)
Allows you to define special conditions required for this town NPC's house. For example, Truffle requires the house to be in an aboveground mushroom biome.
virtual bool CheckDead ()
Whether or not this NPC should be killed when it reaches 0 health. You may program extra effects in this hook (for example, how Golem's head lifts up for the second phase of its fight). Return false to stop this NPC from being killed. Returns true by default.
virtual void DrawEffects (ref Color drawColor)
Allows you to add special visual effects to this NPC (such as creating dust), and modify the color in which the NPC is drawn.
virtual bool DrawHealthBar (byte hbPosition, ref float scale, ref Vector2 position)
Allows you to control how the health bar for this NPC is drawn. The hbPosition parameter is the same as Main.hbPosition; it determines whether the health bar gets drawn above or below the NPC by default. The scale parameter is the health bar's size. By default, it will be the normal 1f; most bosses set this to 1.5f. Return null to let the normal vanilla health-bar-drawing code to run. Return false to stop the health bar from being drawn. Return true to draw the health bar in the position specified by the position parameter (note that this is the world position, not screen position).
virtual void DrawTownAttackGun (ref float scale, ref int item, ref int closeness)
Allows you to customize how this town NPC's weapon is drawn when this NPC is shooting (this NPC must have an attack type of 1). Scale is a multiplier for the item's drawing size, item is the ID of the item to be drawn, and closeness is how close the item should be drawn to the NPC.
virtual void DrawTownAttackSwing (ref Texture2D item, ref int itemSize, ref float scale, ref Vector2 offset)
Allows you to customize how this town NPC's weapon is drawn when this NPC is swinging it (this NPC must have an attack type of 3). Item is the Texture2D instance of the item to be drawn (use Main.itemTexture[id of item]), itemSize is the width and height of the item's hitbox (the same values for TownNPCAttackSwing), scale is the multiplier for the item's drawing size, and offset is the offset from which to draw the item from its normal position.
virtual void FindFrame (int frameHeight)
Allows you to modify the frame from this NPC's texture that is drawn, which is necessary in order to animate NPCs.
virtual Color GetAlpha (Color drawColor)
Allows you to determine the color and transparency in which this NPC is drawn. Return null to use the default color (normally light and buff color). Returns null by default.
virtual string GetChat ()
Allows you to give this town NPC a chat message when a player talks to it. By default returns something embarrassing.
virtual void HitEffect (int hitDirection, double damage)
Allows you to make things happen whenever this NPC is hit, such as creating dust or gores.
virtual void ModifyHitByItem (Player player, Item item, ref int damage, ref float knockback, ref bool crit)
Allows you to modify the damage, knockback, etc., that this NPC takes from a melee weapon.
virtual void ModifyHitByProjectile (Projectile projectile, ref int damage, ref float knockback, ref bool crit, ref int hitDirection)
Allows you to modify the damage, knockback, etc., that this NPC takes from a projectile.
virtual void ModifyHitNPC (NPC target, ref int damage, ref float knockback, ref bool crit)
Allows you to modify the damage, knockback, etc., that this NPC does to a friendly NPC.
virtual void ModifyHitPlayer (Player target, ref int damage, ref bool crit)
Allows you to modify the damage, etc., that this NPC does to a player.
virtual void NPCLoot ()
Allows you to make things happen when this NPC dies (for example, dropping items).
virtual void OnChatButtonClicked (bool firstButton, ref bool shop)
Allows you to make something happen whenever a button is clicked on this town NPC's chat window. The firstButton parameter tells whether the first button or second button (button and button2 from SetChatButtons) was clicked. Set the shop parameter to true to open this NPC's shop.
virtual void OnHitByItem (Player player, Item item, int damage, float knockback, bool crit)
Allows you to create special effects when this NPC is hit by a melee weapon.
virtual void OnHitByProjectile (Projectile projectile, int damage, float knockback, bool crit)
Allows you to create special effects when this NPC is hit by a projectile.
virtual void OnHitNPC (NPC target, int damage, float knockback, bool crit)
Allows you to create special effects when this NPC hits a friendly NPC.
virtual void OnHitPlayer (Player target, int damage, bool crit)
Allows you to create special effects when this NPC hits a player (for example, inflicting debuffs).
virtual void PostAI ()
virtual void PostDraw (SpriteBatch spriteBatch, Color drawColor)
Allows you to draw things in front of this NPC. This method is called even if PreDraw returns false.
virtual bool PreAI ()
Allows you to determine how this NPC behaves. Return false to stop the vanilla AI and the AI hook from being run. Returns true by default.
virtual bool PreDraw (SpriteBatch spriteBatch, Color drawColor)
Allows you to draw things behind this NPC, or to modify the way this NPC is drawn. Return false to stop the game from drawing the NPC (useful if you're manually drawing the NPC). Returns true by default.
virtual bool PreNPCLoot ()
Allows you to determine whether or not this NPC will drop anything at all. Return false to stop the NPC from dropping anything. Returns true by default.
virtual void ReceiveExtraAI (BinaryReader reader)
Use this to receive information that was sent in SendExtraAI.
virtual void ResetEffects ()
This is where you reset any fields you add to your subclass to their default states. This is necessary in order to reset your fields if they are conditionally set by a tick update but the condition is no longer satisfied. (Note: This hook is only really useful for GlobalNPC, but is included in ModNPC for completion.)
virtual void ScaleExpertStats (int numPlayers, float bossLifeScale)
Allows you to customize this NPC's stats in expert mode. This is useful because expert mode's doubling of damage and life might be too much sometimes (for example, with bosses). Also useful for scaling life with the number of players in the world.
virtual void SendExtraAI (BinaryWriter writer)
If you are storing AI information outside of the npc.ai array, use this to send that AI information between clients and servers.
virtual void SetChatButtons (ref string button, ref string button2)
Allows you to set the text for the buttons that appear on this town NPC's chat window. A parameter left as an empty string will not be included as a button on the chat window.
virtual void SetDefaults ()
Allows you to set all your NPC's properties, such as width, damage, aiStyle, lifeMax, etc.
virtual void SetStaticDefaults ()
Allows you to set all your NPC's static properties, such as names/translations and the arrays in NPCID.Sets.
virtual void SetupShop (Chest shop, ref int nextSlot)
Allows you to add items to this town NPC's shop. Add an item by setting the defaults of shop.item[nextSlot] then incrementing nextSlot. In the end, nextSlot must have a value of 1 greater than the highest index in shop.item that contains an item.
virtual int SpawnNPC (int tileX, int tileY)
Allows you to customize how this NPC is created when it naturally spawns (for example, its position or ai array). Return the return value of NPC.NewNPC. By default this method spawns this NPC on top of the tile at the given coordinates.
virtual bool StrikeNPC (ref double damage, int defense, ref float knockback, int hitDirection, ref bool crit)
Allows you to use a custom damage formula for when this NPC takes damage from any source. For example, you can change the way defense works or use a different crit multiplier. Return false to stop the game from running the vanilla damage formula; returns true by default.
virtual void TownNPCAttackCooldown (ref int cooldown, ref int randExtraCooldown)
Allows you to determine the cooldown between each of this town NPC's attack. The cooldown will be a number greater than or equal to the first parameter, and less then the sum of the two parameters.
virtual void TownNPCAttackMagic (ref float auraLightMultiplier)
Allows you to control the brightness of the light emitted by this town NPC's aura when it performs a magic attack. Only used when the town NPC has an attack type of 2 (magic)
virtual void TownNPCAttackProj (ref int projType, ref int attackDelay)
Allows you to determine the projectile type of this town NPC's attack, and how long it takes for the projectile to actually appear. This hook is only used when the town NPC has an attack type of 0 (throwing), 1 (shooting), or 2 (magic).
virtual void TownNPCAttackProjSpeed (ref float multiplier, ref float gravityCorrection, ref float randomOffset)
Allows you to determine the speed at which this town NPC throws a projectile when it attacks. Multiplier is the speed of the projectile, gravityCorrection is how much extra the projectile gets thrown upwards, and randomOffset allows you to randomize the projectile's velocity in a square centered around the original velocity. This hook is only used when the town NPC has an attack type of 0 (throwing), 1 (shooting), or 2 (magic).
virtual void TownNPCAttackShoot (ref bool inBetweenShots)
Allows you to tell the game that this town NPC has already created a projectile and will still create more projectiles as part of a single attack so that the game can animate the NPC's attack properly. Only used when the town NPC has an attack type of 1 (shooting).
virtual void TownNPCAttackStrength (ref int damage, ref float knockback)
Allows you to determine the damage and knockback of this town NPC's attack before the damage is scaled. (More information on scaling in GlobalNPC.BuffTownNPCs.)
virtual void TownNPCAttackSwing (ref int itemWidth, ref int itemHeight)
Allows you to determine the width and height of the item this town NPC swings when it attacks, which controls the range of this NPC's swung weapon. Only used when the town NPC has an attack type of 3 (swinging).
virtual string TownNPCName ()
Allows you to give this town NPC any name when it spawns. By default returns something embarrassing.
virtual void UpdateLifeRegen (ref int damage)
Allows you to make the NPC either regenerate health or take damage over time by setting npc.lifeRegen. Regeneration or damage will occur at a rate of half of npc.lifeRegen per second. The damage parameter is the number that appears above the NPC's head if it takes damage over time.
virtual bool UsesPartyHat ()
Allows you to determine whether this town NPC wears a party hat during a party. Returns true by default.
Public Attributes
int aiType = 0
Determines which type of vanilla NPC this ModNPC will copy the behavior (AI) of. Leave as 0 to not copy any behavior. Defaults to 0.
int animationType = 0
Determines which type of vanilla NPC this ModNPC will copy the animation (FindFrame) of. Leave as 0 to not copy any animation. Defaults to 0.
int banner = 0
The type of NPC that this NPC will be considered as when determining banner drops and banner bonuses. By default this will be 0, which means this NPC is not associated with any banner. To give your NPC its own banner, set this field to the NPC's type.
int bannerItem = 0
The type of the item this NPC drops for every 50 times it is defeated. For any ModNPC whose banner field is set to the type of this NPC, that ModNPC will drop this banner.
int bossBag = -1
The item type of the boss bag that is dropped when DropBossBags is called for this NPC.
virtual bool CloneNewInstances => false
Whether instances of this ModNPC are created through a memberwise clone or its constructor. Defaults to false.
float drawOffsetY = 0f
The vertical offset used for drawing this NPC. Defaults to 0.
int music = -1
The ID of the music that plays when this NPC is on or near the screen. Defaults to -1, which means music plays normally.
Properties
ModTranslation DisplayName [get, set]
The translations for the display name of this NPC.
Mod mod [get, set]
The mod that added this ModNPC.
string Name [get, set]
The internal name of this NPC.
NPC npc [get, set]
The NPC object that this ModNPC controls.
Detailed Description
This class serves as a place for you to place all your properties and hooks for each NPC. Create instances of ModNPC (preferably overriding this class) to pass as parameters to Mod.AddNPC.
Definition at line 12 of file ModNPC.cs.
Constructor & Destructor Documentation
Terraria.ModLoader.ModNPC.ModNPC ()
ModNPC constructor.
Definition at line 95 of file ModNPC.cs.
         {
             npc = new NPC();
         }
Member Function Documentation
virtual void Terraria.ModLoader.ModNPC.AI () virtual
Allows you to determine how this NPC behaves. This will only be called if PreAI returns true.
Definition at line 177 of file ModNPC.cs.
         {
         }
virtual bool Terraria.ModLoader.ModNPC.Autoload (ref string name, ref string texture, ref string[] altTextures) virtual
Allows you to automatically load an NPC instead of using Mod.AddNPC. Return true to allow autoloading; by default returns the mod's autoload property. Name is initialized to the overriding class name, texture is initialized to the namespace and overriding class name with periods replaced with slashes, and altTextures is initialized to null. Use this method to either force or stop an autoload, to change the default display name and texture path, or to give the NPC alternate textures.
Parameters
name
texture
altTextures
Returns
Definition at line 107 of file ModNPC.cs.
Referenced by Terraria.ModLoader.Mod.AutoloadNPC().
         {
             return mod.Properties.Autoload;
         }
virtual void Terraria.ModLoader.ModNPC.AutoloadHead (ref string headTexture, ref string bossHeadTexture) virtual
Allows you to control the path to this NPC's head texture when it is autoloaded. The headTexture defaults to the default NPC texture plus "_Head", and the bossHeadTexture defaults to the default headTexture plus "_Head_Boss". If the textures don't exist, the NPC will not be given a head texture. The headTexture should be used for town NPCs, and the bossHeadTexture should be used for any non-town NPC that you want to display on the map.
Parameters
headTexture
bossHeadTexture
Definition at line 117 of file ModNPC.cs.
References Terraria.ModLoader.ModNPC.mod, Terraria.ModLoader.ModNPC.npc, and Terraria.ModLoader.ModNPC.SetDefaults().
Referenced by Terraria.ModLoader.Mod.AutoloadNPC().
         {
         }
virtual void Terraria.ModLoader.ModNPC.BossHeadRotation (ref float rotation) virtual
Allows you to customize the rotation of this NPC's boss head icon on the map.
Parameters
rotation
Definition at line 427 of file ModNPC.cs.
         {
         }
virtual void Terraria.ModLoader.ModNPC.BossHeadSlot (ref int index) virtual
Allows you to customize the boss head texture used by this NPC based on its state.
Parameters
index
Definition at line 419 of file ModNPC.cs.
         {
         }
virtual void Terraria.ModLoader.ModNPC.BossHeadSpriteEffects (ref SpriteEffects spriteEffects) virtual
Allows you to flip this NPC's boss head icon on the map.
Parameters
spriteEffects
Definition at line 435 of file ModNPC.cs.
         {
         }
virtual void Terraria.ModLoader.ModNPC.BossLoot (ref string name, ref int potionType) virtual
Allows you to customize what happens when this boss dies, such as which name is displayed in the defeat message and what type of potion it drops.
Parameters
name
potionType
Definition at line 266 of file ModNPC.cs.
         {
         }
virtual bool Terraria.ModLoader.ModNPC.CanBeHitByItem (Player player, Item item) virtual
Allows you to determine whether this NPC can be hit by the given melee weapon when swung. Return true to allow hitting the NPC, return false to block hitting the NPC, and return null to use the vanilla code for whether the NPC can be hit. Returns null by default.
Parameters
player
item
Returns
Definition at line 339 of file ModNPC.cs.
         {
             return null;
         }
virtual bool Terraria.ModLoader.ModNPC.CanBeHitByProjectile (Projectile projectile) virtual
Allows you to determine whether this NPC can be hit by the given projectile. Return true to allow hitting the NPC, return false to block hitting the NPC, and return null to use the vanilla code for whether the NPC can be hit. Returns null by default.
Parameters
projectile
Returns
Definition at line 373 of file ModNPC.cs.
         {
             return null;
         }
virtual bool Terraria.ModLoader.ModNPC.CanHitNPC (NPC target) virtual
Allows you to determine whether this NPC can hit the given friendly NPC. Return true to allow hitting the target, return false to block this NPC from hitting the target, and return null to use the vanilla code for whether the target can be hit. Returns null by default.
Parameters
target
Returns
Definition at line 306 of file ModNPC.cs.
         {
             return null;
         }
virtual bool Terraria.ModLoader.ModNPC.CanHitPlayer (Player target, ref int cooldownSlot) virtual
Allows you to determine whether this NPC can hit the given player. Return false to block this NPC from hitting the target. Returns true by default. CooldownSlot determines which of the player's cooldown counters to use (-1, 0, or 1), and defaults to -1.
Parameters
target
cooldownSlot
Returns
Definition at line 276 of file ModNPC.cs.
         {
             return true;
         }
virtual float Terraria.ModLoader.ModNPC.CanSpawn (NPCSpawnInfo spawnInfo) virtual
Whether or not this NPC can spawn with the given spawning conditions. Return the weight for the chance of this NPC to spawn compared to vanilla mobs. All vanilla mobs combined have a total weight of 1. Returns 0 by default, which disables natural spawning.
Parameters
spawnInfo
Returns
Definition at line 494 of file ModNPC.cs.
Referenced by Terraria.ModLoader.NPCLoader.ChooseSpawn().
         {
             return 0f;
         }
virtual bool Terraria.ModLoader.ModNPC.CanTownNPCSpawn (int numTownNPCs, int money) virtual
Whether or not the conditions have been met for this town NPC to be able to move into town. For example, the Demolitionist requires that any player has an explosive.
Parameters
numTownNPCs
money
Returns
Definition at line 516 of file ModNPC.cs.
Referenced by Terraria.ModLoader.NPCLoader.CanTownNPCSpawn().
         {
             return false;
         }
virtual bool Terraria.ModLoader.ModNPC.CheckActive () virtual
Whether or not to run the code for checking whether this NPC will remain active. Return false to stop this NPC from being despawned and to stop this NPC from counting towards the limit for how many NPCs can exist near a player. Returns true by default.
Returns
Definition at line 231 of file ModNPC.cs.
         {
             return true;
         }
virtual bool Terraria.ModLoader.ModNPC.CheckConditions (int left, int right, int top, int bottom) virtual
Allows you to define special conditions required for this town NPC's house. For example, Truffle requires the house to be in an aboveground mushroom biome.
Parameters
left
right
top
bottom
Returns
Definition at line 529 of file ModNPC.cs.
         {
             return true;
         }
virtual bool Terraria.ModLoader.ModNPC.CheckDead () virtual
Whether or not this NPC should be killed when it reaches 0 health. You may program extra effects in this hook (for example, how Golem's head lifts up for the second phase of its fight). Return false to stop this NPC from being killed. Returns true by default.
Returns
Definition at line 240 of file ModNPC.cs.
         {
             return true;
         }
virtual void Terraria.ModLoader.ModNPC.DrawEffects (ref Color drawColor) virtual
Allows you to add special visual effects to this NPC (such as creating dust), and modify the color in which the NPC is drawn.
Parameters
drawColor
Definition at line 453 of file ModNPC.cs.
         {
         }
virtual bool Terraria.ModLoader.ModNPC.DrawHealthBar (byte hbPosition, ref float scale, ref Vector2 position) virtual
Allows you to control how the health bar for this NPC is drawn. The hbPosition parameter is the same as Main.hbPosition; it determines whether the health bar gets drawn above or below the NPC by default. The scale parameter is the health bar's size. By default, it will be the normal 1f; most bosses set this to 1.5f. Return null to let the normal vanilla health-bar-drawing code to run. Return false to stop the health bar from being drawn. Return true to draw the health bar in the position specified by the position parameter (note that this is the world position, not screen position).
Parameters
hbPosition
scale
position
Returns
Definition at line 484 of file ModNPC.cs.
         {
             return null;
         }
virtual void Terraria.ModLoader.ModNPC.DrawTownAttackGun (ref float scale, ref int item, ref int closeness) virtual
Allows you to customize how this town NPC's weapon is drawn when this NPC is shooting (this NPC must have an attack type of 1). Scale is a multiplier for the item's drawing size, item is the ID of the item to be drawn, and closeness is how close the item should be drawn to the NPC.
Parameters
scale
item
closeness
Definition at line 656 of file ModNPC.cs.
         {
         }
virtual void Terraria.ModLoader.ModNPC.DrawTownAttackSwing (ref Texture2D item, ref int itemSize, ref float scale, ref Vector2 offset) virtual
Allows you to customize how this town NPC's weapon is drawn when this NPC is swinging it (this NPC must have an attack type of 3). Item is the Texture2D instance of the item to be drawn (use Main.itemTexture[id of item]), itemSize is the width and height of the item's hitbox (the same values for TownNPCAttackSwing), scale is the multiplier for the item's drawing size, and offset is the offset from which to draw the item from its normal position.
Parameters
item
itemSize
scale
offset
Definition at line 667 of file ModNPC.cs.
         {
         }
virtual void Terraria.ModLoader.ModNPC.FindFrame (int frameHeight) virtual
Allows you to modify the frame from this NPC's texture that is drawn, which is necessary in order to animate NPCs.
Parameters
frameHeight
Definition at line 206 of file ModNPC.cs.
         {
         }
virtual Color Terraria.ModLoader.ModNPC.GetAlpha (Color drawColor) virtual
Allows you to determine the color and transparency in which this NPC is drawn. Return null to use the default color (normally light and buff color). Returns null by default.
Parameters
drawColor
Returns
Definition at line 444 of file ModNPC.cs.
         {
             return null;
         }
virtual string Terraria.ModLoader.ModNPC.GetChat () virtual
Allows you to give this town NPC a chat message when a player talks to it. By default returns something embarrassing.
Returns
Definition at line 556 of file ModNPC.cs.
         {
             return "My modder forgot to give me a chat message.";
         }
virtual void Terraria.ModLoader.ModNPC.HitEffect (int hitDirection, double damage) virtual
Allows you to make things happen whenever this NPC is hit, such as creating dust or gores.
Parameters
hitDirection
damage
Definition at line 215 of file ModNPC.cs.
         {
         }
virtual void Terraria.ModLoader.ModNPC.ModifyHitByItem (Player player, Item item, ref int damage, ref float knockback, ref bool crit) virtual
Allows you to modify the damage, knockback, etc., that this NPC takes from a melee weapon.
Parameters
player
item
damage
knockback
crit
Definition at line 352 of file ModNPC.cs.
         {
         }
virtual void Terraria.ModLoader.ModNPC.ModifyHitByProjectile (Projectile projectile, ref int damage, ref float knockback, ref bool crit, ref int hitDirection) virtual
Allows you to modify the damage, knockback, etc., that this NPC takes from a projectile.
Parameters
projectile
damage
knockback
crit
hitDirection
Definition at line 386 of file ModNPC.cs.
         {
         }
virtual void Terraria.ModLoader.ModNPC.ModifyHitNPC (NPC target, ref int damage, ref float knockback, ref bool crit) virtual
Allows you to modify the damage, knockback, etc., that this NPC does to a friendly NPC.
Parameters
target
damage
knockback
crit
Definition at line 318 of file ModNPC.cs.
         {
         }
virtual void Terraria.ModLoader.ModNPC.ModifyHitPlayer (Player target, ref int damage, ref bool crit) virtual
Allows you to modify the damage, etc., that this NPC does to a player.
Parameters
target
damage
crit
Definition at line 287 of file ModNPC.cs.
         {
         }
virtual void Terraria.ModLoader.ModNPC.NPCLoot () virtual
Allows you to make things happen when this NPC dies (for example, dropping items).
Definition at line 257 of file ModNPC.cs.
         {
         }
virtual void Terraria.ModLoader.ModNPC.OnChatButtonClicked (bool firstButton, ref bool shop) virtual
Allows you to make something happen whenever a button is clicked on this town NPC's chat window. The firstButton parameter tells whether the first button or second button (button and button2 from SetChatButtons) was clicked. Set the shop parameter to true to open this NPC's shop.
Parameters
firstButton
shop
Definition at line 575 of file ModNPC.cs.
         {
         }
virtual void Terraria.ModLoader.ModNPC.OnHitByItem (Player player, Item item, int damage, float knockback, bool crit) virtual
Allows you to create special effects when this NPC is hit by a melee weapon.
Parameters
player
item
damage
knockback
crit
Definition at line 364 of file ModNPC.cs.
         {
         }
virtual void Terraria.ModLoader.ModNPC.OnHitByProjectile (Projectile projectile, int damage, float knockback, bool crit) virtual
Allows you to create special effects when this NPC is hit by a projectile.
Parameters
projectile
damage
knockback
crit
Definition at line 397 of file ModNPC.cs.
         {
         }
virtual void Terraria.ModLoader.ModNPC.OnHitNPC (NPC target, int damage, float knockback, bool crit) virtual
Allows you to create special effects when this NPC hits a friendly NPC.
Parameters
target
damage
knockback
crit
Definition at line 329 of file ModNPC.cs.
         {
         }
virtual void Terraria.ModLoader.ModNPC.OnHitPlayer (Player target, int damage, bool crit) virtual
Allows you to create special effects when this NPC hits a player (for example, inflicting debuffs).
Parameters
target
damage
crit
Definition at line 297 of file ModNPC.cs.
         {
         }
virtual void Terraria.ModLoader.ModNPC.PostAI () virtual
Definition at line 182 of file ModNPC.cs.
         {
         }
virtual void Terraria.ModLoader.ModNPC.PostDraw (SpriteBatch spriteBatch, Color drawColor) virtual
Allows you to draw things in front of this NPC. This method is called even if PreDraw returns false.
Parameters
spriteBatch
drawColor
Definition at line 473 of file ModNPC.cs.
         {
         }
virtual bool Terraria.ModLoader.ModNPC.PreAI () virtual
Allows you to determine how this NPC behaves. Return false to stop the vanilla AI and the AI hook from being run. Returns true by default.
Returns
Definition at line 169 of file ModNPC.cs.
         {
             return true;
         }
virtual bool Terraria.ModLoader.ModNPC.PreDraw (SpriteBatch spriteBatch, Color drawColor) virtual
Allows you to draw things behind this NPC, or to modify the way this NPC is drawn. Return false to stop the game from drawing the NPC (useful if you're manually drawing the NPC). Returns true by default.
Parameters
spriteBatch
drawColor
Returns
Definition at line 463 of file ModNPC.cs.
         {
             return true;
         }
virtual bool Terraria.ModLoader.ModNPC.PreNPCLoot () virtual
Allows you to determine whether or not this NPC will drop anything at all. Return false to stop the NPC from dropping anything. Returns true by default.
Returns
Definition at line 249 of file ModNPC.cs.
         {
             return true;
         }
virtual void Terraria.ModLoader.ModNPC.ReceiveExtraAI (BinaryReader reader) virtual
Use this to receive information that was sent in SendExtraAI.
Parameters
reader
Definition at line 198 of file ModNPC.cs.
         {
         }
virtual void Terraria.ModLoader.ModNPC.ResetEffects () virtual
This is where you reset any fields you add to your subclass to their default states. This is necessary in order to reset your fields if they are conditionally set by a tick update but the condition is no longer satisfied. (Note: This hook is only really useful for GlobalNPC, but is included in ModNPC for completion.)
Definition at line 161 of file ModNPC.cs.
         {
         }
virtual void Terraria.ModLoader.ModNPC.ScaleExpertStats (int numPlayers, float bossLifeScale) virtual
Allows you to customize this NPC's stats in expert mode. This is useful because expert mode's doubling of damage and life might be too much sometimes (for example, with bosses). Also useful for scaling life with the number of players in the world.
Parameters
numPlayers
bossLifeScale
Definition at line 154 of file ModNPC.cs.
         {
         }
virtual void Terraria.ModLoader.ModNPC.SendExtraAI (BinaryWriter writer) virtual
If you are storing AI information outside of the npc.ai array, use this to send that AI information between clients and servers.
Parameters
writer
Definition at line 190 of file ModNPC.cs.
         {
         }
virtual void Terraria.ModLoader.ModNPC.SetChatButtons (ref string button, ref string button2) virtual
Allows you to set the text for the buttons that appear on this town NPC's chat window. A parameter left as an empty string will not be included as a button on the chat window.
Parameters
button
button2
Definition at line 566 of file ModNPC.cs.
         {
         }
virtual void Terraria.ModLoader.ModNPC.SetDefaults () virtual
Allows you to set all your NPC's properties, such as width, damage, aiStyle, lifeMax, etc.
Definition at line 145 of file ModNPC.cs.
Referenced by Terraria.ModLoader.ModNPC.AutoloadHead(), and Terraria.ModLoader.Mod.RegisterHotKey().
         {
         }
virtual void Terraria.ModLoader.ModNPC.SetStaticDefaults () virtual
Allows you to set all your NPC's static properties, such as names/translations and the arrays in NPCID.Sets.
Definition at line 138 of file ModNPC.cs.
Referenced by Terraria.ModLoader.Mod.RegisterHotKey().
         {
         }
virtual void Terraria.ModLoader.ModNPC.SetupShop (Chest shop, ref int nextSlot) virtual
Allows you to add items to this town NPC's shop. Add an item by setting the defaults of shop.item[nextSlot] then incrementing nextSlot. In the end, nextSlot must have a value of 1 greater than the highest index in shop.item that contains an item.
Parameters
shop
nextSlot
Definition at line 584 of file ModNPC.cs.
         {
         }
virtual int Terraria.ModLoader.ModNPC.SpawnNPC (int tileX, int tileY) virtual
Allows you to customize how this NPC is created when it naturally spawns (for example, its position or ai array). Return the return value of NPC.NewNPC. By default this method spawns this NPC on top of the tile at the given coordinates.
Parameters
tileX
tileY
Returns
Definition at line 505 of file ModNPC.cs.
Referenced by Terraria.ModLoader.NPCLoader.SpawnNPC().
         {
             return NPC.NewNPC(tileX * 16 + 8, tileY * 16, npc.type);
         }
virtual bool Terraria.ModLoader.ModNPC.StrikeNPC (ref double damage, int defense, ref float knockback, int hitDirection, ref bool crit) virtual
Allows you to use a custom damage formula for when this NPC takes damage from any source. For example, you can change the way defense works or use a different crit multiplier. Return false to stop the game from running the vanilla damage formula; returns true by default.
Parameters
damage
defense
knockback
hitDirection
crit
Returns
Definition at line 410 of file ModNPC.cs.
         {
             return true;
         }
virtual void Terraria.ModLoader.ModNPC.TownNPCAttackCooldown (ref int cooldown, ref int randExtraCooldown) virtual
Allows you to determine the cooldown between each of this town NPC's attack. The cooldown will be a number greater than or equal to the first parameter, and less then the sum of the two parameters.
Parameters
cooldown
randExtraCooldown
Definition at line 602 of file ModNPC.cs.
         {
         }
virtual void Terraria.ModLoader.ModNPC.TownNPCAttackMagic (ref float auraLightMultiplier) virtual
Allows you to control the brightness of the light emitted by this town NPC's aura when it performs a magic attack. Only used when the town NPC has an attack type of 2 (magic)
Parameters
auraLightMultiplier
Definition at line 637 of file ModNPC.cs.
         {
         }
virtual void Terraria.ModLoader.ModNPC.TownNPCAttackProj (ref int projType, ref int attackDelay) virtual
Allows you to determine the projectile type of this town NPC's attack, and how long it takes for the projectile to actually appear. This hook is only used when the town NPC has an attack type of 0 (throwing), 1 (shooting), or 2 (magic).
Parameters
projType
attackDelay
Definition at line 611 of file ModNPC.cs.
         {
         }
virtual void Terraria.ModLoader.ModNPC.TownNPCAttackProjSpeed (ref float multiplier, ref float gravityCorrection, ref float randomOffset) virtual
Allows you to determine the speed at which this town NPC throws a projectile when it attacks. Multiplier is the speed of the projectile, gravityCorrection is how much extra the projectile gets thrown upwards, and randomOffset allows you to randomize the projectile's velocity in a square centered around the original velocity. This hook is only used when the town NPC has an attack type of 0 (throwing), 1 (shooting), or 2 (magic).
Parameters
multiplier
gravityCorrection
randomOffset
Definition at line 621 of file ModNPC.cs.
         {
         }
virtual void Terraria.ModLoader.ModNPC.TownNPCAttackShoot (ref bool inBetweenShots) virtual
Allows you to tell the game that this town NPC has already created a projectile and will still create more projectiles as part of a single attack so that the game can animate the NPC's attack properly. Only used when the town NPC has an attack type of 1 (shooting).
Parameters
inBetweenShots
Definition at line 629 of file ModNPC.cs.
         {
         }
virtual void Terraria.ModLoader.ModNPC.TownNPCAttackStrength (ref int damage, ref float knockback) virtual
Allows you to determine the damage and knockback of this town NPC's attack before the damage is scaled. (More information on scaling in GlobalNPC.BuffTownNPCs.)
Parameters
damage
knockback
Definition at line 593 of file ModNPC.cs.
         {
         }
virtual void Terraria.ModLoader.ModNPC.TownNPCAttackSwing (ref int itemWidth, ref int itemHeight) virtual
Allows you to determine the width and height of the item this town NPC swings when it attacks, which controls the range of this NPC's swung weapon. Only used when the town NPC has an attack type of 3 (swinging).
Parameters
itemWidth
itemHeight
Definition at line 646 of file ModNPC.cs.
         {
         }
virtual string Terraria.ModLoader.ModNPC.TownNPCName () virtual
Allows you to give this town NPC any name when it spawns. By default returns something embarrassing.
Returns
Definition at line 538 of file ModNPC.cs.
         {
             return "No-Name";
         }
virtual void Terraria.ModLoader.ModNPC.UpdateLifeRegen (ref int damage) virtual
Allows you to make the NPC either regenerate health or take damage over time by setting npc.lifeRegen. Regeneration or damage will occur at a rate of half of npc.lifeRegen per second. The damage parameter is the number that appears above the NPC's head if it takes damage over time.
Parameters
damage
Definition at line 223 of file ModNPC.cs.
         {
         }
virtual bool Terraria.ModLoader.ModNPC.UsesPartyHat () virtual
Allows you to determine whether this town NPC wears a party hat during a party. Returns true by default.
Returns
Definition at line 547 of file ModNPC.cs.
         {
             return true;
         }
Member Data Documentation
int Terraria.ModLoader.ModNPC.aiType = 0
Determines which type of vanilla NPC this ModNPC will copy the behavior (AI) of. Leave as 0 to not copy any behavior. Defaults to 0.
Definition at line 57 of file ModNPC.cs.
int Terraria.ModLoader.ModNPC.animationType = 0
Determines which type of vanilla NPC this ModNPC will copy the animation (FindFrame) of. Leave as 0 to not copy any animation. Defaults to 0.
Definition at line 61 of file ModNPC.cs.
int Terraria.ModLoader.ModNPC.banner = 0
The type of NPC that this NPC will be considered as when determining banner drops and banner bonuses. By default this will be 0, which means this NPC is not associated with any banner. To give your NPC its own banner, set this field to the NPC's type.
Definition at line 84 of file ModNPC.cs.
Referenced by Terraria.ModLoader.Mod.RegisterHotKey().
int Terraria.ModLoader.ModNPC.bannerItem = 0
The type of the item this NPC drops for every 50 times it is defeated. For any ModNPC whose banner field is set to the type of this NPC, that ModNPC will drop this banner.
Definition at line 90 of file ModNPC.cs.
Referenced by Terraria.ModLoader.Mod.RegisterHotKey().
int Terraria.ModLoader.ModNPC.bossBag = -1
The item type of the boss bag that is dropped when DropBossBags is called for this NPC.
Definition at line 65 of file ModNPC.cs.
virtual bool Terraria.ModLoader.ModNPC.CloneNewInstances => false
Whether instances of this ModNPC are created through a memberwise clone or its constructor. Defaults to false.
Definition at line 133 of file ModNPC.cs.
float Terraria.ModLoader.ModNPC.drawOffsetY = 0f
The vertical offset used for drawing this NPC. Defaults to 0.
Definition at line 76 of file ModNPC.cs.
int Terraria.ModLoader.ModNPC.music = -1
The ID of the music that plays when this NPC is on or near the screen. Defaults to -1, which means music plays normally.
Definition at line 70 of file ModNPC.cs.
Property Documentation
ModTranslation Terraria.ModLoader.ModNPC.DisplayName get set
The translations for the display name of this NPC.
Definition at line 47 of file ModNPC.cs.
Referenced by Terraria.ModLoader.Mod.AddNPC(), and Terraria.ModLoader.ModLoader.RefreshModLanguage().
Mod Terraria.ModLoader.ModNPC.mod get set
The mod that added this ModNPC.
Definition at line 29 of file ModNPC.cs.
Referenced by Terraria.ModLoader.Mod.AddNPC(), Terraria.ModLoader.ModNPC.AutoloadHead(), and Terraria.ModLoader.Mod.AutoloadNPC().
string Terraria.ModLoader.ModNPC.Name get set
The internal name of this NPC.
Definition at line 38 of file ModNPC.cs.
Referenced by Terraria.ModLoader.Mod.AddNPC().
NPC Terraria.ModLoader.ModNPC.npc get set
The NPC object that this ModNPC controls.
Definition at line 20 of file ModNPC.cs.
Referenced by Terraria.ModLoader.Mod.AddNPC(), Terraria.ModLoader.ModNPC.AutoloadHead(), Terraria.ModLoader.Mod.AutoloadNPC(), Terraria.ModLoader.NPCLoader.CanTownNPCSpawn(), Terraria.ModLoader.NPCLoader.ChooseSpawn(), Terraria.ModLoader.Mod.NPCType(), Terraria.ModLoader.NPCLoader.OnChatButtonClicked(), Terraria.ModLoader.ModLoader.RefreshModLanguage(), Terraria.ModLoader.Mod.RegisterHotKey(), and Terraria.ModLoader.NPCLoader.SetChatButtons().