Terraria ModLoader: Terraria.ModLoader.WallLoader Class Reference
Terraria.ModLoader.WallLoader Class Reference
This serves as the central class from which wall-related functions are supported and carried out.
Static Public Member Functions
static void AnimateWalls ()
static bool CanExplode (int i, int j, int type)
static bool CreateDust (int i, int j, int type, ref int dustType)
static bool Drop (int i, int j, int type, ref int dropType)
static ModWall GetWall (int type)
Gets the ModWall instance with the given type. If no ModWall with the given type exists, returns null.
static bool KillSound (int i, int j, int type)
static void KillWall (int i, int j, int type, ref bool fail)
static void ModifyLight (int i, int j, int type, ref float r, ref float g, ref float b)
static void NumDust (int i, int j, int type, bool fail, ref int numDust)
static void PlaceInWorld (int i, int j, Item item)
static void PostDraw (int i, int j, int type, SpriteBatch spriteBatch)
static bool PreDraw (int i, int j, int type, SpriteBatch spriteBatch)
static void RandomUpdate (int i, int j, int type)
Static Public Attributes
static int WallCount => nextWall
Private Member Functions
delegate bool DelegateCreateDust (int i, int j, int type, ref int dustType)
delegate bool DelegateDrop (int i, int j, int type, ref int dropType)
delegate void DelegateKillWall (int i, int j, int type, ref bool fail)
delegate void DelegateModifyLight (int i, int j, int type, ref float r, ref float g, ref float b)
delegate void DelegateNumDust (int i, int j, int type, bool fail, ref int num)
Static Private Member Functions
static void Resize2DArray< T > (ref T[,] array, int newSize)
Static Private Attributes
static Func< int, int, int, bool >[] HookCanExplode
static DelegateCreateDust[] HookCreateDust
static DelegateDrop[] HookDrop
static Func< int, int, int, bool >[] HookKillSound
static DelegateKillWall[] HookKillWall
static DelegateModifyLight[] HookModifyLight
static DelegateNumDust[] HookNumDust
static Action< int, int, int, Item >[] HookPlaceInWorld
static Action< int, int, int, SpriteBatch >[] HookPostDraw
static Func< int, int, int, SpriteBatch, bool >[] HookPreDraw
static Action< int, int, int >[] HookRandomUpdate
static bool loaded = false
static int nextWall = WallID.Count
Detailed Description
This serves as the central class from which wall-related functions are supported and carried out.
Definition at line 13 of file WallLoader.cs.
Member Function Documentation
static void Terraria.ModLoader.WallLoader.AnimateWalls () static
Definition at line 224 of file WallLoader.cs.
References Terraria.ModLoader.ModWall.AnimateWall(), and Terraria.ModLoader.ModWall.Type.
{
             if (loaded) {
                 for (int i = 0; i < walls.Count; i++) {
                     ModWall modWall = walls[i];
                     modWall.AnimateWall(ref Main.wallFrame[modWall.Type], ref Main.wallFrameCounter[modWall.Type]);
                 }
             }
         }
static bool Terraria.ModLoader.WallLoader.CanExplode (int i, int j, int type) static
Definition at line 196 of file WallLoader.cs.
{
             foreach (var hook in HookCanExplode) {
                 if (!hook(i, j, type)) {
                     return false;
                 }
             }
             return GetWall(type)?.CanExplode(i, j) ?? true;
         }
static bool Terraria.ModLoader.WallLoader.CreateDust (int i, int j, int type, ref int dustType) static
Definition at line 168 of file WallLoader.cs.
{
             foreach (var hook in HookCreateDust) {
                 if (!hook(i, j, type, ref dustType)) {
                     return false;
                 }
             }
             return GetWall(type)?.CreateDust(i, j, ref dustType) ?? true;
         }
delegate bool Terraria.ModLoader.WallLoader.DelegateCreateDust (int i, int j, int type, ref int dustType) private
delegate bool Terraria.ModLoader.WallLoader.DelegateDrop (int i, int j, int type, ref int dropType) private
delegate void Terraria.ModLoader.WallLoader.DelegateKillWall (int i, int j, int type, ref bool fail) private
delegate void Terraria.ModLoader.WallLoader.DelegateModifyLight (int i, int j, int type, ref float r, ref float g, ref float b) private
delegate void Terraria.ModLoader.WallLoader.DelegateNumDust (int i, int j, int type, bool fail, ref int num) private
static bool Terraria.ModLoader.WallLoader.Drop (int i, int j, int type, ref int dropType) static
Definition at line 178 of file WallLoader.cs.
{
             foreach (var hook in HookDrop) {
                 if (!hook(i, j, type, ref dropType)) {
                     return false;
                 }
             }
             return GetWall(type)?.Drop(i, j, ref dropType) ?? true;
         }
static ModWall Terraria.ModLoader.WallLoader.GetWall (int type) static
Gets the ModWall instance with the given type. If no ModWall with the given type exists, returns null.
Definition at line 50 of file WallLoader.cs.
Referenced by Terraria.ModLoader.ModContent.MusicExists().
{
             return type >= WallID.Count && type < WallCount ? walls[type - WallID.Count] : null;
         }
static bool Terraria.ModLoader.WallLoader.KillSound (int i, int j, int type) static
Definition at line 141 of file WallLoader.cs.
References Terraria.ModLoader.ModWall.KillSound(), Terraria.ModLoader.ModWall.soundStyle, and Terraria.ModLoader.ModWall.soundType.
{
             foreach (var hook in HookKillSound) {
                 if (!hook(i, j, type)) {
                     return false;
                 }
             }
             ModWall modWall = GetWall(type);
             if (modWall != null) {
                 if (!modWall.KillSound(i, j)) {
                     return false;
                 }
                 Main.PlaySound(modWall.soundType, i * 16, j * 16, modWall.soundStyle);
                 return false;
             }
             return true;
         }
static void Terraria.ModLoader.WallLoader.KillWall (int i, int j, int type, ref bool fail) static
Definition at line 188 of file WallLoader.cs.
{
             GetWall(type)?.KillWall(i, j, ref fail);
             foreach (var hook in HookKillWall) {
                 hook(i, j, type, ref fail);
             }
         }
static void Terraria.ModLoader.WallLoader.ModifyLight (int i, int j, int type, ref float r, ref float g, ref float b) static
Definition at line 206 of file WallLoader.cs.
{
             GetWall(type)?.ModifyLight(i, j, ref r, ref g, ref b);
             foreach (var hook in HookModifyLight) {
                 hook(i, j, type, ref r, ref g, ref b);
             }
         }
static void Terraria.ModLoader.WallLoader.NumDust (int i, int j, int type, bool fail, ref int numDust) static
Definition at line 159 of file WallLoader.cs.
{
             GetWall(type)?.NumDust(i, j, fail, ref numDust);
             foreach (var hook in HookNumDust) {
                 hook(i, j, type, fail, ref numDust);
             }
         }
static void Terraria.ModLoader.WallLoader.PlaceInWorld (int i, int j, Item item) static
Definition at line 253 of file WallLoader.cs.
{
             int type = item.createWall;
             if (type < 0)
                 return;
             foreach (var hook in HookPlaceInWorld) {
                 hook(i, j, type, item);
             }
             GetWall(type)?.PlaceInWorld(i, j, item);
         }
static void Terraria.ModLoader.WallLoader.PostDraw (int i, int j, int type, SpriteBatch spriteBatch) static
Definition at line 245 of file WallLoader.cs.
{
             GetWall(type)?.PostDraw(i, j, spriteBatch);
             foreach (var hook in HookPostDraw) {
                 hook(i, j, type, spriteBatch);
             }
         }
static bool Terraria.ModLoader.WallLoader.PreDraw (int i, int j, int type, SpriteBatch spriteBatch) static
Definition at line 235 of file WallLoader.cs.
{
             foreach (var hook in HookPreDraw) {
                 if (!hook(i, j, type, spriteBatch)) {
                     return false;
                 }
             }
             return GetWall(type)?.PreDraw(i, j, spriteBatch) ?? true;
         }
static void Terraria.ModLoader.WallLoader.RandomUpdate (int i, int j, int type) static
Definition at line 216 of file WallLoader.cs.
{
             GetWall(type)?.RandomUpdate(i, j);
             foreach (var hook in HookRandomUpdate) {
                 hook(i, j, type);
             }
         }
static void Terraria.ModLoader.WallLoader.Resize2DArray< T > (ref T array[,], int newSize) static private
Definition at line 54 of file WallLoader.cs.
{
             int dim1 = array.GetLength(0);
             int dim2 = array.GetLength(1);
             T[,] newArray = new T[newSize, dim2];
             for (int j = 0; j < newSize && j < dim1; j++) {
                 for (int k = 0; k < dim2; k++) {
                     newArray[j, k] = array[j, k];
                 }
             }
             array = newArray;
         }
Member Data Documentation
Func<int, int, int, bool> [] Terraria.ModLoader.WallLoader.HookCanExplode static private
Definition at line 29 of file WallLoader.cs.
DelegateCreateDust [] Terraria.ModLoader.WallLoader.HookCreateDust static private
Definition at line 24 of file WallLoader.cs.
DelegateDrop [] Terraria.ModLoader.WallLoader.HookDrop static private
Definition at line 26 of file WallLoader.cs.
Func<int, int, int, bool> [] Terraria.ModLoader.WallLoader.HookKillSound static private
Definition at line 20 of file WallLoader.cs.
DelegateKillWall [] Terraria.ModLoader.WallLoader.HookKillWall static private
Definition at line 28 of file WallLoader.cs.
DelegateModifyLight [] Terraria.ModLoader.WallLoader.HookModifyLight static private
Definition at line 31 of file WallLoader.cs.
DelegateNumDust [] Terraria.ModLoader.WallLoader.HookNumDust static private
Definition at line 22 of file WallLoader.cs.
Action<int, int, int, Item> [] Terraria.ModLoader.WallLoader.HookPlaceInWorld static private
Definition at line 35 of file WallLoader.cs.
Action<int, int, int, SpriteBatch> [] Terraria.ModLoader.WallLoader.HookPostDraw static private
Definition at line 34 of file WallLoader.cs.
Func<int, int, int, SpriteBatch, bool> [] Terraria.ModLoader.WallLoader.HookPreDraw static private
Definition at line 33 of file WallLoader.cs.
Action<int, int, int> [] Terraria.ModLoader.WallLoader.HookRandomUpdate static private
Definition at line 32 of file WallLoader.cs.
bool Terraria.ModLoader.WallLoader.loaded = false static private
Definition at line 18 of file WallLoader.cs.
int Terraria.ModLoader.WallLoader.nextWall = WallID.Count static private
Definition at line 15 of file WallLoader.cs.
int Terraria.ModLoader.WallLoader.WallCount => nextWall static
Definition at line 45 of file WallLoader.cs.