Terraria ModLoader: Terraria.ModLoader.IO.TmodFile Class Reference
Terraria.ModLoader.IO.TmodFile Class Reference
Classes
class DisposeWrapper
class FileEntry
Public Member Functions
void CacheFiles (ISet< string > skip=null)
void Close ()
IDisposable EnsureOpen ()
byte[] GetBytes (FileEntry entry)
byte[] GetBytes (string fileName)
IEnumerator< FileEntry > GetEnumerator ()
byte[] GetFile (string fileName)
byte[] GetMainAssembly (bool?windows=null)
byte[] GetMainPDB (bool?windows=null)
Stream GetStream (FileEntry entry, bool newFileStream=false)
Stream GetStream (string fileName, bool newFileStream=false)
bool HasFile (string fileName)
void RemoveFromCache (IEnumerable< string > fileNames)
void ResetCache ()
void VerifyCoreFiles ()
Public Attributes
const float COMPRESSION_TRADEOFF = 0.9f
int Count => fileTable.Length
const uint MAX_CACHE_SIZE = 1 << 17
const uint MIN_COMPRESS_SIZE = 1 << 10
readonly string path
Properties
byte[] hash [get, private set]
string name [get, set]
Version tModLoaderVersion [get, private set]
Version version [get, set]
Private Member Functions
IEnumerator IEnumerable. GetEnumerator ()
void Upgrade ()
Static Private Member Functions
static string Sanitize (string path)
static bool ShouldCompress (string fileName)
Private Attributes
IDictionary< string, FileEntry > files = new Dictionary<string, FileEntry>()
FileStream fileStream
FileEntry[] fileTable
EntryReadStream lastEntryReadStream
bool validModBrowserSignature = new byte[256]
Detailed Description
Definition at line 14 of file TmodFile.cs.
Member Function Documentation
void Terraria.ModLoader.IO.TmodFile.CacheFiles (ISet< string > skip = null)
Definition at line 294 of file TmodFile.cs.
{
             fileStream.Seek(fileTable[0].Offset, SeekOrigin.Begin);
             foreach (var f in fileTable) {
                 if (f.CompressedLength > MAX_CACHE_SIZE || (skip?.Contains(f.Name) ?? false)) {
                     fileStream.Seek(f.CompressedLength, SeekOrigin.Current);
                     continue;
                 }
                 f.cachedBytes = fileStream.ReadBytes(f.CompressedLength);
             }
         }
void Terraria.ModLoader.IO.TmodFile.Close ()
Definition at line 332 of file TmodFile.cs.
{
             fileStream?.Close();
             fileStream = null;
         }
IDisposable Terraria.ModLoader.IO.TmodFile.EnsureOpen ()
Definition at line 324 of file TmodFile.cs.
Referenced by Terraria.ModLoader.AssemblyManager.LoadedMod.LoadAssemblies().
{
             if (fileStream != null)
                 return new DisposeWrapper(null);
             fileStream = File.OpenRead(path);
             return new DisposeWrapper(Close);
         }
byte [] Terraria.ModLoader.IO.TmodFile.GetBytes (FileEntry entry)
Definition at line 86 of file TmodFile.cs.
References Terraria.ModLoader.IO.TmodFile.FileEntry.IsCompressed, and Terraria.ModLoader.IO.TmodFile.FileEntry.Length.
Referenced by Terraria.ModLoader.AssemblyManager.LoadedMod.LoadAssemblies().
{
             if (entry.cachedBytes != null && !entry.IsCompressed)
                 return entry.cachedBytes;
             using (var stream = GetStream(entry))
                 return stream.ReadBytes(entry.Length);
         }
byte [] Terraria.ModLoader.IO.TmodFile.GetBytes (string fileName)
IEnumerator IEnumerable. Terraria.ModLoader.IO.TmodFile.GetEnumerator () private
IEnumerator<FileEntry> Terraria.ModLoader.IO.TmodFile.GetEnumerator ()
Definition at line 163 of file TmodFile.cs.
References Terraria.ModLoader.IO.TmodFile.FileEntry.CompressedLength, Terraria.ModLoader.IO.TmodFile.FileEntry.Length, and Terraria.ModLoader.ModLoader.version.
{
             foreach (var entry in fileTable)
                 yield return entry;
         }
byte [] Terraria.ModLoader.IO.TmodFile.GetFile (string fileName)
byte [] Terraria.ModLoader.IO.TmodFile.GetMainAssembly (bool? windows = null)
Definition at line 380 of file TmodFile.cs.
References Terraria.ModLoader.ModLoader.windows.
Referenced by Terraria.ModLoader.AssemblyManager.LoadedMod.LoadAssemblies().
{
             bool isWindows = windows.GetValueOrDefault(ModLoader.windows);
             return HasFile("All.dll") ? GetBytes("All.dll") : isWindows ? GetBytes("Windows.dll") : GetBytes("Mono.dll");
         }
byte [] Terraria.ModLoader.IO.TmodFile.GetMainPDB (bool? windows = null)
Definition at line 385 of file TmodFile.cs.
References Terraria.ModLoader.ModLoader.windows.
Referenced by Terraria.ModLoader.AssemblyManager.LoadedMod.LoadAssemblies().
{
             bool isWindows = windows.GetValueOrDefault(ModLoader.windows);
             return HasFile("All.pdb") ? GetBytes("All.pdb") : isWindows ? GetBytes("Windows.pdb") : GetBytes("Mono.mdb");
         }
Stream Terraria.ModLoader.IO.TmodFile.GetStream (FileEntry entry, bool newFileStream = false)
Definition at line 97 of file TmodFile.cs.
References Terraria.ModLoader.IO.TmodFile.FileEntry.IsCompressed.
{
             Stream stream;
             if (entry.cachedBytes != null) {
                 stream = new MemoryStream(entry.cachedBytes);
             }
             else if (newFileStream) {
                 stream = new EntryReadStream(File.OpenRead(path), entry, false);
             }
             else {
                 if (fileStream == null)
                     throw new IOException("File not open: " + path);
                 if (lastEntryReadStream != null && !lastEntryReadStream.IsClosed)
                     throw new IOException($"Previous entry read stream not closed: {lastEntryReadStream.Name}");
                 stream = lastEntryReadStream = new EntryReadStream(fileStream, entry, true);
             }
             if (entry.IsCompressed)
                 stream = new DeflateStream(stream, CompressionMode.Decompress);
             return stream;
         }
Stream Terraria.ModLoader.IO.TmodFile.GetStream (string fileName, bool newFileStream = false)
Definition at line 121 of file TmodFile.cs.
{
             if (!files.TryGetValue(Sanitize(fileName), out var entry))
                 throw new KeyNotFoundException(fileName);
             return GetStream(entry, newFileStream);
         }
bool Terraria.ModLoader.IO.TmodFile.HasFile (string fileName)
void Terraria.ModLoader.IO.TmodFile.RemoveFromCache (IEnumerable< string > fileNames)
Definition at line 306 of file TmodFile.cs.
{
             foreach (var fileName in fileNames)
                 files[fileName].cachedBytes = null;
         }
void Terraria.ModLoader.IO.TmodFile.ResetCache ()
Definition at line 311 of file TmodFile.cs.
{
             foreach (var f in fileTable)
                 f.cachedBytes = null;
         }
static string Terraria.ModLoader.IO.TmodFile.Sanitize (string path) static private
static bool Terraria.ModLoader.IO.TmodFile.ShouldCompress (string fileName) static private
void Terraria.ModLoader.IO.TmodFile.Upgrade () private
Definition at line 337 of file TmodFile.cs.
{
             Interface.loadMods.SubProgressText = $"Upgrading: {Path.GetFileName(path)}";
             Logging.tML.InfoFormat("Upgrading: {0}", Path.GetFileName(path));
             using (var deflateStream = new DeflateStream(fileStream, CompressionMode.Decompress, true))
             using (var reader = new BinaryReader(deflateStream)) {
                 name = reader.ReadString();
                 version = new Version(reader.ReadString());
                 int count = reader.ReadInt32();
                 for (int i = 0; i < count; i++)
                     AddFile(reader.ReadString(), reader.ReadBytes(reader.ReadInt32()));
             }
             // update buildVersion
             var info = BuildProperties.ReadModFile(this);
             info.buildVersion = tModLoaderVersion;
             AddFile("Info", info.ToBytes());
             // make a backup
             fileStream.Seek(0, SeekOrigin.Begin);
             var backupFolder = Path.Combine(Path.GetDirectoryName(path), "UpgradeBackup");
             Directory.CreateDirectory(backupFolder);
             using (var backupStream = File.OpenWrite(Path.Combine(backupFolder, Path.GetFileName(path))))
                 fileStream.CopyTo(backupStream);
             // write to the new format (also updates the file offset table)
             Save();
             // clear all the file contents from AddFile
             ResetCache();
             // Save closes the file so re-open it
             fileStream = File.OpenRead(path);
             // Read contract fulfilled
         }
void Terraria.ModLoader.IO.TmodFile.VerifyCoreFiles ()
Definition at line 372 of file TmodFile.cs.
{
             if (!HasFile("Info"))
                 throw new Exception("Missing Info file");
             if (!HasFile("All.dll") && !(HasFile("Windows.dll") && HasFile("Mono.dll")))
                 throw new Exception("Missing All.dll or Windows.dll and Mono.dll");
         }
Member Data Documentation
const float Terraria.ModLoader.IO.TmodFile.COMPRESSION_TRADEOFF = 0.9f
Definition at line 41 of file TmodFile.cs.
int Terraria.ModLoader.IO.TmodFile.Count => fileTable.Length
Definition at line 160 of file TmodFile.cs.
IDictionary<string, FileEntry> Terraria.ModLoader.IO.TmodFile.files = new Dictionary<string, FileEntry>() private
Definition at line 48 of file TmodFile.cs.
FileStream Terraria.ModLoader.IO.TmodFile.fileStream private
Definition at line 47 of file TmodFile.cs.
FileEntry [] Terraria.ModLoader.IO.TmodFile.fileTable private
Definition at line 49 of file TmodFile.cs.
EntryReadStream Terraria.ModLoader.IO.TmodFile.lastEntryReadStream private
Definition at line 96 of file TmodFile.cs.
const uint Terraria.ModLoader.IO.TmodFile.MAX_CACHE_SIZE = 1 << 17
Definition at line 40 of file TmodFile.cs.
const uint Terraria.ModLoader.IO.TmodFile.MIN_COMPRESS_SIZE = 1 << 10
Definition at line 39 of file TmodFile.cs.
readonly string Terraria.ModLoader.IO.TmodFile.path
Definition at line 45 of file TmodFile.cs.
bool Terraria.ModLoader.IO.TmodFile.validModBrowserSignature = new byte[256] private
Definition at line 65 of file TmodFile.cs.
Property Documentation
byte [] Terraria.ModLoader.IO.TmodFile.hash get private set
Definition at line 61 of file TmodFile.cs.
Referenced by Terraria.ModLoader.ModLoader.IsSignedBy(), Terraria.ModLoader.ModNet.ModHeader.ModHeader(), and Terraria.ModLoader.AssemblyManager.LoadedMod.SetMod().
string Terraria.ModLoader.IO.TmodFile.name get set
Definition at line 55 of file TmodFile.cs.
Referenced by Terraria.ModLoader.ModNet.ModHeader.ModHeader().
Version Terraria.ModLoader.IO.TmodFile.tModLoaderVersion get private set
Definition at line 51 of file TmodFile.cs.
Version Terraria.ModLoader.IO.TmodFile.version get set
Definition at line 57 of file TmodFile.cs.
Referenced by Terraria.ModLoader.ModCompile.BuildingMod.BuildingMod(), Terraria.ModLoader.ModNet.ModHeader.ModHeader(), and Terraria.ModLoader.AssemblyManager.LoadedMod.SetMod().