Terraria ModLoader: Terraria.ModLoader.CommandManager Class Reference
Terraria.ModLoader.CommandManager Class Reference
This serves as the central class from which ModCommand functions are supported and carried out.
Static Public Member Functions
static List< Tuple< string, string > > GetHelp (CommandType type)
static bool Matches (CommandType commandType, CommandType callerType)
Detailed Description
This serves as the central class from which ModCommand functions are supported and carried out.
Definition at line 12 of file CommandManager.cs.
Member Function Documentation
static List<Tuple<string, string> > Terraria.ModLoader.CommandManager.GetHelp (CommandType type) static
Definition at line 114 of file CommandManager.cs.
References Terraria.ModLoader.ModCommand.Command.
{
             var list = new List<Tuple<string, string>>();
             foreach (var entry in Commands) {
                 var cmdList = entry.Value.Where(mc => Matches(mc.Type, type)).ToList();
                 foreach (var mc in cmdList) {
                     string cmd = mc.Command;
                     if (cmdList.Count > 1)
                         cmd = mc.mod.Name + ":" + cmd;
                     list.Add(Tuple.Create(cmd, mc.Description));
                 }
             }
             return list;
         }
static bool Terraria.ModLoader.CommandManager.Matches (CommandType commandType, CommandType callerType) static
Definition at line 16 of file CommandManager.cs.
References Terraria.ModLoader.ModCommand.Action(), Terraria.ModLoader.ModCommand.Command, Terraria.ModLoader.CommandCaller.CommandType, Terraria.ModLoader.ModLoader.GetMod(), and Terraria.ModLoader.CommandCaller.Reply().
{
             if ((commandType & CommandType.World) != 0)
                 if (Main.netMode == 2)
                     commandType |= CommandType.Server;
                 else if (Main.netMode == 0)
                     commandType |= CommandType.Chat;
             return (callerType & commandType) != 0;
         }