Terraria ModLoader: Terraria.ModLoader.ModTileEntity Class Reference
Terraria.ModLoader.ModTileEntity Class Reference abstract
Tile Entities are Entities tightly coupled with tiles, allowing the possibility of tiles to exhibit cool behavior. TileEntity.Update is called in SP and on Server, not on Clients.
Public Member Functions
virtual bool Autoload (ref string name)
Allows you to automatically load a tile entity instead of using Mod.AddTileEntity. Return true to allow autoloading; by default returns the mod's autoload property. Name is initialized to the overriding class name. Use this method to either force or stop an autoload, or change the default display name.
int Find (int i, int j)
Returns the entity ID of this kind of tile entity at the given coordinates for you.
virtual int Hook_AfterPlacement (int i, int j, int type, int style, int direction)
This method does not get called by tModLoader, and is only included for you convenience so you do not have to cast the result of Mod.GetTileEntity.
void Kill (int i, int j)
A helper method that removes this kind of tile entity from the given coordinates for you.
virtual void Load (TagCompound tag)
Allows you to load the custom data you have saved for this tile entity.
virtual void NetReceive (BinaryReader reader, bool lightReceive)
Receives the data sent in the NetSend hook. Called on MP Client when receiving tile data (!lightReceive) and when a MessageID.TileEntitySharing message is sent (lightReceive)
virtual void NetSend (BinaryWriter writer, bool lightSend)
Allows you to send custom data for this tile entity between client and server. This is called on the server while sending tile data (!lightSend) and when a MessageID.TileEntitySharing message is sent (lightSend)
virtual void OnKill ()
This method only gets called in the Kill method. If you plan to use that, you can put code here to make things happen when it is called.
virtual void OnNetPlace ()
Code that should be run when this tile entity is placed by means of server-syncing. Called on Server only.
int Place (int i, int j)
A helper method that places this kind of tile entity in the given coordinates for you.
virtual void PostGlobalUpdate ()
Code that should be run after all tile entities in the world update.
virtual void PreGlobalUpdate ()
Code that should be run before all tile entities in the world update.
sealed override void ReadExtraData (BinaryReader reader, bool networkSend)
Don't use this. It is included only for completion's sake.
virtual TagCompound Save ()
Allows you to save custom data for this tile entity.
abstract bool ValidTile (int i, int j)
Whether or not this tile entity is allowed to survive at the given coordinates. You should check whether the tile is active, as well as the tile's type and frame.
sealed override void WriteExtraData (BinaryWriter writer, bool networkSend)
Don't use this. It is included only for completion's sake.
Static Public Member Functions
static ModTileEntity ConstructFromBase (ModTileEntity tileEntity)
Returns a new ModTileEntity with the same class, mod, name, and type as the parameter. It is very rare that you should have to use this.
static ModTileEntity ConstructFromType (int type)
Returns a new ModTileEntity with the same class, mod, name, and type as the ModTileEntity with the given type. It is very rare that you should have to use this.
static int CountInWorld ()
Returns the number of modded tile entities that exist in the world currently being played.
static ModTileEntity GetTileEntity (int type)
Gets the base ModTileEntity object with the given type.
static void Initialize ()
You should never use this. It is only included here for completion's sake.
static void NetPlaceEntity (int i, int j, int type)
You should never use this. It is only included here for completion's sake.
Public Attributes
const int numVanilla = 3
Properties
Mod mod [get, set]
The mod that added this ModTileEntity.
string Name [get, set]
The internal name of this ModTileEntity.
int Type [get, set]
The numeric type used to identify this kind of tile entity.
Static Private Member Functions
static void UpdateEndInternal ()
static void UpdateStartInternal ()
Static Private Attributes
static int nextTileEntity = numVanilla
Detailed Description
Tile Entities are Entities tightly coupled with tiles, allowing the possibility of tiles to exhibit cool behavior. TileEntity.Update is called in SP and on Server, not on Clients.
See also
Terraria.DataStructures.TileEntity
Definition at line 13 of file ModTileEntity.cs.
Member Function Documentation
virtual bool Terraria.ModLoader.ModTileEntity.Autoload (ref string name) virtual
Allows you to automatically load a tile entity instead of using Mod.AddTileEntity. Return true to allow autoloading; by default returns the mod's autoload property. Name is initialized to the overriding class name. Use this method to either force or stop an autoload, or change the default display name.
Definition at line 199 of file ModTileEntity.cs.
Referenced by Terraria.ModLoader.Mod.AutoloadTileEntity().
{
             return mod.Properties.Autoload;
         }
static ModTileEntity Terraria.ModLoader.ModTileEntity.ConstructFromBase (ModTileEntity tileEntity) static
Returns a new ModTileEntity with the same class, mod, name, and type as the parameter. It is very rare that you should have to use this.
Definition at line 132 of file ModTileEntity.cs.
References Terraria.ModLoader.ModTileEntity.mod, Terraria.ModLoader.ModTileEntity.Name, and Terraria.ModLoader.ModTileEntity.Type.
{
             ModTileEntity newEntity = (ModTileEntity)Activator.CreateInstance(tileEntity.GetType());
             newEntity.mod = tileEntity.mod;
             newEntity.Name = tileEntity.Name;
             newEntity.Type = tileEntity.Type;
             return newEntity;
         }
static ModTileEntity Terraria.ModLoader.ModTileEntity.ConstructFromType (int type) static
Returns a new ModTileEntity with the same class, mod, name, and type as the ModTileEntity with the given type. It is very rare that you should have to use this.
Definition at line 121 of file ModTileEntity.cs.
{
             ModTileEntity tileEntity = GetTileEntity(type);
             if (tileEntity == null) {
                 return null;
             }
             return ConstructFromBase(tileEntity);
         }
static int Terraria.ModLoader.ModTileEntity.CountInWorld () static
Returns the number of modded tile entities that exist in the world currently being played.
Definition at line 70 of file ModTileEntity.cs.
{
             int count = 0;
             foreach (KeyValuePair<int, TileEntity> pair in ByID) {
                 if (pair.Value.type >= numVanilla) {
                     count++;
                 }
             }
             return count;
         }
int Terraria.ModLoader.ModTileEntity.Find (int i, int j)
Returns the entity ID of this kind of tile entity at the given coordinates for you.
Definition at line 171 of file ModTileEntity.cs.
{
             Point16 pos = new Point16(i, j);
             if (ByPosition.ContainsKey(pos)) {
                 TileEntity tileEntity = ByPosition[pos];
                 if (tileEntity.type == Type) {
                     return tileEntity.ID;
                 }
             }
             return -1;
         }
static ModTileEntity Terraria.ModLoader.ModTileEntity.GetTileEntity (int type) static
Gets the base ModTileEntity object with the given type.
Definition at line 58 of file ModTileEntity.cs.
{
             return type >= numVanilla && type < nextTileEntity ? tileEntities[type - numVanilla] : null;
         }
virtual int Terraria.ModLoader.ModTileEntity.Hook_AfterPlacement (int i, int j, int type, int style, int direction) virtual
This method does not get called by tModLoader, and is only included for you convenience so you do not have to cast the result of Mod.GetTileEntity.
Definition at line 241 of file ModTileEntity.cs.
{
             return -1;
         }
static void Terraria.ModLoader.ModTileEntity.Initialize () static
You should never use this. It is only included here for completion's sake.
Definition at line 83 of file ModTileEntity.cs.
{
             _UpdateStart += UpdateStartInternal;
             _UpdateEnd += UpdateEndInternal;
             _NetPlaceEntity += NetPlaceEntity;
         }
void Terraria.ModLoader.ModTileEntity.Kill (int i, int j)
A helper method that removes this kind of tile entity from the given coordinates for you.
Definition at line 156 of file ModTileEntity.cs.
References Terraria.ModLoader.ModTileEntity.OnKill().
{
             Point16 pos = new Point16(i, j);
             if (ByPosition.ContainsKey(pos)) {
                 TileEntity tileEntity = ByPosition[pos];
                 if (tileEntity.type == Type) {
                     ((ModTileEntity)tileEntity).OnKill();
                     ByID.Remove(tileEntity.ID);
                     ByPosition.Remove(pos);
                 }
             }
         }
virtual void Terraria.ModLoader.ModTileEntity.Load (TagCompound tag) virtual
Allows you to load the custom data you have saved for this tile entity.
Definition at line 214 of file ModTileEntity.cs.
{
         }
static void Terraria.ModLoader.ModTileEntity.NetPlaceEntity (int i, int j, int type) static
You should never use this. It is only included here for completion's sake.
Definition at line 104 of file ModTileEntity.cs.
References Terraria.ModLoader.ModTileEntity.OnNetPlace(), Terraria.ModLoader.ModTileEntity.Place(), and Terraria.ModLoader.ModTileEntity.ValidTile().
{
             ModTileEntity tileEntity = GetTileEntity(type);
             if (tileEntity == null) {
                 return;
             }
             if (!tileEntity.ValidTile(i, j)) {
                 return;
             }
             int id = tileEntity.Place(i, j);
             ModTileEntity newEntity = (ModTileEntity)ByID[id];
             newEntity.OnNetPlace();
             NetMessage.SendData(86, -1, -1, null, id, i, j, 0f, 0, 0, 0);
         }
virtual void Terraria.ModLoader.ModTileEntity.NetReceive (BinaryReader reader, bool lightReceive) virtual
Receives the data sent in the NetSend hook. Called on MP Client when receiving tile data (!lightReceive) and when a MessageID.TileEntitySharing message is sent (lightReceive)
Parameters
reader The reader.
lightReceive If true, read only data that can change. Otherwise, read the full information.
Definition at line 230 of file ModTileEntity.cs.
{
         }
virtual void Terraria.ModLoader.ModTileEntity.NetSend (BinaryWriter writer, bool lightSend) virtual
Allows you to send custom data for this tile entity between client and server. This is called on the server while sending tile data (!lightSend) and when a MessageID.TileEntitySharing message is sent (lightSend)
Parameters
writer The writer.
lightSend If true, send only data that can change. Otherwise, send the full information.
Definition at line 222 of file ModTileEntity.cs.
{
         }
virtual void Terraria.ModLoader.ModTileEntity.OnKill () virtual
This method only gets called in the Kill method. If you plan to use that, you can put code here to make things happen when it is called.
Definition at line 266 of file ModTileEntity.cs.
Referenced by Terraria.ModLoader.ModTileEntity.Kill().
{
         }
virtual void Terraria.ModLoader.ModTileEntity.OnNetPlace () virtual
Code that should be run when this tile entity is placed by means of server-syncing. Called on Server only.
Definition at line 248 of file ModTileEntity.cs.
Referenced by Terraria.ModLoader.ModTileEntity.NetPlaceEntity().
{
         }
int Terraria.ModLoader.ModTileEntity.Place (int i, int j)
A helper method that places this kind of tile entity in the given coordinates for you.
Definition at line 143 of file ModTileEntity.cs.
Referenced by Terraria.ModLoader.ModTileEntity.NetPlaceEntity().
{
             ModTileEntity newEntity = ConstructFromBase(this);
             newEntity.Position = new Point16(i, j);
             newEntity.ID = AssignNewID();
             newEntity.type = (byte)Type;
             ByID[newEntity.ID] = newEntity;
             ByPosition[newEntity.Position] = newEntity;
             return newEntity.ID;
         }
virtual void Terraria.ModLoader.ModTileEntity.PostGlobalUpdate () virtual
Code that should be run after all tile entities in the world update.
Definition at line 260 of file ModTileEntity.cs.
Referenced by Terraria.ModLoader.ModTileEntity.UpdateEndInternal().
{
         }
virtual void Terraria.ModLoader.ModTileEntity.PreGlobalUpdate () virtual
Code that should be run before all tile entities in the world update.
Definition at line 254 of file ModTileEntity.cs.
Referenced by Terraria.ModLoader.ModTileEntity.UpdateStartInternal().
{
         }
sealed override void Terraria.ModLoader.ModTileEntity.ReadExtraData (BinaryReader reader, bool networkSend)
Don't use this. It is included only for completion's sake.
Definition at line 192 of file ModTileEntity.cs.
{
             NetReceive(reader, networkSend);
         }
virtual TagCompound Terraria.ModLoader.ModTileEntity.Save () virtual
Allows you to save custom data for this tile entity.
Returns
Definition at line 207 of file ModTileEntity.cs.
{
             return null;
         }
static void Terraria.ModLoader.ModTileEntity.UpdateEndInternal () static private
Definition at line 95 of file ModTileEntity.cs.
References Terraria.ModLoader.ModTileEntity.PostGlobalUpdate().
{
             foreach (ModTileEntity tileEntity in tileEntities) {
                 tileEntity.PostGlobalUpdate();
             }
         }
static void Terraria.ModLoader.ModTileEntity.UpdateStartInternal () static private
Definition at line 89 of file ModTileEntity.cs.
References Terraria.ModLoader.ModTileEntity.PreGlobalUpdate().
{
             foreach (ModTileEntity tileEntity in tileEntities) {
                 tileEntity.PreGlobalUpdate();
             }
         }
abstract bool Terraria.ModLoader.ModTileEntity.ValidTile (int i, int j) pure virtual
Whether or not this tile entity is allowed to survive at the given coordinates. You should check whether the tile is active, as well as the tile's type and frame.
Referenced by Terraria.ModLoader.ModTileEntity.NetPlaceEntity().
sealed override void Terraria.ModLoader.ModTileEntity.WriteExtraData (BinaryWriter writer, bool networkSend)
Don't use this. It is included only for completion's sake.
Definition at line 185 of file ModTileEntity.cs.
{
             NetSend(writer, networkSend);
         }
Member Data Documentation
int Terraria.ModLoader.ModTileEntity.nextTileEntity = numVanilla static private
Definition at line 16 of file ModTileEntity.cs.
const int Terraria.ModLoader.ModTileEntity.numVanilla = 3
Definition at line 15 of file ModTileEntity.cs.
Property Documentation
Mod Terraria.ModLoader.ModTileEntity.mod get set
The mod that added this ModTileEntity.
Definition at line 23 of file ModTileEntity.cs.
Referenced by Terraria.ModLoader.Mod.AddTileEntity(), Terraria.ModLoader.Mod.AutoloadTileEntity(), and Terraria.ModLoader.ModTileEntity.ConstructFromBase().
string Terraria.ModLoader.ModTileEntity.Name get set
The internal name of this ModTileEntity.
Definition at line 31 of file ModTileEntity.cs.
Referenced by Terraria.ModLoader.Mod.AddTileEntity(), and Terraria.ModLoader.ModTileEntity.ConstructFromBase().
int Terraria.ModLoader.ModTileEntity.Type get set
The numeric type used to identify this kind of tile entity.
Definition at line 39 of file ModTileEntity.cs.
Referenced by Terraria.ModLoader.Mod.AddTileEntity(), Terraria.ModLoader.ModTileEntity.ConstructFromBase(), and Terraria.ModLoader.ModContent.MusicExists().