Terraria ModLoader: Terraria.ModLoader.ModRecipe Class Reference
Terraria.ModLoader.ModRecipe Class Reference
This class extends Terraria.Recipe, meaning you can use it in a similar manner to vanilla recipes. However, it provides methods that simplify recipe creation. Recipes are added by creating new instances of ModRecipe, then calling the AddRecipe method.
Public Member Functions
ModRecipe (Mod mod)
Constructor
ModRecipe AddIngredient (int itemID, int stack=1)
Adds an ingredient to this recipe with the given item type and stack size. Ex: recipe.AddIngredient(ItemID.IronAxe)
ModRecipe AddIngredient (Mod mod, string itemName, int stack=1)
Adds an ingredient to this recipe with the given item name from the given mod, and with the given stack stack. If the mod parameter is null, then it will automatically use an item from the mod creating this recipe.
ModRecipe AddIngredient (ModItem item, int stack=1)
Adds an ingredient to this recipe of the given type of item and stack size.
void AddRecipe ()
Adds this recipe to the game. Call this after you have finished setting the result, ingredients, etc.
ModRecipe AddRecipeGroup (string name, int stack=1)
Adds a recipe group ingredient to this recipe with the given RecipeGroup name and stack size. Vanilla recipe groups consist of "Wood", "IronBar", "PresurePlate", "Sand", and "Fragment".
ModRecipe AddRecipeGroup (int recipeGroupID, int stack=1)
Adds a recipe group ingredient to this recipe with the given RecipeGroupID and stack size. Vanilla recipe group IDs can be found in Terraria.ID.RecipeGroupID and modded recipe group IDs will be returned from RecipeGroup.RegisterGroup.
ModRecipe AddTile (int tileID)
Adds a required crafting station with the given tile type to this recipe. Ex: recipe.AddTile(TileID.WorkBenches)
ModRecipe AddTile (Mod mod, string tileName)
Adds a required crafting station to this recipe with the given tile name from the given mod. If the mod parameter is null, then it will automatically use a tile from the mod creating this recipe.
ModRecipe AddTile (ModTile tile)
Adds a required crafting station to this recipe of the given type of tile.
virtual int ConsumeItem (int type, int numRequired)
Allows you to determine how many of a certain ingredient is consumed when this recipe is used. Return the number of ingredients that will actually be consumed. By default returns numRequired.
virtual void OnCraft (Item item)
Allows you to make anything happen when the player uses this recipe. The item parameter is the item the player has just crafted.
virtual bool RecipeAvailable ()
Whether or not the conditions are met for this recipe to be available for the player to use. This hook can be used for conditions unrelated to items or tiles (for example, biome or time).
ModRecipe SetResult (int itemID, int stack=1)
Sets the result of this recipe with the given item type and stack size.
ModRecipe SetResult (Mod mod, string itemName, int stack=1)
Sets the result of this recipe with the given item name from the given mod, and with the given stack stack. If the mod parameter is null, then it will automatically use an item from the mod creating this recipe.
ModRecipe SetResult (ModItem item, int stack=1)
Sets the result of this recipe to the given type of item and stack size. Useful in ModItem.AddRecipes.
Public Attributes
readonly Mod mod
Properties
int RecipeIndex [get, private set]
The index of the recipe in the Main.recipe array.
Private Attributes
int numIngredients = 0
int numTiles = 0
Detailed Description
This class extends Terraria.Recipe, meaning you can use it in a similar manner to vanilla recipes. However, it provides methods that simplify recipe creation. Recipes are added by creating new instances of ModRecipe, then calling the AddRecipe method.
Definition at line 10 of file ModRecipe.cs.
Constructor & Destructor Documentation
Terraria.ModLoader.ModRecipe.ModRecipe (Mod mod)
Constructor
Parameters
mod The mod the recipe originates from.
Definition at line 28 of file ModRecipe.cs.
{
             this.mod = mod;
         }
Member Function Documentation
ModRecipe Terraria.ModLoader.ModRecipe.AddIngredient (int itemID, int stack = 1)
Adds an ingredient to this recipe with the given item type and stack size. Ex: recipe.AddIngredient(ItemID.IronAxe)
Parameters
itemID The item identifier.
stack The stack.
Definition at line 79 of file ModRecipe.cs.
{
             if (numIngredients == 14)
                 throw new RecipeException("Recipe already has maximum number of ingredients. 14 is the max.");
             this.requiredItem[numIngredients].SetDefaults(itemID, false);
             this.requiredItem[numIngredients].stack = stack;
             numIngredients++;
             return this;
         }
ModRecipe Terraria.ModLoader.ModRecipe.AddIngredient (Mod mod, string itemName, int stack = 1)
Adds an ingredient to this recipe with the given item name from the given mod, and with the given stack stack. If the mod parameter is null, then it will automatically use an item from the mod creating this recipe.
Parameters
mod The mod.
itemName Name of the item.
stack The stack.
Exceptions
RecipeException The item " + itemName + " does not exist in mod " + mod.Name + ". If you are trying to use a vanilla item, try removing the first argument.
Definition at line 95 of file ModRecipe.cs.
References Terraria.ModLoader.Environment, Terraria.ModLoader.Mod.ItemType(), and Terraria.ModLoader.Mod.Name.
{
             if (mod == null) {
                 mod = this.mod;
             }
             int type = mod.ItemType(itemName);
             if (type == 0) {
                 string message = "The item " + itemName + " does not exist in the mod " + mod.Name + "." + Environment.NewLine;
                 message += "If you are trying to use a vanilla item, try removing the first argument.";
                 throw new RecipeException(message);
             }
             this.AddIngredient(type, stack);
             return this;
         }
ModRecipe Terraria.ModLoader.ModRecipe.AddIngredient (ModItem item, int stack = 1)
Adds an ingredient to this recipe of the given type of item and stack size.
Parameters
item The item.
stack The stack.
Definition at line 114 of file ModRecipe.cs.
References Terraria.ModLoader.ModItem.item.
{
             this.AddIngredient(item.item.type, stack);
             return this;
         }
void Terraria.ModLoader.ModRecipe.AddRecipe ()
Adds this recipe to the game. Call this after you have finished setting the result, ingredients, etc.
Exceptions
RecipeException A recipe without any result has been added.
Definition at line 230 of file ModRecipe.cs.
{
             if (this.createItem == null || this.createItem.type == 0) {
                 throw new RecipeException("A recipe without any result has been added.");
             }
             if (this.numIngredients > 14 || this.numTiles > 14) {
                 throw new RecipeException("A recipe with either too many tiles or too many ingredients has been added. 14 is the maximum amount.");
             }
             for (int k = 0; k < Recipe.maxRequirements; k++) {
                 if (this.requiredTile[k] == TileID.Bottles) {
                     this.alchemy = true;
                     break;
                 }
             }
             if (Recipe.numRecipes >= Recipe.maxRecipes) {
                 Recipe.maxRecipes += 500;
                 Array.Resize(ref Main.recipe, Recipe.maxRecipes);
                 Array.Resize(ref Main.availableRecipe, Recipe.maxRecipes);
                 Array.Resize(ref Main.availableRecipeY, Recipe.maxRecipes);
                 for (int k = Recipe.numRecipes; k < Recipe.maxRecipes; k++) {
                     Main.recipe[k] = new Recipe();
                     Main.availableRecipeY[k] = 65f * k;
                 }
             }
             Main.recipe[Recipe.numRecipes] = this;
             this.RecipeIndex = Recipe.numRecipes;
             mod.recipes.Add(this);
             Recipe.numRecipes++;
         }
ModRecipe Terraria.ModLoader.ModRecipe.AddRecipeGroup (string name, int stack = 1)
Adds a recipe group ingredient to this recipe with the given RecipeGroup name and stack size. Vanilla recipe groups consist of "Wood", "IronBar", "PresurePlate", "Sand", and "Fragment".
Parameters
name The name.
stack The stack.
Exceptions
RecipeException A recipe group with the name " + name + " does not exist.
Definition at line 125 of file ModRecipe.cs.
{
             if (!RecipeGroup.recipeGroupIDs.ContainsKey(name)) {
                 throw new RecipeException("A recipe group with the name " + name + " does not exist.");
             }
             int id = RecipeGroup.recipeGroupIDs[name];
             RecipeGroup rec = RecipeGroup.recipeGroups[id];
             AddIngredient(rec.ValidItems[rec.IconicItemIndex], stack);
             acceptedGroups.Add(id);
             return this;
         }
ModRecipe Terraria.ModLoader.ModRecipe.AddRecipeGroup (int recipeGroupID, int stack = 1)
Adds a recipe group ingredient to this recipe with the given RecipeGroupID and stack size. Vanilla recipe group IDs can be found in Terraria.ID.RecipeGroupID and modded recipe group IDs will be returned from RecipeGroup.RegisterGroup.
Parameters
recipeGroupID The RecipeGroupID.
stack The stack.
Exceptions
RecipeException A recipe group with the ID " + recipeGroupID + " does not exist.
Definition at line 142 of file ModRecipe.cs.
         {
             if (!RecipeGroup.recipeGroups.ContainsKey(recipeGroupID)) {
                 throw new RecipeException("A recipe group with the ID " + recipeGroupID + " does not exist.");
             }
             RecipeGroup rec = RecipeGroup.recipeGroups[recipeGroupID];
             AddIngredient(rec.ValidItems[rec.IconicItemIndex], stack);
             acceptedGroups.Add(recipeGroupID);
             return this;
         }
ModRecipe Terraria.ModLoader.ModRecipe.AddTile (int tileID)
Adds a required crafting station with the given tile type to this recipe. Ex: recipe.AddTile(TileID.WorkBenches)
Parameters
tileID The tile identifier.
Exceptions
RecipeException No tile has ID " + tileID
Definition at line 158 of file ModRecipe.cs.
References Terraria.ModLoader.TileLoader.TileCount.
{
             if (numTiles == 14)
                 throw new RecipeException("Recipe already has maximum number of tiles. 14 is the max.");
             if (tileID < 0 || tileID >= TileLoader.TileCount) {
                 throw new RecipeException("No tile has ID " + tileID);
             }
             this.requiredTile[numTiles] = tileID;
             numTiles++;
             return this;
         }
ModRecipe Terraria.ModLoader.ModRecipe.AddTile (Mod mod, string tileName)
Adds a required crafting station to this recipe with the given tile name from the given mod. If the mod parameter is null, then it will automatically use a tile from the mod creating this recipe.
Parameters
mod The mod.
tileName Name of the tile.
Exceptions
RecipeException The tile " + tileName + " does not exist in mod " + mod.Name + ". If you are trying to use a vanilla tile, try using ModRecipe.AddTile(tileID).
Definition at line 175 of file ModRecipe.cs.
References Terraria.ModLoader.Environment, Terraria.ModLoader.Mod.Name, and Terraria.ModLoader.Mod.TileType().
{
             if (mod == null) {
                 mod = this.mod;
             }
             int type = mod.TileType(tileName);
             if (type == 0) {
                 string message = "The tile " + tileName + " does not exist in the mod " + mod.Name + "." + Environment.NewLine;
                 message += "If you are trying to use a vanilla tile, try using ModRecipe.AddTile(tileID).";
                 throw new RecipeException(message);
             }
             this.AddTile(type);
             return this;
         }
ModRecipe Terraria.ModLoader.ModRecipe.AddTile (ModTile tile)
Adds a required crafting station to this recipe of the given type of tile.
Parameters
tile The tile.
Definition at line 193 of file ModRecipe.cs.
References Terraria.ModLoader.ModTile.Type.
{
             this.AddTile(tile.Type);
             return this;
         }
virtual int Terraria.ModLoader.ModRecipe.ConsumeItem (int type, int numRequired) virtual
Allows you to determine how many of a certain ingredient is consumed when this recipe is used. Return the number of ingredients that will actually be consumed. By default returns numRequired.
Parameters
type The type.
numRequired The number required.
Returns
Definition at line 222 of file ModRecipe.cs.
{
             return numRequired;
         }
virtual void Terraria.ModLoader.ModRecipe.OnCraft (Item item) virtual
Allows you to make anything happen when the player uses this recipe. The item parameter is the item the player has just crafted.
Parameters
item The item.
Definition at line 210 of file ModRecipe.cs.
Referenced by Terraria.ModLoader.RecipeHooks.OnCraft().
{
         }
virtual bool Terraria.ModLoader.ModRecipe.RecipeAvailable () virtual
Whether or not the conditions are met for this recipe to be available for the player to use. This hook can be used for conditions unrelated to items or tiles (for example, biome or time).
Returns
Whether or not the conditions are met for this recipe to be available for the player to use.
Definition at line 202 of file ModRecipe.cs.
Referenced by Terraria.ModLoader.RecipeHooks.RecipeAvailable().
{
             return true;
         }
ModRecipe Terraria.ModLoader.ModRecipe.SetResult (int itemID, int stack = 1)
Sets the result of this recipe with the given item type and stack size.
Parameters
itemID The item identifier.
stack The stack.
Definition at line 37 of file ModRecipe.cs.
{
             this.createItem.SetDefaults(itemID, false);
             this.createItem.stack = stack;
             return this;
         }
ModRecipe Terraria.ModLoader.ModRecipe.SetResult (Mod mod, string itemName, int stack = 1)
Sets the result of this recipe with the given item name from the given mod, and with the given stack stack. If the mod parameter is null, then it will automatically use an item from the mod creating this recipe.
Parameters
mod The mod the item originates from.
itemName Name of the item.
stack The stack.
Exceptions
RecipeException The item " + itemName + " does not exist in mod " + mod.Name + ". If you are trying to use a vanilla item, try removing the first argument.
Definition at line 50 of file ModRecipe.cs.
References Terraria.ModLoader.Environment, Terraria.ModLoader.Mod.ItemType(), and Terraria.ModLoader.Mod.Name.
{
             if (mod == null) {
                 mod = this.mod;
             }
             int type = mod.ItemType(itemName);
             if (type == 0) {
                 string message = "The item " + itemName + " does not exist in the mod " + mod.Name + "." + Environment.NewLine;
                 message += "If you are trying to use a vanilla item, try removing the first argument.";
                 throw new RecipeException(message);
             }
             this.SetResult(type, stack);
             return this;
         }
ModRecipe Terraria.ModLoader.ModRecipe.SetResult (ModItem item, int stack = 1)
Sets the result of this recipe to the given type of item and stack size. Useful in ModItem.AddRecipes.
Parameters
item The item.
stack The stack.
Definition at line 69 of file ModRecipe.cs.
References Terraria.ModLoader.ModItem.item.
{
             this.SetResult(item.item.type, stack);
             return this;
         }
Member Data Documentation
readonly Mod Terraria.ModLoader.ModRecipe.mod
Definition at line 12 of file ModRecipe.cs.
int Terraria.ModLoader.ModRecipe.numIngredients = 0 private
Definition at line 13 of file ModRecipe.cs.
int Terraria.ModLoader.ModRecipe.numTiles = 0 private
Definition at line 14 of file ModRecipe.cs.
Property Documentation
int Terraria.ModLoader.ModRecipe.RecipeIndex get private set
The index of the recipe in the Main.recipe array.
Definition at line 19 of file ModRecipe.cs.