Terraria ModLoader: Terraria.ModLoader.ErrorLogger Class Reference
Terraria.ModLoader.ErrorLogger Class Reference
This class consists of functions that write error messages to text files for you to read. It also lets you write logs to text files.
Static Public Member Functions
static void ClearLogs ()
Deletes all log files.
static void Log (string message)
You can use this method for your own testing purposes. The message will be added to the Logs.txt file in the Logs folder.
static void Log (object param, bool alternateOutput=false)
Allows you to log an object for your own testing purposes. The message will be added to the Logs.txt file in the Logs folder.
static void LogMulti (IEnumerable< Action > logCalls)
Static Public Attributes
static readonly string LogPath = Path.Combine(Main.SavePath, "Logs")
The file path to which logs are written and stored.
Static Private Attributes
static readonly string[] buildDllLines
static Object logExceptionLock = new Object()
static Object logLock = new Object()
Detailed Description
This class consists of functions that write error messages to text files for you to read. It also lets you write logs to text files.
Definition at line 15 of file ErrorLogger.cs.
Member Function Documentation
static void Terraria.ModLoader.ErrorLogger.ClearLogs () static
Deletes all log files.
Definition at line 281 of file ErrorLogger.cs.
         {
             lock (logLock)
             {
                 Directory.CreateDirectory(LogPath);
                 string[] files = new string[] {
                     LogPath + Path.DirectorySeparatorChar + "Logs.txt",
                     LogPath + Path.DirectorySeparatorChar + "Network Error.txt",
                     LogPath + Path.DirectorySeparatorChar + "Runtime Error.txt",
                     LogPath + Path.DirectorySeparatorChar + "Loading Errors.txt",
                     CompileErrorPath,
                 };
                 foreach (var file in files)
                 {
                     try
                     {
                         File.Delete(file);
                     }
                     catch (Exception)
                     {
                         // Don't worry about it, modder or player might have the file open in tail or notepad.
                     }
                 }
             }
         }
static void Terraria.ModLoader.ErrorLogger.Log (string message) static
You can use this method for your own testing purposes. The message will be added to the Logs.txt file in the Logs folder.
Definition at line 220 of file ErrorLogger.cs.
Referenced by Terraria.ModLoader.ModNPC.AutoStaticDefaults(), Terraria.ModLoader.ModCompile.BuildingMod.BuildingMod(), and Terraria.ModLoader.ModLoader.BuildSort().
         {
             lock (logLock)
             {
                 Directory.CreateDirectory(LogPath);
                 using (StreamWriter writer = File.AppendText(LogPath + Path.DirectorySeparatorChar + "Logs.txt"))
                 {
                     writer.WriteLine(message);
                 }
             }
         }
static void Terraria.ModLoader.ErrorLogger.Log (object param, bool alternateOutput = false) static
Allows you to log an object for your own testing purposes. The message will be added to the Logs.txt file in the Logs folder.
Parameters
param The object to be logged.
alternateOutput If true, the object's data will be manually retrieved and logged. If false, the object's ToString method is logged.
Definition at line 237 of file ErrorLogger.cs.
         {
             lock (logLock)
             {
                 Directory.CreateDirectory(LogPath);
                 using (StreamWriter writer = File.AppendText(LogPath + Path.DirectorySeparatorChar + "Logs.txt"))
                 {
                     if (!alternateOutput)
                     {
                         writer.WriteLine(param.ToString());
                     }
                     else
                     {
                         writer.WriteLine("Object type: " + param.GetType());
                         foreach (PropertyInfo property in param.GetType().GetProperties(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance))
{
                             writer.Write("PROPERTY " + property.Name + " = " + property.GetValue(param, null) + "\n");
                         }
                         foreach (FieldInfo field in param.GetType().GetFields(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance))
{
                             writer.Write("FIELD " + field.Name + " = " + (field.GetValue(param).ToString() != "" ? field.GetValue(param) : "(Field value not found)") + "\n");
                         }
                         foreach (MethodInfo method in param.GetType().GetMethods(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance))
{
                             writer.Write("METHOD " + method.Name + "\n");
                         }
                         int temp = 0;
                         foreach (ConstructorInfo constructor in param.GetType().GetConstructors(BindingFlags.Public | BindingFlags.NonPublic))
{
                             temp++;
                             writer.Write("CONSTRUCTOR " + temp + " : " + constructor.Name + "\n");
                         }
                     }
                 }
             }
         }
static void Terraria.ModLoader.ErrorLogger.LogMulti (IEnumerable< Action > logCalls) static
Definition at line 308 of file ErrorLogger.cs.
Referenced by Terraria.ModLoader.AssemblyManager.LoadedMod.EncapsulateName().
         {
             if (Main.dedServ)
             {
                 foreach (var call in logCalls)
                     call();
                 return;
             }
             var list = logCalls.ToArray();
             list[0]();
             if (list.Length > 1)
                 Interface.errorMessage.OverrideContinueAction(() => LogMulti(list.Skip(1)));
         }
Member Data Documentation
readonly string [] Terraria.ModLoader.ErrorLogger.buildDllLines static private
Initial value:
=
        {
            "Must have either All.dll or both of Windows.dll and Mono.dll",
            "All.dll must not have any references to Microsoft.Xna.Framework or FNA",
            "Windows.dll must reference the windows Terraria.exe and Microsoft.Xna.Framework.dll",
            "Mono.dll must reference a non-windows Terraria.exe and FNA.dll"
        }
Definition at line 22 of file ErrorLogger.cs.
Object Terraria.ModLoader.ErrorLogger.logExceptionLock = new Object() static private
Definition at line 139 of file ErrorLogger.cs.
Object Terraria.ModLoader.ErrorLogger.logLock = new Object() static private
Definition at line 216 of file ErrorLogger.cs.
readonly string Terraria.ModLoader.ErrorLogger.LogPath = Path.Combine(Main.SavePath, "Logs") static
The file path to which logs are written and stored.
Definition at line 20 of file ErrorLogger.cs.