tModLoader: Terraria.ModLoader.ModContent Class Reference
Terraria.ModLoader.ModContent Class Reference
Manages content added by mods. Liasons between mod content and Terraria's arrays and oversees the Loader classes.
Static Public Member Functions
static int BuffType< T > ()
Get the id (type) of a ModBuff by class. Assumes one instance per class.
static int DustType< T > ()
Get the id (type) of a ModDust by class. Assumes one instance per class.
static bool FileExists (string name)
Returns whether or not a file with the specified name exists.
static EquipTexture GetEquipTexture (EquipType type, int slot)
Gets the equipment texture for the specified equipment type and ID.
static byte[] GetFileBytes (string name)
Gets the byte representation of the file with the specified name. The name is in the format of "ModFolder/OtherFolders/FileNameWithExtension". Throws an ArgumentException if the file does not exist.
static T GetInstance< T > ()
static int GetModBackgroundSlot (string texture)
Returns the slot/ID of the background texture with the given name.
static int GetModBossHeadSlot (string texture)
Gets the index of the boss head texture corresponding to the given texture path.
static ModBuff GetModBuff (int type)
Gets the ModBuff instance with the given type. If no ModBuff with the given type exists, returns null.
static ModDust GetModDust (int type)
Gets the ModDust instance with the given type. Returns null if no ModDust with the given type exists.
static int GetModHeadSlot (string texture)
Gets the index of the head texture corresponding to the given texture path.
static ModItem GetModItem (int type)
Gets the ModItem instance corresponding to the specified type. Returns null if no modded item has the given type.
static ModMountData GetModMountData (int type)
Gets the ModMountData instance corresponding to the given type. Returns null if no ModMountData has the given type.
static ModNPC GetModNPC (int type)
Gets the ModNPC instance corresponding to the specified type.
static ModProjectile GetModProjectile (int type)
Gets the ModProjectile instance corresponding to the specified type.
static ModSurfaceBgStyle GetModSurfaceBgStyle (int style)
Returns the ModSurfaceBgStyle object with the given ID.
static ModTile GetModTile (int type)
Gets the ModTile instance with the given type. If no ModTile with the given type exists, returns null.
static ModUgBgStyle GetModUgBgStyle (int style)
Returns the ModUgBgStyle object with the given ID.
static ModWall GetModWall (int type)
Gets the ModWall instance with the given type. If no ModWall with the given type exists, returns null.
static ModWaterfallStyle GetModWaterfallStyle (int style)
Returns the ModWaterfallStyle with the given ID.
static ModWaterStyle GetModWaterStyle (int style)
Returns the ModWaterStyle with the given ID.
static Music GetMusic (string name)
Gets the music with the specified name. The name is in the same format as for texture names. Throws an ArgumentException if the music does not exist. Note: SoundMP3 is in the Terraria.ModLoader namespace.
static SoundEffect GetSound (string name)
Gets the sound with the specified name. The name is in the same format as for texture names. Throws an ArgumentException if the sound does not exist. Note: SoundEffect is in the Microsoft.Xna.Framework.Audio namespace.
static Texture2D GetTexture (string name)
Gets the texture with the specified name. The name is in the format of "ModFolder/OtherFolders/FileNameWithoutExtension". Throws an ArgumentException if the texture does not exist. If a vanilla texture is desired, the format "Terraria/FileNameWithoutExtension" will reference an image from the "terraria/Content/Images" folder. Note: Texture2D is in the Microsoft.Xna.Framework.Graphics namespace.
static int ItemType< T > ()
Get the id (type) of a ModItem by class. Assumes one instance per class.
static int MountType< T > ()
Get the id (type) of a ModMountData by class. Assumes one instance per class.
static bool MusicExists (string name)
Returns whether or not a sound with the specified name exists.
static int NPCType< T > ()
Get the id (type) of a ModNPC by class. Assumes one instance per class.
static Stream OpenRead (string assetName, bool newFileStream=false)
static byte PrefixType< T > ()
Get the id (type) of a ModPrefix by class. Assumes one instance per class.
static int ProjectileType< T > ()
Get the id (type) of a ModProjectile by class. Assumes one instance per class.
static void RefreshModLanguage (GameCulture culture)
static bool SoundExists (string name)
Returns whether or not a sound with the specified name exists.
static void SplitName (string name, out string domain, out string subName)
static bool TextureExists (string name)
Returns whether or not a texture with the specified name exists.
static int TileEntityType< T > ()
Get the id (type) of a ModTileEntity by class. Assumes one instance per class.
static int TileType< T > ()
Get the id (type) of a ModTile by class. Assumes one instance per class.
static int WallType< T > ()
Get the id (type) of a ModWall by class. Assumes one instance per class.
Static Private Member Functions
static void CacheVanillaState ()
static void DisposeMusic ()
static void LoadModContent (CancellationToken token, Action< Mod > loadAction)
static void ResizeArrays (bool unloading=false)
static LocalizedText SetLocalizedText (Dictionary< string, LocalizedText > dict, LocalizedText value)
static void SetupRecipes (CancellationToken token)
Detailed Description
Manages content added by mods. Liasons between mod content and Terraria's arrays and oversees the Loader classes.
Definition at line 26 of file ModContent.cs.
Member Function Documentation
BuffType< T >()
static int Terraria.ModLoader.ModContent.BuffType< T > () static
Get the id (type) of a ModBuff by class. Assumes one instance per class.
Type Constraints
T : ModBuff
T : GetInstance<T>()
T : Type
CacheVanillaState()
static void Terraria.ModLoader.ModContent.CacheVanillaState () static private
Definition at line 392 of file ModContent.cs.
{
            EffectsTracker.CacheVanillaState();
        }
DisposeMusic()
static void Terraria.ModLoader.ModContent.DisposeMusic () static private
Definition at line 581 of file ModContent.cs.
{
            foreach (var music in Main.music.OfType<MusicStreaming>())
                music.Dispose();
        }
DustType< T >()
static int Terraria.ModLoader.ModContent.DustType< T > () static
Get the id (type) of a ModDust by class. Assumes one instance per class.
Type Constraints
T : ModDust
T : GetInstance<T>()
T : Type
FileExists()
static bool Terraria.ModLoader.ModContent.FileExists (string name) static
Returns whether or not a file with the specified name exists.
Definition at line 57 of file ModContent.cs.
{
            if (!name.Contains('/'))
                return false;
            string modName, subName;
            SplitName(name, out modName, out subName);
            Mod mod = ModLoader.GetMod(modName);
            return mod != null && mod.FileExists(subName);
        }
References Terraria.ModLoader.Mod.FileExists(), Terraria.ModLoader.ModLoader.GetMod(), and Terraria.ModLoader.ModContent.SplitName().
GetEquipTexture()
static EquipTexture Terraria.ModLoader.ModContent.GetEquipTexture (EquipType type, int slot) static
Gets the equipment texture for the specified equipment type and ID.
Parameters
type
slot
Returns
GetFileBytes()
static byte[] Terraria.ModLoader.ModContent.GetFileBytes (string name) static
Gets the byte representation of the file with the specified name. The name is in the format of "ModFolder/OtherFolders/FileNameWithExtension". Throws an ArgumentException if the file does not exist.
Exceptions
MissingResourceException Missing mod: " + name
Definition at line 43 of file ModContent.cs.
{
            string modName, subName;
            SplitName(name, out modName, out subName);
            Mod mod = ModLoader.GetMod(modName);
            if (mod == null)
                throw new MissingResourceException("Missing mod: " + name);
            return mod.GetFileBytes(subName);
        }
References Terraria.ModLoader.Mod.GetFileBytes(), Terraria.ModLoader.ModLoader.GetMod(), and Terraria.ModLoader.ModContent.SplitName().
GetInstance< T >()
static T Terraria.ModLoader.ModContent.GetInstance< T > () static
Type Constraints
T : class
T : ContentInstance<T>
T : Instance
GetModBackgroundSlot()
static int Terraria.ModLoader.ModContent.GetModBackgroundSlot (string texture) static
Returns the slot/ID of the background texture with the given name.
GetModBossHeadSlot()
static int Terraria.ModLoader.ModContent.GetModBossHeadSlot (string texture) static
Gets the index of the boss head texture corresponding to the given texture path.
Parameters
texture
Returns
GetModBuff()
static ModBuff Terraria.ModLoader.ModContent.GetModBuff (int type) static
Gets the ModBuff instance with the given type. If no ModBuff with the given type exists, returns null.
GetModDust()
static ModDust Terraria.ModLoader.ModContent.GetModDust (int type) static
Gets the ModDust instance with the given type. Returns null if no ModDust with the given type exists.
GetModHeadSlot()
static int Terraria.ModLoader.ModContent.GetModHeadSlot (string texture) static
Gets the index of the head texture corresponding to the given texture path.
Parameters
texture Relative texture path
Returns
The index of the texture in the heads array, -1 if not found.
GetModItem()
static ModItem Terraria.ModLoader.ModContent.GetModItem (int type) static
Gets the ModItem instance corresponding to the specified type. Returns null if no modded item has the given type.
GetModMountData()
static ModMountData Terraria.ModLoader.ModContent.GetModMountData (int type) static
Gets the ModMountData instance corresponding to the given type. Returns null if no ModMountData has the given type.
Parameters
type The type of the mount.
Returns
Null if not found, otherwise the ModMountData associated with the mount.
GetModNPC()
static ModNPC Terraria.ModLoader.ModContent.GetModNPC (int type) static
Gets the ModNPC instance corresponding to the specified type.
Parameters
type The type of the npc
Returns
The ModNPC instance in the npcs array, null if not found.
GetModProjectile()
static ModProjectile Terraria.ModLoader.ModContent.GetModProjectile (int type) static
Gets the ModProjectile instance corresponding to the specified type.
Parameters
type The type of the projectile
Returns
The ModProjectile instance in the projectiles array, null if not found.
GetModSurfaceBgStyle()
static ModSurfaceBgStyle Terraria.ModLoader.ModContent.GetModSurfaceBgStyle (int style) static
Returns the ModSurfaceBgStyle object with the given ID.
GetModTile()
static ModTile Terraria.ModLoader.ModContent.GetModTile (int type) static
Gets the ModTile instance with the given type. If no ModTile with the given type exists, returns null.
Parameters
type The type of the ModTile
Returns
The ModTile instance in the tiles array, null if not found.
GetModUgBgStyle()
static ModUgBgStyle Terraria.ModLoader.ModContent.GetModUgBgStyle (int style) static
Returns the ModUgBgStyle object with the given ID.
GetModWall()
static ModWall Terraria.ModLoader.ModContent.GetModWall (int type) static
Gets the ModWall instance with the given type. If no ModWall with the given type exists, returns null.
GetModWaterfallStyle()
static ModWaterfallStyle Terraria.ModLoader.ModContent.GetModWaterfallStyle (int style) static
Returns the ModWaterfallStyle with the given ID.
GetModWaterStyle()
static ModWaterStyle Terraria.ModLoader.ModContent.GetModWaterStyle (int style) static
Returns the ModWaterStyle with the given ID.
GetMusic()
static Music Terraria.ModLoader.ModContent.GetMusic (string name) static
Gets the music with the specified name. The name is in the same format as for texture names. Throws an ArgumentException if the music does not exist. Note: SoundMP3 is in the Terraria.ModLoader namespace.
Exceptions
MissingResourceException Missing mod: " + name
Definition at line 179 of file ModContent.cs.
{
            if (Main.dedServ) { return null; }
            string modName, subName;
            SplitName(name, out modName, out subName);
            Mod mod = ModLoader.GetMod(modName);
            if (mod == null) { throw new MissingResourceException("Missing mod: " + name); }
            return mod.GetMusic(subName);
        }
References Terraria.ModLoader.ModLoader.GetMod(), Terraria.ModLoader.Mod.GetMusic(), and Terraria.ModLoader.ModContent.SplitName().
GetSound()
static SoundEffect Terraria.ModLoader.ModContent.GetSound (string name) static
Gets the sound with the specified name. The name is in the same format as for texture names. Throws an ArgumentException if the sound does not exist. Note: SoundEffect is in the Microsoft.Xna.Framework.Audio namespace.
Exceptions
MissingResourceException Missing mod: " + name
Definition at line 147 of file ModContent.cs.
{
            if (Main.dedServ)
                return null;
            string modName, subName;
            SplitName(name, out modName, out subName);
            Mod mod = ModLoader.GetMod(modName);
            if (mod == null)
                throw new MissingResourceException("Missing mod: " + name);
            return mod.GetSound(subName);
        }
References Terraria.ModLoader.ModLoader.GetMod(), Terraria.ModLoader.Mod.GetSound(), and Terraria.ModLoader.ModContent.SplitName().
Referenced by Terraria.ModLoader.Mod.AddSound().
GetTexture()
static Texture2D Terraria.ModLoader.ModContent.GetTexture (string name) static
Gets the texture with the specified name. The name is in the format of "ModFolder/OtherFolders/FileNameWithoutExtension". Throws an ArgumentException if the texture does not exist. If a vanilla texture is desired, the format "Terraria/FileNameWithoutExtension" will reference an image from the "terraria/Content/Images" folder. Note: Texture2D is in the Microsoft.Xna.Framework.Graphics namespace.
Exceptions
MissingResourceException Missing mod: " + name
Definition at line 72 of file ModContent.cs.
{
            if (Main.dedServ)
                return null;
            string modName, subName;
            SplitName(name, out modName, out subName);
            if (modName == "Terraria")
                return Main.instance.Content.Load<Texture2D>("Images" + Path.DirectorySeparatorChar + subName);
            Mod mod = ModLoader.GetMod(modName);
            if (mod == null)
                throw new MissingResourceException("Missing mod: " + name);
            return mod.GetTexture(subName);
        }
References Terraria.ModLoader.ModLoader.GetMod(), and Terraria.ModLoader.ModContent.SplitName().
Referenced by Terraria.ModLoader.Mod.AddBackgroundTexture(), Terraria.ModLoader.Mod.AddBossHeadTexture(), Terraria.ModLoader.Mod.AddDust(), Terraria.ModLoader.Mod.AddEquipTexture(), Terraria.ModLoader.Mod.AddMount(), Terraria.ModLoader.Mod.AddNPCHeadTexture(), Terraria.ModLoader.ModItem.AutoStaticDefaults(), Terraria.ModLoader.ModNPC.AutoStaticDefaults(), Terraria.ModLoader.ModProjectile.AutoStaticDefaults(), Terraria.ModLoader.BackgroundTextureLoader.GetBackgroundSlot(), and Terraria.ModLoader.NPCHeadLoader.GetBossHeadSlot().
ItemType< T >()
static int Terraria.ModLoader.ModContent.ItemType< T > () static
Get the id (type) of a ModItem by class. Assumes one instance per class.
Type Constraints
T : ModItem
T : GetInstance<T>()
T : item.type
LoadModContent()
static void Terraria.ModLoader.ModContent.LoadModContent (CancellationToken token, Action< Mod > loadAction) static private
Definition at line 397 of file ModContent.cs.
{
            MemoryTracking.Checkpoint();
            int num = 0;
            foreach (var mod in ModLoader.Mods) {
                token.ThrowIfCancellationRequested();
                Interface.loadMods.SetCurrentMod(num++, $"{mod.Name} ({mod.DisplayName}) v{mod.Version}");
                try {
                    LoadingMod = mod;
                    loadAction(mod);
                }
                catch (Exception e) {
                    e.Data["mod"] = mod.Name;
                    throw;
                }
                finally {
                    LoadingMod = null;
                    MemoryTracking.Update(mod.Name);
                }
            }
        }
References Terraria.ModLoader.ModLoader.Mods.
MountType< T >()
static int Terraria.ModLoader.ModContent.MountType< T > () static
Get the id (type) of a ModMountData by class. Assumes one instance per class.
Type Constraints
T : ModMountData
T : GetInstance<T>()
T : Type
MusicExists()
static bool Terraria.ModLoader.ModContent.MusicExists (string name) static
Returns whether or not a sound with the specified name exists.
Definition at line 191 of file ModContent.cs.
{
            if (!name.Contains('/')) { return false; }
            string modName, subName;
            SplitName(name, out modName, out subName);
            Mod mod = ModLoader.GetMod(modName);
            return mod != null && mod.MusicExists(subName);
        }
References Terraria.ModLoader.ModLoader.GetMod(), Terraria.ModLoader.Mod.MusicExists(), and Terraria.ModLoader.ModContent.SplitName().
NPCType< T >()
static int Terraria.ModLoader.ModContent.NPCType< T > () static
Get the id (type) of a ModNPC by class. Assumes one instance per class.
Type Constraints
T : ModNPC
T : GetInstance<T>()
T : npc.type
OpenRead()
static Stream Terraria.ModLoader.ModContent.OpenRead (string assetName, bool newFileStream = false) static
Definition at line 629 of file ModContent.cs.
{
            if (!assetName.StartsWith("tmod:"))
                return File.OpenRead(assetName);
            SplitName(assetName.Substring(5).Replace('\\', '/'), out var modName, out var entryPath);
            return ModLoader.GetMod(modName).GetFileStream(entryPath, newFileStream);
        }
References Terraria.ModLoader.Mod.GetFileStream(), Terraria.ModLoader.ModLoader.GetMod(), and Terraria.ModLoader.ModContent.SplitName().
Referenced by Terraria.ModLoader.Audio.MusicStreaming.EnsureLoaded().
PrefixType< T >()
static byte Terraria.ModLoader.ModContent.PrefixType< T > () static
Get the id (type) of a ModPrefix by class. Assumes one instance per class.
Type Constraints
T : ModPrefix
T : GetInstance<T>()
T : Type
ProjectileType< T >()
static int Terraria.ModLoader.ModContent.ProjectileType< T > () static
Get the id (type) of a ModProjectile by class. Assumes one instance per class.
Type Constraints
T : ModProjectile
T : GetInstance<T>()
T : projectile.type
RefreshModLanguage()
static void Terraria.ModLoader.ModContent.RefreshModLanguage (GameCulture culture) static
Definition at line 527 of file ModContent.cs.
{
            Dictionary<string, LocalizedText> dict = LanguageManager.Instance._localizedTexts;
            foreach (ModItem item in ItemLoader.items) {
                LocalizedText text = new LocalizedText(item.DisplayName.Key, item.DisplayName.GetTranslation(culture));
                Lang._itemNameCache[item.item.type] = SetLocalizedText(dict, text);
                text = new LocalizedText(item.Tooltip.Key, item.Tooltip.GetTranslation(culture));
                if (text.Value != null) {
                    text = SetLocalizedText(dict, text);
                    Lang._itemTooltipCache[item.item.type] = ItemTooltip.FromLanguageKey(text.Key);
                }
            }
            foreach (ModPrefix prefix in ModPrefix.prefixes) {
                LocalizedText text = new LocalizedText(prefix.DisplayName.Key, prefix.DisplayName.GetTranslation(culture));
                Lang.prefix[prefix.Type] = SetLocalizedText(dict, text);
            }
            foreach (var keyValuePair in MapLoader.tileEntries) {
                foreach (MapEntry entry in keyValuePair.Value) {
                    if (entry.translation != null) {
                        LocalizedText text = new LocalizedText(entry.translation.Key, entry.translation.GetTranslation(culture));
                        SetLocalizedText(dict, text);
                    }
                }
            }
            foreach (var keyValuePair in MapLoader.wallEntries) {
                foreach (MapEntry entry in keyValuePair.Value) {
                    if (entry.translation != null) {
                        LocalizedText text = new LocalizedText(entry.translation.Key, entry.translation.GetTranslation(culture));
                        SetLocalizedText(dict, text);
                    }
                }
            }
            foreach (ModProjectile proj in ProjectileLoader.projectiles) {
                LocalizedText text = new LocalizedText(proj.DisplayName.Key, proj.DisplayName.GetTranslation(culture));
                Lang._projectileNameCache[proj.projectile.type] = SetLocalizedText(dict, text);
            }
            foreach (ModNPC npc in NPCLoader.npcs) {
                LocalizedText text = new LocalizedText(npc.DisplayName.Key, npc.DisplayName.GetTranslation(culture));
                Lang._npcNameCache[npc.npc.type] = SetLocalizedText(dict, text);
            }
            foreach (ModBuff buff in BuffLoader.buffs) {
                LocalizedText text = new LocalizedText(buff.DisplayName.Key, buff.DisplayName.GetTranslation(culture));
                Lang._buffNameCache[buff.Type] = SetLocalizedText(dict, text);
                text = new LocalizedText(buff.Description.Key, buff.Description.GetTranslation(culture));
                Lang._buffDescriptionCache[buff.Type] = SetLocalizedText(dict, text);
            }
            foreach (Mod mod in ModLoader.Mods) {
                foreach (ModTranslation translation in mod.translations.Values) {
                    LocalizedText text = new LocalizedText(translation.Key, translation.GetTranslation(culture));
                    SetLocalizedText(dict, text);
                }
            }
            LanguageManager.Instance.ProcessCopyCommandsInTexts();
        }
References Terraria.ModLoader.ModBuff.Description, Terraria.ModLoader.ModBuff.DisplayName, Terraria.ModLoader.ModItem.DisplayName, Terraria.ModLoader.ModNPC.DisplayName, Terraria.ModLoader.ModPrefix.DisplayName, Terraria.ModLoader.ModProjectile.DisplayName, Terraria.ModLoader.ModTranslation.GetTranslation(), Terraria.ModLoader.ModItem.item, Terraria.ModLoader.ModTranslation.Key, Terraria.ModLoader.ModLoader.Mods, Terraria.ModLoader.ModNPC.npc, Terraria.ModLoader.ModProjectile.projectile, Terraria.ModLoader.ModContent.SetLocalizedText(), Terraria.ModLoader.ModItem.Tooltip, Terraria.ModLoader.ModBuff.Type, and Terraria.ModLoader.ModPrefix.Type.
ResizeArrays()
static void Terraria.ModLoader.ModContent.ResizeArrays (bool unloading = false) static private
Definition at line 499 of file ModContent.cs.
{
            ItemLoader.ResizeArrays(unloading);
            EquipLoader.ResizeAndFillArrays();
            ModPrefix.ResizeArrays();
            Main.InitializeItemAnimations();
            ModDust.ResizeArrays();
            TileLoader.ResizeArrays(unloading);
            WallLoader.ResizeArrays(unloading);
            ProjectileLoader.ResizeArrays();
            NPCLoader.ResizeArrays(unloading);
            NPCHeadLoader.ResizeAndFillArrays();
            ModGore.ResizeAndFillArrays();
            SoundLoader.ResizeAndFillArrays();
            MountLoader.ResizeArrays();
            BuffLoader.ResizeArrays();
            PlayerHooks.RebuildHooks();
            BackgroundTextureLoader.ResizeAndFillArrays();
            UgBgStyleLoader.ResizeAndFillArrays();
            SurfaceBgStyleLoader.ResizeAndFillArrays();
            GlobalBgStyleLoader.ResizeAndFillArrays(unloading);
            WaterStyleLoader.ResizeArrays();
            WaterfallStyleLoader.ResizeArrays();
            WorldHooks.ResizeArrays();
            foreach (LocalizedText text in LanguageManager.Instance._localizedTexts.Values) {
                text.Override = null;
            }
        }
SetLocalizedText()
static LocalizedText Terraria.ModLoader.ModContent.SetLocalizedText (Dictionary< string, LocalizedText > dict, LocalizedText value) static private
Definition at line 344 of file ModContent.cs.
{
            if (dict.ContainsKey(value.Key)) {
                dict[value.Key].SetValue(value.Value);
            }
            else {
                dict[value.Key] = value;
            }
            return dict[value.Key];
        }
Referenced by Terraria.ModLoader.ModContent.RefreshModLanguage().
SetupRecipes()
static void Terraria.ModLoader.ModContent.SetupRecipes (CancellationToken token) static private
Definition at line 418 of file ModContent.cs.
{
            Interface.loadMods.SetLoadStage("tModLoader.MSAddingRecipes");
            for (int k = 0; k < Recipe.maxRecipes; k++) {
                token.ThrowIfCancellationRequested();
                Main.recipe[k] = new Recipe();
            }
            Recipe.numRecipes = 0;
            RecipeGroupHelper.ResetRecipeGroups();
            RecipeHooks.setupRecipes = true;
            Recipe.SetupRecipes();
            RecipeHooks.setupRecipes = false;
        }
SoundExists()
static bool Terraria.ModLoader.ModContent.SoundExists (string name) static
Returns whether or not a sound with the specified name exists.
Definition at line 164 of file ModContent.cs.
{
            if (!name.Contains('/'))
                return false;
            string modName, subName;
            SplitName(name, out modName, out subName);
            Mod mod = ModLoader.GetMod(modName);
            return mod != null && mod.SoundExists(subName);
        }
References Terraria.ModLoader.ModLoader.GetMod(), Terraria.ModLoader.Mod.SoundExists(), and Terraria.ModLoader.ModContent.SplitName().
SplitName()
static void Terraria.ModLoader.ModContent.SplitName (string name, out string domain, out string subName) static
Definition at line 30 of file ModContent.cs.
{
            int slash = name.IndexOf('/');
            if (slash < 0)
                throw new MissingResourceException("Missing mod qualifier: " + name);
            domain = name.Substring(0, slash);
            subName = name.Substring(slash + 1);
        }
Referenced by Terraria.ModLoader.ModContent.FileExists(), Terraria.ModLoader.ModContent.GetFileBytes(), Terraria.ModLoader.ModContent.GetMusic(), Terraria.ModLoader.ModContent.GetSound(), Terraria.ModLoader.ModContent.GetTexture(), Terraria.ModLoader.ModContent.MusicExists(), Terraria.ModLoader.ModContent.OpenRead(), Terraria.ModLoader.ModContent.SoundExists(), and Terraria.ModLoader.ModContent.TextureExists().
TextureExists()
static bool Terraria.ModLoader.ModContent.TextureExists (string name) static
Returns whether or not a texture with the specified name exists.
Definition at line 91 of file ModContent.cs.
{
            if (Main.dedServ || string.IsNullOrWhiteSpace(name) || !name.Contains('/'))
                return false;
            SplitName(name, out string modName, out string subName);
            if (modName == "Terraria")
                return (Main.instance.Content as TMLContentManager).ImageExists(subName);
            Mod mod = ModLoader.GetMod(modName);
            return mod != null && mod.TextureExists(subName);
        }
References Terraria.ModLoader.ModLoader.GetMod(), Terraria.ModLoader.ModContent.SplitName(), and Terraria.ModLoader.Mod.TextureExists().
Referenced by Terraria.ModLoader.Mod.AddEquipTexture(), Terraria.ModLoader.Mod.AddMount(), and Terraria.ModLoader.ModItem.AutoStaticDefaults().
TileEntityType< T >()
static int Terraria.ModLoader.ModContent.TileEntityType< T > () static
Get the id (type) of a ModTileEntity by class. Assumes one instance per class.
Type Constraints
T : ModTileEntity
T : GetInstance<T>()
T : Type
TileType< T >()
static int Terraria.ModLoader.ModContent.TileType< T > () static
Get the id (type) of a ModTile by class. Assumes one instance per class.
Type Constraints
T : ModTile
T : GetInstance<T>()
T : Type
WallType< T >()
static int Terraria.ModLoader.ModContent.WallType< T > () static
Get the id (type) of a ModWall by class. Assumes one instance per class.
Type Constraints
T : ModWall
T : GetInstance<T>()
T : Type