tModLoader: Terraria.ModLoader.BackupIO.Player Class Reference
Terraria.ModLoader.BackupIO.Player Class Reference
Responsible for archiving player backups
Static Public Member Functions
static void ArchivePlayer (string path, bool isCloudSave)
Static Public Attributes
static readonly string PlayerBackupDir = Path.Combine(PlayerDir, "Backups")
static readonly string PlayerDir = Path.Combine(Main.SavePath, "Players")
Static Private Member Functions
static void WriteArchive (ZipFile zip, bool isCloudSave, string path)
Write the archive. Writes the .plr and .tplr files, then writes the player directory
static void WriteCloudFiles (ZipFile zip, string path)
Write cloud files, which will get the relevant part of the path and write map & tmap files
static void WriteLocalFiles (ZipFile zip, string path)
Write local files, which simply writes the entire player dir
Detailed Description
Responsible for archiving player backups
Definition at line 133 of file BackupIO.cs.
Member Function Documentation
ArchivePlayer()
static void Terraria.ModLoader.BackupIO.Player.ArchivePlayer (string path, bool isCloudSave) static
WriteArchive()
static void Terraria.ModLoader.BackupIO.Player.WriteArchive (ZipFile zip, bool isCloudSave, string path) static private
Write the archive. Writes the .plr and .tplr files, then writes the player directory
Definition at line 144 of file BackupIO.cs.
{
                // Write .plr and .tplr files
                if (FileUtilities.Exists(path, isCloudSave)) zip.AddZipEntry(path, isCloudSave);
                path = Path.ChangeExtension(path, ".tplr");
                if (FileUtilities.Exists(path, isCloudSave)) zip.AddZipEntry(path, isCloudSave);
                // Write other files, such as tmap files to the zip
                if (isCloudSave) WriteCloudFiles(zip, path);
                else WriteLocalFiles(zip, path);
            }
References Terraria.ModLoader.BackupIO.Player.WriteCloudFiles(), and Terraria.ModLoader.BackupIO.Player.WriteLocalFiles().
WriteCloudFiles()
static void Terraria.ModLoader.BackupIO.Player.WriteCloudFiles (ZipFile zip, string path) static private
Write cloud files, which will get the relevant part of the path and write map & tmap files
Definition at line 158 of file BackupIO.cs.
{
                // Path is still equal to local path
                var name = Path.GetFileNameWithoutExtension(path);
                path = Path.ChangeExtension(path, "");
                path = path.Substring(0, path.Length - 1);
                // Write map files from plr dir in cloud
                var cloudFiles = SocialAPI.Cloud.GetFiles().Where(p => p.StartsWith(path, StringComparison.CurrentCultureIgnoreCase)
                                 && (p.EndsWith(".map", StringComparison.CurrentCultureIgnoreCase) || p.EndsWith(".tmap", StringComparison.CurrentCultureIgnoreCase)));
                foreach (string cloudPath in cloudFiles)
                    zip.AddEntry($"{name}/{Path.GetFileName(cloudPath)}", FileUtilities.ReadAllBytes(cloudPath, true));
            }
Referenced by Terraria.ModLoader.BackupIO.Player.WriteArchive().
WriteLocalFiles()
static void Terraria.ModLoader.BackupIO.Player.WriteLocalFiles (ZipFile zip, string path) static private
Write local files, which simply writes the entire player dir
Definition at line 174 of file BackupIO.cs.
{
                // Write map files from plr dir
                var plrDir = Path.Combine(Path.GetDirectoryName(path), Path.GetFileNameWithoutExtension(path));
                if (Directory.Exists(plrDir)) zip.AddZipEntry(plrDir);
            }
Referenced by Terraria.ModLoader.BackupIO.Player.WriteArchive().
Member Data Documentation
PlayerBackupDir
readonly string Terraria.ModLoader.BackupIO.Player.PlayerBackupDir = Path.Combine(PlayerDir, "Backups") static
Definition at line 136 of file BackupIO.cs.
PlayerDir
readonly string Terraria.ModLoader.BackupIO.Player.PlayerDir = Path.Combine(Main.SavePath, "Players") static
Definition at line 135 of file BackupIO.cs.