tModLoader: Terraria.ModLoader.EquipTexture Class Reference
Terraria.ModLoader.EquipTexture Class Reference
This serves as a place for you to program behaviors of equipment textures. This is useful for equipment slots that do not have any item associated with them (for example, the Werewolf buff). Note that this class is purely for visual effects.
Public Member Functions
virtual void ArmorArmGlowMask (Player drawPlayer, float shadow, ref int glowMask, ref Color color)
Allows you to modify which glow mask and in what color is drawn on the player's arms. Note that this is only called for body equipment textures. By default this will call the associated ModItem's ArmorArmGlowMask if there is an associated ModItem.
virtual void ArmorSetShadows (Player player)
Allows you to determine special visual effects this vanity set has on the player without having to code them yourself. By default this will call the associated ModItem's ArmorSetShadows if there is an associated ModItem.
virtual void DrawArmorColor (Player drawPlayer, float shadow, ref Color color, ref int glowMask, ref Color glowMaskColor)
Allows you to modify the colors in which this armor texture and surrounding accessories are drawn, in addition to which glow mask and in what color is drawn. By default this will call the associated ModItem's DrawArmorColor if there is an associated ModItem.
virtual bool DrawBody ()
Return false to hide the player's body when this body equipment texture is worn. By default this will return the associated ModItem's DrawBody, or true if there is no associated ModItem.
virtual void DrawHair (ref bool drawHair, ref bool drawAltHair)
Allows you to determine whether the player's hair or alt (hat) hair draws when this head equipment texture is worn. By default both flags will be false. If there is an associated ModItem, by default this will call that ModItem's DrawHair.
virtual void DrawHands (ref bool drawHands, ref bool drawArms)
Allows you to determine whether the skin/shirt on the player's arms and hands are drawn when this body equipment texture is worn. By default both flags will be false. Note that if drawHands is false, the arms will not be drawn either. If there is an associated ModItem, by default this will call that ModItem's DrawHands.
virtual bool DrawHead ()
Return false to hide the player's head when this head equipment texture is worn. By default this will return the associated ModItem's DrawHead, or true if there is no associated ModItem.
virtual bool DrawLegs ()
Return false to hide the player's legs when this leg or shoe equipment texture is worn. By default this will return the associated ModItem's DrawLegs, or true if there is no associated ModItem.
virtual void HorizontalWingSpeeds (Player player, ref float speed, ref float acceleration)
Allows you to modify horizontal wing speeds.
virtual bool IsVanitySet (int head, int body, int legs)
Returns whether or not the head armor, body armor, and leg armor textures make up a set. This hook is used for the PreUpdateVanitySet, UpdateVanitySet, and ArmorSetShadow hooks. By default this will return the same thing as the associated ModItem's IsVanitySet, or false if no ModItem is associated.
virtual void PreUpdateVanitySet (Player player)
Allows you to create special effects (such as the necro armor's hurt noise) when the player wears this equipment texture's vanity set. This hook is called regardless of whether the player is frozen in any way. By default this will call the associated ModItem's PreUpdateVanitySet if there is an associated ModItem.
virtual void SetMatch (bool male, ref int equipSlot, ref bool robes)
Allows you to modify the equipment that the player appears to be wearing. This hook will only be called for head, body and leg textures. Note that equipSlot is not the same as the item type of the armor the player will appear to be wearing. Worn equipment has a separate set of IDs. You can find the vanilla equipment IDs by looking at the headSlot, bodySlot, and legSlot fields for items, and modded equipment IDs by looking at EquipLoader. If this hook is called on body armor, equipSlot allows you to modify the leg armor the player appears to be wearing. If you modify it, make sure to set robes to true. If this hook is called on leg armor, equipSlot allows you to modify the leg armor the player appears to be wearing, and the robes parameter is useless. By default, if there is an associated ModItem, this will call that ModItem's SetMatch.
virtual void UpdateVanity (Player player, EquipType type)
Allows you to create special effects (such as dust) when this equipment texture is displayed on the player under the given equipment type. By default this will call the associated ModItem's UpdateVanity if there is an associated ModItem.
virtual void UpdateVanitySet (Player player)
Allows you to create special effects (such as dust) when the player wears this equipment texture's vanity set. This hook will only be called if the player is not frozen in any way. By default this will call the associated ModItem's UpdateVanitySet if there is an associated ModItem.
virtual void VerticalWingSpeeds (Player player, ref float ascentWhenFalling, ref float ascentWhenRising, ref float maxCanAscendMultiplier, ref float maxAscentMultiplier, ref float constantAscend)
Allows you to modify vertical wing speeds.
virtual bool WingUpdate (Player player, bool inUse)
Allows for wing textures to do various things while in use. "inUse" is whether or not the jump button is currently pressed. Called when this wing texture visually appears on the player. Use to animate wings, create dusts, invoke sounds, and create lights. By default this will call the associated ModItem's WingUpdate if there is an associated ModItem.
Properties
ModItem item [get, set]
The item that is associated with this equipment texture. Null if no item is associated with this.
Mod mod [get, set]
The mod that added this equipment texture.
string Name [get, set]
The internal name of this equipment texture.
int Slot [get, set]
The slot (internal ID) of this equipment texture.
string Texture [get, set]
The name and folders of the texture file used by this equipment texture.
EquipType Type [get, set]
The type of equipment that this equipment texture is used as.
Detailed Description
This serves as a place for you to program behaviors of equipment textures. This is useful for equipment slots that do not have any item associated with them (for example, the Werewolf buff). Note that this class is purely for visual effects.
Definition at line 8 of file EquipTexture.cs.
Member Function Documentation
ArmorArmGlowMask()
virtual void Terraria.ModLoader.EquipTexture.ArmorArmGlowMask (Player drawPlayer, float shadow, ref int glowMask, ref Color color) virtual
Allows you to modify which glow mask and in what color is drawn on the player's arms. Note that this is only called for body equipment textures. By default this will call the associated ModItem's ArmorArmGlowMask if there is an associated ModItem.
Parameters
drawPlayer
shadow
glowMask
color
Definition at line 194 of file EquipTexture.cs.
{
            if (item != null) {
                item.ArmorArmGlowMask(drawPlayer, shadow, ref glowMask, ref color);
            }
        }
References Terraria.ModLoader.ModItem.ArmorArmGlowMask(), and Terraria.ModLoader.EquipTexture.item.
Referenced by Terraria.ModLoader.ItemLoader.ArmorArmGlowMask().
ArmorSetShadows()
virtual void Terraria.ModLoader.EquipTexture.ArmorSetShadows (Player player) virtual
Allows you to determine special visual effects this vanity set has on the player without having to code them yourself. By default this will call the associated ModItem's ArmorSetShadows if there is an associated ModItem.
Parameters
player
Definition at line 107 of file EquipTexture.cs.
{
            if (item != null) {
                item.ArmorSetShadows(player);
            }
        }
References Terraria.ModLoader.ModItem.ArmorSetShadows(), and Terraria.ModLoader.EquipTexture.item.
Referenced by Terraria.ModLoader.ItemLoader.ArmorSetShadows().
DrawArmorColor()
virtual void Terraria.ModLoader.EquipTexture.DrawArmorColor (Player drawPlayer, float shadow, ref Color color, ref int glowMask, ref Color glowMaskColor) virtual
Allows you to modify the colors in which this armor texture and surrounding accessories are drawn, in addition to which glow mask and in what color is drawn. By default this will call the associated ModItem's DrawArmorColor if there is an associated ModItem.
Parameters
drawPlayer
shadow
color
glowMask
glowMaskColor
Definition at line 181 of file EquipTexture.cs.
{
            if (item != null) {
                item.DrawArmorColor(drawPlayer, shadow, ref color, ref glowMask, ref glowMaskColor);
            }
        }
References Terraria.ModLoader.ModItem.DrawArmorColor(), and Terraria.ModLoader.EquipTexture.item.
Referenced by Terraria.ModLoader.ItemLoader.DrawArmorColor().
DrawBody()
virtual bool Terraria.ModLoader.EquipTexture.DrawBody () virtual
Return false to hide the player's body when this body equipment texture is worn. By default this will return the associated ModItem's DrawBody, or true if there is no associated ModItem.
Returns
Definition at line 161 of file EquipTexture.cs.
{
            return item == null || item.DrawBody();
        }
References Terraria.ModLoader.ModItem.DrawBody(), and Terraria.ModLoader.EquipTexture.item.
Referenced by Terraria.ModLoader.ItemLoader.DrawBody().
DrawHair()
virtual void Terraria.ModLoader.EquipTexture.DrawHair (ref bool drawHair, ref bool drawAltHair) virtual
Allows you to determine whether the player's hair or alt (hat) hair draws when this head equipment texture is worn. By default both flags will be false. If there is an associated ModItem, by default this will call that ModItem's DrawHair.
Parameters
drawHair
drawAltHair
Definition at line 143 of file EquipTexture.cs.
{
            if (item != null) {
                item.DrawHair(ref drawHair, ref drawAltHair);
            }
        }
References Terraria.ModLoader.ModItem.DrawHair(), and Terraria.ModLoader.EquipTexture.item.
Referenced by Terraria.ModLoader.ItemLoader.DrawHair().
DrawHands()
virtual void Terraria.ModLoader.EquipTexture.DrawHands (ref bool drawHands, ref bool drawArms) virtual
Allows you to determine whether the skin/shirt on the player's arms and hands are drawn when this body equipment texture is worn. By default both flags will be false. Note that if drawHands is false, the arms will not be drawn either. If there is an associated ModItem, by default this will call that ModItem's DrawHands.
Parameters
drawHands
drawArms
Definition at line 132 of file EquipTexture.cs.
{
            if (item != null) {
                item.DrawHands(ref drawHands, ref drawArms);
            }
        }
References Terraria.ModLoader.ModItem.DrawHands(), and Terraria.ModLoader.EquipTexture.item.
Referenced by Terraria.ModLoader.ItemLoader.DrawHands().
DrawHead()
virtual bool Terraria.ModLoader.EquipTexture.DrawHead () virtual
Return false to hide the player's head when this head equipment texture is worn. By default this will return the associated ModItem's DrawHead, or true if there is no associated ModItem.
Returns
Definition at line 153 of file EquipTexture.cs.
{
            return item == null || item.DrawHead();
        }
References Terraria.ModLoader.ModItem.DrawHead(), and Terraria.ModLoader.EquipTexture.item.
Referenced by Terraria.ModLoader.ItemLoader.DrawHead().
DrawLegs()
virtual bool Terraria.ModLoader.EquipTexture.DrawLegs () virtual
Return false to hide the player's legs when this leg or shoe equipment texture is worn. By default this will return the associated ModItem's DrawLegs, or true if there is no associated ModItem.
Returns
Definition at line 169 of file EquipTexture.cs.
{
            return item == null || item.DrawLegs();
        }
References Terraria.ModLoader.ModItem.DrawLegs(), and Terraria.ModLoader.EquipTexture.item.
Referenced by Terraria.ModLoader.ItemLoader.DrawLegs().
HorizontalWingSpeeds()
virtual void Terraria.ModLoader.EquipTexture.HorizontalWingSpeeds (Player player, ref float speed, ref float acceleration) virtual
Allows you to modify horizontal wing speeds.
Parameters
player
speed
acceleration
Definition at line 223 of file EquipTexture.cs.
{
            if (item != null) {
                item.HorizontalWingSpeeds(player, ref speed, ref acceleration);
            }
        }
References Terraria.ModLoader.ModItem.HorizontalWingSpeeds(), and Terraria.ModLoader.EquipTexture.item.
Referenced by Terraria.ModLoader.ItemLoader.HorizontalWingSpeeds().
IsVanitySet()
virtual bool Terraria.ModLoader.EquipTexture.IsVanitySet (int head, int body, int legs) virtual
Returns whether or not the head armor, body armor, and leg armor textures make up a set. This hook is used for the PreUpdateVanitySet, UpdateVanitySet, and ArmorSetShadow hooks. By default this will return the same thing as the associated ModItem's IsVanitySet, or false if no ModItem is associated.
Parameters
head
body
legs
Returns
Definition at line 76 of file EquipTexture.cs.
{
            if (item == null) {
                return false;
            }
            return item.IsVanitySet(head, body, legs);
        }
References Terraria.ModLoader.ModItem.IsVanitySet(), and Terraria.ModLoader.EquipTexture.item.
Referenced by Terraria.ModLoader.ItemLoader.ArmorSetShadows(), Terraria.ModLoader.ItemLoader.PreUpdateVanitySet(), and Terraria.ModLoader.ItemLoader.UpdateVanitySet().
PreUpdateVanitySet()
virtual void Terraria.ModLoader.EquipTexture.PreUpdateVanitySet (Player player) virtual
Allows you to create special effects (such as the necro armor's hurt noise) when the player wears this equipment texture's vanity set. This hook is called regardless of whether the player is frozen in any way. By default this will call the associated ModItem's PreUpdateVanitySet if there is an associated ModItem.
Parameters
player
Definition at line 87 of file EquipTexture.cs.
{
            if (item != null) {
                item.PreUpdateVanitySet(player);
            }
        }
References Terraria.ModLoader.EquipTexture.item, and Terraria.ModLoader.ModItem.PreUpdateVanitySet().
Referenced by Terraria.ModLoader.ItemLoader.PreUpdateVanitySet().
SetMatch()
virtual void Terraria.ModLoader.EquipTexture.SetMatch (bool male, ref int equipSlot, ref bool robes) virtual
Allows you to modify the equipment that the player appears to be wearing. This hook will only be called for head, body and leg textures. Note that equipSlot is not the same as the item type of the armor the player will appear to be wearing. Worn equipment has a separate set of IDs. You can find the vanilla equipment IDs by looking at the headSlot, bodySlot, and legSlot fields for items, and modded equipment IDs by looking at EquipLoader. If this hook is called on body armor, equipSlot allows you to modify the leg armor the player appears to be wearing. If you modify it, make sure to set robes to true. If this hook is called on leg armor, equipSlot allows you to modify the leg armor the player appears to be wearing, and the robes parameter is useless. By default, if there is an associated ModItem, this will call that ModItem's SetMatch.
Parameters
male
equipSlot
robes
Definition at line 121 of file EquipTexture.cs.
{
            if (item != null) {
                item.SetMatch(male, ref equipSlot, ref robes);
            }
        }
References Terraria.ModLoader.EquipTexture.item, and Terraria.ModLoader.ModItem.SetMatch().
Referenced by Terraria.ModLoader.ItemLoader.SetMatch().
UpdateVanity()
virtual void Terraria.ModLoader.EquipTexture.UpdateVanity (Player player, EquipType type) virtual
Allows you to create special effects (such as dust) when this equipment texture is displayed on the player under the given equipment type. By default this will call the associated ModItem's UpdateVanity if there is an associated ModItem.
Parameters
player
type
Definition at line 63 of file EquipTexture.cs.
{
            if (item != null) {
                item.UpdateVanity(player, type);
            }
        }
References Terraria.ModLoader.EquipTexture.item, and Terraria.ModLoader.ModItem.UpdateVanity().
Referenced by Terraria.ModLoader.ItemLoader.UpdateVanity().
UpdateVanitySet()
virtual void Terraria.ModLoader.EquipTexture.UpdateVanitySet (Player player) virtual
Allows you to create special effects (such as dust) when the player wears this equipment texture's vanity set. This hook will only be called if the player is not frozen in any way. By default this will call the associated ModItem's UpdateVanitySet if there is an associated ModItem.
Parameters
player
Definition at line 97 of file EquipTexture.cs.
{
            if (item != null) {
                item.UpdateVanitySet(player);
            }
        }
References Terraria.ModLoader.EquipTexture.item, and Terraria.ModLoader.ModItem.UpdateVanitySet().
Referenced by Terraria.ModLoader.ItemLoader.UpdateVanitySet().
VerticalWingSpeeds()
virtual void Terraria.ModLoader.EquipTexture.VerticalWingSpeeds (Player player, ref float ascentWhenFalling, ref float ascentWhenRising, ref float maxCanAscendMultiplier, ref float maxAscentMultiplier, ref float constantAscend) virtual
Allows you to modify vertical wing speeds.
Parameters
player
ascentWhenFalling
ascentWhenRising
maxCanAscendMultiplier
maxAscentMultiplier
constantAscend
Definition at line 209 of file EquipTexture.cs.
{
            if (item != null) {
                item.VerticalWingSpeeds(player, ref ascentWhenFalling, ref ascentWhenRising, ref maxCanAscendMultiplier,
                    ref maxAscentMultiplier, ref constantAscend);
            }
        }
References Terraria.ModLoader.EquipTexture.item, and Terraria.ModLoader.ModItem.VerticalWingSpeeds().
Referenced by Terraria.ModLoader.ItemLoader.VerticalWingSpeeds().
WingUpdate()
virtual bool Terraria.ModLoader.EquipTexture.WingUpdate (Player player, bool inUse) virtual
Allows for wing textures to do various things while in use. "inUse" is whether or not the jump button is currently pressed. Called when this wing texture visually appears on the player. Use to animate wings, create dusts, invoke sounds, and create lights. By default this will call the associated ModItem's WingUpdate if there is an associated ModItem.
Parameters
player
inUse
Returns
Definition at line 235 of file EquipTexture.cs.
{
            return item?.WingUpdate(player, inUse) ?? false;
        }
References Terraria.ModLoader.EquipTexture.item, and Terraria.ModLoader.ModItem.WingUpdate().
Referenced by Terraria.ModLoader.ItemLoader.WingUpdate().
Property Documentation
item
ModItem Terraria.ModLoader.EquipTexture.item get set
The item that is associated with this equipment texture. Null if no item is associated with this.
Definition at line 53 of file EquipTexture.cs.
{
            get;
            internal set;
        }
Referenced by Terraria.ModLoader.EquipTexture.ArmorArmGlowMask(), Terraria.ModLoader.EquipTexture.ArmorSetShadows(), Terraria.ModLoader.EquipTexture.DrawArmorColor(), Terraria.ModLoader.EquipTexture.DrawBody(), Terraria.ModLoader.EquipTexture.DrawHair(), Terraria.ModLoader.EquipTexture.DrawHands(), Terraria.ModLoader.EquipTexture.DrawHead(), Terraria.ModLoader.EquipTexture.DrawLegs(), Terraria.ModLoader.ItemLoader.GetWing(), Terraria.ModLoader.EquipTexture.HorizontalWingSpeeds(), Terraria.ModLoader.EquipTexture.IsVanitySet(), Terraria.ModLoader.EquipTexture.PreUpdateVanitySet(), Terraria.ModLoader.EquipTexture.SetMatch(), Terraria.ModLoader.EquipTexture.UpdateVanity(), Terraria.ModLoader.EquipTexture.UpdateVanitySet(), Terraria.ModLoader.EquipTexture.VerticalWingSpeeds(), and Terraria.ModLoader.EquipTexture.WingUpdate().
mod
Mod Terraria.ModLoader.EquipTexture.mod get set
The mod that added this equipment texture.
Definition at line 21 of file EquipTexture.cs.
                       {
            get;
            internal set;
        }
Name
string Terraria.ModLoader.EquipTexture.Name get set
The internal name of this equipment texture.
Definition at line 29 of file EquipTexture.cs.
{
            get;
            internal set;
        }
Slot
int Terraria.ModLoader.EquipTexture.Slot get set
The slot (internal ID) of this equipment texture.
Definition at line 45 of file EquipTexture.cs.
{
            get;
            internal set;
        }
Texture
string Terraria.ModLoader.EquipTexture.Texture get set
The name and folders of the texture file used by this equipment texture.
Definition at line 13 of file EquipTexture.cs.
{
            get;
            internal set;
        }
Type
EquipType Terraria.ModLoader.EquipTexture.Type get set
The type of equipment that this equipment texture is used as.
Definition at line 37 of file EquipTexture.cs.
{
            get;
            internal set;
        }