tModLoader: Terraria.ModLoader.IO.TagSerializer< T, S > Class Template Reference
Terraria.ModLoader.IO.TagSerializer< T, S > Class Template Reference abstract
Public Member Functions
abstract object Deserialize (object tag)
override object Deserialize (object tag)
abstract T Deserialize (S tag)
abstract IList DeserializeList (IList value)
override IList DeserializeList (IList value)
abstract object Serialize (object value)
override object Serialize (object value)
abstract S Serialize (T value)
abstract IList SerializeList (IList value)
override IList SerializeList (IList value)
Static Public Member Functions
static void AddSerializer (TagSerializer serializer)
static Type GetType (string name)
static bool TryGetSerializer (Type type, out TagSerializer serializer)
Properties
abstract Type TagType [get]
override Type TagType [get]
abstract Type Type [get]
override Type Type [get]
Static Private Member Functions
static TagSerializer ()
Static Private Attributes
static IDictionary< Type, TagSerializer > serializers = new Dictionary<Type, TagSerializer>()
static IDictionary< string, Type > typeNameCache = new Dictionary<string, Type>()
Detailed Description
Definition at line 76 of file TagSerializer.cs.
Constructor & Destructor Documentation
TagSerializer()
static Terraria.ModLoader.IO.TagSerializer< T, S >.TagSerializer () static private
Definition at line 23 of file TagSerializer.cs.
{
            Reload();
        }
Referenced by Terraria.ModLoader.IO.TagSerializer< T, S >.TryGetSerializer().
Member Function Documentation
AddSerializer()
static void Terraria.ModLoader.IO.TagSerializer< T, S >.AddSerializer (TagSerializer< T, S > serializer) static
Definition at line 54 of file TagSerializer.cs.
{
            serializers.Add(serializer.Type, serializer);
        }
References Terraria.ModLoader.IO.TagSerializer< T, S >.serializers, and Terraria.ModLoader.IO.TagSerializer< T, S >.Type.
Deserialize() [1/3]
abstract object Terraria.ModLoader.IO.TagSerializer< T, S >.Deserialize (object tag) pure virtual
Referenced by Terraria.ModLoader.IO.TagSerializer< T, S >.Deserialize(), Terraria.ModLoader.IO.TagIO.Deserialize(), and Terraria.ModLoader.IO.TagSerializer< T, S >.DeserializeList().
Deserialize() [2/3]
override object Terraria.ModLoader.IO.TagSerializer< T, S >.Deserialize (object tag)
Definition at line 88 of file TagSerializer.cs.
{
            return Deserialize((S)tag);
        }
References Terraria.ModLoader.IO.TagSerializer< T, S >.Deserialize().
Deserialize() [3/3]
abstract T Terraria.ModLoader.IO.TagSerializer< T, S >.Deserialize (S tag) pure virtual
DeserializeList() [1/2]
abstract IList Terraria.ModLoader.IO.TagSerializer< T, S >.DeserializeList (IList value) pure virtual
DeserializeList() [2/2]
override IList Terraria.ModLoader.IO.TagSerializer< T, S >.DeserializeList (IList value)
Definition at line 96 of file TagSerializer.cs.
{
            return ((IList<S>)value).Select(Deserialize).ToList();
        }
References Terraria.ModLoader.IO.TagSerializer< T, S >.Deserialize().
GetType()
static Type Terraria.ModLoader.IO.TagSerializer< T, S >.GetType (string name) static
Definition at line 58 of file TagSerializer.cs.
{
            if (typeNameCache.TryGetValue(name, out Type type))
                return type;
            type = Type.GetType(name);
            if (type != null)
                return typeNameCache[name] = type;
            foreach (var mod in ModLoader.Mods) {
                type = mod.Code?.GetType(name);
                if (type != null)
                    return typeNameCache[name] = type;
            }
            return null;
        }
References Terraria.ModLoader.ModLoader.Mods, Terraria.ModLoader.IO.TagSerializer< T, S >.Type, and Terraria.ModLoader.IO.TagSerializer< T, S >.typeNameCache.
Serialize() [1/3]
abstract object Terraria.ModLoader.IO.TagSerializer< T, S >.Serialize (object value) pure virtual
Referenced by Terraria.ModLoader.IO.TagIO.Serialize(), Terraria.ModLoader.IO.TagSerializer< T, S >.Serialize(), and Terraria.ModLoader.IO.TagSerializer< T, S >.SerializeList().
Serialize() [2/3]
override object Terraria.ModLoader.IO.TagSerializer< T, S >.Serialize (object value)
Definition at line 84 of file TagSerializer.cs.
{
            return Serialize((T)value);
        }
References Terraria.ModLoader.IO.TagSerializer< T, S >.Serialize().
Serialize() [3/3]
abstract S Terraria.ModLoader.IO.TagSerializer< T, S >.Serialize (T value) pure virtual
SerializeList() [1/2]
abstract IList Terraria.ModLoader.IO.TagSerializer< T, S >.SerializeList (IList value) pure virtual
Referenced by Terraria.ModLoader.IO.TagIO.Serialize().
SerializeList() [2/2]
override IList Terraria.ModLoader.IO.TagSerializer< T, S >.SerializeList (IList value)
Definition at line 92 of file TagSerializer.cs.
{
            return ((IList<T>)value).Select(Serialize).ToList();
        }
References Terraria.ModLoader.IO.TagSerializer< T, S >.Serialize().
TryGetSerializer()
static bool Terraria.ModLoader.IO.TagSerializer< T, S >.TryGetSerializer (Type type, out TagSerializer< T, S > serializer) static
Definition at line 41 of file TagSerializer.cs.
{
            if (serializers.TryGetValue(type, out serializer))
                return true;
            if (typeof(TagSerializable).IsAssignableFrom(type)) {
                var sType = typeof(TagSerializableSerializer<>).MakeGenericType(type);
                serializers[type] = serializer = (TagSerializer)sType.GetConstructor(new Type[0]).Invoke(new object[0]);
                return true;
            }
            return false;
        }
References Terraria.ModLoader.IO.TagSerializer< T, S >.TagSerializer(), Terraria.ModLoader.IO.TagSerializer< T, S >.serializers, and Terraria.ModLoader.IO.TagSerializer< T, S >.Type.
Referenced by Terraria.ModLoader.IO.TagIO.Deserialize(), and Terraria.ModLoader.IO.TagIO.Serialize().
Member Data Documentation
serializers
IDictionary<Type, TagSerializer> Terraria.ModLoader.IO.TagSerializer< T, S >.serializers = new Dictionary<Type, TagSerializer>() static private
Definition at line 20 of file TagSerializer.cs.
Referenced by Terraria.ModLoader.IO.TagSerializer< T, S >.AddSerializer(), and Terraria.ModLoader.IO.TagSerializer< T, S >.TryGetSerializer().
typeNameCache
IDictionary<string, Type> Terraria.ModLoader.IO.TagSerializer< T, S >.typeNameCache = new Dictionary<string, Type>() static private
Definition at line 21 of file TagSerializer.cs.
Referenced by Terraria.ModLoader.IO.TagSerializer< T, S >.GetType().
Property Documentation
TagType [1/2]
abstract Type Terraria.ModLoader.IO.TagSerializer< T, S >.TagType get
Definition at line 13 of file TagSerializer.cs.
{ get; }
Referenced by Terraria.ModLoader.IO.TagIO.Deserialize().
TagType [2/2]
override Type Terraria.ModLoader.IO.TagSerializer< T, S >.TagType get
Definition at line 79 of file TagSerializer.cs.
Type [1/2]
abstract Type Terraria.ModLoader.IO.TagSerializer< T, S >.Type get
Definition at line 12 of file TagSerializer.cs.
{ get; }
Referenced by Terraria.ModLoader.IO.TagSerializer< T, S >.AddSerializer(), Terraria.ModLoader.IO.TagSerializer< T, S >.GetType(), and Terraria.ModLoader.IO.TagSerializer< T, S >.TryGetSerializer().
Type [2/2]
override Type Terraria.ModLoader.IO.TagSerializer< T, S >.Type get
Definition at line 78 of file TagSerializer.cs.