tModLoader: Terraria.ModLoader.SurfaceBgStyleLoader Class Reference
Terraria.ModLoader.SurfaceBgStyleLoader Class Reference
Static Public Member Functions
static void ChooseStyle (ref int style)
static void DrawCloseBackground (int style)
static void DrawFarTexture ()
static void DrawMiddleTexture ()
static ModSurfaceBgStyle GetSurfaceBgStyle (int style)
Returns the ModSurfaceBgStyle object with the given ID.
static void ModifyFarFades (int style, float[] fades, float transitionSpeed)
Static Public Attributes
const int vanillaSurfaceBgStyleCount = 10
Static Private Attributes
static int nextSurfaceBgStyle = vanillaSurfaceBgStyleCount
Detailed Description
Definition at line 69 of file BackgroundStyleLoaders.cs.
Member Function Documentation
ChooseStyle()
static void Terraria.ModLoader.SurfaceBgStyleLoader.ChooseStyle (ref int style) static
Definition at line 101 of file BackgroundStyleLoaders.cs.
{
            if (!GlobalBgStyleLoader.loaded) {
                return;
            }
            foreach (var surfaceBgStyle in surfaceBgStyles) {
                if (surfaceBgStyle.ChooseBgStyle()) {
                    style = surfaceBgStyle.Slot;
                }
            }
            foreach (var hook in GlobalBgStyleLoader.HookChooseSurfaceBgStyle) {
                hook(ref style);
            }
        }
DrawCloseBackground()
static void Terraria.ModLoader.SurfaceBgStyleLoader.DrawCloseBackground (int style) static
Definition at line 181 of file BackgroundStyleLoaders.cs.
{
            if (!GlobalBgStyleLoader.loaded) {
                return;
            }
            if (Main.bgAlpha[style] <= 0f) {
                return;
            }
            var surfaceBgStyle = GetSurfaceBgStyle(style);
            if (surfaceBgStyle != null && surfaceBgStyle.PreDrawCloseBackground(Main.spriteBatch)) {
                Main.bgScale = 1.25f;
                Main.instance.bgParallax = 0.37;
                float a = 1800.0f;
                float b = 1750.0f;
                int textureSlot = surfaceBgStyle.ChooseCloseTexture(ref Main.bgScale, ref Main.instance.bgParallax, ref a, ref b);
                if (textureSlot >= 0 && textureSlot < Main.backgroundTexture.Length) {
                    //Custom: bgScale, textureslot, patallaz, these 2 numbers...., Top and Start?
                    Main.instance.LoadBackground(textureSlot);
                    Main.bgScale *= 2f;
                    Main.bgW = (int)((float)Main.backgroundWidth[textureSlot] * Main.bgScale);
                    SkyManager.Instance.DrawToDepth(Main.spriteBatch, 1f / (float)Main.instance.bgParallax);
                    Main.instance.bgStart = (int)(-Math.IEEERemainder(Main.screenPosition.X * Main.instance.bgParallax, Main.bgW) - (Main.bgW / 2));
                    Main.instance.bgTop = (int)((-Main.screenPosition.Y + Main.instance.screenOff / 2f) / (Main.worldSurface * 16.0) * a + b) + (int)Main.instance.scAdj;
                    if (Main.gameMenu) {
                        Main.instance.bgTop = 320;
                    }
                    Main.instance.bgLoops = Main.screenWidth / Main.bgW + 2;
                    if ((double)Main.screenPosition.Y < Main.worldSurface * 16.0 + 16.0) {
                        for (int k = 0; k < Main.instance.bgLoops; k++) {
                            Main.spriteBatch.Draw(Main.backgroundTexture[textureSlot],
                                new Vector2((Main.instance.bgStart + Main.bgW * k), Main.instance.bgTop),
                                new Rectangle(0, 0, Main.backgroundWidth[textureSlot], Main.backgroundHeight[textureSlot]),
                                Main.backColor, 0f, default(Vector2), Main.bgScale, SpriteEffects.None, 0f);
                        }
                    }
                }
            }
        }
References Terraria.ModLoader.SurfaceBgStyleLoader.GetSurfaceBgStyle().
DrawFarTexture()
static void Terraria.ModLoader.SurfaceBgStyleLoader.DrawFarTexture () static
Definition at line 128 of file BackgroundStyleLoaders.cs.
{
            if (!GlobalBgStyleLoader.loaded) {
                return;
            }
            // TODO: Causes background to flicker during load because Main.bgAlpha2 is resized after surfaceBgStyles is added to in AutoLoad.
            foreach (var style in surfaceBgStyles) {
                int slot = style.Slot;
                Main.backColor = Main.trueBackColor;
                Main.backColor.R = (byte)(Main.backColor.R * Main.bgAlpha2[slot]);
                Main.backColor.G = (byte)(Main.backColor.G * Main.bgAlpha2[slot]);
                Main.backColor.B = (byte)(Main.backColor.B * Main.bgAlpha2[slot]);
                Main.backColor.A = (byte)(Main.backColor.A * Main.bgAlpha2[slot]);
                if (Main.bgAlpha2[slot] > 0f) {
                    int textureSlot = style.ChooseFarTexture();
                    if (textureSlot >= 0 && textureSlot < Main.backgroundTexture.Length) {
                        Main.instance.LoadBackground(textureSlot);
                        for (int k = 0; k < Main.instance.bgLoops; k++) {
                            Main.spriteBatch.Draw(Main.backgroundTexture[textureSlot],
                                new Vector2(Main.instance.bgStart + Main.bgW * k, Main.instance.bgTop),
                                new Rectangle(0, 0, Main.backgroundWidth[textureSlot], Main.backgroundHeight[textureSlot]),
                                Main.backColor, 0f, default(Vector2), Main.bgScale, SpriteEffects.None, 0f);
                        }
                    }
                }
            }
        }
DrawMiddleTexture()
static void Terraria.ModLoader.SurfaceBgStyleLoader.DrawMiddleTexture () static
Definition at line 155 of file BackgroundStyleLoaders.cs.
{
            if (!GlobalBgStyleLoader.loaded) {
                return;
            }
            foreach (var style in surfaceBgStyles) {
                int slot = style.Slot;
                Main.backColor = Main.trueBackColor;
                Main.backColor.R = (byte)(Main.backColor.R * Main.bgAlpha2[slot]);
                Main.backColor.G = (byte)(Main.backColor.G * Main.bgAlpha2[slot]);
                Main.backColor.B = (byte)(Main.backColor.B * Main.bgAlpha2[slot]);
                Main.backColor.A = (byte)(Main.backColor.A * Main.bgAlpha2[slot]);
                if (Main.bgAlpha2[slot] > 0f) {
                    int textureSlot = style.ChooseMiddleTexture();
                    if (textureSlot >= 0 && textureSlot < Main.backgroundTexture.Length) {
                        Main.instance.LoadBackground(textureSlot);
                        for (int k = 0; k < Main.instance.bgLoops; k++) {
                            Main.spriteBatch.Draw(Main.backgroundTexture[textureSlot],
                                new Vector2(Main.instance.bgStart + Main.bgW * k, Main.instance.bgTop),
                                new Rectangle(0, 0, Main.backgroundWidth[textureSlot], Main.backgroundHeight[textureSlot]),
                                Main.backColor, 0f, default(Vector2), Main.bgScale, SpriteEffects.None, 0f);
                        }
                    }
                }
            }
        }
GetSurfaceBgStyle()
static ModSurfaceBgStyle Terraria.ModLoader.SurfaceBgStyleLoader.GetSurfaceBgStyle (int style) static
Returns the ModSurfaceBgStyle object with the given ID.
Definition at line 86 of file BackgroundStyleLoaders.cs.
{
            return style >= vanillaSurfaceBgStyleCount && style < nextSurfaceBgStyle
                ? surfaceBgStyles[style - vanillaSurfaceBgStyleCount] : null;
        }
References Terraria.ModLoader.SurfaceBgStyleLoader.nextSurfaceBgStyle, and Terraria.ModLoader.SurfaceBgStyleLoader.vanillaSurfaceBgStyleCount.
Referenced by Terraria.ModLoader.SurfaceBgStyleLoader.DrawCloseBackground(), and Terraria.ModLoader.SurfaceBgStyleLoader.ModifyFarFades().
ModifyFarFades()
static void Terraria.ModLoader.SurfaceBgStyleLoader.ModifyFarFades (int style, float[] fades, float transitionSpeed) static
Definition at line 115 of file BackgroundStyleLoaders.cs.
{
            if (!GlobalBgStyleLoader.loaded) {
                return;
            }
            var surfaceBgStyle = GetSurfaceBgStyle(style);
            if (surfaceBgStyle != null) {
                surfaceBgStyle.ModifyFarFades(fades, transitionSpeed);
            }
            foreach (var hook in GlobalBgStyleLoader.HookModifyFarSurfaceFades) {
                hook(style, fades, transitionSpeed);
            }
        }
References Terraria.ModLoader.SurfaceBgStyleLoader.GetSurfaceBgStyle().
Member Data Documentation
nextSurfaceBgStyle
int Terraria.ModLoader.SurfaceBgStyleLoader.nextSurfaceBgStyle = vanillaSurfaceBgStyleCount static private
Definition at line 72 of file BackgroundStyleLoaders.cs.
Referenced by Terraria.ModLoader.SurfaceBgStyleLoader.GetSurfaceBgStyle().
vanillaSurfaceBgStyleCount
const int Terraria.ModLoader.SurfaceBgStyleLoader.vanillaSurfaceBgStyleCount = 10 static
Definition at line 71 of file BackgroundStyleLoaders.cs.
Referenced by Terraria.ModLoader.SurfaceBgStyleLoader.GetSurfaceBgStyle().