tModLoader: Terraria.ModLoader.RecipeFinder Class Reference
Terraria.ModLoader.RecipeFinder Class Reference
This class will search through all existing recipes for you based on criteria that you give it. It's useful for finding a particular vanilla recipe that you wish to remove or edit. Use this by creating new instances with the empty constructor for each search you perform.
Public Member Functions
RecipeFinder ()
void AddIngredient (int itemID, int stack=1)
Adds an ingredient with the given item type and stack size to the search criteria.
void AddRecipeGroup (int recipeGroupID, int stack=1)
Adds a recipe group ingredient with the given RecipeGroupID and stack size to the search criteria.
void AddRecipeGroup (string name, int stack=1)
Adds a recipe group ingredient with the given RecipeGroup name and stack size to the search criteria.
void AddTile (int tileID)
Adds a required crafting station with the given tile type to the search criteria.
Recipe FindExactRecipe ()
Searches for a recipe that matches the search criteria exactly, then returns it. That means the recipe will have exactly the same ingredients, tiles, liquid requirements, recipe groups, and result; even the stack sizes will match. If no recipe with an exact match is found, this will return null.
List< Recipe > SearchRecipes ()
Searches for all recipes that include the search criteria, then returns them in a list. In terms of ingredients, it will search for recipes that include all the search criteria ingredients, with stack sizes greater than or equal to the search criteria. It will also make sure the recipes include all search criteria recipe groups and tiles. If the search criteria includes a result, the recipes will also have the same result with a stack size greater than or equal to the search criteria. Finally, if needWater, needLava, or needHoney are set to true, the found recipes will also have them set to true.
void SetResult (int itemID, int stack=1)
Sets the search criteria's result to the given item type and stack size.
Public Attributes
bool needHoney
Adds the requirement of being nearby honey to the search criteria. Defaults to false.
bool needLava
Adds the requirement of being nearby lava to the search criteria. Defaults to false.
bool needWater
Adds the requirement of being nearby water to the search criteria. Defaults to false.
Static Private Member Functions
static List< int > GetAcceptedGroups (Recipe recipe)
Private Attributes
List< int > groups = new List<int>()
List< Item > items = new List<Item>()
Item result = new Item()
List< int > tiles = new List<int>()
Detailed Description
This class will search through all existing recipes for you based on criteria that you give it. It's useful for finding a particular vanilla recipe that you wish to remove or edit. Use this by creating new instances with the empty constructor for each search you perform.
Definition at line 10 of file RecipeFinder.cs.
Constructor & Destructor Documentation
RecipeFinder()
Terraria.ModLoader.RecipeFinder.RecipeFinder ()
Definition at line 29 of file RecipeFinder.cs.
{
        }
Member Function Documentation
AddIngredient()
void Terraria.ModLoader.RecipeFinder.AddIngredient (int itemID, int stack = 1)
Adds an ingredient with the given item type and stack size to the search criteria.
Parameters
itemID The item ID of the ingredient to add.
stack The stack of the ingredient to add.
Definition at line 37 of file RecipeFinder.cs.
{
            if (itemID <= 0 || itemID >= ItemLoader.ItemCount) {
                throw new RecipeException("No item has ID " + itemID);
            }
            Item item = new Item();
            item.SetDefaults(itemID, false);
            item.stack = stack;
            items.Add(item);
        }
References Terraria.ModLoader.Item, Terraria.ModLoader.ItemLoader.ItemCount, and Terraria.ModLoader.RecipeFinder.items.
Referenced by Terraria.ModLoader.RecipeFinder.AddRecipeGroup().
AddRecipeGroup() [1/2]
void Terraria.ModLoader.RecipeFinder.AddRecipeGroup (int recipeGroupID, int stack = 1)
Adds a recipe group ingredient with the given RecipeGroupID and stack size to the search criteria.
Parameters
name The RecipeGroupID of the recipegroup to accept.
stack The stack of the recipegroup to accept.
Definition at line 67 of file RecipeFinder.cs.
        {
            if (!RecipeGroup.recipeGroupIDs.ContainsValue(recipeGroupID)) {
                throw new RecipeException("No recipe group has the RecipeGroupID " + recipeGroupID);
            }
            RecipeGroup rec = RecipeGroup.recipeGroups[recipeGroupID];
            AddIngredient(rec.ValidItems[rec.IconicItemIndex], stack);
            groups.Add(recipeGroupID);
        }
References Terraria.ModLoader.RecipeFinder.AddIngredient(), and Terraria.ModLoader.RecipeFinder.groups.
AddRecipeGroup() [2/2]
void Terraria.ModLoader.RecipeFinder.AddRecipeGroup (string name, int stack = 1)
Adds a recipe group ingredient with the given RecipeGroup name and stack size to the search criteria.
Parameters
name The name of the recipegroup to accept.
stack The stack of the recipegroup to accept.
Definition at line 52 of file RecipeFinder.cs.
{
            if (!RecipeGroup.recipeGroupIDs.ContainsKey(name)) {
                throw new RecipeException("No recipe group is named " + name);
            }
            int id = RecipeGroup.recipeGroupIDs[name];
            RecipeGroup rec = RecipeGroup.recipeGroups[id];
            AddIngredient(rec.ValidItems[rec.IconicItemIndex], stack);
            groups.Add(id);
        }
References Terraria.ModLoader.RecipeFinder.AddIngredient(), and Terraria.ModLoader.RecipeFinder.groups.
AddTile()
void Terraria.ModLoader.RecipeFinder.AddTile (int tileID)
Adds a required crafting station with the given tile type to the search criteria.
Parameters
tileID The tile ID of the tile to add.
Definition at line 94 of file RecipeFinder.cs.
{
            if (tileID < 0 || tileID >= TileLoader.TileCount) {
                throw new RecipeException("No tile has ID " + tileID);
            }
            tiles.Add(tileID);
        }
References Terraria.ModLoader.TileLoader.TileCount, and Terraria.ModLoader.RecipeFinder.tiles.
FindExactRecipe()
Recipe Terraria.ModLoader.RecipeFinder.FindExactRecipe ()
Searches for a recipe that matches the search criteria exactly, then returns it. That means the recipe will have exactly the same ingredients, tiles, liquid requirements, recipe groups, and result; even the stack sizes will match. If no recipe with an exact match is found, this will return null.
Returns
The recipe found matching the finder's criteria.
Definition at line 105 of file RecipeFinder.cs.
{
            for (int k = 0; k < Recipe.numRecipes; k++) {
                Recipe recipe = Main.recipe[k];
                bool matches = true;
                List<Item> checkItems = new List<Item>(items);
                for (int i = 0; i < Recipe.maxRequirements; i++) {
                    Item item = recipe.requiredItem[i];
                    if (item.type == 0) {
                        break;
                    }
                    bool itemMatched = false;
                    for (int j = 0; j < checkItems.Count; j++) {
                        if (item.type == checkItems[j].type && item.stack == checkItems[j].stack) {
                            itemMatched = true;
                            checkItems.RemoveAt(j);
                            break;
                        }
                    }
                    if (!itemMatched) {
                        matches = false;
                        break;
                    }
                }
                if (checkItems.Count > 0) {
                    matches = false;
                }
                List<int> checkGroups = new List<int>(groups);
                List<int> acceptedGroups = GetAcceptedGroups(recipe);
                for (int i = 0; i < acceptedGroups.Count; i++) {
                    int group = acceptedGroups[i];
                    bool groupMatched = false;
                    for (int j = 0; j < checkGroups.Count; j++) {
                        if (group == checkGroups[j]) {
                            groupMatched = true;
                            checkGroups.RemoveAt(j);
                            break;
                        }
                    }
                    if (!groupMatched) {
                        matches = false;
                        break;
                    }
                }
                if (checkGroups.Count > 0) {
                    matches = false;
                }
                if (result.type != recipe.createItem.type || result.stack != recipe.createItem.stack) {
                    matches = false;
                }
                List<int> checkTiles = new List<int>(tiles);
                for (int i = 0; i < Recipe.maxRequirements; i++) {
                    int tile = recipe.requiredTile[i];
                    if (tile == -1) {
                        break;
                    }
                    bool tileMatched = false;
                    for (int j = 0; j < checkTiles.Count; j++) {
                        if (tile == checkTiles[j]) {
                            tileMatched = true;
                            checkTiles.RemoveAt(j);
                            break;
                        }
                    }
                    if (!tileMatched) {
                        matches = false;
                        break;
                    }
                }
                if (checkTiles.Count > 0) {
                    matches = false;
                }
                if (needWater != recipe.needWater) {
                    matches = false;
                }
                else if (needLava != recipe.needLava) {
                    matches = false;
                }
                else if (needHoney != recipe.needHoney) {
                    matches = false;
                }
                if (matches) {
                    return recipe;
                }
            }
            return null;
        }
References Terraria.ModLoader.RecipeFinder.GetAcceptedGroups(), Terraria.ModLoader.RecipeFinder.groups, Terraria.ModLoader.Item, Terraria.ModLoader.RecipeFinder.items, Terraria.ModLoader.RecipeFinder.needHoney, Terraria.ModLoader.RecipeFinder.needLava, Terraria.ModLoader.RecipeFinder.needWater, Terraria.ModLoader.RecipeFinder.result, and Terraria.ModLoader.RecipeFinder.tiles.
GetAcceptedGroups()
static List< int > Terraria.ModLoader.RecipeFinder.GetAcceptedGroups (Recipe recipe) static private
Definition at line 271 of file RecipeFinder.cs.
{
            List<int> acceptedGroups = new List<int>(recipe.acceptedGroups);
            if (recipe.anyWood) {
                acceptedGroups.Add(RecipeGroupID.Wood);
            }
            if (recipe.anyIronBar) {
                acceptedGroups.Add(RecipeGroupID.IronBar);
            }
            if (recipe.anySand) {
                acceptedGroups.Add(RecipeGroupID.Sand);
            }
            if (recipe.anyPressurePlate) {
                acceptedGroups.Add(RecipeGroupID.PressurePlate);
            }
            if (recipe.anyFragment) {
                acceptedGroups.Add(RecipeGroupID.Fragment);
            }
            return acceptedGroups;
        }
Referenced by Terraria.ModLoader.RecipeFinder.FindExactRecipe(), and Terraria.ModLoader.RecipeFinder.SearchRecipes().
SearchRecipes()
List< Recipe > Terraria.ModLoader.RecipeFinder.SearchRecipes ()
Searches for all recipes that include the search criteria, then returns them in a list. In terms of ingredients, it will search for recipes that include all the search criteria ingredients, with stack sizes greater than or equal to the search criteria. It will also make sure the recipes include all search criteria recipe groups and tiles. If the search criteria includes a result, the recipes will also have the same result with a stack size greater than or equal to the search criteria. Finally, if needWater, needLava, or needHoney are set to true, the found recipes will also have them set to true.
Returns
A list containing found recipes matching the finder's criteria.
Definition at line 196 of file RecipeFinder.cs.
{
            List<Recipe> recipes = new List<Recipe>();
            for (int k = 0; k < Recipe.numRecipes; k++) {
                Recipe recipe = Main.recipe[k];
                bool matches = true;
                List<Item> checkItems = new List<Item>(items);
                for (int i = 0; i < Recipe.maxRequirements; i++) {
                    Item item = recipe.requiredItem[i];
                    if (item.type == 0) {
                        break;
                    }
                    for (int j = 0; j < checkItems.Count; j++) {
                        if (item.type == checkItems[j].type && item.stack >= checkItems[j].stack) {
                            checkItems.RemoveAt(j);
                            break;
                        }
                    }
                }
                if (checkItems.Count > 0) {
                    matches = false;
                }
                List<int> checkGroups = new List<int>(groups);
                List<int> acceptedGroups = GetAcceptedGroups(recipe);
                for (int i = 0; i < acceptedGroups.Count; i++) {
                    int group = acceptedGroups[i];
                    for (int j = 0; j < checkGroups.Count; j++) {
                        if (group == checkGroups[j]) {
                            checkGroups.RemoveAt(j);
                            break;
                        }
                    }
                }
                if (checkGroups.Count > 0) {
                    matches = false;
                }
                if (result.type != 0) {
                    if (result.type != recipe.createItem.type) {
                        matches = false;
                    }
                    else if (result.stack > recipe.createItem.stack) {
                        matches = false;
                    }
                }
                List<int> checkTiles = new List<int>(tiles);
                for (int i = 0; i < Recipe.maxRequirements; i++) {
                    int tile = recipe.requiredTile[i];
                    if (tile == -1) {
                        break;
                    }
                    for (int j = 0; j < checkTiles.Count; j++) {
                        if (tile == checkTiles[j]) {
                            checkTiles.RemoveAt(j);
                            break;
                        }
                    }
                }
                if (checkTiles.Count > 0) {
                    matches = false;
                }
                if (needWater && !recipe.needWater) {
                    matches = false;
                }
                else if (needLava && !recipe.needLava) {
                    matches = false;
                }
                else if (needHoney && !recipe.needHoney) {
                    matches = false;
                }
                if (matches) {
                    recipes.Add(recipe);
                }
            }
            return recipes;
        }
References Terraria.ModLoader.RecipeFinder.GetAcceptedGroups(), Terraria.ModLoader.RecipeFinder.groups, Terraria.ModLoader.Item, Terraria.ModLoader.RecipeFinder.items, Terraria.ModLoader.RecipeFinder.needHoney, Terraria.ModLoader.RecipeFinder.needLava, Terraria.ModLoader.RecipeFinder.needWater, Terraria.ModLoader.RecipeFinder.result, and Terraria.ModLoader.RecipeFinder.tiles.
SetResult()
void Terraria.ModLoader.RecipeFinder.SetResult (int itemID, int stack = 1)
Sets the search criteria's result to the given item type and stack size.
Parameters
itemID The item ID of the item to set as result.
stack The stack of the item to set as result.
Definition at line 82 of file RecipeFinder.cs.
{
            if (itemID <= 0 || itemID >= ItemLoader.ItemCount) {
                throw new RecipeException("No item has ID " + itemID);
            }
            result.SetDefaults(itemID, false);
            result.stack = stack;
        }
References Terraria.ModLoader.ItemLoader.ItemCount, and Terraria.ModLoader.RecipeFinder.result.
Member Data Documentation
groups
List<int> Terraria.ModLoader.RecipeFinder.groups = new List<int>() private
Definition at line 13 of file RecipeFinder.cs.
Referenced by Terraria.ModLoader.RecipeFinder.AddRecipeGroup(), Terraria.ModLoader.RecipeFinder.FindExactRecipe(), and Terraria.ModLoader.RecipeFinder.SearchRecipes().
items
List<Item> Terraria.ModLoader.RecipeFinder.items = new List<Item>() private
Definition at line 12 of file RecipeFinder.cs.
Referenced by Terraria.ModLoader.RecipeFinder.AddIngredient(), Terraria.ModLoader.RecipeFinder.FindExactRecipe(), and Terraria.ModLoader.RecipeFinder.SearchRecipes().
needHoney
bool Terraria.ModLoader.RecipeFinder.needHoney
Adds the requirement of being nearby honey to the search criteria. Defaults to false.
Definition at line 27 of file RecipeFinder.cs.
Referenced by Terraria.ModLoader.RecipeFinder.FindExactRecipe(), and Terraria.ModLoader.RecipeFinder.SearchRecipes().
needLava
bool Terraria.ModLoader.RecipeFinder.needLava
Adds the requirement of being nearby lava to the search criteria. Defaults to false.
Definition at line 23 of file RecipeFinder.cs.
Referenced by Terraria.ModLoader.RecipeFinder.FindExactRecipe(), and Terraria.ModLoader.RecipeFinder.SearchRecipes().
needWater
bool Terraria.ModLoader.RecipeFinder.needWater
Adds the requirement of being nearby water to the search criteria. Defaults to false.
Definition at line 19 of file RecipeFinder.cs.
Referenced by Terraria.ModLoader.RecipeFinder.FindExactRecipe(), and Terraria.ModLoader.RecipeFinder.SearchRecipes().
result
Item Terraria.ModLoader.RecipeFinder.result = new Item() private
Definition at line 14 of file RecipeFinder.cs.
Referenced by Terraria.ModLoader.RecipeFinder.FindExactRecipe(), Terraria.ModLoader.RecipeFinder.SearchRecipes(), and Terraria.ModLoader.RecipeFinder.SetResult().
tiles
List<int> Terraria.ModLoader.RecipeFinder.tiles = new List<int>() private
Definition at line 15 of file RecipeFinder.cs.
Referenced by Terraria.ModLoader.RecipeFinder.AddTile(), Terraria.ModLoader.RecipeFinder.FindExactRecipe(), and Terraria.ModLoader.RecipeFinder.SearchRecipes().