tModLoader: Terraria.ModLoader.Logging Class Reference
Terraria.ModLoader.Logging Class Reference
Static Public Member Functions
static void IgnoreExceptionContents (string source)
static void IgnoreExceptionSource (string source)
static void PrettifyStackTraceSources (StackFrame[] frames)
Static Public Attributes
static readonly string LogArchiveDir = Path.Combine(LogDir, "Old")
static readonly string LogDir = Path.Combine(Program.SavePath, "Logs")
Properties
static string LogPath [get, private set]
Static Private Member Functions
static void AddChatMessage (string msg, Color color)
static bool CanOpen (string fileName)
static void ConfigureAppenders ()
static void EnablePortablePDBTraces ()
static void FirstChanceExceptionHandler (object sender, FirstChanceExceptionEventArgs args)
static string GetNewLogFile (string baseName)
static void LogFirstChanceExceptions ()
Static Private Attributes
static ThreadLocal< bool > handlerActive = new ThreadLocal<bool>(() => false)
static List< string > ignoreContents
static List< string > ignoreMessages
static HashSet< string > ignoreSources
static List< string > ignoreThrowingMethods
static List< string > initWarnings = new List<string>()
static HashSet< string > pastExceptions = new HashSet<string>()
static Exception previousException
static Regex statusRegex = new Regex(@"(.+?)[: \d]*%$")
static readonly Assembly TerrariaAssembly = Assembly.GetExecutingAssembly()
Detailed Description
Definition at line 23 of file Logging.cs.
Member Function Documentation
AddChatMessage()
static void Terraria.ModLoader.Logging.AddChatMessage (string msg, Color color) static private
Definition at line 256 of file Logging.cs.
{
            if (Main.gameMenu)
                return;
            float soundVolume = Main.soundVolume;
            Main.soundVolume = 0f;
            Main.NewText(msg, color);
            Main.soundVolume = soundVolume;
        }
Referenced by Terraria.ModLoader.Logging.FirstChanceExceptionHandler().
CanOpen()
static bool Terraria.ModLoader.Logging.CanOpen (string fileName) static private
Definition at line 128 of file Logging.cs.
{
            try {
                using (new FileStream(fileName, FileMode.Append)) ;
                return true;
            }
            catch (IOException) {
                return false;
            }
        }
Referenced by Terraria.ModLoader.Logging.GetNewLogFile().
ConfigureAppenders()
static void Terraria.ModLoader.Logging.ConfigureAppenders () static private
Definition at line 68 of file Logging.cs.
{
            var layout = new PatternLayout {
                ConversionPattern = "[%d{HH:mm:ss}] [%t/%level] [%logger]: %m%n"
            };
            layout.ActivateOptions();
            var appenders = new List<IAppender>();
#if CLIENT
            appenders.Add(new ConsoleAppender {
                Name = "ConsoleAppender",
                Layout = layout
            });
#endif
            appenders.Add(new DebugAppender {
                Name = "DebugAppender",
                Layout = layout
            });
            var fileAppender = new FileAppender {
                Name = "FileAppender",
                File = LogPath = Path.Combine(LogDir, GetNewLogFile(side)),
                AppendToFile = false,
                Encoding = Encoding.UTF8,
                Layout = layout
            };
            fileAppender.ActivateOptions();
            appenders.Add(fileAppender);
            BasicConfigurator.Configure(appenders.ToArray());
        }
References Terraria.ModLoader.Logging.GetNewLogFile(), Terraria.ModLoader.Logging.LogDir, and Terraria.ModLoader.Logging.LogPath.
EnablePortablePDBTraces()
static void Terraria.ModLoader.Logging.EnablePortablePDBTraces () static private
Definition at line 320 of file Logging.cs.
{
            if (FrameworkVersion.Framework == Framework.NetFramework && FrameworkVersion.Version >= new Version(4, 7, 2))
                Type.GetType("System.AppContextSwitches").GetField("_ignorePortablePDBsInStackTraces", BindingFlags.Static | BindingFlags.NonPublic).SetValue(null, -1);
        }
References Terraria.ModLoader.FrameworkVersion.Framework, and Terraria.ModLoader.FrameworkVersion.Version.
FirstChanceExceptionHandler()
static void Terraria.ModLoader.Logging.FirstChanceExceptionHandler (object sender, FirstChanceExceptionEventArgs args) static private
Definition at line 188 of file Logging.cs.
{
            if (handlerActive.Value)
                return;
            bool oom = args.Exception is OutOfMemoryException;
            //In case of OOM, unload the Main.tile array and do immediate garbage collection.
            //If we don't do this, there will be a big chance that this method will fail to even quit the game, due to another OOM exception being thrown.
            if (oom) {
                Main.tile = null;
                GC.Collect();
            }
            try {
                handlerActive.Value = true;
                if (!oom) {
                    if (args.Exception == previousException ||
                        args.Exception is ThreadAbortException ||
                        ignoreSources.Contains(args.Exception.Source) ||
                        ignoreMessages.Any(str => args.Exception.Message?.Contains(str) ?? false) ||
                        ignoreThrowingMethods.Any(str => args.Exception.StackTrace?.Contains(str) ?? false))
                        return;
                }
                var stackTrace = new StackTrace(true);
                PrettifyStackTraceSources(stackTrace.GetFrames());
                var traceString = stackTrace.ToString();
                if (!oom && ignoreContents.Any(traceString.Contains))
                    return;
                traceString = traceString.Substring(traceString.IndexOf('\n'));
                var exString = args.Exception.GetType() + ": " + args.Exception.Message + traceString;
                lock (pastExceptions) {
                    if (!pastExceptions.Add(exString))
                        return;
                }
                previousException = args.Exception;
                var msg = args.Exception.Message + " " + Language.GetTextValue("tModLoader.RuntimeErrorSeeLogsForFullTrace", Path.GetFileName(LogPath));
    #if CLIENT
                if (ModCompile.activelyModding)
                    AddChatMessage(msg, Color.OrangeRed);
    #else
                Console.ForegroundColor = ConsoleColor.DarkMagenta;
                Console.WriteLine(msg);
                Console.ResetColor();
    #endif
                tML.Warn(Language.GetTextValue("tModLoader.RuntimeErrorSilentlyCaughtException") + '\n' + exString);
                if (oom) {
                    string error = Language.GetTextValue("tModLoader.OutOfMemory");
                    Logging.tML.Fatal(error);
                    Interface.MessageBoxShow(error);
                    Environment.Exit(1);
                }
            }
            catch (Exception e) {
                tML.Warn("FirstChanceExceptionHandler exception", e);
            }
            finally {
                handlerActive.Value = false;
            }
        }
References Terraria.ModLoader.Logging.AddChatMessage(), Terraria.ModLoader.Console, Terraria.ModLoader.Environment, Terraria.ModLoader.Logging.handlerActive, Terraria.ModLoader.Logging.ignoreContents, Terraria.ModLoader.Logging.ignoreMessages, Terraria.ModLoader.Logging.ignoreSources, Terraria.ModLoader.Logging.ignoreThrowingMethods, Terraria.ModLoader.Logging.LogPath, Terraria.ModLoader.Logging.pastExceptions, Terraria.ModLoader.Logging.PrettifyStackTraceSources(), and Terraria.ModLoader.Logging.previousException.
Referenced by Terraria.ModLoader.Logging.LogFirstChanceExceptions().
GetNewLogFile()
static string Terraria.ModLoader.Logging.GetNewLogFile (string baseName) static private
Definition at line 99 of file Logging.cs.
{
            var pattern = new Regex($"{baseName}(\\d*)\\.log$");
            var existingLogs = Directory.GetFiles(LogDir).Where(s => pattern.IsMatch(Path.GetFileName(s))).ToList();
            if (!existingLogs.All(CanOpen)) {
                int n = existingLogs.Select(s => {
                    var tok = pattern.Match(Path.GetFileName(s)).Groups[1].Value;
                    return tok.Length == 0 ? 1 : int.Parse(tok);
                }).Max();
                return $"{baseName}{n + 1}.log";
            }
            foreach (var existingLog in existingLogs.OrderBy(File.GetCreationTime)) {
                var oldExt = ".old";
                int n = 0;
                while (File.Exists(existingLog + oldExt))
                    oldExt = $".old{++n}";
                try {
                    File.Move(existingLog, existingLog + oldExt);
                }
                catch (IOException e) {
                    initWarnings.Add($"Move failed during log initialization: {existingLog} -> {Path.GetFileName(existingLog)}{oldExt}\n{e}");
                }
            }
            return $"{baseName}.log";
        }
References Terraria.ModLoader.Logging.CanOpen(), Terraria.ModLoader.Logging.initWarnings, and Terraria.ModLoader.Logging.LogDir.
Referenced by Terraria.ModLoader.Logging.ConfigureAppenders().
IgnoreExceptionContents()
static void Terraria.ModLoader.Logging.IgnoreExceptionContents (string source) static
Definition at line 181 of file Logging.cs.
{
            if (!ignoreContents.Contains(source))
                ignoreContents.Add(source);
        }
References Terraria.ModLoader.Logging.ignoreContents.
IgnoreExceptionSource()
static void Terraria.ModLoader.Logging.IgnoreExceptionSource (string source) static
LogFirstChanceExceptions()
static void Terraria.ModLoader.Logging.LogFirstChanceExceptions () static private
Definition at line 138 of file Logging.cs.
{
            if (FrameworkVersion.Framework == Framework.Mono)
                tML.Warn("First-chance exception reporting is not implemented on Mono");
            AppDomain.CurrentDomain.FirstChanceException += FirstChanceExceptionHandler;
        }
References Terraria.ModLoader.Logging.FirstChanceExceptionHandler(), and Terraria.ModLoader.FrameworkVersion.Framework.
PrettifyStackTraceSources()
static void Terraria.ModLoader.Logging.PrettifyStackTraceSources (StackFrame[] frames) static
Definition at line 294 of file Logging.cs.
{
            if (frames == null)
                return;
            foreach (var frame in frames) {
                string filename = frame.GetFileName();
                var assembly = frame.GetMethod()?.DeclaringType?.Assembly;
                if (filename == null || assembly == null)
                    continue;
                string trim;
                if (AssemblyManager.GetAssemblyOwner(assembly, out var modName))
                    trim = modName;
                else if (assembly == TerrariaAssembly)
                    trim = "tModLoader";
                else
                    continue;
                int idx = filename.LastIndexOf(trim, StringComparison.InvariantCultureIgnoreCase);
                if (idx > 0) {
                    filename = filename.Substring(idx);
                    f_fileName.SetValue(frame, filename);
                }
            }
        }
References Terraria.ModLoader.Logging.TerrariaAssembly.
Referenced by Terraria.ModLoader.Logging.FirstChanceExceptionHandler().
Member Data Documentation
handlerActive
ThreadLocal<bool> Terraria.ModLoader.Logging.handlerActive = new ThreadLocal<bool>(() => false) static private
Definition at line 186 of file Logging.cs.
Referenced by Terraria.ModLoader.Logging.FirstChanceExceptionHandler().
ignoreContents
List<string> Terraria.ModLoader.Logging.ignoreContents static private
Initial value:
= new List<string> {
            "System.Console.set_OutputEncoding",
            "Terraria.ModLoader.Core.ModCompile",
            "Delegate.CreateDelegateNoSecurityCheck",
            "MethodBase.GetMethodBody",
            "Terraria.Net.Sockets.TcpSocket.Terraria.Net.Sockets.ISocket.AsyncSend",
            "System.Diagnostics.Process.Kill",
            "Terraria.ModLoader.Core.AssemblyManager.CecilAssemblyResolver.Resolve",
            "Terraria.ModLoader.Engine.TMLContentManager.OpenStream"
        }
Definition at line 153 of file Logging.cs.
Referenced by Terraria.ModLoader.Logging.FirstChanceExceptionHandler(), and Terraria.ModLoader.Logging.IgnoreExceptionContents().
ignoreMessages
List<string> Terraria.ModLoader.Logging.ignoreMessages static private
Initial value:
= new List<string> {
            "A blocking operation was interrupted by a call to WSACancelBlockingCall",
            "The request was aborted: The request was canceled.",
            "Object name: 'System.Net.Sockets.Socket'.",
            "Object name: 'System.Net.Sockets.NetworkStream'",
            "This operation cannot be performed on a completed asynchronous result object.",
            "Object name: 'SslStream'.",
            "Unable to load DLL 'Microsoft.DiaSymReader.Native.x86.dll'"
        }
Definition at line 166 of file Logging.cs.
Referenced by Terraria.ModLoader.Logging.FirstChanceExceptionHandler().
ignoreSources
HashSet<string> Terraria.ModLoader.Logging.ignoreSources static private
Initial value:
= new HashSet<string> {
            "MP3Sharp"
        }
Definition at line 148 of file Logging.cs.
Referenced by Terraria.ModLoader.Logging.FirstChanceExceptionHandler().
ignoreThrowingMethods
List<string> Terraria.ModLoader.Logging.ignoreThrowingMethods static private
Initial value:
= new List<string> {
            "at Terraria.Lighting.doColors_Mode",
            "System.Threading.CancellationToken.Throw",
        }
Definition at line 176 of file Logging.cs.
Referenced by Terraria.ModLoader.Logging.FirstChanceExceptionHandler().
initWarnings
List<string> Terraria.ModLoader.Logging.initWarnings = new List<string>() static private
Definition at line 38 of file Logging.cs.
Referenced by Terraria.ModLoader.Logging.GetNewLogFile().
LogArchiveDir
readonly string Terraria.ModLoader.Logging.LogArchiveDir = Path.Combine(LogDir, "Old") static
Definition at line 26 of file Logging.cs.
LogDir
readonly string Terraria.ModLoader.Logging.LogDir = Path.Combine(Program.SavePath, "Logs") static
Definition at line 25 of file Logging.cs.
Referenced by Terraria.ModLoader.ErrorLogger.ClearLogs(), Terraria.ModLoader.Logging.ConfigureAppenders(), and Terraria.ModLoader.Logging.GetNewLogFile().
pastExceptions
HashSet<string> Terraria.ModLoader.Logging.pastExceptions = new HashSet<string>() static private
Definition at line 145 of file Logging.cs.
Referenced by Terraria.ModLoader.Logging.FirstChanceExceptionHandler().
previousException
Exception Terraria.ModLoader.Logging.previousException static private
Definition at line 187 of file Logging.cs.
Referenced by Terraria.ModLoader.Logging.FirstChanceExceptionHandler().
statusRegex
Regex Terraria.ModLoader.Logging.statusRegex = new Regex(@"(.+?)[: \d]*%$") static private
Definition at line 266 of file Logging.cs.
TerrariaAssembly
readonly Assembly Terraria.ModLoader.Logging.TerrariaAssembly = Assembly.GetExecutingAssembly() static private
Definition at line 292 of file Logging.cs.
Referenced by Terraria.ModLoader.Logging.PrettifyStackTraceSources().
Property Documentation
LogPath
string Terraria.ModLoader.Logging.LogPath static get private set
Definition at line 27 of file Logging.cs.
{ get; private set; }
Referenced by Terraria.ModLoader.Logging.ConfigureAppenders(), and Terraria.ModLoader.Logging.FirstChanceExceptionHandler().