tModLoader: Terraria.ModLoader.WaterStyleLoader Class Reference
Terraria.ModLoader.WaterStyleLoader Class Reference
This serves as the central class from which WaterStyle functions are supported and carried out.
Static Public Member Functions
static void ChooseWaterStyle (ref int style)
static void DrawWaterfall (WaterfallManager waterfallManager, SpriteBatch spriteBatch)
static void DrawWatersToScreen (bool bg)
static ModWaterStyle GetWaterStyle (int style)
Returns the ModWaterStyle with the given ID.
static void LightColorMultiplier (int style, ref float r, ref float g, ref float b)
static void UpdateLiquidAlphas ()
Static Public Attributes
const int vanillaWaterCount = Main.maxLiquidTypes
The maximum amount of liquids in vanilla.
Properties
static int WaterStyleCount [get]
The number of water styles that exist in the game, both vanilla and modded.
Static Private Attributes
static int nextWaterStyle = vanillaWaterCount
Detailed Description
This serves as the central class from which WaterStyle functions are supported and carried out.
Definition at line 12 of file WaterStyleLoader.cs.
Member Function Documentation
ChooseWaterStyle()
static void Terraria.ModLoader.WaterStyleLoader.ChooseWaterStyle (ref int style) static
Definition at line 53 of file WaterStyleLoader.cs.
{
            foreach (ModWaterStyle waterStyle in waterStyles) {
                if (waterStyle.ChooseWaterStyle()) {
                    style = waterStyle.Type;
                }
            }
            WorldHooks.ChooseWaterStyle(ref style);
        }
References Terraria.ModLoader.ModWaterStyle.ChooseWaterStyle(), Terraria.ModLoader.WorldHooks.ChooseWaterStyle(), and Terraria.ModLoader.ModWaterStyle.Type.
DrawWaterfall()
static void Terraria.ModLoader.WaterStyleLoader.DrawWaterfall (WaterfallManager waterfallManager, SpriteBatch spriteBatch) static
Definition at line 109 of file WaterStyleLoader.cs.
{
            foreach (ModWaterStyle waterStyle in waterStyles) {
                if (Main.liquidAlpha[waterStyle.Type] > 0f) {
                    waterfallManager.DrawWaterfall(spriteBatch, waterStyle.ChooseWaterfallStyle(),
                        Main.liquidAlpha[waterStyle.Type]);
                }
            }
        }
References Terraria.ModLoader.ModWaterStyle.ChooseWaterfallStyle(), and Terraria.ModLoader.ModWaterStyle.Type.
DrawWatersToScreen()
static void Terraria.ModLoader.WaterStyleLoader.DrawWatersToScreen (bool bg) static
Definition at line 91 of file WaterStyleLoader.cs.
{
            for (int k = vanillaWaterCount; k < nextWaterStyle; k++) {
                if (Main.liquidAlpha[k] > 0f) {
                    if (bg) {
                        if (Main.waterStyle < k) {
                            Main.instance.DrawWater(bg, k, Main.liquidAlpha[k]);
                        }
                        else {
                            Main.instance.DrawWater(bg, k, 1f);
                        }
                    }
                    else {
                        Main.instance.DrawWater(bg, k, Main.liquidAlpha[k]);
                    }
                }
            }
        }
References Terraria.ModLoader.WaterStyleLoader.nextWaterStyle, and Terraria.ModLoader.WaterStyleLoader.vanillaWaterCount.
GetWaterStyle()
static ModWaterStyle Terraria.ModLoader.WaterStyleLoader.GetWaterStyle (int style) static
Returns the ModWaterStyle with the given ID.
Definition at line 35 of file WaterStyleLoader.cs.
{
            if (style < vanillaWaterCount || style >= nextWaterStyle) {
                return null;
            }
            return waterStyles[style - vanillaWaterCount];
        }
References Terraria.ModLoader.WaterStyleLoader.nextWaterStyle, and Terraria.ModLoader.WaterStyleLoader.vanillaWaterCount.
Referenced by Terraria.ModLoader.WaterStyleLoader.LightColorMultiplier().
LightColorMultiplier()
static void Terraria.ModLoader.WaterStyleLoader.LightColorMultiplier (int style, ref float r, ref float g, ref float b) static
Definition at line 118 of file WaterStyleLoader.cs.
{
            ModWaterStyle waterStyle = GetWaterStyle(style);
            if (waterStyle != null) {
                waterStyle.LightColorMultiplier(ref r, ref g, ref b);
                r *= Lighting.negLight * Lighting.blueWave;
                g *= Lighting.negLight * Lighting.blueWave;
                b *= Lighting.negLight * Lighting.blueWave;
            }
        }
References Terraria.ModLoader.WaterStyleLoader.GetWaterStyle(), and Terraria.ModLoader.ModWaterStyle.LightColorMultiplier().
UpdateLiquidAlphas()
static void Terraria.ModLoader.WaterStyleLoader.UpdateLiquidAlphas () static
Definition at line 62 of file WaterStyleLoader.cs.
{
            if (Main.waterStyle >= vanillaWaterCount) {
                for (int k = 0; k < vanillaWaterCount; k++) {
                    if (k == 1 || k == 11) {
                        continue;
                    }
                    Main.liquidAlpha[k] -= 0.2f;
                    if (Main.liquidAlpha[k] < 0f) {
                        Main.liquidAlpha[k] = 0f;
                    }
                }
            }
            foreach (ModWaterStyle waterStyle in waterStyles) {
                int type = waterStyle.Type;
                if (Main.waterStyle == type) {
                    Main.liquidAlpha[type] += 0.2f;
                    if (Main.liquidAlpha[type] > 1f) {
                        Main.liquidAlpha[type] = 1f;
                    }
                }
                else {
                    Main.liquidAlpha[type] -= 0.2f;
                    if (Main.liquidAlpha[type] < 0f) {
                        Main.liquidAlpha[type] = 0f;
                    }
                }
            }
        }
References Terraria.ModLoader.ModWaterStyle.Type, and Terraria.ModLoader.WaterStyleLoader.vanillaWaterCount.
Member Data Documentation
nextWaterStyle
int Terraria.ModLoader.WaterStyleLoader.nextWaterStyle = vanillaWaterCount static private
Definition at line 18 of file WaterStyleLoader.cs.
Referenced by Terraria.ModLoader.WaterStyleLoader.DrawWatersToScreen(), and Terraria.ModLoader.WaterStyleLoader.GetWaterStyle().
vanillaWaterCount
const int Terraria.ModLoader.WaterStyleLoader.vanillaWaterCount = Main.maxLiquidTypes static
The maximum amount of liquids in vanilla.
Definition at line 17 of file WaterStyleLoader.cs.
Referenced by Terraria.ModLoader.WaterStyleLoader.DrawWatersToScreen(), Terraria.ModLoader.WaterStyleLoader.GetWaterStyle(), and Terraria.ModLoader.WaterStyleLoader.UpdateLiquidAlphas().
Property Documentation
WaterStyleCount
int Terraria.ModLoader.WaterStyleLoader.WaterStyleCount static get
The number of water styles that exist in the game, both vanilla and modded.
Definition at line 24 of file WaterStyleLoader.cs.