tModLoader: Terraria.ModLoader.IO.UploadFile Class Reference
Terraria.ModLoader.IO.UploadFile Class Reference
Public Member Functions
UploadFile ()
Static Public Member Functions
static byte[] GetUploadFilesRequestData (IEnumerable< UploadFile > files, NameValueCollection values, string boundary)
static byte[] UploadFiles (string address, IEnumerable< UploadFile > files, NameValueCollection values)
Properties
byte[] Content [get, set]
string ContentType [get, set]
string Filename [get, set]
string Name [get, set]
Static Private Member Functions
static void WriteFiles (Stream requestStream, IEnumerable< UploadFile > files, string boundary)
static void WriteValues (Stream requestStream, NameValueCollection values, string boundary)
Detailed Description
Definition at line 11 of file UploadFile.cs.
Constructor & Destructor Documentation
UploadFile()
Terraria.ModLoader.IO.UploadFile.UploadFile ()
Definition at line 13 of file UploadFile.cs.
{
            ContentType = "application/octet-stream";
        }
References Terraria.ModLoader.IO.UploadFile.ContentType.
Member Function Documentation
GetUploadFilesRequestData()
static byte[] Terraria.ModLoader.IO.UploadFile.GetUploadFilesRequestData (IEnumerable< UploadFile > files, NameValueCollection values, string boundary) static
Definition at line 45 of file UploadFile.cs.
{
            boundary = "--" + boundary;
            using (var requestStream = new MemoryStream()) {
                WriteValues(requestStream, values, boundary);
                WriteFiles(requestStream, files, boundary);
                var boundaryBuffer = Encoding.ASCII.GetBytes(boundary + "--");
                requestStream.Write(boundaryBuffer, 0, boundaryBuffer.Length);
                return requestStream.ToArray();
            }
        }
References Terraria.ModLoader.IO.UploadFile.WriteFiles(), and Terraria.ModLoader.IO.UploadFile.WriteValues().
UploadFiles()
static byte[] Terraria.ModLoader.IO.UploadFile.UploadFiles (string address, IEnumerable< UploadFile > files, NameValueCollection values) static
Definition at line 25 of file UploadFile.cs.
{
            var request = WebRequest.Create(address);
            request.Method = "POST";
            var boundary = "---------------------------" + DateTime.Now.Ticks.ToString("x", NumberFormatInfo.InvariantInfo);
            request.ContentType = "multipart/form-data; boundary=" + boundary;
            boundary = "--" + boundary;
            using (var requestStream = request.GetRequestStream()) {
                WriteValues(requestStream, values, boundary);
                WriteFiles(requestStream, files, boundary);
                var boundaryBuffer = Encoding.ASCII.GetBytes(boundary + "--");
                requestStream.Write(boundaryBuffer, 0, boundaryBuffer.Length);
            }
            using (var response = request.GetResponse())
            using (var responseStream = response.GetResponseStream())
            using (var stream = new MemoryStream()) {
                responseStream.CopyTo(stream);
                return stream.ToArray();
            }
        }
References Terraria.ModLoader.IO.UploadFile.WriteFiles(), and Terraria.ModLoader.IO.UploadFile.WriteValues().
WriteFiles()
static void Terraria.ModLoader.IO.UploadFile.WriteFiles (Stream requestStream, IEnumerable< UploadFile > files, string boundary) static private
Definition at line 71 of file UploadFile.cs.
{
            if (files == null)
                return;
            // Write the files
            foreach (var file in files) {
                var buffer = Encoding.ASCII.GetBytes(boundary + Environment.NewLine);
                requestStream.Write(buffer, 0, buffer.Length);
                buffer = Encoding.UTF8.GetBytes(string.Format("Content-Disposition: form-data; name=\"{0}\"; filename=\"{1}\"{2}", file.Name, file.Filename, Environment.NewLine));
                requestStream.Write(buffer, 0, buffer.Length);
                buffer = Encoding.ASCII.GetBytes(string.Format("Content-Type: {0}{1}{1}", file.ContentType, Environment.NewLine));
                requestStream.Write(buffer, 0, buffer.Length);
                requestStream.Write(file.Content, 0, file.Content.Length);
                buffer = Encoding.ASCII.GetBytes(Environment.NewLine);
                requestStream.Write(buffer, 0, buffer.Length);
            }
        }
References Terraria.ModLoader.Environment.
Referenced by Terraria.ModLoader.IO.UploadFile.GetUploadFilesRequestData(), and Terraria.ModLoader.IO.UploadFile.UploadFiles().
WriteValues()
static void Terraria.ModLoader.IO.UploadFile.WriteValues (Stream requestStream, NameValueCollection values, string boundary) static private
Definition at line 56 of file UploadFile.cs.
{
            if (values == null)
                return;
            // Write the values
            foreach (string name in values.Keys) {
                var buffer = Encoding.ASCII.GetBytes(boundary + Environment.NewLine);
                requestStream.Write(buffer, 0, buffer.Length);
                buffer = Encoding.ASCII.GetBytes(string.Format("Content-Disposition: form-data; name=\"{0}\"{1}{1}", name, Environment.NewLine));
                requestStream.Write(buffer, 0, buffer.Length);
                buffer = Encoding.UTF8.GetBytes(values[name] + Environment.NewLine);
                requestStream.Write(buffer, 0, buffer.Length);
            }
        }
References Terraria.ModLoader.Environment.
Referenced by Terraria.ModLoader.IO.UploadFile.GetUploadFilesRequestData(), and Terraria.ModLoader.IO.UploadFile.UploadFiles().
Property Documentation
Content
byte [] Terraria.ModLoader.IO.UploadFile.Content get set
Definition at line 23 of file UploadFile.cs.
{ get; set; }
ContentType
string Terraria.ModLoader.IO.UploadFile.ContentType get set
Definition at line 21 of file UploadFile.cs.
{ get; set; }
Referenced by Terraria.ModLoader.IO.UploadFile.UploadFile().
Filename
string Terraria.ModLoader.IO.UploadFile.Filename get set
Definition at line 19 of file UploadFile.cs.
{ get; set; }
Name
string Terraria.ModLoader.IO.UploadFile.Name get set
Definition at line 17 of file UploadFile.cs.
{ get; set; }