tModLoader: Terraria.ModLoader.IO.TagIO Class Reference
Terraria.ModLoader.IO.TagIO Class Reference
Classes
class ClassPayloadHandler
class PayloadHandler
Static Public Member Functions
static T Clone< T > (T o)
static object Deserialize (Type type, object tag)
static T Deserialize< T > (object tag)
static TagCompound FromFile (string path, bool compressed=true)
static TagCompound FromStream (Stream stream, bool compressed=true)
static TagCompound Read (BinaryReader reader)
static object ReadTag (BinaryReader r, out string name)
static object Serialize (object value)
static void ToFile (TagCompound root, string path, bool compress=true)
static void ToStream (TagCompound root, Stream stream, bool compress=true)
static void Write (TagCompound root, BinaryWriter writer)
static void WriteTag (string name, object tag, BinaryWriter w)
Static Private Member Functions
static PayloadHandler GetHandler (int id)
static int GetPayloadId (Type t)
Static Private Attributes
static readonly PayloadHandler[] PayloadHandlers
static readonly Dictionary< Type, int > PayloadIDs
static PayloadHandler< string > StringHandler = (PayloadHandler<string>)PayloadHandlers[8]
Detailed Description
Definition at line 11 of file TagIO.cs.
Member Function Documentation
Clone< T >()
static T Terraria.ModLoader.IO.TagIO.Clone< T > (T o) static
Deserialize()
static object Terraria.ModLoader.IO.TagIO.Deserialize (Type type, object tag) static
Definition at line 213 of file TagIO.cs.
{
            if (type.IsInstanceOfType(tag))
                return tag;
            TagSerializer serializer;
            if (TagSerializer.TryGetSerializer(type, out serializer)) {
                if (tag == null)
                    tag = Deserialize(serializer.TagType, null);
                return serializer.Deserialize(tag);
            }
            //normal nbt type with missing value
            if (tag == null) {
                if (type.GetGenericArguments().Length == 0)
                    return GetHandler(GetPayloadId(type)).Default();
                if (type.GetGenericTypeDefinition() == typeof(Nullable<>))
                    return null;
            }
            //list conversion required
            if ((tag == null || tag is IList) &&
                type.GetGenericArguments().Length == 1) {
                var elemType = type.GetGenericArguments()[0];
                var newListType = typeof(List<>).MakeGenericType(elemType);
                if (type.IsAssignableFrom(newListType)) {//if the desired type is a superclass of List<elemType>
                    if (tag == null)
                        return newListType.GetConstructor(new Type[0]).Invoke(new object[0]);
                    if (TagSerializer.TryGetSerializer(elemType, out serializer))
                        return serializer.DeserializeList((IList)tag);
                    //create a strongly typed nested list
                    var oldList = (IList)tag;
                    var newList = (IList)newListType.GetConstructor(new[] { typeof(int) }).Invoke(new object[] { oldList.Count });
                    foreach (var elem in oldList)
                        newList.Add(Deserialize(elemType, elem));
                    return newList;
                }
            }
            if (tag == null)//unable to create an empty list subclassing the desired type
                throw new IOException($"Invalid NBT payload type '{type}'");
            throw new InvalidCastException($"Unable to cast object of type '{tag.GetType()}' to type '{type}'");
        }
References Terraria.ModLoader.IO.TagSerializer< T, S >.Deserialize(), Terraria.ModLoader.IO.TagSerializer< T, S >.TagType, and Terraria.ModLoader.IO.TagSerializer< T, S >.TryGetSerializer().
Referenced by Terraria.ModLoader.IO.TagCompound.Get< T >().
Deserialize< T >()
static T Terraria.ModLoader.IO.TagIO.Deserialize< T > (object tag) static
Definition at line 208 of file TagIO.cs.
{
            if (tag is T) return (T)tag;
            return (T)Deserialize(typeof(T), tag);
        }
FromFile()
static TagCompound Terraria.ModLoader.IO.TagIO.FromFile (string path, bool compressed = true) static
Definition at line 282 of file TagIO.cs.
{
            try {
                using (Stream fs = new FileStream(path, FileMode.Open, FileAccess.Read))
                    return FromStream(fs, compressed);
            }
            catch (IOException e) {
                throw new IOException("Failed to read NBT file: " + path, e);
            }
        }
FromStream()
static TagCompound Terraria.ModLoader.IO.TagIO.FromStream (Stream stream, bool compressed = true) static
Definition at line 292 of file TagIO.cs.
{
            if (compressed) stream = new GZipStream(stream, CompressionMode.Decompress);
            return Read(new BigEndianReader(stream));
        }
Referenced by Terraria.ModLoader.IO.ItemIO.FromBase64().
GetHandler()
static PayloadHandler Terraria.ModLoader.IO.TagIO.GetHandler (int id) static private
Definition at line 164 of file TagIO.cs.
{
            if (id < 1 || id >= PayloadHandlers.Length)
                throw new IOException("Invalid NBT payload id: " + id);
            return PayloadHandlers[id];
        }
GetPayloadId()
static int Terraria.ModLoader.IO.TagIO.GetPayloadId (Type t) static private
Definition at line 171 of file TagIO.cs.
{
            int id;
            if (PayloadIDs.TryGetValue(t, out id))
                return id;
            if (typeof(IList).IsAssignableFrom(t))
                return 9;
            throw new IOException($"Invalid NBT payload type '{t}'");
        }
Read()
static TagCompound Terraria.ModLoader.IO.TagIO.Read (BinaryReader reader) static
Definition at line 297 of file TagIO.cs.
{
            string name;
            var tag = ReadTag(reader, out name);
            if (!(tag is TagCompound))
                throw new IOException("Root tag not a TagCompound");
            return (TagCompound)tag;
        }
ReadTag()
static object Terraria.ModLoader.IO.TagIO.ReadTag (BinaryReader r, out string name) static
Definition at line 264 of file TagIO.cs.
{
            int id = r.ReadByte();
            if (id == 0) {
                name = null;
                return null;
            }
            name = StringHandler.reader(r);
            return PayloadHandlers[id].Read(r);
        }
Serialize()
static object Terraria.ModLoader.IO.TagIO.Serialize (object value) static
Definition at line 182 of file TagIO.cs.
{
            var type = value.GetType();
            TagSerializer serializer;
            if (TagSerializer.TryGetSerializer(type, out serializer))
                return serializer.Serialize(value);
            //does a base level typecheck with throw
            if (GetPayloadId(type) != 9)
                return value;
            var elemType = type.GetGenericArguments()[0];
            if (TagSerializer.TryGetSerializer(elemType, out serializer))
                return serializer.SerializeList((IList)value);
            if (GetPayloadId(elemType) != 9)
                return value;//already a valid NBT list type
            //list of lists conversion
            var list = value as IList<IList> ?? ((IList)value).Cast<IList>().ToList();
            for (int i = 0; i < list.Count; i++)
                list[i] = (IList)Serialize(list[i]);
            return list;
        }
References Terraria.ModLoader.IO.TagSerializer< T, S >.Serialize(), Terraria.ModLoader.IO.TagSerializer< T, S >.SerializeList(), and Terraria.ModLoader.IO.TagSerializer< T, S >.TryGetSerializer().
Referenced by Terraria.ModLoader.IO.TagCompound.Set().
ToFile()
static void Terraria.ModLoader.IO.TagIO.ToFile (TagCompound root, string path, bool compress = true) static
Definition at line 306 of file TagIO.cs.
{
            try {
                using (Stream fs = new FileStream(path, FileMode.OpenOrCreate, FileAccess.Write))
                    ToStream(root, fs, compress);
            }
            catch (IOException e) {
                throw new IOException("Failed to read NBT file: " + path, e);
            }
        }
ToStream()
static void Terraria.ModLoader.IO.TagIO.ToStream (TagCompound root, Stream stream, bool compress = true) static
Definition at line 316 of file TagIO.cs.
{
            if (compress) stream = new GZipStream(stream, CompressionMode.Compress, true);
            Write(root, new BigEndianWriter(stream));
            if (compress) stream.Close();
        }
Referenced by Terraria.ModLoader.IO.ItemIO.ToBase64().
Write()
static void Terraria.ModLoader.IO.TagIO.Write (TagCompound root, BinaryWriter writer) static
WriteTag()
static void Terraria.ModLoader.IO.TagIO.WriteTag (string name, object tag, BinaryWriter w) static
Definition at line 275 of file TagIO.cs.
{
            int id = GetPayloadId(tag.GetType());
            w.Write((byte)id);
            StringHandler.writer(w, name);
            PayloadHandlers[id].Write(w, tag);
        }
Member Data Documentation
PayloadHandlers
readonly PayloadHandler [] Terraria.ModLoader.IO.TagIO.PayloadHandlers static private
Definition at line 77 of file TagIO.cs.
PayloadIDs
readonly Dictionary<Type, int> Terraria.ModLoader.IO.TagIO.PayloadIDs static private
Initial value:
=
            Enumerable.Range(1, PayloadHandlers.Length - 1).ToDictionary(i => PayloadHandlers[i].PayloadType)
Definition at line 159 of file TagIO.cs.
StringHandler
PayloadHandler<string> Terraria.ModLoader.IO.TagIO.StringHandler = (PayloadHandler<string>)PayloadHandlers[8] static private
Definition at line 162 of file TagIO.cs.