tModLoader: Terraria.ModLoader.RecipeHooks Class Reference
Terraria.ModLoader.RecipeHooks Class Reference
This is where all ModRecipe and GlobalRecipe hooks are gathered and called.
Static Public Member Functions
static void OnCraft (Item item, Recipe recipe)
Allows you to make anything happen when a player uses this recipe.
static bool RecipeAvailable (Recipe recipe)
Returns whether or not the conditions are met for this recipe to be available for the player to use.
Detailed Description
This is where all ModRecipe and GlobalRecipe hooks are gathered and called.
Definition at line 9 of file RecipeHooks.cs.
Member Function Documentation
OnCraft()
static void Terraria.ModLoader.RecipeHooks.OnCraft (Item item, Recipe recipe) static
Allows you to make anything happen when a player uses this recipe.
Parameters
item The item crafted.
recipe The recipe used to craft the item.
Definition at line 78 of file RecipeHooks.cs.
{
            ModRecipe modRecipe = recipe as ModRecipe;
            if (modRecipe != null) {
                modRecipe.OnCraft(item);
            }
            foreach (GlobalRecipe globalRecipe in globalRecipes) {
                globalRecipe.OnCraft(item, recipe);
            }
        }
References Terraria.ModLoader.ModRecipe.OnCraft(), and Terraria.ModLoader.GlobalRecipe.OnCraft().
RecipeAvailable()
static bool Terraria.ModLoader.RecipeHooks.RecipeAvailable (Recipe recipe) static
Returns whether or not the conditions are met for this recipe to be available for the player to use.
Parameters
recipe The recipe to check.
Returns
Whether or not the conditions are met for this recipe.
Definition at line 60 of file RecipeHooks.cs.
{
            ModRecipe modRecipe = recipe as ModRecipe;
            if (modRecipe != null && !modRecipe.RecipeAvailable()) {
                return false;
            }
            foreach (GlobalRecipe globalRecipe in globalRecipes) {
                if (!globalRecipe.RecipeAvailable(recipe)) {
                    return false;
                }
            }
            return true;
        }
References Terraria.ModLoader.ModRecipe.RecipeAvailable(), and Terraria.ModLoader.GlobalRecipe.RecipeAvailable().