tModLoader: Terraria.ModLoader.GlobalRecipe Class Reference
Terraria.ModLoader.GlobalRecipe Class Reference
This class provides hooks that control all recipes in the game.
Public Member Functions
virtual bool Autoload (ref string name)
Allows you to automatically load a GlobalRecipe instead of using Mod.AddGlobalRecipe. Return true to allow autoloading; by default returns the mod's autoload property. Name is initialized to the overriding class name. Use this method to either force or stop an autoload, and to change the default internal name.
virtual void OnCraft (Item item, Recipe recipe)
Allows you to make anything happen when the player uses the given recipe. The item parameter is the item the player has just crafted.
virtual bool RecipeAvailable (Recipe recipe)
Whether or not the conditions are met for the given recipe to be available for the player to use. This hook can be used for conditions unrelated to items or tiles (for example, biome or time).
Properties
Mod mod [get, set]
The mod which added this GlobalRecipe.
string Name [get, set]
The name of this GlobaRecipe.
Detailed Description
This class provides hooks that control all recipes in the game.
Definition at line 6 of file GlobalRecipe.cs.
Member Function Documentation
Autoload()
virtual bool Terraria.ModLoader.GlobalRecipe.Autoload (ref string name) virtual
Allows you to automatically load a GlobalRecipe instead of using Mod.AddGlobalRecipe. Return true to allow autoloading; by default returns the mod's autoload property. Name is initialized to the overriding class name. Use this method to either force or stop an autoload, and to change the default internal name.
Definition at line 27 of file GlobalRecipe.cs.
{
            return mod.Properties.Autoload;
        }
References Terraria.ModLoader.ModProperties.Autoload, Terraria.ModLoader.GlobalRecipe.mod, and Terraria.ModLoader.Mod.Properties.
Referenced by Terraria.ModLoader.Mod.AutoloadGlobalRecipe().
OnCraft()
virtual void Terraria.ModLoader.GlobalRecipe.OnCraft (Item item, Recipe recipe) virtual
Allows you to make anything happen when the player uses the given recipe. The item parameter is the item the player has just crafted.
Parameters
item The item created.
recipe The recipe used to create the item.
Definition at line 43 of file GlobalRecipe.cs.
{
        }
Referenced by Terraria.ModLoader.RecipeHooks.OnCraft().
RecipeAvailable()
virtual bool Terraria.ModLoader.GlobalRecipe.RecipeAvailable (Recipe recipe) virtual
Whether or not the conditions are met for the given recipe to be available for the player to use. This hook can be used for conditions unrelated to items or tiles (for example, biome or time).
Definition at line 34 of file GlobalRecipe.cs.
{
            return true;
        }
Referenced by Terraria.ModLoader.RecipeHooks.RecipeAvailable().
Property Documentation
mod
Mod Terraria.ModLoader.GlobalRecipe.mod get set
The mod which added this GlobalRecipe.
Definition at line 11 of file GlobalRecipe.cs.
                       {
            get;
            internal set;
        }
Referenced by Terraria.ModLoader.GlobalRecipe.Autoload().
Name
string Terraria.ModLoader.GlobalRecipe.Name get set
The name of this GlobaRecipe.
Definition at line 19 of file GlobalRecipe.cs.
{
            get;
            internal set;
        }
Referenced by Terraria.ModLoader.Mod.AutoloadGlobalRecipe().