tModLoader: Terraria.ModLoader.ContentInstance< T > Class Template Reference
Terraria.ModLoader.ContentInstance< T > Class Template Reference
Classes
class ContentEntry
Static Public Member Functions
static void Register (object obj)
Properties
static T Instance [get, private set]
static IReadOnlyList< T > Instances [get, private set]
Static Private Member Functions
static ContentInstance ()
static ContentEntry Factory (Type t)
static void Update (object instance, IEnumerable instances)
Static Private Attributes
static ConcurrentDictionary< Type, ContentEntry > contentByType = new ConcurrentDictionary<Type, ContentEntry>()
Detailed Description
Type Constraints
T : class
Definition at line 64 of file ContentInstance.cs.
Constructor & Destructor Documentation
ContentInstance()
static Terraria.ModLoader.ContentInstance< T >.ContentInstance () static private
Definition at line 69 of file ContentInstance.cs.
{
            ContentInstance.Link(typeof(T), Update);
        }
References Terraria.ModLoader.ContentInstance< T >.Update().
Member Function Documentation
Factory()
static ContentEntry Terraria.ModLoader.ContentInstance< T >.Factory (Type t) static private
Register()
static void Terraria.ModLoader.ContentInstance< T >.Register (object obj) static
References Terraria.ModLoader.ContentInstance< T >.contentByType.
Referenced by Terraria.ModLoader.Mod.AddBuff(), Terraria.ModLoader.Mod.AddConfig(), Terraria.ModLoader.Mod.AddDust(), Terraria.ModLoader.Mod.AddGlobalBgStyle(), Terraria.ModLoader.Mod.AddGlobalBuff(), Terraria.ModLoader.Mod.AddGlobalItem(), Terraria.ModLoader.Mod.AddGlobalNPC(), Terraria.ModLoader.Mod.AddGlobalProjectile(), Terraria.ModLoader.Mod.AddGlobalRecipe(), Terraria.ModLoader.Mod.AddGlobalTile(), Terraria.ModLoader.Mod.AddGlobalWall(), Terraria.ModLoader.Mod.AddGore(), Terraria.ModLoader.Mod.AddItem(), Terraria.ModLoader.Mod.AddModWorld(), Terraria.ModLoader.Mod.AddMount(), Terraria.ModLoader.Mod.AddNPC(), Terraria.ModLoader.Mod.AddPlayer(), Terraria.ModLoader.Mod.AddPrefix(), Terraria.ModLoader.Mod.AddProjectile(), Terraria.ModLoader.Mod.AddSurfaceBgStyle(), Terraria.ModLoader.Mod.AddTile(), Terraria.ModLoader.Mod.AddTileEntity(), Terraria.ModLoader.Mod.AddUgBgStyle(), Terraria.ModLoader.Mod.AddWall(), Terraria.ModLoader.Mod.AddWaterfallStyle(), and Terraria.ModLoader.Mod.AddWaterStyle().
Update()
static void Terraria.ModLoader.ContentInstance< T >.Update (object instance, IEnumerable instances) static private
Definition at line 73 of file ContentInstance.cs.
{
            Instance = (T)instance;
            Instances = instances?.Cast<T>()?.ToArray();
        }
References Terraria.ModLoader.ContentInstance< T >.Instance, and Terraria.ModLoader.ContentInstance< T >.Instances.
Referenced by Terraria.ModLoader.ContentInstance< T >.ContentInstance().
Member Data Documentation
contentByType
ConcurrentDictionary<Type, ContentEntry> Terraria.ModLoader.ContentInstance< T >.contentByType = new ConcurrentDictionary<Type, ContentEntry>() static private
Definition at line 50 of file ContentInstance.cs.
Referenced by Terraria.ModLoader.ContentInstance< T >.Register().
Property Documentation
Instance
T Terraria.ModLoader.ContentInstance< T >.Instance static get private set
Definition at line 66 of file ContentInstance.cs.
{ get; private set; }
Referenced by Terraria.ModLoader.ContentInstance< T >.Update().
Instances
IReadOnlyList<T> Terraria.ModLoader.ContentInstance< T >.Instances static get private set
Definition at line 67 of file ContentInstance.cs.
{ get; private set; }
Referenced by Terraria.ModLoader.ContentInstance< T >.Update().