tModLoader: Terraria.ModLoader.ProjectileLoader Class Reference
Terraria.ModLoader.ProjectileLoader Class Reference
This serves as the central class from which projectile-related functions are carried out. It also stores a list of mod projectiles by ID.
Classes
class HookList
Static Public Member Functions
static void AI (Projectile projectile)
static ? bool CanCutTiles (Projectile projectile)
static bool CanDamage (Projectile projectile)
static ? bool CanHitNPC (Projectile projectile, NPC target)
static bool CanHitPlayer (Projectile projectile, Player target)
static bool CanHitPvp (Projectile projectile, Player target)
static ? bool CanUseGrapple (int type, Player player)
static ? bool Colliding (Projectile projectile, Rectangle projHitbox, Rectangle targetHitbox)
static void CutTiles (Projectile projectile)
static void DrawHeldProjInFrontOfHeldItemAndArms (Projectile projectile, ref bool flag)
static void DrawOffset (Projectile projectile, ref int offsetX, ref int offsetY, ref float originX)
static ? Color GetAlpha (Projectile projectile, Color lightColor)
static ModProjectile GetProjectile (int type)
Gets the ModProjectile instance corresponding to the specified type.
static bool GrappleOutOfRange (float distance, Projectile projectile)
static void GrapplePullSpeed (Projectile projectile, Player player, ref float speed)
static void GrappleRetreatSpeed (Projectile projectile, Player player, ref float speed)
static void GrappleTargetPoint (Projectile projectile, Player player, ref float grappleX, ref float grappleY)
static void Kill (Projectile projectile, int timeLeft)
static bool MinionContactDamage (Projectile projectile)
static void ModifyDamageHitbox (Projectile projectile, ref Rectangle hitbox)
static void ModifyHitNPC (Projectile projectile, NPC target, ref int damage, ref float knockback, ref bool crit, ref int hitDirection)
static void ModifyHitPlayer (Projectile projectile, Player target, ref int damage, ref bool crit)
static void ModifyHitPvp (Projectile projectile, Player target, ref int damage, ref bool crit)
static void NumGrappleHooks (Projectile projectile, Player player, ref int numHooks)
static void OnHitNPC (Projectile projectile, NPC target, int damage, float knockback, bool crit)
static void OnHitPlayer (Projectile projectile, Player target, int damage, bool crit)
static void OnHitPvp (Projectile projectile, Player target, int damage, bool crit)
static bool OnTileCollide (Projectile projectile, Vector2 oldVelocity)
static void PostAI (Projectile projectile)
static void PostDraw (Projectile projectile, SpriteBatch spriteBatch, Color lightColor)
static bool PreAI (Projectile projectile)
static bool PreDraw (Projectile projectile, SpriteBatch spriteBatch, Color lightColor)
static bool PreDrawExtras (Projectile projectile, SpriteBatch spriteBatch)
static bool PreKill (Projectile projectile, int timeLeft)
static void ProjectileAI (Projectile projectile)
static byte[] ReadExtraAI (BinaryReader reader, BitsByte flags)
static void ReceiveExtraAI (Projectile projectile, byte[] extraAI)
static byte[] SendExtraAI (Projectile projectile, ref BitsByte flags)
static bool ShouldUpdatePosition (Projectile projectile)
static ? bool SingleGrappleHook (int type, Player player)
static bool TileCollideStyle (Projectile projectile, ref int width, ref int height, ref bool fallThrough)
static void UseGrapple (Player player, ref int type)
Properties
static int ProjectileCount [get]
Private Member Functions
delegate void DelegateGrapplePullSpeed (Projectile projectile, Player player, ref float speed)
delegate void DelegateGrappleRetreatSpeed (Projectile projectile, Player player, ref float speed)
delegate void DelegateGrappleTargetPoint (Projectile projectile, Player player, ref float grappleX, ref float grappleY)
delegate void DelegateModifyDamageHitbox (Projectile projectile, ref Rectangle hitbox)
delegate void DelegateModifyHitNPC (Projectile projectile, NPC target, ref int damage, ref float knockback, ref bool crit, ref int hitDirection)
delegate void DelegateModifyHitPlayer (Projectile projectile, Player target, ref int damage, ref bool crit)
delegate void DelegateModifyHitPvp (Projectile projectile, Player target, ref int damage, ref bool crit)
delegate void DelegateNumGrappleHooks (Projectile projectile, Player player, ref int numHooks)
delegate bool DelegateTileCollideStyle (Projectile projectile, ref int width, ref int height, ref bool fallThrough)
delegate void DelegateUseGrapple (Player player, ref int type)
Static Private Member Functions
static HookList AddHook< F > (Expression< Func< GlobalProjectile, F > > func)
static bool HasMethod (Type t, string method, params Type[] args)
Static Private Attributes
static HookList HookAI = AddHook<Action<Projectile>>(g => g.AI)
static HookList HookCanCutTiles = AddHook<Func<Projectile, bool?>>(g => g.CanCutTiles)
static HookList HookCanDamage = AddHook<Func<Projectile, bool>>(g => g.CanDamage)
static HookList HookCanHitNPC = AddHook<Func<Projectile, NPC, bool?>>(g => g.CanHitNPC)
static HookList HookCanHitPlayer = AddHook<Func<Projectile, Player, bool>>(g => g.CanHitPlayer)
static HookList HookCanHitPvp = AddHook<Func<Projectile, Player, bool>>(g => g.CanHitPvp)
static HookList HookCanUseGrapple = AddHook<Func<int, Player, bool?>>(g => g.CanUseGrapple)
static HookList HookColliding = AddHook<Func<Projectile, Rectangle, Rectangle, bool?>>(g => g.Colliding)
static HookList HookCutTiles = AddHook<Action<Projectile>>(g => g.CutTiles)
static HookList HookDrawBehind = AddHook<Action<Projectile, int, List<int>, List<int>, List<int>, List<int>>>(g => g.DrawBehind)
static HookList HookGetAlpha = AddHook<Func<Projectile, Color, Color?>>(g => g.GetAlpha)
static HookList HookGrapplePullSpeed = AddHook<DelegateGrapplePullSpeed>(g => g.GrapplePullSpeed)
static HookList HookGrappleRetreatSpeed = AddHook<DelegateGrappleRetreatSpeed>(g => g.GrappleRetreatSpeed)
static HookList HookGrappleTargetPoint = AddHook<DelegateGrappleTargetPoint>(g => g.GrappleTargetPoint)
static HookList HookKill = AddHook<Action<Projectile, int>>(g => g.Kill)
static HookList HookMinionContactDamage = AddHook<Func<Projectile, bool>>(g => g.MinionContactDamage)
static HookList HookModifyDamageHitbox = AddHook<DelegateModifyDamageHitbox>(g => g.ModifyDamageHitbox)
static HookList HookModifyHitNPC = AddHook<DelegateModifyHitNPC>(g => g.ModifyHitNPC)
static HookList HookModifyHitPlayer = AddHook<DelegateModifyHitPlayer>(g => g.ModifyHitPlayer)
static HookList HookModifyHitPvp = AddHook<DelegateModifyHitPvp>(g => g.ModifyHitPvp)
static HookList HookNumGrappleHooks = AddHook<DelegateNumGrappleHooks>(g => g.NumGrappleHooks)
static HookList HookOnHitNPC = AddHook<Action<Projectile, NPC, int, float, bool>>(g => g.OnHitNPC)
static HookList HookOnHitPlayer = AddHook<Action<Projectile, Player, int, bool>>(g => g.OnHitPlayer)
static HookList HookOnHitPvp = AddHook<Action<Projectile, Player, int, bool>>(g => g.OnHitPvp)
static HookList HookOnTileCollide = AddHook<Func<Projectile, Vector2, bool>>(g => g.OnTileCollide)
static HookList HookPostAI = AddHook<Action<Projectile>>(g => g.PostAI)
static HookList HookPostDraw = AddHook<Action<Projectile, SpriteBatch, Color>>(g => g.PostDraw)
static HookList HookPreAI = AddHook<Func<Projectile, bool>>(g => g.PreAI)
static HookList HookPreDraw = AddHook<Func<Projectile, SpriteBatch, Color, bool>>(g => g.PreDraw)
static HookList HookPreDrawExtras = AddHook<Func<Projectile, SpriteBatch, bool>>(g => g.PreDrawExtras)
static HookList HookPreKill = AddHook<Func<Projectile, int, bool>>(g => g.PreKill)
static List< HookList > hooks = new List<HookList>()
static HookList HookSetDefaults = AddHook<Action<Projectile>>(g => g.SetDefaults)
static HookList HookShouldUpdatePosition = AddHook<Func<Projectile, bool>>(g => g.ShouldUpdatePosition)
static HookList HookSingleGrappleHook = AddHook<Func<int, Player, bool?>>(g => g.SingleGrappleHook)
static HookList HookTileCollideStyle = AddHook<DelegateTileCollideStyle>(g => g.TileCollideStyle)
static HookList HookUseGrapple = AddHook<DelegateUseGrapple>(g => g.UseGrapple)
static int nextProjectile = ProjectileID.Count
Detailed Description
This serves as the central class from which projectile-related functions are carried out. It also stores a list of mod projectiles by ID.
Definition at line 18 of file ProjectileLoader.cs.
Member Function Documentation
AddHook< F >()
static HookList Terraria.ModLoader.ProjectileLoader.AddHook< F > (Expression< Func< GlobalProjectile, F > > func) static private
Definition at line 39 of file ProjectileLoader.cs.
{
            var hook = new HookList(ModLoader.Method(func));
            hooks.Add(hook);
            return hook;
        }
References Terraria.ModLoader.ProjectileLoader.hooks.
AI()
static void Terraria.ModLoader.ProjectileLoader.AI (Projectile projectile) static
Definition at line 182 of file ProjectileLoader.cs.
{
            projectile.modProjectile?.AI();
            foreach (GlobalProjectile g in HookAI.arr) {
                g.Instance(projectile).AI(projectile);
            }
        }
References Terraria.ModLoader.GlobalProjectile.AI(), Terraria.ModLoader.ProjectileLoader.HookList.arr, Terraria.ModLoader.ProjectileLoader.HookAI, and Terraria.ModLoader.GlobalProjectile.Instance().
Referenced by Terraria.ModLoader.ProjectileLoader.ProjectileAI().
CanCutTiles()
static ? bool Terraria.ModLoader.ProjectileLoader.CanCutTiles (Projectile projectile) static
Definition at line 283 of file ProjectileLoader.cs.
{
            foreach (GlobalProjectile g in HookCanCutTiles.arr) {
                bool? canCutTiles = g.Instance(projectile).CanCutTiles(projectile);
                if (canCutTiles.HasValue) {
                    return canCutTiles.Value;
                }
            }
            return projectile.modProjectile?.CanCutTiles();
        }
References Terraria.ModLoader.ProjectileLoader.HookList.arr, Terraria.ModLoader.GlobalProjectile.CanCutTiles(), Terraria.ModLoader.ProjectileLoader.HookCanCutTiles, and Terraria.ModLoader.GlobalProjectile.Instance().
CanDamage()
static bool Terraria.ModLoader.ProjectileLoader.CanDamage (Projectile projectile) static
Definition at line 327 of file ProjectileLoader.cs.
{
            if (projectile.modProjectile != null && !projectile.modProjectile.CanDamage()) {
                return false;
            }
            foreach (GlobalProjectile g in HookCanDamage.arr) {
                if (!g.Instance(projectile).CanDamage(projectile)) {
                    return false;
                }
            }
            return true;
        }
References Terraria.ModLoader.ProjectileLoader.HookList.arr, Terraria.ModLoader.GlobalProjectile.CanDamage(), Terraria.ModLoader.ProjectileLoader.HookCanDamage, and Terraria.ModLoader.GlobalProjectile.Instance().
CanHitNPC()
static ? bool Terraria.ModLoader.ProjectileLoader.CanHitNPC (Projectile projectile, NPC target) static
Definition at line 365 of file ProjectileLoader.cs.
{
            bool? flag = null;
            foreach (GlobalProjectile g in HookCanHitNPC.arr) {
                bool? canHit = g.Instance(projectile).CanHitNPC(projectile, target);
                if (canHit.HasValue && !canHit.Value) {
                    return false;
                }
                if (canHit.HasValue) {
                    flag = canHit.Value;
                }
            }
            if (projectile.modProjectile != null) {
                bool? canHit = projectile.modProjectile.CanHitNPC(target);
                if (canHit.HasValue && !canHit.Value) {
                    return false;
                }
                if (canHit.HasValue) {
                    flag = canHit.Value;
                }
            }
            return flag;
        }
References Terraria.ModLoader.ProjectileLoader.HookList.arr, Terraria.ModLoader.GlobalProjectile.CanHitNPC(), Terraria.ModLoader.ProjectileLoader.HookCanHitNPC, and Terraria.ModLoader.GlobalProjectile.Instance().
CanHitPlayer()
static bool Terraria.ModLoader.ProjectileLoader.CanHitPlayer (Projectile projectile, Player target) static
Definition at line 446 of file ProjectileLoader.cs.
{
            foreach (GlobalProjectile g in HookCanHitPlayer.arr) {
                if (!g.Instance(projectile).CanHitPlayer(projectile, target)) {
                    return false;
                }
            }
            if (projectile.modProjectile != null) {
                return projectile.modProjectile.CanHitPlayer(target);
            }
            return true;
        }
References Terraria.ModLoader.ProjectileLoader.HookList.arr, Terraria.ModLoader.GlobalProjectile.CanHitPlayer(), Terraria.ModLoader.ProjectileLoader.HookCanHitPlayer, and Terraria.ModLoader.GlobalProjectile.Instance().
CanHitPvp()
static bool Terraria.ModLoader.ProjectileLoader.CanHitPvp (Projectile projectile, Player target) static
Definition at line 411 of file ProjectileLoader.cs.
{
            foreach (GlobalProjectile g in HookCanHitPvp.arr) {
                if (!g.Instance(projectile).CanHitPvp(projectile, target)) {
                    return false;
                }
            }
            if (projectile.modProjectile != null) {
                return projectile.modProjectile.CanHitPvp(target);
            }
            return true;
        }
References Terraria.ModLoader.ProjectileLoader.HookList.arr, Terraria.ModLoader.GlobalProjectile.CanHitPvp(), Terraria.ModLoader.ProjectileLoader.HookCanHitPvp, and Terraria.ModLoader.GlobalProjectile.Instance().
CanUseGrapple()
static ? bool Terraria.ModLoader.ProjectileLoader.CanUseGrapple (int type, Player player) static
Definition at line 555 of file ProjectileLoader.cs.
{
            var flag = GetProjectile(type)?.CanUseGrapple(player);
            foreach (GlobalProjectile g in HookCanUseGrapple.arr) {
                bool? canGrapple = g.CanUseGrapple(type, player);
                if (canGrapple.HasValue) {
                    flag = canGrapple;
                }
            }
            return flag;
        }
References Terraria.ModLoader.ProjectileLoader.HookList.arr, Terraria.ModLoader.GlobalProjectile.CanUseGrapple(), Terraria.ModLoader.ModProjectile.CanUseGrapple(), Terraria.ModLoader.ProjectileLoader.GetProjectile(), and Terraria.ModLoader.ProjectileLoader.HookCanUseGrapple.
Colliding()
static ? bool Terraria.ModLoader.ProjectileLoader.Colliding (Projectile projectile, Rectangle projHitbox, Rectangle targetHitbox) static
Definition at line 481 of file ProjectileLoader.cs.
{
            foreach (GlobalProjectile g in HookColliding.arr) {
                bool? colliding = g.Instance(projectile).Colliding(projectile, projHitbox, targetHitbox);
                if (colliding.HasValue) {
                    return colliding.Value;
                }
            }
            return projectile.modProjectile?.Colliding(projHitbox, targetHitbox);
        }
References Terraria.ModLoader.ProjectileLoader.HookList.arr, Terraria.ModLoader.GlobalProjectile.Colliding(), Terraria.ModLoader.ProjectileLoader.HookColliding, and Terraria.ModLoader.GlobalProjectile.Instance().
CutTiles()
static void Terraria.ModLoader.ProjectileLoader.CutTiles (Projectile projectile) static
Definition at line 295 of file ProjectileLoader.cs.
{
            foreach (GlobalProjectile g in HookCutTiles.arr) {
                g.Instance(projectile).CutTiles(projectile);
            }
            projectile.modProjectile?.CutTiles();
        }
References Terraria.ModLoader.ProjectileLoader.HookList.arr, Terraria.ModLoader.GlobalProjectile.CutTiles(), Terraria.ModLoader.ProjectileLoader.HookCutTiles, and Terraria.ModLoader.GlobalProjectile.Instance().
DelegateGrapplePullSpeed()
delegate void Terraria.ModLoader.ProjectileLoader.DelegateGrapplePullSpeed (Projectile projectile, Player player, ref float speed) private
DelegateGrappleRetreatSpeed()
delegate void Terraria.ModLoader.ProjectileLoader.DelegateGrappleRetreatSpeed (Projectile projectile, Player player, ref float speed) private
DelegateGrappleTargetPoint()
delegate void Terraria.ModLoader.ProjectileLoader.DelegateGrappleTargetPoint (Projectile projectile, Player player, ref float grappleX, ref float grappleY) private
DelegateModifyDamageHitbox()
delegate void Terraria.ModLoader.ProjectileLoader.DelegateModifyDamageHitbox (Projectile projectile, ref Rectangle hitbox) private
DelegateModifyHitNPC()
delegate void Terraria.ModLoader.ProjectileLoader.DelegateModifyHitNPC (Projectile projectile, NPC target, ref int damage, ref float knockback, ref bool crit, ref int hitDirection) private
DelegateModifyHitPlayer()
delegate void Terraria.ModLoader.ProjectileLoader.DelegateModifyHitPlayer (Projectile projectile, Player target, ref int damage, ref bool crit) private
DelegateModifyHitPvp()
delegate void Terraria.ModLoader.ProjectileLoader.DelegateModifyHitPvp (Projectile projectile, Player target, ref int damage, ref bool crit) private
DelegateNumGrappleHooks()
delegate void Terraria.ModLoader.ProjectileLoader.DelegateNumGrappleHooks (Projectile projectile, Player player, ref int numHooks) private
DelegateTileCollideStyle()
delegate bool Terraria.ModLoader.ProjectileLoader.DelegateTileCollideStyle (Projectile projectile, ref int width, ref int height, ref bool fallThrough) private
DelegateUseGrapple()
delegate void Terraria.ModLoader.ProjectileLoader.DelegateUseGrapple (Player player, ref int type) private
DrawHeldProjInFrontOfHeldItemAndArms()
static void Terraria.ModLoader.ProjectileLoader.DrawHeldProjInFrontOfHeldItemAndArms (Projectile projectile, ref bool flag) static
Definition at line 491 of file ProjectileLoader.cs.
{
            if (projectile.modProjectile != null) {
                flag = projectile.modProjectile.drawHeldProjInFrontOfHeldItemAndArms;
            }
        }
DrawOffset()
static void Terraria.ModLoader.ProjectileLoader.DrawOffset (Projectile projectile, ref int offsetX, ref int offsetY, ref float originX) static
Definition at line 509 of file ProjectileLoader.cs.
{
            if (projectile.modProjectile != null) {
                offsetX = projectile.modProjectile.drawOffsetX;
                offsetY = -projectile.modProjectile.drawOriginOffsetY;
                originX += projectile.modProjectile.drawOriginOffsetX;
            }
        }
GetAlpha()
static ? Color Terraria.ModLoader.ProjectileLoader.GetAlpha (Projectile projectile, Color lightColor) static
Definition at line 499 of file ProjectileLoader.cs.
{
            foreach (GlobalProjectile g in HookGetAlpha.arr) {
                Color? color = g.Instance(projectile).GetAlpha(projectile, lightColor);
                if (color.HasValue) {
                    return color;
                }
            }
            return projectile.modProjectile?.GetAlpha(lightColor);
        }
References Terraria.ModLoader.ProjectileLoader.HookList.arr, Terraria.ModLoader.GlobalProjectile.GetAlpha(), Terraria.ModLoader.ProjectileLoader.HookGetAlpha, and Terraria.ModLoader.GlobalProjectile.Instance().
GetProjectile()
static ModProjectile Terraria.ModLoader.ProjectileLoader.GetProjectile (int type) static
Gets the ModProjectile instance corresponding to the specified type.
Parameters
type The type of the projectile
Returns
The ModProjectile instance in the projectiles array, null if not found.
Definition at line 60 of file ProjectileLoader.cs.
{
            return type >= ProjectileID.Count && type < ProjectileCount ? projectiles[type - ProjectileID.Count] : null;
        }
References Terraria.ModLoader.ProjectileLoader.ProjectileCount.
Referenced by Terraria.ModLoader.ProjectileLoader.CanUseGrapple(), Terraria.ModLoader.ProjectileLoader.SingleGrappleHook(), and Terraria.ModLoader.ProjectileLoader.UseGrapple().
GrappleOutOfRange()
static bool Terraria.ModLoader.ProjectileLoader.GrappleOutOfRange (float distance, Projectile projectile) static
Definition at line 592 of file ProjectileLoader.cs.
{
            return distance > projectile.modProjectile?.GrappleRange();
        }
GrapplePullSpeed()
static void Terraria.ModLoader.ProjectileLoader.GrapplePullSpeed (Projectile projectile, Player player, ref float speed) static
Definition at line 621 of file ProjectileLoader.cs.
{
            projectile.modProjectile?.GrapplePullSpeed(player, ref speed);
            foreach (GlobalProjectile g in HookGrapplePullSpeed.arr) {
                g.Instance(projectile).GrapplePullSpeed(projectile, player, ref speed);
            }
        }
References Terraria.ModLoader.ProjectileLoader.HookList.arr, Terraria.ModLoader.GlobalProjectile.GrapplePullSpeed(), Terraria.ModLoader.ProjectileLoader.HookGrapplePullSpeed, and Terraria.ModLoader.GlobalProjectile.Instance().
GrappleRetreatSpeed()
static void Terraria.ModLoader.ProjectileLoader.GrappleRetreatSpeed (Projectile projectile, Player player, ref float speed) static
Definition at line 610 of file ProjectileLoader.cs.
{
            projectile.modProjectile?.GrappleRetreatSpeed(player, ref speed);
            foreach (GlobalProjectile g in HookGrappleRetreatSpeed.arr) {
                g.Instance(projectile).GrappleRetreatSpeed(projectile, player, ref speed);
            }
        }
References Terraria.ModLoader.ProjectileLoader.HookList.arr, Terraria.ModLoader.GlobalProjectile.GrappleRetreatSpeed(), Terraria.ModLoader.ProjectileLoader.HookGrappleRetreatSpeed, and Terraria.ModLoader.GlobalProjectile.Instance().
GrappleTargetPoint()
static void Terraria.ModLoader.ProjectileLoader.GrappleTargetPoint (Projectile projectile, Player player, ref float grappleX, ref float grappleY) static
Definition at line 632 of file ProjectileLoader.cs.
{
            projectile.modProjectile?.GrappleTargetPoint(player, ref grappleX, ref grappleY);
            foreach(GlobalProjectile g in HookGrappleTargetPoint.arr) {
                g.Instance(projectile).GrappleTargetPoint(projectile, player, ref grappleX, ref grappleY);
            }
        }
References Terraria.ModLoader.ProjectileLoader.HookList.arr, Terraria.ModLoader.GlobalProjectile.GrappleTargetPoint(), Terraria.ModLoader.ProjectileLoader.HookGrappleTargetPoint, and Terraria.ModLoader.GlobalProjectile.Instance().
HasMethod()
static bool Terraria.ModLoader.ProjectileLoader.HasMethod (Type t, string method, params Type[] args) static private
Definition at line 650 of file ProjectileLoader.cs.
{
            return t.GetMethod(method, args).DeclaringType != typeof(GlobalProjectile);
        }
Kill()
static void Terraria.ModLoader.ProjectileLoader.Kill (Projectile projectile, int timeLeft) static
Definition at line 317 of file ProjectileLoader.cs.
{
            projectile.modProjectile?.Kill(timeLeft);
            foreach (GlobalProjectile g in HookKill.arr) {
                g.Instance(projectile).Kill(projectile, timeLeft);
            }
        }
References Terraria.ModLoader.ProjectileLoader.HookList.arr, Terraria.ModLoader.ProjectileLoader.HookKill, Terraria.ModLoader.GlobalProjectile.Instance(), and Terraria.ModLoader.GlobalProjectile.Kill().
MinionContactDamage()
static bool Terraria.ModLoader.ProjectileLoader.MinionContactDamage (Projectile projectile) static
Definition at line 341 of file ProjectileLoader.cs.
{
            if (projectile.modProjectile != null && projectile.modProjectile.MinionContactDamage()) {
                return true;
            }
            foreach (GlobalProjectile g in HookMinionContactDamage.arr) {
                if (g.Instance(projectile).MinionContactDamage(projectile)) {
                    return true;
                }
            }
            return false;
        }
References Terraria.ModLoader.ProjectileLoader.HookList.arr, Terraria.ModLoader.ProjectileLoader.HookMinionContactDamage, Terraria.ModLoader.GlobalProjectile.Instance(), and Terraria.ModLoader.GlobalProjectile.MinionContactDamage().
ModifyDamageHitbox()
static void Terraria.ModLoader.ProjectileLoader.ModifyDamageHitbox (Projectile projectile, ref Rectangle hitbox) static
Definition at line 356 of file ProjectileLoader.cs.
{
            projectile.modProjectile?.ModifyDamageHitbox(ref hitbox);
            foreach (GlobalProjectile g in HookModifyDamageHitbox.arr) {
                g.Instance(projectile).ModifyDamageHitbox(projectile, ref hitbox);
            }
        }
References Terraria.ModLoader.ProjectileLoader.HookList.arr, Terraria.ModLoader.ProjectileLoader.HookModifyDamageHitbox, Terraria.ModLoader.GlobalProjectile.Instance(), and Terraria.ModLoader.GlobalProjectile.ModifyDamageHitbox().
ModifyHitNPC()
static void Terraria.ModLoader.ProjectileLoader.ModifyHitNPC (Projectile projectile, NPC target, ref int damage, ref float knockback, ref bool crit, ref int hitDirection) static
Definition at line 391 of file ProjectileLoader.cs.
{
            projectile.modProjectile?.ModifyHitNPC(target, ref damage, ref knockback, ref crit, ref hitDirection);
            foreach (GlobalProjectile g in HookModifyHitNPC.arr) {
                g.Instance(projectile).ModifyHitNPC(projectile, target, ref damage, ref knockback, ref crit, ref hitDirection);
            }
        }
References Terraria.ModLoader.ProjectileLoader.HookList.arr, Terraria.ModLoader.ProjectileLoader.HookModifyHitNPC, Terraria.ModLoader.GlobalProjectile.Instance(), and Terraria.ModLoader.GlobalProjectile.ModifyHitNPC().
ModifyHitPlayer()
static void Terraria.ModLoader.ProjectileLoader.ModifyHitPlayer (Projectile projectile, Player target, ref int damage, ref bool crit) static
Definition at line 461 of file ProjectileLoader.cs.
{
            projectile.modProjectile?.ModifyHitPlayer(target, ref damage, ref crit);
            foreach (GlobalProjectile g in HookModifyHitPlayer.arr) {
                g.Instance(projectile).ModifyHitPlayer(projectile, target, ref damage, ref crit);
            }
        }
References Terraria.ModLoader.ProjectileLoader.HookList.arr, Terraria.ModLoader.ProjectileLoader.HookModifyHitPlayer, Terraria.ModLoader.GlobalProjectile.Instance(), and Terraria.ModLoader.GlobalProjectile.ModifyHitPlayer().
ModifyHitPvp()
static void Terraria.ModLoader.ProjectileLoader.ModifyHitPvp (Projectile projectile, Player target, ref int damage, ref bool crit) static
Definition at line 426 of file ProjectileLoader.cs.
{
            projectile.modProjectile?.ModifyHitPvp(target, ref damage, ref crit);
            foreach (GlobalProjectile g in HookModifyHitPvp.arr) {
                g.Instance(projectile).ModifyHitPvp(projectile, target, ref damage, ref crit);
            }
        }
References Terraria.ModLoader.ProjectileLoader.HookList.arr, Terraria.ModLoader.ProjectileLoader.HookModifyHitPvp, Terraria.ModLoader.GlobalProjectile.Instance(), and Terraria.ModLoader.GlobalProjectile.ModifyHitPvp().
NumGrappleHooks()
static void Terraria.ModLoader.ProjectileLoader.NumGrappleHooks (Projectile projectile, Player player, ref int numHooks) static
Definition at line 599 of file ProjectileLoader.cs.
{
            projectile.modProjectile?.NumGrappleHooks(player, ref numHooks);
            foreach (GlobalProjectile g in HookNumGrappleHooks.arr) {
                g.Instance(projectile).NumGrappleHooks(projectile, player, ref numHooks);
            }
        }
References Terraria.ModLoader.ProjectileLoader.HookList.arr, Terraria.ModLoader.ProjectileLoader.HookNumGrappleHooks, Terraria.ModLoader.GlobalProjectile.Instance(), and Terraria.ModLoader.GlobalProjectile.NumGrappleHooks().
OnHitNPC()
static void Terraria.ModLoader.ProjectileLoader.OnHitNPC (Projectile projectile, NPC target, int damage, float knockback, bool crit) static
Definition at line 401 of file ProjectileLoader.cs.
{
            projectile.modProjectile?.OnHitNPC(target, damage, knockback, crit);
            foreach (GlobalProjectile g in HookOnHitNPC.arr) {
                g.Instance(projectile).OnHitNPC(projectile, target, damage, knockback, crit);
            }
        }
References Terraria.ModLoader.ProjectileLoader.HookList.arr, Terraria.ModLoader.ProjectileLoader.HookOnHitNPC, Terraria.ModLoader.GlobalProjectile.Instance(), and Terraria.ModLoader.GlobalProjectile.OnHitNPC().
OnHitPlayer()
static void Terraria.ModLoader.ProjectileLoader.OnHitPlayer (Projectile projectile, Player target, int damage, bool crit) static
Definition at line 471 of file ProjectileLoader.cs.
{
            projectile.modProjectile?.OnHitPlayer(target, damage, crit);
            foreach (GlobalProjectile g in HookOnHitPlayer.arr) {
                g.Instance(projectile).OnHitPlayer(projectile, target, damage, crit);
            }
        }
References Terraria.ModLoader.ProjectileLoader.HookList.arr, Terraria.ModLoader.ProjectileLoader.HookOnHitPlayer, Terraria.ModLoader.GlobalProjectile.Instance(), and Terraria.ModLoader.GlobalProjectile.OnHitPlayer().
OnHitPvp()
static void Terraria.ModLoader.ProjectileLoader.OnHitPvp (Projectile projectile, Player target, int damage, bool crit) static
Definition at line 436 of file ProjectileLoader.cs.
{
            projectile.modProjectile?.OnHitPvp(target, damage, crit);
            foreach (GlobalProjectile g in HookOnHitPvp.arr) {
                g.Instance(projectile).OnHitPvp(projectile, target, damage, crit);
            }
        }
References Terraria.ModLoader.ProjectileLoader.HookList.arr, Terraria.ModLoader.ProjectileLoader.HookOnHitPvp, Terraria.ModLoader.GlobalProjectile.Instance(), and Terraria.ModLoader.GlobalProjectile.OnHitPvp().
OnTileCollide()
static bool Terraria.ModLoader.ProjectileLoader.OnTileCollide (Projectile projectile, Vector2 oldVelocity) static
Definition at line 270 of file ProjectileLoader.cs.
{
            bool result = true;
            foreach (GlobalProjectile g in HookOnTileCollide.arr) {
                result &= g.Instance(projectile).OnTileCollide(projectile, oldVelocity);
            }
            if (result && projectile.modProjectile != null) {
                return projectile.modProjectile.OnTileCollide(oldVelocity);
            }
            return result;
        }
References Terraria.ModLoader.ProjectileLoader.HookList.arr, Terraria.ModLoader.ProjectileLoader.HookOnTileCollide, Terraria.ModLoader.GlobalProjectile.Instance(), and Terraria.ModLoader.GlobalProjectile.OnTileCollide().
PostAI()
static void Terraria.ModLoader.ProjectileLoader.PostAI (Projectile projectile) static
Definition at line 192 of file ProjectileLoader.cs.
{
            projectile.modProjectile?.PostAI();
            foreach (GlobalProjectile g in HookPostAI.arr) {
                g.Instance(projectile).PostAI(projectile);
            }
        }
References Terraria.ModLoader.ProjectileLoader.HookList.arr, Terraria.ModLoader.ProjectileLoader.HookPostAI, Terraria.ModLoader.GlobalProjectile.Instance(), and Terraria.ModLoader.GlobalProjectile.PostAI().
Referenced by Terraria.ModLoader.ProjectileLoader.ProjectileAI().
PostDraw()
static void Terraria.ModLoader.ProjectileLoader.PostDraw (Projectile projectile, SpriteBatch spriteBatch, Color lightColor) static
Definition at line 545 of file ProjectileLoader.cs.
{
            projectile.modProjectile?.PostDraw(spriteBatch, lightColor);
            foreach (GlobalProjectile g in HookPostDraw.arr) {
                g.Instance(projectile).PostDraw(projectile, spriteBatch, lightColor);
            }
        }
References Terraria.ModLoader.ProjectileLoader.HookList.arr, Terraria.ModLoader.ProjectileLoader.HookPostDraw, Terraria.ModLoader.GlobalProjectile.Instance(), and Terraria.ModLoader.GlobalProjectile.PostDraw().
PreAI()
static bool Terraria.ModLoader.ProjectileLoader.PreAI (Projectile projectile) static
Definition at line 169 of file ProjectileLoader.cs.
{
            bool result = true;
            foreach (GlobalProjectile g in HookPreAI.arr) {
                result &= g.Instance(projectile).PreAI(projectile);
            }
            if (result && projectile.modProjectile != null) {
                return projectile.modProjectile.PreAI();
            }
            return result;
        }
References Terraria.ModLoader.ProjectileLoader.HookList.arr, Terraria.ModLoader.ProjectileLoader.HookPreAI, Terraria.ModLoader.GlobalProjectile.Instance(), and Terraria.ModLoader.GlobalProjectile.PreAI().
Referenced by Terraria.ModLoader.ProjectileLoader.ProjectileAI().
PreDraw()
static bool Terraria.ModLoader.ProjectileLoader.PreDraw (Projectile projectile, SpriteBatch spriteBatch, Color lightColor) static
Definition at line 532 of file ProjectileLoader.cs.
{
            bool result = true;
            foreach (GlobalProjectile g in HookPreDraw.arr) {
                result &= g.Instance(projectile).PreDraw(projectile, spriteBatch, lightColor);
            }
            if (result && projectile.modProjectile != null) {
                return projectile.modProjectile.PreDraw(spriteBatch, lightColor);
            }
            return result;
        }
References Terraria.ModLoader.ProjectileLoader.HookList.arr, Terraria.ModLoader.ProjectileLoader.HookPreDraw, Terraria.ModLoader.GlobalProjectile.Instance(), and Terraria.ModLoader.GlobalProjectile.PreDraw().
PreDrawExtras()
static bool Terraria.ModLoader.ProjectileLoader.PreDrawExtras (Projectile projectile, SpriteBatch spriteBatch) static
Definition at line 519 of file ProjectileLoader.cs.
{
            bool result = true;
            foreach (GlobalProjectile g in HookPreDrawExtras.arr) {
                result &= g.Instance(projectile).PreDrawExtras(projectile, spriteBatch);
            }
            if (result && projectile.modProjectile != null) {
                return projectile.modProjectile.PreDrawExtras(spriteBatch);
            }
            return result;
        }
References Terraria.ModLoader.ProjectileLoader.HookList.arr, Terraria.ModLoader.ProjectileLoader.HookPreDrawExtras, Terraria.ModLoader.GlobalProjectile.Instance(), and Terraria.ModLoader.GlobalProjectile.PreDrawExtras().
PreKill()
static bool Terraria.ModLoader.ProjectileLoader.PreKill (Projectile projectile, int timeLeft) static
Definition at line 304 of file ProjectileLoader.cs.
{
            bool result = true;
            foreach (GlobalProjectile g in HookPreKill.arr) {
                result &= g.Instance(projectile).PreKill(projectile, timeLeft);
            }
            if (result && projectile.modProjectile != null) {
                return projectile.modProjectile.PreKill(timeLeft);
            }
            return result;
        }
References Terraria.ModLoader.ProjectileLoader.HookList.arr, Terraria.ModLoader.ProjectileLoader.HookPreKill, Terraria.ModLoader.GlobalProjectile.Instance(), and Terraria.ModLoader.GlobalProjectile.PreKill().
ProjectileAI()
static void Terraria.ModLoader.ProjectileLoader.ProjectileAI (Projectile projectile) static
Definition at line 151 of file ProjectileLoader.cs.
{
            if (PreAI(projectile)) {
                int type = projectile.type;
                bool useAiType = projectile.modProjectile != null && projectile.modProjectile.aiType > 0;
                if (useAiType) {
                    projectile.type = projectile.modProjectile.aiType;
                }
                projectile.VanillaAI();
                if (useAiType) {
                    projectile.type = type;
                }
                AI(projectile);
            }
            PostAI(projectile);
        }
References Terraria.ModLoader.ProjectileLoader.AI(), Terraria.ModLoader.ProjectileLoader.PostAI(), and Terraria.ModLoader.ProjectileLoader.PreAI().
ReadExtraAI()
static byte[] Terraria.ModLoader.ProjectileLoader.ReadExtraAI (BinaryReader reader, BitsByte flags) static
Definition at line 220 of file ProjectileLoader.cs.
{
            if (flags[Projectile.maxAI + 1]) {
                return reader.ReadBytes(reader.ReadByte());
            }
            return new byte[0];
        }
ReceiveExtraAI()
static void Terraria.ModLoader.ProjectileLoader.ReceiveExtraAI (Projectile projectile, byte[] extraAI) static
Definition at line 228 of file ProjectileLoader.cs.
{
            if (extraAI.Length > 0 && projectile.modProjectile != null) {
                using (MemoryStream stream = new MemoryStream(extraAI)) {
                    using (BinaryReader reader = new BinaryReader(stream)) {
                        projectile.modProjectile.ReceiveExtraAI(reader);
                    }
                }
            }
        }
SendExtraAI()
static byte[] Terraria.ModLoader.ProjectileLoader.SendExtraAI (Projectile projectile, ref BitsByte flags) static
Definition at line 201 of file ProjectileLoader.cs.
{
            if (projectile.modProjectile != null) {
                byte[] data;
                using (MemoryStream stream = new MemoryStream()) {
                    using (BinaryWriter modWriter = new BinaryWriter(stream)) {
                        projectile.modProjectile.SendExtraAI(modWriter);
                        modWriter.Flush();
                        data = stream.ToArray();
                    }
                }
                if (data.Length > 0) {
                    flags[Projectile.maxAI + 1] = true;
                }
                return data;
            }
            return new byte[0];
        }
ShouldUpdatePosition()
static bool Terraria.ModLoader.ProjectileLoader.ShouldUpdatePosition (Projectile projectile) static
Definition at line 240 of file ProjectileLoader.cs.
{
            if (IsModProjectile(projectile) && !projectile.modProjectile.ShouldUpdatePosition()) {
                return false;
            }
            foreach (GlobalProjectile g in HookShouldUpdatePosition.arr) {
                if (!g.Instance(projectile).ShouldUpdatePosition(projectile)) {
                    return false;
                }
            }
            return true;
        }
References Terraria.ModLoader.ProjectileLoader.HookList.arr, Terraria.ModLoader.ProjectileLoader.HookShouldUpdatePosition, Terraria.ModLoader.GlobalProjectile.Instance(), and Terraria.ModLoader.GlobalProjectile.ShouldUpdatePosition().
SingleGrappleHook()
static ? bool Terraria.ModLoader.ProjectileLoader.SingleGrappleHook (int type, Player player) static
Definition at line 569 of file ProjectileLoader.cs.
{
            bool? flag = GetProjectile(type)?.SingleGrappleHook(player);
            foreach (GlobalProjectile g in HookSingleGrappleHook.arr) {
                bool? singleHook = g.SingleGrappleHook(type, player);
                if (singleHook.HasValue) {
                    flag = singleHook;
                }
            }
            return flag;
        }
References Terraria.ModLoader.ProjectileLoader.HookList.arr, Terraria.ModLoader.ProjectileLoader.GetProjectile(), Terraria.ModLoader.ProjectileLoader.HookSingleGrappleHook, Terraria.ModLoader.GlobalProjectile.SingleGrappleHook(), and Terraria.ModLoader.ModProjectile.SingleGrappleHook().
TileCollideStyle()
static bool Terraria.ModLoader.ProjectileLoader.TileCollideStyle (Projectile projectile, ref int width, ref int height, ref bool fallThrough) static
Definition at line 255 of file ProjectileLoader.cs.
{
            if (IsModProjectile(projectile) && !projectile.modProjectile.TileCollideStyle(ref width, ref height, ref fallThrough)) {
                return false;
            }
            foreach (GlobalProjectile g in HookTileCollideStyle.arr) {
                if (!g.Instance(projectile).TileCollideStyle(projectile, ref width, ref height, ref fallThrough)) {
                    return false;
                }
            }
            return true;
        }
References Terraria.ModLoader.ProjectileLoader.HookList.arr, Terraria.ModLoader.ProjectileLoader.HookTileCollideStyle, Terraria.ModLoader.GlobalProjectile.Instance(), and Terraria.ModLoader.GlobalProjectile.TileCollideStyle().
UseGrapple()
static void Terraria.ModLoader.ProjectileLoader.UseGrapple (Player player, ref int type) static
Definition at line 584 of file ProjectileLoader.cs.
{
            GetProjectile(type)?.UseGrapple(player, ref type);
            foreach (GlobalProjectile g in HookUseGrapple.arr) {
                g.UseGrapple(player, ref type);
            }
        }
References Terraria.ModLoader.ProjectileLoader.HookList.arr, Terraria.ModLoader.ProjectileLoader.GetProjectile(), Terraria.ModLoader.ProjectileLoader.HookUseGrapple, Terraria.ModLoader.GlobalProjectile.UseGrapple(), and Terraria.ModLoader.ModProjectile.UseGrapple().
Member Data Documentation
HookAI
HookList Terraria.ModLoader.ProjectileLoader.HookAI = AddHook<Action<Projectile>>(g => g.AI) static private
Definition at line 180 of file ProjectileLoader.cs.
Referenced by Terraria.ModLoader.ProjectileLoader.AI().
HookCanCutTiles
HookList Terraria.ModLoader.ProjectileLoader.HookCanCutTiles = AddHook<Func<Projectile, bool?>>(g => g.CanCutTiles) static private
Definition at line 281 of file ProjectileLoader.cs.
Referenced by Terraria.ModLoader.ProjectileLoader.CanCutTiles().
HookCanDamage
HookList Terraria.ModLoader.ProjectileLoader.HookCanDamage = AddHook<Func<Projectile, bool>>(g => g.CanDamage) static private
Definition at line 325 of file ProjectileLoader.cs.
Referenced by Terraria.ModLoader.ProjectileLoader.CanDamage().
HookCanHitNPC
HookList Terraria.ModLoader.ProjectileLoader.HookCanHitNPC = AddHook<Func<Projectile, NPC, bool?>>(g => g.CanHitNPC) static private
Definition at line 363 of file ProjectileLoader.cs.
Referenced by Terraria.ModLoader.ProjectileLoader.CanHitNPC().
HookCanHitPlayer
HookList Terraria.ModLoader.ProjectileLoader.HookCanHitPlayer = AddHook<Func<Projectile, Player, bool>>(g => g.CanHitPlayer) static private
Definition at line 444 of file ProjectileLoader.cs.
Referenced by Terraria.ModLoader.ProjectileLoader.CanHitPlayer().
HookCanHitPvp
HookList Terraria.ModLoader.ProjectileLoader.HookCanHitPvp = AddHook<Func<Projectile, Player, bool>>(g => g.CanHitPvp) static private
Definition at line 409 of file ProjectileLoader.cs.
Referenced by Terraria.ModLoader.ProjectileLoader.CanHitPvp().
HookCanUseGrapple
HookList Terraria.ModLoader.ProjectileLoader.HookCanUseGrapple = AddHook<Func<int, Player, bool?>>(g => g.CanUseGrapple) static private
Definition at line 553 of file ProjectileLoader.cs.
Referenced by Terraria.ModLoader.ProjectileLoader.CanUseGrapple().
HookColliding
HookList Terraria.ModLoader.ProjectileLoader.HookColliding = AddHook<Func<Projectile, Rectangle, Rectangle, bool?>>(g => g.Colliding) static private
Definition at line 479 of file ProjectileLoader.cs.
Referenced by Terraria.ModLoader.ProjectileLoader.Colliding().
HookCutTiles
HookList Terraria.ModLoader.ProjectileLoader.HookCutTiles = AddHook<Action<Projectile>>(g => g.CutTiles) static private
Definition at line 293 of file ProjectileLoader.cs.
Referenced by Terraria.ModLoader.ProjectileLoader.CutTiles().
HookDrawBehind
HookList Terraria.ModLoader.ProjectileLoader.HookDrawBehind = AddHook<Action<Projectile, int, List<int>, List<int>, List<int>, List<int>>>(g => g.DrawBehind) static private
Definition at line 640 of file ProjectileLoader.cs.
HookGetAlpha
HookList Terraria.ModLoader.ProjectileLoader.HookGetAlpha = AddHook<Func<Projectile, Color, Color?>>(g => g.GetAlpha) static private
Definition at line 497 of file ProjectileLoader.cs.
Referenced by Terraria.ModLoader.ProjectileLoader.GetAlpha().
HookGrapplePullSpeed
HookList Terraria.ModLoader.ProjectileLoader.HookGrapplePullSpeed = AddHook<DelegateGrapplePullSpeed>(g => g.GrapplePullSpeed) static private
Definition at line 619 of file ProjectileLoader.cs.
Referenced by Terraria.ModLoader.ProjectileLoader.GrapplePullSpeed().
HookGrappleRetreatSpeed
HookList Terraria.ModLoader.ProjectileLoader.HookGrappleRetreatSpeed = AddHook<DelegateGrappleRetreatSpeed>(g => g.GrappleRetreatSpeed) static private
Definition at line 608 of file ProjectileLoader.cs.
Referenced by Terraria.ModLoader.ProjectileLoader.GrappleRetreatSpeed().
HookGrappleTargetPoint
HookList Terraria.ModLoader.ProjectileLoader.HookGrappleTargetPoint = AddHook<DelegateGrappleTargetPoint>(g => g.GrappleTargetPoint) static private
Definition at line 630 of file ProjectileLoader.cs.
Referenced by Terraria.ModLoader.ProjectileLoader.GrappleTargetPoint().
HookKill
HookList Terraria.ModLoader.ProjectileLoader.HookKill = AddHook<Action<Projectile, int>>(g => g.Kill) static private
Definition at line 315 of file ProjectileLoader.cs.
Referenced by Terraria.ModLoader.ProjectileLoader.Kill().
HookMinionContactDamage
HookList Terraria.ModLoader.ProjectileLoader.HookMinionContactDamage = AddHook<Func<Projectile, bool>>(g => g.MinionContactDamage) static private
Definition at line 339 of file ProjectileLoader.cs.
Referenced by Terraria.ModLoader.ProjectileLoader.MinionContactDamage().
HookModifyDamageHitbox
HookList Terraria.ModLoader.ProjectileLoader.HookModifyDamageHitbox = AddHook<DelegateModifyDamageHitbox>(g => g.ModifyDamageHitbox) static private
Definition at line 354 of file ProjectileLoader.cs.
Referenced by Terraria.ModLoader.ProjectileLoader.ModifyDamageHitbox().
HookModifyHitNPC
HookList Terraria.ModLoader.ProjectileLoader.HookModifyHitNPC = AddHook<DelegateModifyHitNPC>(g => g.ModifyHitNPC) static private
Definition at line 389 of file ProjectileLoader.cs.
Referenced by Terraria.ModLoader.ProjectileLoader.ModifyHitNPC().
HookModifyHitPlayer
HookList Terraria.ModLoader.ProjectileLoader.HookModifyHitPlayer = AddHook<DelegateModifyHitPlayer>(g => g.ModifyHitPlayer) static private
Definition at line 459 of file ProjectileLoader.cs.
Referenced by Terraria.ModLoader.ProjectileLoader.ModifyHitPlayer().
HookModifyHitPvp
HookList Terraria.ModLoader.ProjectileLoader.HookModifyHitPvp = AddHook<DelegateModifyHitPvp>(g => g.ModifyHitPvp) static private
Definition at line 424 of file ProjectileLoader.cs.
Referenced by Terraria.ModLoader.ProjectileLoader.ModifyHitPvp().
HookNumGrappleHooks
HookList Terraria.ModLoader.ProjectileLoader.HookNumGrappleHooks = AddHook<DelegateNumGrappleHooks>(g => g.NumGrappleHooks) static private
Definition at line 597 of file ProjectileLoader.cs.
Referenced by Terraria.ModLoader.ProjectileLoader.NumGrappleHooks().
HookOnHitNPC
HookList Terraria.ModLoader.ProjectileLoader.HookOnHitNPC = AddHook<Action<Projectile, NPC, int, float, bool>>(g => g.OnHitNPC) static private
Definition at line 399 of file ProjectileLoader.cs.
Referenced by Terraria.ModLoader.ProjectileLoader.OnHitNPC().
HookOnHitPlayer
HookList Terraria.ModLoader.ProjectileLoader.HookOnHitPlayer = AddHook<Action<Projectile, Player, int, bool>>(g => g.OnHitPlayer) static private
Definition at line 469 of file ProjectileLoader.cs.
Referenced by Terraria.ModLoader.ProjectileLoader.OnHitPlayer().
HookOnHitPvp
HookList Terraria.ModLoader.ProjectileLoader.HookOnHitPvp = AddHook<Action<Projectile, Player, int, bool>>(g => g.OnHitPvp) static private
Definition at line 434 of file ProjectileLoader.cs.
Referenced by Terraria.ModLoader.ProjectileLoader.OnHitPvp().
HookOnTileCollide
HookList Terraria.ModLoader.ProjectileLoader.HookOnTileCollide = AddHook<Func<Projectile, Vector2, bool>>(g => g.OnTileCollide) static private
Definition at line 268 of file ProjectileLoader.cs.
Referenced by Terraria.ModLoader.ProjectileLoader.OnTileCollide().
HookPostAI
HookList Terraria.ModLoader.ProjectileLoader.HookPostAI = AddHook<Action<Projectile>>(g => g.PostAI) static private
Definition at line 190 of file ProjectileLoader.cs.
Referenced by Terraria.ModLoader.ProjectileLoader.PostAI().
HookPostDraw
HookList Terraria.ModLoader.ProjectileLoader.HookPostDraw = AddHook<Action<Projectile, SpriteBatch, Color>>(g => g.PostDraw) static private
Definition at line 543 of file ProjectileLoader.cs.
Referenced by Terraria.ModLoader.ProjectileLoader.PostDraw().
HookPreAI
HookList Terraria.ModLoader.ProjectileLoader.HookPreAI = AddHook<Func<Projectile, bool>>(g => g.PreAI) static private
Definition at line 167 of file ProjectileLoader.cs.
Referenced by Terraria.ModLoader.ProjectileLoader.PreAI().
HookPreDraw
HookList Terraria.ModLoader.ProjectileLoader.HookPreDraw = AddHook<Func<Projectile, SpriteBatch, Color, bool>>(g => g.PreDraw) static private
Definition at line 530 of file ProjectileLoader.cs.
Referenced by Terraria.ModLoader.ProjectileLoader.PreDraw().
HookPreDrawExtras
HookList Terraria.ModLoader.ProjectileLoader.HookPreDrawExtras = AddHook<Func<Projectile, SpriteBatch, bool>>(g => g.PreDrawExtras) static private
Definition at line 517 of file ProjectileLoader.cs.
Referenced by Terraria.ModLoader.ProjectileLoader.PreDrawExtras().
HookPreKill
HookList Terraria.ModLoader.ProjectileLoader.HookPreKill = AddHook<Func<Projectile, int, bool>>(g => g.PreKill) static private
Definition at line 302 of file ProjectileLoader.cs.
Referenced by Terraria.ModLoader.ProjectileLoader.PreKill().
hooks
List<HookList> Terraria.ModLoader.ProjectileLoader.hooks = new List<HookList>() static private
Definition at line 37 of file ProjectileLoader.cs.
Referenced by Terraria.ModLoader.ProjectileLoader.AddHook< F >().
HookSetDefaults
HookList Terraria.ModLoader.ProjectileLoader.HookSetDefaults = AddHook<Action<Projectile>>(g => g.SetDefaults) static private
Definition at line 128 of file ProjectileLoader.cs.
HookShouldUpdatePosition
HookList Terraria.ModLoader.ProjectileLoader.HookShouldUpdatePosition = AddHook<Func<Projectile, bool>>(g => g.ShouldUpdatePosition) static private
Definition at line 238 of file ProjectileLoader.cs.
Referenced by Terraria.ModLoader.ProjectileLoader.ShouldUpdatePosition().
HookSingleGrappleHook
HookList Terraria.ModLoader.ProjectileLoader.HookSingleGrappleHook = AddHook<Func<int, Player, bool?>>(g => g.SingleGrappleHook) static private
Definition at line 567 of file ProjectileLoader.cs.
Referenced by Terraria.ModLoader.ProjectileLoader.SingleGrappleHook().
HookTileCollideStyle
HookList Terraria.ModLoader.ProjectileLoader.HookTileCollideStyle = AddHook<DelegateTileCollideStyle>(g => g.TileCollideStyle) static private
Definition at line 253 of file ProjectileLoader.cs.
Referenced by Terraria.ModLoader.ProjectileLoader.TileCollideStyle().
HookUseGrapple
HookList Terraria.ModLoader.ProjectileLoader.HookUseGrapple = AddHook<DelegateUseGrapple>(g => g.UseGrapple) static private
Definition at line 582 of file ProjectileLoader.cs.
Referenced by Terraria.ModLoader.ProjectileLoader.UseGrapple().
nextProjectile
int Terraria.ModLoader.ProjectileLoader.nextProjectile = ProjectileID.Count static private
Definition at line 20 of file ProjectileLoader.cs.
Property Documentation
ProjectileCount
int Terraria.ModLoader.ProjectileLoader.ProjectileCount static get
Definition at line 53 of file ProjectileLoader.cs.
Referenced by Terraria.ModLoader.ProjectileLoader.GetProjectile().