tModLoader: Terraria.ModLoader.IO.TagPrinter Class Reference
Terraria.ModLoader.IO.TagPrinter Class Reference
Public Member Functions
override string ToString ()
Static Public Member Functions
static string Print (KeyValuePair< string, object > entry)
static string Print (TagCompound tag)
Private Member Functions
string TypeString (Type type)
void WriteEntry (KeyValuePair< string, object > entry)
void WriteList< T > (char start, char end, bool multiline, IEnumerable< T > list, Action< T > write)
void WriteValue (object elem)
Private Attributes
string indent = ""
StringBuilder sb = new StringBuilder()
Detailed Description
Definition at line 9 of file TagPrinter.cs.
Member Function Documentation
Print() [1/2]
static string Terraria.ModLoader.IO.TagPrinter.Print (KeyValuePair< string, object > entry) static
Definition at line 110 of file TagPrinter.cs.
{
            var printer = new TagPrinter();
            printer.WriteEntry(entry);
            return printer.ToString();
        }
Print() [2/2]
static string Terraria.ModLoader.IO.TagPrinter.Print (TagCompound tag) static
Definition at line 104 of file TagPrinter.cs.
{
            var printer = new TagPrinter();
            printer.WriteValue(tag);
            return printer.ToString();
        }
Referenced by Terraria.ModLoader.IO.TagCompound.ToString().
ToString()
override string Terraria.ModLoader.IO.TagPrinter.ToString ()
Definition at line 14 of file TagPrinter.cs.
{
            return sb.ToString();
        }
References Terraria.ModLoader.IO.TagPrinter.sb.
TypeString()
string Terraria.ModLoader.IO.TagPrinter.TypeString (Type type) private
Definition at line 18 of file TagPrinter.cs.
{
            if (type == typeof(byte)) return "byte";
            if (type == typeof(short)) return "short";
            if (type == typeof(int)) return "int";
            if (type == typeof(long)) return "long";
            if (type == typeof(float)) return "float";
            if (type == typeof(double)) return "double";
            if (type == typeof(string)) return "string";
            if (type == typeof(byte[])) return "byte[]";
            if (type == typeof(int[])) return "int[]";
            if (type == typeof(TagCompound)) return "object";
            if (type == typeof(IList)) return "list";
            throw new ArgumentException("Unknown Type: " + type);
        }
Referenced by Terraria.ModLoader.IO.TagPrinter.WriteEntry(), and Terraria.ModLoader.IO.TagPrinter.WriteValue().
WriteEntry()
void Terraria.ModLoader.IO.TagPrinter.WriteEntry (KeyValuePair< string, object > entry) private
Definition at line 49 of file TagPrinter.cs.
{
            if (entry.Value == null) {
                sb.Append('"').Append(entry.Key).Append("\" = null");
                return;
            }
            var type = entry.Value.GetType();
            var isList = entry.Value is IList && !(entry.Value is Array);
            sb.Append(TypeString(isList ? type.GetGenericArguments()[0] : type));
            sb.Append(" \"").Append(entry.Key).Append("\" ");
            if (type != typeof(TagCompound) && !isList)
                sb.Append("= ");
            WriteValue(entry.Value);
        }
References Terraria.ModLoader.IO.TagPrinter.sb, Terraria.ModLoader.IO.TagPrinter.TypeString(), and Terraria.ModLoader.IO.TagPrinter.WriteValue().
Referenced by Terraria.ModLoader.IO.TagPrinter.WriteValue().
WriteList< T >()
void Terraria.ModLoader.IO.TagPrinter.WriteList< T > (char start, char end, bool multiline, IEnumerable< T > list, Action< T > write) private
Definition at line 33 of file TagPrinter.cs.
{
            sb.Append(start);
            indent += "  ";
            var first = true;
            foreach (var entry in list) {
                if (first) first = false;
                else sb.Append(multiline ? "," : ", ");
                if (multiline) sb.AppendLine().Append(indent);
                write(entry);
            }
            indent = indent.Substring(2);
            if (multiline && !first) sb.AppendLine().Append(indent);
            sb.Append(end);
        }
References Terraria.ModLoader.IO.TagPrinter.indent, and Terraria.ModLoader.IO.TagPrinter.sb.
WriteValue()
void Terraria.ModLoader.IO.TagPrinter.WriteValue (object elem) private
Definition at line 67 of file TagPrinter.cs.
{
            if (elem is byte)
                sb.Append((byte)elem);
            else if (elem is short)
                sb.Append((short)elem);
            else if (elem is int)
                sb.Append((int)elem);
            else if (elem is long)
                sb.Append((long)elem);
            else if (elem is float)
                sb.Append((float)elem);
            else if (elem is double)
                sb.Append((double)elem);
            else if (elem is string)
                sb.Append('"').Append((string)elem).Append('"');
            else if (elem is byte[])
                sb.Append('[').Append(string.Join(", ", (byte[])elem)).Append(']');
            else if (elem is int[])
                sb.Append('[').Append(string.Join(", ", (int[])elem)).Append(']');
            else if (elem is TagCompound) {
                var tag = (TagCompound)elem;
                WriteList('{', '}', true, tag, WriteEntry);
            }
            else if (elem is IList) {
                var type = elem.GetType().GetGenericArguments()[0];
                WriteList('[', ']',
                    type == typeof(string) || type == typeof(TagCompound) || typeof(IList).IsAssignableFrom(type),
                    ((IList)elem).Cast<object>(),
                    o => {
                        if (type == typeof(IList)) //lists of lists need their subtype printed
                            sb.Append(TypeString(o.GetType().GetGenericArguments()[0])).Append(' ');
                        WriteValue(o);
                    });
            }
        }
References Terraria.ModLoader.IO.TagPrinter.sb, Terraria.ModLoader.IO.TagPrinter.TypeString(), Terraria.ModLoader.IO.TagPrinter.WriteEntry(), and Terraria.ModLoader.IO.TagPrinter.WriteValue().
Referenced by Terraria.ModLoader.IO.TagPrinter.WriteEntry(), and Terraria.ModLoader.IO.TagPrinter.WriteValue().
Member Data Documentation
indent
string Terraria.ModLoader.IO.TagPrinter.indent = "" private
Definition at line 11 of file TagPrinter.cs.
Referenced by Terraria.ModLoader.IO.TagPrinter.WriteList< T >().
sb
StringBuilder Terraria.ModLoader.IO.TagPrinter.sb = new StringBuilder() private
Definition at line 12 of file TagPrinter.cs.
Referenced by Terraria.ModLoader.IO.TagPrinter.ToString(), Terraria.ModLoader.IO.TagPrinter.WriteEntry(), Terraria.ModLoader.IO.TagPrinter.WriteList< T >(), and Terraria.ModLoader.IO.TagPrinter.WriteValue().