tModLoader: Terraria.ModLoader.CombinedHooks Class Reference
Terraria.ModLoader.CombinedHooks Class Reference
Static Public Member Functions
static void GetWeaponDamage (Player player, Item item, ref int damage)
static void ModifyManaCost (Player player, Item item, ref float reduce, ref float mult)
static void ModifyWeaponDamage (Player player, Item item, ref float add, ref float mult, ref float flat)
static void OnConsumeMana (Player player, Item item, int manaConsumed)
static void OnMissingMana (Player player, Item item, int neededMana)
Detailed Description
Definition at line 5 of file CombinedHooks.cs.
Member Function Documentation
GetWeaponDamage()
static void Terraria.ModLoader.CombinedHooks.GetWeaponDamage (Player player, Item item, ref int damage) static
Definition at line 13 of file CombinedHooks.cs.
{
            ItemLoader.GetWeaponDamage(item, player, ref damage);
            PlayerHooks.GetWeaponDamage(player, item, ref damage);
        }
References Terraria.ModLoader.ItemLoader.GetWeaponDamage(), and Terraria.ModLoader.PlayerHooks.GetWeaponDamage().
ModifyManaCost()
static void Terraria.ModLoader.CombinedHooks.ModifyManaCost (Player player, Item item, ref float reduce, ref float mult) static
Definition at line 18 of file CombinedHooks.cs.
{
            ItemLoader.ModifyManaCost(item, player, ref reduce, ref mult);
            PlayerHooks.ModifyManaCost(player, item, ref reduce, ref mult);
        }
References Terraria.ModLoader.ItemLoader.ModifyManaCost(), and Terraria.ModLoader.PlayerHooks.ModifyManaCost().
ModifyWeaponDamage()
static void Terraria.ModLoader.CombinedHooks.ModifyWeaponDamage (Player player, Item item, ref float add, ref float mult, ref float flat) static
Definition at line 7 of file CombinedHooks.cs.
{
            ItemLoader.ModifyWeaponDamage(item, player, ref add, ref mult, ref flat);
            PlayerHooks.ModifyWeaponDamage(player, item, ref add, ref mult, ref flat);
        }
References Terraria.ModLoader.ItemLoader.ModifyWeaponDamage(), and Terraria.ModLoader.PlayerHooks.ModifyWeaponDamage().
OnConsumeMana()
static void Terraria.ModLoader.CombinedHooks.OnConsumeMana (Player player, Item item, int manaConsumed) static
Definition at line 23 of file CombinedHooks.cs.
{
            ItemLoader.OnConsumeMana(item, player, manaConsumed);
            PlayerHooks.OnConsumeMana(player, item, manaConsumed);
        }
References Terraria.ModLoader.ItemLoader.OnConsumeMana(), and Terraria.ModLoader.PlayerHooks.OnConsumeMana().
OnMissingMana()
static void Terraria.ModLoader.CombinedHooks.OnMissingMana (Player player, Item item, int neededMana) static
Definition at line 28 of file CombinedHooks.cs.
{
            ItemLoader.OnMissingMana(item, player, neededMana);
            PlayerHooks.OnMissingMana(player, item, neededMana);
        }
References Terraria.ModLoader.ItemLoader.OnMissingMana(), and Terraria.ModLoader.PlayerHooks.OnMissingMana().