tModLoader: Terraria.ModLoader.Config.ConfigManager Class Reference
Terraria.ModLoader.Config.ConfigManager Class Reference
Static Public Member Functions
static object AlternateCreateInstance (Type type)
static bool EnumerableEquals (IEnumerable a, IEnumerable b)
static ModConfig GeneratePopulatedClone (ModConfig original)
static T GetCustomAttribute< T > (PropertyFieldWrapper memberInfo, object item, object array)
static T GetCustomAttribute< T > (PropertyFieldWrapper memberInfo, Type type)
static IEnumerable< PropertyFieldWrapper > GetFieldsAndProperties (object item)
static bool ObjectEquals (object a, object b)
static void SetPendingChanges (bool changes=true)
static Tuple< UIElement, UIElement > WrapIt (UIElement parent, ref int top, PropertyFieldWrapper memberInfo, object item, int order, object list=null, Type arrayType=null, int index=-1)
Static Public Attributes
static readonly string ModConfigPath = Path.Combine(Main.SavePath, "Mod Configs")
static readonly JsonSerializerSettings serializerSettings
static readonly string ServerModConfigPath = Path.Combine(Main.SavePath, "Mod Configs", "Server")
Static Private Attributes
static readonly IList< JsonConverter > converters
static readonly IDictionary< Mod, List< ModConfig > > LoadTimeConfigs = new Dictionary<Mod, List<ModConfig>>()
Detailed Description
Definition at line 18 of file ConfigManager.cs.
Member Function Documentation
AlternateCreateInstance()
static object Terraria.ModLoader.Config.ConfigManager.AlternateCreateInstance (Type type) static
Definition at line 300 of file ConfigManager.cs.
        {
            if (type == typeof(string))
                return "";
            return Activator.CreateInstance(type);
        }
EnumerableEquals()
static bool Terraria.ModLoader.Config.ConfigManager.EnumerableEquals (IEnumerable a, IEnumerable b) static
Definition at line 354 of file ConfigManager.cs.
{
            IEnumerator enumeratorA = a.GetEnumerator();
            IEnumerator enumeratorB = b.GetEnumerator();
            bool hasNextA = enumeratorA.MoveNext();
            bool hasNextB = enumeratorB.MoveNext();
            while (hasNextA && hasNextB) {
                if (!ObjectEquals(enumeratorA.Current, enumeratorB.Current)) return false;
                hasNextA = enumeratorA.MoveNext();
                hasNextB = enumeratorB.MoveNext();
            }
            return !hasNextA && !hasNextB;
        }
References Terraria.ModLoader.Config.ConfigManager.ObjectEquals().
Referenced by Terraria.ModLoader.Config.ConfigManager.ObjectEquals().
GeneratePopulatedClone()
static ModConfig Terraria.ModLoader.Config.ConfigManager.GeneratePopulatedClone (ModConfig original) static
Definition at line 293 of file ConfigManager.cs.
{
            string json = JsonConvert.SerializeObject(original, ConfigManager.serializerSettings);
            ModConfig properClone = original.Clone();
            JsonConvert.PopulateObject(json, properClone, ConfigManager.serializerSettings);
            return properClone;
        }
References Terraria.ModLoader.Config.ModConfig.Clone(), and Terraria.ModLoader.Config.ConfigManager.serializerSettings.
GetCustomAttribute< T >() [1/2]
static T Terraria.ModLoader.Config.ConfigManager.GetCustomAttribute< T > (PropertyFieldWrapper memberInfo, object item, object array) static
Type Constraints
T : Attribute
Definition at line 309 of file ConfigManager.cs.
                                                                                                                  : Attribute {
            // Class
            T attribute = (T)Attribute.GetCustomAttribute(memberInfo.Type, typeof(T), true);
            if (array != null)
            {
                // item null?
            //  attribute = (T)Attribute.GetCustomAttribute(item.GetType(), typeof(T), true) ?? attribute; // TODO: is this wrong?
            }
            // Member
            attribute = (T)Attribute.GetCustomAttribute(memberInfo.MemberInfo, typeof(T)) ?? attribute;
            return attribute;
            // TODO: allow for inheriting from parent's parent? (could get attribute from parent ConfigElement)
        }
GetCustomAttribute< T >() [2/2]
static T Terraria.ModLoader.Config.ConfigManager.GetCustomAttribute< T > (PropertyFieldWrapper memberInfo, Type type) static
Type Constraints
T : Attribute
Definition at line 323 of file ConfigManager.cs.
                                                                                                  : Attribute {
            // Class
            T attribute = (T)Attribute.GetCustomAttribute(memberInfo.Type, typeof(T), true);
            attribute = (T)Attribute.GetCustomAttribute(type, typeof(T), true) ?? attribute;
            // Member
            attribute = (T)Attribute.GetCustomAttribute(memberInfo.MemberInfo, typeof(T)) ?? attribute;
            return attribute;
        }
GetFieldsAndProperties()
static IEnumerable< PropertyFieldWrapper > Terraria.ModLoader.Config.ConfigManager.GetFieldsAndProperties (object item) static
Definition at line 278 of file ConfigManager.cs.
        {
            PropertyInfo[] properties = item.GetType().GetProperties(
                //BindingFlags.DeclaredOnly |
                BindingFlags.Public |
                BindingFlags.Instance);
            FieldInfo[] fields = item.GetType().GetFields(
                //BindingFlags.DeclaredOnly |
                BindingFlags.Public |
                BindingFlags.Instance);
            return fields.Select(x => new PropertyFieldWrapper(x)).Concat(properties.Select(x => new PropertyFieldWrapper(x)));
        }
Referenced by Terraria.ModLoader.Config.ModConfig.NeedsReload().
ObjectEquals()
static bool Terraria.ModLoader.Config.ConfigManager.ObjectEquals (object a, object b) static
Definition at line 346 of file ConfigManager.cs.
{
            if (ReferenceEquals(a, b)) return true;
            if (a == null || b == null) return false;
            if (a is IEnumerable && b is IEnumerable && !(a is string) && !(b is string))
                return EnumerableEquals((IEnumerable)a, (IEnumerable)b);
            return a.Equals(b);
        }
References Terraria.ModLoader.Config.ConfigManager.EnumerableEquals().
Referenced by Terraria.ModLoader.Config.ReferenceDefaultsPreservingResolver.CreateProperties(), Terraria.ModLoader.Config.ConfigManager.EnumerableEquals(), and Terraria.ModLoader.Config.ModConfig.NeedsReload().
SetPendingChanges()
static void Terraria.ModLoader.Config.ConfigManager.SetPendingChanges (bool changes = true) static
Definition at line 340 of file ConfigManager.cs.
{
            // public api for modders.
            Interface.modConfig.SetPendingChanges(changes);
        }
WrapIt()
static Tuple< UIElement, UIElement > Terraria.ModLoader.Config.ConfigManager.WrapIt (UIElement parent, ref int top, PropertyFieldWrapper memberInfo, object item, int order, object list = null, Type arrayType = null, int index = -1) static
Definition at line 334 of file ConfigManager.cs.
        {
            // public api for modders.
            return UIModConfig.WrapIt(parent, ref top, memberInfo, item, order, list, arrayType, index);
        }
Member Data Documentation
converters
readonly IList<JsonConverter> Terraria.ModLoader.Config.ConfigManager.converters static private
Initial value:
= new List<JsonConverter>() {
            new Newtonsoft.Json.Converters.VersionConverter(),
        }
Definition at line 48 of file ConfigManager.cs.
LoadTimeConfigs
readonly IDictionary<Mod, List<ModConfig> > Terraria.ModLoader.Config.ConfigManager.LoadTimeConfigs = new Dictionary<Mod, List<ModConfig>>() static private
Definition at line 26 of file ConfigManager.cs.
ModConfigPath
readonly string Terraria.ModLoader.Config.ConfigManager.ModConfigPath = Path.Combine(Main.SavePath, "Mod Configs") static
Definition at line 53 of file ConfigManager.cs.
serializerSettings
readonly JsonSerializerSettings Terraria.ModLoader.Config.ConfigManager.serializerSettings static
Initial value:
= new JsonSerializerSettings
        {
            Formatting = Formatting.Indented,
            DefaultValueHandling = DefaultValueHandling.IgnoreAndPopulate,
            ObjectCreationHandling = ObjectCreationHandling.Replace,
            NullValueHandling = NullValueHandling.Ignore,
            Converters = converters,
            ContractResolver = new ReferenceDefaultsPreservingResolver()
        }
Definition at line 28 of file ConfigManager.cs.
Referenced by Terraria.ModLoader.Config.ConfigManager.GeneratePopulatedClone().
ServerModConfigPath
readonly string Terraria.ModLoader.Config.ConfigManager.ServerModConfigPath = Path.Combine(Main.SavePath, "Mod Configs", "Server") static
Definition at line 54 of file ConfigManager.cs.