tModLoader: Terraria.ModLoader.ModPrefix Class Reference
Terraria.ModLoader.ModPrefix Class Reference
Public Member Functions
virtual void Apply (Item item)
Applies the custom data stats set in SetStats to the given item.
virtual void AutoDefaults ()
virtual bool Autoload (ref string name)
virtual bool CanRoll (Item item)
Returns if your ModPrefix can roll on the given item By default returns RollChance(item) > 0
virtual void ModifyValue (ref float valueMult)
Allows you to modify the sell price of the item based on the prefix or changes in custom data stats. This also influences the item's rarity.
virtual float RollChance (Item item)
The roll chance of your prefix relative to a vanilla prefix, 1f by default.
virtual void SetDefaults ()
Allows you to set the prefix's name/translations and to set its category.
virtual void SetStats (ref float damageMult, ref float knockbackMult, ref float useTimeMult, ref float scaleMult, ref float shootSpeedMult, ref float manaMult, ref int critBonus)
Sets the stat changes for this prefix. If data is not already pre-stored, it is best to store custom data changes to some static variables.
virtual void ValidateItem (Item item, ref bool invalid)
Validates whether this prefix with the custom data stats set from SetStats is allowed on the given item. It is not allowed if one of the stat changes do not cause any change (eg. percentage being too small to make a difference).
Static Public Member Functions
static ModPrefix GetPrefix (byte type)
Returns the ModPrefix associated with specified type If not a ModPrefix, returns null.
static List< ModPrefix > GetPrefixesInCategory (PrefixCategory category)
Returns a list of all modded prefixes of a certain category.
Properties
virtual PrefixCategory Category [get]
The category your prefix belongs to, PrefixCategory.Custom by default
ModTranslation DisplayName [get, set]
Mod mod [get, set]
string Name [get, set]
static byte PrefixCount [get]
byte Type [get, set]
Static Private Member Functions
static ModPrefix ()
Static Private Attributes
static byte nextPrefix = PrefixID.Count
Detailed Description
Definition at line 10 of file ModPrefix.cs.
Constructor & Destructor Documentation
ModPrefix()
static Terraria.ModLoader.ModPrefix.ModPrefix () static private
Definition at line 18 of file ModPrefix.cs.
{
            categoryPrefixes = new Dictionary<PrefixCategory, IList<ModPrefix>>();
            foreach (PrefixCategory category in Enum.GetValues(typeof(PrefixCategory))) {
                categoryPrefixes[category] = new List<ModPrefix>();
            }
        }
Member Function Documentation
Apply()
virtual void Terraria.ModLoader.ModPrefix.Apply (Item item) virtual
Applies the custom data stats set in SetStats to the given item.
Parameters
item
Definition at line 159 of file ModPrefix.cs.
{
        }
AutoDefaults()
virtual void Terraria.ModLoader.ModPrefix.AutoDefaults () virtual
Definition at line 130 of file ModPrefix.cs.
{
            if (DisplayName.IsDefault())
                DisplayName.SetDefault(Regex.Replace(Name, "([A-Z])", " $1").Trim());
        }
References Terraria.ModLoader.ModPrefix.DisplayName, Terraria.ModLoader.ModTranslation.IsDefault(), Terraria.ModLoader.ModPrefix.Name, and Terraria.ModLoader.ModTranslation.SetDefault().
Autoload()
virtual bool Terraria.ModLoader.ModPrefix.Autoload (ref string name) virtual
Definition at line 126 of file ModPrefix.cs.
{
            return mod.Properties.Autoload;
        }
References Terraria.ModLoader.ModProperties.Autoload, Terraria.ModLoader.ModPrefix.mod, and Terraria.ModLoader.Mod.Properties.
Referenced by Terraria.ModLoader.Mod.AutoloadPrefix().
CanRoll()
virtual bool Terraria.ModLoader.ModPrefix.CanRoll (Item item) virtual
Returns if your ModPrefix can roll on the given item By default returns RollChance(item) > 0
Parameters
item
Returns
Definition at line 117 of file ModPrefix.cs.
{
            return RollChance(item) > 0;
        }
References Terraria.ModLoader.ModPrefix.RollChance().
GetPrefix()
static ModPrefix Terraria.ModLoader.ModPrefix.GetPrefix (byte type) static
Returns the ModPrefix associated with specified type If not a ModPrefix, returns null.
Parameters
type
Returns
Definition at line 40 of file ModPrefix.cs.
{
            return type >= PrefixID.Count && type < PrefixCount ? prefixes[type - PrefixID.Count] : null;
        }
References Terraria.ModLoader.ModPrefix.PrefixCount.
Referenced by Terraria.ModLoader.IO.ItemIO.Save().
GetPrefixesInCategory()
static List< ModPrefix > Terraria.ModLoader.ModPrefix.GetPrefixesInCategory (PrefixCategory category) static
Returns a list of all modded prefixes of a certain category.
Parameters
category
Returns
Definition at line 49 of file ModPrefix.cs.
{
            return new List<ModPrefix>(categoryPrefixes[category]);
        }
ModifyValue()
virtual void Terraria.ModLoader.ModPrefix.ModifyValue (ref float valueMult) virtual
Allows you to modify the sell price of the item based on the prefix or changes in custom data stats. This also influences the item's rarity.
Definition at line 165 of file ModPrefix.cs.
{
        }
RollChance()
virtual float Terraria.ModLoader.ModPrefix.RollChance (Item item) virtual
The roll chance of your prefix relative to a vanilla prefix, 1f by default.
Parameters
item
Returns
Definition at line 107 of file ModPrefix.cs.
{
            return 1f;
        }
Referenced by Terraria.ModLoader.ModPrefix.CanRoll().
SetDefaults()
virtual void Terraria.ModLoader.ModPrefix.SetDefaults () virtual
Allows you to set the prefix's name/translations and to set its category.
Definition at line 138 of file ModPrefix.cs.
{
        }
SetStats()
virtual void Terraria.ModLoader.ModPrefix.SetStats (ref float damageMult, ref float knockbackMult, ref float useTimeMult, ref float scaleMult, ref float shootSpeedMult, ref float manaMult, ref int critBonus) virtual
Sets the stat changes for this prefix. If data is not already pre-stored, it is best to store custom data changes to some static variables.
Definition at line 144 of file ModPrefix.cs.
{
        }
ValidateItem()
virtual void Terraria.ModLoader.ModPrefix.ValidateItem (Item item, ref bool invalid) virtual
Validates whether this prefix with the custom data stats set from SetStats is allowed on the given item. It is not allowed if one of the stat changes do not cause any change (eg. percentage being too small to make a difference).
Definition at line 152 of file ModPrefix.cs.
{
        }
Member Data Documentation
nextPrefix
byte Terraria.ModLoader.ModPrefix.nextPrefix = PrefixID.Count static private
Definition at line 12 of file ModPrefix.cs.
Property Documentation
Category
virtual PrefixCategory Terraria.ModLoader.ModPrefix.Category get
The category your prefix belongs to, PrefixCategory.Custom by default
Definition at line 124 of file ModPrefix.cs.
Referenced by Terraria.ModLoader.Mod.AddPrefix().
DisplayName
ModTranslation Terraria.ModLoader.ModPrefix.DisplayName get set
Definition at line 97 of file ModPrefix.cs.
{
            get;
            internal set;
        }
Referenced by Terraria.ModLoader.ModPrefix.AutoDefaults(), and Terraria.ModLoader.ModContent.RefreshModLanguage().
mod
Mod Terraria.ModLoader.ModPrefix.mod get set
Definition at line 82 of file ModPrefix.cs.
                       {
            get;
            internal set;
        }
Referenced by Terraria.ModLoader.ModPrefix.Autoload(), and Terraria.ModLoader.IO.ItemIO.Save().
Name
string Terraria.ModLoader.ModPrefix.Name get set
Definition at line 87 of file ModPrefix.cs.
{
            get;
            internal set;
        }
Referenced by Terraria.ModLoader.ModPrefix.AutoDefaults(), Terraria.ModLoader.Mod.AutoloadPrefix(), and Terraria.ModLoader.IO.ItemIO.Save().
PrefixCount
byte Terraria.ModLoader.ModPrefix.PrefixCount static get
Definition at line 53 of file ModPrefix.cs.
Referenced by Terraria.ModLoader.ModPrefix.GetPrefix().
Type
byte Terraria.ModLoader.ModPrefix.Type get set
Definition at line 92 of file ModPrefix.cs.
{
            get;
            internal set;
        }
Referenced by Terraria.ModLoader.ModContent.RefreshModLanguage().