tModLoader: Terraria.ModLoader.IO.TagCompound Class Reference
Terraria.ModLoader.IO.TagCompound Class Reference
Public Member Functions
void Add (KeyValuePair< string, object > entry)
void Add (string key, object value)
void Clear ()
object Clone ()
bool ContainsKey (string key)
T Get< T > (string key)
double GetAsDouble (string key)
int GetAsInt (string key)
long GetAsLong (string key)
short GetAsShort (string key)
bool GetBool (string key)
byte GetByte (string key)
byte[] GetByteArray (string key)
TagCompound GetCompound (string key)
double GetDouble (string key)
IEnumerator< KeyValuePair< string, object > > GetEnumerator ()
float GetFloat (string key)
int GetInt (string key)
int[] GetIntArray (string key)
IList< T > GetList< T > (string key)
long GetLong (string key)
short GetShort (string key)
string GetString (string key)
T GetTag< T > (string key)
bool HasTag (string key)
bool Remove (string key)
bool RemoveTag (string key)
void Set (string key, object value)
void Set (string key, object value, bool replace=false)
void SetTag (string key, object value)
override string ToString ()
Properties
int Count [get]
object this[string key] [get, set]
Private Member Functions
IEnumerator IEnumerable. GetEnumerator ()
Private Attributes
Dictionary< string, object > dict = new Dictionary<string, object>()
Detailed Description
Definition at line 14 of file TagCompound.cs.
Member Function Documentation
Add() [1/2]
void Terraria.ModLoader.IO.TagCompound.Add (KeyValuePair< string, object > entry)
Add() [2/2]
void Terraria.ModLoader.IO.TagCompound.Add (string key, object value)
Clear()
void Terraria.ModLoader.IO.TagCompound.Clear ()
Definition at line 121 of file TagCompound.cs.
{ dict.Clear(); }
References Terraria.ModLoader.IO.TagCompound.dict.
Clone()
object Terraria.ModLoader.IO.TagCompound.Clone ()
Definition at line 99 of file TagCompound.cs.
{
            var copy = new TagCompound();
            foreach (var entry in this)
                copy.Set(entry.Key, TagIO.Clone(entry.Value));
            return copy;
        }
ContainsKey()
bool Terraria.ModLoader.IO.TagCompound.ContainsKey (string key)
Referenced by Terraria.ModLoader.IO.ItemIO.Load().
Get< T >()
T Terraria.ModLoader.IO.TagCompound.Get< T > (string key)
Definition at line 17 of file TagCompound.cs.
{
            object tag = null;
            dict.TryGetValue(key, out tag);
            try {
                return TagIO.Deserialize<T>(tag);
            }
            catch (Exception e) {
                throw new IOException(
                    $"NBT Deserialization (type={typeof(T)}," +
                    $"entry={TagPrinter.Print(new KeyValuePair<string, object>(key, tag))})", e);
            }
        }
References Terraria.ModLoader.IO.TagIO.Deserialize(), and Terraria.ModLoader.IO.TagCompound.dict.
GetAsDouble()
double Terraria.ModLoader.IO.TagCompound.GetAsDouble (string key)
Definition at line 94 of file TagCompound.cs.
{
            var o = Get<object>(key);
            return o as double? ?? o as float? ?? 0;
        }
GetAsInt()
int Terraria.ModLoader.IO.TagCompound.GetAsInt (string key)
Definition at line 84 of file TagCompound.cs.
{
            var o = Get<object>(key);
            return o as int? ?? o as short? ?? o as byte? ?? 0;
        }
GetAsLong()
long Terraria.ModLoader.IO.TagCompound.GetAsLong (string key)
Definition at line 89 of file TagCompound.cs.
{
            var o = Get<object>(key);
            return o as long? ?? o as int? ?? o as short? ?? o as byte? ?? 0;
        }
GetAsShort()
short Terraria.ModLoader.IO.TagCompound.GetAsShort (string key)
Definition at line 79 of file TagCompound.cs.
{
            var o = Get<object>(key);
            return o as short? ?? o as byte? ?? 0;
        }
GetBool()
bool Terraria.ModLoader.IO.TagCompound.GetBool (string key)
Referenced by Terraria.ModLoader.IO.ItemIO.Load().
GetByte()
byte Terraria.ModLoader.IO.TagCompound.GetByte (string key)
Referenced by Terraria.ModLoader.IO.ItemIO.Load().
GetByteArray()
byte[] Terraria.ModLoader.IO.TagCompound.GetByteArray (string key)
Referenced by Terraria.ModLoader.IO.ItemIO.Load().
GetCompound()
TagCompound Terraria.ModLoader.IO.TagCompound.GetCompound (string key)
Referenced by Terraria.ModLoader.IO.ItemIO.Load().
GetDouble()
double Terraria.ModLoader.IO.TagCompound.GetDouble (string key)
GetEnumerator() [1/2]
IEnumerator< KeyValuePair< string, object > > Terraria.ModLoader.IO.TagCompound.GetEnumerator ()
GetEnumerator() [2/2]
IEnumerator IEnumerable. Terraria.ModLoader.IO.TagCompound.GetEnumerator () private
GetFloat()
float Terraria.ModLoader.IO.TagCompound.GetFloat (string key)
GetInt()
int Terraria.ModLoader.IO.TagCompound.GetInt (string key)
Referenced by Terraria.ModLoader.IO.ItemIO.Load().
GetIntArray()
int[] Terraria.ModLoader.IO.TagCompound.GetIntArray (string key)
GetList< T >()
IList< T > Terraria.ModLoader.IO.TagCompound.GetList< T > (string key)
GetLong()
long Terraria.ModLoader.IO.TagCompound.GetLong (string key)
GetShort()
short Terraria.ModLoader.IO.TagCompound.GetShort (string key)
GetString()
string Terraria.ModLoader.IO.TagCompound.GetString (string key)
Referenced by Terraria.ModLoader.IO.ItemIO.Load().
GetTag< T >()
T Terraria.ModLoader.IO.TagCompound.GetTag< T > (string key)
HasTag()
bool Terraria.ModLoader.IO.TagCompound.HasTag (string key)
Remove()
bool Terraria.ModLoader.IO.TagCompound.Remove (string key)
Referenced by Terraria.ModLoader.IO.TagCompound.Set().
RemoveTag()
bool Terraria.ModLoader.IO.TagCompound.RemoveTag (string key)
Set() [1/2]
void Terraria.ModLoader.IO.TagCompound.Set (string key, object value)
Set() [2/2]
void Terraria.ModLoader.IO.TagCompound.Set (string key, object value, bool replace = false)
Definition at line 34 of file TagCompound.cs.
{
            if (value == null) {
                Remove(key);
                return;
            }
            object serialized;
            try {
                serialized = TagIO.Serialize(value);
            }
            catch (IOException e) {
                var valueInfo = "value=" + value;
                if (value.GetType().ToString() != value.ToString())
                    valueInfo = "type=" + value.GetType() + "," + valueInfo;
                throw new IOException($"NBT Serialization (key={key},{valueInfo})", e);
            }
            if (replace)
                dict[key] = serialized;
            else
                dict.Add(key, serialized);
        }
References Terraria.ModLoader.IO.TagCompound.dict, Terraria.ModLoader.IO.TagCompound.Remove(), and Terraria.ModLoader.IO.TagIO.Serialize().
SetTag()
void Terraria.ModLoader.IO.TagCompound.SetTag (string key, object value)
ToString()
override string Terraria.ModLoader.IO.TagCompound.ToString ()
Definition at line 107 of file TagCompound.cs.
{
            return TagPrinter.Print(this);
        }
References Terraria.ModLoader.IO.TagPrinter.Print().
Member Data Documentation
dict
Dictionary<string, object> Terraria.ModLoader.IO.TagCompound.dict = new Dictionary<string, object>() private
Definition at line 16 of file TagCompound.cs.
Referenced by Terraria.ModLoader.IO.TagCompound.Clear(), Terraria.ModLoader.IO.TagCompound.Get< T >(), and Terraria.ModLoader.IO.TagCompound.Set().
Property Documentation
Count
int Terraria.ModLoader.IO.TagCompound.Count get
Definition at line 122 of file TagCompound.cs.
this[string key]
object Terraria.ModLoader.IO.TagCompound.this[string key] get set
Definition at line 111 of file TagCompound.cs.
{
            get { return Get<object>(key); }
            set { Set(key, value, true); }
        }