tModLoader: Terraria.ModLoader.ModTranslation Class Reference
Terraria.ModLoader.ModTranslation Class Reference
Public Member Functions
void AddTranslation (GameCulture culture, string value)
void AddTranslation (int culture, string value)
void AddTranslation (string culture, string value)
string GetDefault ()
string GetTranslation (GameCulture culture)
string GetTranslation (int culture)
string GetTranslation (string culture)
bool IsDefault ()
void SetDefault (string value)
Public Attributes
readonly string Key
Private Attributes
Dictionary< int, string > translations
Static Private Attributes
const int fallback = 1
Detailed Description
Definition at line 7 of file ModTranslation.cs.
Member Function Documentation
AddTranslation() [1/3]
void Terraria.ModLoader.ModTranslation.AddTranslation (GameCulture culture, string value)
Definition at line 33 of file ModTranslation.cs.
{
            AddTranslation(culture.LegacyId, value);
        }
References Terraria.ModLoader.ModTranslation.AddTranslation().
AddTranslation() [2/3]
void Terraria.ModLoader.ModTranslation.AddTranslation (int culture, string value)
Definition at line 25 of file ModTranslation.cs.
{
            translations[culture] = value;
        }
References Terraria.ModLoader.ModTranslation.translations.
Referenced by Terraria.ModLoader.ModTranslation.AddTranslation(), Terraria.ModLoader.Mod.AutoloadLocalization(), and Terraria.ModLoader.ModTranslation.SetDefault().
AddTranslation() [3/3]
void Terraria.ModLoader.ModTranslation.AddTranslation (string culture, string value)
Definition at line 29 of file ModTranslation.cs.
{
            AddTranslation(GameCulture.FromName(culture).LegacyId, value);
        }
References Terraria.ModLoader.ModTranslation.AddTranslation().
GetDefault()
string Terraria.ModLoader.ModTranslation.GetDefault ()
Definition at line 41 of file ModTranslation.cs.
{
            return GetTranslation(fallback);
        }
References Terraria.ModLoader.ModTranslation.fallback, and Terraria.ModLoader.ModTranslation.GetTranslation().
GetTranslation() [1/3]
string Terraria.ModLoader.ModTranslation.GetTranslation (GameCulture culture)
Definition at line 56 of file ModTranslation.cs.
{
            return GetTranslation(culture.LegacyId);
        }
References Terraria.ModLoader.ModTranslation.GetTranslation().
GetTranslation() [2/3]
string Terraria.ModLoader.ModTranslation.GetTranslation (int culture)
Definition at line 45 of file ModTranslation.cs.
{
            if (translations.ContainsKey(culture)) {
                return translations[culture];
            }
            return translations[fallback];
        }
References Terraria.ModLoader.ModTranslation.fallback, and Terraria.ModLoader.ModTranslation.translations.
Referenced by Terraria.ModLoader.ModTranslation.GetDefault(), Terraria.ModLoader.ModTranslation.GetTranslation(), and Terraria.ModLoader.ModContent.RefreshModLanguage().
GetTranslation() [3/3]
string Terraria.ModLoader.ModTranslation.GetTranslation (string culture)
Definition at line 52 of file ModTranslation.cs.
{
            return GetTranslation(GameCulture.FromName(culture).LegacyId);
        }
References Terraria.ModLoader.ModTranslation.GetTranslation().
IsDefault()
bool Terraria.ModLoader.ModTranslation.IsDefault ()
Definition at line 37 of file ModTranslation.cs.
{
            return translations[fallback] == Key;
        }
References Terraria.ModLoader.ModTranslation.fallback, Terraria.ModLoader.ModTranslation.Key, and Terraria.ModLoader.ModTranslation.translations.
Referenced by Terraria.ModLoader.ModPrefix.AutoDefaults(), Terraria.ModLoader.ModItem.AutoStaticDefaults(), Terraria.ModLoader.ModNPC.AutoStaticDefaults(), and Terraria.ModLoader.ModProjectile.AutoStaticDefaults().
SetDefault()
void Terraria.ModLoader.ModTranslation.SetDefault (string value)
Definition at line 21 of file ModTranslation.cs.
{
            AddTranslation(fallback, value);
        }
References Terraria.ModLoader.ModTranslation.AddTranslation(), and Terraria.ModLoader.ModTranslation.fallback.
Referenced by Terraria.ModLoader.ModPrefix.AutoDefaults(), Terraria.ModLoader.ModItem.AutoStaticDefaults(), Terraria.ModLoader.ModNPC.AutoStaticDefaults(), and Terraria.ModLoader.ModProjectile.AutoStaticDefaults().
Member Data Documentation
fallback
const int Terraria.ModLoader.ModTranslation.fallback = 1 static private
Definition at line 9 of file ModTranslation.cs.
Referenced by Terraria.ModLoader.ModTranslation.GetDefault(), Terraria.ModLoader.ModTranslation.GetTranslation(), Terraria.ModLoader.ModTranslation.IsDefault(), and Terraria.ModLoader.ModTranslation.SetDefault().
Key
readonly string Terraria.ModLoader.ModTranslation.Key
Definition at line 10 of file ModTranslation.cs.
Referenced by Terraria.ModLoader.Mod.AddTranslation(), Terraria.ModLoader.ModTranslation.IsDefault(), and Terraria.ModLoader.ModContent.RefreshModLanguage().
translations
Dictionary<int, string> Terraria.ModLoader.ModTranslation.translations private
Definition at line 11 of file ModTranslation.cs.
Referenced by Terraria.ModLoader.ModTranslation.AddTranslation(), Terraria.ModLoader.ModTranslation.GetTranslation(), and Terraria.ModLoader.ModTranslation.IsDefault().