tModLoader: Terraria.ModLoader.IO.ItemIO Class Reference
Terraria.ModLoader.IO.ItemIO Class Reference
Static Public Member Functions
static Item FromBase64 (string base64)
static void Load (Item item, TagCompound tag)
static Item Load (TagCompound tag)
static void LoadLegacy (Item item, BinaryReader reader, bool readStack=false, bool readFavorite=false)
static void LoadLegacyInventory (Item[] inv, BinaryReader reader, bool readStack=false, bool readFavorite=false)
static Item Receive (BinaryReader reader, bool readStack=false, bool readFavorite=false)
static void Receive (Item item, BinaryReader reader, bool readStack=false, bool readFavorite=false)
static void ReceiveModData (Item item, BinaryReader reader)
static TagCompound Save (Item item)
static void Send (Item item, BinaryWriter writer, bool writeStack=false, bool writeFavourite=false)
static void SendModData (Item item, BinaryWriter writer)
static string ToBase64 (Item item)
Detailed Description
Definition at line 10 of file ItemIO.cs.
Member Function Documentation
FromBase64()
static Item Terraria.ModLoader.IO.ItemIO.FromBase64 (string base64) static
Definition at line 316 of file ItemIO.cs.
{
            MemoryStream ms = new MemoryStream(Convert.FromBase64String(base64));
            return ItemIO.Load(TagIO.FromStream(ms, true));
        }
References Terraria.ModLoader.IO.TagIO.FromStream(), Terraria.ModLoader.Item, and Terraria.ModLoader.IO.ItemIO.Load().
Load() [1/2]
static void Terraria.ModLoader.IO.ItemIO.Load (Item item, TagCompound tag) static
Definition at line 55 of file ItemIO.cs.
        {
            string modName = tag.GetString("mod");
            if (modName == "") {
                item.netDefaults(0);
                return;
            }
            if (modName == "Terraria") {
                item.netDefaults(tag.GetInt("id"));
                if (tag.ContainsKey("legacyData"))
                    LoadLegacyModData(item, tag.GetByteArray("legacyData"), tag.GetBool("hasGlobalSaving"));
            }
            else {
                int type = ModLoader.GetMod(modName)?.ItemType(tag.GetString("name")) ?? 0;
                if (type > 0) {
                    item.netDefaults(type);
                    if (tag.ContainsKey("legacyData"))
                        LoadLegacyModData(item, tag.GetByteArray("legacyData"), tag.GetBool("hasGlobalSaving"));
                    else
                        item.modItem.Load(tag.GetCompound("data"));
                }
                else {
                    item.netDefaults(ModContent.ItemType<MysteryItem>());
                    ((MysteryItem)item.modItem).Setup(tag);
                }
            }
            if (tag.ContainsKey("modPrefixMod") && tag.ContainsKey("modPrefixName")) {
                string prefixMod = tag.GetString("modPrefixMod");
                string prefixName = tag.GetString("modPrefixName");
                item.Prefix(ModLoader.GetMod(prefixMod)?.PrefixType(prefixName) ?? 0);
            }
            else if (tag.ContainsKey("prefix")) {
                item.Prefix(tag.GetByte("prefix"));
            }
            item.stack = tag.Get<int?>("stack") ?? 1;
            item.favorited = tag.GetBool("fav");
            if (!(item.modItem is MysteryItem))
                LoadGlobals(item, tag.GetList<TagCompound>("globalData"));
        }
References Terraria.ModLoader.IO.TagCompound.ContainsKey(), Terraria.ModLoader.IO.TagCompound.GetBool(), Terraria.ModLoader.IO.TagCompound.GetByte(), Terraria.ModLoader.IO.TagCompound.GetByteArray(), Terraria.ModLoader.IO.TagCompound.GetCompound(), Terraria.ModLoader.IO.TagCompound.GetInt(), Terraria.ModLoader.ModLoader.GetMod(), Terraria.ModLoader.IO.TagCompound.GetString(), Terraria.ModLoader.Mod.ItemType(), and Terraria.ModLoader.Mod.PrefixType().
Referenced by Terraria.ModLoader.IO.ItemIO.FromBase64(), and Terraria.ModLoader.IO.ItemIO.Load().
Load() [2/2]
static Item Terraria.ModLoader.IO.ItemIO.Load (TagCompound tag) static
Definition at line 98 of file ItemIO.cs.
{
            var item = new Item();
            Load(item, tag);
            return item;
        }
References Terraria.ModLoader.Item, and Terraria.ModLoader.IO.ItemIO.Load().
LoadLegacy()
static void Terraria.ModLoader.IO.ItemIO.LoadLegacy (Item item, BinaryReader reader, bool readStack = false, bool readFavorite = false) static
Definition at line 199 of file ItemIO.cs.
{
            string modName = reader.ReadString();
            bool hasGlobalSaving = false;
            if (modName.Length == 0) {
                hasGlobalSaving = true;
                modName = reader.ReadString();
            }
            if (modName == "Terraria") {
                item.netDefaults(reader.ReadInt32());
                LoadLegacyModData(item, LegacyModData(item.type, reader, hasGlobalSaving), hasGlobalSaving);
            }
            else {
                string itemName = reader.ReadString();
                int type = ModLoader.GetMod(modName)?.ItemType(itemName) ?? 0;
                byte[] data = LegacyModData(type == 0 ? int.MaxValue : type, reader, hasGlobalSaving);
                if (type != 0) {
                    item.netDefaults(type);
                    LoadLegacyModData(item, data, hasGlobalSaving);
                }
                else {
                    item.netDefaults(ModContent.ItemType<MysteryItem>());
                    var tag = new TagCompound {
                        ["mod"] = modName,
                        ["name"] = itemName,
                        ["hasGlobalSaving"] = hasGlobalSaving,
                        ["legacyData"] = data
                    };
                    ((MysteryItem)item.modItem).Setup(tag);
                }
            }
            item.Prefix(reader.ReadByte());
            if (readStack)
                item.stack = reader.ReadInt32();
            if (readFavorite)
                item.favorited = reader.ReadBoolean();
        }
References Terraria.ModLoader.ModLoader.GetMod(), and Terraria.ModLoader.Mod.ItemType().
Referenced by Terraria.ModLoader.IO.ItemIO.LoadLegacyInventory().
LoadLegacyInventory()
static void Terraria.ModLoader.IO.ItemIO.LoadLegacyInventory (Item[] inv, BinaryReader reader, bool readStack = false, bool readFavorite = false) static
Definition at line 303 of file ItemIO.cs.
{
            int count = reader.ReadUInt16();
            for (int k = 0; k < count; k++) {
                LoadLegacy(inv[reader.ReadUInt16()], reader, readStack, readFavorite);
            }
        }
References Terraria.ModLoader.IO.ItemIO.LoadLegacy().
Receive() [1/2]
static Item Terraria.ModLoader.IO.ItemIO.Receive (BinaryReader reader, bool readStack = false, bool readFavorite = false) static
Definition at line 159 of file ItemIO.cs.
{
            var item = new Item();
            Receive(item, reader, readStack, readFavorite);
            return item;
        }
References Terraria.ModLoader.Item, and Terraria.ModLoader.IO.ItemIO.Receive().
Receive() [2/2]
static void Terraria.ModLoader.IO.ItemIO.Receive (Item item, BinaryReader reader, bool readStack = false, bool readFavorite = false) static
Definition at line 151 of file ItemIO.cs.
{
            item.netDefaults(reader.ReadInt16());
            item.Prefix(reader.ReadByte());
            if (readStack) item.stack = reader.ReadInt16();
            if (readFavorite) item.favorited = reader.ReadBoolean();
            ReceiveModData(item, reader);
        }
References Terraria.ModLoader.IO.ItemIO.ReceiveModData().
Referenced by Terraria.ModLoader.IO.ItemIO.Receive().
ReceiveModData()
static void Terraria.ModLoader.IO.ItemIO.ReceiveModData (Item item, BinaryReader reader) static
Definition at line 172 of file ItemIO.cs.
{
            if (item.IsAir) return;
            try {
                reader.SafeRead(r => item.modItem?.NetRecieve(r));
            }
            catch (IOException e) {
                if (FrameworkVersion.Framework == Framework.Mono) {
                    Logging.tML.Error(e);
                }
                Logging.tML.Error($"Above IOException error caused by {item.modItem.Name} from the {item.modItem.mod.Name} mod.");
            }
            foreach (var globalItem in ItemLoader.NetGlobals) {
                try {
                    reader.SafeRead(r => globalItem.Instance(item).NetReceive(item, r));
                }
                catch (IOException e) {
                    if (FrameworkVersion.Framework == Framework.Mono) {
                        Logging.tML.Error(e);
                    }
                    Logging.tML.Error($"Above IOException error caused by {globalItem.Name} from the {globalItem.mod.Name} mod while reading {item.Name}.");
                }
            }
        }
References Terraria.ModLoader.FrameworkVersion.Framework.
Referenced by Terraria.ModLoader.IO.ItemIO.Receive().
Save()
static TagCompound Terraria.ModLoader.IO.ItemIO.Save (Item item) static
Definition at line 18 of file ItemIO.cs.
{
            var tag = new TagCompound();
            if (item.type <= 0)
                return tag;
            if (item.modItem == null) {
                tag.Set("mod", "Terraria");
                tag.Set("id", item.netID);
            }
            else {
                tag.Set("mod", item.modItem.mod.Name);
                tag.Set("name", item.modItem.Name);
                tag.Set("data", item.modItem.Save());
            }
            if (item.prefix != 0 && item.prefix < PrefixID.Count)
                tag.Set("prefix", item.prefix);
            if (item.prefix >= PrefixID.Count) {
                ModPrefix modPrefix = ModPrefix.GetPrefix(item.prefix);
                if (modPrefix != null) {
                    tag.Set("modPrefixMod", modPrefix.mod.Name);
                    tag.Set("modPrefixName", modPrefix.Name);
                }
            }
            if (item.stack > 1)
                tag.Set("stack", item.stack);
            if (item.favorited)
                tag.Set("fav", true);
            tag.Set("globalData", SaveGlobals(item));
            return tag;
        }
References Terraria.ModLoader.ModPrefix.GetPrefix(), Terraria.ModLoader.ModPrefix.mod, Terraria.ModLoader.Mod.Name, and Terraria.ModLoader.ModPrefix.Name.
Referenced by Terraria.ModLoader.IO.ItemIO.ToBase64().
Send()
static void Terraria.ModLoader.IO.ItemIO.Send (Item item, BinaryWriter writer, bool writeStack = false, bool writeFavourite = false) static
Definition at line 143 of file ItemIO.cs.
{
            writer.Write((short)item.netID);
            writer.Write(item.prefix);
            if (writeStack) writer.Write((short)item.stack);
            if (writeFavourite) writer.Write(item.favorited);
            SendModData(item, writer);
        }
References Terraria.ModLoader.IO.ItemIO.SendModData().
SendModData()
static void Terraria.ModLoader.IO.ItemIO.SendModData (Item item, BinaryWriter writer) static
Definition at line 165 of file ItemIO.cs.
{
            if (item.IsAir) return;
            writer.SafeWrite(w => item.modItem?.NetSend(w));
            foreach (var globalItem in ItemLoader.NetGlobals)
                writer.SafeWrite(w => globalItem.Instance(item).NetSend(item, w));
        }
Referenced by Terraria.ModLoader.IO.ItemIO.Send().
ToBase64()
static string Terraria.ModLoader.IO.ItemIO.ToBase64 (Item item) static
Definition at line 310 of file ItemIO.cs.
{
            MemoryStream ms = new MemoryStream();
            TagIO.ToStream(ItemIO.Save(item), ms, true);
            return Convert.ToBase64String(ms.ToArray());
        }
References Terraria.ModLoader.IO.ItemIO.Save(), and Terraria.ModLoader.IO.TagIO.ToStream().