tModLoader: Terraria.ModLoader.NPCLoader Class Reference
Terraria.ModLoader.NPCLoader Class Reference
This serves as the central class from which NPC-related functions are carried out. It also stores a list of mod NPCs by ID.
Classes
class HookList
Static Public Member Functions
static void AI (NPC npc)
static void BossBag (NPC npc, ref int bagType)
static void BossHeadRotation (NPC npc, ref float rotation)
static void BossHeadSlot (NPC npc, ref int index)
static void BossHeadSpriteEffects (NPC npc, ref SpriteEffects spriteEffects)
static void BossLoot (NPC npc, ref string name, ref int potionType)
static void BuffTownNPC (ref float damageMult, ref int defense)
static ? bool CanBeHitByItem (NPC npc, Player player, Item item)
static ? bool CanBeHitByProjectile (NPC npc, Projectile projectile)
static bool CanChat (NPC npc, bool vanillaCanChat)
static bool CanGoToStatue (NPC npc, bool toKingStatue, bool vanillaCanGo)
static ? bool CanHitNPC (NPC npc, NPC target)
static bool CanHitPlayer (NPC npc, Player target, ref int cooldownSlot)
static void CanTownNPCSpawn (int numTownNPCs, int money)
static bool CheckActive (NPC npc)
static bool CheckConditions (int type)
static bool CheckDead (NPC npc)
static ? int ChooseSpawn (NPCSpawnInfo spawnInfo)
static void DrawEffects (NPC npc, ref Color drawColor)
static bool DrawHealthBar (NPC npc, ref float scale)
static void DrawTownAttackGun (NPC npc, ref float scale, ref int item, ref int closeness)
static void DrawTownAttackSwing (NPC npc, ref Texture2D item, ref int itemSize, ref float scale, ref Vector2 offset)
static void EditSpawnRange (Player player, ref int spawnRangeX, ref int spawnRangeY, ref int safeRangeX, ref int safeRangeY)
static void EditSpawnRate (Player player, ref int spawnRate, ref int maxSpawns)
static void FindFrame (NPC npc, int frameHeight)
static ? Color GetAlpha (NPC npc, Color lightColor)
static void GetChat (NPC npc, ref string chat)
static ModNPC GetNPC (int type)
Gets the ModNPC instance corresponding to the specified type.
static void HitEffect (NPC npc, int hitDirection, double damage)
static void ModifyHitByItem (NPC npc, Player player, Item item, ref int damage, ref float knockback, ref bool crit)
static void ModifyHitByProjectile (NPC npc, Projectile projectile, ref int damage, ref float knockback, ref bool crit, ref int hitDirection)
static void ModifyHitNPC (NPC npc, NPC target, ref int damage, ref float knockback, ref bool crit)
static void ModifyHitPlayer (NPC npc, Player target, ref int damage, ref bool crit)
static void NPCAI (NPC npc)
static void NPCLoot (NPC npc)
static void OnCatchNPC (NPC npc, Player player, Item item)
static void OnChatButtonClicked (bool firstButton)
static void OnGoToStatue (NPC npc, bool toKingStatue)
static void OnHitByItem (NPC npc, Player player, Item item, int damage, float knockback, bool crit)
static void OnHitByProjectile (NPC npc, Projectile projectile, int damage, float knockback, bool crit)
static void OnHitNPC (NPC npc, NPC target, int damage, float knockback, bool crit)
static void OnHitPlayer (NPC npc, Player target, int damage, bool crit)
static void PostAI (NPC npc)
static void PostDraw (NPC npc, SpriteBatch spriteBatch, Color drawColor)
static bool PreAI (NPC npc)
static bool PreChatButtonClicked (bool firstButton)
static bool PreDraw (NPC npc, SpriteBatch spriteBatch, Color drawColor)
static bool PreNPCLoot (NPC npc)
static void ReceiveExtraAI (NPC npc, BinaryReader reader)
static void ResetEffects (NPC npc)
static void ScaleExpertStats (NPC npc, int numPlayers, float bossLifeScale)
static void SendExtraAI (NPC npc, BinaryWriter writer)
static void SetChatButtons (ref string button, ref string button2)
static void SetupShop (int type, Chest shop, ref int nextSlot)
static void SetupTravelShop (int[] shop, ref int nextSlot)
static int SpawnNPC (int type, int tileX, int tileY)
static bool SpecialNPCLoot (NPC npc)
static bool StrikeNPC (NPC npc, ref double damage, int defense, ref float knockback, int hitDirection, ref bool crit)
static void TownNPCAttackCooldown (NPC npc, ref int cooldown, ref int randExtraCooldown)
static void TownNPCAttackMagic (NPC npc, ref float auraLightMultiplier)
static void TownNPCAttackProj (NPC npc, ref int projType, ref int attackDelay)
static void TownNPCAttackProjSpeed (NPC npc, ref float multiplier, ref float gravityCorrection, ref float randomOffset)
static void TownNPCAttackShoot (NPC npc, ref bool inBetweenShots)
static void TownNPCAttackStrength (NPC npc, ref int damage, ref float knockback)
static void TownNPCAttackSwing (NPC npc, ref int itemWidth, ref int itemHeight)
static string TownNPCName (int type)
static void UpdateLifeRegen (NPC npc, ref int damage)
static bool UsesPartyHat (NPC npc)
Static Public Attributes
static readonly IList< int > blockLoot = new List<int>()
Allows you to stop an NPC from dropping loot by adding item IDs to this list. This list will be cleared whenever NPCLoot ends. Useful for either removing an item or change the drop rate of an item in the NPC's loot table. To change the drop rate of an item, use the PreNPCLoot hook, spawn the item yourself, then add the item's ID to this list.
Properties
static int NPCCount [get]
Private Member Functions
delegate void DelegateBossHeadRotation (NPC npc, ref float rotation)
delegate void DelegateBossHeadSlot (NPC npc, ref int index)
delegate void DelegateBossHeadSpriteEffects (NPC npc, ref SpriteEffects spriteEffects)
delegate void DelegateBuffTownNPC (ref float damageMult, ref int defense)
delegate bool DelegateCanHitPlayer (NPC npc, Player target, ref int cooldownSlot)
delegate void DelegateDrawEffects (NPC npc, ref Color drawColor)
delegate? bool DelegateDrawHealthBar (NPC npc, byte bhPosition, ref float scale, ref Vector2 position)
delegate void DelegateDrawTownAttackGun (NPC npc, ref float scale, ref int item, ref int closeness)
delegate void DelegateDrawTownAttackSwing (NPC npc, ref Texture2D item, ref int itemSize, ref float scale, ref Vector2 offset)
delegate void DelegateEditSpawnRange (Player player, ref int spawnRangeX, ref int spawnRangeY, ref int safeRangeX, ref int safeRangeY)
delegate void DelegateEditSpawnRate (Player player, ref int spawnRate, ref int maxSpawns)
delegate void DelegateGetChat (NPC npc, ref string chat)
delegate void DelegateModifyHitByItem (NPC npc, Player player, Item item, ref int damage, ref float knockback, ref bool crit)
delegate void DelegateModifyHitByProjectile (NPC npc, Projectile projectile, ref int damage, ref float knockback, ref bool crit, ref int hitDirection)
delegate void DelegateModifyHitNPC (NPC npc, NPC target, ref int damage, ref float knockback, ref bool crit)
delegate void DelegateModifyHitPlayer (NPC npc, Player target, ref int damage, ref bool crit)
delegate void DelegateOnChatButtonClicked (NPC npc, bool firstButton)
delegate void DelegateSetupShop (int type, Chest shop, ref int nextSlot)
delegate void DelegateSetupTravelShop (int[] shop, ref int nextSlot)
delegate bool DelegateStrikeNPC (NPC npc, ref double damage, int defense, ref float knockback, int hitDirection, ref bool crit)
delegate void DelegateTownNPCAttackCooldown (NPC npc, ref int cooldown, ref int randExtraCooldown)
delegate void DelegateTownNPCAttackMagic (NPC npc, ref float auraLightMultiplier)
delegate void DelegateTownNPCAttackProj (NPC npc, ref int projType, ref int attackDelay)
delegate void DelegateTownNPCAttackProjSpeed (NPC npc, ref float multiplier, ref float gravityCorrection, ref float randomOffset)
delegate void DelegateTownNPCAttackShoot (NPC npc, ref bool inBetweenShots)
delegate void DelegateTownNPCAttackStrength (NPC npc, ref int damage, ref float knockback)
delegate void DelegateTownNPCAttackSwing (NPC npc, ref int itemWidth, ref int itemHeight)
delegate void DelegateUpdateLifeRegen (NPC npc, ref int damage)
Static Private Member Functions
static NPCLoader ()
static HookList AddHook< F > (Expression< Func< GlobalNPC, F > > func)
static void DrawHealthBar (NPC npc, Vector2 position, float scale)
static bool HasMethod (Type t, string method, params Type[] args)
Static Private Attributes
static HookList HookAI = AddHook<Action<NPC>>(g => g.AI)
static HookList HookBossHeadRotation = AddHook<DelegateBossHeadRotation>(g => g.BossHeadRotation)
static HookList HookBossHeadSlot = AddHook<DelegateBossHeadSlot>(g => g.BossHeadSlot)
static HookList HookBossHeadSpriteEffects = AddHook<DelegateBossHeadSpriteEffects>(g => g.BossHeadSpriteEffects)
static HookList HookBuffTownNPC = AddHook<DelegateBuffTownNPC>(g => g.BuffTownNPC)
static HookList HookCanBeHitByItem = AddHook<Func<NPC, Player, Item, bool?>>(g => g.CanBeHitByItem)
static HookList HookCanBeHitByProjectile = AddHook<Func<NPC, Projectile, bool?>>(g => g.CanBeHitByProjectile)
static HookList HookCanChat = AddHook<Func<NPC, bool?>>(g => g.CanChat)
static HookList HookCanGoToStatue = AddHook<Func<NPC, bool, bool?>>(g => g.CanGoToStatue)
static HookList HookCanHitNPC = AddHook<Func<NPC, NPC, bool?>>(g => g.CanHitNPC)
static HookList HookCanHitPlayer = AddHook<DelegateCanHitPlayer>(g => g.CanHitPlayer)
static HookList HookCheckActive = AddHook<Func<NPC, bool>>(g => g.CheckActive)
static HookList HookCheckDead = AddHook<Func<NPC, bool>>(g => g.CheckDead)
static HookList HookDrawBehind = AddHook<Action<NPC, int>>(g => g.DrawBehind)
static HookList HookDrawEffects = AddHook<DelegateDrawEffects>(g => g.DrawEffects)
static HookList HookDrawHealthBar = AddHook<DelegateDrawHealthBar>(g => g.DrawHealthBar)
static HookList HookDrawTownAttackGun = AddHook<DelegateDrawTownAttackGun>(g => g.DrawTownAttackGun)
static HookList HookDrawTownAttackSwing = AddHook<DelegateDrawTownAttackSwing>(g => g.DrawTownAttackSwing)
static HookList HookEditSpawnPool = AddHook<Action<Dictionary<int, float>, NPCSpawnInfo>>(g => g.EditSpawnPool)
static HookList HookEditSpawnRange = AddHook<DelegateEditSpawnRange>(g => g.EditSpawnRange)
static HookList HookEditSpawnRate = AddHook<DelegateEditSpawnRate>(g => g.EditSpawnRate)
static HookList HookFindFrame = AddHook<Action<NPC, int>>(g => g.FindFrame)
static HookList HookGetAlpha = AddHook<Func<NPC, Color, Color?>>(g => g.GetAlpha)
static HookList HookGetChat = AddHook<DelegateGetChat>(g => g.GetChat)
static HookList HookHitEffect = AddHook<Action<NPC, int, double>>(g => g.HitEffect)
static HookList HookModifyHitByItem = AddHook<DelegateModifyHitByItem>(g => g.ModifyHitByItem)
static HookList HookModifyHitByProjectile = AddHook<DelegateModifyHitByProjectile>(g => g.ModifyHitByProjectile)
static HookList HookModifyHitNPC = AddHook<DelegateModifyHitNPC>(g => g.ModifyHitNPC)
static HookList HookModifyHitPlayer = AddHook<DelegateModifyHitPlayer>(g => g.ModifyHitPlayer)
static HookList HookNPCLoot = AddHook<Action<NPC>>(g => g.NPCLoot)
static HookList HookOnCatchNPC = AddHook<Action<NPC, Player, Item>>(g => g.OnCatchNPC)
static HookList HookOnChatButtonClicked = AddHook<DelegateOnChatButtonClicked>(g => g.OnChatButtonClicked)
static HookList HookOnGoToStatue = AddHook<Action<NPC, bool>>(g => g.OnGoToStatue)
static HookList HookOnHitByItem = AddHook<Action<NPC, Player, Item, int, float, bool>>(g => g.OnHitByItem)
static HookList HookOnHitByProjectile = AddHook<Action<NPC, Projectile, int, float, bool>>(g => g.OnHitByProjectile)
static HookList HookOnHitNPC = AddHook<Action<NPC, NPC, int, float, bool>>(g => g.OnHitNPC)
static HookList HookOnHitPlayer = AddHook<Action<NPC, Player, int, bool>>(g => g.OnHitPlayer)
static HookList HookPostAI = AddHook<Action<NPC>>(g => g.PostAI)
static HookList HookPostDraw = AddHook<Action<NPC, SpriteBatch, Color>>(g => g.PostDraw)
static HookList HookPreAI = AddHook<Func<NPC, bool>>(g => g.PreAI)
static HookList HookPreChatButtonClicked = AddHook<Func<NPC, bool, bool>>(g => g.PreChatButtonClicked)
static HookList HookPreDraw = AddHook<Func<NPC, SpriteBatch, Color, bool>>(g => g.PreDraw)
static HookList HookPreNPCLoot = AddHook<Func<NPC, bool>>(g => g.PreNPCLoot)
static HookList HookResetEffects = AddHook<Action<NPC>>(g => g.ResetEffects)
static List< HookList > hooks = new List<HookList>()
static HookList HookScaleExpertStats = AddHook<Action<NPC, int, float>>(g => g.ScaleExpertStats)
static HookList HookSetDefaults = AddHook<Action<NPC>>(g => g.SetDefaults)
static HookList HookSetupShop = AddHook<DelegateSetupShop>(g => g.SetupShop)
static HookList HookSetupTravelShop = AddHook<DelegateSetupTravelShop>(g => g.SetupTravelShop)
static HookList HookSpawnNPC = AddHook<Action<int, int, int>>(g => g.SpawnNPC)
static HookList HookSpecialNPCLoot = AddHook<Func<NPC, bool>>(g => g.SpecialNPCLoot)
static HookList HookStrikeNPC = AddHook<DelegateStrikeNPC>(g => g.StrikeNPC)
static HookList HookTownNPCAttackCooldown = AddHook<DelegateTownNPCAttackCooldown>(g => g.TownNPCAttackCooldown)
static HookList HookTownNPCAttackMagic = AddHook<DelegateTownNPCAttackMagic>(g => g.TownNPCAttackMagic)
static HookList HookTownNPCAttackProj = AddHook<DelegateTownNPCAttackProj>(g => g.TownNPCAttackProj)
static HookList HookTownNPCAttackProjSpeed = AddHook<DelegateTownNPCAttackProjSpeed>(g => g.TownNPCAttackProjSpeed)
static HookList HookTownNPCAttackShoot = AddHook<DelegateTownNPCAttackShoot>(g => g.TownNPCAttackShoot)
static HookList HookTownNPCAttackStrength = AddHook<DelegateTownNPCAttackStrength>(g => g.TownNPCAttackStrength)
static HookList HookTownNPCAttackSwing = AddHook<DelegateTownNPCAttackSwing>(g => g.TownNPCAttackSwing)
static HookList HookUpdateLifeRegen = AddHook<DelegateUpdateLifeRegen>(g => g.UpdateLifeRegen)
static int nextNPC = NPCID.Count
static readonly int[] shopToNPC = new int[Main.MaxShopIDs - 1]
static int vanillaSkeletonCount = NPCID.Sets.Skeletons.Count
Detailed Description
This serves as the central class from which NPC-related functions are carried out. It also stores a list of mod NPCs by ID.
Definition at line 19 of file NPCLoader.cs.
Constructor & Destructor Documentation
NPCLoader()
static Terraria.ModLoader.NPCLoader.NPCLoader () static private
Definition at line 54 of file NPCLoader.cs.
{
            shopToNPC[1] = NPCID.Merchant;
            shopToNPC[2] = NPCID.ArmsDealer;
            shopToNPC[3] = NPCID.Dryad;
            shopToNPC[4] = NPCID.Demolitionist;
            shopToNPC[5] = NPCID.Clothier;
            shopToNPC[6] = NPCID.GoblinTinkerer;
            shopToNPC[7] = NPCID.Wizard;
            shopToNPC[8] = NPCID.Mechanic;
            shopToNPC[9] = NPCID.SantaClaus;
            shopToNPC[10] = NPCID.Truffle;
            shopToNPC[11] = NPCID.Steampunker;
            shopToNPC[12] = NPCID.DyeTrader;
            shopToNPC[13] = NPCID.PartyGirl;
            shopToNPC[14] = NPCID.Cyborg;
            shopToNPC[15] = NPCID.Painter;
            shopToNPC[16] = NPCID.WitchDoctor;
            shopToNPC[17] = NPCID.Pirate;
            shopToNPC[18] = NPCID.Stylist;
            shopToNPC[19] = NPCID.TravellingMerchant;
            shopToNPC[20] = NPCID.SkeletonMerchant;
            shopToNPC[21] = NPCID.DD2Bartender;
        }
References Terraria.ModLoader.NPCLoader.shopToNPC.
Member Function Documentation
AddHook< F >()
static HookList Terraria.ModLoader.NPCLoader.AddHook< F > (Expression< Func< GlobalNPC, F > > func) static private
Definition at line 48 of file NPCLoader.cs.
{
            var hook = new HookList(ModLoader.Method(func));
            hooks.Add(hook);
            return hook;
        }
References Terraria.ModLoader.NPCLoader.hooks.
AI()
static void Terraria.ModLoader.NPCLoader.AI (NPC npc) static
Definition at line 270 of file NPCLoader.cs.
{
            npc.modNPC?.AI();
            foreach (GlobalNPC g in HookAI.arr) {
                g.Instance(npc).AI(npc);
            }
        }
References Terraria.ModLoader.GlobalNPC.AI(), Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.NPCLoader.HookAI, and Terraria.ModLoader.GlobalNPC.Instance().
Referenced by Terraria.ModLoader.NPCLoader.NPCAI().
BossBag()
static void Terraria.ModLoader.NPCLoader.BossBag (NPC npc, ref int bagType) static
Definition at line 435 of file NPCLoader.cs.
{
            if (npc.modNPC != null) {
                bagType = npc.modNPC.bossBag;
            }
        }
BossHeadRotation()
static void Terraria.ModLoader.NPCLoader.BossHeadRotation (NPC npc, ref float rotation) static
Definition at line 654 of file NPCLoader.cs.
{
            npc.modNPC?.BossHeadRotation(ref rotation);
            foreach (GlobalNPC g in HookBossHeadRotation.arr) {
                g.Instance(npc).BossHeadRotation(npc, ref rotation);
            }
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.GlobalNPC.BossHeadRotation(), Terraria.ModLoader.NPCLoader.HookBossHeadRotation, and Terraria.ModLoader.GlobalNPC.Instance().
BossHeadSlot()
static void Terraria.ModLoader.NPCLoader.BossHeadSlot (NPC npc, ref int index) static
Definition at line 643 of file NPCLoader.cs.
{
            npc.modNPC?.BossHeadSlot(ref index);
            foreach (GlobalNPC g in HookBossHeadSlot.arr) {
                g.Instance(npc).BossHeadSlot(npc, ref index);
            }
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.GlobalNPC.BossHeadSlot(), Terraria.ModLoader.NPCLoader.HookBossHeadSlot, and Terraria.ModLoader.GlobalNPC.Instance().
BossHeadSpriteEffects()
static void Terraria.ModLoader.NPCLoader.BossHeadSpriteEffects (NPC npc, ref SpriteEffects spriteEffects) static
Definition at line 665 of file NPCLoader.cs.
{
            npc.modNPC?.BossHeadSpriteEffects(ref spriteEffects);
            foreach (GlobalNPC g in HookBossHeadSpriteEffects.arr) {
                g.Instance(npc).BossHeadSpriteEffects(npc, ref spriteEffects);
            }
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.GlobalNPC.BossHeadSpriteEffects(), Terraria.ModLoader.NPCLoader.HookBossHeadSpriteEffects, and Terraria.ModLoader.GlobalNPC.Instance().
BossLoot()
static void Terraria.ModLoader.NPCLoader.BossLoot (NPC npc, ref string name, ref int potionType) static
Definition at line 431 of file NPCLoader.cs.
{
            npc.modNPC?.BossLoot(ref name, ref potionType);
        }
BuffTownNPC()
static void Terraria.ModLoader.NPCLoader.BuffTownNPC (ref float damageMult, ref int defense) static
Definition at line 994 of file NPCLoader.cs.
{
            foreach (GlobalNPC g in HookBuffTownNPC.arr) {
                g.BuffTownNPC(ref damageMult, ref defense);
            }
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.GlobalNPC.BuffTownNPC(), and Terraria.ModLoader.NPCLoader.HookBuffTownNPC.
CanBeHitByItem()
static ? bool Terraria.ModLoader.NPCLoader.CanBeHitByItem (NPC npc, Player player, Item item) static
Definition at line 534 of file NPCLoader.cs.
{
            bool? flag = null;
            foreach (GlobalNPC g in HookCanBeHitByItem.arr) {
                bool? canHit = g.Instance(npc).CanBeHitByItem(npc, player, item);
                if (canHit.HasValue && !canHit.Value) {
                    return false;
                }
                if (canHit.HasValue) {
                    flag = canHit.Value;
                }
            }
            if (npc.modNPC != null) {
                bool? canHit = npc.modNPC.CanBeHitByItem(player, item);
                if (canHit.HasValue && !canHit.Value) {
                    return false;
                }
                if (canHit.HasValue) {
                    flag = canHit.Value;
                }
            }
            return flag;
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.GlobalNPC.CanBeHitByItem(), Terraria.ModLoader.NPCLoader.HookCanBeHitByItem, and Terraria.ModLoader.GlobalNPC.Instance().
CanBeHitByProjectile()
static ? bool Terraria.ModLoader.NPCLoader.CanBeHitByProjectile (NPC npc, Projectile projectile) static
Definition at line 580 of file NPCLoader.cs.
{
            bool? flag = null;
            foreach (GlobalNPC g in HookCanBeHitByProjectile.arr) {
                bool? canHit = g.Instance(npc).CanBeHitByProjectile(npc, projectile);
                if (canHit.HasValue && !canHit.Value) {
                    return false;
                }
                if (canHit.HasValue) {
                    flag = canHit.Value;
                }
            }
            if (npc.modNPC != null) {
                bool? canHit = npc.modNPC.CanBeHitByProjectile(projectile);
                if (canHit.HasValue && !canHit.Value) {
                    return false;
                }
                if (canHit.HasValue) {
                    flag = canHit.Value;
                }
            }
            return flag;
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.GlobalNPC.CanBeHitByProjectile(), Terraria.ModLoader.NPCLoader.HookCanBeHitByProjectile, and Terraria.ModLoader.GlobalNPC.Instance().
CanChat()
static bool Terraria.ModLoader.NPCLoader.CanChat (NPC npc, bool vanillaCanChat) static
Definition at line 861 of file NPCLoader.cs.
{
            bool defaultCanChat = npc.modNPC?.CanChat() ?? vanillaCanChat;
            foreach (GlobalNPC g in HookCanChat.arr) {
                bool? canChat = g.Instance(npc).CanChat(npc);
                if (canChat.HasValue) {
                    if (!canChat.Value) {
                        return false;
                    }
                    defaultCanChat = true;
                }
            }
            return defaultCanChat;
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.GlobalNPC.CanChat(), Terraria.ModLoader.NPCLoader.HookCanChat, and Terraria.ModLoader.GlobalNPC.Instance().
CanGoToStatue()
static bool Terraria.ModLoader.NPCLoader.CanGoToStatue (NPC npc, bool toKingStatue, bool vanillaCanGo) static
Definition at line 965 of file NPCLoader.cs.
{
            bool defaultCanGo = npc.modNPC?.CanGoToStatue(toKingStatue) ?? vanillaCanGo;
            foreach (GlobalNPC g in HookCanGoToStatue.arr) {
                bool? canGo = g.Instance(npc).CanGoToStatue(npc, toKingStatue);
                if (canGo.HasValue) {
                    if (!canGo.Value) {
                        return false;
                    }
                    defaultCanGo = true;
                }
            }
            return defaultCanGo;
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.GlobalNPC.CanGoToStatue(), Terraria.ModLoader.NPCLoader.HookCanGoToStatue, and Terraria.ModLoader.GlobalNPC.Instance().
CanHitNPC()
static ? bool Terraria.ModLoader.NPCLoader.CanHitNPC (NPC npc, NPC target) static
Definition at line 489 of file NPCLoader.cs.
{
            bool? flag = null;
            foreach (GlobalNPC g in HookCanHitNPC.arr) {
                bool? canHit = g.Instance(npc).CanHitNPC(npc, target);
                if (canHit.HasValue && !canHit.Value) {
                    return false;
                }
                if (canHit.HasValue) {
                    flag = canHit.Value;
                }
            }
            if (npc.modNPC != null) {
                bool? canHit = npc.modNPC.CanHitNPC(target);
                if (canHit.HasValue && !canHit.Value) {
                    return false;
                }
                if (canHit.HasValue) {
                    flag = canHit.Value;
                }
            }
            return flag;
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.GlobalNPC.CanHitNPC(), Terraria.ModLoader.NPCLoader.HookCanHitNPC, and Terraria.ModLoader.GlobalNPC.Instance().
CanHitPlayer()
static bool Terraria.ModLoader.NPCLoader.CanHitPlayer (NPC npc, Player target, ref int cooldownSlot) static
Definition at line 454 of file NPCLoader.cs.
{
            foreach (GlobalNPC g in HookCanHitPlayer.arr) {
                if (!g.Instance(npc).CanHitPlayer(npc, target, ref cooldownSlot)) {
                    return false;
                }
            }
            if (npc.modNPC != null) {
                return npc.modNPC.CanHitPlayer(target, ref cooldownSlot);
            }
            return true;
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.GlobalNPC.CanHitPlayer(), Terraria.ModLoader.NPCLoader.HookCanHitPlayer, and Terraria.ModLoader.GlobalNPC.Instance().
CanTownNPCSpawn()
static void Terraria.ModLoader.NPCLoader.CanTownNPCSpawn (int numTownNPCs, int money) static
Definition at line 835 of file NPCLoader.cs.
{
            foreach (ModNPC npc in npcs) {
                if (npc.npc.townNPC && NPC.TypeToHeadIndex(npc.npc.type) >= 0 && !NPC.AnyNPCs(npc.npc.type) &&
                    npc.CanTownNPCSpawn(numTownNPCs, money)) {
                    Main.townNPCCanSpawn[npc.npc.type] = true;
                    if (WorldGen.prioritizedTownNPC == 0) {
                        WorldGen.prioritizedTownNPC = npc.npc.type;
                    }
                }
            }
        }
References Terraria.ModLoader.ModNPC.CanTownNPCSpawn(), and Terraria.ModLoader.ModNPC.npc.
CheckActive()
static bool Terraria.ModLoader.NPCLoader.CheckActive (NPC npc) static
Definition at line 358 of file NPCLoader.cs.
{
            if (npc.modNPC != null && !npc.modNPC.CheckActive()) {
                return false;
            }
            foreach (GlobalNPC g in HookCheckActive.arr) {
                if (!g.Instance(npc).CheckActive(npc)) {
                    return false;
                }
            }
            return true;
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.GlobalNPC.CheckActive(), Terraria.ModLoader.NPCLoader.HookCheckActive, and Terraria.ModLoader.GlobalNPC.Instance().
CheckConditions()
static bool Terraria.ModLoader.NPCLoader.CheckConditions (int type) static
Definition at line 847 of file NPCLoader.cs.
{
            return GetNPC(type)?.CheckConditions(WorldGen.roomX1, WorldGen.roomX2, WorldGen.roomY1, WorldGen.roomY2) ?? true;
        }
References Terraria.ModLoader.ModNPC.CheckConditions(), and Terraria.ModLoader.NPCLoader.GetNPC().
CheckDead()
static bool Terraria.ModLoader.NPCLoader.CheckDead (NPC npc) static
Definition at line 372 of file NPCLoader.cs.
{
            bool result = true;
            if (npc.modNPC != null) {
                result = npc.modNPC.CheckDead();
            }
            foreach (GlobalNPC g in HookCheckDead.arr) {
                result &= g.Instance(npc).CheckDead(npc);
            }
            return result;
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.GlobalNPC.CheckDead(), Terraria.ModLoader.NPCLoader.HookCheckDead, and Terraria.ModLoader.GlobalNPC.Instance().
ChooseSpawn()
static ? int Terraria.ModLoader.NPCLoader.ChooseSpawn (NPCSpawnInfo spawnInfo) static
Definition at line 789 of file NPCLoader.cs.
{
            NPCSpawnHelper.Reset();
            NPCSpawnHelper.DoChecks(spawnInfo);
            IDictionary<int, float> pool = new Dictionary<int, float>();
            pool[0] = 1f;
            foreach (ModNPC npc in npcs) {
                float weight = npc.SpawnChance(spawnInfo);
                if (weight > 0f) {
                    pool[npc.npc.type] = weight;
                }
            }
            foreach (GlobalNPC g in HookEditSpawnPool.arr) {
                g.EditSpawnPool(pool, spawnInfo);
            }
            float totalWeight = 0f;
            foreach (int type in pool.Keys) {
                if (pool[type] < 0f) {
                    pool[type] = 0f;
                }
                totalWeight += pool[type];
            }
            float choice = (float)Main.rand.NextDouble() * totalWeight;
            foreach (int type in pool.Keys) {
                float weight = pool[type];
                if (choice < weight) {
                    return type;
                }
                choice -= weight;
            }
            return null;
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.GlobalNPC.EditSpawnPool(), Terraria.ModLoader.NPCLoader.HookEditSpawnPool, Terraria.ModLoader.ModNPC.npc, and Terraria.ModLoader.ModNPC.SpawnChance().
DelegateBossHeadRotation()
delegate void Terraria.ModLoader.NPCLoader.DelegateBossHeadRotation (NPC npc, ref float rotation) private
DelegateBossHeadSlot()
delegate void Terraria.ModLoader.NPCLoader.DelegateBossHeadSlot (NPC npc, ref int index) private
DelegateBossHeadSpriteEffects()
delegate void Terraria.ModLoader.NPCLoader.DelegateBossHeadSpriteEffects (NPC npc, ref SpriteEffects spriteEffects) private
DelegateBuffTownNPC()
delegate void Terraria.ModLoader.NPCLoader.DelegateBuffTownNPC (ref float damageMult, ref int defense) private
DelegateCanHitPlayer()
delegate bool Terraria.ModLoader.NPCLoader.DelegateCanHitPlayer (NPC npc, Player target, ref int cooldownSlot) private
DelegateDrawEffects()
delegate void Terraria.ModLoader.NPCLoader.DelegateDrawEffects (NPC npc, ref Color drawColor) private
DelegateDrawHealthBar()
delegate? bool Terraria.ModLoader.NPCLoader.DelegateDrawHealthBar (NPC npc, byte bhPosition, ref float scale, ref Vector2 position) private
DelegateDrawTownAttackGun()
delegate void Terraria.ModLoader.NPCLoader.DelegateDrawTownAttackGun (NPC npc, ref float scale, ref int item, ref int closeness) private
DelegateDrawTownAttackSwing()
delegate void Terraria.ModLoader.NPCLoader.DelegateDrawTownAttackSwing (NPC npc, ref Texture2D item, ref int itemSize, ref float scale, ref Vector2 offset) private
DelegateEditSpawnRange()
delegate void Terraria.ModLoader.NPCLoader.DelegateEditSpawnRange (Player player, ref int spawnRangeX, ref int spawnRangeY, ref int safeRangeX, ref int safeRangeY) private
DelegateEditSpawnRate()
delegate void Terraria.ModLoader.NPCLoader.DelegateEditSpawnRate (Player player, ref int spawnRate, ref int maxSpawns) private
DelegateGetChat()
delegate void Terraria.ModLoader.NPCLoader.DelegateGetChat (NPC npc, ref string chat) private
DelegateModifyHitByItem()
delegate void Terraria.ModLoader.NPCLoader.DelegateModifyHitByItem (NPC npc, Player player, Item item, ref int damage, ref float knockback, ref bool crit) private
DelegateModifyHitByProjectile()
delegate void Terraria.ModLoader.NPCLoader.DelegateModifyHitByProjectile (NPC npc, Projectile projectile, ref int damage, ref float knockback, ref bool crit, ref int hitDirection) private
DelegateModifyHitNPC()
delegate void Terraria.ModLoader.NPCLoader.DelegateModifyHitNPC (NPC npc, NPC target, ref int damage, ref float knockback, ref bool crit) private
DelegateModifyHitPlayer()
delegate void Terraria.ModLoader.NPCLoader.DelegateModifyHitPlayer (NPC npc, Player target, ref int damage, ref bool crit) private
DelegateOnChatButtonClicked()
delegate void Terraria.ModLoader.NPCLoader.DelegateOnChatButtonClicked (NPC npc, bool firstButton) private
DelegateSetupShop()
delegate void Terraria.ModLoader.NPCLoader.DelegateSetupShop (int type, Chest shop, ref int nextSlot) private
DelegateSetupTravelShop()
delegate void Terraria.ModLoader.NPCLoader.DelegateSetupTravelShop (int[] shop, ref int nextSlot) private
DelegateStrikeNPC()
delegate bool Terraria.ModLoader.NPCLoader.DelegateStrikeNPC (NPC npc, ref double damage, int defense, ref float knockback, int hitDirection, ref bool crit) private
DelegateTownNPCAttackCooldown()
delegate void Terraria.ModLoader.NPCLoader.DelegateTownNPCAttackCooldown (NPC npc, ref int cooldown, ref int randExtraCooldown) private
DelegateTownNPCAttackMagic()
delegate void Terraria.ModLoader.NPCLoader.DelegateTownNPCAttackMagic (NPC npc, ref float auraLightMultiplier) private
DelegateTownNPCAttackProj()
delegate void Terraria.ModLoader.NPCLoader.DelegateTownNPCAttackProj (NPC npc, ref int projType, ref int attackDelay) private
DelegateTownNPCAttackProjSpeed()
delegate void Terraria.ModLoader.NPCLoader.DelegateTownNPCAttackProjSpeed (NPC npc, ref float multiplier, ref float gravityCorrection, ref float randomOffset) private
DelegateTownNPCAttackShoot()
delegate void Terraria.ModLoader.NPCLoader.DelegateTownNPCAttackShoot (NPC npc, ref bool inBetweenShots) private
DelegateTownNPCAttackStrength()
delegate void Terraria.ModLoader.NPCLoader.DelegateTownNPCAttackStrength (NPC npc, ref int damage, ref float knockback) private
DelegateTownNPCAttackSwing()
delegate void Terraria.ModLoader.NPCLoader.DelegateTownNPCAttackSwing (NPC npc, ref int itemWidth, ref int itemHeight) private
DelegateUpdateLifeRegen()
delegate void Terraria.ModLoader.NPCLoader.DelegateUpdateLifeRegen (NPC npc, ref int damage) private
DrawEffects()
static void Terraria.ModLoader.NPCLoader.DrawEffects (NPC npc, ref Color drawColor) static
Definition at line 688 of file NPCLoader.cs.
{
            npc.modNPC?.DrawEffects(ref drawColor);
            foreach (GlobalNPC g in HookDrawEffects.arr) {
                g.Instance(npc).DrawEffects(npc, ref drawColor);
            }
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.GlobalNPC.DrawEffects(), Terraria.ModLoader.NPCLoader.HookDrawEffects, and Terraria.ModLoader.GlobalNPC.Instance().
DrawHealthBar() [1/2]
static bool Terraria.ModLoader.NPCLoader.DrawHealthBar (NPC npc, ref float scale) static
Definition at line 733 of file NPCLoader.cs.
{
            Vector2 position = new Vector2(npc.position.X + npc.width / 2, npc.position.Y + npc.gfxOffY);
            if (Main.HealthBarDrawSettings == 1) {
                position.Y += npc.height + 10f + Main.NPCAddHeight(npc.whoAmI);
            }
            else if (Main.HealthBarDrawSettings == 2) {
                position.Y -= 24f + Main.NPCAddHeight(npc.whoAmI) / 2f;
            }
            foreach (GlobalNPC g in HookDrawHealthBar.arr) {
                bool? result = g.Instance(npc).DrawHealthBar(npc, Main.HealthBarDrawSettings, ref scale, ref position);
                if (result.HasValue) {
                    if (result.Value) {
                        DrawHealthBar(npc, position, scale);
                    }
                    return false;
                }
            }
            if (NPCLoader.IsModNPC(npc)) {
                bool? result = npc.modNPC.DrawHealthBar(Main.HealthBarDrawSettings, ref scale, ref position);
                if (result.HasValue) {
                    if (result.Value) {
                        DrawHealthBar(npc, position, scale);
                    }
                    return false;
                }
            }
            return true;
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.GlobalNPC.DrawHealthBar(), Terraria.ModLoader.NPCLoader.DrawHealthBar(), Terraria.ModLoader.NPCLoader.HookDrawHealthBar, and Terraria.ModLoader.GlobalNPC.Instance().
Referenced by Terraria.ModLoader.NPCLoader.DrawHealthBar().
DrawHealthBar() [2/2]
static void Terraria.ModLoader.NPCLoader.DrawHealthBar (NPC npc, Vector2 position, float scale) static private
Definition at line 762 of file NPCLoader.cs.
{
            float alpha = Lighting.Brightness((int)(npc.Center.X / 16f), (int)(npc.Center.Y / 16f));
            Main.instance.DrawHealthBar(position.X, position.Y, npc.life, npc.lifeMax, alpha, scale);
        }
DrawTownAttackGun()
static void Terraria.ModLoader.NPCLoader.DrawTownAttackGun (NPC npc, ref float scale, ref int item, ref int closeness) static
Definition at line 1097 of file NPCLoader.cs.
{
            npc.modNPC?.DrawTownAttackGun(ref scale, ref item, ref closeness);
            foreach (GlobalNPC g in HookDrawTownAttackGun.arr) {
                g.Instance(npc).DrawTownAttackGun(npc, ref scale, ref item, ref closeness);
            }
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.GlobalNPC.DrawTownAttackGun(), Terraria.ModLoader.NPCLoader.HookDrawTownAttackGun, and Terraria.ModLoader.GlobalNPC.Instance().
DrawTownAttackSwing()
static void Terraria.ModLoader.NPCLoader.DrawTownAttackSwing (NPC npc, ref Texture2D item, ref int itemSize, ref float scale, ref Vector2 offset) static
Definition at line 1108 of file NPCLoader.cs.
{
            npc.modNPC?.DrawTownAttackSwing(ref item, ref itemSize, ref scale, ref offset);
            foreach (GlobalNPC g in HookDrawTownAttackSwing.arr) {
                g.Instance(npc).DrawTownAttackSwing(npc, ref item, ref itemSize, ref scale, ref offset);
            }
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.GlobalNPC.DrawTownAttackSwing(), Terraria.ModLoader.NPCLoader.HookDrawTownAttackSwing, and Terraria.ModLoader.GlobalNPC.Instance().
EditSpawnRange()
static void Terraria.ModLoader.NPCLoader.EditSpawnRange (Player player, ref int spawnRangeX, ref int spawnRangeY, ref int safeRangeX, ref int safeRangeY) static
Definition at line 780 of file NPCLoader.cs.
{
            foreach (GlobalNPC g in HookEditSpawnRange.arr) {
                g.EditSpawnRange(player, ref spawnRangeX, ref spawnRangeY, ref safeRangeX, ref safeRangeY);
            }
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.GlobalNPC.EditSpawnRange(), and Terraria.ModLoader.NPCLoader.HookEditSpawnRange.
EditSpawnRate()
static void Terraria.ModLoader.NPCLoader.EditSpawnRate (Player player, ref int spawnRate, ref int maxSpawns) static
Definition at line 770 of file NPCLoader.cs.
{
            foreach (GlobalNPC g in HookEditSpawnRate.arr) {
                g.EditSpawnRate(player, ref spawnRate, ref maxSpawns);
            }
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.GlobalNPC.EditSpawnRate(), and Terraria.ModLoader.NPCLoader.HookEditSpawnRate.
FindFrame()
static void Terraria.ModLoader.NPCLoader.FindFrame (NPC npc, int frameHeight) static
Definition at line 320 of file NPCLoader.cs.
{
            int type = npc.type;
            if (npc.modNPC != null && npc.modNPC.animationType > 0) {
                npc.type = npc.modNPC.animationType;
            }
            npc.VanillaFindFrame(frameHeight);
            npc.type = type;
            npc.modNPC?.FindFrame(frameHeight);
            foreach (GlobalNPC g in HookFindFrame.arr) {
                g.Instance(npc).FindFrame(npc, frameHeight);
            }
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.GlobalNPC.FindFrame(), Terraria.ModLoader.NPCLoader.HookFindFrame, and Terraria.ModLoader.GlobalNPC.Instance().
GetAlpha()
static ? Color Terraria.ModLoader.NPCLoader.GetAlpha (NPC npc, Color lightColor) static
Definition at line 675 of file NPCLoader.cs.
{
            foreach (GlobalNPC g in HookGetAlpha.arr) {
                Color? color = g.Instance(npc).GetAlpha(npc, lightColor);
                if (color.HasValue) {
                    return color.Value;
                }
            }
            return npc.modNPC?.GetAlpha(lightColor);
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.GlobalNPC.GetAlpha(), Terraria.ModLoader.NPCLoader.HookGetAlpha, and Terraria.ModLoader.GlobalNPC.Instance().
GetChat()
static void Terraria.ModLoader.NPCLoader.GetChat (NPC npc, ref string chat) static
Definition at line 880 of file NPCLoader.cs.
{
            if (npc.modNPC != null) {
                chat = npc.modNPC.GetChat();
            }
            else if (chat.Equals("")) {
                chat = Language.GetTextValue("tModLoader.DefaultTownNPCChat");
            }
            foreach (GlobalNPC g in HookGetChat.arr) {
                g.Instance(npc).GetChat(npc, ref chat);
            }
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.GlobalNPC.GetChat(), Terraria.ModLoader.NPCLoader.HookGetChat, and Terraria.ModLoader.GlobalNPC.Instance().
GetNPC()
static ModNPC Terraria.ModLoader.NPCLoader.GetNPC (int type) static
Gets the ModNPC instance corresponding to the specified type.
Parameters
type The type of the npc
Returns
The ModNPC instance in the npcs array, null if not found.
Definition at line 93 of file NPCLoader.cs.
{
            return type >= NPCID.Count && type < NPCCount ? npcs[type - NPCID.Count] : null;
        }
References Terraria.ModLoader.NPCLoader.NPCCount.
Referenced by Terraria.ModLoader.NPCLoader.CheckConditions(), Terraria.ModLoader.NPCLoader.SetupShop(), Terraria.ModLoader.NPCLoader.SpawnNPC(), and Terraria.ModLoader.NPCLoader.TownNPCName().
HasMethod()
static bool Terraria.ModLoader.NPCLoader.HasMethod (Type t, string method, params Type[] args) static private
Definition at line 1116 of file NPCLoader.cs.
{
            return t.GetMethod(method, args).DeclaringType != typeof(GlobalNPC);
        }
HitEffect()
static void Terraria.ModLoader.NPCLoader.HitEffect (NPC npc, int hitDirection, double damage) static
Definition at line 336 of file NPCLoader.cs.
{
            npc.VanillaHitEffect(hitDirection, damage);
            npc.modNPC?.HitEffect(hitDirection, damage);
            foreach (GlobalNPC g in HookHitEffect.arr) {
                g.Instance(npc).HitEffect(npc, hitDirection, damage);
            }
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.GlobalNPC.HitEffect(), Terraria.ModLoader.NPCLoader.HookHitEffect, and Terraria.ModLoader.GlobalNPC.Instance().
ModifyHitByItem()
static void Terraria.ModLoader.NPCLoader.ModifyHitByItem (NPC npc, Player player, Item item, ref int damage, ref float knockback, ref bool crit) static
Definition at line 560 of file NPCLoader.cs.
{
            npc.modNPC?.ModifyHitByItem(player, item, ref damage, ref knockback, ref crit);
            foreach (GlobalNPC g in HookModifyHitByItem.arr) {
                g.Instance(npc).ModifyHitByItem(npc, player, item, ref damage, ref knockback, ref crit);
            }
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.NPCLoader.HookModifyHitByItem, Terraria.ModLoader.GlobalNPC.Instance(), and Terraria.ModLoader.GlobalNPC.ModifyHitByItem().
ModifyHitByProjectile()
static void Terraria.ModLoader.NPCLoader.ModifyHitByProjectile (NPC npc, Projectile projectile, ref int damage, ref float knockback, ref bool crit, ref int hitDirection) static
Definition at line 606 of file NPCLoader.cs.
{
            npc.modNPC?.ModifyHitByProjectile(projectile, ref damage, ref knockback, ref crit, ref hitDirection);
            foreach (GlobalNPC g in HookModifyHitByProjectile.arr) {
                g.Instance(npc).ModifyHitByProjectile(npc, projectile, ref damage, ref knockback, ref crit, ref hitDirection);
            }
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.NPCLoader.HookModifyHitByProjectile, Terraria.ModLoader.GlobalNPC.Instance(), and Terraria.ModLoader.GlobalNPC.ModifyHitByProjectile().
ModifyHitNPC()
static void Terraria.ModLoader.NPCLoader.ModifyHitNPC (NPC npc, NPC target, ref int damage, ref float knockback, ref bool crit) static
Definition at line 515 of file NPCLoader.cs.
{
            npc.modNPC?.ModifyHitNPC(target, ref damage, ref knockback, ref crit);
            foreach (GlobalNPC g in HookModifyHitNPC.arr) {
                g.Instance(npc).ModifyHitNPC(npc, target, ref damage, ref knockback, ref crit);
            }
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.NPCLoader.HookModifyHitNPC, Terraria.ModLoader.GlobalNPC.Instance(), and Terraria.ModLoader.GlobalNPC.ModifyHitNPC().
ModifyHitPlayer()
static void Terraria.ModLoader.NPCLoader.ModifyHitPlayer (NPC npc, Player target, ref int damage, ref bool crit) static
Definition at line 469 of file NPCLoader.cs.
{
            npc.modNPC?.ModifyHitPlayer(target, ref damage, ref crit);
            foreach (GlobalNPC g in HookModifyHitPlayer.arr) {
                g.Instance(npc).ModifyHitPlayer(npc, target, ref damage, ref crit);
            }
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.NPCLoader.HookModifyHitPlayer, Terraria.ModLoader.GlobalNPC.Instance(), and Terraria.ModLoader.GlobalNPC.ModifyHitPlayer().
NPCAI()
static void Terraria.ModLoader.NPCLoader.NPCAI (NPC npc) static
Definition at line 239 of file NPCLoader.cs.
{
            if (PreAI(npc)) {
                int type = npc.type;
                bool useAiType = npc.modNPC != null && npc.modNPC.aiType > 0;
                if (useAiType) {
                    npc.type = npc.modNPC.aiType;
                }
                npc.VanillaAI();
                if (useAiType) {
                    npc.type = type;
                }
                AI(npc);
            }
            PostAI(npc);
        }
References Terraria.ModLoader.NPCLoader.AI(), Terraria.ModLoader.NPCLoader.PostAI(), and Terraria.ModLoader.NPCLoader.PreAI().
NPCLoot()
static void Terraria.ModLoader.NPCLoader.NPCLoot (NPC npc) static
Definition at line 422 of file NPCLoader.cs.
{
            npc.modNPC?.NPCLoot();
            foreach (GlobalNPC g in HookNPCLoot.arr) {
                g.Instance(npc).NPCLoot(npc);
            }
            blockLoot.Clear();
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.NPCLoader.blockLoot, Terraria.ModLoader.NPCLoader.HookNPCLoot, Terraria.ModLoader.GlobalNPC.Instance(), and Terraria.ModLoader.GlobalNPC.NPCLoot().
OnCatchNPC()
static void Terraria.ModLoader.NPCLoader.OnCatchNPC (NPC npc, Player player, Item item) static
Definition at line 443 of file NPCLoader.cs.
{
            npc.modNPC?.OnCatchNPC(player, item);
            foreach (GlobalNPC g in HookOnCatchNPC.arr) {
                g.Instance(npc).OnCatchNPC(npc, player, item);
            }
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.NPCLoader.HookOnCatchNPC, Terraria.ModLoader.GlobalNPC.Instance(), and Terraria.ModLoader.GlobalNPC.OnCatchNPC().
OnChatButtonClicked()
static void Terraria.ModLoader.NPCLoader.OnChatButtonClicked (bool firstButton) static
Definition at line 920 of file NPCLoader.cs.
{
            NPC npc = Main.npc[Main.LocalPlayer.talkNPC];
            bool shop = false;
            if (npc.modNPC != null) {
                npc.modNPC.OnChatButtonClicked(firstButton, ref shop);
                Main.PlaySound(SoundID.MenuTick);
                if (shop) {
                    Main.playerInventory = true;
                    Main.npcChatText = "";
                    Main.npcShop = Main.MaxShopIDs - 1;
                    Main.instance.shop[Main.npcShop].SetupShop(npc.type);
                }
            }
            foreach (GlobalNPC g in HookOnChatButtonClicked.arr) {
                g.Instance(npc).OnChatButtonClicked(npc, firstButton);
            }
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.NPCLoader.HookOnChatButtonClicked, Terraria.ModLoader.GlobalNPC.Instance(), Terraria.ModLoader.ModNPC.npc, and Terraria.ModLoader.GlobalNPC.OnChatButtonClicked().
OnGoToStatue()
static void Terraria.ModLoader.NPCLoader.OnGoToStatue (NPC npc, bool toKingStatue) static
Definition at line 983 of file NPCLoader.cs.
{
            npc.modNPC?.OnGoToStatue(toKingStatue);
            foreach (GlobalNPC g in HookOnGoToStatue.arr) {
                g.OnGoToStatue(npc, toKingStatue);
            }
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.NPCLoader.HookOnGoToStatue, and Terraria.ModLoader.GlobalNPC.OnGoToStatue().
OnHitByItem()
static void Terraria.ModLoader.NPCLoader.OnHitByItem (NPC npc, Player player, Item item, int damage, float knockback, bool crit) static
Definition at line 570 of file NPCLoader.cs.
{
            npc.modNPC?.OnHitByItem(player, item, damage, knockback, crit);
            foreach (GlobalNPC g in HookOnHitByItem.arr) {
                g.Instance(npc).OnHitByItem(npc, player, item, damage, knockback, crit);
            }
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.NPCLoader.HookOnHitByItem, Terraria.ModLoader.GlobalNPC.Instance(), and Terraria.ModLoader.GlobalNPC.OnHitByItem().
OnHitByProjectile()
static void Terraria.ModLoader.NPCLoader.OnHitByProjectile (NPC npc, Projectile projectile, int damage, float knockback, bool crit) static
Definition at line 616 of file NPCLoader.cs.
{
            npc.modNPC?.OnHitByProjectile(projectile, damage, knockback, crit);
            foreach (GlobalNPC g in HookOnHitByProjectile.arr) {
                g.Instance(npc).OnHitByProjectile(npc, projectile, damage, knockback, crit);
            }
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.NPCLoader.HookOnHitByProjectile, Terraria.ModLoader.GlobalNPC.Instance(), and Terraria.ModLoader.GlobalNPC.OnHitByProjectile().
OnHitNPC()
static void Terraria.ModLoader.NPCLoader.OnHitNPC (NPC npc, NPC target, int damage, float knockback, bool crit) static
Definition at line 525 of file NPCLoader.cs.
{
            npc.modNPC?.OnHitNPC(target, damage, knockback, crit);
            foreach (GlobalNPC g in HookOnHitNPC.arr) {
                g.Instance(npc).OnHitNPC(npc, target, damage, knockback, crit);
            }
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.NPCLoader.HookOnHitNPC, Terraria.ModLoader.GlobalNPC.Instance(), and Terraria.ModLoader.GlobalNPC.OnHitNPC().
OnHitPlayer()
static void Terraria.ModLoader.NPCLoader.OnHitPlayer (NPC npc, Player target, int damage, bool crit) static
Definition at line 479 of file NPCLoader.cs.
{
            npc.modNPC?.OnHitPlayer(target, damage, crit);
            foreach (GlobalNPC g in HookOnHitPlayer.arr) {
                g.Instance(npc).OnHitPlayer(npc, target, damage, crit);
            }
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.NPCLoader.HookOnHitPlayer, Terraria.ModLoader.GlobalNPC.Instance(), and Terraria.ModLoader.GlobalNPC.OnHitPlayer().
PostAI()
static void Terraria.ModLoader.NPCLoader.PostAI (NPC npc) static
Definition at line 280 of file NPCLoader.cs.
{
            npc.modNPC?.PostAI();
            foreach (GlobalNPC g in HookPostAI.arr) {
                g.Instance(npc).PostAI(npc);
            }
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.NPCLoader.HookPostAI, Terraria.ModLoader.GlobalNPC.Instance(), and Terraria.ModLoader.GlobalNPC.PostAI().
Referenced by Terraria.ModLoader.NPCLoader.NPCAI().
PostDraw()
static void Terraria.ModLoader.NPCLoader.PostDraw (NPC npc, SpriteBatch spriteBatch, Color drawColor) static
Definition at line 711 of file NPCLoader.cs.
{
            npc.modNPC?.PostDraw(spriteBatch, drawColor);
            foreach (GlobalNPC g in HookPostDraw.arr) {
                g.Instance(npc).PostDraw(npc, spriteBatch, drawColor);
            }
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.NPCLoader.HookPostDraw, Terraria.ModLoader.GlobalNPC.Instance(), and Terraria.ModLoader.GlobalNPC.PostDraw().
PreAI()
static bool Terraria.ModLoader.NPCLoader.PreAI (NPC npc) static
Definition at line 257 of file NPCLoader.cs.
{
            bool result = true;
            foreach (GlobalNPC g in HookPreAI.arr) {
                result &= g.Instance(npc).PreAI(npc);
            }
            if (result && npc.modNPC != null) {
                return npc.modNPC.PreAI();
            }
            return result;
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.NPCLoader.HookPreAI, Terraria.ModLoader.GlobalNPC.Instance(), and Terraria.ModLoader.GlobalNPC.PreAI().
Referenced by Terraria.ModLoader.NPCLoader.NPCAI().
PreChatButtonClicked()
static bool Terraria.ModLoader.NPCLoader.PreChatButtonClicked (bool firstButton) static
Definition at line 901 of file NPCLoader.cs.
{
            NPC npc = Main.npc[Main.LocalPlayer.talkNPC];
            bool result = true;
            foreach (GlobalNPC g in HookPreChatButtonClicked.arr) {
                result &= g.Instance(npc).PreChatButtonClicked(npc, firstButton);
            }
            if (!result) {
                Main.PlaySound(SoundID.MenuTick);
                return false;
            }
            return true;
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.NPCLoader.HookPreChatButtonClicked, Terraria.ModLoader.GlobalNPC.Instance(), Terraria.ModLoader.ModNPC.npc, and Terraria.ModLoader.GlobalNPC.PreChatButtonClicked().
PreDraw()
static bool Terraria.ModLoader.NPCLoader.PreDraw (NPC npc, SpriteBatch spriteBatch, Color drawColor) static
Definition at line 698 of file NPCLoader.cs.
{
            bool result = true;
            foreach (GlobalNPC g in HookPreDraw.arr) {
                result &= g.Instance(npc).PreDraw(npc, spriteBatch, drawColor);
            }
            if (result && npc.modNPC != null) {
                return npc.modNPC.PreDraw(spriteBatch, drawColor);
            }
            return result;
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.NPCLoader.HookPreDraw, Terraria.ModLoader.GlobalNPC.Instance(), and Terraria.ModLoader.GlobalNPC.PreDraw().
PreNPCLoot()
static bool Terraria.ModLoader.NPCLoader.PreNPCLoot (NPC npc) static
Definition at line 402 of file NPCLoader.cs.
{
            bool result = true;
            foreach (GlobalNPC g in HookPreNPCLoot.arr) {
                result &= g.Instance(npc).PreNPCLoot(npc);
            }
            if (result && npc.modNPC != null) {
                result = npc.modNPC.PreNPCLoot();
            }
            if (!result) {
                blockLoot.Clear();
                return false;
            }
            return true;
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.NPCLoader.blockLoot, Terraria.ModLoader.NPCLoader.HookPreNPCLoot, Terraria.ModLoader.GlobalNPC.Instance(), and Terraria.ModLoader.GlobalNPC.PreNPCLoot().
ReceiveExtraAI()
static void Terraria.ModLoader.NPCLoader.ReceiveExtraAI (NPC npc, BinaryReader reader) static
Definition at line 305 of file NPCLoader.cs.
{
            if (npc.modNPC != null) {
                byte[] extraAI = reader.ReadBytes(reader.ReadByte());
                if (extraAI.Length > 0) {
                    using (MemoryStream stream = new MemoryStream(extraAI)) {
                        using (BinaryReader modReader = new BinaryReader(stream)) {
                            npc.modNPC.ReceiveExtraAI(modReader);
                        }
                    }
                }
            }
        }
ResetEffects()
static void Terraria.ModLoader.NPCLoader.ResetEffects (NPC npc) static
Definition at line 231 of file NPCLoader.cs.
{
            npc.modNPC?.ResetEffects();
            foreach (GlobalNPC g in HookResetEffects.arr) {
                g.Instance(npc).ResetEffects(npc);
            }
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.NPCLoader.HookResetEffects, Terraria.ModLoader.GlobalNPC.Instance(), and Terraria.ModLoader.GlobalNPC.ResetEffects().
ScaleExpertStats()
static void Terraria.ModLoader.NPCLoader.ScaleExpertStats (NPC npc, int numPlayers, float bossLifeScale) static
Definition at line 221 of file NPCLoader.cs.
{
            npc.modNPC?.ScaleExpertStats(numPlayers, bossLifeScale);
            foreach (GlobalNPC g in HookScaleExpertStats.arr) {
                g.Instance(npc).ScaleExpertStats(npc, numPlayers, bossLifeScale);
            }
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.NPCLoader.HookScaleExpertStats, Terraria.ModLoader.GlobalNPC.Instance(), and Terraria.ModLoader.GlobalNPC.ScaleExpertStats().
SendExtraAI()
static void Terraria.ModLoader.NPCLoader.SendExtraAI (NPC npc, BinaryWriter writer) static
Definition at line 288 of file NPCLoader.cs.
{
            if (npc.modNPC != null) {
                byte[] data;
                using (MemoryStream stream = new MemoryStream()) {
                    using (BinaryWriter modWriter = new BinaryWriter(stream)) {
                        npc.modNPC.SendExtraAI(modWriter);
                        modWriter.Flush();
                        data = stream.ToArray();
                    }
                }
                writer.Write((byte)data.Length);
                if (data.Length > 0) {
                    writer.Write(data);
                }
            }
        }
SetChatButtons()
static void Terraria.ModLoader.NPCLoader.SetChatButtons (ref string button, ref string button2) static
Definition at line 892 of file NPCLoader.cs.
{
            if (Main.player[Main.myPlayer].talkNPC >= 0) {
                NPC npc = Main.npc[Main.player[Main.myPlayer].talkNPC];
                npc.modNPC?.SetChatButtons(ref button, ref button2);
            }
        }
References Terraria.ModLoader.ModNPC.npc.
SetupShop()
static void Terraria.ModLoader.NPCLoader.SetupShop (int type, Chest shop, ref int nextSlot) static
Definition at line 942 of file NPCLoader.cs.
{
            if (type < shopToNPC.Length) {
                type = shopToNPC[type];
            }
            else {
                GetNPC(type)?.SetupShop(shop, ref nextSlot);
            }
            foreach (GlobalNPC g in HookSetupShop.arr) {
                g.SetupShop(type, shop, ref nextSlot);
            }
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.NPCLoader.GetNPC(), Terraria.ModLoader.NPCLoader.HookSetupShop, Terraria.ModLoader.ModNPC.SetupShop(), Terraria.ModLoader.GlobalNPC.SetupShop(), and Terraria.ModLoader.NPCLoader.shopToNPC.
SetupTravelShop()
static void Terraria.ModLoader.NPCLoader.SetupTravelShop (int[] shop, ref int nextSlot) static
Definition at line 957 of file NPCLoader.cs.
{
            foreach (GlobalNPC g in HookSetupTravelShop.arr) {
                g.SetupTravelShop(shop, ref nextSlot);
            }
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.NPCLoader.HookSetupTravelShop, and Terraria.ModLoader.GlobalNPC.SetupTravelShop().
SpawnNPC()
static int Terraria.ModLoader.NPCLoader.SpawnNPC (int type, int tileX, int tileY) static
Definition at line 823 of file NPCLoader.cs.
{
            var npc = type >= NPCID.Count ?
                GetNPC(type).SpawnNPC(tileX, tileY) :
                NPC.NewNPC(tileX * 16 + 8, tileY * 16, type);
            foreach (GlobalNPC g in HookSpawnNPC.arr) {
                g.Instance(Main.npc[npc]).SpawnNPC(npc, tileX, tileY);
            }
            return npc;
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.NPCLoader.GetNPC(), Terraria.ModLoader.NPCLoader.HookSpawnNPC, Terraria.ModLoader.GlobalNPC.Instance(), Terraria.ModLoader.GlobalNPC.SpawnNPC(), and Terraria.ModLoader.ModNPC.SpawnNPC().
SpecialNPCLoot()
static bool Terraria.ModLoader.NPCLoader.SpecialNPCLoot (NPC npc) static
Definition at line 388 of file NPCLoader.cs.
{
            foreach (GlobalNPC g in HookSpecialNPCLoot.arr) {
                if (g.Instance(npc).SpecialNPCLoot(npc)) {
                    return true;
                }
            }
            if (npc.modNPC != null) {
                return npc.modNPC.SpecialNPCLoot();
            }
            return false;
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.NPCLoader.HookSpecialNPCLoot, Terraria.ModLoader.GlobalNPC.Instance(), and Terraria.ModLoader.GlobalNPC.SpecialNPCLoot().
StrikeNPC()
static bool Terraria.ModLoader.NPCLoader.StrikeNPC (NPC npc, ref double damage, int defense, ref float knockback, int hitDirection, ref bool crit) static
Definition at line 627 of file NPCLoader.cs.
{
            bool flag = true;
            if (npc.modNPC != null) {
                flag = npc.modNPC.StrikeNPC(ref damage, defense, ref knockback, hitDirection, ref crit);
            }
            foreach (GlobalNPC g in HookStrikeNPC.arr) {
                if (!g.Instance(npc).StrikeNPC(npc, ref damage, defense, ref knockback, hitDirection, ref crit)) {
                    flag = false;
                }
            }
            return flag;
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.NPCLoader.HookStrikeNPC, Terraria.ModLoader.GlobalNPC.Instance(), and Terraria.ModLoader.GlobalNPC.StrikeNPC().
TownNPCAttackCooldown()
static void Terraria.ModLoader.NPCLoader.TownNPCAttackCooldown (NPC npc, ref int cooldown, ref int randExtraCooldown) static
Definition at line 1029 of file NPCLoader.cs.
{
            npc.modNPC?.TownNPCAttackCooldown(ref cooldown, ref randExtraCooldown);
            foreach (GlobalNPC g in HookTownNPCAttackCooldown.arr) {
                g.Instance(npc).TownNPCAttackCooldown(npc, ref cooldown, ref randExtraCooldown);
            }
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.NPCLoader.HookTownNPCAttackCooldown, Terraria.ModLoader.GlobalNPC.Instance(), and Terraria.ModLoader.GlobalNPC.TownNPCAttackCooldown().
TownNPCAttackMagic()
static void Terraria.ModLoader.NPCLoader.TownNPCAttackMagic (NPC npc, ref float auraLightMultiplier) static
Definition at line 1075 of file NPCLoader.cs.
{
            npc.modNPC?.TownNPCAttackMagic(ref auraLightMultiplier);
            foreach (GlobalNPC g in HookTownNPCAttackMagic.arr) {
                g.Instance(npc).TownNPCAttackMagic(npc, ref auraLightMultiplier);
            }
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.NPCLoader.HookTownNPCAttackMagic, Terraria.ModLoader.GlobalNPC.Instance(), and Terraria.ModLoader.GlobalNPC.TownNPCAttackMagic().
TownNPCAttackProj()
static void Terraria.ModLoader.NPCLoader.TownNPCAttackProj (NPC npc, ref int projType, ref int attackDelay) static
Definition at line 1040 of file NPCLoader.cs.
{
            npc.modNPC?.TownNPCAttackProj(ref projType, ref attackDelay);
            foreach (GlobalNPC g in HookTownNPCAttackProj.arr) {
                g.Instance(npc).TownNPCAttackProj(npc, ref projType, ref attackDelay);
            }
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.NPCLoader.HookTownNPCAttackProj, Terraria.ModLoader.GlobalNPC.Instance(), and Terraria.ModLoader.GlobalNPC.TownNPCAttackProj().
TownNPCAttackProjSpeed()
static void Terraria.ModLoader.NPCLoader.TownNPCAttackProjSpeed (NPC npc, ref float multiplier, ref float gravityCorrection, ref float randomOffset) static
Definition at line 1052 of file NPCLoader.cs.
{
            npc.modNPC?.TownNPCAttackProjSpeed(ref multiplier, ref gravityCorrection, ref randomOffset);
            foreach (GlobalNPC g in HookTownNPCAttackProjSpeed.arr) {
                g.Instance(npc).TownNPCAttackProjSpeed(npc, ref multiplier, ref gravityCorrection, ref randomOffset);
            }
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.NPCLoader.HookTownNPCAttackProjSpeed, Terraria.ModLoader.GlobalNPC.Instance(), and Terraria.ModLoader.GlobalNPC.TownNPCAttackProjSpeed().
TownNPCAttackShoot()
static void Terraria.ModLoader.NPCLoader.TownNPCAttackShoot (NPC npc, ref bool inBetweenShots) static
Definition at line 1064 of file NPCLoader.cs.
{
            npc.modNPC?.TownNPCAttackShoot(ref inBetweenShots);
            foreach (GlobalNPC g in HookTownNPCAttackShoot.arr) {
                g.Instance(npc).TownNPCAttackShoot(npc, ref inBetweenShots);
            }
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.NPCLoader.HookTownNPCAttackShoot, Terraria.ModLoader.GlobalNPC.Instance(), and Terraria.ModLoader.GlobalNPC.TownNPCAttackShoot().
TownNPCAttackStrength()
static void Terraria.ModLoader.NPCLoader.TownNPCAttackStrength (NPC npc, ref int damage, ref float knockback) static
Definition at line 1018 of file NPCLoader.cs.
{
            npc.modNPC?.TownNPCAttackStrength(ref damage, ref knockback);
            foreach (GlobalNPC g in HookTownNPCAttackStrength.arr) {
                g.Instance(npc).TownNPCAttackStrength(npc, ref damage, ref knockback);
            }
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.NPCLoader.HookTownNPCAttackStrength, Terraria.ModLoader.GlobalNPC.Instance(), and Terraria.ModLoader.GlobalNPC.TownNPCAttackStrength().
TownNPCAttackSwing()
static void Terraria.ModLoader.NPCLoader.TownNPCAttackSwing (NPC npc, ref int itemWidth, ref int itemHeight) static
Definition at line 1086 of file NPCLoader.cs.
{
            npc.modNPC?.TownNPCAttackSwing(ref itemWidth, ref itemHeight);
            foreach (GlobalNPC g in HookTownNPCAttackSwing.arr) {
                g.Instance(npc).TownNPCAttackSwing(npc, ref itemWidth, ref itemHeight);
            }
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.NPCLoader.HookTownNPCAttackSwing, Terraria.ModLoader.GlobalNPC.Instance(), and Terraria.ModLoader.GlobalNPC.TownNPCAttackSwing().
TownNPCName()
static string Terraria.ModLoader.NPCLoader.TownNPCName (int type) static
Definition at line 851 of file NPCLoader.cs.
{
            return GetNPC(type)?.TownNPCName() ?? "";
        }
References Terraria.ModLoader.NPCLoader.GetNPC(), and Terraria.ModLoader.ModNPC.TownNPCName().
UpdateLifeRegen()
static void Terraria.ModLoader.NPCLoader.UpdateLifeRegen (NPC npc, ref int damage) static
Definition at line 348 of file NPCLoader.cs.
{
            npc.modNPC?.UpdateLifeRegen(ref damage);
            foreach (GlobalNPC g in HookUpdateLifeRegen.arr) {
                g.Instance(npc).UpdateLifeRegen(npc, ref damage);
            }
        }
References Terraria.ModLoader.NPCLoader.HookList.arr, Terraria.ModLoader.NPCLoader.HookUpdateLifeRegen, Terraria.ModLoader.GlobalNPC.Instance(), and Terraria.ModLoader.GlobalNPC.UpdateLifeRegen().
UsesPartyHat()
static bool Terraria.ModLoader.NPCLoader.UsesPartyHat (NPC npc) static
Definition at line 855 of file NPCLoader.cs.
{
            return npc.modNPC?.UsesPartyHat() ?? true;
        }
Member Data Documentation
blockLoot
readonly IList<int> Terraria.ModLoader.NPCLoader.blockLoot = new List<int>() static
Allows you to stop an NPC from dropping loot by adding item IDs to this list. This list will be cleared whenever NPCLoot ends. Useful for either removing an item or change the drop rate of an item in the NPC's loot table. To change the drop rate of an item, use the PreNPCLoot hook, spawn the item yourself, then add the item's ID to this list.
Definition at line 34 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.NPCLoot(), Terraria.ModLoader.NPCLoader.PreNPCLoot(), and Terraria.ModLoader.ItemLoader.PreOpenVanillaBag().
HookAI
HookList Terraria.ModLoader.NPCLoader.HookAI = AddHook<Action<NPC>>(g => g.AI) static private
Definition at line 268 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.AI().
HookBossHeadRotation
HookList Terraria.ModLoader.NPCLoader.HookBossHeadRotation = AddHook<DelegateBossHeadRotation>(g => g.BossHeadRotation) static private
Definition at line 652 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.BossHeadRotation().
HookBossHeadSlot
HookList Terraria.ModLoader.NPCLoader.HookBossHeadSlot = AddHook<DelegateBossHeadSlot>(g => g.BossHeadSlot) static private
Definition at line 641 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.BossHeadSlot().
HookBossHeadSpriteEffects
HookList Terraria.ModLoader.NPCLoader.HookBossHeadSpriteEffects = AddHook<DelegateBossHeadSpriteEffects>(g => g.BossHeadSpriteEffects) static private
Definition at line 663 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.BossHeadSpriteEffects().
HookBuffTownNPC
HookList Terraria.ModLoader.NPCLoader.HookBuffTownNPC = AddHook<DelegateBuffTownNPC>(g => g.BuffTownNPC) static private
Definition at line 992 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.BuffTownNPC().
HookCanBeHitByItem
HookList Terraria.ModLoader.NPCLoader.HookCanBeHitByItem = AddHook<Func<NPC, Player, Item, bool?>>(g => g.CanBeHitByItem) static private
Definition at line 532 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.CanBeHitByItem().
HookCanBeHitByProjectile
HookList Terraria.ModLoader.NPCLoader.HookCanBeHitByProjectile = AddHook<Func<NPC, Projectile, bool?>>(g => g.CanBeHitByProjectile) static private
Definition at line 578 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.CanBeHitByProjectile().
HookCanChat
HookList Terraria.ModLoader.NPCLoader.HookCanChat = AddHook<Func<NPC, bool?>>(g => g.CanChat) static private
Definition at line 859 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.CanChat().
HookCanGoToStatue
HookList Terraria.ModLoader.NPCLoader.HookCanGoToStatue = AddHook<Func<NPC, bool, bool?>>(g => g.CanGoToStatue) static private
Definition at line 963 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.CanGoToStatue().
HookCanHitNPC
HookList Terraria.ModLoader.NPCLoader.HookCanHitNPC = AddHook<Func<NPC, NPC, bool?>>(g => g.CanHitNPC) static private
Definition at line 487 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.CanHitNPC().
HookCanHitPlayer
HookList Terraria.ModLoader.NPCLoader.HookCanHitPlayer = AddHook<DelegateCanHitPlayer>(g => g.CanHitPlayer) static private
Definition at line 452 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.CanHitPlayer().
HookCheckActive
HookList Terraria.ModLoader.NPCLoader.HookCheckActive = AddHook<Func<NPC, bool>>(g => g.CheckActive) static private
Definition at line 356 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.CheckActive().
HookCheckDead
HookList Terraria.ModLoader.NPCLoader.HookCheckDead = AddHook<Func<NPC, bool>>(g => g.CheckDead) static private
Definition at line 370 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.CheckDead().
HookDrawBehind
HookList Terraria.ModLoader.NPCLoader.HookDrawBehind = AddHook<Action<NPC, int>>(g => g.DrawBehind) static private
Definition at line 719 of file NPCLoader.cs.
HookDrawEffects
HookList Terraria.ModLoader.NPCLoader.HookDrawEffects = AddHook<DelegateDrawEffects>(g => g.DrawEffects) static private
Definition at line 686 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.DrawEffects().
HookDrawHealthBar
HookList Terraria.ModLoader.NPCLoader.HookDrawHealthBar = AddHook<DelegateDrawHealthBar>(g => g.DrawHealthBar) static private
Definition at line 731 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.DrawHealthBar().
HookDrawTownAttackGun
HookList Terraria.ModLoader.NPCLoader.HookDrawTownAttackGun = AddHook<DelegateDrawTownAttackGun>(g => g.DrawTownAttackGun) static private
Definition at line 1095 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.DrawTownAttackGun().
HookDrawTownAttackSwing
HookList Terraria.ModLoader.NPCLoader.HookDrawTownAttackSwing = AddHook<DelegateDrawTownAttackSwing>(g => g.DrawTownAttackSwing) static private
Definition at line 1106 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.DrawTownAttackSwing().
HookEditSpawnPool
HookList Terraria.ModLoader.NPCLoader.HookEditSpawnPool = AddHook<Action<Dictionary<int, float>, NPCSpawnInfo>>(g => g.EditSpawnPool) static private
Definition at line 787 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.ChooseSpawn().
HookEditSpawnRange
HookList Terraria.ModLoader.NPCLoader.HookEditSpawnRange = AddHook<DelegateEditSpawnRange>(g => g.EditSpawnRange) static private
Definition at line 778 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.EditSpawnRange().
HookEditSpawnRate
HookList Terraria.ModLoader.NPCLoader.HookEditSpawnRate = AddHook<DelegateEditSpawnRate>(g => g.EditSpawnRate) static private
Definition at line 768 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.EditSpawnRate().
HookFindFrame
HookList Terraria.ModLoader.NPCLoader.HookFindFrame = AddHook<Action<NPC, int>>(g => g.FindFrame) static private
Definition at line 318 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.FindFrame().
HookGetAlpha
HookList Terraria.ModLoader.NPCLoader.HookGetAlpha = AddHook<Func<NPC, Color, Color?>>(g => g.GetAlpha) static private
Definition at line 673 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.GetAlpha().
HookGetChat
HookList Terraria.ModLoader.NPCLoader.HookGetChat = AddHook<DelegateGetChat>(g => g.GetChat) static private
Definition at line 878 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.GetChat().
HookHitEffect
HookList Terraria.ModLoader.NPCLoader.HookHitEffect = AddHook<Action<NPC, int, double>>(g => g.HitEffect) static private
Definition at line 334 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.HitEffect().
HookModifyHitByItem
HookList Terraria.ModLoader.NPCLoader.HookModifyHitByItem = AddHook<DelegateModifyHitByItem>(g => g.ModifyHitByItem) static private
Definition at line 558 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.ModifyHitByItem().
HookModifyHitByProjectile
HookList Terraria.ModLoader.NPCLoader.HookModifyHitByProjectile = AddHook<DelegateModifyHitByProjectile>(g => g.ModifyHitByProjectile) static private
Definition at line 604 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.ModifyHitByProjectile().
HookModifyHitNPC
HookList Terraria.ModLoader.NPCLoader.HookModifyHitNPC = AddHook<DelegateModifyHitNPC>(g => g.ModifyHitNPC) static private
Definition at line 513 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.ModifyHitNPC().
HookModifyHitPlayer
HookList Terraria.ModLoader.NPCLoader.HookModifyHitPlayer = AddHook<DelegateModifyHitPlayer>(g => g.ModifyHitPlayer) static private
Definition at line 467 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.ModifyHitPlayer().
HookNPCLoot
HookList Terraria.ModLoader.NPCLoader.HookNPCLoot = AddHook<Action<NPC>>(g => g.NPCLoot) static private
Definition at line 420 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.NPCLoot().
HookOnCatchNPC
HookList Terraria.ModLoader.NPCLoader.HookOnCatchNPC = AddHook<Action<NPC, Player, Item>>(g => g.OnCatchNPC) static private
Definition at line 441 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.OnCatchNPC().
HookOnChatButtonClicked
HookList Terraria.ModLoader.NPCLoader.HookOnChatButtonClicked = AddHook<DelegateOnChatButtonClicked>(g => g.OnChatButtonClicked) static private
Definition at line 918 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.OnChatButtonClicked().
HookOnGoToStatue
HookList Terraria.ModLoader.NPCLoader.HookOnGoToStatue = AddHook<Action<NPC, bool>>(g => g.OnGoToStatue) static private
Definition at line 981 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.OnGoToStatue().
HookOnHitByItem
HookList Terraria.ModLoader.NPCLoader.HookOnHitByItem = AddHook<Action<NPC, Player, Item, int, float, bool>>(g => g.OnHitByItem) static private
Definition at line 568 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.OnHitByItem().
HookOnHitByProjectile
HookList Terraria.ModLoader.NPCLoader.HookOnHitByProjectile = AddHook<Action<NPC, Projectile, int, float, bool>>(g => g.OnHitByProjectile) static private
Definition at line 614 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.OnHitByProjectile().
HookOnHitNPC
HookList Terraria.ModLoader.NPCLoader.HookOnHitNPC = AddHook<Action<NPC, NPC, int, float, bool>>(g => g.OnHitNPC) static private
Definition at line 523 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.OnHitNPC().
HookOnHitPlayer
HookList Terraria.ModLoader.NPCLoader.HookOnHitPlayer = AddHook<Action<NPC, Player, int, bool>>(g => g.OnHitPlayer) static private
Definition at line 477 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.OnHitPlayer().
HookPostAI
HookList Terraria.ModLoader.NPCLoader.HookPostAI = AddHook<Action<NPC>>(g => g.PostAI) static private
Definition at line 278 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.PostAI().
HookPostDraw
HookList Terraria.ModLoader.NPCLoader.HookPostDraw = AddHook<Action<NPC, SpriteBatch, Color>>(g => g.PostDraw) static private
Definition at line 709 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.PostDraw().
HookPreAI
HookList Terraria.ModLoader.NPCLoader.HookPreAI = AddHook<Func<NPC, bool>>(g => g.PreAI) static private
Definition at line 255 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.PreAI().
HookPreChatButtonClicked
HookList Terraria.ModLoader.NPCLoader.HookPreChatButtonClicked = AddHook<Func<NPC, bool, bool>>(g => g.PreChatButtonClicked) static private
Definition at line 899 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.PreChatButtonClicked().
HookPreDraw
HookList Terraria.ModLoader.NPCLoader.HookPreDraw = AddHook<Func<NPC, SpriteBatch, Color, bool>>(g => g.PreDraw) static private
Definition at line 696 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.PreDraw().
HookPreNPCLoot
HookList Terraria.ModLoader.NPCLoader.HookPreNPCLoot = AddHook<Func<NPC, bool>>(g => g.PreNPCLoot) static private
Definition at line 400 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.PreNPCLoot().
HookResetEffects
HookList Terraria.ModLoader.NPCLoader.HookResetEffects = AddHook<Action<NPC>>(g => g.ResetEffects) static private
Definition at line 229 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.ResetEffects().
hooks
List<HookList> Terraria.ModLoader.NPCLoader.hooks = new List<HookList>() static private
Definition at line 46 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.AddHook< F >().
HookScaleExpertStats
HookList Terraria.ModLoader.NPCLoader.HookScaleExpertStats = AddHook<Action<NPC, int, float>>(g => g.ScaleExpertStats) static private
Definition at line 219 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.ScaleExpertStats().
HookSetDefaults
HookList Terraria.ModLoader.NPCLoader.HookSetDefaults = AddHook<Action<NPC>>(g => g.SetDefaults) static private
Definition at line 190 of file NPCLoader.cs.
HookSetupShop
HookList Terraria.ModLoader.NPCLoader.HookSetupShop = AddHook<DelegateSetupShop>(g => g.SetupShop) static private
Definition at line 940 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.SetupShop().
HookSetupTravelShop
HookList Terraria.ModLoader.NPCLoader.HookSetupTravelShop = AddHook<DelegateSetupTravelShop>(g => g.SetupTravelShop) static private
Definition at line 955 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.SetupTravelShop().
HookSpawnNPC
HookList Terraria.ModLoader.NPCLoader.HookSpawnNPC = AddHook<Action<int, int, int>>(g => g.SpawnNPC) static private
Definition at line 821 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.SpawnNPC().
HookSpecialNPCLoot
HookList Terraria.ModLoader.NPCLoader.HookSpecialNPCLoot = AddHook<Func<NPC, bool>>(g => g.SpecialNPCLoot) static private
Definition at line 386 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.SpecialNPCLoot().
HookStrikeNPC
HookList Terraria.ModLoader.NPCLoader.HookStrikeNPC = AddHook<DelegateStrikeNPC>(g => g.StrikeNPC) static private
Definition at line 625 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.StrikeNPC().
HookTownNPCAttackCooldown
HookList Terraria.ModLoader.NPCLoader.HookTownNPCAttackCooldown = AddHook<DelegateTownNPCAttackCooldown>(g => g.TownNPCAttackCooldown) static private
Definition at line 1027 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.TownNPCAttackCooldown().
HookTownNPCAttackMagic
HookList Terraria.ModLoader.NPCLoader.HookTownNPCAttackMagic = AddHook<DelegateTownNPCAttackMagic>(g => g.TownNPCAttackMagic) static private
Definition at line 1073 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.TownNPCAttackMagic().
HookTownNPCAttackProj
HookList Terraria.ModLoader.NPCLoader.HookTownNPCAttackProj = AddHook<DelegateTownNPCAttackProj>(g => g.TownNPCAttackProj) static private
Definition at line 1038 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.TownNPCAttackProj().
HookTownNPCAttackProjSpeed
HookList Terraria.ModLoader.NPCLoader.HookTownNPCAttackProjSpeed = AddHook<DelegateTownNPCAttackProjSpeed>(g => g.TownNPCAttackProjSpeed) static private
Definition at line 1050 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.TownNPCAttackProjSpeed().
HookTownNPCAttackShoot
HookList Terraria.ModLoader.NPCLoader.HookTownNPCAttackShoot = AddHook<DelegateTownNPCAttackShoot>(g => g.TownNPCAttackShoot) static private
Definition at line 1062 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.TownNPCAttackShoot().
HookTownNPCAttackStrength
HookList Terraria.ModLoader.NPCLoader.HookTownNPCAttackStrength = AddHook<DelegateTownNPCAttackStrength>(g => g.TownNPCAttackStrength) static private
Definition at line 1016 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.TownNPCAttackStrength().
HookTownNPCAttackSwing
HookList Terraria.ModLoader.NPCLoader.HookTownNPCAttackSwing = AddHook<DelegateTownNPCAttackSwing>(g => g.TownNPCAttackSwing) static private
Definition at line 1084 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.TownNPCAttackSwing().
HookUpdateLifeRegen
HookList Terraria.ModLoader.NPCLoader.HookUpdateLifeRegen = AddHook<DelegateUpdateLifeRegen>(g => g.UpdateLifeRegen) static private
Definition at line 346 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.UpdateLifeRegen().
nextNPC
int Terraria.ModLoader.NPCLoader.nextNPC = NPCID.Count static private
Definition at line 22 of file NPCLoader.cs.
shopToNPC
readonly int [] Terraria.ModLoader.NPCLoader.shopToNPC = new int[Main.MaxShopIDs - 1] static private
Definition at line 30 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.NPCLoader(), and Terraria.ModLoader.NPCLoader.SetupShop().
vanillaSkeletonCount
int Terraria.ModLoader.NPCLoader.vanillaSkeletonCount = NPCID.Sets.Skeletons.Count static private
Definition at line 29 of file NPCLoader.cs.
Property Documentation
NPCCount
int Terraria.ModLoader.NPCLoader.NPCCount static get
Definition at line 86 of file NPCLoader.cs.
Referenced by Terraria.ModLoader.NPCLoader.GetNPC().