tModLoader: Terraria.ModLoader.TileLoader Class Reference
Terraria.ModLoader.TileLoader Class Reference
This serves as the central class from which tile-related functions are supported and carried out.
Static Public Member Functions
static void AdjTiles (Player player, int type)
static void AnimateTiles ()
static int AutoSelect (int i, int j, Player player)
static bool CanDropAcorn (int type)
static bool CanExplode (int i, int j)
static bool CanGrowModCactus (int type)
static bool CanGrowModPalmTree (int type)
static bool CanGrowModTree (int type)
static bool CanKillTile (int i, int j, int type, ref bool blockDamaged)
static bool CanPlace (int i, int j, int type)
static void ChangeWaterfallStyle (int type, ref int style)
static void CheckModTile (int i, int j, int type)
static int CloseDoorID (Tile tile)
static bool CreateDust (int i, int j, int type, ref int dustType)
static bool Dangersense (int i, int j, int type, Player player)
static void DisableSmartCursor (Tile tile, ref bool disable)
static void DisableSmartInteract (Tile tile, ref bool disable)
static void DrawEffects (int i, int j, int type, SpriteBatch spriteBatch, ref Color drawColor, ref int nextSpecialDrawIndex)
static bool Drop (int i, int j, int type)
static void DropCritterChance (int i, int j, int type, ref int wormChance, ref int grassHopperChance, ref int jungleGrubChance)
static void DropPalmTreeWood (int type, ref int wood)
static void DropTreeWood (int type, ref int wood)
static void FixSmartInteractCoords (int type, ref int width, ref int height, ref int frameWidth, ref int frameHeight, ref int extraX, ref int extraY)
static void FloorVisuals (int type, Player player)
static Texture2D GetCactusTexture (int type)
static Texture2D GetPalmTreeTexture (Tile tile)
static Texture2D GetPalmTreeTopTextures (int type)
static ModTile GetTile (int type)
Gets the ModTile instance with the given type. If no ModTile with the given type exists, returns null.
static Texture2D GetTreeBranchTextures (int type, int i, int j, int trunkOffset, ref int frame)
static Texture2D GetTreeTexture (Tile tile)
static Texture2D GetTreeTopTextures (int type, int i, int j, ref int frame, ref int frameWidth, ref int frameHeight, ref int xOffsetLeft, ref int yOffset)
static bool HasSmartInteract (int type)
static bool HasWalkDust (int type)
static void HitWire (int i, int j, int type)
static bool IsClosedDoor (Tile tile)
static bool IsDresser (int type)
static bool IsLockedChest (int i, int j, int type)
static bool IsModBed (int type)
static bool IsModMusicBox (Tile tile)
static bool IsSapling (int type)
static bool IsTorch (int type)
static void KillMultiTile (int i, int j, int frameX, int frameY, int type)
static bool KillSound (int i, int j, int type)
static void KillTile (int i, int j, int type, ref bool fail, ref bool effectOnly, ref bool noItem)
static void MineDamage (int minePower, ref int damage)
static string ModChestName (int type)
static string ModDresserName (int type)
static void ModifyLight (int i, int j, int type, ref float r, ref float g, ref float b)
static void MouseOver (int i, int j)
static void MouseOverFar (int i, int j)
static void NearbyEffects (int i, int j, int type, bool closer)
static void NumDust (int i, int j, int type, bool fail, ref int numDust)
static int OpenDoorID (Tile tile)
static void PalmTreeDust (Tile tile, ref int dust)
static void PalmTreeGrowthFXGore (int type, ref int gore)
static void PickPowerCheck (Tile target, int pickPower, ref int damage)
static void PlaceInWorld (int i, int j, Item item)
static void PostDraw (int i, int j, int type, SpriteBatch spriteBatch)
static bool PreDraw (int i, int j, int type, SpriteBatch spriteBatch)
static bool PreHitWire (int i, int j, int type)
static void RandomUpdate (int i, int j, int type)
static bool RightClick (int i, int j)
static bool SaplingGrowthType (int type, ref int saplingType, ref int style)
static void SetAnimationFrame (int type, int i, int j, ref int frameXOffset, ref int frameYOffset)
Sets the animation frame. Sets frameYOffset = modTile.animationFrameHeight * Main.tileFrame[type]; and then calls ModTile.AnimateIndividualTile
static void SetDrawPositions (int i, int j, ref int width, ref int offsetY, ref int height)
static void SetSpriteEffects (int i, int j, int type, ref SpriteEffects spriteEffects)
static bool Slope (int i, int j, int type)
static void SpecialDraw (int type, int specX, int specY, SpriteBatch spriteBatch)
Special Draw calls ModTile and GlobalTile SpecialDraw methods. Special Draw is called from DrawTiles after the draw loop, allowing for basically another layer above tiles. Main.specX and Main.specY are used to specify tiles to call SpecialDraw on. Use DrawEffects hook to queue for SpecialDraw.
static bool TileFrame (int i, int j, int type, ref bool resetFrame, ref bool noBreak)
static void TreeDust (Tile tile, ref int dust)
static void TreeGrowthFXGore (int type, ref int gore)
static bool UnlockChest (int i, int j, int type, ref short frameXAdjustment, ref int dustType, ref bool manual)
static void WalkDust (int type, ref int dustType, ref bool makeDust, ref Color color)
Properties
static int TileCount [get]
Private Member Functions
delegate bool DelegateCanKillTile (int i, int j, int type, ref bool blockDamaged)
delegate void DelegateChangeWaterfallStyle (int type, ref int style)
delegate bool DelegateCreateDust (int i, int j, int type, ref int dustType)
delegate void DelegateDrawEffects (int i, int j, int type, SpriteBatch spriteBatch, ref Color drawColor, ref int nextSpecialDrawIndex)
delegate void DelegateDropCritterChance (int i, int j, int type, ref int wormChance, ref int grassHopperChance, ref int jungleGrubChance)
delegate void DelegateKillTile (int i, int j, int type, ref bool fail, ref bool effectOnly, ref bool noItem)
delegate void DelegateModifyLight (int i, int j, int type, ref float r, ref float g, ref float b)
delegate void DelegateNumDust (int i, int j, int type, bool fail, ref int num)
delegate int DelegateSaplingGrowthType (int type, ref int style)
delegate void DelegateSetSpriteEffects (int i, int j, int type, ref SpriteEffects spriteEffects)
delegate bool DelegateTileFrame (int i, int j, int type, ref bool resetFrame, ref bool noBreak)
Static Private Member Functions
static void Resize2DArray< T > (ref T[,] array, int newSize)
Static Private Attributes
static Func< int, int[]>[] HookAdjTiles
static Action[] HookAnimateTile
static Func< int, int, int, Item, bool >[] HookAutoSelect
static Func< int, int, int, bool >[] HookCanExplode
static DelegateCanKillTile[] HookCanKillTile
static Func< int, int, int, bool >[] HookCanPlace
static DelegateChangeWaterfallStyle[] HookChangeWaterfallStyle
static DelegateCreateDust[] HookCreateDust
static Func< int, int, int, Player, bool >[] HookDangersense
static DelegateDrawEffects[] HookDrawEffects
static Func< int, int, int, bool >[] HookDrop
static DelegateDropCritterChance[] HookDropCritterChance
static Action< int, Player >[] HookFloorVisuals
static Action< int, int, int >[] HookHitWire
static Func< int, int, int, bool >[] HookKillSound
static DelegateKillTile[] HookKillTile
static DelegateModifyLight[] HookModifyLight
static Action< int, int, int >[] HookMouseOver
static Action< int, int, int >[] HookMouseOverFar
static Action< int, int, int, bool >[] HookNearbyEffects
static DelegateNumDust[] HookNumDust
static Action< int, int, Item >[] HookPlaceInWorld
static Action< int, int, int, SpriteBatch >[] HookPostDraw
static Func< int, int, int, SpriteBatch, bool >[] HookPreDraw
static Func< int, int, int, bool >[] HookPreHitWire
static Action< int, int, int >[] HookRandomUpdate
static Action< int, int, int >[] HookRightClick
static DelegateSaplingGrowthType[] HookSaplingGrowthType
static DelegateSetSpriteEffects[] HookSetSpriteEffects
static Func< int, int, int, bool >[] HookSlope
static Action< int, int, int, SpriteBatch >[] HookSpecialDraw
static DelegateTileFrame[] HookTileFrame
static bool loaded = false
static int nextTile = TileID.Count
static readonly int vanillaChairCount = TileID.Sets.RoomNeeds.CountsAsChair.Length
static readonly int vanillaDoorCount = TileID.Sets.RoomNeeds.CountsAsDoor.Length
static readonly int vanillaTableCount = TileID.Sets.RoomNeeds.CountsAsTable.Length
static readonly int vanillaTorchCount = TileID.Sets.RoomNeeds.CountsAsTorch.Length
Detailed Description
This serves as the central class from which tile-related functions are supported and carried out.
Definition at line 14 of file TileLoader.cs.
Member Function Documentation
AdjTiles()
static void Terraria.ModLoader.TileLoader.AdjTiles (Player player, int type) static
Definition at line 796 of file TileLoader.cs.
{
            ModTile modTile = GetTile(type);
            if (modTile != null) {
                foreach (int k in modTile.adjTiles) {
                    player.adjTile[k] = true;
                }
            }
            foreach (var hook in HookAdjTiles) {
                int[] adjTiles = hook(type);
                foreach (int k in adjTiles) {
                    player.adjTile[k] = true;
                }
            }
        }
References Terraria.ModLoader.ModTile.adjTiles, Terraria.ModLoader.TileLoader.GetTile(), and Terraria.ModLoader.TileLoader.HookAdjTiles.
AnimateTiles()
static void Terraria.ModLoader.TileLoader.AnimateTiles () static
Definition at line 672 of file TileLoader.cs.
{
            if (loaded) {
                for (int i = 0; i < tiles.Count; i++) {
                    ModTile modTile = tiles[i];
                    modTile.AnimateTile(ref Main.tileFrame[modTile.Type], ref Main.tileFrameCounter[modTile.Type]);
                }
                foreach (var hook in HookAnimateTile) {
                    hook();
                }
            }
        }
References Terraria.ModLoader.ModTile.AnimateTile(), Terraria.ModLoader.TileLoader.HookAnimateTile, Terraria.ModLoader.TileLoader.loaded, and Terraria.ModLoader.ModTile.Type.
AutoSelect()
static int Terraria.ModLoader.TileLoader.AutoSelect (int i, int j, Player player) static
Definition at line 844 of file TileLoader.cs.
{
            if (!Main.tile[i, j].active()) {
                return -1;
            }
            int type = Main.tile[i, j].type;
            ModTile modTile = GetTile(type);
            for (int k = 0; k < 50; k++) {
                Item item = player.inventory[k];
                if (item.type == 0 || item.stack == 0) {
                    continue;
                }
                if (modTile != null && modTile.AutoSelect(i, j, item)) {
                    return k;
                }
                foreach (var hook in HookAutoSelect) {
                    if (hook(i, j, type, item)) {
                        return k;
                    }
                }
            }
            return -1;
        }
References Terraria.ModLoader.ModTile.AutoSelect(), Terraria.ModLoader.TileLoader.GetTile(), Terraria.ModLoader.TileLoader.HookAutoSelect, and Terraria.ModLoader.Item.
CanDropAcorn()
static bool Terraria.ModLoader.TileLoader.CanDropAcorn (int type) static
Definition at line 968 of file TileLoader.cs.
{
            return trees.ContainsKey(type) ? trees[type].CanDropAcorn() : false;
        }
CanExplode()
static bool Terraria.ModLoader.TileLoader.CanExplode (int i, int j) static
Definition at line 595 of file TileLoader.cs.
{
            int type = Main.tile[i, j].type;
            ModTile modTile = GetTile(type);
            if (modTile != null && !modTile.CanExplode(i, j)) {
                return false;
            }
            foreach (var hook in HookCanExplode) {
                if (!hook(i, j, type)) {
                    return false;
                }
            }
            return true;
        }
References Terraria.ModLoader.ModTile.CanExplode(), Terraria.ModLoader.TileLoader.GetTile(), and Terraria.ModLoader.TileLoader.HookCanExplode.
CanGrowModCactus()
static bool Terraria.ModLoader.TileLoader.CanGrowModCactus (int type) static
Definition at line 1022 of file TileLoader.cs.
{
            return cacti.ContainsKey(type);
        }
CanGrowModPalmTree()
static bool Terraria.ModLoader.TileLoader.CanGrowModPalmTree (int type) static
Definition at line 992 of file TileLoader.cs.
{
            return palmTrees.ContainsKey(type);
        }
CanGrowModTree()
static bool Terraria.ModLoader.TileLoader.CanGrowModTree (int type) static
Definition at line 952 of file TileLoader.cs.
{
            return trees.ContainsKey(type);
        }
CanKillTile()
static bool Terraria.ModLoader.TileLoader.CanKillTile (int i, int j, int type, ref bool blockDamaged) static
Definition at line 573 of file TileLoader.cs.
{
            foreach (var hook in HookCanKillTile) {
                if (!hook(i, j, type, ref blockDamaged)) {
                    return false;
                }
            }
            return GetTile(type)?.CanKillTile(i, j, ref blockDamaged) ?? true;
        }
References Terraria.ModLoader.ModTile.CanKillTile(), Terraria.ModLoader.TileLoader.GetTile(), and Terraria.ModLoader.TileLoader.HookCanKillTile.
CanPlace()
static bool Terraria.ModLoader.TileLoader.CanPlace (int i, int j, int type) static
Definition at line 786 of file TileLoader.cs.
{
            foreach (var hook in HookCanPlace) {
                if (!hook(i, j, type)) {
                    return false;
                }
            }
            return GetTile(type)?.CanPlace(i, j) ?? true;
        }
References Terraria.ModLoader.ModTile.CanPlace(), Terraria.ModLoader.TileLoader.GetTile(), and Terraria.ModLoader.TileLoader.HookCanPlace.
ChangeWaterfallStyle()
static void Terraria.ModLoader.TileLoader.ChangeWaterfallStyle (int type, ref int style) static
Definition at line 913 of file TileLoader.cs.
{
            GetTile(type)?.ChangeWaterfallStyle(ref style);
            foreach (var hook in HookChangeWaterfallStyle) {
                hook(type, ref style);
            }
        }
References Terraria.ModLoader.ModTile.ChangeWaterfallStyle(), Terraria.ModLoader.TileLoader.GetTile(), and Terraria.ModLoader.TileLoader.HookChangeWaterfallStyle.
CheckModTile()
static void Terraria.ModLoader.TileLoader.CheckModTile (int i, int j, int type) static
Definition at line 297 of file TileLoader.cs.
{
            if (WorldGen.destroyObject) {
                return;
            }
            TileObjectData tileData = TileObjectData.GetTileData(type, 0, 0);
            if (tileData == null) {
                return;
            }
            int frameX = Main.tile[i, j].frameX;
            int frameY = Main.tile[i, j].frameY;
            int subX = frameX / tileData.CoordinateFullWidth;
            int subY = frameY / tileData.CoordinateFullHeight;
            int wrap = tileData.StyleWrapLimit;
            if (wrap == 0) {
                wrap = 1;
            }
            int subTile = tileData.StyleHorizontal ? subY * wrap + subX : subX * wrap + subY;
            int style = subTile / tileData.StyleMultiplier;
            int alternate = subTile % tileData.StyleMultiplier;
            for (int k = 0; k < tileData.AlternatesCount; k++) {
                if (alternate >= tileData.Alternates[k].Style && alternate <= tileData.Alternates[k].Style + tileData.RandomStyleRange) {
                    alternate = k;
                    break;
                }
            }
            tileData = TileObjectData.GetTileData(type, style, alternate + 1);
            int partFrameX = frameX % tileData.CoordinateFullWidth;
            int partFrameY = frameY % tileData.CoordinateFullHeight;
            int partX = partFrameX / (tileData.CoordinateWidth + tileData.CoordinatePadding);
            int partY = 0;
            int remainingFrameY = partFrameY;
            while (remainingFrameY > 0) {
                remainingFrameY -= tileData.CoordinateHeights[partY] + tileData.CoordinatePadding;
                partY++;
            }
            i -= partX;
            j -= partY;
            int originX = i + tileData.Origin.X;
            int originY = j + tileData.Origin.Y;
            TileObject objectData;
            bool partiallyDestroyed = false;
            for (int x = i; x < i + tileData.Width; x++) {
                for (int y = j; y < j + tileData.Height; y++) {
                    if (!Main.tile[x, y].active() || Main.tile[x, y].type != type) {
                        partiallyDestroyed = true;
                        break;
                    }
                }
                if (partiallyDestroyed) {
                    break;
                }
            }
            if (partiallyDestroyed || !TileObject.CanPlace(originX, originY, type, style, 0, out objectData, true, true)) {
                WorldGen.destroyObject = true;
                for (int x = i; x < i + tileData.Width; x++) {
                    for (int y = j; y < j + tileData.Height; y++) {
                        if (Main.tile[x, y].type == type && Main.tile[x, y].active()) {
                            WorldGen.KillTile(x, y, false, false, false);
                        }
                    }
                }
                KillMultiTile(i, j, frameX - partFrameX, frameY - partFrameY, type);
                WorldGen.destroyObject = false;
                for (int x = i - 1; x < i + tileData.Width + 2; x++) {
                    for (int y = j - 1; y < j + tileData.Height + 2; y++) {
                        WorldGen.TileFrame(x, y, false, false);
                    }
                }
            }
            TileObject.objectPreview.Active = false;
        }
References Terraria.ModLoader.TileLoader.KillMultiTile().
CloseDoorID()
static int Terraria.ModLoader.TileLoader.CloseDoorID (Tile tile) static
Definition at line 403 of file TileLoader.cs.
{
            ModTile modTile = GetTile(tile.type);
            if (modTile != null) {
                return modTile.closeDoorID;
            }
            if (tile.type == TileID.OpenDoor) {
                return TileID.ClosedDoor;
            }
            return -1;
        }
References Terraria.ModLoader.ModTile.closeDoorID, and Terraria.ModLoader.TileLoader.GetTile().
CreateDust()
static bool Terraria.ModLoader.TileLoader.CreateDust (int i, int j, int type, ref int dustType) static
Definition at line 533 of file TileLoader.cs.
{
            foreach (var hook in HookCreateDust) {
                if (!hook(i, j, type, ref dustType)) {
                    return false;
                }
            }
            return GetTile(type)?.CreateDust(i, j, ref dustType) ?? true;
        }
References Terraria.ModLoader.ModTile.CreateDust(), Terraria.ModLoader.TileLoader.GetTile(), and Terraria.ModLoader.TileLoader.HookCreateDust.
Dangersense()
static bool Terraria.ModLoader.TileLoader.Dangersense (int i, int j, int type, Player player) static
Definition at line 630 of file TileLoader.cs.
{
            ModTile modTile = GetTile(type);
            if (modTile != null && modTile.Dangersense(i, j, player)) {
                return true;
            }
            foreach (var hook in HookDangersense) {
                if (hook(i, j, type, player)) {
                    return true;
                }
            }
            return false;
        }
References Terraria.ModLoader.ModTile.Dangersense(), Terraria.ModLoader.TileLoader.GetTile(), and Terraria.ModLoader.TileLoader.HookDangersense.
DelegateCanKillTile()
delegate bool Terraria.ModLoader.TileLoader.DelegateCanKillTile (int i, int j, int type, ref bool blockDamaged) private
DelegateChangeWaterfallStyle()
delegate void Terraria.ModLoader.TileLoader.DelegateChangeWaterfallStyle (int type, ref int style) private
DelegateCreateDust()
delegate bool Terraria.ModLoader.TileLoader.DelegateCreateDust (int i, int j, int type, ref int dustType) private
DelegateDrawEffects()
delegate void Terraria.ModLoader.TileLoader.DelegateDrawEffects (int i, int j, int type, SpriteBatch spriteBatch, ref Color drawColor, ref int nextSpecialDrawIndex) private
DelegateDropCritterChance()
delegate void Terraria.ModLoader.TileLoader.DelegateDropCritterChance (int i, int j, int type, ref int wormChance, ref int grassHopperChance, ref int jungleGrubChance) private
DelegateKillTile()
delegate void Terraria.ModLoader.TileLoader.DelegateKillTile (int i, int j, int type, ref bool fail, ref bool effectOnly, ref bool noItem) private
DelegateModifyLight()
delegate void Terraria.ModLoader.TileLoader.DelegateModifyLight (int i, int j, int type, ref float r, ref float g, ref float b) private
DelegateNumDust()
delegate void Terraria.ModLoader.TileLoader.DelegateNumDust (int i, int j, int type, bool fail, ref int num) private
DelegateSaplingGrowthType()
delegate int Terraria.ModLoader.TileLoader.DelegateSaplingGrowthType (int type, ref int style) private
DelegateSetSpriteEffects()
delegate void Terraria.ModLoader.TileLoader.DelegateSetSpriteEffects (int i, int j, int type, ref SpriteEffects spriteEffects) private
DelegateTileFrame()
delegate bool Terraria.ModLoader.TileLoader.DelegateTileFrame (int i, int j, int type, ref bool resetFrame, ref bool noBreak) private
DisableSmartCursor()
static void Terraria.ModLoader.TileLoader.DisableSmartCursor (Tile tile, ref bool disable) static
Definition at line 369 of file TileLoader.cs.
{
            if (tile.active()) {
                ModTile modTile = GetTile(tile.type);
                if (modTile != null) {
                    disable = modTile.disableSmartCursor;
                }
            }
        }
References Terraria.ModLoader.ModTile.disableSmartCursor, and Terraria.ModLoader.TileLoader.GetTile().
DisableSmartInteract()
static void Terraria.ModLoader.TileLoader.DisableSmartInteract (Tile tile, ref bool disable) static
Definition at line 378 of file TileLoader.cs.
{
            if (tile.active()) {
                ModTile modTile = GetTile(tile.type);
                if (modTile != null) {
                    disable = modTile.disableSmartInteract;
                }
            }
        }
References Terraria.ModLoader.ModTile.disableSmartInteract, and Terraria.ModLoader.TileLoader.GetTile().
DrawEffects()
static void Terraria.ModLoader.TileLoader.DrawEffects (int i, int j, int type, SpriteBatch spriteBatch, ref Color drawColor, ref int nextSpecialDrawIndex) static
Definition at line 714 of file TileLoader.cs.
{
            GetTile(type)?.DrawEffects(i, j, spriteBatch, ref drawColor, ref nextSpecialDrawIndex);
            foreach (var hook in HookDrawEffects) {
                hook(i, j, type, spriteBatch, ref drawColor, ref nextSpecialDrawIndex);
            }
        }
References Terraria.ModLoader.ModTile.DrawEffects(), Terraria.ModLoader.TileLoader.GetTile(), and Terraria.ModLoader.TileLoader.HookDrawEffects.
Drop()
static bool Terraria.ModLoader.TileLoader.Drop (int i, int j, int type) static
Definition at line 553 of file TileLoader.cs.
{
            foreach (var hook in HookDrop) {
                if (!hook(i, j, type)) {
                    return false;
                }
            }
            ModTile modTile = GetTile(type);
            if (modTile != null) {
                if (!modTile.Drop(i, j)) {
                    return false;
                }
                if (modTile.drop > 0) {
                    Item.NewItem(i * 16, j * 16, 16, 16, modTile.drop, 1, false, -1);
                }
                return false;
            }
            return true;
        }
References Terraria.ModLoader.ModTile.drop, Terraria.ModLoader.ModTile.Drop(), Terraria.ModLoader.TileLoader.GetTile(), Terraria.ModLoader.TileLoader.HookDrop, and Terraria.ModLoader.Item.
DropCritterChance()
static void Terraria.ModLoader.TileLoader.DropCritterChance (int i, int j, int type, ref int wormChance, ref int grassHopperChance, ref int jungleGrubChance) static
Definition at line 543 of file TileLoader.cs.
{
            GetTile(type)?.DropCritterChance(i, j, ref wormChance, ref grassHopperChance, ref jungleGrubChance);
            foreach (var hook in HookDropCritterChance) {
                hook(i, j, type, ref wormChance, ref grassHopperChance, ref jungleGrubChance);
            }
        }
References Terraria.ModLoader.ModTile.DropCritterChance(), Terraria.ModLoader.TileLoader.GetTile(), and Terraria.ModLoader.TileLoader.HookDropCritterChance.
DropPalmTreeWood()
static void Terraria.ModLoader.TileLoader.DropPalmTreeWood (int type, ref int wood) static
Definition at line 1008 of file TileLoader.cs.
{
            if (palmTrees.ContainsKey(type)) {
                wood = palmTrees[type].DropWood();
            }
        }
DropTreeWood()
static void Terraria.ModLoader.TileLoader.DropTreeWood (int type, ref int wood) static
Definition at line 972 of file TileLoader.cs.
{
            if (trees.ContainsKey(type)) {
                wood = trees[type].DropWood();
            }
        }
FixSmartInteractCoords()
static void Terraria.ModLoader.TileLoader.FixSmartInteractCoords (int type, ref int width, ref int height, ref int frameWidth, ref int frameHeight, ref int extraX, ref int extraY) static
Definition at line 493 of file TileLoader.cs.
{
            ModTile modTile = GetTile(type);
            if (modTile != null) {
                TileObjectData data = TileObjectData.GetTileData(type, 0);
                width = data.Width;
                height = data.Height;
                frameWidth = data.CoordinateWidth + data.CoordinatePadding;
                frameHeight = data.CoordinateHeights[0] + data.CoordinatePadding;
                extraY = data.CoordinateFullHeight % frameHeight;
            }
        }
References Terraria.ModLoader.TileLoader.GetTile().
FloorVisuals()
static void Terraria.ModLoader.TileLoader.FloorVisuals (int type, Player player) static
Definition at line 887 of file TileLoader.cs.
{
            GetTile(type)?.FloorVisuals(player);
            foreach (var hook in HookFloorVisuals) {
                hook(type, player);
            }
        }
References Terraria.ModLoader.ModTile.FloorVisuals(), Terraria.ModLoader.TileLoader.GetTile(), and Terraria.ModLoader.TileLoader.HookFloorVisuals.
GetCactusTexture()
static Texture2D Terraria.ModLoader.TileLoader.GetCactusTexture (int type) static
Definition at line 1026 of file TileLoader.cs.
{
            return cacti.ContainsKey(type) ? cacti[type].GetTexture() : null;
        }
GetPalmTreeTexture()
static Texture2D Terraria.ModLoader.TileLoader.GetPalmTreeTexture (Tile tile) static
Definition at line 1014 of file TileLoader.cs.
{
            return tile.active() && palmTrees.ContainsKey(tile.type) ? palmTrees[tile.type].GetTexture() : null;
        }
GetPalmTreeTopTextures()
static Texture2D Terraria.ModLoader.TileLoader.GetPalmTreeTopTextures (int type) static
Definition at line 1018 of file TileLoader.cs.
{
            return palmTrees.ContainsKey(type) ? palmTrees[type].GetTopTextures() : null;
        }
GetTile()
static ModTile Terraria.ModLoader.TileLoader.GetTile (int type) static
Gets the ModTile instance with the given type. If no ModTile with the given type exists, returns null.
Parameters
type The type of the ModTile
Returns
The ModTile instance in the tiles array, null if not found.
Definition at line 102 of file TileLoader.cs.
{
            return type >= TileID.Count && type < TileCount ? tiles[type - TileID.Count] : null;
        }
References Terraria.ModLoader.TileLoader.TileCount.
Referenced by Terraria.ModLoader.Mod.AddMusicBox(), Terraria.ModLoader.TileLoader.AdjTiles(), Terraria.ModLoader.TileLoader.AutoSelect(), Terraria.ModLoader.TileLoader.CanExplode(), Terraria.ModLoader.TileLoader.CanKillTile(), Terraria.ModLoader.TileLoader.CanPlace(), Terraria.ModLoader.TileLoader.ChangeWaterfallStyle(), Terraria.ModLoader.TileLoader.CloseDoorID(), Terraria.ModLoader.TileLoader.CreateDust(), Terraria.ModLoader.TileLoader.Dangersense(), Terraria.ModLoader.TileLoader.DisableSmartCursor(), Terraria.ModLoader.TileLoader.DisableSmartInteract(), Terraria.ModLoader.TileLoader.DrawEffects(), Terraria.ModLoader.TileLoader.Drop(), Terraria.ModLoader.TileLoader.DropCritterChance(), Terraria.ModLoader.TileLoader.FixSmartInteractCoords(), Terraria.ModLoader.TileLoader.FloorVisuals(), Terraria.ModLoader.TileLoader.HasSmartInteract(), Terraria.ModLoader.TileLoader.HasWalkDust(), Terraria.ModLoader.TileLoader.HitWire(), Terraria.ModLoader.TileLoader.IsClosedDoor(), Terraria.ModLoader.TileLoader.IsLockedChest(), Terraria.ModLoader.TileLoader.IsModBed(), Terraria.ModLoader.TileLoader.IsSapling(), Terraria.ModLoader.TileLoader.IsTorch(), Terraria.ModLoader.TileLoader.KillMultiTile(), Terraria.ModLoader.TileLoader.KillSound(), Terraria.ModLoader.TileLoader.KillTile(), Terraria.ModLoader.TileLoader.MineDamage(), Terraria.ModLoader.TileLoader.ModChestName(), Terraria.ModLoader.TileLoader.ModDresserName(), Terraria.ModLoader.TileLoader.ModifyLight(), Terraria.ModLoader.TileLoader.MouseOver(), Terraria.ModLoader.TileLoader.MouseOverFar(), Terraria.ModLoader.TileLoader.NearbyEffects(), Terraria.ModLoader.TileLoader.NumDust(), Terraria.ModLoader.TileLoader.OpenDoorID(), Terraria.ModLoader.TileLoader.PickPowerCheck(), Terraria.ModLoader.TileLoader.PlaceInWorld(), Terraria.ModLoader.TileLoader.PostDraw(), Terraria.ModLoader.TileLoader.PreDraw(), Terraria.ModLoader.TileLoader.RandomUpdate(), Terraria.ModLoader.TileLoader.RightClick(), Terraria.ModLoader.TileLoader.SaplingGrowthType(), Terraria.ModLoader.TileLoader.SetAnimationFrame(), Terraria.ModLoader.TileLoader.SetDrawPositions(), Terraria.ModLoader.TileLoader.SetSpriteEffects(), Terraria.ModLoader.TileLoader.Slope(), Terraria.ModLoader.TileLoader.SpecialDraw(), Terraria.ModLoader.TileLoader.TileFrame(), Terraria.ModLoader.TileLoader.UnlockChest(), and Terraria.ModLoader.TileLoader.WalkDust().
GetTreeBranchTextures()
static Texture2D Terraria.ModLoader.TileLoader.GetTreeBranchTextures (int type, int i, int j, int trunkOffset, ref int frame) static
Definition at line 988 of file TileLoader.cs.
{
            return trees.ContainsKey(type) ? trees[type].GetBranchTextures(i, j, trunkOffset, ref frame) : null;
        }
GetTreeTexture()
static Texture2D Terraria.ModLoader.TileLoader.GetTreeTexture (Tile tile) static
Definition at line 978 of file TileLoader.cs.
{
            return tile.active() && trees.ContainsKey(tile.type) ? trees[tile.type].GetTexture() : null;
        }
GetTreeTopTextures()
static Texture2D Terraria.ModLoader.TileLoader.GetTreeTopTextures (int type, int i, int j, ref int frame, ref int frameWidth, ref int frameHeight, ref int xOffsetLeft, ref int yOffset) static
Definition at line 982 of file TileLoader.cs.
{
            return trees.ContainsKey(type) ? trees[type].GetTopTextures(i, j, ref frame,
                ref frameWidth, ref frameHeight, ref xOffsetLeft, ref yOffset) : null;
        }
HasSmartInteract()
static bool Terraria.ModLoader.TileLoader.HasSmartInteract (int type) static
Definition at line 489 of file TileLoader.cs.
{
            return GetTile(type)?.HasSmartInteract() ?? false;
        }
References Terraria.ModLoader.TileLoader.GetTile(), and Terraria.ModLoader.ModTile.HasSmartInteract().
HasWalkDust()
static bool Terraria.ModLoader.TileLoader.HasWalkDust (int type) static
Definition at line 905 of file TileLoader.cs.
{
            return GetTile(type)?.HasWalkDust() ?? false;
        }
References Terraria.ModLoader.TileLoader.GetTile(), and Terraria.ModLoader.ModTile.HasWalkDust().
HitWire()
static void Terraria.ModLoader.TileLoader.HitWire (int i, int j, int type) static
Definition at line 879 of file TileLoader.cs.
{
            GetTile(type)?.HitWire(i, j);
            foreach (var hook in HookHitWire) {
                hook(i, j, type);
            }
        }
References Terraria.ModLoader.TileLoader.GetTile(), Terraria.ModLoader.ModTile.HitWire(), and Terraria.ModLoader.TileLoader.HookHitWire.
IsClosedDoor()
static bool Terraria.ModLoader.TileLoader.IsClosedDoor (Tile tile) static
Definition at line 413 of file TileLoader.cs.
{
            ModTile modTile = GetTile(tile.type);
            if (modTile != null) {
                return modTile.openDoorID > -1;
            }
            return tile.type == TileID.ClosedDoor;
        }
References Terraria.ModLoader.TileLoader.GetTile().
IsDresser()
static bool Terraria.ModLoader.TileLoader.IsDresser (int type) static
Definition at line 429 of file TileLoader.cs.
{
            if (type == TileID.Dressers) {
                return true;
            }
            return ModDresserName(type).Length > 0;
        }
References Terraria.ModLoader.TileLoader.ModDresserName().
IsLockedChest()
static bool Terraria.ModLoader.TileLoader.IsLockedChest (int i, int j, int type) static
Definition at line 1042 of file TileLoader.cs.
{
            return GetTile(type)?.IsLockedChest(i, j) ?? false;
        }
References Terraria.ModLoader.TileLoader.GetTile(), and Terraria.ModLoader.ModTile.IsLockedChest().
IsModBed()
static bool Terraria.ModLoader.TileLoader.IsModBed (int type) static
Definition at line 444 of file TileLoader.cs.
{
            ModTile modTile = GetTile(type);
            if (modTile == null) {
                return false;
            }
            return modTile.bed;
        }
References Terraria.ModLoader.ModTile.bed, and Terraria.ModLoader.TileLoader.GetTile().
IsModMusicBox()
static bool Terraria.ModLoader.TileLoader.IsModMusicBox (Tile tile) static
Definition at line 468 of file TileLoader.cs.
{
            return SoundLoader.tileToMusic.ContainsKey(tile.type)
            && SoundLoader.tileToMusic[tile.type].ContainsKey(tile.frameY / 36 * 36);
        }
IsSapling()
static bool Terraria.ModLoader.TileLoader.IsSapling (int type) static
Definition at line 460 of file TileLoader.cs.
{
            ModTile modTile = GetTile(type);
            if (modTile == null) {
                return type == TileID.Saplings;
            }
            return modTile.sapling;
        }
References Terraria.ModLoader.TileLoader.GetTile(), and Terraria.ModLoader.ModTile.sapling.
Referenced by Terraria.ModLoader.TileLoader.SaplingGrowthType().
IsTorch()
static bool Terraria.ModLoader.TileLoader.IsTorch (int type) static
Definition at line 452 of file TileLoader.cs.
{
            ModTile modTile = GetTile(type);
            if (modTile == null) {
                return type == TileID.Torches;
            }
            return modTile.torch;
        }
References Terraria.ModLoader.TileLoader.GetTile(), and Terraria.ModLoader.ModTile.torch.
KillMultiTile()
static void Terraria.ModLoader.TileLoader.KillMultiTile (int i, int j, int frameX, int frameY, int type) static
Definition at line 591 of file TileLoader.cs.
{
            GetTile(type)?.KillMultiTile(i, j, frameX, frameY);
        }
References Terraria.ModLoader.TileLoader.GetTile(), and Terraria.ModLoader.ModTile.KillMultiTile().
Referenced by Terraria.ModLoader.TileLoader.CheckModTile().
KillSound()
static bool Terraria.ModLoader.TileLoader.KillSound (int i, int j, int type) static
Definition at line 506 of file TileLoader.cs.
{
            foreach (var hook in HookKillSound) {
                if (!hook(i, j, type)) {
                    return false;
                }
            }
            ModTile modTile = GetTile(type);
            if (modTile != null) {
                if (!modTile.KillSound(i, j)) {
                    return false;
                }
                Main.PlaySound(modTile.soundType, i * 16, j * 16, modTile.soundStyle);
                return false;
            }
            return true;
        }
References Terraria.ModLoader.TileLoader.GetTile(), Terraria.ModLoader.TileLoader.HookKillSound, Terraria.ModLoader.ModTile.KillSound(), Terraria.ModLoader.ModTile.soundStyle, and Terraria.ModLoader.ModTile.soundType.
KillTile()
static void Terraria.ModLoader.TileLoader.KillTile (int i, int j, int type, ref bool fail, ref bool effectOnly, ref bool noItem) static
Definition at line 583 of file TileLoader.cs.
{
            GetTile(type)?.KillTile(i, j, ref fail, ref effectOnly, ref noItem);
            foreach (var hook in HookKillTile) {
                hook(i, j, type, ref fail, ref effectOnly, ref noItem);
            }
        }
References Terraria.ModLoader.TileLoader.GetTile(), Terraria.ModLoader.TileLoader.HookKillTile, and Terraria.ModLoader.ModTile.KillTile().
MineDamage()
static void Terraria.ModLoader.TileLoader.MineDamage (int minePower, ref int damage) static
Definition at line 771 of file TileLoader.cs.
{
            Tile target = Main.tile[Player.tileTargetX, Player.tileTargetY];
            ModTile modTile = GetTile(target.type);
            damage += modTile != null ? (int)(minePower / modTile.mineResist) : minePower;
        }
References Terraria.ModLoader.TileLoader.GetTile(), and Terraria.ModLoader.ModTile.mineResist.
ModChestName()
static string Terraria.ModLoader.TileLoader.ModChestName (int type) static
Definition at line 421 of file TileLoader.cs.
{
            ModTile modTile = GetTile(type);
            if (modTile != null) {
                return modTile.chest;
            }
            return "";
        }
References Terraria.ModLoader.ModTile.chest, and Terraria.ModLoader.TileLoader.GetTile().
ModDresserName()
static string Terraria.ModLoader.TileLoader.ModDresserName (int type) static
Definition at line 436 of file TileLoader.cs.
{
            ModTile modTile = GetTile(type);
            if (modTile != null) {
                return modTile.dresser;
            }
            return "";
        }
References Terraria.ModLoader.ModTile.dresser, and Terraria.ModLoader.TileLoader.GetTile().
Referenced by Terraria.ModLoader.TileLoader.IsDresser().
ModifyLight()
static void Terraria.ModLoader.TileLoader.ModifyLight (int i, int j, int type, ref float r, ref float g, ref float b) static
Definition at line 619 of file TileLoader.cs.
{
            if (!Main.tileLighted[type]) {
                return;
            }
            GetTile(type)?.ModifyLight(i, j, ref r, ref g, ref b);
            foreach (var hook in HookModifyLight) {
                hook(i, j, type, ref r, ref g, ref b);
            }
        }
References Terraria.ModLoader.TileLoader.GetTile(), Terraria.ModLoader.TileLoader.HookModifyLight, and Terraria.ModLoader.ModTile.ModifyLight().
MouseOver()
static void Terraria.ModLoader.TileLoader.MouseOver (int i, int j) static
Definition at line 826 of file TileLoader.cs.
{
            int type = Main.tile[i, j].type;
            GetTile(type)?.MouseOver(i, j);
            foreach (var hook in HookMouseOver) {
                hook(i, j, type);
            }
        }
References Terraria.ModLoader.TileLoader.GetTile(), Terraria.ModLoader.TileLoader.HookMouseOver, and Terraria.ModLoader.ModTile.MouseOver().
MouseOverFar()
static void Terraria.ModLoader.TileLoader.MouseOverFar (int i, int j) static
Definition at line 835 of file TileLoader.cs.
{
            int type = Main.tile[i, j].type;
            GetTile(type)?.MouseOverFar(i, j);
            foreach (var hook in HookMouseOverFar) {
                hook(i, j, type);
            }
        }
References Terraria.ModLoader.TileLoader.GetTile(), Terraria.ModLoader.TileLoader.HookMouseOverFar, and Terraria.ModLoader.ModTile.MouseOverFar().
NearbyEffects()
static void Terraria.ModLoader.TileLoader.NearbyEffects (int i, int j, int type, bool closer) static
Definition at line 610 of file TileLoader.cs.
{
            GetTile(type)?.NearbyEffects(i, j, closer);
            foreach (var hook in HookNearbyEffects) {
                hook(i, j, type, closer);
            }
        }
References Terraria.ModLoader.TileLoader.GetTile(), Terraria.ModLoader.TileLoader.HookNearbyEffects, and Terraria.ModLoader.ModTile.NearbyEffects().
NumDust()
static void Terraria.ModLoader.TileLoader.NumDust (int i, int j, int type, bool fail, ref int numDust) static
Definition at line 524 of file TileLoader.cs.
{
            GetTile(type)?.NumDust(i, j, fail, ref numDust);
            foreach (var hook in HookNumDust) {
                hook(i, j, type, fail, ref numDust);
            }
        }
References Terraria.ModLoader.TileLoader.GetTile(), Terraria.ModLoader.TileLoader.HookNumDust, and Terraria.ModLoader.ModTile.NumDust().
OpenDoorID()
static int Terraria.ModLoader.TileLoader.OpenDoorID (Tile tile) static
Definition at line 389 of file TileLoader.cs.
{
            ModTile modTile = GetTile(tile.type);
            if (modTile != null) {
                return modTile.openDoorID;
            }
            if (tile.type == TileID.ClosedDoor && (tile.frameY < 594 || tile.frameY > 646 || tile.frameX >= 54)) {
                return TileID.OpenDoor;
            }
            return -1;
        }
References Terraria.ModLoader.TileLoader.GetTile(), and Terraria.ModLoader.ModTile.openDoorID.
PalmTreeDust()
static void Terraria.ModLoader.TileLoader.PalmTreeDust (Tile tile, ref int dust) static
Definition at line 996 of file TileLoader.cs.
{
            if (tile.active() && palmTrees.ContainsKey(tile.type)) {
                dust = palmTrees[tile.type].CreateDust();
            }
        }
PalmTreeGrowthFXGore()
static void Terraria.ModLoader.TileLoader.PalmTreeGrowthFXGore (int type, ref int gore) static
Definition at line 1002 of file TileLoader.cs.
{
            if (palmTrees.ContainsKey(type)) {
                gore = palmTrees[type].GrowthFXGore();
            }
        }
PickPowerCheck()
static void Terraria.ModLoader.TileLoader.PickPowerCheck (Tile target, int pickPower, ref int damage) static
Definition at line 778 of file TileLoader.cs.
{
            ModTile modTile = GetTile(target.type);
            if (modTile != null && pickPower < modTile.minPick) {
                damage = 0;
            }
        }
References Terraria.ModLoader.TileLoader.GetTile(), and Terraria.ModLoader.ModTile.minPick.
PlaceInWorld()
static void Terraria.ModLoader.TileLoader.PlaceInWorld (int i, int j, Item item) static
Definition at line 1030 of file TileLoader.cs.
{
            int type = item.createTile;
            if (type < 0)
                return;
            foreach (var hook in HookPlaceInWorld) {
                hook(i, j, item);
            }
            GetTile(type)?.PlaceInWorld(i, j, item);
        }
References Terraria.ModLoader.TileLoader.GetTile(), Terraria.ModLoader.TileLoader.HookPlaceInWorld, and Terraria.ModLoader.ModTile.PlaceInWorld().
PostDraw()
static void Terraria.ModLoader.TileLoader.PostDraw (int i, int j, int type, SpriteBatch spriteBatch) static
Definition at line 722 of file TileLoader.cs.
{
            GetTile(type)?.PostDraw(i, j, spriteBatch);
            foreach (var hook in HookPostDraw) {
                hook(i, j, type, spriteBatch);
            }
        }
References Terraria.ModLoader.TileLoader.GetTile(), Terraria.ModLoader.TileLoader.HookPostDraw, and Terraria.ModLoader.ModTile.PostDraw().
PreDraw()
static bool Terraria.ModLoader.TileLoader.PreDraw (int i, int j, int type, SpriteBatch spriteBatch) static
Definition at line 705 of file TileLoader.cs.
{
            foreach (var hook in HookPreDraw) {
                if (!hook(i, j, type, spriteBatch)) {
                    return false;
                }
            }
            return GetTile(type)?.PreDraw(i, j, spriteBatch) ?? true;
        }
References Terraria.ModLoader.TileLoader.GetTile(), Terraria.ModLoader.TileLoader.HookPreDraw, and Terraria.ModLoader.ModTile.PreDraw().
PreHitWire()
static bool Terraria.ModLoader.TileLoader.PreHitWire (int i, int j, int type) static
Definition at line 867 of file TileLoader.cs.
{
            foreach (var hook in HookPreHitWire) {
                if (!hook(i, j, type)) {
                    return false;
                }
            }
            return true;
        }
References Terraria.ModLoader.TileLoader.HookPreHitWire.
RandomUpdate()
static void Terraria.ModLoader.TileLoader.RandomUpdate (int i, int j, int type) static
Definition at line 744 of file TileLoader.cs.
{
            if (!Main.tile[i, j].active()) {
                return;
            }
            GetTile(type)?.RandomUpdate(i, j);
            foreach (var hook in HookRandomUpdate) {
                hook(i, j, type);
            }
        }
References Terraria.ModLoader.TileLoader.GetTile(), Terraria.ModLoader.TileLoader.HookRandomUpdate, and Terraria.ModLoader.ModTile.RandomUpdate().
Resize2DArray< T >()
static void Terraria.ModLoader.TileLoader.Resize2DArray< T > (ref T array[,], int newSize) static private
Definition at line 106 of file TileLoader.cs.
{
            int dim1 = array.GetLength(0);
            int dim2 = array.GetLength(1);
            T[,] newArray = new T[newSize, dim2];
            for (int j = 0; j < newSize && j < dim1; j++) {
                for (int k = 0; k < dim2; k++) {
                    newArray[j, k] = array[j, k];
                }
            }
            array = newArray;
        }
RightClick()
static bool Terraria.ModLoader.TileLoader.RightClick (int i, int j) static
Definition at line 812 of file TileLoader.cs.
{
            bool returnValue = false;
            int type = Main.tile[i, j].type;
            GetTile(type)?.RightClick(i, j);
            if (GetTile(type)?.NewRightClick(i, j) ?? false)
                returnValue = true;
            foreach (var hook in HookRightClick) {
                hook(i, j, type);
            }
            return returnValue;
        }
References Terraria.ModLoader.TileLoader.GetTile(), Terraria.ModLoader.TileLoader.HookRightClick, and Terraria.ModLoader.ModTile.RightClick().
SaplingGrowthType()
static bool Terraria.ModLoader.TileLoader.SaplingGrowthType (int type, ref int saplingType, ref int style) static
Definition at line 920 of file TileLoader.cs.
{
            int originalType = saplingType;
            int originalStyle = style;
            bool flag = false;
            ModTile modTile = GetTile(type);
            if (modTile != null) {
                saplingType = modTile.SaplingGrowthType(ref style);
                if (IsSapling(saplingType)) {
                    originalType = saplingType;
                    originalStyle = style;
                    flag = true;
                }
                else {
                    saplingType = originalType;
                    style = originalStyle;
                }
            }
            foreach (var hook in HookSaplingGrowthType) {
                saplingType = hook(type, ref style);
                if (IsSapling(saplingType)) {
                    originalType = saplingType;
                    originalStyle = style;
                    flag = true;
                }
                else {
                    saplingType = originalType;
                    style = originalStyle;
                }
            }
            return flag;
        }
References Terraria.ModLoader.TileLoader.GetTile(), Terraria.ModLoader.TileLoader.HookSaplingGrowthType, Terraria.ModLoader.TileLoader.IsSapling(), and Terraria.ModLoader.ModTile.SaplingGrowthType().
SetAnimationFrame()
static void Terraria.ModLoader.TileLoader.SetAnimationFrame (int type, int i, int j, ref int frameXOffset, ref int frameYOffset) static
Sets the animation frame. Sets frameYOffset = modTile.animationFrameHeight * Main.tileFrame[type]; and then calls ModTile.AnimateIndividualTile
Parameters
type The tile type.
i The x position in tile coordinates.
j The y position in tile coordinates.
frameXOffset The offset to frameX.
frameYOffset The offset to frameY.
Definition at line 694 of file TileLoader.cs.
{
            ModTile modTile = GetTile(type);
            if (modTile != null) {
                frameYOffset = modTile.animationFrameHeight * Main.tileFrame[type];
                modTile.AnimateIndividualTile(type, i, j, ref frameXOffset, ref frameYOffset);
            }
        }
References Terraria.ModLoader.ModTile.AnimateIndividualTile(), and Terraria.ModLoader.TileLoader.GetTile().
SetDrawPositions()
static void Terraria.ModLoader.TileLoader.SetDrawPositions (int i, int j, ref int width, ref int offsetY, ref int height) static
Definition at line 653 of file TileLoader.cs.
{
            Tile tile = Main.tile[i, j];
            if (tile.type >= TileID.Count) {
                TileObjectData tileData = TileObjectData.GetTileData(tile.type, 0, 0);
                if (tileData != null) {
                    int partFrameY = tile.frameY % tileData.CoordinateFullHeight;
                    int partY = 0;
                    while (partFrameY > 0) {
                        partFrameY -= tileData.CoordinateHeights[partY] + tileData.CoordinatePadding;
                        partY++;
                    }
                    width = tileData.CoordinateWidth;
                    offsetY = tileData.DrawYOffset;
                    height = tileData.CoordinateHeights[partY];
                }
                GetTile(tile.type).SetDrawPositions(i, j, ref width, ref offsetY, ref height);
            }
        }
References Terraria.ModLoader.TileLoader.GetTile(), and Terraria.ModLoader.ModTile.SetDrawPositions().
SetSpriteEffects()
static void Terraria.ModLoader.TileLoader.SetSpriteEffects (int i, int j, int type, ref SpriteEffects spriteEffects) static
Definition at line 644 of file TileLoader.cs.
{
            GetTile(type)?.SetSpriteEffects(i, j, ref spriteEffects);
            foreach (var hook in HookSetSpriteEffects) {
                hook(i, j, type, ref spriteEffects);
            }
        }
References Terraria.ModLoader.TileLoader.GetTile(), Terraria.ModLoader.TileLoader.HookSetSpriteEffects, and Terraria.ModLoader.ModTile.SetSpriteEffects().
Slope()
static bool Terraria.ModLoader.TileLoader.Slope (int i, int j, int type) static
Definition at line 896 of file TileLoader.cs.
{
            foreach (var hook in HookSlope) {
                if (!hook(i, j, type)) {
                    return true;
                }
            }
            return !GetTile(type)?.Slope(i, j) ?? false;
        }
References Terraria.ModLoader.TileLoader.GetTile(), Terraria.ModLoader.TileLoader.HookSlope, and Terraria.ModLoader.ModTile.Slope().
SpecialDraw()
static void Terraria.ModLoader.TileLoader.SpecialDraw (int type, int specX, int specY, SpriteBatch spriteBatch) static
Special Draw calls ModTile and GlobalTile SpecialDraw methods. Special Draw is called from DrawTiles after the draw loop, allowing for basically another layer above tiles. Main.specX and Main.specY are used to specify tiles to call SpecialDraw on. Use DrawEffects hook to queue for SpecialDraw.
Definition at line 733 of file TileLoader.cs.
{
            GetTile(type)?.SpecialDraw(specX, specY, spriteBatch);
            foreach (var hook in HookSpecialDraw) {
                hook(specX, specY, type, spriteBatch);
            }
        }
References Terraria.ModLoader.TileLoader.GetTile(), Terraria.ModLoader.TileLoader.HookSpecialDraw, and Terraria.ModLoader.ModTile.SpecialDraw().
TileFrame()
static bool Terraria.ModLoader.TileLoader.TileFrame (int i, int j, int type, ref bool resetFrame, ref bool noBreak) static
Definition at line 756 of file TileLoader.cs.
{
            ModTile modTile = GetTile(type);
            bool flag = true;
            if (modTile != null) {
                flag = modTile.TileFrame(i, j, ref resetFrame, ref noBreak);
            }
            foreach (var hook in HookTileFrame) {
                flag &= hook(i, j, type, ref resetFrame, ref noBreak);
            }
            return flag;
        }
References Terraria.ModLoader.TileLoader.GetTile(), Terraria.ModLoader.TileLoader.HookTileFrame, and Terraria.ModLoader.ModTile.TileFrame().
TreeDust()
static void Terraria.ModLoader.TileLoader.TreeDust (Tile tile, ref int dust) static
Definition at line 956 of file TileLoader.cs.
{
            if (tile.active() && trees.ContainsKey(tile.type)) {
                dust = trees[tile.type].CreateDust();
            }
        }
TreeGrowthFXGore()
static void Terraria.ModLoader.TileLoader.TreeGrowthFXGore (int type, ref int gore) static
Definition at line 962 of file TileLoader.cs.
{
            if (trees.ContainsKey(type)) {
                gore = trees[type].GrowthFXGore();
            }
        }
UnlockChest()
static bool Terraria.ModLoader.TileLoader.UnlockChest (int i, int j, int type, ref short frameXAdjustment, ref int dustType, ref bool manual) static
Definition at line 1046 of file TileLoader.cs.
{
            return GetTile(type)?.UnlockChest(i, j, ref frameXAdjustment, ref dustType, ref manual) ?? false;
        }
References Terraria.ModLoader.TileLoader.GetTile(), and Terraria.ModLoader.ModTile.UnlockChest().
WalkDust()
static void Terraria.ModLoader.TileLoader.WalkDust (int type, ref int dustType, ref bool makeDust, ref Color color) static
Definition at line 909 of file TileLoader.cs.
{
            GetTile(type)?.WalkDust(ref dustType, ref makeDust, ref color);
        }
References Terraria.ModLoader.TileLoader.GetTile(), and Terraria.ModLoader.ModTile.WalkDust().
Member Data Documentation
HookAdjTiles
Func<int, int[]> [] Terraria.ModLoader.TileLoader.HookAdjTiles static private
Definition at line 72 of file TileLoader.cs.
Referenced by Terraria.ModLoader.TileLoader.AdjTiles().
HookAnimateTile
Action [] Terraria.ModLoader.TileLoader.HookAnimateTile static private
Definition at line 62 of file TileLoader.cs.
Referenced by Terraria.ModLoader.TileLoader.AnimateTiles().
HookAutoSelect
Func<int, int, int, Item, bool> [] Terraria.ModLoader.TileLoader.HookAutoSelect static private
Definition at line 76 of file TileLoader.cs.
Referenced by Terraria.ModLoader.TileLoader.AutoSelect().
HookCanExplode
Func<int, int, int, bool> [] Terraria.ModLoader.TileLoader.HookCanExplode static private
Definition at line 55 of file TileLoader.cs.
Referenced by Terraria.ModLoader.TileLoader.CanExplode().
HookCanKillTile
DelegateCanKillTile [] Terraria.ModLoader.TileLoader.HookCanKillTile static private
Definition at line 52 of file TileLoader.cs.
Referenced by Terraria.ModLoader.TileLoader.CanKillTile().
HookCanPlace
Func<int, int, int, bool> [] Terraria.ModLoader.TileLoader.HookCanPlace static private
Definition at line 71 of file TileLoader.cs.
Referenced by Terraria.ModLoader.TileLoader.CanPlace().
HookChangeWaterfallStyle
DelegateChangeWaterfallStyle [] Terraria.ModLoader.TileLoader.HookChangeWaterfallStyle static private
Definition at line 82 of file TileLoader.cs.
Referenced by Terraria.ModLoader.TileLoader.ChangeWaterfallStyle().
HookCreateDust
DelegateCreateDust [] Terraria.ModLoader.TileLoader.HookCreateDust static private
Definition at line 47 of file TileLoader.cs.
Referenced by Terraria.ModLoader.TileLoader.CreateDust().
HookDangersense
Func<int, int, int, Player, bool> [] Terraria.ModLoader.TileLoader.HookDangersense static private
Definition at line 59 of file TileLoader.cs.
Referenced by Terraria.ModLoader.TileLoader.Dangersense().
HookDrawEffects
DelegateDrawEffects [] Terraria.ModLoader.TileLoader.HookDrawEffects static private
Definition at line 65 of file TileLoader.cs.
Referenced by Terraria.ModLoader.TileLoader.DrawEffects().
HookDrop
Func<int, int, int, bool> [] Terraria.ModLoader.TileLoader.HookDrop static private
Definition at line 50 of file TileLoader.cs.
Referenced by Terraria.ModLoader.TileLoader.Drop().
HookDropCritterChance
DelegateDropCritterChance [] Terraria.ModLoader.TileLoader.HookDropCritterChance static private
Definition at line 49 of file TileLoader.cs.
Referenced by Terraria.ModLoader.TileLoader.DropCritterChance().
HookFloorVisuals
Action<int, Player> [] Terraria.ModLoader.TileLoader.HookFloorVisuals static private
Definition at line 80 of file TileLoader.cs.
Referenced by Terraria.ModLoader.TileLoader.FloorVisuals().
HookHitWire
Action<int, int, int> [] Terraria.ModLoader.TileLoader.HookHitWire static private
Definition at line 78 of file TileLoader.cs.
Referenced by Terraria.ModLoader.TileLoader.HitWire().
HookKillSound
Func<int, int, int, bool> [] Terraria.ModLoader.TileLoader.HookKillSound static private
Definition at line 43 of file TileLoader.cs.
Referenced by Terraria.ModLoader.TileLoader.KillSound().
HookKillTile
DelegateKillTile [] Terraria.ModLoader.TileLoader.HookKillTile static private
Definition at line 54 of file TileLoader.cs.
Referenced by Terraria.ModLoader.TileLoader.KillTile().
HookModifyLight
DelegateModifyLight [] Terraria.ModLoader.TileLoader.HookModifyLight static private
Definition at line 58 of file TileLoader.cs.
Referenced by Terraria.ModLoader.TileLoader.ModifyLight().
HookMouseOver
Action<int, int, int> [] Terraria.ModLoader.TileLoader.HookMouseOver static private
Definition at line 74 of file TileLoader.cs.
Referenced by Terraria.ModLoader.TileLoader.MouseOver().
HookMouseOverFar
Action<int, int, int> [] Terraria.ModLoader.TileLoader.HookMouseOverFar static private
Definition at line 75 of file TileLoader.cs.
Referenced by Terraria.ModLoader.TileLoader.MouseOverFar().
HookNearbyEffects
Action<int, int, int, bool> [] Terraria.ModLoader.TileLoader.HookNearbyEffects static private
Definition at line 56 of file TileLoader.cs.
Referenced by Terraria.ModLoader.TileLoader.NearbyEffects().
HookNumDust
DelegateNumDust [] Terraria.ModLoader.TileLoader.HookNumDust static private
Definition at line 45 of file TileLoader.cs.
Referenced by Terraria.ModLoader.TileLoader.NumDust().
HookPlaceInWorld
Action<int, int, Item> [] Terraria.ModLoader.TileLoader.HookPlaceInWorld static private
Definition at line 85 of file TileLoader.cs.
Referenced by Terraria.ModLoader.TileLoader.PlaceInWorld().
HookPostDraw
Action<int, int, int, SpriteBatch> [] Terraria.ModLoader.TileLoader.HookPostDraw static private
Definition at line 66 of file TileLoader.cs.
Referenced by Terraria.ModLoader.TileLoader.PostDraw().
HookPreDraw
Func<int, int, int, SpriteBatch, bool> [] Terraria.ModLoader.TileLoader.HookPreDraw static private
Definition at line 63 of file TileLoader.cs.
Referenced by Terraria.ModLoader.TileLoader.PreDraw().
HookPreHitWire
Func<int, int, int, bool> [] Terraria.ModLoader.TileLoader.HookPreHitWire static private
Definition at line 77 of file TileLoader.cs.
Referenced by Terraria.ModLoader.TileLoader.PreHitWire().
HookRandomUpdate
Action<int, int, int> [] Terraria.ModLoader.TileLoader.HookRandomUpdate static private
Definition at line 68 of file TileLoader.cs.
Referenced by Terraria.ModLoader.TileLoader.RandomUpdate().
HookRightClick
Action<int, int, int> [] Terraria.ModLoader.TileLoader.HookRightClick static private
Definition at line 73 of file TileLoader.cs.
Referenced by Terraria.ModLoader.TileLoader.RightClick().
HookSaplingGrowthType
DelegateSaplingGrowthType [] Terraria.ModLoader.TileLoader.HookSaplingGrowthType static private
Definition at line 84 of file TileLoader.cs.
Referenced by Terraria.ModLoader.TileLoader.SaplingGrowthType().
HookSetSpriteEffects
DelegateSetSpriteEffects [] Terraria.ModLoader.TileLoader.HookSetSpriteEffects static private
Definition at line 61 of file TileLoader.cs.
Referenced by Terraria.ModLoader.TileLoader.SetSpriteEffects().
HookSlope
Func<int, int, int, bool> [] Terraria.ModLoader.TileLoader.HookSlope static private
Definition at line 79 of file TileLoader.cs.
Referenced by Terraria.ModLoader.TileLoader.Slope().
HookSpecialDraw
Action<int, int, int, SpriteBatch> [] Terraria.ModLoader.TileLoader.HookSpecialDraw static private
Definition at line 67 of file TileLoader.cs.
Referenced by Terraria.ModLoader.TileLoader.SpecialDraw().
HookTileFrame
DelegateTileFrame [] Terraria.ModLoader.TileLoader.HookTileFrame static private
Definition at line 70 of file TileLoader.cs.
Referenced by Terraria.ModLoader.TileLoader.TileFrame().
loaded
bool Terraria.ModLoader.TileLoader.loaded = false static private
Definition at line 37 of file TileLoader.cs.
Referenced by Terraria.ModLoader.TileLoader.AnimateTiles().
nextTile
int Terraria.ModLoader.TileLoader.nextTile = TileID.Count static private
Definition at line 31 of file TileLoader.cs.
vanillaChairCount
readonly int Terraria.ModLoader.TileLoader.vanillaChairCount = TileID.Sets.RoomNeeds.CountsAsChair.Length static private
Definition at line 38 of file TileLoader.cs.
vanillaDoorCount
readonly int Terraria.ModLoader.TileLoader.vanillaDoorCount = TileID.Sets.RoomNeeds.CountsAsDoor.Length static private
Definition at line 41 of file TileLoader.cs.
vanillaTableCount
readonly int Terraria.ModLoader.TileLoader.vanillaTableCount = TileID.Sets.RoomNeeds.CountsAsTable.Length static private
Definition at line 39 of file TileLoader.cs.
vanillaTorchCount
readonly int Terraria.ModLoader.TileLoader.vanillaTorchCount = TileID.Sets.RoomNeeds.CountsAsTorch.Length static private
Definition at line 40 of file TileLoader.cs.
Property Documentation
TileCount
int Terraria.ModLoader.TileLoader.TileCount static get
Definition at line 95 of file TileLoader.cs.
Referenced by Terraria.ModLoader.ModRecipe.AddTile(), Terraria.ModLoader.RecipeEditor.AddTile(), Terraria.ModLoader.RecipeFinder.AddTile(), Terraria.ModLoader.RecipeEditor.DeleteTile(), and Terraria.ModLoader.TileLoader.GetTile().