tModLoader: Terraria.ModLoader.BuffLoader Class Reference
Terraria.ModLoader.BuffLoader Class Reference
This serves as the central class from which buff-related functions are supported and carried out.
Static Public Member Functions
static bool CanBeCleared (int buff)
static void CustomBuffTipSize (string buffTip, List< Vector2 > sizes)
static void DrawCustomBuffTip (string buffTip, SpriteBatch spriteBatch, int originX, int originY)
static ModBuff GetBuff (int type)
Gets the ModBuff instance with the given type. If no ModBuff with the given type exists, returns null.
static bool LongerExpertDebuff (int buff)
static void ModifyBuffTip (int buff, ref string tip, ref int rare)
static bool ReApply (int buff, NPC npc, int time, int buffIndex)
static bool ReApply (int buff, Player player, int time, int buffIndex)
static void Update (int buff, NPC npc, ref int buffIndex)
static void Update (int buff, Player player, ref int buffIndex)
Properties
static int BuffCount [get]
Private Member Functions
delegate void DelegateModifyBuffTip (int type, ref string tip, ref int rare)
delegate void DelegateUpdateNPC (int type, NPC npc, ref int buffIndex)
delegate void DelegateUpdatePlayer (int type, Player player, ref int buffIndex)
Static Private Member Functions
static BuffLoader ()
Static Private Attributes
static Action< string, List< Vector2 > >[] HookCustomBuffTipSize
static Action< string, SpriteBatch, int, int >[] HookDrawCustomBuffTip
static DelegateModifyBuffTip[] HookModifyBuffTip
static Func< int, NPC, int, int, bool >[] HookReApplyNPC
static Func< int, Player, int, int, bool >[] HookReApplyPlayer
static DelegateUpdateNPC[] HookUpdateNPC
static DelegateUpdatePlayer[] HookUpdatePlayer
static int nextBuff = BuffID.Count
static readonly bool[] vanillaCanBeCleared = new bool[BuffID.Count]
static readonly bool[] vanillaLongerExpertDebuff = new bool[BuffID.Count]
Detailed Description
This serves as the central class from which buff-related functions are supported and carried out.
Definition at line 14 of file BuffLoader.cs.
Constructor & Destructor Documentation
BuffLoader()
static Terraria.ModLoader.BuffLoader.BuffLoader () static private
Definition at line 34 of file BuffLoader.cs.
{
            for (int k = 0; k < BuffID.Count; k++) {
                vanillaCanBeCleared[k] = true;
            }
            vanillaLongerExpertDebuff[BuffID.Poisoned] = true;
            vanillaLongerExpertDebuff[BuffID.Darkness] = true;
            vanillaLongerExpertDebuff[BuffID.Cursed] = true;
            vanillaLongerExpertDebuff[BuffID.OnFire] = true;
            vanillaLongerExpertDebuff[BuffID.Bleeding] = true;
            vanillaLongerExpertDebuff[BuffID.Confused] = true;
            vanillaLongerExpertDebuff[BuffID.Slow] = true;
            vanillaLongerExpertDebuff[BuffID.Weak] = true;
            vanillaLongerExpertDebuff[BuffID.Silenced] = true;
            vanillaLongerExpertDebuff[BuffID.BrokenArmor] = true;
            vanillaLongerExpertDebuff[BuffID.CursedInferno] = true;
            vanillaLongerExpertDebuff[BuffID.Frostburn] = true;
            vanillaLongerExpertDebuff[BuffID.Chilled] = true;
            vanillaLongerExpertDebuff[BuffID.Frozen] = true;
            vanillaLongerExpertDebuff[BuffID.Ichor] = true;
            vanillaLongerExpertDebuff[BuffID.Venom] = true;
            vanillaLongerExpertDebuff[BuffID.Blackout] = true;
            vanillaCanBeCleared[BuffID.PotionSickness] = false;
            vanillaCanBeCleared[BuffID.Werewolf] = false;
            vanillaCanBeCleared[BuffID.Merfolk] = false;
            vanillaCanBeCleared[BuffID.WaterCandle] = false;
            vanillaCanBeCleared[BuffID.Campfire] = false;
            vanillaCanBeCleared[BuffID.HeartLamp] = false;
            vanillaCanBeCleared[BuffID.NoBuilding] = false;
        }
References Terraria.ModLoader.BuffLoader.vanillaCanBeCleared, and Terraria.ModLoader.BuffLoader.vanillaLongerExpertDebuff.
Member Function Documentation
CanBeCleared()
static bool Terraria.ModLoader.BuffLoader.CanBeCleared (int buff) static
Definition at line 170 of file BuffLoader.cs.
{
            return GetBuff(buff)?.canBeCleared ?? vanillaCanBeCleared[buff];
        }
References Terraria.ModLoader.ModBuff.canBeCleared, Terraria.ModLoader.BuffLoader.GetBuff(), and Terraria.ModLoader.BuffLoader.vanillaCanBeCleared.
CustomBuffTipSize()
static void Terraria.ModLoader.BuffLoader.CustomBuffTipSize (string buffTip, List< Vector2 > sizes) static
Definition at line 183 of file BuffLoader.cs.
{
            foreach (var hook in HookCustomBuffTipSize) {
                hook(buffTip, sizes);
            }
        }
References Terraria.ModLoader.BuffLoader.HookCustomBuffTipSize.
DelegateModifyBuffTip()
delegate void Terraria.ModLoader.BuffLoader.DelegateModifyBuffTip (int type, ref string tip, ref int rare) private
DelegateUpdateNPC()
delegate void Terraria.ModLoader.BuffLoader.DelegateUpdateNPC (int type, NPC npc, ref int buffIndex) private
DelegateUpdatePlayer()
delegate void Terraria.ModLoader.BuffLoader.DelegateUpdatePlayer (int type, Player player, ref int buffIndex) private
DrawCustomBuffTip()
static void Terraria.ModLoader.BuffLoader.DrawCustomBuffTip (string buffTip, SpriteBatch spriteBatch, int originX, int originY) static
Definition at line 189 of file BuffLoader.cs.
{
            foreach (var hook in HookDrawCustomBuffTip) {
                hook(buffTip, spriteBatch, originX, originY);
            }
        }
References Terraria.ModLoader.BuffLoader.HookDrawCustomBuffTip.
GetBuff()
static ModBuff Terraria.ModLoader.BuffLoader.GetBuff (int type) static
Gets the ModBuff instance with the given type. If no ModBuff with the given type exists, returns null.
Definition at line 77 of file BuffLoader.cs.
{
            return type >= BuffID.Count && type < BuffCount ? buffs[type - BuffID.Count] : null;
        }
References Terraria.ModLoader.BuffLoader.BuffCount.
Referenced by Terraria.ModLoader.BuffLoader.CanBeCleared(), Terraria.ModLoader.BuffLoader.LongerExpertDebuff(), Terraria.ModLoader.BuffLoader.ModifyBuffTip(), Terraria.ModLoader.BuffLoader.ReApply(), and Terraria.ModLoader.BuffLoader.Update().
LongerExpertDebuff()
static bool Terraria.ModLoader.BuffLoader.LongerExpertDebuff (int buff) static
Definition at line 166 of file BuffLoader.cs.
{
            return GetBuff(buff)?.longerExpertDebuff ?? vanillaLongerExpertDebuff[buff];
        }
References Terraria.ModLoader.BuffLoader.GetBuff(), Terraria.ModLoader.ModBuff.longerExpertDebuff, and Terraria.ModLoader.BuffLoader.vanillaLongerExpertDebuff.
ModifyBuffTip()
static void Terraria.ModLoader.BuffLoader.ModifyBuffTip (int buff, ref string tip, ref int rare) static
Definition at line 174 of file BuffLoader.cs.
{
            if (IsModBuff(buff)) {
                GetBuff(buff).ModifyBuffTip(ref tip, ref rare);
            }
            foreach (var hook in HookModifyBuffTip) {
                hook(buff, ref tip, ref rare);
            }
        }
References Terraria.ModLoader.BuffLoader.GetBuff(), Terraria.ModLoader.BuffLoader.HookModifyBuffTip, and Terraria.ModLoader.ModBuff.ModifyBuffTip().
ReApply() [1/2]
static bool Terraria.ModLoader.BuffLoader.ReApply (int buff, NPC npc, int time, int buffIndex) static
Definition at line 154 of file BuffLoader.cs.
{
            foreach (var hook in HookReApplyNPC) {
                if (hook(buff, npc, time, buffIndex)) {
                    return true;
                }
            }
            if (IsModBuff(buff)) {
                return GetBuff(buff).ReApply(npc, time, buffIndex);
            }
            return false;
        }
References Terraria.ModLoader.BuffLoader.GetBuff(), Terraria.ModLoader.BuffLoader.HookReApplyNPC, and Terraria.ModLoader.ModBuff.ReApply().
ReApply() [2/2]
static bool Terraria.ModLoader.BuffLoader.ReApply (int buff, Player player, int time, int buffIndex) static
Definition at line 142 of file BuffLoader.cs.
{
            foreach (var hook in HookReApplyPlayer) {
                if (hook(buff, player, time, buffIndex)) {
                    return true;
                }
            }
            if (IsModBuff(buff)) {
                return GetBuff(buff).ReApply(player, time, buffIndex);
            }
            return false;
        }
References Terraria.ModLoader.BuffLoader.GetBuff(), Terraria.ModLoader.BuffLoader.HookReApplyPlayer, and Terraria.ModLoader.ModBuff.ReApply().
Update() [1/2]
static void Terraria.ModLoader.BuffLoader.Update (int buff, NPC npc, ref int buffIndex) static
Definition at line 133 of file BuffLoader.cs.
{
            if (IsModBuff(buff)) {
                GetBuff(buff).Update(npc, ref buffIndex);
            }
            foreach (var hook in HookUpdateNPC) {
                hook(buff, npc, ref buffIndex);
            }
        }
References Terraria.ModLoader.BuffLoader.GetBuff(), Terraria.ModLoader.BuffLoader.HookUpdateNPC, and Terraria.ModLoader.ModBuff.Update().
Update() [2/2]
static void Terraria.ModLoader.BuffLoader.Update (int buff, Player player, ref int buffIndex) static
Definition at line 120 of file BuffLoader.cs.
{
            int originalIndex = buffIndex;
            if (IsModBuff(buff)) {
                GetBuff(buff).Update(player, ref buffIndex);
            }
            foreach (var hook in HookUpdatePlayer) {
                if (buffIndex != originalIndex) {
                    break;
                }
                hook(buff, player, ref buffIndex);
            }
        }
References Terraria.ModLoader.BuffLoader.GetBuff(), Terraria.ModLoader.BuffLoader.HookUpdatePlayer, and Terraria.ModLoader.ModBuff.Update().
Member Data Documentation
HookCustomBuffTipSize
Action<string, List<Vector2> > [] Terraria.ModLoader.BuffLoader.HookCustomBuffTipSize static private
Definition at line 31 of file BuffLoader.cs.
Referenced by Terraria.ModLoader.BuffLoader.CustomBuffTipSize().
HookDrawCustomBuffTip
Action<string, SpriteBatch, int, int> [] Terraria.ModLoader.BuffLoader.HookDrawCustomBuffTip static private
Definition at line 32 of file BuffLoader.cs.
Referenced by Terraria.ModLoader.BuffLoader.DrawCustomBuffTip().
HookModifyBuffTip
DelegateModifyBuffTip [] Terraria.ModLoader.BuffLoader.HookModifyBuffTip static private
Definition at line 30 of file BuffLoader.cs.
Referenced by Terraria.ModLoader.BuffLoader.ModifyBuffTip().
HookReApplyNPC
Func<int, NPC, int, int, bool> [] Terraria.ModLoader.BuffLoader.HookReApplyNPC static private
Definition at line 28 of file BuffLoader.cs.
Referenced by Terraria.ModLoader.BuffLoader.ReApply().
HookReApplyPlayer
Func<int, Player, int, int, bool> [] Terraria.ModLoader.BuffLoader.HookReApplyPlayer static private
Definition at line 27 of file BuffLoader.cs.
Referenced by Terraria.ModLoader.BuffLoader.ReApply().
HookUpdateNPC
DelegateUpdateNPC [] Terraria.ModLoader.BuffLoader.HookUpdateNPC static private
Definition at line 26 of file BuffLoader.cs.
Referenced by Terraria.ModLoader.BuffLoader.Update().
HookUpdatePlayer
DelegateUpdatePlayer [] Terraria.ModLoader.BuffLoader.HookUpdatePlayer static private
Definition at line 24 of file BuffLoader.cs.
Referenced by Terraria.ModLoader.BuffLoader.Update().
nextBuff
int Terraria.ModLoader.BuffLoader.nextBuff = BuffID.Count static private
Definition at line 17 of file BuffLoader.cs.
vanillaCanBeCleared
readonly bool [] Terraria.ModLoader.BuffLoader.vanillaCanBeCleared = new bool[BuffID.Count] static private
Definition at line 21 of file BuffLoader.cs.
Referenced by Terraria.ModLoader.BuffLoader.BuffLoader(), and Terraria.ModLoader.BuffLoader.CanBeCleared().
vanillaLongerExpertDebuff
readonly bool [] Terraria.ModLoader.BuffLoader.vanillaLongerExpertDebuff = new bool[BuffID.Count] static private
Definition at line 20 of file BuffLoader.cs.
Referenced by Terraria.ModLoader.BuffLoader.BuffLoader(), and Terraria.ModLoader.BuffLoader.LongerExpertDebuff().
Property Documentation
BuffCount
int Terraria.ModLoader.BuffLoader.BuffCount static get
Definition at line 72 of file BuffLoader.cs.
Referenced by Terraria.ModLoader.BuffLoader.GetBuff().