tModLoader: Terraria.ModLoader.PlayerHooks Class Reference
Terraria.ModLoader.PlayerHooks Class Reference
This is where all ModPlayer hooks are gathered and called.
Classes
class HookList
Static Public Member Functions
static void AnglerQuestReward (Player player, float rareMultiplier, List< Item > rewardItems)
static bool CanBeHitByNPC (Player player, NPC npc, ref int cooldownSlot)
static bool CanBeHitByProjectile (Player player, Projectile proj)
static bool CanBuyItem (Player player, NPC npc, Item[] shopInventory, Item item)
static ? bool CanHitNPC (Player player, Item item, NPC target)
static ? bool CanHitNPCWithProj (Projectile proj, NPC target)
static bool CanHitPvp (Player player, Item item, Player target)
static bool CanHitPvpWithProj (Projectile proj, Player target)
static bool CanSellItem (Player player, NPC npc, Item[] shopInventory, Item item)
static void CatchFish (Player player, Item fishingRod, int power, int liquidType, int poolSize, int worldLayer, int questFish, ref int caughtType, ref bool junk)
static void clientClone (Player player, Player clientClone)
static bool ConsumeAmmo (Player player, Item weapon, Item ammo)
static void CopyCustomBiomesTo (Player player, Player other)
static bool CustomBiomesMatch (Player player, Player other)
static void DrawEffects (PlayerDrawInfo drawInfo, ref float r, ref float g, ref float b, ref float a, ref bool fullBright)
static void FrameEffects (Player player)
static List< PlayerHeadLayer > GetDrawHeadLayers (Player drawPlayer)
static List< PlayerLayer > GetDrawLayers (Player drawPlayer)
static void GetDyeTraderReward (Player player, List< int > rewardPool)
static void GetFishingLevel (Player player, Item fishingRod, Item bait, ref int fishingLevel)
static void GetHealLife (Player player, Item item, bool quickHeal, ref int healValue)
static void GetHealMana (Player player, Item item, bool quickHeal, ref int healValue)
static Texture2D GetMapBackgroundImage (Player player)
static void GetWeaponCrit (Player player, Item item, ref int crit)
static void GetWeaponDamage (Player player, Item item, ref int damage)
static void GetWeaponKnockback (Player player, Item item, ref float knockback)
static void Hurt (Player player, bool pvp, bool quiet, double damage, int hitDirection, bool crit)
static void Kill (Player player, double damage, int hitDirection, bool pvp, PlayerDeathReason damageSource)
static void MeleeEffects (Player player, Item item, Rectangle hitbox)
static float MeleeSpeedMultiplier (Player player, Item item)
static void ModifyDrawInfo (ref PlayerDrawInfo drawInfo)
static void ModifyHitByNPC (Player player, NPC npc, ref int damage, ref bool crit)
static void ModifyHitByProjectile (Player player, Projectile proj, ref int damage, ref bool crit)
static void ModifyHitNPC (Player player, Item item, NPC target, ref int damage, ref float knockback, ref bool crit)
static void ModifyHitNPCWithProj (Projectile proj, NPC target, ref int damage, ref float knockback, ref bool crit, ref int hitDirection)
static void ModifyHitPvp (Player player, Item item, Player target, ref int damage, ref bool crit)
static void ModifyHitPvpWithProj (Projectile proj, Player target, ref int damage, ref bool crit)
static void ModifyManaCost (Player player, Item item, ref float reduce, ref float mult)
static bool ModifyNurseHeal (Player p, NPC npc, ref int health, ref bool removeDebuffs, ref string chat)
static void ModifyNursePrice (Player p, NPC npc, int health, bool removeDebuffs, ref int price)
static void ModifyScreenPosition (Player player)
static void ModifyWeaponDamage (Player player, Item item, ref float add, ref float mult, ref float flat)
Calls ModItem.HookModifyWeaponDamage, then all GlobalItem.HookModifyWeaponDamage hooks.
static void ModifyZoom (Player player, ref float zoom)
static void NaturalLifeRegen (Player player, ref float regen)
static void OnConsumeAmmo (Player player, Item weapon, Item ammo)
static void OnConsumeMana (Player player, Item item, int manaConsumed)
static void OnEnterWorld (int playerIndex)
static void OnHitAnything (Player player, float x, float y, Entity victim)
static void OnHitByNPC (Player player, NPC npc, int damage, bool crit)
static void OnHitByProjectile (Player player, Projectile proj, int damage, bool crit)
static void OnHitNPC (Player player, Item item, NPC target, int damage, float knockback, bool crit)
static void OnHitNPCWithProj (Projectile proj, NPC target, int damage, float knockback, bool crit)
static void OnHitPvp (Player player, Item item, Player target, int damage, bool crit)
static void OnHitPvpWithProj (Projectile proj, Player target, int damage, bool crit)
static void OnMissingMana (Player player, Item item, int manaNeeded)
static void OnRespawn (Player player)
static void PlayerConnect (int playerIndex)
static void PlayerDisconnect (int playerIndex)
static void PostBuyItem (Player player, NPC npc, Item[] shopInventory, Item item)
static void PostHurt (Player player, bool pvp, bool quiet, double damage, int hitDirection, bool crit)
static void PostItemCheck (Player player)
static void PostNurseHeal (Player player, NPC npc, int health, bool removeDebuffs, int price)
static void PostSavePlayer (Player player)
static void PostSellItem (Player player, NPC npc, Item[] shopInventory, Item item)
static void PostUpdate (Player player)
static void PostUpdateBuffs (Player player)
static void PostUpdateEquips (Player player)
static void PostUpdateMiscEffects (Player player)
static void PostUpdateRunSpeeds (Player player)
static bool PreHurt (Player player, bool pvp, bool quiet, ref int damage, ref int hitDirection, ref bool crit, ref bool customDamage, ref bool playSound, ref bool genGore, ref PlayerDeathReason damageSource)
static bool PreItemCheck (Player player)
static bool PreKill (Player player, double damage, int hitDirection, bool pvp, ref bool playSound, ref bool genGore, ref PlayerDeathReason damageSource)
static void PreSavePlayer (Player player)
static void PreUpdate (Player player)
static void PreUpdateBuffs (Player player)
static void PreUpdateMovement (Player player)
static void ProcessTriggers (Player player, TriggersSet triggersSet)
static void ReceiveCustomBiomes (Player player, BinaryReader reader)
static void ResetEffects (Player player)
static void SendClientChanges (Player player, Player clientPlayer)
static void SendCustomBiomes (Player player, BinaryWriter writer)
static void SetControls (Player player)
static void SetStartInventory (Player player)
static void SetStartInventory (Player player, IList< Item > items)
static IList< Item > SetupStartInventory (Player player, bool mediumcoreDeath=false)
static bool ShiftClickSlot (Player player, Item[] inventory, int context, int slot)
static bool Shoot (Player player, Item item, ref Vector2 position, ref float speedX, ref float speedY, ref int type, ref int damage, ref float knockBack)
static void SyncPlayer (Player player, int toWho, int fromWho, bool newPlayer)
static float TotalMeleeSpeedMultiplier (Player player, Item item)
static int TotalMeleeTime (float useAnimation, Player player, Item item)
static int TotalUseTime (float useTime, Player player, Item item)
static float TotalUseTimeMultiplier (Player player, Item item)
static void UpdateAutopause (Player player)
static void UpdateBadLifeRegen (Player player)
static void UpdateBiomes (Player player)
static void UpdateBiomeVisuals (Player player)
static void UpdateDead (Player player)
static void UpdateEquips (Player player, ref bool wallSpeedBuff, ref bool tileSpeedBuff, ref bool tileRangeBuff)
static void UpdateLifeRegen (Player player)
static void UpdateVanityAccessories (Player player)
static float UseTimeMultiplier (Player player, Item item)
Private Member Functions
delegate bool DelegateCanBeHitByNPC (NPC npc, ref int cooldownSlot)
delegate void DelegateCatchFish (Item fishingRod, Item bait, int power, int liquidType, int poolSize, int worldLayer, int questFish, ref int caughtType, ref bool junk)
delegate void DelegateDrawEffects (PlayerDrawInfo drawInfo, ref float r, ref float g, ref float b, ref float a, ref bool fullBright)
delegate void DelegateGetFishingLevel (Item fishingRod, Item bait, ref int fishingLevel)
delegate void DelegateGetHealLife (Item item, bool quickHeal, ref int healValue)
delegate void DelegateGetHealMana (Item item, bool quickHeal, ref int healValue)
delegate void DelegateGetWeaponCrit (Item item, ref int crit)
delegate void DelegateGetWeaponDamage (Item item, ref int damage)
delegate void DelegateGetWeaponKnockback (Item item, ref float knockback)
delegate void DelegateModifyDrawInfo (ref PlayerDrawInfo drawInfo)
delegate void DelegateModifyHitByNPC (NPC npc, ref int damage, ref bool crit)
delegate void DelegateModifyHitByProjectile (Projectile proj, ref int damage, ref bool crit)
delegate void DelegateModifyHitNPC (Item item, NPC target, ref int damage, ref float knockback, ref bool crit)
delegate void DelegateModifyHitNPCWithProj (Projectile proj, NPC target, ref int damage, ref float knockback, ref bool crit, ref int hitDirection)
delegate void DelegateModifyHitPvp (Item item, Player target, ref int damage, ref bool crit)
delegate void DelegateModifyHitPvpWithProj (Projectile proj, Player target, ref int damage, ref bool crit)
delegate void DelegateModifyManaCost (Item item, ref float reduce, ref float mult)
delegate bool DelegateModifyNurseHeal (NPC npc, ref int health, ref bool removeDebuffs, ref string chatText)
delegate void DelegateModifyNursePrice (NPC npc, int health, bool removeDebuffs, ref int price)
delegate void DelegateModifyWeaponDamage (Item item, ref float add, ref float mult, ref float flat)
delegate void DelegateModifyWeaponDamageOld (Item item, ref float add, ref float mult)
delegate void DelegateModifyZoom (ref float zoom)
delegate void DelegateNaturalLifeRegen (ref float regen)
delegate bool DelegatePreHurt (bool pvp, bool quiet, ref int damage, ref int hitDirection, ref bool crit, ref bool customDamage, ref bool playSound, ref bool genGore, ref PlayerDeathReason damageSource)
delegate bool DelegatePreKill (double damage, int hitDirection, bool pvp, ref bool playSound, ref bool genGore, ref PlayerDeathReason damageSource)
delegate bool DelegateShoot (Item item, ref Vector2 position, ref float speedX, ref float speedY, ref int type, ref int damage, ref float knockBack)
delegate void DelegateUpdateEquips (ref bool wallSpeedBuff, ref bool tileSpeedBuff, ref bool tileRangeBuff)
Static Private Member Functions
static HookList AddHook< F > (Expression< Func< ModPlayer, F > > func)
static bool HasMethod (Type t, string method, params Type[] args)
static bool SendCustomBiomes (ModPlayer modPlayer, BinaryWriter writer)
Static Private Attributes
static HookList HookAnglerQuestReward = AddHook<Action<float, List<Item>>>(p => p.AnglerQuestReward)
static HookList HookCanBeHitByNPC = AddHook<DelegateCanBeHitByNPC>(p => p.CanBeHitByNPC)
static HookList HookCanBeHitByProjectile = AddHook<Func<Projectile, bool>>(p => p.CanBeHitByProjectile)
static HookList HookCanBuyItem = AddHook<Func<NPC, Item[], Item, bool>>(p => p.CanBuyItem)
static HookList HookCanHitNPC = AddHook<Func<Item, NPC, bool?>>(p => p.CanHitNPC)
static HookList HookCanHitNPCWithProj = AddHook<Func<Projectile, NPC, bool?>>(p => p.CanHitNPCWithProj)
static HookList HookCanHitPvp = AddHook<Func<Item, Player, bool>>(p => p.CanHitPvp)
static HookList HookCanHitPvpWithProj = AddHook<Func<Projectile, Player, bool>>(p => p.CanHitPvpWithProj)
static HookList HookCanSellItem = AddHook<Func<NPC, Item[], Item, bool>>(p => p.CanSellItem)
static HookList HookCatchFish = AddHook<DelegateCatchFish>(p => p.CatchFish)
static HookList HookClientClone = AddHook<Action<ModPlayer>>(p => p.clientClone)
static HookList HookConsumeAmmo = AddHook<Func<Item, Item, bool>>(p => p.ConsumeAmmo)
static HookList HookCopyCustomBiomesTo = AddHook<Action<Player>>(p => p.CopyCustomBiomesTo)
static HookList HookCustomBiomesMatch = AddHook<Func<Player, bool>>(p => p.CustomBiomesMatch)
static HookList HookDrawEffects = AddHook<DelegateDrawEffects>(p => p.DrawEffects)
static HookList HookFrameEffects = AddHook<Action>(p => p.FrameEffects)
static HookList HookGetDyeTraderReward = AddHook<Action<List<int>>>(p => p.GetDyeTraderReward)
static HookList HookGetFishingLevel = AddHook<DelegateGetFishingLevel>(p => p.GetFishingLevel)
static HookList HookGetHealLife = AddHook<DelegateGetHealLife>(p => p.GetHealLife)
static HookList HookGetHealMana = AddHook<DelegateGetHealMana>(p => p.GetHealMana)
static HookList HookGetMapBackgroundImage = AddHook<Func<Texture2D>>(p => p.GetMapBackgroundImage)
static HookList HookGetWeaponCrit = AddHook<DelegateGetWeaponCrit>(p => p.GetWeaponCrit)
static HookList HookGetWeaponDamage = AddHook<DelegateGetWeaponDamage>(p => p.GetWeaponDamage)
static HookList HookGetWeaponKnockback = AddHook<DelegateGetWeaponKnockback>(p => p.GetWeaponKnockback)
static HookList HookHurt = AddHook<Action<bool, bool, double, int, bool>>(p => p.Hurt)
static HookList HookKill = AddHook<Action<double, int, bool, PlayerDeathReason>>(p => p.Kill)
static HookList HookMeleeEffects = AddHook<Action<Item, Rectangle>>(p => p.MeleeEffects)
static HookList HookMeleeSpeedMultiplier = AddHook<Func<Item, float>>(p => p.MeleeSpeedMultiplier)
static HookList HookModifyDrawHeadLayers = AddHook<Action<List<PlayerHeadLayer>>>(p => p.ModifyDrawHeadLayers)
static HookList HookModifyDrawInfo = AddHook<DelegateModifyDrawInfo>(p => p.ModifyDrawInfo)
static HookList HookModifyDrawLayers = AddHook<Action<List<PlayerLayer>>>(p => p.ModifyDrawLayers)
static HookList HookModifyHitByNPC = AddHook<DelegateModifyHitByNPC>(p => p.ModifyHitByNPC)
static HookList HookModifyHitByProjectile = AddHook<DelegateModifyHitByProjectile>(p => p.ModifyHitByProjectile)
static HookList HookModifyHitNPC = AddHook<DelegateModifyHitNPC>(p => p.ModifyHitNPC)
static HookList HookModifyHitNPCWithProj = AddHook<DelegateModifyHitNPCWithProj>(p => p.ModifyHitNPCWithProj)
static HookList HookModifyHitPvp = AddHook<DelegateModifyHitPvp>(p => p.ModifyHitPvp)
static HookList HookModifyHitPvpWithProj = AddHook<DelegateModifyHitPvpWithProj>(p => p.ModifyHitPvpWithProj)
static HookList HookModifyManaCost = AddHook<DelegateModifyManaCost>(p => p.ModifyManaCost)
static HookList HookModifyNurseHeal = AddHook<DelegateModifyNurseHeal>(p => p.ModifyNurseHeal)
static HookList HookModifyNursePrice = AddHook<DelegateModifyNursePrice>(p => p.ModifyNursePrice)
static HookList HookModifyScreenPosition = AddHook<Action>(p => p.ModifyScreenPosition)
static HookList HookModifyWeaponDamage = AddHook<DelegateModifyWeaponDamage>(p => p.ModifyWeaponDamage)
static HookList HookModifyWeaponDamageOld = AddHook<DelegateModifyWeaponDamage>(p => p.ModifyWeaponDamage)
static HookList HookModifyZoom = AddHook<DelegateModifyZoom>(p => p.ModifyZoom)
static HookList HookNaturalLifeRegen = AddHook<DelegateNaturalLifeRegen>(p => p.NaturalLifeRegen)
static HookList HookOnConsumeAmmo = AddHook<Action<Item, Item>>(p => p.OnConsumeAmmo)
static HookList HookOnConsumeMana = AddHook<Action<Item, int>>(p => p.OnConsumeMana)
static HookList HookOnEnterWorld = AddHook<Action<Player>>(p => p.OnEnterWorld)
static HookList HookOnHitAnything = AddHook<Action<float, float, Entity>>(p => p.OnHitAnything)
static HookList HookOnHitByNPC = AddHook<Action<NPC, int, bool>>(p => p.OnHitByNPC)
static HookList HookOnHitByProjectile = AddHook<Action<Projectile, int, bool>>(p => p.OnHitByProjectile)
static HookList HookOnHitNPC = AddHook<Action<Item, NPC, int, float, bool>>(p => p.OnHitNPC)
static HookList HookOnHitNPCWithProj = AddHook<Action<Projectile, NPC, int, float, bool>>(p => p.OnHitNPCWithProj)
static HookList HookOnHitPvp = AddHook<Action<Item, Player, int, bool>>(p => p.OnHitPvp)
static HookList HookOnHitPvpWithProj = AddHook<Action<Projectile, Player, int, bool>>(p => p.OnHitPvpWithProj)
static HookList HookOnMissingMana = AddHook<Action<Item, int>>(p => p.OnMissingMana)
static HookList HookOnRespawn = AddHook<Action<Player>>(p => p.OnRespawn)
static HookList HookPlayerConnect = AddHook<Action<Player>>(p => p.PlayerConnect)
static HookList HookPlayerDisconnect = AddHook<Action<Player>>(p => p.PlayerDisconnect)
static HookList HookPostBuyItem = AddHook<Action<NPC, Item[], Item>>(p => p.PostBuyItem)
static HookList HookPostHurt = AddHook<Action<bool, bool, double, int, bool>>(p => p.PostHurt)
static HookList HookPostItemCheck = AddHook<Action>(p => p.PostItemCheck)
static HookList HookPostNurseHeal = AddHook<Action<NPC, int, bool, int>>(p => p.PostNurseHeal)
static HookList HookPostSavePlayer = AddHook<Action>(p => p.PostSavePlayer)
static HookList HookPostSellItem = AddHook<Action<NPC, Item[], Item>>(p => p.PostSellItem)
static HookList HookPostUpdate = AddHook<Action>(p => p.PostUpdate)
static HookList HookPostUpdateBuffs = AddHook<Action>(p => p.PostUpdateBuffs)
static HookList HookPostUpdateEquips = AddHook<Action>(p => p.PostUpdateEquips)
static HookList HookPostUpdateMiscEffects = AddHook<Action>(p => p.PostUpdateMiscEffects)
static HookList HookPostUpdateRunSpeeds = AddHook<Action>(p => p.PostUpdateRunSpeeds)
static HookList HookPreHurt = AddHook<DelegatePreHurt>(p => p.PreHurt)
static HookList HookPreItemCheck = AddHook<Func<bool>>(p => p.PreItemCheck)
static HookList HookPreKill = AddHook<DelegatePreKill>(p => p.PreKill)
static HookList HookPreSavePlayer = AddHook<Action>(p => p.PreSavePlayer)
static HookList HookPreUpdate = AddHook<Action>(p => p.PreUpdate)
static HookList HookPreUpdateBuffs = AddHook<Action>(p => p.PreUpdateBuffs)
static HookList HookPreUpdateMovement = AddHook<Action>(p => p.PreUpdateMovement)
static HookList HookProcessTriggers = AddHook<Action<TriggersSet>>(p => p.ProcessTriggers)
static HookList HookResetEffects = AddHook<Action>(p => p.ResetEffects)
static List< HookList > hooks = new List<HookList>()
static HookList HookSendClientChanges = AddHook<Action<ModPlayer>>(p => p.SendClientChanges)
static HookList HookSendCustomBiomes = AddHook<Action<BinaryWriter>>(p => p.SendCustomBiomes)
static HookList HookSetControls = AddHook<Action>(p => p.SetControls)
static HookList HookSetupStartInventory = AddHook<Action<List<Item>, bool>>(p => p.SetupStartInventory)
static HookList HookSetupStartInventoryOld = AddHook<Action<List<Item>>>(p => p.SetupStartInventory)
static HookList HookShiftClickSlot = AddHook<Func<Item[], int, int, bool>>(p => p.ShiftClickSlot)
static HookList HookShoot = AddHook<DelegateShoot>(p => p.Shoot)
static HookList HookSyncPlayer = AddHook<Action<int, int, bool>>(p => p.SyncPlayer)
static HookList HookUpdateAutopause = AddHook<Action>(p => p.UpdateAutopause)
static HookList HookUpdateBadLifeRegen = AddHook<Action>(p => p.UpdateBadLifeRegen)
static HookList HookUpdateBiomes = AddHook<Action>(p => p.UpdateBiomes)
static HookList HookUpdateBiomeVisuals = AddHook<Action>(p => p.UpdateBiomeVisuals)
static HookList HookUpdateDead = AddHook<Action>(p => p.UpdateDead)
static HookList HookUpdateEquips = AddHook<DelegateUpdateEquips>(p => p.UpdateEquips)
static HookList HookUpdateLifeRegen = AddHook<Action>(p => p.UpdateLifeRegen)
static HookList HookUpdateVanityAccessories = AddHook<Action>(p => p.UpdateVanityAccessories)
static HookList HookUseTimeMultiplier = AddHook<Func<Item, float>>(p => p.UseTimeMultiplier)
static readonly IList< ModPlayer > players = new List<ModPlayer>()
Detailed Description
This is where all ModPlayer hooks are gathered and called.
Definition at line 20 of file PlayerHooks.cs.
Member Function Documentation
AddHook< F >()
static HookList Terraria.ModLoader.PlayerHooks.AddHook< F > (Expression< Func< ModPlayer, F > > func) static private
Definition at line 36 of file PlayerHooks.cs.
{
            var hook = new HookList(ModLoader.Method(func));
            hooks.Add(hook);
            return hook;
        }
References Terraria.ModLoader.PlayerHooks.hooks.
AnglerQuestReward()
static void Terraria.ModLoader.PlayerHooks.AnglerQuestReward (Player player, float rareMultiplier, List< Item > rewardItems) static
Definition at line 936 of file PlayerHooks.cs.
{
            foreach (int index in HookAnglerQuestReward.arr) {
                player.modPlayers[index].AnglerQuestReward(rareMultiplier, rewardItems);
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookAnglerQuestReward.
CanBeHitByNPC()
static bool Terraria.ModLoader.PlayerHooks.CanBeHitByNPC (Player player, NPC npc, ref int cooldownSlot) static
Definition at line 855 of file PlayerHooks.cs.
{
            foreach (int index in HookCanBeHitByNPC.arr) {
                if (!player.modPlayers[index].CanBeHitByNPC(npc, ref cooldownSlot)) {
                    return false;
                }
            }
            return true;
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookCanBeHitByNPC.
CanBeHitByProjectile()
static bool Terraria.ModLoader.PlayerHooks.CanBeHitByProjectile (Player player, Projectile proj) static
Definition at line 883 of file PlayerHooks.cs.
{
            foreach (int index in HookCanBeHitByProjectile.arr) {
                if (!player.modPlayers[index].CanBeHitByProjectile(proj)) {
                    return false;
                }
            }
            return true;
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookCanBeHitByProjectile.
CanBuyItem()
static bool Terraria.ModLoader.PlayerHooks.CanBuyItem (Player player, NPC npc, Item[] shopInventory, Item item) static
Definition at line 1170 of file PlayerHooks.cs.
{
            foreach (int index in HookCanBuyItem.arr) {
                if (!player.modPlayers[index].CanBuyItem(npc, shopInventory, item))
                    return false;
            }
            return true;
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, Terraria.ModLoader.ModPlayer.CanBuyItem(), and Terraria.ModLoader.PlayerHooks.HookCanBuyItem.
CanHitNPC()
static ? bool Terraria.ModLoader.PlayerHooks.CanHitNPC (Player player, Item item, NPC target) static
Definition at line 717 of file PlayerHooks.cs.
{
            bool? flag = null;
            foreach (int index in HookCanHitNPC.arr) {
                bool? canHit = player.modPlayers[index].CanHitNPC(item, target);
                if (canHit.HasValue && !canHit.Value) {
                    return false;
                }
                if (canHit.HasValue) {
                    flag = canHit.Value;
                }
            }
            return flag;
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookCanHitNPC.
CanHitNPCWithProj()
static ? bool Terraria.ModLoader.PlayerHooks.CanHitNPCWithProj (Projectile proj, NPC target) static
Definition at line 750 of file PlayerHooks.cs.
{
            if (proj.npcProj || proj.trap) {
                return null;
            }
            Player player = Main.player[proj.owner];
            bool? flag = null;
            foreach (int index in HookCanHitNPCWithProj.arr) {
                bool? canHit = player.modPlayers[index].CanHitNPCWithProj(proj, target);
                if (canHit.HasValue && !canHit.Value) {
                    return false;
                }
                if (canHit.HasValue) {
                    flag = canHit.Value;
                }
            }
            return flag;
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookCanHitNPCWithProj.
CanHitPvp()
static bool Terraria.ModLoader.PlayerHooks.CanHitPvp (Player player, Item item, Player target) static
Definition at line 795 of file PlayerHooks.cs.
{
            foreach (int index in HookCanHitPvp.arr) {
                if (!player.modPlayers[index].CanHitPvp(item, target)) {
                    return false;
                }
            }
            return true;
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookCanHitPvp.
CanHitPvpWithProj()
static bool Terraria.ModLoader.PlayerHooks.CanHitPvpWithProj (Projectile proj, Player target) static
Definition at line 823 of file PlayerHooks.cs.
{
            Player player = Main.player[proj.owner];
            foreach (int index in HookCanHitPvpWithProj.arr) {
                if (!player.modPlayers[index].CanHitPvpWithProj(proj, target)) {
                    return false;
                }
            }
            return true;
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookCanHitPvpWithProj.
CanSellItem()
static bool Terraria.ModLoader.PlayerHooks.CanSellItem (Player player, NPC npc, Item[] shopInventory, Item item) static
Definition at line 1152 of file PlayerHooks.cs.
{
            foreach (int index in HookCanSellItem.arr) {
                if (!player.modPlayers[index].CanSellItem(npc, shopInventory, item))
                    return false;
            }
            return true;
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, Terraria.ModLoader.ModPlayer.CanSellItem(), and Terraria.ModLoader.PlayerHooks.HookCanSellItem.
CatchFish()
static void Terraria.ModLoader.PlayerHooks.CatchFish (Player player, Item fishingRod, int power, int liquidType, int poolSize, int worldLayer, int questFish, ref int caughtType, ref bool junk) static
Definition at line 912 of file PlayerHooks.cs.
{
            int i = 0;
            while (i < 58) {
                if (player.inventory[i].stack > 0 && player.inventory[i].bait > 0) {
                    break;
                }
                i++;
            }
            foreach (int index in HookCatchFish.arr) {
                player.modPlayers[index].CatchFish(fishingRod, player.inventory[i], power, liquidType, poolSize, worldLayer, questFish, ref caughtType, ref junk);
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookCatchFish.
clientClone()
static void Terraria.ModLoader.PlayerHooks.clientClone (Player player, Player clientClone) static
Definition at line 272 of file PlayerHooks.cs.
{
            foreach (int index in HookClientClone.arr) {
                player.modPlayers[index].clientClone(clientClone.modPlayers[index]);
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, Terraria.ModLoader.PlayerHooks.clientClone(), and Terraria.ModLoader.PlayerHooks.HookClientClone.
Referenced by Terraria.ModLoader.PlayerHooks.clientClone().
ConsumeAmmo()
static bool Terraria.ModLoader.PlayerHooks.ConsumeAmmo (Player player, Item weapon, Item ammo) static
Definition at line 671 of file PlayerHooks.cs.
{
            foreach (int index in HookConsumeAmmo.arr) {
                if (!player.modPlayers[index].ConsumeAmmo(weapon, ammo)) {
                    return false;
                }
            }
            return true;
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookConsumeAmmo.
CopyCustomBiomesTo()
static void Terraria.ModLoader.PlayerHooks.CopyCustomBiomesTo (Player player, Player other) static
Definition at line 195 of file PlayerHooks.cs.
{
            foreach (int index in HookCopyCustomBiomesTo.arr) {
                player.modPlayers[index].CopyCustomBiomesTo(other);
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookCopyCustomBiomesTo.
CustomBiomesMatch()
static bool Terraria.ModLoader.PlayerHooks.CustomBiomesMatch (Player player, Player other) static
Definition at line 184 of file PlayerHooks.cs.
{
            foreach (int index in HookCustomBiomesMatch.arr) {
                if (!player.modPlayers[index].CustomBiomesMatch(other)) {
                    return false;
                }
            }
            return true;
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookCustomBiomesMatch.
DelegateCanBeHitByNPC()
delegate bool Terraria.ModLoader.PlayerHooks.DelegateCanBeHitByNPC (NPC npc, ref int cooldownSlot) private
DelegateCatchFish()
delegate void Terraria.ModLoader.PlayerHooks.DelegateCatchFish (Item fishingRod, Item bait, int power, int liquidType, int poolSize, int worldLayer, int questFish, ref int caughtType, ref bool junk) private
DelegateDrawEffects()
delegate void Terraria.ModLoader.PlayerHooks.DelegateDrawEffects (PlayerDrawInfo drawInfo, ref float r, ref float g, ref float b, ref float a, ref bool fullBright) private
DelegateGetFishingLevel()
delegate void Terraria.ModLoader.PlayerHooks.DelegateGetFishingLevel (Item fishingRod, Item bait, ref int fishingLevel) private
DelegateGetHealLife()
delegate void Terraria.ModLoader.PlayerHooks.DelegateGetHealLife (Item item, bool quickHeal, ref int healValue) private
DelegateGetHealMana()
delegate void Terraria.ModLoader.PlayerHooks.DelegateGetHealMana (Item item, bool quickHeal, ref int healValue) private
DelegateGetWeaponCrit()
delegate void Terraria.ModLoader.PlayerHooks.DelegateGetWeaponCrit (Item item, ref int crit) private
DelegateGetWeaponDamage()
delegate void Terraria.ModLoader.PlayerHooks.DelegateGetWeaponDamage (Item item, ref int damage) private
DelegateGetWeaponKnockback()
delegate void Terraria.ModLoader.PlayerHooks.DelegateGetWeaponKnockback (Item item, ref float knockback) private
DelegateModifyDrawInfo()
delegate void Terraria.ModLoader.PlayerHooks.DelegateModifyDrawInfo (ref PlayerDrawInfo drawInfo) private
DelegateModifyHitByNPC()
delegate void Terraria.ModLoader.PlayerHooks.DelegateModifyHitByNPC (NPC npc, ref int damage, ref bool crit) private
DelegateModifyHitByProjectile()
delegate void Terraria.ModLoader.PlayerHooks.DelegateModifyHitByProjectile (Projectile proj, ref int damage, ref bool crit) private
DelegateModifyHitNPC()
delegate void Terraria.ModLoader.PlayerHooks.DelegateModifyHitNPC (Item item, NPC target, ref int damage, ref float knockback, ref bool crit) private
DelegateModifyHitNPCWithProj()
delegate void Terraria.ModLoader.PlayerHooks.DelegateModifyHitNPCWithProj (Projectile proj, NPC target, ref int damage, ref float knockback, ref bool crit, ref int hitDirection) private
DelegateModifyHitPvp()
delegate void Terraria.ModLoader.PlayerHooks.DelegateModifyHitPvp (Item item, Player target, ref int damage, ref bool crit) private
DelegateModifyHitPvpWithProj()
delegate void Terraria.ModLoader.PlayerHooks.DelegateModifyHitPvpWithProj (Projectile proj, Player target, ref int damage, ref bool crit) private
DelegateModifyManaCost()
delegate void Terraria.ModLoader.PlayerHooks.DelegateModifyManaCost (Item item, ref float reduce, ref float mult) private
DelegateModifyNurseHeal()
delegate bool Terraria.ModLoader.PlayerHooks.DelegateModifyNurseHeal (NPC npc, ref int health, ref bool removeDebuffs, ref string chatText) private
DelegateModifyNursePrice()
delegate void Terraria.ModLoader.PlayerHooks.DelegateModifyNursePrice (NPC npc, int health, bool removeDebuffs, ref int price) private
DelegateModifyWeaponDamage()
delegate void Terraria.ModLoader.PlayerHooks.DelegateModifyWeaponDamage (Item item, ref float add, ref float mult, ref float flat) private
DelegateModifyWeaponDamageOld()
delegate void Terraria.ModLoader.PlayerHooks.DelegateModifyWeaponDamageOld (Item item, ref float add, ref float mult) private
DelegateModifyZoom()
delegate void Terraria.ModLoader.PlayerHooks.DelegateModifyZoom (ref float zoom) private
DelegateNaturalLifeRegen()
delegate void Terraria.ModLoader.PlayerHooks.DelegateNaturalLifeRegen (ref float regen) private
DelegatePreHurt()
delegate bool Terraria.ModLoader.PlayerHooks.DelegatePreHurt (bool pvp, bool quiet, ref int damage, ref int hitDirection, ref bool crit, ref bool customDamage, ref bool playSound, ref bool genGore, ref PlayerDeathReason damageSource) private
DelegatePreKill()
delegate bool Terraria.ModLoader.PlayerHooks.DelegatePreKill (double damage, int hitDirection, bool pvp, ref bool playSound, ref bool genGore, ref PlayerDeathReason damageSource) private
DelegateShoot()
delegate bool Terraria.ModLoader.PlayerHooks.DelegateShoot (Item item, ref Vector2 position, ref float speedX, ref float speedY, ref int type, ref int damage, ref float knockBack) private
DelegateUpdateEquips()
delegate void Terraria.ModLoader.PlayerHooks.DelegateUpdateEquips (ref bool wallSpeedBuff, ref bool tileSpeedBuff, ref bool tileRangeBuff) private
DrawEffects()
static void Terraria.ModLoader.PlayerHooks.DrawEffects (PlayerDrawInfo drawInfo, ref float r, ref float g, ref float b, ref float a, ref bool fullBright) static
Definition at line 953 of file PlayerHooks.cs.
{
            ModPlayer[] modPlayers = drawInfo.drawPlayer.modPlayers;
            foreach (int index in HookDrawEffects.arr) {
                modPlayers[index].DrawEffects(drawInfo, ref r, ref g, ref b, ref a, ref fullBright);
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, Terraria.ModLoader.PlayerDrawInfo.drawPlayer, and Terraria.ModLoader.PlayerHooks.HookDrawEffects.
FrameEffects()
static void Terraria.ModLoader.PlayerHooks.FrameEffects (Player player) static
Definition at line 431 of file PlayerHooks.cs.
{
            foreach (int index in HookFrameEffects.arr) {
                player.modPlayers[index].FrameEffects();
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookFrameEffects.
GetDrawHeadLayers()
static List< PlayerHeadLayer > Terraria.ModLoader.PlayerHooks.GetDrawHeadLayers (Player drawPlayer) static
Definition at line 1025 of file PlayerHooks.cs.
{
            List<PlayerHeadLayer> layers = new List<PlayerHeadLayer> {
                PlayerHeadLayer.Head,
                PlayerHeadLayer.Hair,
                PlayerHeadLayer.AltHair,
                PlayerHeadLayer.Armor,
                PlayerHeadLayer.FaceAcc
            };
            foreach (PlayerHeadLayer layer in layers) {
                layer.visible = true;
            }
            foreach (int index in HookModifyDrawHeadLayers.arr) {
                drawPlayer.modPlayers[index].ModifyDrawHeadLayers(layers);
            }
            return layers;
        }
References Terraria.ModLoader.PlayerHeadLayer.AltHair, Terraria.ModLoader.PlayerHeadLayer.Armor, Terraria.ModLoader.PlayerHooks.HookList.arr, Terraria.ModLoader.PlayerHeadLayer.Hair, Terraria.ModLoader.PlayerHeadLayer.Head, and Terraria.ModLoader.PlayerHooks.HookModifyDrawHeadLayers.
GetDrawLayers()
static List< PlayerLayer > Terraria.ModLoader.PlayerHooks.GetDrawLayers (Player drawPlayer) static
Definition at line 972 of file PlayerHooks.cs.
{
            List<PlayerLayer> layers = new List<PlayerLayer> {
                PlayerLayer.HairBack,
                PlayerLayer.MountBack,
                PlayerLayer.MiscEffectsBack,
                PlayerLayer.BackAcc,
                PlayerLayer.Wings,
                PlayerLayer.BalloonAcc,
                PlayerLayer.Skin
            };
            if (drawPlayer.wearsRobe) {
                layers.Add(PlayerLayer.ShoeAcc);
                layers.Add(PlayerLayer.Legs);
            }
            else {
                layers.Add(PlayerLayer.Legs);
                layers.Add(PlayerLayer.ShoeAcc);
            }
            layers.Add(PlayerLayer.Body);
            layers.Add(PlayerLayer.HandOffAcc);
            layers.Add(PlayerLayer.WaistAcc);
            layers.Add(PlayerLayer.NeckAcc);
            layers.Add(PlayerLayer.Face);
            layers.Add(PlayerLayer.Hair);
            layers.Add(PlayerLayer.Head);
            layers.Add(PlayerLayer.FaceAcc);
            if (drawPlayer.mount.Cart) {
                layers.Add(PlayerLayer.ShieldAcc);
                layers.Add(PlayerLayer.MountFront);
            }
            else {
                layers.Add(PlayerLayer.MountFront);
                layers.Add(PlayerLayer.ShieldAcc);
            }
            layers.Add(PlayerLayer.SolarShield);
            layers.Add(PlayerLayer.HeldProjBack);
            layers.Add(PlayerLayer.HeldItem);
            layers.Add(PlayerLayer.Arms);
            layers.Add(PlayerLayer.HandOnAcc);
            layers.Add(PlayerLayer.HeldProjFront);
            layers.Add(PlayerLayer.FrontAcc);
            layers.Add(PlayerLayer.MiscEffectsFront);
            foreach (PlayerLayer layer in layers) {
                layer.visible = true;
            }
            foreach (int index in HookModifyDrawLayers.arr) {
                drawPlayer.modPlayers[index].ModifyDrawLayers(layers);
            }
            return layers;
        }
References Terraria.ModLoader.PlayerLayer.Arms, Terraria.ModLoader.PlayerHooks.HookList.arr, Terraria.ModLoader.PlayerLayer.BackAcc, Terraria.ModLoader.PlayerLayer.BalloonAcc, Terraria.ModLoader.PlayerLayer.Body, Terraria.ModLoader.PlayerLayer.Face, Terraria.ModLoader.PlayerLayer.FaceAcc, Terraria.ModLoader.PlayerLayer.FrontAcc, Terraria.ModLoader.PlayerLayer.Hair, Terraria.ModLoader.PlayerLayer.HairBack, Terraria.ModLoader.PlayerLayer.HandOffAcc, Terraria.ModLoader.PlayerLayer.HandOnAcc, Terraria.ModLoader.PlayerLayer.Head, Terraria.ModLoader.PlayerLayer.HeldItem, Terraria.ModLoader.PlayerLayer.HeldProjBack, Terraria.ModLoader.PlayerLayer.HeldProjFront, Terraria.ModLoader.PlayerHooks.HookModifyDrawLayers, Terraria.ModLoader.PlayerLayer.Legs, Terraria.ModLoader.PlayerLayer.MiscEffectsBack, Terraria.ModLoader.PlayerLayer.MiscEffectsFront, Terraria.ModLoader.PlayerLayer.MountBack, Terraria.ModLoader.PlayerLayer.MountFront, Terraria.ModLoader.PlayerLayer.NeckAcc, Terraria.ModLoader.PlayerLayer.ShieldAcc, Terraria.ModLoader.PlayerLayer.ShoeAcc, Terraria.ModLoader.PlayerLayer.SolarShield, Terraria.ModLoader.PlayerLayer.WaistAcc, and Terraria.ModLoader.PlayerLayer.Wings.
GetDyeTraderReward()
static void Terraria.ModLoader.PlayerHooks.GetDyeTraderReward (Player player, List< int > rewardPool) static
Definition at line 944 of file PlayerHooks.cs.
{
            foreach (int index in HookGetDyeTraderReward.arr) {
                player.modPlayers[index].GetDyeTraderReward(rewardPool);
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookGetDyeTraderReward.
GetFishingLevel()
static void Terraria.ModLoader.PlayerHooks.GetFishingLevel (Player player, Item fishingRod, Item bait, ref int fishingLevel) static
Definition at line 928 of file PlayerHooks.cs.
{
            foreach (int index in HookGetFishingLevel.arr) {
                player.modPlayers[index].GetFishingLevel(fishingRod, bait, ref fishingLevel);
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookGetFishingLevel.
GetHealLife()
static void Terraria.ModLoader.PlayerHooks.GetHealLife (Player player, Item item, bool quickHeal, ref int healValue) static
Definition at line 552 of file PlayerHooks.cs.
{
            if (item.IsAir)
                return;
            foreach (int index in HookGetHealLife.arr) {
                player.modPlayers[index].GetHealLife(item, quickHeal, ref healValue);
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookGetHealLife.
GetHealMana()
static void Terraria.ModLoader.PlayerHooks.GetHealMana (Player player, Item item, bool quickHeal, ref int healValue) static
Definition at line 564 of file PlayerHooks.cs.
{
            if (item.IsAir)
                return;
            foreach (int index in HookGetHealMana.arr) {
                player.modPlayers[index].GetHealMana(item, quickHeal, ref healValue);
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookGetHealMana.
GetMapBackgroundImage()
static Texture2D Terraria.ModLoader.PlayerHooks.GetMapBackgroundImage (Player player) static
Definition at line 296 of file PlayerHooks.cs.
{
            Texture2D texture = null;
            foreach (int index in HookGetMapBackgroundImage.arr) {
                texture = player.modPlayers[index].GetMapBackgroundImage();
                if (texture != null) {
                    return texture;
                }
            }
            return texture;
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookGetMapBackgroundImage.
GetWeaponCrit()
static void Terraria.ModLoader.PlayerHooks.GetWeaponCrit (Player player, Item item, ref int crit) static
Definition at line 662 of file PlayerHooks.cs.
{
            if (item.IsAir) return;
            foreach (int index in HookGetWeaponCrit.arr) {
                player.modPlayers[index].GetWeaponCrit(item, ref crit);
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookGetWeaponCrit.
GetWeaponDamage()
static void Terraria.ModLoader.PlayerHooks.GetWeaponDamage (Player player, Item item, ref int damage) static
Definition at line 611 of file PlayerHooks.cs.
{
            if (item.IsAir)
                return;
            foreach (int index in HookGetWeaponDamage.arr) {
                player.modPlayers[index].GetWeaponDamage(item, ref damage);
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookGetWeaponDamage.
Referenced by Terraria.ModLoader.CombinedHooks.GetWeaponDamage().
GetWeaponKnockback()
static void Terraria.ModLoader.PlayerHooks.GetWeaponKnockback (Player player, Item item, ref float knockback) static
Definition at line 650 of file PlayerHooks.cs.
{
            if (item.IsAir)
                return;
            foreach (int index in HookGetWeaponKnockback.arr) {
                player.modPlayers[index].GetWeaponKnockback(item, ref knockback);
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookGetWeaponKnockback.
HasMethod()
static bool Terraria.ModLoader.PlayerHooks.HasMethod (Type t, string method, params Type[] args) static private
Definition at line 1106 of file PlayerHooks.cs.
{
            return t.GetMethod(method, args).DeclaringType != typeof(ModPlayer);
        }
Hurt()
static void Terraria.ModLoader.PlayerHooks.Hurt (Player player, bool pvp, bool quiet, double damage, int hitDirection, bool crit) static
Definition at line 455 of file PlayerHooks.cs.
{
            foreach (int index in HookHurt.arr) {
                player.modPlayers[index].Hurt(pvp, quiet, damage, hitDirection, crit);
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookHurt.
Kill()
static void Terraria.ModLoader.PlayerHooks.Kill (Player player, double damage, int hitDirection, bool pvp, PlayerDeathReason damageSource) static
Definition at line 486 of file PlayerHooks.cs.
{
            foreach (int index in HookKill.arr) {
                player.modPlayers[index].Kill(damage, hitDirection, pvp, damageSource);
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookKill.
MeleeEffects()
static void Terraria.ModLoader.PlayerHooks.MeleeEffects (Player player, Item item, Rectangle hitbox) static
Definition at line 701 of file PlayerHooks.cs.
{
            foreach (int index in HookMeleeEffects.arr) {
                player.modPlayers[index].MeleeEffects(item, hitbox);
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookMeleeEffects.
MeleeSpeedMultiplier()
static float Terraria.ModLoader.PlayerHooks.MeleeSpeedMultiplier (Player player, Item item) static
Definition at line 531 of file PlayerHooks.cs.
{
            float multiplier = 1f;
            if (item.IsAir) return multiplier;
            foreach (int index in HookMeleeSpeedMultiplier.arr) {
                multiplier *= player.modPlayers[index].MeleeSpeedMultiplier(item);
            }
            return multiplier;
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookMeleeSpeedMultiplier.
Referenced by Terraria.ModLoader.PlayerHooks.TotalMeleeSpeedMultiplier().
ModifyDrawInfo()
static void Terraria.ModLoader.PlayerHooks.ModifyDrawInfo (ref PlayerDrawInfo drawInfo) static
Definition at line 963 of file PlayerHooks.cs.
{
            ModPlayer[] modPlayers = drawInfo.drawPlayer.modPlayers;
            foreach (int index in HookModifyDrawInfo.arr) {
                modPlayers[index].ModifyDrawInfo(ref drawInfo);
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, Terraria.ModLoader.PlayerHooks.HookModifyDrawInfo, and Terraria.ModLoader.ModPlayer.ModifyDrawInfo().
ModifyHitByNPC()
static void Terraria.ModLoader.PlayerHooks.ModifyHitByNPC (Player player, NPC npc, ref int damage, ref bool crit) static
Definition at line 867 of file PlayerHooks.cs.
{
            foreach (int index in HookModifyHitByNPC.arr) {
                player.modPlayers[index].ModifyHitByNPC(npc, ref damage, ref crit);
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookModifyHitByNPC.
ModifyHitByProjectile()
static void Terraria.ModLoader.PlayerHooks.ModifyHitByProjectile (Player player, Projectile proj, ref int damage, ref bool crit) static
Definition at line 895 of file PlayerHooks.cs.
{
            foreach (int index in HookModifyHitByProjectile.arr) {
                player.modPlayers[index].ModifyHitByProjectile(proj, ref damage, ref crit);
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookModifyHitByProjectile.
ModifyHitNPC()
static void Terraria.ModLoader.PlayerHooks.ModifyHitNPC (Player player, Item item, NPC target, ref int damage, ref float knockback, ref bool crit) static
Definition at line 734 of file PlayerHooks.cs.
{
            foreach (int index in HookModifyHitNPC.arr) {
                player.modPlayers[index].ModifyHitNPC(item, target, ref damage, ref knockback, ref crit);
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookModifyHitNPC.
ModifyHitNPCWithProj()
static void Terraria.ModLoader.PlayerHooks.ModifyHitNPCWithProj (Projectile proj, NPC target, ref int damage, ref float knockback, ref bool crit, ref int hitDirection) static
Definition at line 771 of file PlayerHooks.cs.
{
            if (proj.npcProj || proj.trap) {
                return;
            }
            Player player = Main.player[proj.owner];
            foreach (int index in HookModifyHitNPCWithProj.arr) {
                player.modPlayers[index].ModifyHitNPCWithProj(proj, target, ref damage, ref knockback, ref crit, ref hitDirection);
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookModifyHitNPCWithProj.
ModifyHitPvp()
static void Terraria.ModLoader.PlayerHooks.ModifyHitPvp (Player player, Item item, Player target, ref int damage, ref bool crit) static
Definition at line 807 of file PlayerHooks.cs.
{
            foreach (int index in HookModifyHitPvp.arr) {
                player.modPlayers[index].ModifyHitPvp(item, target, ref damage, ref crit);
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookModifyHitPvp.
ModifyHitPvpWithProj()
static void Terraria.ModLoader.PlayerHooks.ModifyHitPvpWithProj (Projectile proj, Player target, ref int damage, ref bool crit) static
Definition at line 836 of file PlayerHooks.cs.
{
            Player player = Main.player[proj.owner];
            foreach (int index in HookModifyHitPvpWithProj.arr) {
                player.modPlayers[index].ModifyHitPvpWithProj(proj, target, ref damage, ref crit);
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookModifyHitPvpWithProj.
ModifyManaCost()
static void Terraria.ModLoader.PlayerHooks.ModifyManaCost (Player player, Item item, ref float reduce, ref float mult) static
Definition at line 576 of file PlayerHooks.cs.
{
            if (item.IsAir)
                return;
            foreach (int index in HookModifyManaCost.arr) {
                player.modPlayers[index].ModifyManaCost(item, ref reduce, ref mult);
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookModifyManaCost.
Referenced by Terraria.ModLoader.CombinedHooks.ModifyManaCost().
ModifyNurseHeal()
static bool Terraria.ModLoader.PlayerHooks.ModifyNurseHeal (Player p, NPC npc, ref int health, ref bool removeDebuffs, ref string chat) static
Definition at line 1181 of file PlayerHooks.cs.
{
            foreach (int index in HookModifyNurseHeal.arr) {
                if (!p.modPlayers[index].ModifyNurseHeal(npc, ref health, ref removeDebuffs, ref chat))
                    return false;
            }
            return true;
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookModifyNurseHeal.
ModifyNursePrice()
static void Terraria.ModLoader.PlayerHooks.ModifyNursePrice (Player p, NPC npc, int health, bool removeDebuffs, ref int price) static
Definition at line 1192 of file PlayerHooks.cs.
{
            foreach (int index in HookModifyNursePrice.arr) {
                p.modPlayers[index].ModifyNursePrice(npc, health, removeDebuffs, ref price);
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookModifyNursePrice.
ModifyScreenPosition()
static void Terraria.ModLoader.PlayerHooks.ModifyScreenPosition (Player player) static
Definition at line 1044 of file PlayerHooks.cs.
{
            foreach (int index in HookModifyScreenPosition.arr) {
                player.modPlayers[index].ModifyScreenPosition();
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookModifyScreenPosition.
ModifyWeaponDamage()
static void Terraria.ModLoader.PlayerHooks.ModifyWeaponDamage (Player player, Item item, ref float add, ref float mult, ref float flat) static
Calls ModItem.HookModifyWeaponDamage, then all GlobalItem.HookModifyWeaponDamage hooks.
Definition at line 627 of file PlayerHooks.cs.
{
            if (item.IsAir)
                return;
            foreach (int index in HookModifyWeaponDamageOld.arr) {
                player.modPlayers[index].ModifyWeaponDamage(item, ref add, ref mult);
            }
            foreach (int index in HookModifyWeaponDamage.arr) {
                player.modPlayers[index].ModifyWeaponDamage(item, ref add, ref mult, ref flat);
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, Terraria.ModLoader.PlayerHooks.HookModifyWeaponDamage, and Terraria.ModLoader.PlayerHooks.HookModifyWeaponDamageOld.
Referenced by Terraria.ModLoader.CombinedHooks.ModifyWeaponDamage().
ModifyZoom()
static void Terraria.ModLoader.PlayerHooks.ModifyZoom (Player player, ref float zoom) static
Definition at line 1053 of file PlayerHooks.cs.
{
            foreach (int index in HookModifyZoom.arr) {
                player.modPlayers[index].ModifyZoom(ref zoom);
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookModifyZoom.
NaturalLifeRegen()
static void Terraria.ModLoader.PlayerHooks.NaturalLifeRegen (Player player, ref float regen) static
Definition at line 326 of file PlayerHooks.cs.
{
            foreach (int index in HookNaturalLifeRegen.arr) {
                player.modPlayers[index].NaturalLifeRegen(ref regen);
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookNaturalLifeRegen.
OnConsumeAmmo()
static void Terraria.ModLoader.PlayerHooks.OnConsumeAmmo (Player player, Item weapon, Item ammo) static
Definition at line 682 of file PlayerHooks.cs.
{
            foreach (int index in HookOnConsumeAmmo.arr)
                player.modPlayers[index].OnConsumeAmmo(weapon, ammo);
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookOnConsumeAmmo.
OnConsumeMana()
static void Terraria.ModLoader.PlayerHooks.OnConsumeMana (Player player, Item item, int manaConsumed) static
Definition at line 598 of file PlayerHooks.cs.
{
            if (item.IsAir)
                return;
            foreach (int index in HookOnConsumeMana.arr) {
                player.modPlayers[index].OnConsumeMana(item, manaConsumed);
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookOnConsumeMana.
Referenced by Terraria.ModLoader.CombinedHooks.OnConsumeMana().
OnEnterWorld()
static void Terraria.ModLoader.PlayerHooks.OnEnterWorld (int playerIndex) static
Definition at line 1080 of file PlayerHooks.cs.
{
            var player = Main.player[playerIndex];
            foreach (int index in HookOnEnterWorld.arr) {
                player.modPlayers[index].OnEnterWorld(player);
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookOnEnterWorld.
OnHitAnything()
static void Terraria.ModLoader.PlayerHooks.OnHitAnything (Player player, float x, float y, Entity victim) static
Definition at line 709 of file PlayerHooks.cs.
{
            foreach (int index in HookOnHitAnything.arr) {
                player.modPlayers[index].OnHitAnything(x, y, victim);
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookOnHitAnything.
OnHitByNPC()
static void Terraria.ModLoader.PlayerHooks.OnHitByNPC (Player player, NPC npc, int damage, bool crit) static
Definition at line 875 of file PlayerHooks.cs.
{
            foreach (int index in HookOnHitByNPC.arr) {
                player.modPlayers[index].OnHitByNPC(npc, damage, crit);
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookOnHitByNPC.
OnHitByProjectile()
static void Terraria.ModLoader.PlayerHooks.OnHitByProjectile (Player player, Projectile proj, int damage, bool crit) static
Definition at line 903 of file PlayerHooks.cs.
{
            foreach (int index in HookOnHitByProjectile.arr) {
                player.modPlayers[index].OnHitByProjectile(proj, damage, crit);
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookOnHitByProjectile.
OnHitNPC()
static void Terraria.ModLoader.PlayerHooks.OnHitNPC (Player player, Item item, NPC target, int damage, float knockback, bool crit) static
Definition at line 742 of file PlayerHooks.cs.
{
            foreach (int index in HookOnHitNPC.arr) {
                player.modPlayers[index].OnHitNPC(item, target, damage, knockback, crit);
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookOnHitNPC.
OnHitNPCWithProj()
static void Terraria.ModLoader.PlayerHooks.OnHitNPCWithProj (Projectile proj, NPC target, int damage, float knockback, bool crit) static
Definition at line 783 of file PlayerHooks.cs.
{
            if (proj.npcProj || proj.trap) {
                return;
            }
            Player player = Main.player[proj.owner];
            foreach (int index in HookOnHitNPCWithProj.arr) {
                player.modPlayers[index].OnHitNPCWithProj(proj, target, damage, knockback, crit);
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookOnHitNPCWithProj.
OnHitPvp()
static void Terraria.ModLoader.PlayerHooks.OnHitPvp (Player player, Item item, Player target, int damage, bool crit) static
Definition at line 815 of file PlayerHooks.cs.
{
            foreach (int index in HookOnHitPvp.arr) {
                player.modPlayers[index].OnHitPvp(item, target, damage, crit);
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookOnHitPvp.
OnHitPvpWithProj()
static void Terraria.ModLoader.PlayerHooks.OnHitPvpWithProj (Projectile proj, Player target, int damage, bool crit) static
Definition at line 845 of file PlayerHooks.cs.
{
            Player player = Main.player[proj.owner];
            foreach (int index in HookOnHitPvpWithProj.arr) {
                player.modPlayers[index].OnHitPvpWithProj(proj, target, damage, crit);
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookOnHitPvpWithProj.
OnMissingMana()
static void Terraria.ModLoader.PlayerHooks.OnMissingMana (Player player, Item item, int manaNeeded) static
Definition at line 587 of file PlayerHooks.cs.
{
            if (item.IsAir)
                return;
            foreach (int index in HookOnMissingMana.arr) {
                player.modPlayers[index].OnMissingMana(item, manaNeeded);
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookOnMissingMana.
Referenced by Terraria.ModLoader.CombinedHooks.OnMissingMana().
OnRespawn()
static void Terraria.ModLoader.PlayerHooks.OnRespawn (Player player) static
Definition at line 1089 of file PlayerHooks.cs.
{
            foreach (int index in HookOnRespawn.arr) {
                player.modPlayers[index].OnRespawn(player);
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookOnRespawn.
PlayerConnect()
static void Terraria.ModLoader.PlayerHooks.PlayerConnect (int playerIndex) static
Definition at line 1061 of file PlayerHooks.cs.
{
            var player = Main.player[playerIndex];
            foreach (int index in HookPlayerConnect.arr) {
                player.modPlayers[index].PlayerConnect(player);
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookPlayerConnect.
PlayerDisconnect()
static void Terraria.ModLoader.PlayerHooks.PlayerDisconnect (int playerIndex) static
Definition at line 1070 of file PlayerHooks.cs.
{
            var player = Main.player[playerIndex];
            foreach (int index in HookPlayerDisconnect.arr) {
                player.modPlayers[index].PlayerDisconnect(player);
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookPlayerDisconnect.
PostBuyItem()
static void Terraria.ModLoader.PlayerHooks.PostBuyItem (Player player, NPC npc, Item[] shopInventory, Item item) static
Definition at line 1162 of file PlayerHooks.cs.
{
            foreach (int index in HookPostBuyItem.arr) {
                player.modPlayers[index].PostBuyItem(npc, shopInventory, item);
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, Terraria.ModLoader.PlayerHooks.HookPostBuyItem, and Terraria.ModLoader.ModPlayer.PostBuyItem().
PostHurt()
static void Terraria.ModLoader.PlayerHooks.PostHurt (Player player, bool pvp, bool quiet, double damage, int hitDirection, bool crit) static
Definition at line 463 of file PlayerHooks.cs.
{
            foreach (int index in HookPostHurt.arr) {
                player.modPlayers[index].PostHurt(pvp, quiet, damage, hitDirection, crit);
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookPostHurt.
PostItemCheck()
static void Terraria.ModLoader.PlayerHooks.PostItemCheck (Player player) static
Definition at line 504 of file PlayerHooks.cs.
{
            foreach (int index in HookPostItemCheck.arr) {
                player.modPlayers[index].PostItemCheck();
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookPostItemCheck.
PostNurseHeal()
static void Terraria.ModLoader.PlayerHooks.PostNurseHeal (Player player, NPC npc, int health, bool removeDebuffs, int price) static
Definition at line 1200 of file PlayerHooks.cs.
{
            foreach (int index in HookPostNurseHeal.arr) {
                player.modPlayers[index].PostNurseHeal(npc, health, removeDebuffs, price);
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, Terraria.ModLoader.PlayerHooks.HookPostNurseHeal, and Terraria.ModLoader.ModPlayer.PostNurseHeal().
PostSavePlayer()
static void Terraria.ModLoader.PlayerHooks.PostSavePlayer (Player player) static
Definition at line 168 of file PlayerHooks.cs.
{
            foreach (int index in HookPostSavePlayer.arr) {
                player.modPlayers[index].PostSavePlayer();
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookPostSavePlayer.
PostSellItem()
static void Terraria.ModLoader.PlayerHooks.PostSellItem (Player player, NPC npc, Item[] shopInventory, Item item) static
Definition at line 1143 of file PlayerHooks.cs.
{
            foreach (int index in HookPostSellItem.arr) {
                player.modPlayers[index].PostSellItem(npc, shopInventory, item);
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, Terraria.ModLoader.PlayerHooks.HookPostSellItem, and Terraria.ModLoader.ModPlayer.PostSellItem().
PostUpdate()
static void Terraria.ModLoader.PlayerHooks.PostUpdate (Player player) static
Definition at line 423 of file PlayerHooks.cs.
{
            foreach (int index in HookPostUpdate.arr) {
                player.modPlayers[index].PostUpdate();
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookPostUpdate.
PostUpdateBuffs()
static void Terraria.ModLoader.PlayerHooks.PostUpdateBuffs (Player player) static
Definition at line 366 of file PlayerHooks.cs.
{
            foreach (int index in HookPostUpdateBuffs.arr) {
                player.modPlayers[index].PostUpdateBuffs();
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookPostUpdateBuffs.
PostUpdateEquips()
static void Terraria.ModLoader.PlayerHooks.PostUpdateEquips (Player player) static
Definition at line 391 of file PlayerHooks.cs.
{
            foreach (int index in HookPostUpdateEquips.arr) {
                player.modPlayers[index].PostUpdateEquips();
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookPostUpdateEquips.
PostUpdateMiscEffects()
static void Terraria.ModLoader.PlayerHooks.PostUpdateMiscEffects (Player player) static
Definition at line 399 of file PlayerHooks.cs.
{
            foreach (int index in HookPostUpdateMiscEffects.arr) {
                player.modPlayers[index].PostUpdateMiscEffects();
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookPostUpdateMiscEffects.
PostUpdateRunSpeeds()
static void Terraria.ModLoader.PlayerHooks.PostUpdateRunSpeeds (Player player) static
Definition at line 407 of file PlayerHooks.cs.
{
            foreach (int index in HookPostUpdateRunSpeeds.arr) {
                player.modPlayers[index].PostUpdateRunSpeeds();
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookPostUpdateRunSpeeds.
PreHurt()
static bool Terraria.ModLoader.PlayerHooks.PreHurt (Player player, bool pvp, bool quiet, ref int damage, ref int hitDirection, ref bool crit, ref bool customDamage, ref bool playSound, ref bool genGore, ref PlayerDeathReason damageSource) static
Definition at line 441 of file PlayerHooks.cs.
{
            bool flag = true;
            foreach (int index in HookPreHurt.arr) {
                if (!player.modPlayers[index].PreHurt(pvp, quiet, ref damage, ref hitDirection, ref crit, ref customDamage,
                        ref playSound, ref genGore, ref damageSource)) {
                    flag = false;
                }
            }
            return flag;
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookPreHurt.
PreItemCheck()
static bool Terraria.ModLoader.PlayerHooks.PreItemCheck (Player player) static
Definition at line 494 of file PlayerHooks.cs.
{
            bool result = true;
            foreach (int index in HookPreItemCheck.arr) {
                result &= player.modPlayers[index].PreItemCheck();
            }
            return result;
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookPreItemCheck.
PreKill()
static bool Terraria.ModLoader.PlayerHooks.PreKill (Player player, double damage, int hitDirection, bool pvp, ref bool playSound, ref bool genGore, ref PlayerDeathReason damageSource) static
Definition at line 473 of file PlayerHooks.cs.
{
            bool flag = true;
            foreach (int index in HookPreKill.arr) {
                if (!player.modPlayers[index].PreKill(damage, hitDirection, pvp, ref playSound, ref genGore, ref damageSource)) {
                    flag = false;
                }
            }
            return flag;
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookPreKill.
PreSavePlayer()
static void Terraria.ModLoader.PlayerHooks.PreSavePlayer (Player player) static
Definition at line 160 of file PlayerHooks.cs.
{
            foreach (int index in HookPreSavePlayer.arr) {
                player.modPlayers[index].PreSavePlayer();
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookPreSavePlayer.
PreUpdate()
static void Terraria.ModLoader.PlayerHooks.PreUpdate (Player player) static
Definition at line 342 of file PlayerHooks.cs.
{
            foreach (int index in HookPreUpdate.arr) {
                player.modPlayers[index].PreUpdate();
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookPreUpdate.
PreUpdateBuffs()
static void Terraria.ModLoader.PlayerHooks.PreUpdateBuffs (Player player) static
Definition at line 358 of file PlayerHooks.cs.
{
            foreach (int index in HookPreUpdateBuffs.arr) {
                player.modPlayers[index].PreUpdateBuffs();
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookPreUpdateBuffs.
PreUpdateMovement()
static void Terraria.ModLoader.PlayerHooks.PreUpdateMovement (Player player) static
Definition at line 415 of file PlayerHooks.cs.
{
            foreach (int index in HookPreUpdateMovement.arr) {
                player.modPlayers[index].PreUpdateMovement();
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookPreUpdateMovement.
ProcessTriggers()
static void Terraria.ModLoader.PlayerHooks.ProcessTriggers (Player player, TriggersSet triggersSet) static
Definition at line 641 of file PlayerHooks.cs.
{
            foreach (int index in HookProcessTriggers.arr) {
                player.modPlayers[index].ProcessTriggers(triggersSet);
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookProcessTriggers.
ReceiveCustomBiomes()
static void Terraria.ModLoader.PlayerHooks.ReceiveCustomBiomes (Player player, BinaryReader reader) static
Definition at line 240 of file PlayerHooks.cs.
{
            int count = reader.ReadUInt16();
            for (int k = 0; k < count; k++) {
                string modName = reader.ReadString();
                string name = reader.ReadString();
                byte[] data = reader.ReadBytes(reader.ReadByte());
                Mod mod = ModLoader.GetMod(modName);
                ModPlayer modPlayer = mod == null ? null : player.GetModPlayer(mod, name);
                if (modPlayer != null) {
                    using (MemoryStream stream = new MemoryStream(data)) {
                        using (BinaryReader customReader = new BinaryReader(stream)) {
                            try {
                                modPlayer.ReceiveCustomBiomes(customReader);
                            }
                            catch {
                            }
                        }
                    }
                }
            }
        }
References Terraria.ModLoader.ModLoader.GetMod(), and Terraria.ModLoader.ModPlayer.ReceiveCustomBiomes().
ResetEffects()
static void Terraria.ModLoader.PlayerHooks.ResetEffects (Player player) static
Definition at line 63 of file PlayerHooks.cs.
{
            foreach (int index in HookResetEffects.arr) {
                player.modPlayers[index].ResetEffects();
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookResetEffects.
SendClientChanges()
static void Terraria.ModLoader.PlayerHooks.SendClientChanges (Player player, Player clientPlayer) static
Definition at line 288 of file PlayerHooks.cs.
{
            foreach (int index in HookSendClientChanges.arr) {
                player.modPlayers[index].SendClientChanges(clientPlayer.modPlayers[index]);
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookSendClientChanges.
SendCustomBiomes() [1/2]
static bool Terraria.ModLoader.PlayerHooks.SendCustomBiomes (ModPlayer modPlayer, BinaryWriter writer) static private
Definition at line 221 of file PlayerHooks.cs.
{
            byte[] data;
            using (MemoryStream stream = new MemoryStream()) {
                using (BinaryWriter customWriter = new BinaryWriter(stream)) {
                    modPlayer.SendCustomBiomes(customWriter);
                    customWriter.Flush();
                    data = stream.ToArray();
                }
            }
            if (data.Length > 0) {
                writer.Write(modPlayer.mod.Name);
                writer.Write(modPlayer.Name);
                writer.Write((byte)data.Length);
                writer.Write(data);
                return true;
            }
            return false;
        }
References Terraria.ModLoader.ModPlayer.mod, Terraria.ModLoader.Mod.Name, Terraria.ModLoader.ModPlayer.Name, and Terraria.ModLoader.ModPlayer.SendCustomBiomes().
SendCustomBiomes() [2/2]
static void Terraria.ModLoader.PlayerHooks.SendCustomBiomes (Player player, BinaryWriter writer) static
Definition at line 203 of file PlayerHooks.cs.
{
            ushort count = 0;
            byte[] data;
            using (MemoryStream stream = new MemoryStream()) {
                using (BinaryWriter customWriter = new BinaryWriter(stream)) {
                    foreach (int index in HookSendCustomBiomes.arr) {
                        if (SendCustomBiomes(player.modPlayers[index], customWriter)) {
                            count++;
                        }
                    }
                    customWriter.Flush();
                    data = stream.ToArray();
                }
            }
            writer.Write(count);
            writer.Write(data);
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, Terraria.ModLoader.PlayerHooks.HookSendCustomBiomes, and Terraria.ModLoader.PlayerHooks.SendCustomBiomes().
Referenced by Terraria.ModLoader.PlayerHooks.SendCustomBiomes().
SetControls()
static void Terraria.ModLoader.PlayerHooks.SetControls (Player player) static
Definition at line 350 of file PlayerHooks.cs.
{
            foreach (int index in HookSetControls.arr) {
                player.modPlayers[index].SetControls();
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookSetControls.
SetStartInventory() [1/2]
static void Terraria.ModLoader.PlayerHooks.SetStartInventory (Player player) static
Definition at line 154 of file PlayerHooks.cs.
{
            SetStartInventory(player, SetupStartInventory(player));
        }
References Terraria.ModLoader.PlayerHooks.SetStartInventory(), and Terraria.ModLoader.PlayerHooks.SetupStartInventory().
SetStartInventory() [2/2]
static void Terraria.ModLoader.PlayerHooks.SetStartInventory (Player player, IList< Item > items) static
Definition at line 136 of file PlayerHooks.cs.
{
            if (items.Count <= 50) {
                for (int k = 0; k < items.Count && k < 49; k++)
                    player.inventory[k] = items[k];
            }
            else {
                for (int k = 0; k < 49; k++) {
                    player.inventory[k] = items[k];
                }
                Item bag = new Item();
                bag.SetDefaults(ModContent.ItemType<StartBag>());
                for (int k = 49; k < items.Count; k++) {
                    ((StartBag)bag.modItem).AddItem(items[k]);
                }
                player.inventory[49] = bag;
            }
        }
References Terraria.ModLoader.Item.
Referenced by Terraria.ModLoader.PlayerHooks.SetStartInventory().
SetupStartInventory()
static IList< Item > Terraria.ModLoader.PlayerHooks.SetupStartInventory (Player player, bool mediumcoreDeath = false) static
Definition at line 80 of file PlayerHooks.cs.
{
            IList<Item> items = new List<Item>();
            Item item = new Item();
            item.SetDefaults(3507);
            item.Prefix(-1);
            items.Add(item);
            item = new Item();
            item.SetDefaults(3509);
            item.Prefix(-1);
            items.Add(item);
            item = new Item();
            item.SetDefaults(3506);
            item.Prefix(-1);
            items.Add(item);
            if (Main.cEd && !mediumcoreDeath) {
                item = new Item();
                item.SetDefaults(603);
                items.Add(item);
            }
            foreach (int index in HookSetupStartInventory.arr) {
                player.modPlayers[index].SetupStartInventory(items, mediumcoreDeath);
            }
            foreach (int index in HookSetupStartInventoryOld.arr) {
                player.modPlayers[index].SetupStartInventory(items);
            }
            IDictionary<int, int> counts = new Dictionary<int, int>();
            foreach (Item item0 in items) {
                if (item0.maxStack > 1) {
                    if (!counts.ContainsKey(item0.netID)) {
                        counts[item0.netID] = 0;
                    }
                    counts[item0.netID] += item0.stack;
                }
            }
            int k = 0;
            while (k < items.Count) {
                bool flag = true;
                int id = items[k].netID;
                if (counts.ContainsKey(id)) {
                    items[k].stack = counts[id];
                    if (items[k].stack > items[k].maxStack) {
                        items[k].stack = items[k].maxStack;
                    }
                    counts[id] -= items[k].stack;
                    if (items[k].stack <= 0) {
                        items.RemoveAt(k);
                        flag = false;
                    }
                }
                if (flag) {
                    k++;
                }
            }
            return items;
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, Terraria.ModLoader.PlayerHooks.HookSetupStartInventory, Terraria.ModLoader.PlayerHooks.HookSetupStartInventoryOld, and Terraria.ModLoader.Item.
Referenced by Terraria.ModLoader.PlayerHooks.SetStartInventory().
ShiftClickSlot()
static bool Terraria.ModLoader.PlayerHooks.ShiftClickSlot (Player player, Item[] inventory, int context, int slot) static
Definition at line 1097 of file PlayerHooks.cs.
{
            foreach (int index in HookShiftClickSlot.arr) {
                if (player.modPlayers[index].ShiftClickSlot(inventory, context, slot)) {
                    return true;
                }
            }
            return false;
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookShiftClickSlot.
Shoot()
static bool Terraria.ModLoader.PlayerHooks.Shoot (Player player, Item item, ref Vector2 position, ref float speedX, ref float speedY, ref int type, ref int damage, ref float knockBack) static
Definition at line 690 of file PlayerHooks.cs.
{
            foreach (int index in HookShoot.arr) {
                if (!player.modPlayers[index].Shoot(item, ref position, ref speedX, ref speedY, ref type, ref damage, ref knockBack)) {
                    return false;
                }
            }
            return true;
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookShoot.
SyncPlayer()
static void Terraria.ModLoader.PlayerHooks.SyncPlayer (Player player, int toWho, int fromWho, bool newPlayer) static
Definition at line 280 of file PlayerHooks.cs.
{
            foreach (int index in HookSyncPlayer.arr) {
                player.modPlayers[index].SyncPlayer(toWho, fromWho, newPlayer);
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookSyncPlayer.
TotalMeleeSpeedMultiplier()
static float Terraria.ModLoader.PlayerHooks.TotalMeleeSpeedMultiplier (Player player, Item item) static
Definition at line 540 of file PlayerHooks.cs.
{
            return TotalUseTimeMultiplier(player, item) * MeleeSpeedMultiplier(player, item)
                * ItemLoader.MeleeSpeedMultiplier(item, player);
        }
References Terraria.ModLoader.ItemLoader.MeleeSpeedMultiplier(), Terraria.ModLoader.PlayerHooks.MeleeSpeedMultiplier(), and Terraria.ModLoader.PlayerHooks.TotalUseTimeMultiplier().
Referenced by Terraria.ModLoader.PlayerHooks.TotalMeleeTime().
TotalMeleeTime()
static int Terraria.ModLoader.PlayerHooks.TotalMeleeTime (float useAnimation, Player player, Item item) static
Definition at line 545 of file PlayerHooks.cs.
{
            return Math.Max(2, (int)(useAnimation / TotalMeleeSpeedMultiplier(player, item)));
        }
References Terraria.ModLoader.PlayerHooks.TotalMeleeSpeedMultiplier().
TotalUseTime()
static int Terraria.ModLoader.PlayerHooks.TotalUseTime (float useTime, Player player, Item item) static
Definition at line 525 of file PlayerHooks.cs.
{
            return Math.Max(2, (int)(useTime / TotalUseTimeMultiplier(player, item)));
        }
References Terraria.ModLoader.PlayerHooks.TotalUseTimeMultiplier().
TotalUseTimeMultiplier()
static float Terraria.ModLoader.PlayerHooks.TotalUseTimeMultiplier (Player player, Item item) static
Definition at line 521 of file PlayerHooks.cs.
{
            return UseTimeMultiplier(player, item) * ItemLoader.UseTimeMultiplier(item, player);
        }
References Terraria.ModLoader.ItemLoader.UseTimeMultiplier(), and Terraria.ModLoader.PlayerHooks.UseTimeMultiplier().
Referenced by Terraria.ModLoader.PlayerHooks.TotalMeleeSpeedMultiplier(), and Terraria.ModLoader.PlayerHooks.TotalUseTime().
UpdateAutopause()
static void Terraria.ModLoader.PlayerHooks.UpdateAutopause (Player player) static
Definition at line 334 of file PlayerHooks.cs.
{
            foreach (int index in HookUpdateAutopause.arr) {
                player.modPlayers[index].UpdateAutopause();
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookUpdateAutopause.
UpdateBadLifeRegen()
static void Terraria.ModLoader.PlayerHooks.UpdateBadLifeRegen (Player player) static
Definition at line 309 of file PlayerHooks.cs.
{
            foreach (int index in HookUpdateBadLifeRegen.arr) {
                player.modPlayers[index].UpdateBadLifeRegen();
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookUpdateBadLifeRegen.
UpdateBiomes()
static void Terraria.ModLoader.PlayerHooks.UpdateBiomes (Player player) static
Definition at line 176 of file PlayerHooks.cs.
{
            foreach (int index in HookUpdateBiomes.arr) {
                player.modPlayers[index].UpdateBiomes();
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookUpdateBiomes.
UpdateBiomeVisuals()
static void Terraria.ModLoader.PlayerHooks.UpdateBiomeVisuals (Player player) static
Definition at line 264 of file PlayerHooks.cs.
{
            foreach (int index in HookUpdateBiomeVisuals.arr) {
                player.modPlayers[index].UpdateBiomeVisuals();
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookUpdateBiomeVisuals.
UpdateDead()
static void Terraria.ModLoader.PlayerHooks.UpdateDead (Player player) static
Definition at line 71 of file PlayerHooks.cs.
{
            foreach (int index in HookUpdateDead.arr) {
                player.modPlayers[index].UpdateDead();
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookUpdateDead.
UpdateEquips()
static void Terraria.ModLoader.PlayerHooks.UpdateEquips (Player player, ref bool wallSpeedBuff, ref bool tileSpeedBuff, ref bool tileRangeBuff) static
Definition at line 375 of file PlayerHooks.cs.
{
            foreach (int index in HookUpdateEquips.arr) {
                player.modPlayers[index].UpdateEquips(ref wallSpeedBuff, ref tileSpeedBuff, ref tileRangeBuff);
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookUpdateEquips.
UpdateLifeRegen()
static void Terraria.ModLoader.PlayerHooks.UpdateLifeRegen (Player player) static
Definition at line 317 of file PlayerHooks.cs.
{
            foreach (int index in HookUpdateLifeRegen.arr) {
                player.modPlayers[index].UpdateLifeRegen();
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookUpdateLifeRegen.
UpdateVanityAccessories()
static void Terraria.ModLoader.PlayerHooks.UpdateVanityAccessories (Player player) static
Definition at line 383 of file PlayerHooks.cs.
{
            foreach (int index in HookUpdateVanityAccessories.arr) {
                player.modPlayers[index].UpdateVanityAccessories();
            }
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookUpdateVanityAccessories.
UseTimeMultiplier()
static float Terraria.ModLoader.PlayerHooks.UseTimeMultiplier (Player player, Item item) static
Definition at line 512 of file PlayerHooks.cs.
{
            float multiplier = 1f;
            if (item.IsAir) return multiplier;
            foreach (int index in HookUseTimeMultiplier.arr) {
                multiplier *= player.modPlayers[index].UseTimeMultiplier(item);
            }
            return multiplier;
        }
References Terraria.ModLoader.PlayerHooks.HookList.arr, and Terraria.ModLoader.PlayerHooks.HookUseTimeMultiplier.
Referenced by Terraria.ModLoader.PlayerHooks.TotalUseTimeMultiplier().
Member Data Documentation
HookAnglerQuestReward
HookList Terraria.ModLoader.PlayerHooks.HookAnglerQuestReward = AddHook<Action<float, List<Item>>>(p => p.AnglerQuestReward) static private
Definition at line 934 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.AnglerQuestReward().
HookCanBeHitByNPC
HookList Terraria.ModLoader.PlayerHooks.HookCanBeHitByNPC = AddHook<DelegateCanBeHitByNPC>(p => p.CanBeHitByNPC) static private
Definition at line 853 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.CanBeHitByNPC().
HookCanBeHitByProjectile
HookList Terraria.ModLoader.PlayerHooks.HookCanBeHitByProjectile = AddHook<Func<Projectile, bool>>(p => p.CanBeHitByProjectile) static private
Definition at line 881 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.CanBeHitByProjectile().
HookCanBuyItem
HookList Terraria.ModLoader.PlayerHooks.HookCanBuyItem = AddHook<Func<NPC, Item[], Item, bool>>(p => p.CanBuyItem) static private
Definition at line 1168 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.CanBuyItem().
HookCanHitNPC
HookList Terraria.ModLoader.PlayerHooks.HookCanHitNPC = AddHook<Func<Item, NPC, bool?>>(p => p.CanHitNPC) static private
Definition at line 715 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.CanHitNPC().
HookCanHitNPCWithProj
HookList Terraria.ModLoader.PlayerHooks.HookCanHitNPCWithProj = AddHook<Func<Projectile, NPC, bool?>>(p => p.CanHitNPCWithProj) static private
Definition at line 748 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.CanHitNPCWithProj().
HookCanHitPvp
HookList Terraria.ModLoader.PlayerHooks.HookCanHitPvp = AddHook<Func<Item, Player, bool>>(p => p.CanHitPvp) static private
Definition at line 793 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.CanHitPvp().
HookCanHitPvpWithProj
HookList Terraria.ModLoader.PlayerHooks.HookCanHitPvpWithProj = AddHook<Func<Projectile, Player, bool>>(p => p.CanHitPvpWithProj) static private
Definition at line 821 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.CanHitPvpWithProj().
HookCanSellItem
HookList Terraria.ModLoader.PlayerHooks.HookCanSellItem = AddHook<Func<NPC, Item[], Item, bool>>(p => p.CanSellItem) static private
Definition at line 1149 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.CanSellItem().
HookCatchFish
HookList Terraria.ModLoader.PlayerHooks.HookCatchFish = AddHook<DelegateCatchFish>(p => p.CatchFish) static private
Definition at line 910 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.CatchFish().
HookClientClone
HookList Terraria.ModLoader.PlayerHooks.HookClientClone = AddHook<Action<ModPlayer>>(p => p.clientClone) static private
Definition at line 270 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.clientClone().
HookConsumeAmmo
HookList Terraria.ModLoader.PlayerHooks.HookConsumeAmmo = AddHook<Func<Item, Item, bool>>(p => p.ConsumeAmmo) static private
Definition at line 669 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.ConsumeAmmo().
HookCopyCustomBiomesTo
HookList Terraria.ModLoader.PlayerHooks.HookCopyCustomBiomesTo = AddHook<Action<Player>>(p => p.CopyCustomBiomesTo) static private
Definition at line 193 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.CopyCustomBiomesTo().
HookCustomBiomesMatch
HookList Terraria.ModLoader.PlayerHooks.HookCustomBiomesMatch = AddHook<Func<Player, bool>>(p => p.CustomBiomesMatch) static private
Definition at line 182 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.CustomBiomesMatch().
HookDrawEffects
HookList Terraria.ModLoader.PlayerHooks.HookDrawEffects = AddHook<DelegateDrawEffects>(p => p.DrawEffects) static private
Definition at line 951 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.DrawEffects().
HookFrameEffects
HookList Terraria.ModLoader.PlayerHooks.HookFrameEffects = AddHook<Action>(p => p.FrameEffects) static private
Definition at line 429 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.FrameEffects().
HookGetDyeTraderReward
HookList Terraria.ModLoader.PlayerHooks.HookGetDyeTraderReward = AddHook<Action<List<int>>>(p => p.GetDyeTraderReward) static private
Definition at line 942 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.GetDyeTraderReward().
HookGetFishingLevel
HookList Terraria.ModLoader.PlayerHooks.HookGetFishingLevel = AddHook<DelegateGetFishingLevel>(p => p.GetFishingLevel) static private
Definition at line 926 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.GetFishingLevel().
HookGetHealLife
HookList Terraria.ModLoader.PlayerHooks.HookGetHealLife = AddHook<DelegateGetHealLife>(p => p.GetHealLife) static private
Definition at line 550 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.GetHealLife().
HookGetHealMana
HookList Terraria.ModLoader.PlayerHooks.HookGetHealMana = AddHook<DelegateGetHealMana>(p => p.GetHealMana) static private
Definition at line 562 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.GetHealMana().
HookGetMapBackgroundImage
HookList Terraria.ModLoader.PlayerHooks.HookGetMapBackgroundImage = AddHook<Func<Texture2D>>(p => p.GetMapBackgroundImage) static private
Definition at line 294 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.GetMapBackgroundImage().
HookGetWeaponCrit
HookList Terraria.ModLoader.PlayerHooks.HookGetWeaponCrit = AddHook<DelegateGetWeaponCrit>(p => p.GetWeaponCrit) static private
Definition at line 660 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.GetWeaponCrit().
HookGetWeaponDamage
HookList Terraria.ModLoader.PlayerHooks.HookGetWeaponDamage = AddHook<DelegateGetWeaponDamage>(p => p.GetWeaponDamage) static private
Definition at line 609 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.GetWeaponDamage().
HookGetWeaponKnockback
HookList Terraria.ModLoader.PlayerHooks.HookGetWeaponKnockback = AddHook<DelegateGetWeaponKnockback>(p => p.GetWeaponKnockback) static private
Definition at line 648 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.GetWeaponKnockback().
HookHurt
HookList Terraria.ModLoader.PlayerHooks.HookHurt = AddHook<Action<bool, bool, double, int, bool>>(p => p.Hurt) static private
Definition at line 453 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.Hurt().
HookKill
HookList Terraria.ModLoader.PlayerHooks.HookKill = AddHook<Action<double, int, bool, PlayerDeathReason>>(p => p.Kill) static private
Definition at line 484 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.Kill().
HookMeleeEffects
HookList Terraria.ModLoader.PlayerHooks.HookMeleeEffects = AddHook<Action<Item, Rectangle>>(p => p.MeleeEffects) static private
Definition at line 699 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.MeleeEffects().
HookMeleeSpeedMultiplier
HookList Terraria.ModLoader.PlayerHooks.HookMeleeSpeedMultiplier = AddHook<Func<Item, float>>(p => p.MeleeSpeedMultiplier) static private
Definition at line 529 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.MeleeSpeedMultiplier().
HookModifyDrawHeadLayers
HookList Terraria.ModLoader.PlayerHooks.HookModifyDrawHeadLayers = AddHook<Action<List<PlayerHeadLayer>>>(p => p.ModifyDrawHeadLayers) static private
Definition at line 1023 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.GetDrawHeadLayers().
HookModifyDrawInfo
HookList Terraria.ModLoader.PlayerHooks.HookModifyDrawInfo = AddHook<DelegateModifyDrawInfo>(p => p.ModifyDrawInfo) static private
Definition at line 961 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.ModifyDrawInfo().
HookModifyDrawLayers
HookList Terraria.ModLoader.PlayerHooks.HookModifyDrawLayers = AddHook<Action<List<PlayerLayer>>>(p => p.ModifyDrawLayers) static private
Definition at line 970 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.GetDrawLayers().
HookModifyHitByNPC
HookList Terraria.ModLoader.PlayerHooks.HookModifyHitByNPC = AddHook<DelegateModifyHitByNPC>(p => p.ModifyHitByNPC) static private
Definition at line 865 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.ModifyHitByNPC().
HookModifyHitByProjectile
HookList Terraria.ModLoader.PlayerHooks.HookModifyHitByProjectile = AddHook<DelegateModifyHitByProjectile>(p => p.ModifyHitByProjectile) static private
Definition at line 893 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.ModifyHitByProjectile().
HookModifyHitNPC
HookList Terraria.ModLoader.PlayerHooks.HookModifyHitNPC = AddHook<DelegateModifyHitNPC>(p => p.ModifyHitNPC) static private
Definition at line 732 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.ModifyHitNPC().
HookModifyHitNPCWithProj
HookList Terraria.ModLoader.PlayerHooks.HookModifyHitNPCWithProj = AddHook<DelegateModifyHitNPCWithProj>(p => p.ModifyHitNPCWithProj) static private
Definition at line 769 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.ModifyHitNPCWithProj().
HookModifyHitPvp
HookList Terraria.ModLoader.PlayerHooks.HookModifyHitPvp = AddHook<DelegateModifyHitPvp>(p => p.ModifyHitPvp) static private
Definition at line 805 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.ModifyHitPvp().
HookModifyHitPvpWithProj
HookList Terraria.ModLoader.PlayerHooks.HookModifyHitPvpWithProj = AddHook<DelegateModifyHitPvpWithProj>(p => p.ModifyHitPvpWithProj) static private
Definition at line 834 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.ModifyHitPvpWithProj().
HookModifyManaCost
HookList Terraria.ModLoader.PlayerHooks.HookModifyManaCost = AddHook<DelegateModifyManaCost>(p => p.ModifyManaCost) static private
Definition at line 574 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.ModifyManaCost().
HookModifyNurseHeal
HookList Terraria.ModLoader.PlayerHooks.HookModifyNurseHeal = AddHook<DelegateModifyNurseHeal>(p => p.ModifyNurseHeal) static private
Definition at line 1179 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.ModifyNurseHeal().
HookModifyNursePrice
HookList Terraria.ModLoader.PlayerHooks.HookModifyNursePrice = AddHook<DelegateModifyNursePrice>(p => p.ModifyNursePrice) static private
Definition at line 1190 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.ModifyNursePrice().
HookModifyScreenPosition
HookList Terraria.ModLoader.PlayerHooks.HookModifyScreenPosition = AddHook<Action>(p => p.ModifyScreenPosition) static private
Definition at line 1042 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.ModifyScreenPosition().
HookModifyWeaponDamage
HookList Terraria.ModLoader.PlayerHooks.HookModifyWeaponDamage = AddHook<DelegateModifyWeaponDamage>(p => p.ModifyWeaponDamage) static private
Definition at line 623 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.ModifyWeaponDamage().
HookModifyWeaponDamageOld
HookList Terraria.ModLoader.PlayerHooks.HookModifyWeaponDamageOld = AddHook<DelegateModifyWeaponDamage>(p => p.ModifyWeaponDamage) static private
Definition at line 621 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.ModifyWeaponDamage().
HookModifyZoom
HookList Terraria.ModLoader.PlayerHooks.HookModifyZoom = AddHook<DelegateModifyZoom>(p => p.ModifyZoom) static private
Definition at line 1051 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.ModifyZoom().
HookNaturalLifeRegen
HookList Terraria.ModLoader.PlayerHooks.HookNaturalLifeRegen = AddHook<DelegateNaturalLifeRegen>(p => p.NaturalLifeRegen) static private
Definition at line 324 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.NaturalLifeRegen().
HookOnConsumeAmmo
HookList Terraria.ModLoader.PlayerHooks.HookOnConsumeAmmo = AddHook<Action<Item, Item>>(p => p.OnConsumeAmmo) static private
Definition at line 680 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.OnConsumeAmmo().
HookOnConsumeMana
HookList Terraria.ModLoader.PlayerHooks.HookOnConsumeMana = AddHook<Action<Item, int>>(p => p.OnConsumeMana) static private
Definition at line 596 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.OnConsumeMana().
HookOnEnterWorld
HookList Terraria.ModLoader.PlayerHooks.HookOnEnterWorld = AddHook<Action<Player>>(p => p.OnEnterWorld) static private
Definition at line 1077 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.OnEnterWorld().
HookOnHitAnything
HookList Terraria.ModLoader.PlayerHooks.HookOnHitAnything = AddHook<Action<float, float, Entity>>(p => p.OnHitAnything) static private
Definition at line 707 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.OnHitAnything().
HookOnHitByNPC
HookList Terraria.ModLoader.PlayerHooks.HookOnHitByNPC = AddHook<Action<NPC, int, bool>>(p => p.OnHitByNPC) static private
Definition at line 873 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.OnHitByNPC().
HookOnHitByProjectile
HookList Terraria.ModLoader.PlayerHooks.HookOnHitByProjectile = AddHook<Action<Projectile, int, bool>>(p => p.OnHitByProjectile) static private
Definition at line 901 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.OnHitByProjectile().
HookOnHitNPC
HookList Terraria.ModLoader.PlayerHooks.HookOnHitNPC = AddHook<Action<Item, NPC, int, float, bool>>(p => p.OnHitNPC) static private
Definition at line 740 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.OnHitNPC().
HookOnHitNPCWithProj
HookList Terraria.ModLoader.PlayerHooks.HookOnHitNPCWithProj = AddHook<Action<Projectile, NPC, int, float, bool>>(p => p.OnHitNPCWithProj) static private
Definition at line 781 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.OnHitNPCWithProj().
HookOnHitPvp
HookList Terraria.ModLoader.PlayerHooks.HookOnHitPvp = AddHook<Action<Item, Player, int, bool>>(p => p.OnHitPvp) static private
Definition at line 813 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.OnHitPvp().
HookOnHitPvpWithProj
HookList Terraria.ModLoader.PlayerHooks.HookOnHitPvpWithProj = AddHook<Action<Projectile, Player, int, bool>>(p => p.OnHitPvpWithProj) static private
Definition at line 843 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.OnHitPvpWithProj().
HookOnMissingMana
HookList Terraria.ModLoader.PlayerHooks.HookOnMissingMana = AddHook<Action<Item, int>>(p => p.OnMissingMana) static private
Definition at line 585 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.OnMissingMana().
HookOnRespawn
HookList Terraria.ModLoader.PlayerHooks.HookOnRespawn = AddHook<Action<Player>>(p => p.OnRespawn) static private
Definition at line 1087 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.OnRespawn().
HookPlayerConnect
HookList Terraria.ModLoader.PlayerHooks.HookPlayerConnect = AddHook<Action<Player>>(p => p.PlayerConnect) static private
Definition at line 1059 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.PlayerConnect().
HookPlayerDisconnect
HookList Terraria.ModLoader.PlayerHooks.HookPlayerDisconnect = AddHook<Action<Player>>(p => p.PlayerDisconnect) static private
Definition at line 1068 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.PlayerDisconnect().
HookPostBuyItem
HookList Terraria.ModLoader.PlayerHooks.HookPostBuyItem = AddHook<Action<NPC, Item[], Item>>(p => p.PostBuyItem) static private
Definition at line 1160 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.PostBuyItem().
HookPostHurt
HookList Terraria.ModLoader.PlayerHooks.HookPostHurt = AddHook<Action<bool, bool, double, int, bool>>(p => p.PostHurt) static private
Definition at line 461 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.PostHurt().
HookPostItemCheck
HookList Terraria.ModLoader.PlayerHooks.HookPostItemCheck = AddHook<Action>(p => p.PostItemCheck) static private
Definition at line 502 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.PostItemCheck().
HookPostNurseHeal
HookList Terraria.ModLoader.PlayerHooks.HookPostNurseHeal = AddHook<Action<NPC, int, bool, int>>(p => p.PostNurseHeal) static private
Definition at line 1198 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.PostNurseHeal().
HookPostSavePlayer
HookList Terraria.ModLoader.PlayerHooks.HookPostSavePlayer = AddHook<Action>(p => p.PostSavePlayer) static private
Definition at line 166 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.PostSavePlayer().
HookPostSellItem
HookList Terraria.ModLoader.PlayerHooks.HookPostSellItem = AddHook<Action<NPC, Item[], Item>>(p => p.PostSellItem) static private
Definition at line 1141 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.PostSellItem().
HookPostUpdate
HookList Terraria.ModLoader.PlayerHooks.HookPostUpdate = AddHook<Action>(p => p.PostUpdate) static private
Definition at line 421 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.PostUpdate().
HookPostUpdateBuffs
HookList Terraria.ModLoader.PlayerHooks.HookPostUpdateBuffs = AddHook<Action>(p => p.PostUpdateBuffs) static private
Definition at line 364 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.PostUpdateBuffs().
HookPostUpdateEquips
HookList Terraria.ModLoader.PlayerHooks.HookPostUpdateEquips = AddHook<Action>(p => p.PostUpdateEquips) static private
Definition at line 389 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.PostUpdateEquips().
HookPostUpdateMiscEffects
HookList Terraria.ModLoader.PlayerHooks.HookPostUpdateMiscEffects = AddHook<Action>(p => p.PostUpdateMiscEffects) static private
Definition at line 397 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.PostUpdateMiscEffects().
HookPostUpdateRunSpeeds
HookList Terraria.ModLoader.PlayerHooks.HookPostUpdateRunSpeeds = AddHook<Action>(p => p.PostUpdateRunSpeeds) static private
Definition at line 405 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.PostUpdateRunSpeeds().
HookPreHurt
HookList Terraria.ModLoader.PlayerHooks.HookPreHurt = AddHook<DelegatePreHurt>(p => p.PreHurt) static private
Definition at line 439 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.PreHurt().
HookPreItemCheck
HookList Terraria.ModLoader.PlayerHooks.HookPreItemCheck = AddHook<Func<bool>>(p => p.PreItemCheck) static private
Definition at line 492 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.PreItemCheck().
HookPreKill
HookList Terraria.ModLoader.PlayerHooks.HookPreKill = AddHook<DelegatePreKill>(p => p.PreKill) static private
Definition at line 471 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.PreKill().
HookPreSavePlayer
HookList Terraria.ModLoader.PlayerHooks.HookPreSavePlayer = AddHook<Action>(p => p.PreSavePlayer) static private
Definition at line 158 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.PreSavePlayer().
HookPreUpdate
HookList Terraria.ModLoader.PlayerHooks.HookPreUpdate = AddHook<Action>(p => p.PreUpdate) static private
Definition at line 340 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.PreUpdate().
HookPreUpdateBuffs
HookList Terraria.ModLoader.PlayerHooks.HookPreUpdateBuffs = AddHook<Action>(p => p.PreUpdateBuffs) static private
Definition at line 356 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.PreUpdateBuffs().
HookPreUpdateMovement
HookList Terraria.ModLoader.PlayerHooks.HookPreUpdateMovement = AddHook<Action>(p => p.PreUpdateMovement) static private
Definition at line 413 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.PreUpdateMovement().
HookProcessTriggers
HookList Terraria.ModLoader.PlayerHooks.HookProcessTriggers = AddHook<Action<TriggersSet>>(p => p.ProcessTriggers) static private
Definition at line 639 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.ProcessTriggers().
HookResetEffects
HookList Terraria.ModLoader.PlayerHooks.HookResetEffects = AddHook<Action>(p => p.ResetEffects) static private
Definition at line 61 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.ResetEffects().
hooks
List<HookList> Terraria.ModLoader.PlayerHooks.hooks = new List<HookList>() static private
Definition at line 34 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.AddHook< F >().
HookSendClientChanges
HookList Terraria.ModLoader.PlayerHooks.HookSendClientChanges = AddHook<Action<ModPlayer>>(p => p.SendClientChanges) static private
Definition at line 286 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.SendClientChanges().
HookSendCustomBiomes
HookList Terraria.ModLoader.PlayerHooks.HookSendCustomBiomes = AddHook<Action<BinaryWriter>>(p => p.SendCustomBiomes) static private
Definition at line 201 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.SendCustomBiomes().
HookSetControls
HookList Terraria.ModLoader.PlayerHooks.HookSetControls = AddHook<Action>(p => p.SetControls) static private
Definition at line 348 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.SetControls().
HookSetupStartInventory
HookList Terraria.ModLoader.PlayerHooks.HookSetupStartInventory = AddHook<Action<List<Item>, bool>>(p => p.SetupStartInventory) static private
Definition at line 77 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.SetupStartInventory().
HookSetupStartInventoryOld
HookList Terraria.ModLoader.PlayerHooks.HookSetupStartInventoryOld = AddHook<Action<List<Item>>>(p => p.SetupStartInventory) static private
Definition at line 78 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.SetupStartInventory().
HookShiftClickSlot
HookList Terraria.ModLoader.PlayerHooks.HookShiftClickSlot = AddHook<Func<Item[], int, int, bool>>(p => p.ShiftClickSlot) static private
Definition at line 1095 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.ShiftClickSlot().
HookShoot
HookList Terraria.ModLoader.PlayerHooks.HookShoot = AddHook<DelegateShoot>(p => p.Shoot) static private
Definition at line 688 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.Shoot().
HookSyncPlayer
HookList Terraria.ModLoader.PlayerHooks.HookSyncPlayer = AddHook<Action<int, int, bool>>(p => p.SyncPlayer) static private
Definition at line 278 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.SyncPlayer().
HookUpdateAutopause
HookList Terraria.ModLoader.PlayerHooks.HookUpdateAutopause = AddHook<Action>(p => p.UpdateAutopause) static private
Definition at line 332 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.UpdateAutopause().
HookUpdateBadLifeRegen
HookList Terraria.ModLoader.PlayerHooks.HookUpdateBadLifeRegen = AddHook<Action>(p => p.UpdateBadLifeRegen) static private
Definition at line 307 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.UpdateBadLifeRegen().
HookUpdateBiomes
HookList Terraria.ModLoader.PlayerHooks.HookUpdateBiomes = AddHook<Action>(p => p.UpdateBiomes) static private
Definition at line 174 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.UpdateBiomes().
HookUpdateBiomeVisuals
HookList Terraria.ModLoader.PlayerHooks.HookUpdateBiomeVisuals = AddHook<Action>(p => p.UpdateBiomeVisuals) static private
Definition at line 262 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.UpdateBiomeVisuals().
HookUpdateDead
HookList Terraria.ModLoader.PlayerHooks.HookUpdateDead = AddHook<Action>(p => p.UpdateDead) static private
Definition at line 69 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.UpdateDead().
HookUpdateEquips
HookList Terraria.ModLoader.PlayerHooks.HookUpdateEquips = AddHook<DelegateUpdateEquips>(p => p.UpdateEquips) static private
Definition at line 373 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.UpdateEquips().
HookUpdateLifeRegen
HookList Terraria.ModLoader.PlayerHooks.HookUpdateLifeRegen = AddHook<Action>(p => p.UpdateLifeRegen) static private
Definition at line 315 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.UpdateLifeRegen().
HookUpdateVanityAccessories
HookList Terraria.ModLoader.PlayerHooks.HookUpdateVanityAccessories = AddHook<Action>(p => p.UpdateVanityAccessories) static private
Definition at line 381 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.UpdateVanityAccessories().
HookUseTimeMultiplier
HookList Terraria.ModLoader.PlayerHooks.HookUseTimeMultiplier = AddHook<Func<Item, float>>(p => p.UseTimeMultiplier) static private
Definition at line 510 of file PlayerHooks.cs.
Referenced by Terraria.ModLoader.PlayerHooks.UseTimeMultiplier().
players
readonly IList<ModPlayer> Terraria.ModLoader.PlayerHooks.players = new List<ModPlayer>() static private
Definition at line 22 of file PlayerHooks.cs.