version: "2.0"
services:
  tml:
    build:
      context: .
      args:
        UID: 1000
        GID: 1000
    tty: true
    stdin_open: true
    ports:
      - 7777:7777
    volumes:
      - "./Terraria:/terraria"
