Terraria ModLoader: Terraria.ModLoader.EquipLoader Class Reference
Terraria.ModLoader.EquipLoader Class Reference
This serves as a central place to store equipment slots and their corresponding textures. You will use this to obtain the IDs for your equipment textures.
Static Public Member Functions
static EquipTexture GetEquipTexture (EquipType type, int slot)
Gets the equipment texture for the specified equipment type and ID.
Static Public Attributes
static readonly EquipType [] EquipTypes = (EquipType[])Enum.GetValues(typeof(EquipType))
Static Private Member Functions
static EquipLoader ()
Static Private Attributes
static readonly IDictionary< EquipType, int > nextEquip = new Dictionary<EquipType, int>()
Detailed Description
This serves as a central place to store equipment slots and their corresponding textures. You will use this to obtain the IDs for your equipment textures.
Definition at line 11 of file EquipLoader.cs.
Constructor & Destructor Documentation
EquipLoader()
static Terraria.ModLoader.EquipLoader.EquipLoader () static private
Definition at line 34 of file EquipLoader.cs.
{
             foreach (EquipType type in EquipTypes) {
                 nextEquip[type] = GetNumVanilla(type);
                 equipTextures[type] = new Dictionary<int, EquipTexture>();
             }
             slotToId[EquipType.Head] = new Dictionary<int, int>();
             slotToId[EquipType.Body] = new Dictionary<int, int>();
             slotToId[EquipType.Legs] = new Dictionary<int, int>();
         }
Member Function Documentation
GetEquipTexture()
static EquipTexture Terraria.ModLoader.EquipLoader.GetEquipTexture (EquipType type, int slot) static
Gets the equipment texture for the specified equipment type and ID.
Parameters
type
slot
Returns
Definition at line 56 of file EquipLoader.cs.
References Terraria.ModLoader.ModContent.GetTexture(), Terraria.ModLoader.Item, and Terraria.ModLoader.EquipTexture.Texture.
Referenced by Terraria.ModLoader.ItemLoader.ArmorArmGlowMask(), Terraria.ModLoader.ItemLoader.ArmorSetShadows(), Terraria.ModLoader.ItemLoader.DrawArmorColor(), Terraria.ModLoader.ItemLoader.DrawBody(), Terraria.ModLoader.ItemLoader.DrawHair(), Terraria.ModLoader.ItemLoader.DrawHands(), Terraria.ModLoader.ItemLoader.DrawHead(), Terraria.ModLoader.ItemLoader.DrawLegs(), Terraria.ModLoader.ItemLoader.GetWing(), Terraria.ModLoader.ItemLoader.HorizontalWingSpeeds(), Terraria.ModLoader.ModContent.MusicExists(), Terraria.ModLoader.ItemLoader.PreUpdateVanitySet(), Terraria.ModLoader.ItemLoader.SetMatch(), Terraria.ModLoader.ItemLoader.UpdateVanity(), Terraria.ModLoader.ItemLoader.UpdateVanitySet(), Terraria.ModLoader.ItemLoader.VerticalWingSpeeds(), and Terraria.ModLoader.ItemLoader.WingUpdate().
{
             EquipTexture texture;
             return equipTextures[type].TryGetValue(slot, out texture) ? texture : null;
         }
Member Data Documentation
EquipTypes
readonly EquipType [] Terraria.ModLoader.EquipLoader.EquipTypes = (EquipType[])Enum.GetValues(typeof(EquipType)) static
Definition at line 32 of file EquipLoader.cs.
Referenced by Terraria.ModLoader.ItemLoader.UpdateVanity().
nextEquip
readonly IDictionary<EquipType, int> Terraria.ModLoader.EquipLoader.nextEquip = new Dictionary<EquipType, int>() static private
Definition at line 14 of file EquipLoader.cs.