
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\tModLoader.targets" />
  <PropertyGroup>
    <AssemblyName>ExampleMod</AssemblyName>
    <LangVersion>latest</LangVersion>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Old\**" />
    <EmbeddedResource Remove="Old\**" />
    <None Remove="Old\**" />
  </ItemGroup>
</Project>