//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tModCodeAssist {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tModCodeAssist.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors when incorrect ID type is used.
        /// </summary>
        internal static string BadIDTypeDescription {
            get {
                return ResourceManager.GetString("BadIDTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression &quot;{0}&quot; is not type of {1}.
        /// </summary>
        internal static string BadIDTypeMessageFormat {
            get {
                return ResourceManager.GetString("BadIDTypeMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect ID type is used.
        /// </summary>
        internal static string BadIDTypeTitle {
            get {
                return ResourceManager.GetString("BadIDTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes magic numbers into appropriate ID values.
        /// </summary>
        internal static string ChangeMagicNumberToIDDescription {
            get {
                return ResourceManager.GetString("ChangeMagicNumberToIDDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number {0} should be changed to {1} for readability.
        /// </summary>
        internal static string ChangeMagicNumberToIDMessageFormat {
            get {
                return ResourceManager.GetString("ChangeMagicNumberToIDMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change magic numbers into appropriate ID values.
        /// </summary>
        internal static string ChangeMagicNumberToIDTitle {
            get {
                return ResourceManager.GetString("ChangeMagicNumberToIDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors when class name or namespace collides with an existing Terraria type name.
        /// </summary>
        internal static string CommonCollisionNameDescription {
            get {
                return ResourceManager.GetString("CommonCollisionNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class name or namespace &quot;{0}&quot; from &quot;{1}&quot; collides with an existing Terraria type.
        /// </summary>
        internal static string CommonCollisionNameMessageFormat {
            get {
                return ResourceManager.GetString("CommonCollisionNameMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common type collision name.
        /// </summary>
        internal static string CommonCollisionNameTitle {
            get {
                return ResourceManager.GetString("CommonCollisionNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplifies local (client-side) player access.
        /// </summary>
        internal static string SimplifyLocalPlayerDescription {
            get {
                return ResourceManager.GetString("SimplifyLocalPlayerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression &quot;{0}&quot; can be simplified for readability.
        /// </summary>
        internal static string SimplifyLocalPlayerMessageFormat {
            get {
                return ResourceManager.GetString("SimplifyLocalPlayerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplify local (client-side) player access.
        /// </summary>
        internal static string SimplifyLocalPlayerTitle {
            get {
                return ResourceManager.GetString("SimplifyLocalPlayerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplifies common UnifiedRandom usage patterns.
        /// </summary>
        internal static string SimplifyUnifiedRandomDescription {
            get {
                return ResourceManager.GetString("SimplifyUnifiedRandomDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression &quot;{0}&quot; can be simplified for readability.
        /// </summary>
        internal static string SimplifyUnifiedRandomMessageFormat {
            get {
                return ResourceManager.GetString("SimplifyUnifiedRandomMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplify common UnifiedRandom usage patterns.
        /// </summary>
        internal static string SimplifyUnifiedRandomTitle {
            get {
                return ResourceManager.GetString("SimplifyUnifiedRandomTitle", resourceCulture);
            }
        }
    }
}
