name: Wiki Changed Discord Notification

on:
  gollum

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: 'oznu/gh-wiki-edit-discord-notification@main'
        with:
          discord-webhook-url: ${{ secrets.DISCORD_WEBHOOK_GITHUB }}
          discord-username: GitHub-wiki
